### ISSUE TITLE
"geth import" uses too much RAM

### ISSUE THREAD

**Issue by arhuaco** [ethereum/go-ethereum#1018]
This is how RAM is used  to import 358840 blocks:

![Memory usage](http://i.imgur.com/2d809MZ.png)

**Comment by karalabe** [comment]
That spike I'm guessing is aroung 295K, where there are a lot of huge transactions or whatnot inside the blocks and even importing them takes a 30-60x more time that the other empty blocks.

However, I myself would not expect linear memory growth (and was something I wanted to investigate at a certain point), because it's a time bomb this way. We should definitely look into this.

**Comment by bas-vk** [comment]
I don't think this is a problem. Geth manages its memory actually quit well but go's scavenger routine will simple hold on to the memory (as most GC languages). Probably it will return the memory to the os when the environment is low on memory since some people have geth running on a raspberry.

To illustrate this I have logged the actual heap usage of geth during a full sync
<img src="http://i61.tinypic.com/i6iaux.jpg">

You can see that most of the memory (yellow line) isn't used and also not returned (purple line) to the OS. We could force it to return the memory to the os with `runtime.debug.FreeOSMemory()` but I don't think this is necessary.

**Comment by arhuaco** [comment]
I am not writing about a full sync. "geth import" is what causes the issue with too much RAM usage.

**Comment by karalabe** [comment]
This was solved a while ago. Please reopen if you still experience issues.
