### ISSUE TITLE
eth_getFilterLogs takes ~15s and 100% CPU to get logs from block 0

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#1038]
Getting past logs using a filter created like the following:
```
{"jsonrpc":"2.0","method":"eth_newFilter","params":[{"topics":["0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c"],"address":"0xbd999ac9af99055bdbc8b0fe564b64381513fa99","fromBlock":"0x0","toBlock":"latest"}],"id":8}
```

Takes up to 15s and 100% CPU for all current 370 000 blocks to scan.

If a lot of dapps request filters like this its very likely that the node crashes or makes the computer unusable.

We need to look into ways of improving the performance here.

**Comment by caktux** [comment]
I had to limit filtering events to a few hundred blocks (forget it with the current 700,000+ blocks with tx spam), and it still takes a few seconds for those calls, so a big +1 on better performance here

**Comment by tgerring** [comment]
It's unlikely that we can get near-instant performance as you want, even with an explicit index on all the predicates. The way you're querying the data structure will naturally result in what the relational world calls a "table scan". These are always slow because the entire data structure has to be scanned form beginning to end. Traditionally, this is overcome with the creation of specific indexes to meet the type of predicates being requested.

This is further complicated by the fact that we're essentially using a key/value store, so we can't necessarily expect the same kind of performance we would from a relational search. Even if we had the structure normalised in to a relational database, we would have to manually create indexes for the most common types of queries, which results in a degradation of write performance (due to needing to update al the indexes). We could build something like thing in a KV store, of course, but it's unlikely that we'd build it to cover all use cases of "earliest to latest" and people would STILL run into scanning behaviour.

What is the use case of fetching all historical logs that can't be met by scanning the last epoch or so?

**Comment by caktux** [comment]
If scanning the last epoch can be done relatively well, that'd be perfect. This is for historical price data and listing specific transactions data. As it stands I have to limit this to a 1 hour range (300 blocks or so), filtering on indexed event data only, but from what you're saying I doubt those indexes are currently optimized; there could be some gains to be made there.

**Comment by frozeman** [comment]
When you start a dapp for the second time on another computer, or restore e.g. a wallet contract from a backup, you want to get all past transactions, which would require a full scan.

If we would index the logs by address, which created the log, we would are lady minify the to scanlable documents to a fraction of the whole chain.

Most logs are anyway filtered by specifying an address, only in som rare cases you filter only by topics, without and address.

**Comment by tgerring** [comment]
> If we would index the logs by address

This is a tricky proposition. If we create a data structure that allows the lookup of log by address, do we have any link back from the log to the generating transaction or block? In general, I think we need to take a hard look at what explicit references we should store to make lookup from child structure to parent structure easier.

Currently, in the "extradb", we store full context for a transaction (i.e. tx index) or receipt (i.e. bloom), but this is actually unnecessary if we store smartly-indexed references since the data can be quickly looked up in near-real-time with leveldb's range queries.

**Comment by karalabe** [comment]
@obscuren This was sorted out by the log mipmaps right? If so, please close.
