### ISSUE TITLE
add missing tests

### ISSUE THREAD

**Issue by CJentzsch** [ethereum/go-ethereum#1052]
some tests are skipped (should be optional by using a command line flag), some are not used and one old test pass although it shouldn't:

*VM tests*

- [x] vmPerformance is skipped
- [x] vmSystemOperationsTest is not used
- [x] all tests in https://github.com/ethereum/tests/tree/develop/VMTests/RandomTests are not used

*State Tests*

- [x] MemoryStressTest is skipped
- [x] QuadraticComplexity is skipped
- [x] all tests in https://github.com/ethereum/tests/tree/develop/StateTests/RandomTests are not used

*BlockChainTests*

- [x] bcJS_API_Test.json is an old deprecated test with the wrong format, I forgot to delete it, will do so soon. But you seem to pass it. Please check your BlockChainTest implementation and make sure you dont pass it, then I will delete the wrong test.

- [x] bcWallet is not used

**Comment by obscuren** [comment]
See https://github.com/ethereum/go-ethereum/pull/1043

@Gustav-Simonsson address the blockchain tests please

**Comment by Gustav-Simonsson** [comment]
For the record, the reason Go passes bcJS_API_Test.json is due to https://github.com/ethereum/tests/wiki/Blockchain-Tests-II specifying
```
If the client concludes that the block is invalid, it should verify that no blockHeader, transactions or uncleHeaders object is present in the test. The client is expected to iterate through the list of blocks and ignore invalid blocks.
```
Go fails parsing of the block RLP because the RLP is missing, thus it concludes the block is invalid, and checks for existence of blockheader field, which is missing. It then concludes that the block parsing is expected to fail, and considers the test successful.

This type of behavior can be avoided by directly specifying the expected test outcome with e.g. "result" : "rlp_parsing_fail" instead of using presence of fields as the indicator. That would also make it much easier to see at a glance what the expected outcome of the test is.

**Comment by CJentzsch** [comment]
so bcJS_API_Test issue is fine, the only thing missing now are the random VM- and StateTests.
