### ISSUE TITLE
Separate extra and dapp db

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#1053]
the `extra` database was meant for stuff which isn't important. Extra is now being used by receipts and transactions. DApps have access to this database through `db_XXXPut` and can overwrite entries. We need an extra db or remove the `get` and `put` methods.

**Comment by zelig** [comment]
the community indicated they rely on this feature. We shouldnt remove it:
suggestions:
* use another db: `dappDb` for dapps. 
* use a pattern to make sure different dapps would not collide - dapp-specific prefix. 
* could make it even more secure by explicitly having to 
* a way to prevent dapps reading each others db (maybe could require a nonce and a hash for each flush/transaction that is verified against a token you must supply your client on the command line or config file:

```
geth --dbsecrets ~/.ethereum/secrets.json  
```

then you need to send `db.get(nonce, result)` where `result = sha3(nonce|secret)` and secret is entered by the user and kept in memory by the dapp. Or some similar crypto :)

**Comment by frozeman** [comment]
My two cents:

Storing dapp data in the node is imho the wrong way, dapps should have their own mean of storing (local storage, extra db server). The node should only provide ways to communicate with the network.

(Even key management is questionable, but we will need it for mist in the near future)

If we find a working solution to deliver dapps, over different sub-domains (e.g. `mydapp.localhost`), then dapps have a way to "safely" store data and i would see no reason why to keep this extra db.

**Comment by zelig** [comment]
brilliant. as long as provide continuity of the feature.

**Comment by obscuren** [comment]
@bas-vk I remember you said you had an idea for local storage. Could you briefly describe?

**Comment by frozeman** [comment]
@zelig in this case people need to use local storage in browser/mist, so we would remove this db functions. For now i would just make it into a separate db and don't put more effort in it.. and leave the api as is

**Comment by bas-vk** [comment]
Its basically what @frozeman mentioned above. Each DApp should have its own storage and this is exactly what a html 5 container provides in the form of <a href=https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/Storage#localStorage">"local storage"</a>.

I have a webserver which serves pages strait from a zipfile without the need to extract them (easy to distribute). E.g. if you have `wallet.zip` and `exchange.zip` in some directory the webserver will create 2 subdomains `wallet.localhost` and `exchange.localhost` and serves files directly from those archives.

Due to the same origin policy both DApps cannot access each others local storage. Besides local storage the html 5 webcontainer also provides session storage which is not persisted to disk. DApp developers should be familiar with both techniques since they are not new an commonly used by modern webapplications.

So I would recommend removing both functions in geth and let web3 store the data in the local storage, or remove them entirely if we are willing to change the API. The same holds `db_putHex` and `db_getHex`?

**Comment by scottzer0** [comment]
perhaps this is unrealistic, but i'd like my DAPP to not rely on a local http server for delivery.  i'm trying to keep it's design very be-delivered-from-anywhere and only assume there's a local ethereum node (even that's flexible).  browser local storage is a solution for some of the persistent data i would like to store (mainly basic user prefs, contact/addresses aliases, etc), but my intention was to lean on the node's db to be further persistent (using other browsers, app origin domain changes, etc.)

i won't cry if support's remove, but that's my $0.02.

**Comment by niran** [comment]
Personally, my support for the feature is only because we're already using it. Long term, there are plenty of solutions for client side storage: localStorage in the browser, or for dapps what live outside of a browser as native or [Electron](http://electron.atom.io/) apps, the options are limitless. I'd support deprecating the API but keeping it around for six months or so.

**Comment by bas-vk** [comment]
I absolute can see why such a feature is useful for DApp developers but the current functions are not the correct way to do this. DApps can write to this local DB without any constraints and overwrite each others entries. If you rely on these functions it will fail on you at some time and will introduce vulnerabilities. Due to these problems the use of these functions is really limited and I recommend to remove them to prevent false assumptions. If you want to store key value entries in a reliable store there are other ways to do this.

**Comment by frozeman** [comment]
@scottzer0 if your dapp runs simply from the file protocol then they will run fine from our dapp delivery system :)
The advantage of delivering the dapps over a local server is that you can have routes, which allow you to share locations in you dapp, e.g. profiles, addresses, invite users to chats etc.
If you only use relative path you should be fine, if you use absolute path, you should be fine too.

concerning localstorage: Its a nice feature as its a local db, which is isolated from other dapps through its domino name (we are in the progress to figuring out how to do that). Its available in all browsers and you can simply port you dapp into any desktop app container like node webkit or electron.

Therefor i would recommend using local storage, but stay tuned until we can make a final decision.
