### ISSUE TITLE
Wont sync due to incorrect hashes from all peers

### ISSUE THREAD

**Issue by cjphilpot** [ethereum/go-ethereum#1075]
Neither my Ubuntu or OS X client will sync with the network now. Tried old versions of geth and am getting the same problem.

https://gist.github.com/cjphilpot/47459a51d3a989beb6dd

**Comment by obscuren** [comment]
@karalabe PTAL

**Comment by karalabe** [comment]
You are getting network timeouts. None of your peers seems to respond within the alloted 5 second window for a hash request. Are you sure you're not experiencing connectivity issues?

**Comment by karalabe** [comment]
Looking through the logs I can see that you actually do receive the requested hashes eventually, but after 10-15 seconds so they are discarded. That is imho too much for fetching some 64K of data. The reason we disconnect after 5 secs is that if your connectivity is otherwise good, but you have a shitty peer, then just switch over to somebody faster. The side effect is that if **your** connection is very weak, then you may have an issue hooking into the network.

Could you please check you internet connection, bandwidth, latency, etc, so maybe we can figure out what the best solution would be if there is indeed a problem to solve on our part.

**Comment by cjphilpot** [comment]
Thanks @karalabe! I rebooted my main router and things are syncing up again. It was strange because I wasn't experiencing any other connection problems with the Internet. Closing now. Thanks again for the explanation!

**Comment by obscuren** [comment]
Same things happens in China behind the Great Firewall :-|

**Comment by karalabe** [comment]
Hmm, so running through China adds that huge of a latency?

**Comment by obscuren** [comment]
Apparently

**Comment by obscuren** [comment]
It should be resolved when more nodes spawn in that area

**Comment by cjphilpot** [comment]
I think that is a big part of my problem too. Im in Bahrain and there are no other nodes anywhere around here.

**Comment by karalabe** [comment]
We should think about this a bit if we want to address it or not. One option would be to bump the timeouts a bit, but then you might get stuck behind a very very slow peer that's dripping data to you; another would be to somehow try and dynamically adjust the timeout (i.e. if all your peers are exhausted, maybe bump it a bit), but it could complicate things beyond necessity.
