### ISSUE TITLE
Synchronisation failed: peer is unknown or unhealthy

### ISSUE THREAD

**Issue by stephantual** [ethereum/go-ethereum#1127]
8951a03db39a2a877ada34c927d78352d465303e - buntu 14.04

I seem stuck at #452,458. I have 68 peers

I used the latest code (commit hash above) and rebuild the chain from scratch (wiped the .ethereum
folder, let it rebuild). 

```
I0527 16:14:22.454849    4677 sync.go:121] Synchronisation failed: no peers available or all peers tried for block download process
I0527 16:14:33.205811    4677 downloader.go:141] Unregister failed: peer is not registered
I0527 16:14:33.205836    4677 handler.go:102] Removal failed: peer is not registered
I0527 16:17:20.205844    4677 chain_manager.go:753] Bad block #446189 (38f5bbbffd74804820ffa4bab0cd540e9de229725afb98c1a7e57936f4a714bc)
I0527 16:17:20.205882    4677 chain_manager.go:754] gas used error (44532 / 160116)
I0527 16:17:20.243399    4677 sync.go:121] Synchronisation failed: block downloading cancelled (requested)
I0527 16:20:49.668373    4677 chain_manager.go:753] Bad block #446189 (38f5bbbffd74804820ffa4bab0cd540e9de229725afb98c1a7e57936f4a714bc)
I0527 16:20:49.668470    4677 chain_manager.go:754] gas used error (44532 / 160116)
I0527 16:20:49.945106    4677 sync.go:121] Synchronisation failed: no peers available or all peers tried for block download process
I0527 16:21:58.829693    4677 sync.go:121] Synchronisation failed: peer is unknown or unhealthy
I0527 16:22:15.601247    4677 sync.go:121] Synchronisation failed: peer is unknown or unhealthy
I0527 16:22:23.709149    4677 sync.go:121] Synchronisation failed: peer is unknown or unhealthy
I0527 16:23:07.554213    4677 downloader.go:141] Unregister failed: peer is not registered
I0527 16:23:07.554255    4677 handler.go:102] Removal failed: peer is not registered
I0527 16:25:14.855339    4677 downloader.go:141] Unregister failed: peer is not registered
I0527 16:25:14.855371    4677 handler.go:102] Removal failed: peer is not registered
> I0527 16:26:09.669673    4677 chain_manager.go:753] Bad block #446189 (38f5bbbffd74804820ffa4bab0cd540e9de229725afb98c1a7e57936f4a714bc)
I0527 16:26:09.669789    4677 chain_manager.go:754] gas used error (44532 / 160116)
I0527 16:26:09.859750    4677 sync.go:121] Synchronisation failed: no peers available or all peers tried for block download process
```

**Comment by MercStills** [comment]
I am stuck at #452,397 with same commit and OS.  I have 25 peers.

Similar log with repetitive "Synchronisation failed: peer is unknown or unhealthy" and "Unregister failed: peer is not registered".

**Comment by karalabe** [comment]
I'm testing a potential fix to it. It should work all ok, but don't want to push prematurely. If you're interested to try it, switch over to the `hard-disconnect-trial` branch.

**Comment by mrosack** [comment]
I'm having similar problems to this issue and #1117, tried the `hard-disconnect-trial` branch, but it doesn't seem to be any better. :(

I keep exiting and restarting geth, and it will slowly download chunks of blocks every once in a while, but it won't stay up to date with the blockchain:

```
I0527 16:23:08.494954     935 backend.go:256] Protocol Version: 60, Network Id: 0
I0527 16:23:08.494996     935 backend.go:266] Blockchain DB Version: 3
I0527 16:23:08.495832     935 chain_manager.go:257] Last block (#454478) 3a6636280e4aa72d6b6f072f7d3e91dda2f26183b71744df23fd636de37bbec2 TD=963161316684743
I0527 16:23:09.041842     935 cmd.go:137] Starting Geth/v0.9.25-5235e01b/linux/go1.4.2
I0527 16:23:09.041938     935 server.go:293] Starting Server
I0527 16:23:10.562340     935 udp.go:189] Listening, enode://97903e26c215ee6af32540284437ff17a81770ca4af059606679f4b0b9d8abdfa39744e2188392de2c501fce1cd5c07adcaf94e00d4b0762f1eb6eec2cff23a3@[::]:30303
I0527 16:23:10.562487     935 backend.go:477] Server started
I0527 16:23:10.562551     935 server.go:530] Listening on [::]:30303
> I0527 16:23:15.363355     935 worker.go:464] transaction(265f34bf) below gas price (tx=10 Shannon ask=10 Szabo). All sequential txs from this address(a8da6124) will be ignored
I0527 16:23:15.363642     935 worker.go:464] transaction(94f43363) below gas price (tx=10 Shannon ask=10 Szabo). All sequential txs from this address(a8da6124) will be ignored
I0527 16:23:25.550618     935 downloader.go:159] Block synchronisation started
I0527 16:23:27.677441     935 chain_manager.go:655] imported 3 block(s) (0 queued 0 ignored) in 1.114515824s. #454481 [92a1aeaa / 35961842]
I0527 16:23:27.678689     935 worker.go:464] transaction(265f34bf) below gas price (tx=10 Shannon ask=10 Szabo). All sequential txs from this address(a8da6124) will be ignored
I0527 16:23:27.678934     935 worker.go:464] transaction(94f43363) below gas price (tx=10 Shannon ask=10 Szabo). All sequential txs from this address(a8da6124) will be ignored
I0527 16:25:04.579855     935 chain_manager.go:655] imported 12 block(s) (0 queued 0 ignored) in 16.810675ms. #454493 [b54f09b5 / b2d3343a]
I0527 16:28:23.763977     935 worker.go:464] transaction(265f34bf) below gas price (tx=10 Shannon ask=10 Szabo). All sequential txs from this address(a8da6124) will be ignored
I0527 16:28:23.764604     935 worker.go:464] transaction(94f43363) below gas price (tx=10 Shannon ask=10 Szabo). All sequential txs from this address(a8da6124) will be ignored
```

**Comment by karalabe** [comment]
Currently the network fell into a million little pieces, that each isolated itself from everyone else. Most probably the only way to reboot it is to have enough peers find each other. Even then those that won't update (most of the current network) will keep screwing up the updated nodes. Eventually it will tilt and the old ones will phase out, but we need more fresh nodes in the system. The boot nodes are syncing but they had to restart from scratch due to the fork and will take a bit more until they catch up. Just please keep your node running :) With the above PR fix :)

**Comment by MercStills** [comment]
I have been running the PR fix for last couple hours.  And I did not wipe .ethereum folder.

Although I still get the bad peers messages and bad block# 446,189 message, I seemed to be in sync with longest chain, at least temporarily.  Then my chain lags behind and doesn't get updated for 50 or so blocks, but eventually does get sync according to data on stats.ethdev.com.

I will turn on a few more nodes with the above PR fix to help smooth out the network.

**Comment by karalabe** [comment]
The reason you get blocks in chunks is because eth has two ways to distribute blocks: download from someone (this one runs when a new peer connects to you, or otherwise every 10 sec as a sanity check); or receive it as a broadcast from one of your neighbors. However since you're broadcasting a new block to only sqrt of your peers, if almost everyone is a bad peer, they'll just act as black holes. And thus you need to wait either until you get luck and receive the block (by which time there will probably be a gap in your chain so you too drop it). Downloading can again be screwed up if you try to pull from an invalid node as you have to pull a hash chain and then detect the issue and drop the peer (then the next bad peer, next bat peer, etc).

This is the reason that if there are many more bad peers than good peers, then your node has a very tough time finding someone with valid data.

**Comment by karalabe** [comment]
Btw, thanks for helping sort this mess out :)

**Comment by karalabe** [comment]
Ok, so this issue was fixed in the previous release. Just for the sake of completeness, the issue was if a bad peer was detected, my code called a `removePeer` method, thinking it would disconnect said node. However that function only ignored the peer, not disconnected, so it screwed up my downloader logic which assumed that it will have to reconnect if it wants to talk to us again.
