### ISSUE TITLE
[ALL] FEATURE REQUESTS console

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#1252]
Please add the `admin.unlock` account back to the console

**Comment by tymat** [comment]
1. admin.unlock is supported through the IPC interface (see: https://github.com/ethereum/go-ethereum/blob/develop/rpc/api/personal.go).  It would be nice to have geth console features to be configurable like the IPC so that one could include any number of console commands like eth, admin, personal.  

2. We would also like to have a way to lock the account (i.e. personal_lockAccount) both from console and IPC interface.  

3. A timeout value to lock the account back after a certain period of inactivity would be handy.  

4. Find a good way to do something like [mlock() syscall](http://linux.die.net/man/2/mlock) to ensure that the IPC/console commands are not swapped to disk which can disclose sensitive information.

**Comment by bas-vk** [comment]
As tymat stated, since yesterday a PR was merged which adds a new console. It's a *big* change 
which will probably have some bugs. Thats why I added the new ipc console instead of replacing the current console so you guys can play with it but still have the old console which is known to work. The new console has not all the features the old console has (e.g. ask for your password). This is something I hope to address the next week.

For now you can:
```
> personal.unlockAccount(eth.coinbase, 'yourpassword', 300)
```
Last argument is the unlock duration in seconds, it's optional and by default 300 seconds.

I have started to document these new calls but it is very incomplete and not yet usable at this time.

**Comment by obscuren** [comment]
Setting `--vmdebug` from the console

**Comment by ethers** [comment]
are most things from `geth console` being added to the new console?  would like `admin.contractInfo` added etc.

**Comment by karalabe** [comment]
Another thing that would be extremely useful is to allow setting `--vmodule`, something along the lines of

```
debug.vmodule("downloader", 6)         // Override CLI parameter
debug.vmodule("downloader", "default") // Revert to CLI parameter
```

**Comment by karalabe** [comment]
Another idea, 

```
debug.pprof("120")
```

 to run the profiler for 120 secs, maybe an optional flag of the dump file.

**Comment by ethers** [comment]
`eth.pendingTransactions` and `eth.resend` seem to also be missing in new console

**Comment by ethers** [comment]
a way to set the coinbase, probably in the `miner` commands (or `admin` is ok too)

**Comment by zelig** [comment]
I believe this has been fixed
