### ISSUE TITLE
Expect standalone console to hide summary info at verbosity 2

### ISSUE THREAD

**Issue by carver** [ethereum/go-ethereum#1253]
I was expecting `console --verbosity 2` to not print out the header info (especially to stdout). For example:

**got**
```
$ echo 'eth.getBlock("latest").difficulty' | console --verbosity 2
instance: Geth/v0.9.29/linux/go1.4.2
 datadir: /home/carver/.ethereum
coinbase: 0x0000000000000000000000000000000000000000
at block: 575787 (2015-06-12 01:31)
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 shh:1.0 txpool:1.0 web3:1.0
37722391634
```

**expected**
```
$ echo 'eth.getBlock("latest").difficulty' | console --verbosity 2
37722391634
```

**Comment by obscuren** [comment]
To be fair @bas-vk I think it shouldn't output any information at all when you boot up the console.

**Comment by bas-vk** [comment]
I didn't think that anyone would be using the console this way but it makes sense. You can even execute scripts this way.

There are several options:
1. don't output any information
2. output it over stderr
3. add a "cmd" flag which executes the command, prints the result and then stops
4. don't change anything since it is already possible to do this:
```
± |develop ✗| → echo -e '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", false],"id":1}' | nc -U /home/bas/.ethereum/geth.ipc | jq '.result.difficulty'
"0x98dbba29a"
```

Personally I'm leaning towards option 3 since it is the most explicit and I like the default welcome message. Especially when you connect to a remote geth instances (future plan) it's nice that you get presented with a small message telling you which node you are connected to and what the current status is.

**Comment by carver** [comment]
The closest analogy I can think of is `ssh` - you get a welcome message when you log in with `ssh localhost`, but if you add a command, like `ssh localhost echo loopy`, then you only see the results of your command.
