### ISSUE TITLE
 Block's parent unknown

### ISSUE THREAD

**Issue by kvhnuke** [ethereum/go-ethereum#1308]
This is the second time this happened, on the exact same block number, after this it seems like there is no way to start syncing from block #640967.
last time I did removedb and started to sync from the beginning but it gave me the same error at the same block. 

version: latest developer

I0621 19:46:10.786913   30032 chain_manager.go:690] imported 1 block(s) (0 queued 0 ignored) including 60 txs in 5.496449553s. #640966 [47233985 / 47233985]
I0621 19:46:10.806794   30032 chain_manager.go:801] Bad block #640967 (905f44ee8670a3f910df1f927d11a412b2e85fe3c8894cacd06f16ef4bcc5b3e)
I0621 19:46:10.806866   30032 chain_manager.go:802] Block's parent unknown 472339850948350e541cfcbe69ea6390a1523e436011d31f1c564e8a2e8037ab
I0621 19:46:10.822569   30032 downloader.go:224] Synchronisation failed: block downloading canceled (requested)
^CI0621 19:47:01.645109   30032 cmd.go:60] Shutting down (interrupt) ...
I0621 19:47:01.758768   30032 downloader.go:224] Synchronisation failed: no peers to keep download active
I0621 19:47:02.481046   30032 chain_manager.go:690] imported 1 block(s) (0 queued 0 ignored) including 60 txs in 1.878685734s. #640966 [47233985 / 47233985]
I0621 19:47:02.481252   30032 chain_manager.go:518] Chain manager stopped
I0621 19:47:02.481314   30032 handler.go:141] Stopping ethereum protocol handler...
I0621 19:47:02.481376   30032 handler.go:151] Ethereum protocol handler stopped
I0621 19:47:02.481435   30032 transaction_pool.go:122] TX Pool stopped
I0621 19:47:02.516510   30032 backend.go:635] Automatic pregeneration of ethash DAG OFF (ethash dir: /root/.ethash)
I0621 19:47:02.518630   30032 database.go:78] flushed and closed db: /root/.ethereum/blockchain
I0621 19:47:02.627267   30032 database.go:78] flushed and closed db: /root/.ethereum/state
I0621 19:47:02.631073   30032 database.go:78] flushed and closed db: /root/.ethereum/extra
root@localhost:/home# geth
I0621 19:47:06.965512   15441 backend.go:269] Protocol Version: 60, Network Id: 0
I0621 19:47:06.965728   15441 backend.go:279] Blockchain DB Version: 3
F0621 19:47:07.018681   15441 chain_manager.go:238] Fatal. LastBlock not found. Please run removedb and resync

**Comment by karalabe** [comment]
Did you by any chance run out of disk space? We've noticed a similar issue with database corruption when the disk was full (there were some missing write error checks). I've managed to screw up my chain at least 3-5 times in the last few days, turned out only due to the disk... 

If you are sure you indeed have enough space (my chain is currently at 24.3GB), you can try **temporarily** replacing this line: https://github.com/ethereum/go-ethereum/blob/develop/core/chain_manager.go#L233 with `block := bc.GetBlockByNumber(640900)`. This should force geth to revert to a previous block instead of trying to access the latest (which seems to gone missing).

**Comment by obscuren** [comment]
Or a system crash?

Missing parent is not a corruption. You shouldn't give this block to the chain manager of it doesn't exist. Is this perhaps the case Peter?

**Comment by karalabe** [comment]
The log does contain:

```
I0621 19:46:10.786913 30032 chain_manager.go:690] imported 1 block(s) (0 queued 0 ignored) including 60 txs in 5.496449553s. #640966 [47233985 / 47233985]
I0621 19:46:10.806794 30032 chain_manager.go:801] Bad block #640967 (905f44ee8670a3f910df1f927d11a412b2e85fe3c8894cacd06f16ef4bcc5b3e)
I0621 19:46:10.806866 30032 chain_manager.go:802] Block's parent unknown 472339850948350e541cfcbe69ea6390a1523e436011d31f1c564e8a2e8037ab
```

So it doesn't look like a crash. As far as I know we check for parents before any insert.

However, I think the most important part is the last log entry:
```
F0621 19:47:07.018681 15441 chain_manager.go:238] Fatal. LastBlock not found. Please run removedb and resync
```

which seems to suggest, that at least writing LastBlock failed, so I'm betting writing out the block itself too, that's why it's missing from the db.

**Comment by kvhnuke** [comment]
yes indeed!!! it did run out of disk space, Thank you!

**Comment by obscuren** [comment]
cool. should be fixed in https://github.com/ethereum/go-ethereum/pull/1305
