### ISSUE TITLE
Make filter ids non numeric

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#1330]
The current setup with filter allows that you can guess other filter IDs, (e.g. by counting up) and listen to other filters. 

For ethereum activity this might only be used to disturb other dapps, but for whisper filters it could be used to listen to private encrypted conversations.

A simple fix would be to make the filter ids non numeric e.g. `"eg35gdf5trew4535"`, so that they are hard to guess.

Accroding to the RPC specs, ids can also `... contain a String, Number, or NULL value if included.`

This would make filters safe from spying dapps.

**Comment by tgerring** [comment]
I don't think this is a good place for this issue, especially as this is potentially impacting all of the clients. It relates to a variety of other privacy issues that should be discussed more comprehensively to ensure that we're not hamstringing ourselves at the same time.

I would very much like to see issues like this raised on a developer mailing list (similar to Bitcoin's) so that each implementation can handle it as they see fit.

**Comment by frozeman** [comment]
IMHO this is a cross client issue, as they should all using the same specs.
Our current dapp mailing list is not the right place to discuss this stuff right now.

Changing to non numeric keys, should not need to any change in web3.js or dapps, but it increases security.

**Comment by fjl** [comment]
This is addressed in recent releases.
