### ISSUE TITLE
Inconsistent ipc behavior between geth 0.9.32 and 0.9.33

### ISSUE THREAD

**Issue by ppratscher** [ethereum/go-ethereum#1350]
There seems to be an issue with the updated ipc interface and easy-ipc for node. The following gist https://gist.github.com/ppratscher/3128f41064dc5a92a717 did work fine with geth 0.9.32 (executes immediately and the connection remains open) while it does not work with geth 0.9.33 (latest develop) as it takes approx 5secs to return the call and the connection closes immediately afterwards. Could this be related to the new batch feature of the ipc interface?

**Comment by ppratscher** [comment]
There is also a strange behavior when using the net package as incomplete json data is returned from the call, see: https://gist.github.com/ppratscher/cdaf96589053843dafc4 which returns:

>connected to server!
>
>undefined:1
>871683572095760715221900279379292786303637268765822681241993384808166021603722
>                                                                              ^
>SyntaxError: Unexpected end of input

**Comment by bas-vk** [comment]
@ppratscher, on gitter you mentioned the `net` package is working for you. Is the first question still an issue then? I have tried your example and see some strange behavior.  Geth returns the response but easy-ipc doesn't seems to trigger a data event.

About receiving an invalid response. The IPC connection has a max buffer size which is imposed by the OS. The requested block is very large and the length of the response is larger then the buffer size of your OS. Because of that geth will send the response in multiple chunks which fit in the buffer. Its up to the receiver to combine these chunks and parse the response when the response is received complete.

I have created a brief example here: https://gist.github.com/bas-vk/6df3c86168d05eff373f

**Comment by ppratscher** [comment]
Well I would prefer that at least one of the current node ipc libraries would work with geth (as they used with version 0.9.32).

Thanks for your example. But this approach still fails as soon as you send multiple async requests using one connection. See: https://gist.github.com/ppratscher/00c753148d00b33cbda7

The gist works fine with geth 0.9.32.

**Comment by bas-vk** [comment]
The example you gave is pipelining and not async requests. Pipelining isn't supported and gives performance improvements over high latency connections. In the case of this ipc connection I don't expect a noticeable performance gain from this. It adds however a lot of complexity. Since latency isn't an issue over this interface the only benefit would be to allow for parallel processing of the requests. But in that case the responses can come back out of order and clients must be able to handle this.

Browsers open multiple connections to a server which allows for async parallel processing. There is nothing holding you back from opening multiple connections to geth if you want this behavior.
