### ISSUE TITLE
CPU mining question. Getting uncles but balance still 0.

### ISSUE THREAD

**Issue by Kramerr** [ethereum/go-ethereum#14366]
#### System information

Geth version: `geth version` geth 1.6.0
OS & Version: Windows/Linux/OSX : windows 10

I have downloaded all the blocks from the block chain and when starting geth and running miner.start(8) it shows that I have started mining. I run i7-5700HQ 16gb ram. I get a few uncles here and there but have not seen any ether in my account. Am I doing everything correctly or am I doing something wrong? Also wanted to know what would be the best way to mine with my laptop? I also have a good GPU it is a GeForce GTX 970M. Picture shows my mining with CPU. Thanks in Advance for help and advice.
![untitled1111](https://cloud.githubusercontent.com/assets/27564927/25304800/e2bc679a-2744-11e7-81b5-5993eea83356.png)

**Comment by bas-vk** [comment]
The picture only shows the node importing blocks from the network. The line with `Commit new mining work` indicates that the miner is indeed running but it has not found a pow solution. In that case you should see a line with `Successfully sealed new block`. 

You probably want to join a mining pool. I have no experience with mining so I cannot give you advice. There are a couple [how to's](https://www.cryptocompare.com/mining/guides/how-to-mine-ethereum/) on the internet with instructions how to setup your computer for mining. You probably want to take a look at them. Also the [ethereum mining reddit page](https://www.reddit.com/r/EtherMining/) might be a useful place to start.

**Comment by karalabe** [comment]
The current network hashrate is 22.3TH/s. If you check `eth.hashrate`, you'll see own hashrate. With a CPU, your hashrate will be on the order of magnitude of 250KH/s. That means you have a chance of finding 1 block out of every 89200000 (i.e. one block every 42.4 years). TL;DR; forget mining with a CPU on the mainnet. CPU mining is only useful for test and private networks where you don't care about security, just want to test Ethereum.

If you want to GPU mine, I'd suggest using https://github.com/Genoil/cpp-ethereum, since that received a lot of tunings compared to the stock `ethminer` since there was no particular reason for the EF to keep pushing the limits on the miner, when there's a fully capable mining community to do that. Even for that though, you probably want to join a pool as even a very very powerful desktop GPU can only crunch at about 25MH/s.

**Comment by wardfire** [comment]
No one actually answered the part of the question about uncles. I have the same question. I'm GPU mining at about 20MH/s and have seen a few uncles show up in my log when i tested solo mining. My ethereum wallet's balance didn't change though. What does it mean when uncles=1 shows up in your log? Does it mean you should be receiving a mining reward?

**Comment by itinance** [comment]
+ @wardfire 

same here: here and there "1 uncles" but the balance keeps zero.

**Comment by asgs** [comment]
@karalabe that makes a lot of sense. the current Nethash is ~94 Th/s and here I'm watching geth console logs running on my 8-core i7 machine waiting to see the "mined a block" log! It looks as if apowerful GPU setup won't help successfully mine a block these days.

Would it be fine with you guys to add a note in the README or the main wiki docs talking about this? Most of the people using geth are people who don't have a GPU to mine ETH, hoping their CPUs could do it after a few days, if not weeks/months

**Comment by steve100254** [comment]
Does anyone have an answer to this.  I have mined at least 3 uncles and so far, no eth in my account

**Comment by airatru** [comment]
Greetings,
I've been testing solo mining on my desktop and setup geth server and mining software. After a few minutes I've a message "Successfully sealed new block" with seal hash and block hash. But my address on etherscan shows 0. Am I doing something wrong? I've seen some logs having a second string after that one saying: "block reached canonical chain". Does it mean not all blocks reach the chain? I didn't get that second message.
