### ISSUE TITLE
eth.filter is not working, geth version 1.3.5, linux os

### ISSUE THREAD

**Issue by aniket-kumar** [ethereum/go-ethereum#14362]
Geth version: `geth version 1.3.5`
OS & Version: Ubuntu 16.04 & Ubuntu 14.04
web3.eth.filter({fromBlock:1, toBlock: 35}).get() is returning []. While there are transactions in the blocks between 1 & 35. How to resolve ?

**Comment by bas-vk** [comment]
Upgrade to the latest version that you can find on the [download](https://geth.ethereum.org/downloads/) page or through the ubuntu [ppa](https://launchpad.net/~ethereum/+archive/ubuntu/ethereum).

**Comment by aniket-kumar** [comment]
Initially i tried to run it on geth 1.5.9, but filter didn't work there. But on one windows machine with geth 1.3.5, filters were working so i downgraded it on ubuntu too. After all this, filters still didn't work. what to do next?

**Comment by bas-vk** [comment]
Could you post a couple of receipts of transactions, the arguments that you used to create the filter and the ABI of the events that you want to match.

**Comment by aniket-kumar** [comment]
I just want to get detail of all the transactions of the blockchain. I used it as  `web3.eth.filter({fromBlock:1, toBlock: 35}).get()`. It works fine with geth 1.3.5 on windows but not on ubuntu.

**Comment by karalabe** [comment]
Are you sure you have your private chain synced correctly on your Ubuntu machine? Getting contract events via filters works for me on the mainnet with Geth 1.6.0.

**Comment by aniket-kumar** [comment]
@karalabe I am not talking about contract events. I am using this filter to get all the transactions' info of the blockchain. See this : https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethfilter

**Comment by karalabe** [comment]
A filter gets you contract events (called logs), not transactions, as
mentioned in the doc you linked:


   - filter.get(callback): Returns all of the log entries that fit the
   filter.



On Apr 25, 2017 09:22, "aniket-kumar" <notifications@github.com> wrote:

@karalabe <https://github.com/karalabe> I am not talking about contract
events. I am using this filter to get all the transactions' info of the
blockchain. See this : https://github.com/ethereum/wiki/wiki/JavaScript-API#
web3ethfilter

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ethereum/go-ethereum/issues/14362#issuecomment-296925792>,
or mute the thread
