### ISSUE TITLE
Transaction load test (fails when asyncronous creation of contract is used via multiple RPC calls for contract creation )

### ISSUE THREAD

**Issue by Anatoliy4041** [ethereum/go-ethereum#14375]
#### System  #information

Geth version: v1.5.9-stable-a07539fb
OS & Version:  Ubuntu 16.04.2 LTS

Hi Guys!

Actually I'd like to ask help about transaction load test which I try to perform.
I created a simple person storage contract and coded nodejs simple app to load private ethereum network where I sent 10 new person to. So it's one transaction per one person. 
The issue is that some transaction were mined , however some were not, and those even weren't added into pending txpool.
Then I tried for 50, 100 persons and the result was - only 1/4 transactions where each one represents one person - disappeared.
I tried to set -verbosity for max to 6 to trace those and did't find any clue what happened with them.

For example - logs the transaction of person which were not added into block chain:

Line 8663: I0424 11:55:06.227721 core/tx_pool.go:343] (t) 0x09aa3330 => e7df539a (0x56cc50) f4abe26906f2675b054707b6c86df1b9f74f12e7706d3cb0e50249042d0be506
	Line 8678:         TX(f4abe26906f2675b054707b6c86df1b9f74f12e7706d3cb0e50249042d0be506)
	Line 8691: I0424 11:55:06.239756 internal/ethapi/api.go:1143] Tx(0xf4abe26906f2675b054707b6c86df1b9f74f12e7706d3cb0e50249042d0be506) to: 0xe7df539af99387efb4c26ab6f60f5f613ae90e93
	Line 8788: I0424 11:55:06.275486 internal/ethapi/api.go:1026] receipt not found for transaction 0xf4abe26906f2675b054707b6c86df1b9f74f12e7706d3cb0e50249042d0be506

From that it is clearly seen that transaction was created, however it was found in pending  neither found receipt

Could you help to sort this question please!

#### Expected behaviour

All of 100 transaction mined into blockchain

#### Actual behaviour

Some transactions are not mined and even not added to pending (txpool) 

#### Steps to reproduce the behaviour

To reproduce that behavior just try to perform load test  by genereting 100 transaction at once

**Comment by holiman** [comment]
Could you provide the code that you used? 
As you can see here: https://github.com/ethereum/go-ethereum/issues/14361#issuecomment-296187252 , I can create thousands of transactions without losing any, so any additional information you can provide would be helpful.

**Comment by Anatoliy4041** [comment]
I'll post it here in the nearest future!

By now I'll like to share what I've got so far - I implemented your code  in #14361 and it woked perfectly!
However I'd like to add some intresting point I came accross when I tried to get it sorted.
My script for load test is working in asynchronous way (via callback) by sending request to RPC standart geth client port 8545 (it shoud be relatively high amount of transactions 20, 50 or 100). In this case some of transactions disappeared. When I do it in synchronous way it's fine(or I do it asynchronously via geth console).

So based on that, I'd wonder to know is there any limitation for request which geth RPC can handle? And did you came accross on the similar geth behaviour?

**Comment by Anatoliy4041** [comment]
[Here](https://github.com/Anatoliy4041/loadtest) is the link to the code I used to reproduce the bug.
So as you can see when you run the test (e.g for creating 10 contracts) you'll get 10 tx hashes, however you won't get the same amount of contract addreses.

Some intresing points I found using that test(RPC calls via 8545 port) is:
1) as many tx as were added to txpool will be mined and we will get their addresses
2) when I do the test in syncronous way (without callbacl after "MyContract.new(.." It works perfectly!

So the issue happens when ascyncronous multiple RPC calls for contract creation happen.
When I tried to launch via console my code and @holiman  in #14361 both in syncronous and ascyncronous way it was fine

**Comment by holiman** [comment]
Thanks for the update and the very thorough documentation! I'll look into it

**Comment by fabio-muramatsu** [comment]
I'm experiencing a similar issue in a private network, but using `sendRawTransaction` instead. More specifically, I was creating ~200 transactions in a loop, each of them sending some ether to an account. Interestingly, all 200 transactions were received by the geth node, since they were all logged in the console as shown below.
```
INFO [04-27|11:37:24] Submitted transaction                    fullhash=0x904309d3e850edad865b50805d5f19db6fdb2ad2ab971f8ce415773ce57b7250 recipient=0x7423c975164969881680c7ad944444dfae1887f9
...
```
However, in most of my tests, some of these transactions were not added in the transaction pool. The results of `txpool.content.pending` and `txpool.content.queued` show less than 200 transactions, which means a few transactions were somehow lost in geth.
Another interesting fact is that this problem seems to be related to the request throughput. For instance, the problem happens when I call `sendRawTransaction` once every 5ms. If I increase this interval to 50ms, all 200 transactions are correctly added to the pool.

I'm running geth v1.6.0 on Arch Linux, and my tests were run in Node.js v7.8 using web3js. All `sendRawTransaction` calls were performed asynchronously.

**Comment by Anatoliy4041** [comment]
@holiman I also want to add that the number of transactions which are not added to txpool is changed every time I run my ascync create contract requests

**Comment by Anatoliy4041** [comment]
@fabio-muramatsu Could you share please, how did you get your geth logs in such way? e.g. the original one looks like:
I0425 17:02:54.289282 miner/worker.go:517] commit new work on block 1523 with 0 txs & 0 uncles. Took 557.556µs
Did you set up disent logger?

**Comment by fabio-muramatsu** [comment]
@Anatoliy4041 Actually that's the default log displayed in the console. I think it was changed in v1.6.0.

**Comment by holiman** [comment]
I've managed to reproduce it. It's quite simple, actually. 
[`sendTransaction`](https://github.com/ethereum/go-ethereum/blob/fff16169c64a83d57d2eed35b6a2e33248c7d5eb/internal/ethapi/api.go#L1172) calls [`setDefaults`](https://github.com/ethereum/go-ethereum/blob/fff16169c64a83d57d2eed35b6a2e33248c7d5eb/internal/ethapi/api.go#L1138) which calls [`getPoolNonce`](https://github.com/ethereum/go-ethereum/blob/a7b9e484d05ceb0afce4ba5dbc62b8f262c2e354/eth/api_backend.go#L159) . There's a small sync around `getPoolNonce`, but two (or several) requests which hit `sendTransaction` simultaneously _will_ obtain the same nonce, since

* setDefaults (sets nonce to whatever the `state` says)
* It takes some time to sign the transaction (unsynched here)
* Transaction is submitted, in [`submitTransaction`](https://github.com/ethereum/go-ethereum/blob/fff16169c64a83d57d2eed35b6a2e33248c7d5eb/internal/ethapi/api.go#L1195). 
* Only when the tx is submitted is the nonce in the pending state increased. 

So basically, paralellism fails for submission of transactions from the same account, since the bottleneck in signing a tx creates a lot of colliding nonces. 

And it's even worse :(

I tried using a `GetAndIncNonce`, a synchronized method which gets and sets the nonce in one go. This solves the first problem, and N tx:s submitted simultaneously don't get the same nonce. They get `1,2,3,4,5,6`. Then the first one is submitted, and somewhere in `tx_pool`, I believe `promoteTx`, the method thing which previously 'saved' us now bites us in the ass: 
```
	pool.pendingState.SetNonce(addr, tx.Nonce()+1)
```
So this sets the `nonce` back to `2`. And instead of continuing at `7`, the nonces now are set back to `2`. 

So the sequence becomes: 
`0,1,2,3,4,5,6,2,3,3,6,7,8,9,8,9,10,7,8`. 

In order to solve this, I have a feeling that we need

* `pendingState` with nonces for everything submitted to the pool
* `localState` with nonces for transactions submitted locally, which haven't yet reached the pool. 

Submitting a `default` transaction does the following (synched): 
* Call `localState.getAndIncreaseNonce(account)`
  * If not available
      * set `localState<account><nonce>`= `pendingState.getNonce(account)`
  * set `localstate<account><nonce>++` 
  * return `localstate<account><nonce>`
 
@karalabe @fjl thoughts ?

**Comment by holiman** [comment]
Submitted a PR, to demo one way of fixing the issue.

**Comment by fabio-muramatsu** [comment]
@holiman Thank you for your response. If I got it right, geth has an issue determining the nonce for transactions sent successively from the same account, right? However, in my case, I'm creating transactions manually with the right nonce (i.e., transactions with sequential nonces), signing them and submitting to geth with `sendRawTransaction`. So geth seems to be dropping transactions even when it is not required to set the nonce internally, as I'm already defining it externally. Do you think my issue is related to your findings?
Thank you again for your attention.

**Comment by holiman** [comment]
@fabio-muramatsu iiuc, the problem you're describing is something else. Could you please open a separate ticket for that ? Any test-scripts you have, or detailed instructions about reproducing it is appreciated.
