### ISSUE TITLE
MsgEvents for network simulation/tests

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#14391]
Implement MsgEvents along the lines of https://github.com/ethersphere/go-ethereum/pull/74 and https://github.com/ethersphere/go-ethereum/pull/75

DidSend and DidReceive should be subscriptions too but i think it should be set to filter MsgTypes (and maybe peers too) already on the sender side. For this I recommend a reporter object, it would create a separate eventer that should be passed to each p2p/protocol constructor, if not nil, each message received would be Post-ed to the eventer. The reporter would set up a Subscription for messages with types subscribed to, add the sender (remote peer id) to the event and send it via the rpc subscription

**Comment by lmars** [comment]
I was imagining we would enhance the current [`PeerEvents`](https://github.com/ethersphere/go-ethereum/blob/network-testing-framework/p2p/adapters/exec.go#L347-L375) API so that the RPC stream also returns p2p messages, so [`PeerEvent.Type`](https://github.com/ethersphere/go-ethereum/blob/network-testing-framework/p2p/peer.go#L76-L81) could take a new value `PeerEventTypeMsg`.

We would probably want to update [`p2p.Server.SubscribePeers`](https://github.com/ethersphere/go-ethereum/blob/network-testing-framework/p2p/server.go#L145) so that it takes some message filters in case the client just wants events for particular message types (or no messages at all), and probably rename that to `p2p.Server.PeerEvents` too.

To implement this, I was thinking of just wrapping the current [rlpx p2p.MsgReadWriter](https://github.com/ethersphere/go-ethereum/blob/network-testing-framework/p2p/rlpx.go#L71-L97) with an object which emits the events, and then that can be passed transparently to `Protocol.Run`.

**Comment by zelig** [comment]
https://github.com/ethersphere/go-ethereum/pull/113
