### ISSUE TITLE
issues with sync

### ISSUE THREAD

**Issue by unknown1233333** [ethereum/go-ethereum#14393]
#### System information

Geth version: '1.6.0'
OS & Version: Windows 7 64 bit

Using mist wallet with geth 1.6.0.
I been trying to sync for days.
I get errors where some ldb files get corrupted and geth.exe would just crash.
I was able to get through that error by deleting the bad ldb files (don't know if this will cause any issues down the road.)
but now the downloading of the new block just slows down.  I start mist and geth and after like 5 minute it stops downloading new blocks.  nothing happens.
COMPLETELY UNUSEABLE!
PLEASE FIX THIS!

**Comment by karalabe** [comment]
If you delete files randomly from the database then that will make everything useless. Delete all of the chain data and start over.

How did you start geth? Mist didn't bundle Geth yet afaik, so I guess you started geth manually. Please share the command line options you did with.

Send us some logs from Geth, otherwise we have no idea "what" is happening while you say "nothing happens".

PLEASE DON'T WRITE IN CAPS, WE GET PISSED WHEN SOMEONE IS SHOUTING AT US.
