### ISSUE TITLE
geth --testnet on Ropsten not works.

### ISSUE THREAD

**Issue by EasonWang01** [ethereum/go-ethereum#14409]
#### System information

Geth version: `1.5.8`
OS & Version: Windows/OSX

1.using  --testnet default connect to Ropsten

<img width="520" alt="2017-05-03 10 30 16" src="https://cloud.githubusercontent.com/assets/11001914/25646720/b02c8132-2fed-11e7-94a3-2b58a8f3f9b6.png">

2.mined for money
<img width="1066" alt="2017-05-03 10 30 27" src="https://cloud.githubusercontent.com/assets/11001914/25646739/d04f9576-2fed-11e7-9bc4-2a73beab299e.png">

3.But nothing show on etherscan.
<img width="896" alt="2017-05-03 10 30 45" src="https://cloud.githubusercontent.com/assets/11001914/25646750/e241b926-2fed-11e7-91c2-cf4a1b39715d.png">

4.send transaction and no result show on etherscan but wallet

<img width="989" alt="2017-05-03 11 13 22" src="https://cloud.githubusercontent.com/assets/11001914/25647126/d1c47616-2ff1-11e7-9ddc-5b412d0eb6e6.png">

<img width="1166" alt="2017-05-03 11 13 36" src="https://cloud.githubusercontent.com/assets/11001914/25647128/d52cdf6e-2ff1-11e7-94b9-d581521ba265.png">

**Comment by karalabe** [comment]
You didn't wait for your node to sync to the testnet. Also Ropsten was reset with a fresh set of bootnodes to to some attacks, so please upgrade to Geth 1.6.0, and resync from there. Wait until you're in sync and only then start to mine.

**Comment by EasonWang01** [comment]
thanks for reply.But what is the network I connect to with 1.5.8?Not really know why the geth version will affect the node sync.

**Comment by karalabe** [comment]
The old Ropsten was torn to pieces by spam attacks. A few blocks were rolled back and a new version was deployed with new bootnodes. The key is the bootnodes, which only shipped hard coded in Geth 1.6.

**Comment by EasonWang01** [comment]
thanks.

**Comment by EasonWang01** [comment]
But if people still using geth 1.5.8 or early version is this means that their account ether will not works anymore?Because upgrade to 1.6.0 is a different genesis block.

**Comment by karalabe** [comment]
It's the same genesis and all, just a few spam blocks were removed from the chain head. It's possible to sync with earlier versions of geth too to the correct chain, but I'm unsure if the old bootnodes are still up, so there might be connectivity issues unless someone manually adds the new bootnodes as peers.

**Comment by EasonWang01** [comment]
thanks,but do you know why same genesis block but the console will says wrong genesis block in block when I upgrade from 1.5.8 to 1.6.0.

**Comment by karalabe** [comment]
Ah, yes. Previously if you specified a custom datadir and testnet too, it placed the chain into `<your custom datadir>/testnet`. As of Geth 1.6, if you explicitly specify a custom datadir, then it will use that and won't create an extra `testnet` folder nested inside it. This is a good thing because until now it was impossible to place the testnet in a folder that's not called testnet and that's not nested one folder deeper than needed.

The error messages is that the folder you pointed your node at already contains a chain that's incompatible with the one you want to overwrite it with. Most probably it already contains the mainnet, and won't let you overwrite it with the testnet.

Just specify `--datadir F:\ethereum\testnet` and you'll get the old behavior.
