### ISSUE TITLE
Mobile: iOS Account creation

### ISSUE THREAD

**Issue by ArEnSc** [ethereum/go-ethereum#14421]
#### System information

Geth version: `geth version` 1.6.0 and 1.6.1
OS & Version: iOS
Commit hash : (if `develop`)

#### Expected behaviour
 
Creates an account

#### Actual behaviour

Crashes the app

#### Steps to reproduce the behaviour

// Code
   let accountManager = GethKeyStore()
    var newAccount:GethAccount?
    newAccount = try! accountManager.newAccount(password)
    print("Created a new Go Ethereum Account @: \(newAccount?.getAddress().getHex())")

#### Backtrace

````
go_seq_go_to_refnum on objective-c objects is not permitted 2017-05-04 22:32:48.186656-0400 EtherWallet[6991:1519010] 

* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'go_seq_go_to_refnum on objective-c objects is not permitted'
[backtrace]
````

**Comment by ArEnSc** [comment]
Also what happened to the path to store the keys?

**Comment by eliasnaur** [comment]
As noted in https://github.com/golang/go/issues/20254 it is an error to use the default empty initializer for Go proxies. Arguably, this problem is worse in Swift because the constructor syntax hides the call to init().

https://go-review.googlesource.com/c/51870/ adds the `unavailable` attribute to such initializers so the code in the OP results in a compile error.

**Comment by karalabe** [comment]
This was fixed upstream in gomobile last year by https://golang.org/cl/52012
