### ISSUE TITLE
The shh.subscribe example of the wiki page does not work with geth/1.6.1

### ISSUE THREAD

**Issue by kraeki** [ethereum/go-ethereum#14450]
#### System information

Geth version: `geth version`
OS & Version: Windows
Commit hash : (if `v1.6.1)

#### Expected behaviour
Successfully subscribe and return filter id

#### Actual behaviour
shh.subscribe returns two errors occur alternating:
```
Error: The handle is invalid
Error: EOF
```
#### Steps to reproduce the behaviour
```
geth console
id = shh.generateSymmetricKey()
f = shh.subscribe({type: 'sym', topics: ['0x07678231'], key: id})​
```
#### Backtrace

````
f = shh.subscribe({type: 'sym', topics: ['0x07678231'], key: id})​
Error: The handle is invalid.
    at web3.js:3104:20
    at web3.js:6191:15
    at web3.js:5004:36
    at <anonymous>:1:5​
````
#### Logs from geth
I added some debug logs and can see that the payload being sent (in.Payload) has strange 4-digit numbers which of course are out of ASCII range and therefore cause the parsing to fail.
````
DEBUG[05-12|01:26:56|rpc/json.go:168] incoming in.Method: 'shh_subscribe'                                                               
DEBUG[05-12|01:26:56|rpc/json.go:169] incoming in.Payload: '[91 123 34 107 101 121 34 58 34 52 57 97 55 50 55 98 97 49 101 98 51 51 97 52 102 56 49 99 56 98 56 55 52 50102 51 102 56 97 101 57 48 53 52 51 57 50 57 56 97 98 98 101 53 53 54 101 101 99 56 51 98 51 9949 54 57 98 52 97 97 56 53 34 44 34 116 111 112 105 99 115 34 58 91 34 48 120 48 55 54 55 56 5051 49 34 93 44 34 116 121 112 101 34 58 34 115 121 109 34 125 93]'
````

````
DEBUG[05-12|01:01:42|rpc/json.go:173] Unable to parse subscription method: json: cannot unmarshal object into Go value of type string
DEBUG[05-12|01:01:42|rpc/server.go:183] read error Unable to parse subscription request
````

**Comment by kenshyx** [comment]
I'm getting something similar when calling `shh.newIdentity()` 
```
Error: The method shh_newIdentity does not exist/is not available
    at web3.js:3104:20
    at web3.js:6191:15
    at web3.js:5004:36
    at <anonymous>:1:1
```

**Comment by nnicksize** [comment]
The function `shh.newIdentity()` is from Whisper v2. In geth version 1.6.1 they upgraded to Whisper v5, so this function should indeed no longer be available (I don't know why it's still listed in the geth console, though).
You can refer to [this wiki page](https://github.com/ethereum/go-ethereum/wiki/Whisper-Overview) for Whisper v5. There are examples listed, including the one that gives the above described error.

**Comment by nnicksize** [comment]
@kraeki Regarding your logs:

Taking all out-of-range values mod 255 (max value for an unsigned byte) returns 4 for the byte at position 62 (9949) which is the [End-of-Transmission character](https://en.wikipedia.org/wiki/End-of-Transmission_character) (&#9220;). I assume that this character leads to the `Error: EOF`. The second error `Error: The handle is invalid` then occurs because the connection is reset.

How to get the correct string: Split the values that are too long at a sensible location for bytes (one "too long byte" becomes to "normal bytes")
50102 = 50 102 (ASCII chars: 2 f)
9949 = 99 49 (ASCII chars: c 1)
5051 = 50 51 (ASCII chars: 2 3)
Decoding the modified array of bytes results in the following ASCII string: [{"key":"49a727ba1eb33a4f81c8b8742f3f8ae905439298abbe556eec83b3c169b4aa85","topics":["0x07678231"],"type":"sym"}]
Which should be correct, judging and assuming you've used the same "topics" (0x07678231) as the example [here](https://github.com/ethereum/go-ethereum/wiki/Whisper-Usage).

**Addendum:**
Decoded byte array mod 255:
[{"key":"49a727ba1eb33a4f81c8b874z3f8ae905439298abbe556eec83b3&#9220;69b4aa85","topics":["0x07678?1"],"type":"sym"}]

Modified and decoded byte array with **highlighted** "split" bytes:
[{"key":"49a727ba1eb33a4f81c8b874**2f**3f8ae905439298abbe556eec83b3**c1**69b4aa85","topics":["0x07678**23**1"],"type":"sym"}]


Maybe this is some weird copy+paste issue on the client side? Can you try to send the the valid string to the jsonrpc api directl?

**Comment by kraeki** [comment]
@bas-vk It looks like the encoding of `shh.subscribe({type: 'sym', topics: ['0xffffffff'], key: id})` after hitting it in the console somehow is wrong. Do you know where in the source code this encoding happens?

**Comment by kraeki** [comment]
The issue is fixed for now

**Comment by bas-vk** [comment]
The problem stems from the fact that that the rpc package assumes that methods with the `xxx_subscribe` format are subscription creation request. Initially this was only true for `eth_subscribe` but was recently generalized so it would also work for other "namespaces" as well. It basically allows other protocol to offer subscriptions in their API. The commit adds an exception so that `shh_subscribe` is not considered a subscription creation request but just an ordinary RPC call.

Although that works it also means that the `shh` namespace looses support for subscriptions which is undesirable. The simplest solution would be to rename `ssh_subscribe` to something else. But that is something that needs to be discussed.

**Comment by bas-vk** [comment]
Update, we are reworking the whisper API.
This will be address as part of that effort.

**Comment by kraeki** [comment]
Any update on this? Any reference to the rework?
