### ISSUE TITLE
Is the smart contract's data stored in blockchain or in database or other place?

### ISSUE THREAD

**Issue by jiebanghan** [ethereum/go-ethereum#14521]
I am just wrting contracts, and there are some  variable definition such as:
mapping(bytes32 => bytes32) private  userPasswds ;
and you know its aim is to store some values.
My question is where does the data store? is it in blockchain or in database( in Ethereum ,the state dababase is goleveldb)? If it is stored in database, is it permeant  even if all the nodes are power cut.

**Comment by karalabe** [comment]
The state is stored in a special data structure called a Merkle-Patricia trie, inside leveldb. Imagine it as a prefix-trie containing all the accounts by address, where each "leaf" representing an account contains yet another prefix-trie containing all the stored state by hash. Spice this up with crypto guarantees instead of a plain prefix-trie, and you get the Merkle-Patricia trie. :)

**Comment by jiebanghan** [comment]
Thank you. is the data permeantly stored even if all the nodes in the ethereum network are power cut?

**Comment by karalabe** [comment]
The data will remain on disk for the nodes yes, you can start the node up later and your data will be available. Also if you have the chain itself (blocks containing the transaction), you can always reconstruct the state itself, since the blocks were used originally to generate the state in the first place.

**Comment by jiebanghan** [comment]
Thank you very much for speaking with me.

**Comment by larrymeng** [comment]
mapping(bytes32 => bytes32) private userPasswds ;

By the way, is the data (userPasswds) secure? 
1) Can anyone can visit by Web3.js?
2) Can anyone can access the data stored in blockchain?

Thx

**Comment by firnsan** [comment]
Can  i think like this? The trx in block is similar with the `redo log` of mysql innodb , and state in level is similar with the `data page` of innodb. Is there some document about how ethereum store the data?

**Comment by joshtharakan** [comment]
Please refer the below article, it neatly explains the concepts.
https://hackernoon.com/getting-deep-into-ethereum-how-data-is-stored-in-ethereum-e3f669d96033

**Comment by nag9s** [comment]
@karalabe  , @jiebanghan  - This part of the question always excites me - As I understood , hash is one way , once hash applied - there is no way to retrieve the data , however , it is easy to verify the data. In that case, data is stored in terms of hashes in blockchain - how data retrieval happens say when the user is looking at the transactions etc ...

**Comment by Meyemedia** [comment]
Is there a way to encrypt sensitive data or make it hidden such as wallet addresses and passwords within smart contracts, is there a way to make it hidden if the contract will remain on a public place such as github for further development.

I want developers to build on my project, and smart contracts. Without giving them access to sensitive parameters and data such as passwords,
