### ISSUE TITLE
allow multiple sources in compile RPC

### ISSUE THREAD

**Issue by nmushegian** [ethereum/go-ethereum#1464]
`solc` lets you specify multiple sources as arguments. AFAIK this is the only way to compile code with `import` statements, without doing source file preprocessing yourself.

The appropriate rpc api definitions should be changed to allow us to do this. Or documented if you can somehow already do this.

This would let us drop the cpp-ethereum dependency completely, which is great because it isn't officially supported.

**Comment by zelig** [comment]
multiple contracts in a source are supported since https://github.com/ethersphere/go-ethereum/commit/b0ae84aa0dae65f00492f981bb61887331def2a5

The RPC and console commands do not take files but a string, so you need to have your source code snippets available anyway. Once you have strings, you can just concatenate them and you are done.
