### ISSUE TITLE
Can transaction be failed?

### ISSUE THREAD

**Issue by ucwong** [ethereum/go-ethereum#14672]
I sent a transaction with rpc cmd and receive a return txnId. will this txn be alive till included in blockchain or it can be failed for some reason?

Should I wait for it? or resend it?

If bitcoin I can find pending txn and it may be confirmed for weeks or months. But it is ok. What about eth? I can't confirm whether this txn is still alive in p2p network.

**Comment by karthiknvlr** [comment]
It will be there in the network till it gets mined. you can see the pending transactions using command eth.pendingTransactions

**Comment by ucwong** [comment]
@karthiknvlr thank you for your reply. But  eth.pendingTransactions with nothing return

![image](https://user-images.githubusercontent.com/22344498/27419516-ece9db5a-5753-11e7-92ec-a8fefe0f089d.png)

**Comment by holiman** [comment]
Can you tell us your address ? If not, you can easily check on etherscan what the nonce was of the last outgoing transaction that was included in a block. The next transaction needs to have that nonce `+1` in order to be valid. If you make a transaction to yourself (using that nonce, can have 0 value), you should clear out any potential signed transactions floating in cyberspace.

**Comment by ucwong** [comment]
@holiman 0x9435D50503aeE35C8757ae4933f7a0aB56597805 I sent not only one txn yesterday, some of them are confirmed but others not. I think they are disorder now. I can't remember what is the exactly nonce

**Comment by holiman** [comment]
This is the last 'official' transaction: https://etherscan.io/tx/0xffaa778139a98a767831b3807bde642a5fe2bca7c478bd50b5751c6053d95218 
It has nonce `10680`. 
If you want to be certain that there's not a `10681` lurking out there, you need to send a transaction to replace that one. Your local geth node seems unaware of that (potential) tx, so it will probably work fine to just send a 0-value tx to your own account (since geth will use `10681` automatically, if it's unaware of any other such transaction).

**Comment by holiman** [comment]
Oh, and check `txpool.status` while you're at it.

**Comment by ucwong** [comment]
@holiman 
![image](https://user-images.githubusercontent.com/22344498/27425769-1d693dda-576c-11e7-9ce7-ff21eae61cd8.png)

**Comment by holiman** [comment]
Ok, now also check
```
txpool.content.pending["0x9435d50503aee35c8757ae4933f7a0ab56597805"]
```
and
```
txpool.content.queued["0x9435d50503aee35c8757ae4933f7a0ab56597805"]
```

**Comment by ucwong** [comment]
@holiman 
![image](https://user-images.githubusercontent.com/22344498/27427024-1323550a-5770-11e7-9918-4169aaed054c.png)

I don't restart the node

**Comment by aaressinfomedia** [comment]
I need help, can some one find out reason for filed transaction  here : https://etherscan.io/tx/0x2b8ca6cdb7b71c0b401e1b72527c5ae393c7a11d3354634f76fdb9cfc578ca80

**Comment by holiman** [comment]
@aaressinfomedia The transaction trace ends on `REVERT`(https://etherscan.io/vmtrace?txhash=0x2b8ca6cdb7b71c0b401e1b72527c5ae393c7a11d3354634f76fdb9cfc578ca80) . 

If you look at the source (https://etherscan.io/address/0x068bd35f0f2aaf9b6e51c903500f8ed72e55afaa#code) ,they have this fun thing: 

```
	function transfer(address _to, uint256 _value){
		require(balanceOf[msg.sender] > _value);
		require(balanceOf[_to] + _value > balanceOf[_to]) ;
		//if(admin)

```
So, basically, the `balanceOf` needs to  be `>` than value : you have `10605` tokens, but can thus max move out `10604` tokens. Oh, and this has nothing to do with go-ethereum. I'm going to close this ticket, btw.

**Comment by sssubik** [comment]
@holiman @ucwong Hey, what is a 0 value transaction.Also does sending a 0 value transaction with same nonce overide the transaction with same nonce and does a 0 value transaction cost any money?

**Comment by holiman** [comment]
> Hey, what is a 0 value transaction

A 0-value transaction is basically invocation of a method on a contract (presumably -- doing a 0-value transaction to some address without code is pointless). Such a tx can e.g. be used to transfer tokens, since tokens are a layer-2 thing, and have nothing to do with `ether`, which is the `value` we're talking about.

> Also does sending a 0 value transaction with same nonce overide the transaction with same nonce

Override and override .... only one of them can ever get included, the question is which the miner chooses to pick: probably the one which pays him more. So the gasprice plays a large part here. 

>  and does a 0 value transaction cost any money
 
Yes, it costs money via the `gas` that is spent. The cost is `gas + gasprice`, where gasprice is `ether` (usually expressed in `GWei` -- gigawei, where `wei` is the smallet `ether` unit)
