### ISSUE TITLE
Lost the password of my address

### ISSUE THREAD

**Issue by mo0vjke** [ethereum/go-ethereum#14748]
Hi everyone.

I've lost my password, but I know that I had generated it using formula $i.KEY;
$i - numerical value

I've already tried to brute the password using rpc "personal_sendTransaction", but it takes to much time ≈ 1 sec per password.

Anyone knows how to brute it in a faster way.

Thanks!

**Comment by karalabe** [comment]
The private keys are encrypted using a memory and computationally hard algorithm to make brute forcing it extremely long. On a modern CPU it takes about 1 second and 256MB memory to try one single decryption.

You might try running in concurrently from many threads (although I would probably use a library and try to decrypt directly instead of via a geth RPC call, since Geth has some concurrency protection when multiple transactions use the same account). Not sure if there's some GPU decrypter that might brute force it a bit faster, but it's definitely a hard nut to crack.

**Comment by JamesDall** [comment]
Brute-forcing is slow. Some people have reported issues with dots in their password on mist. Might be an underlying issue with geth.
https://github.com/ethereum/mist/issues/2411
