### ISSUE TITLE
"nonce too low" error persists

### ISSUE THREAD

**Issue by nmushegian** [ethereum/go-ethereum#1482]
v0.9.39
I am still getting the "nonce too low" error when I try to create many new contracts / calls (sends) quickly. I'm even using the sync versions so it's not like there could be a race condition or anything - what's going on? I'm stuck writing support code like "if not in pending or confirmed, retry"...

**Comment by tgerring** [comment]
How are you creating the transactions? i.e. via RPC, console, etc

Last night, I successfully [spammed 3000 transactions](https://www.reddit.com/r/ethereum/comments/3djjy6/vitalik_asks_for_massive_spam_please_help_us_here/) from the same address with no problem

**Comment by tgerring** [comment]
Tried spamming again and got this after ~1700 successive transactions:

```
> spam()
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
Nonce too low
    at InvalidResponse (<anonymous>:-59655:-7)
    at send (<anonymous>:-117559:-7)
    at sendTransaction (<anonymous>:-106295:-7)
    at spam (<anonymous>:-45:-7)
    at <anonymous>:1:1
```

**Comment by tymat** [comment]
I occasionally get this even on my private test net.

**Comment by fjl** [comment]
@tgerring One reason why this could happen with automatic (chosen by geth) nonce values is that the way `xeth` assigns the nonce is inherently racy. It reads the nonce from the txpool's `ManagedState` and then submits the tx. If one or more requests do this at the same time, they can assign the same nonce twice. I'm not saying that there should be a lock around tx submission, just noting this here because you might find this interesting.

**Comment by nmushegian** [comment]
> I'm not saying that there should be a lock around tx submission

Any reason not to? The nonce requirements force transactions to be sequential anyway

**Comment by obscuren** [comment]
Because it can be better done elsewhere without the requirements of locking up transaction submission

**Comment by fjl** [comment]
The master issue for this is now: #1662.
