### ISSUE TITLE
Faucet fails for named gitsts

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#14821]
If you name the gist it will not work with the faucet - and this turns people away from the wonderful rinkeby.

Context: https://www.reddit.com/r/ethereum/comments/6ns100/first_transaction_with_walleth_on_the_main_network/

example working:
https://gist.github.com/veox/aeedf036887e0688f9bc7d092f1fb925

example not working:
https://gist.github.com/veox/f89113a087c84013f139099264e0cf2c

**Comment by veox** [comment]
Partial copy-paste from reddit (that's me bringing it up there):

-----

Tried Firefox, too - it errors out differently, with a red-background pop-up mid-screen saying:

> No Ethereum address found to fund

If I give it the [gist link](https://gist.github.com/veox/f89113a087c84013f139099264e0cf2c) or [gist link to specific file](https://gist.github.com/veox/f89113a087c84013f139099264e0cf2c#file-eth-rinkeby-addr), and

> Anonymous Gists are not allowed

if I give it a link to the [raw gist file](https://gist.githubusercontent.com/veox/f89113a087c84013f139099264e0cf2c/raw/665e6192ce954c04ef866645a5b68faa02132eb8/eth-rinkeby.addr).

-----

This is on Firefox 54.0.

Chromium 59.0.3071.115 doesn't work, too, possibly for the same reason.

All on Arch Linux, last updated on 2017-06-30. (Although it's unlikely to be OS-dependent, since @ligi [says on reddit](https://www.reddit.com/r/ethereum/comments/6ns100/first_transaction_with_walleth_on_the_main_network/dkbwp2c/) the gist-with-desc doesn't work for him, too.

**Comment by karalabe** [comment]
That's an odd one, because it works for my named gist https://gist.github.com/karalabe/14ee7fe64709bf54f874ca81f002c6f0

**Comment by karalabe** [comment]
Hmmm, https://api.github.com/gists/f89113a087c84013f139099264e0cf2c contains an extra trailing `\n` in the gist.

**Comment by karalabe** [comment]
https://github.com/ethereum/go-ethereum/pull/14824 should fix it.

**Comment by ligi** [comment]
Great - and super fast as always - 2h from reporting to PR - big up go team!

**Comment by karalabe** [comment]
Fixed and deployed!

![faucet](http://i.imgur.com/NF12NLp.png)
