### ISSUE TITLE
Port chain events over to Feed

### ISSUE THREAD

**Issue by tailingchen** [ethereum/go-ethereum#14840]
According to [comment](https://github.com/ethereum/go-ethereum/pull/14808#issuecomment-315699891), I think it’s a good change to replace all `TypeMux` to `Feed`. I’m willing to do this and have some ideas.
Due to a `Feed` can only be used with a single type. I’d like to add `FeedPool` to maintain all feeds have subscribed, like the following:
```
type FeedPool struct {
        ...
        mu    sync.RWMutex
        feeds map[reflect.Type]*Feed
}
```
In this way, we can subscribe and send any events through one `FeedPool` instead of passing many Feed to a function.
Any comments and suggestions are welcome.

**Comment by yutelin** [comment]
TypeMux causes performance issues since it centralizes all event handling in one place.

**Comment by tailingchen** [comment]
I think `centralizing all event handling in one place` is not a quite big problem.  The issue of `TypeMux` is that subscriptions of the same event might wait for each other due to the channel of the subscription is full.

**Comment by fjl** [comment]
An issue with `TypeMux` (unrelated to the blocking send) is that it is passed around as an object. This obscures dependencies between components because once an object has reference to the `TypeMux`, it can subscribe to any event sent on it.

The original motivation for `Feed` was that this should change so that subscribers should track the *producer* of the events (e.g. to get chain events, your object should call `SubscribeXXX` on the `BlockChain` object. You can see an example [here](https://github.com/ethereum/go-ethereum/issues/1867#issuecomment-233182850).

**Comment by fjl** [comment]
To be more clear: I think `FeedPool` is not a good solution. Instead, we should focus on removing uses of `TypeMux` where possible, adding `SubscribeXXX` methods for individual events and calling them. This can happen across multiple small PRs.

**Comment by tailingchen** [comment]
@fjl Thanks for your suggestions. As your said, the `FeedPool` is not a proper design. I will try `SubscriptionScope` to manage multiple subscriptions in  component.

**Comment by fjl** [comment]
Done in 1.7.0. Thank you so much!
