### ISSUE TITLE
Clique mining gets stuck with a signer that shouldn't exist

### ISSUE THREAD

**Issue by OniReimu** [ethereum/go-ethereum#14948]
#### System information

Geth version: `geth 1.7.0`
OS & Version: Linux/OSX

#### Actual behaviour

I am not sure if it is a bug or I missed something important. 
I have got two signers, Signer_1 and Signer_2, the number of consecutive blocks out of which a signer can sign one was floor(2/2+1)=2. Now I get the root admin of one of the signers, say Signer_2, and `rm -rvf data/` that includes all necessary data when `geth --datadir account new` and `geth --datadir init`. Then I come back to Signer_1 and do `clique.getSigners()`, found that the address of Signer_2 still exist, which means `SIGNER_LIMIT` still equals to 2, and if I run `miner.start()` on Signer_1, I will indefinitely get stuck with message `Signed recently, must wait for others`. Besides, `clique.propose(Addr, true/false)` does not work here either (may be because of the insufficient votes? Only one signer is working, Signer_1. The other one has been deleted by removing the directory). Although I tried to rebuild a node for Signer_2, but it was with a different address that even cannot be added into the signer list due to the inexistence of the old address of Signer_2 unexpectedly existing in the signer list. Unfortunately, I couldn't find any available function to delete this old address from signer list without a normal proposals.
Other than start it over, any ideas with this?

**Comment by karalabe** [comment]
Well, how did you expect the network rules to change just because you deleted a folder from your computer?

The list of authorized signers remains constant until the majority signers proposes to make changes to it. You need majority consensus to both add and remove signers from that list. In your case, you need both keys to modify the authorization list. If you irreversibly deleted one key, you are pretty much out of luck.
