### ISSUE TITLE
Mining on Intel Xeon Phi - KNL-F 7250

### ISSUE THREAD

**Issue by galindro** [ethereum/go-ethereum#14992]
Is it possible to use geth with Intel Xeon Phi KNL-F 7250 CPU? Is it prepared to use all the processor features? Can I use it with a mining pool or is it best for solo mining?

**Comment by karalabe** [comment]
Geth itself does not support running the miner on a GPU or the Phi. I'm unsure if there's a port to the Phi, I was considering doing it at some point, but since long term we're moving away from mining, I see my efforts more valuable elsewhere. Perhaps you can ask over at the Genoil folk who are maintaining their own port of ethminer https://github.com/Genoil.

**Comment by galindro** [comment]
https://github.com/Genoil/cpp-ethereum/issues/279
