### ISSUE TITLE
Why is the blockchain folders size very different?

### ISSUE THREAD

**Issue by coldlar** [ethereum/go-ethereum#15037]
#### System information

Geth version: `geth 1.6.5`
OS & Version: Linux

#### Expected behaviour
I have more different platform all node wallet. on Linux, Windows, Mac.
On one linux, The chaindata folders size is `148G+`;
other Linux, The chaindata folders size is `80G+`, `100G+`, etc... and I set a new server chaindata folder size is `55G+` at 2 days ago.
**bigest**:
```bash
~/.ethereum/geth/chaindata# du -sh
148G    .
~/.ethereum/geth/chaindata# ls | wc -l
75232
```
**smallest**:
```bash
~/.ethereum/geth/chaindata# du -sh
55G     .
~/.ethereum/geth/chaindata# ls | wc -l
30185
```
the same of start up agrs, all is Ubuntu.

My start up args:
```bash
nohup ./geth --rpcaddr 0.0.0.0 --rpc --rpcport 22333 --rpccorsdomain "http://localhost:3000" --rpc    api "eth,net,web3,personal" &
```
`They are all in good condition`

The difference is so great, I don't understand.
the bigest folder is 148G+ and the smallest is 54G+, Nearly 3 times as much space.
Shouldn't the BlockChain data be the same?

Is there any unnecessary data inside the chain?

#### Actual behaviour
Shouldn't it be all the same of chaindata?

**Comment by PersonaOnTheRun** [comment]
When you start a new geth on a fresh computer it doesn't download the entire blockchain. 

If you did your sync using --fast it only downloads the receipts. [This thread talked about it a bit more.](https://ethereum.stackexchange.com/questions/1161/what-is-geths-fast-sync-and-why-is-it-faster)

`Instead of processing the entire block-chain one link at a time, and replay all transactions that ever happened in history, fast syncing downloads the transaction receipts along the blocks, and pulls an entire recent state database.`

**Comment by holiman** [comment]
^What @PersonaOnTheRun said . Closing this..
