### ISSUE TITLE
Geth doesn't handle retrieving pending logs

### ISSUE THREAD

**Issue by hectorchu** [ethereum/go-ethereum#15166]
#### System information

Geth version: 1.7.0-stable
OS & Version: OSX
Commit hash : (if `develop`)

#### Expected behaviour
contract.allEvents({fromBlock: 0, toBlock: 'pending'}).get(callback)
returns logs for the contract in both the blockchain and pending transactions

#### Actual behaviour
Returns an empty list in 1.7
Hangs in busy loop in 1.6

#### Backtrace

````
[backtrace]
````

#### Notes
func (f *Filter) unindexedLogs(ctx context.Context, end uint64) ([]*types.Log, error) {
in eth/filters/filter.go#178
f.begin = 0 and int64(end) = -2 (the pending enum) so loop doesn't execute

In Geth 1.6 the loop is
func (f *Filter) getLogs(ctx context.Context, start, end uint64) (logs []*types.Log, blockNumber uint64, err error) {
in eth/filters/filter.go#170
start = 0 and end = uint64(-2) so loop doesn't terminate

**Comment by mrz5018** [comment]
It looks like `toBlock: 'latest'` gets away with it because of a check in `func (f *Filter) Logs(ctx context.Context) ([]*types.Log, error)`.  In that function there is a check to replace `-1` ('latest') here:

```
	if f.begin == -1 {
		f.begin = int64(head)
	}
	end := uint64(f.end)
	if f.end == -1 {
		end = head
	}
```

I'm new here, so I definitely could be wrong, but it seems like 'pending' doesn't actually have a block number properly assigned to it.  So, those conditional checks in `Logs` could probably just be modified to check for -1 or -2.  Does that sound right?

If that seems reasonable I could open up a pull request to fix that.

**Comment by bogatyy** [comment]
Bumping this. Given debug_traceTransaction exists, is it possible to add the functionality to simulate events in pending transactions as well?
