### ISSUE TITLE
[iOS] Support bitcode

### ISSUE THREAD

**Issue by michaelScoff** [ethereum/go-ethereum#15213]
#### System information

Geth version: 1.7
OS & Version: OSX
Commit hash : latest

#### Expected behaviour

Successfully compiled

#### Actual behaviour

`Geth` lib does not have support for bitcode

#### Steps to reproduce the behaviour

- Integrate Geth via Cocoapods
- Compile Xcode build with bitcoin enabled.

#### Backtrace

````
'/Users/..../Pods/Geth/Frameworks/Geth.framework/Geth(000002.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/.../Pods/Geth/Frameworks/Geth.framework/Geth' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
````

**Comment by michaelScoff** [comment]
@karalabe Hey Peter, how much work involved to implement this? this doubles size of the app, just one library that does not have support for bitcode.

**Comment by ronaldmannak** [comment]
@michaelScoff How were you able to use Cocoapods for OSX? The [podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/5/b/b/Geth/1.7.1-unstable.11080/Geth.podspec.json) only seems to support iOS.

**Comment by michaelScoff** [comment]
@ronaldmannak I meant to create this issue regarding `iOS`, do you know how hard would it be to support bitcode for this repo?

**Comment by fjl** [comment]
We cannot offer bitcode because the Go compiler can't emit it. This might change in the future, but there is no way at the moment. See https://github.com/golang/go/issues/12682 for details. 

I know bitcode is important to iOS folks and we will definitely add support for it if, say, the llgo compiler gets mature enough to support our codebase. But don't hold your breath.
