### ISSUE TITLE
personal_unlockAccount format

### ISSUE THREAD

**Issue by xallavon** [ethereum/go-ethereum#15293]
#### System information

Geth version: `geth version 1.7.1`
OS & Version: Linux

#### Expected behaviour
JSONRPC request `personal_unlockAccount('0xaccount', 'secret', '0x100')`
will unlock account '0xaccount'.

#### Actual behaviour
I receive following error

```
(-32602, 'invalid argument 2: json: cannot unmarshal string into Go value of type uint64')
```

According to [wiki](https://github.com/ethereum/wiki/wiki/JSON-RPC#hex-value-encoding) I thought that last parameter should be treated as `QUANTITY` and encoded as hex. It worked in some previous versions and it works in parity. IMO this should be at least described in wiki & standardized, so that we could safely switch between `geth` and `parity` if we use the same api subsets.

**Comment by sivachaitanya** [comment]
3rd input parameter to personal_unlockAccount should be 0

**Comment by SinErgy84** [comment]
**PUSH** / **REOPEN***

The issue still exists. It is a contradiction of its own documentation, compare https://eth.wiki/json-rpc/API#hex-value-encoding
All other endpoints require a clean conversion from numeric values to their HEX representation.
personal_unlockAccount and its third parameter for the duration is the only method that deviates from this rule and is implemented incorrectly in my opinion.

Apparently other developers got used to it after implementation and it works. But interoperability between different clients is not possible because Geth handles it differently than e.g. Parity/OpenEthereum or Erigon.
