### ISSUE TITLE
websocket.Dial ws://stats.rinkeby.io/api: bad status

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#15290]
on one device (NXP i.MX6UL) I am always getting "bad status" from rinkeby stats.

```
 WARN [10-13|12:35:43] Stats server unreachable                 err="websocket.Dial ws://stats.rinkeby.io/api: bad status"
```

Interestingly I can connect to the stats-server on another device. Also I can sync the chain on this device and ping stats.rinkeby.io.

**Comment by karalabe** [comment]
The ethstats client doesn't know whether the server is running `ws` or `wss`, so unless explicitly specified, it tries one, then the other, then one, then the other, etc. (first it tries `wss`). If `wss` fails for some reason (e.g. timeout), it may try `ws`, which should return the bad status since the server only speaks secure ws. It should however switch to `wss` and succeed eventually.

**Comment by ligi** [comment]
thanks!

**Comment by ligi** [comment]
Hm but there seems to be some problem - got it to show up at some point - but it is flaky:
"liat" is the name of this node running above.
![selection_158](https://user-images.githubusercontent.com/111600/31567431-c6715a5a-b06f-11e7-988f-7711c6ca99d8.png)

**Comment by mnoster** [comment]
I am having the same issue with the rinkeby stats ws connection
![bad network](https://user-images.githubusercontent.com/16027973/36761597-a9afcdea-1bd4-11e8-8da2-acb3acfa5dc8.PNG)

**Comment by jonnyhsy** [comment]
Seems rinkeby site is down

**Comment by karalabe** [comment]
Sigh, every month or so, docker just goes up to 100% CPU usage and hangs everything. Restarted the frontend machine now.
