### ISSUE TITLE
How can I get transactions invoked by contract

### ISSUE THREAD

**Issue by gaoxiangxyz** [ethereum/go-ethereum#15307]
I tried to get all transactions of an ether account from blockchain using web3. But if ether is sent to the account by 'send' or 'transfer' function in contract, there is only a transaction from caller address to contract address  got by web3.eth.getTransaction. 

How to do  to find whether the contract call has some transactions related to the account?
How can I get transactions invoked by contract like [Invoked Transactions in etherchain.org](https://etherchain.org/tx/0x0a9337b4180961dd4a9eea09d42bf9133f0cb15fe629f0bb18691caf825c0bb9).

Thanks.

**Comment by karalabe** [comment]
Currently there is no way to get internal transactions. Geth does feature a JavaScript transaction tracer that can be used to trace and find internal transactions, though it could probably use some tutorials. There isn't any pre-baked-in functionality to get the internal calls.

**Comment by gaoxiangxyz** [comment]
@karalabe  thanks a lot.
Could you provide the url of these tutorials?

Another question, if a contract call fail (such as throw error, out of gas, invalid bytecodes), is there a transaction in block chain for this fail call? If there is, how to know it is a fail transaction?

**Comment by dartkinselok** [comment]
@gaoxiangxyz for internal transactions and tracing of failed calls we're using Parity. Maybe you should look at this: https://github.com/paritytech/parity/wiki/JSONRPC-trace-module#trace_transaction

Hope it helped you 😇

**Comment by isLishude** [comment]
Maybe fix this by a hard fork

**Comment by holiman** [comment]
Closing this since it has been answered by Peter. Follow-up answers:

- How to know an address is account address or contract address
You can't, really... But if it has code, it's a contract. If it has an outgoing transaction, it's an end-user accont. 

- if a contract call fail (such as throw error, out of gas, invalid bytecodes), is there a transaction in block chain for this fail call? If there is, how to know it is a fail transaction?

Yes, unless it 'failed' due to too little balance on the account. You should find it on e.g etherscan or see the receipt via geth rpc interface.
