### ISSUE TITLE
change from MD5 to SHA256 for geth download checksum's

### ISSUE THREAD

**Issue by AdrianScott** [ethereum/go-ethereum#15315]
change from MD5 to SHA256 for geth download checksum's

**Comment by RichHorrocks** [comment]
I'm suspecting that MD5 is used, rather than a "stronger" algorithm, because it's only being used as a way to check the integrity of the download (i.e. to check the file downloaded without any errors), rather than as a way to check its provenance. And for this, MD5 is probably as good as anything else.

If we wanted to go a step further, rather than just providing a checksum, we could provide GPG signatures in the form of `.asc` files, and [do what the Tor project does](https://www.torproject.org/docs/verifying-signatures.html.en). Perhaps overkill?

**Comment by karalabe** [comment]
The checksums are the ones the Azure blobstore provides. They only support MD5, hence why we added it as a sanity check. If you want to make sure the file has not been tampered with, I'd advise to verify the attached signatures instead of relying on checksums.

**Comment by AdrianScott** [comment]
Great, thanks
