### ISSUE TITLE
Initial sync very slow with --syncmode "fast"

### ISSUE THREAD

**Issue by snodo** [ethereum/go-ethereum#15326]
#### System information
Debian 9
- Linux 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2 (2017-06-12) x86_64 GNU/Linux
- Virtual Machine (VirtualBox on Windows 10 Host)
- i7-7700k (all 4 cores passed to the vm)
- 6 GB RAM
- HDD

Geth
- Version: 1.7.3-unstable
- Git Commit: e9295163aa25479e817efee4aac23eaeb7554bba
- Architecture: amd64
- Protocol Versions: [63 62]
- Network Id: 1
- Go Version: go1.7.4
- Operating System: linux
- GOPATH=
- GOROOT=/usr/lib/go-1.7

#### Expected behaviour
Fast sync until the end.
Download full blockchain first, start downloading states AFTER the chain is (nearly) complete.

#### Actual behaviour
Very fast sync up to ~90% (took only about 1 hour)
Then it starts doing weird things during sync.
Geth does not only import new block headers and receipts but already starts downloading state entries. This consumes very high amount of RAM and slows down the vm dramatically.
Sync process took ~2hours for gaining 1%.
Restarting Geth process does not really help. It starts downloading block headers and receipts at first but after a few minutes those state entry downloads start again.

#### Steps to reproduce the behaviour
- clean debian 9 install
- install dependencies with apt-get
- download geth from git and compile
- geth --syncmode "fast" --cache 2048 --rpc
(I tried more and less cache -> did not get any improvement)

**Comment by karalabe** [comment]
Syncing Ethereum currently is very very hard with an HDD. I'd really recommend using an SSD for it.

**Comment by snodo** [comment]
That doesn't really solve my problem.
After all this mess I tried to run the same command on a faster VPS with a little more RAM and an SSD.
- 4 cores of a Xeon E5-2680
- 8 GB RAM
- SSD

It was less than 1 hour for ~93 % of sync.
But then the same problems started:
RAM usage went up to 100%. Sadly I was not allowed to setup SWAP on my VPS so the geth process crashed.
After restarting geth it took a few minutes until RAM was full again. But in these few minutes before the crash about 1-2% got synced.
So I had to restart geth about 5 times until it was fully synced.

Now it's running fine 24/7 and is always up to date. In this mode it uses "only" ~2.5 GB of RAM.

**Comment by philiparthurmoore** [comment]
@snodo Does your setup adequately cover doing day-to-day work with `geth` running in the background? I'm currently running `geth --syncmode "fast" --cache 2048` and CPU load seems totally fine but it's taking up around 3G RAM. My system has 16GB so both Ethereum and Zcash daemons are running without any issues after the initial sync but I wanted to check in and see how your system has been holding up.

**Comment by karalabe** [comment]
Syncing Ethereum is a pain point for many people, so I'll try to detail what's happening behind the scenes so there might be a bit less confusion.

The current default mode of sync for Geth is called fast sync. Instead of starting from the genesis block and reprocessing all the transactions that ever occurred (which could take weeks), fast sync downloads the blocks, and only verifies the associated proof-of-works. Downloading all the blocks is a straightforward and fast procedure and will relatively quickly reassemble the entire chain.

Many people falsely assume that because they have the blocks, they are in sync. Unfortunately this is not the case, since no transaction was executed, so we do not have any account state available (ie. balances, nonces, smart contract code and data). These need to be downloaded separately and cross checked with the latest blocks. This phase is called the state trie download and it actually runs concurrently with the block downloads; alas it take a lot longer nowadays than downloading the blocks.

So, what's the state trie? In the Ethereum mainnet, there are a [ton of accounts already](https://etherscan.io/chart/address), which track the balance, nonce, etc of each user/contract. The accounts themselves are however insufficient to run a node, they need to be cryptographically linked to each block so that nodes can actually verify that the account's are not tampered with. This cryptographic linking is done by creating a tree data structure above the accounts, each level aggregating the layer below it into an ever smaller layer, until you reach the single root. This gigantic data structure containing all the accounts and the intermediate cryptographic proofs is called the state trie.

Ok, so why does this pose a problem? This trie data structure is an intricate interlink of hundreds of millions of tiny cryptographic proofs (trie nodes). To truly have a synchronized node, you need to download all the account data, as well as all the tiny cryptographic proofs to verify that noone in the network is trying to cheat you. This itself is already a crazy number of data items. The part where it gets even messier is that this data is constantly morphing: at every block (15s), about 1000 nodes are deleted from this trie and about 2000 new ones are added. This means your node needs to synchronize a dataset that is changing 200 times per second. The worst part is that while you are synchronizing, the network is moving forward, and state that you begun to download might disappear while you're downloading, so your node needs to constantly follow the network while trying to gather all the recent data. But until you actually do gather all the data, your local node is not usable since it cannot cryptographically prove anything about any accounts.

If you see that you are 64 blocks behind mainnet, you aren't yet synchronized, not even close. You are just done with the block download phase and still running the state downloads. You can see this yourself via the seemingly endless `Imported state entries [...]` stream of logs. You'll need to wait that out too before your node comes truly online.

---

**Q: The node just hangs on importing state enties?!**

A: The node doesn't hang, it just doesn't know how large the state trie is in advance so it keeps on going and going and going until it discovers and downloads the entire thing.

The reason is that a block in Ethereum only contains the state root, a single hash of the root node. When the node begins synchronizing, it knows about exactly 1 node and tries to download it. That node, can refer up to 16 new nodes, so in the next step, we'll know about 16 new nodes and try to download those. As we go along the download, most of the nodes will reference new ones that we didn't know about until then. This is why you might be tempted to think it's stuck on the same numbers. It is not, rather it's discovering and downloading the trie as it goes along.

**Q: I'm stuck at 64 blocks behind mainnet?!**

A: As explained above, you are not stuck, just finished with the block download phase, waiting for the state download phase to complete too. This latter phase nowadays take a lot longer than just getting the blocks.

**Q: Why does downloading the state take so long, I have good bandwidth?**

A: State sync is mostly limited by disk IO, not bandwidth.

The state trie in Ethereum contains hundreds of millions of nodes, most of which take the form of a single hash referencing up to 16 other hashes. This is a horrible way to store data on a disk, because there's almost no structure in it, just random numbers referencing even more random numbers. This makes any underlying database weep, as it cannot optimize storing and looking up the data in any meaningful way.

Not only is storing the data very suboptimal, but due to the 200 modification / second and pruning of past data, we cannot even download it is a properly pre-processed way to make it import faster without the underlying database shuffling it around too much. The end result is that even a fast sync nowadays incurs a huge disk IO cost, which is too much for a mechanical hard drive.

**Q: Wait, so I can't run a full node on an HDD?**

A: Unfortunately not. Doing a fast sync on an HDD will take more time than you're willing to wait with the current data schema. Even if you do wait it out, an HDD will not be able to keep up with the read/write requirements of transaction processing on mainnet.

You however should be able to run a light client on an HDD with minimal impact on system resources. If you wish to run a full node however, an SSD is your only option.

**Comment by gaia** [comment]
@karalabe would you say that in 2022 NVME is required or is SSD still enough?
