### ISSUE TITLE
The `misspell` linter is broken on CI

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#15371]
A while ago we've integrated the https://github.com/client9/misspell Go linter into our CI workflow to get rid of the annoying spelling errors. This worked well for a year or so, when `misspell` itself broke https://github.com/client9/misspell/issues/105 and CI started failing. There appear no willingness from the `misspell` contributors to fix this error, so we should pin an early version of `misspell` and reenable it on Travis.

This task would entail investigating if the above issue still persists, and if so, https://github.com/ethereum/go-ethereum/blob/master/build/ci.go#L313 should be extended with version pinning to it checks out the version of misspell that did not have this issue. Alternatively we can also try to work around it. Either way, to goal is to have misspell running agian.

**Comment by cpurta** [comment]
`go get` pulls from the HEAD of the repository, since it is assumed that HEAD is stable. If the developers are unwilling to make any changes to fix it, it may be worth forking the repo and making the changes and then using `go get` on the fixed fork. The only issue there is that if you wanted any of the most recent changes from misspell repo you would have to merge that into the fork. It is kind of an odd work around to the issue but without the use of a dependency manager there does not appear to be another way to fix this. 

Seeing as there are submodules you could perhaps add that and not have to perform a `go get` and just have the submodule point to a commit that is stable for CI.

**Comment by karalabe** [comment]
Yeah, though maybe the best solution would be to somehow implement a fix that gets accepted upstream. We definitely don't want to maintain our own misspell package :D
