### ISSUE TITLE
Syncing with testnet fails on Raspberry Pi

### ISSUE THREAD

**Issue by Areman66** [ethereum/go-ethereum#15445]
#### System information

Geth version: `1.7.2-stable`
OS & Version: Linux raspberrypi 4.9.59-v7+ (Raspberry PI 3 model B) 
Commit hash : 1db4ecdc0b9e828ff65777fb466fc7c1d04e0de9

Hi guys,
geth works fine when syncing with main net but when I try to sync with the testnet, it keeps failing. It drops peers constantly. I have no clue what might be causing the problem. Any help would be most appreciated.

**Comment by karalabe** [comment]
Could you please provide some logs?

**Comment by Areman66** [comment]
I am such a newbie. Would you please tell me what sort of logs you mean and how I should extract them?

**Comment by holiman** [comment]
The basic logs would be what geth spits out on the commandline. If you run geth with e.g. 
`geth  &> log.txt` , you should get some more info. 

There are also options to increase the verbosity for certain areas, but that would be a good start. Personally, I've noticed that when there's a slow disk, it results in peers being dropped since the disk issues cause you to become an unresponsive peer. 

To see what kind of speeds you're getting, this can be a good start. On my ssd:  
```
$dd if=/dev/zero of=/tmp/output conv=fdatasync bs=384k count=1k; rm -f /tmp/output
1024+0 records in
1024+0 records out
402653184 bytes (403 MB, 384 MiB) copied, 0,944079 s, 427 MB/s
```

**Comment by Areman66** [comment]
Folks! Thank you so much for your prompt responses. I don't know why and how but it started to work all of a sudden just the day after I posted this issue.
Thank you again
