### ISSUE TITLE
--password on CLI

### ISSUE THREAD

**Issue by x011** [ethereum/go-ethereum#15444]
#### System information

Geth version: `Version: 1.7.2-unstable`
OS & Version: `Linux CentOS 7 - x64`

#### Expected behavior
Accepting a password on the command line (`--password`) instead of a file path.

#### Actual behavior
`--password ` throws an error if the password is supplied directly.

#### Steps to reproduce the behavior
 `geth --password <(echo -n notsosecret) account new` as mentioned on the [wiki page](https://github.com/ethereumproject/go-ethereum/wiki/Command-Line-Options#sample-usage-in-testing-environment)  

#### Backtrace

````
[backtrace]
````

**Comment by holiman** [comment]
I'm not sure what you mean. This works fine for me: 
```
#build/bin/geth --datadir /tmp/foo --password <(echo -n notsosecret) account new
WARN [11-10|09:15:30] No etherbase set and no accounts found as default 
Address: {3d37a6ead37e41d30f99eb87504938ddceb0f6a3}
```
Are you making a feature-request for  `geth --password "mypassword"` , or does the code above not work for you? 

In case it's the former, I don't think that's a good idea, since it encourages users to feed passwords via commandline, which is a bad practice (it's saved in bash history). 

I'm going to close this ticket, but please reopen in case I misunderstood, and something is actually broken.
