### ISSUE TITLE
Make puppeth play nice with domainless setups

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#15472]
Originally Puppeth was implemented so it can run web services both on raw ports on domain-less machines, as well as using port sharing behind reverse proxies and domains. Since we mostly used Puppeth in house for Rinkeby only, the domain-less mode of operation got broken without anyone noticing.

This issue is here to verify which functionality works still correctly and which got broken for domain-less setups and to patch them up. Note, this issue should only be started when https://github.com/ethereum/go-ethereum/pull/15390 is merged since that's a huge pending change.

**Comment by corpetty** [comment]
For what its worth:

Deploying to remote servers using `user@ip` for each server setup works for:
- Ethstats
- Bootnode
- Sealnode
- Faucet

Not Dashboard

Because I've only tested the current 1.7.3 version (not Devcon demo), it is hard to say if those changes broke or fixed some of the issues I currently have.  

I also deploy each instance on separate ports.

**Comment by owocki** [comment]
hey @karalabe --  👋  hi there.. kevin from gitcoin.  im considering putting a bounty on this issue (or the other [help wanted issues on this repo](https://github.com/ethereum/go-ethereum/labels/help%20wanted)) to help you all get some fresh interest on them.  any objection?  are there specific github issues that would make good test bounties?  ill bring the budget, you just tell me what you want.

**Comment by corpetty** [comment]
Port sharing also doesn't work with domain-less deployments.  I'll be playing around on a homenetwork of servers and VMs this month. I'll have more info on what doesn't work as time continues.
