### ISSUE TITLE
Getting "transaction underpriced" for low gas txs

### ISSUE THREAD

**Issue by danfinlay** [ethereum/go-ethereum#15612]
When a user submits a transaction, they may bid a low gas transaction, but that doesn't mean anything absolute about the lowest possible price, it just reflects how long a user might wait for the transaction to be processed.

What does the "Transaction underpriced" error mean, can it be disabled, or can its floor be lowered?

This has become a common error for new users of CryptoKitties on MetaMask.

**Comment by mcdee** [comment]
Geth has a minimum gas price, which is configurable for each node with the `--txpool.pricelimit` option.  If you attempt to submit a transaction to a node with a lower price than the node's pricelimit it will refuse it with this error.

Note that just dialling down the price limit on a local node won't necessarily help: your local node will accept the transaction but if none (or very few) of the mining nodes will accept the transaction (due to their own price limit) it won't be mined and different nodes end up with different pool information (which becomes lots of fun to debug for the user).

**Comment by danfinlay** [comment]
Thanks for the tip, Jim!  We've been seeing it fluctuate wildly, but Infura is going to try hard-coding it lower, now that MetaMask supports re-submitting with a higher gas price.

**Comment by wupeaking** [comment]
I have same issue when I use SuggestGasPrice to set gasPrice ,  the txpool.pricelimit is default.

**Comment by CrispinFlowerday** [comment]
FYI, This was affecting us, and I have put in a PR (https://github.com/ethereum/go-ethereum/pull/16576) to fix this issue with local transactions
