### ISSUE TITLE
err="waiting for transactions"

### ISSUE THREAD

**Issue by sevenMonkey** [ethereum/go-ethereum#15646]
#### System information

Geth version:  1.7.3-stable
OS & Version: OSX
Commit hash : 

#### Expected behaviour
Occurs this error when I startup the geth client, I can't search the question in google
```
geth --datadir "~/Library/Ethereum/ethdev" --dev
```
WARN [12-11|11:31:52] Block sealing failed                     err="waiting for transactions"

#### Actual behaviour
```
geth --datadir "~/Library/Ethereum/ethdev" --dev
```
WARN [12-11|11:31:52] Block sealing failed                     err="waiting for transactions"

#### Backtrace

````
[backtrace]
````

**Comment by Aofzazgithub** [comment]
Amazing

**Comment by renankruger** [comment]
Same here, we cannot start a dev network.

**Comment by karalabe** [comment]
In dev mode, the node only mines if there are transactions. Make a transaction and the node will mine it.

**Comment by drozdziak1** [comment]
I know this is pretty old, but what can I do if I'd like to locally test code which relies on confirmations?

**Comment by karalabe** [comment]
You can force dev mode to seal blocks periodically instead of waiting for transactions via `--dev.period=3` (for a 3 second period). You lose instant transactions though. Would that be enough?

**Comment by MicahZoltu** [comment]
@karalabe Is it possible to get the instant-block functionality via `genesis.json` instead of `--dev`?  I have a `genesis.json` that is setup a certain way for our project, but I am using `clique` which appears to have a minimum of `1` second blocks.  If I try to use `--dev` geth complains because the rest of my settings are not compatible with that mode.
