### ISSUE TITLE
Research alternatives to leveldb (like badger)

### ISSUE THREAD

**Issue by cdetrio** [ethereum/go-ethereum#15717]
As [discussed](https://github.com/ethereum/pm/issues/28#issuecomment-351972476) on All Core Devs meeting 30, there is already an experimental branch that replaces leveldb with [badger](https://github.com/dgraph-io/badger): https://github.com/fjl/go-ethereum/tree/badger-exp

Badger has since been updated, so it would be interesting to try again with the latest badger and run some benchmarks, especially with a large database (30gb+).

**Comment by fjl** [comment]
Badger's API has changed a lot since the experiment. It now features a transaction-based API, i.e. the only way to use the database is:

```go
err := db.Update(func(tx *badger.Txn) error {
    // write to tx
})
```

This is incompatible with our use of leveldb. I've tried to convert go-ethereum to use this style of database access in the past, but there's just too much code that uses the DB directly. Notably, converting to this style would also give us the option to try out boltdb (a mature KV store) and most SQL databases.

**Comment by philoctetes409bc** [comment]
no.... that won't really solve anything really. the problem you're thinking of is that it's quite slow to search but thats because its not indexed. To do this on the level that etherscan works, you would need to use something like solr/lucene to index the blockchain transactions, block ids, addresses, ect.

**Comment by ArchetypicalDude** [comment]
Hi guys,

I did some tinkering the last few days with LevelDB's BlockSize and CompactionTableSize. Could get some minor improvements on block processing speed on a fully synced node, but really nothing to write home about.

I am pretty inexperienced in go but I'm beginning to find my way through the geth code. I'm planning to spend a few hours per day the next weeks to try and find some database improvements, including trying some different database implementations like badger.

Just thought I'd let you know. Very thankful for any suggestions on how to best proceed, for now I'm just hacking away :)

**Comment by ArchetypicalDude** [comment]
Finally got a full sync with badger working :) Will commit the code the somewhere shortly after I have cleaned up a bit. Had to build another badger-specific-cache to really utilize batch writes and vandalized quite a bit of the existing cache-code...

`INFO [02-18|09:24:38] Imported new chain segment               blocks=1  txs=182  mgas=7.923   elapsed=190.492ms mgasps=41.590  number=5111857 hash=7afaee…29989d cache=303.06mB
INFO [02-18|09:25:26] Imported new chain segment               blocks=1  txs=96   mgas=7.927   elapsed=109.296ms mgasps=72.524  number=5111858 hash=b879d0…a64438 cache=303.23mB
INFO [02-18|09:25:50] Imported new chain segment               blocks=1  txs=178  mgas=7.950   elapsed=177.426ms mgasps=44.809  number=5111859 hash=124149…a8bddb cache=303.99mB
INFO [02-18|09:25:59] Imported new chain segment               blocks=1  txs=169  mgas=7.958   elapsed=166.438ms mgasps=47.813  number=5111860 hash=e9f4d7…ef06ea cache=304.16mB
INFO [02-18|09:26:11] Imported new chain segment               blocks=1  txs=138  mgas=5.386   elapsed=98.170ms  mgasps=54.868  number=5111861 hash=5d320b…1455fa cache=304.00mB
INFO [02-18|09:26:26] Imported new chain segment               blocks=1  txs=124  mgas=7.948   elapsed=143.951ms mgasps=55.214  number=5111862 hash=ccf757…ce47cc cache=304.19mB
INFO [02-18|09:26:29] Imported new chain segment               blocks=1  txs=80   mgas=3.336   elapsed=67.780ms  mgasps=49.219  number=5111863 hash=e93110…73a09d cache=304.03mB
INFO [02-18|09:26:50] Imported new chain segment               blocks=1  txs=102  mgas=5.134   elapsed=100.398ms mgasps=51.138  number=5111864 hash=70442f…57f599 cache=304.02mB
INFO [02-18|09:27:16] Imported new chain segment               blocks=1  txs=165  mgas=7.981   elapsed=202.147ms mgasps=39.480  number=5111865 hash=dc7d83…636a6e cache=304.70mB
INFO [02-18|09:27:26] Imported new chain segment               blocks=1  txs=83   mgas=3.670   elapsed=69.384ms  mgasps=52.893  number=5111866 hash=9c0386…e9e366 cache=304.85mB
INFO [02-18|09:27:29] Imported new chain segment               blocks=1  txs=129  mgas=7.882   elapsed=120.171ms mgasps=65.589  number=5111867 hash=ea1cf1…ea37be cache=304.75mB
INFO [02-18|09:27:40] Imported new chain segment               blocks=1  txs=20   mgas=2.126   elapsed=28.243ms  mgasps=75.264  number=5111868 hash=01c3ce…e947bb cache=304.58mB
INFO [02-18|09:27:44] Imported new chain segment               blocks=1  txs=63   mgas=7.892   elapsed=68.542ms  mgasps=115.143 number=5111869 hash=5a99d0…214815 cache=303.95mB
INFO [02-18|09:28:12] Imported new chain segment               blocks=1  txs=37   mgas=7.997   elapsed=74.055ms  mgasps=107.988 number=5111870 hash=370821…beec02 cache=303.77mB
INFO [02-18|09:28:15] Imported new chain segment               blocks=1  txs=124  mgas=7.981   elapsed=154.709ms mgasps=51.584  number=5111871 hash=d7fa00…b855bf cache=303.93mB
INFO [02-18|09:28:22] Imported new chain segment               blocks=1  txs=36   mgas=7.951   elapsed=126.091ms mgasps=63.057  number=5111872 hash=aa818b…f990d2 cache=303.74mB
INFO [02-18|09:28:35] Imported new chain segment               blocks=1  txs=140  mgas=7.988   elapsed=142.994ms mgasps=55.863  number=5111873 hash=7181b3…6579c9 cache=303.75mB
INFO [02-18|09:28:40] Imported new chain segment               blocks=1  txs=86   mgas=3.859   elapsed=76.347ms  mgasps=50.551  number=5111874 hash=71a0c9…bd138f cache=304.24mB`

**Comment by holiman** [comment]
Super! It'll be very interesting to see some benchmark comparisons

**Comment by ArchetypicalDude** [comment]
Here it is, still a bit messy I guess:
https://github.com/ArchetypicalDude/go-ethereum/commit/acdd9939ea8f686918ef247da3983b4a7d57a988

Feel free to tell me any benchmarks you would be interested in!

**Comment by ArchetypicalDude** [comment]
So time is pretty scarce at the moment, I'll just write down the results which seem most interesting to me. Did a fast-sync from scratch on a fairly powerful machine (i7, 32gb ram, SSD) until block 5207200, ~101 million state entries were downloaded. Geth-version was 1.8.3 from the master branch:

- LevelDb: Duration ~4h 45m, chaindata-size 69gb
- BadgerDb: Duration ~2h 35m, chaindata-size 159gb
- Once synced, block processing time/mgasps is pretty much exactly the same
-  Block processing duration is more dependent on number of transactions in the block, not so much on gas used in the block
- No hiccups/crashes/problems at all while syncing, geth 1.8 is really great work!

So I'd say BadgerDb offers better write performance, which is reflected in the shorter syncing-duration. Read performance is not particularly great, so there is no speed up in transaction/block processing, where lots of reads on the state database need to be performed. Not yet really sure why badger uses that much more disk space. Maybe I messed something up, maybe there is just more write amplification in the way data is stored inside BadgerDb. Will look further into these things, I enjoy hacking on go-ethereum very much. Will also try out BoltDb for sure.

**Comment by cdetrio** [comment]
@ArchetypicalDude that's great! It'd be helpful to have more detailed performance profiling, e.g. quartile and 95% measurements of the write latency. These are already available for geth leveldb usage, in go-metrics https://github.com/ethereum/go-ethereum/wiki/Metrics-and-Monitoring

Also wondering, does your branch change all geth DB usage to badger's transaction-based API?

**Comment by ArchetypicalDude** [comment]
I'll have a closer look at the existing metrics and monitoring starting tomorrow and will provide more detailed numbers :)

All data that is written to disk through the ethdb/interface.go is using the transaction-based API. Exception from that is only a very simple cache: PUTS (batch and single write operations) are first put into a map[string][]byte and are then flushed to disk in a single transaction when the map gets large enough. I think the database gets even bigger when using a transaction for every single key-value-pair, but I'll have to test that more accurately.

**Comment by ArchetypicalDude** [comment]
Implemented the metrics-module and stripped out my ghettocache to make results from the different key-value-stores more comparable (it didn't really improve things anyway). Also added a branch which uses BoltDB. Meters and Timers should get updated at the exact same function calls throughout the different implementations. I also added one Meter and two Timers to get batch operations into the statistics. Before only single PUTs were measured. They are available under:

- eth/db/chaindata/user/batchPuts
- eth/db/chaindata/user/batchWriteTimes
- eth/db/chaindata/user/batchWrites

I pulled the following stats while fast-syncing when the database gets really hammered via "debug.metrics(false).eth.db.chaindata". Used hardware is almost identical.
**LevelDB:**

> {
  compact: {
    input: {
      Avg01Min: "713.27M (11.89M/s)",
      Avg05Min: "5.19G (17.29M/s)",
      Avg15Min: "11.57G (12.85M/s)",
      Overall: "28.30G (9.99M/s)"
    },
    output: {
      Avg01Min: "713.10M (11.88M/s)",
      Avg05Min: "5.25G (17.49M/s)",
      Avg15Min: "13.35G (14.84M/s)",
      Overall: "42.53G (15.02M/s)"
    },
    time: {
      Avg01Min: "47.86G (797.73M/s)",
      Avg05Min: "304.45G (1.01G/s)",
      Avg15Min: "822.00G (913.33M/s)",
      Overall: "2.74T (969.04M/s)"
    }
  },
  user: {
    batchPuts: {
      Avg01Min: "0 (0.00/s)",
      Avg05Min: "198.69K (662.30/s)",
      Avg15Min: "6.37M (7.07K/s)",
      Maximum: "37.771µs",
      Minimum: "91ns",
      Overall: "50.33M (17.79K/s)",
      Percentiles: {
        20: "100ns",
        5: "95ns",
        50: "113ns",
        80: "179ns",
        95: "242ns"
      }
    },
    batchWriteTimes: {
      Avg01Min: "0 (0.00/s)",
      Avg05Min: "785 (2.62/s)",
      Avg15Min: "25.14K (27.93/s)",
      Maximum: "142.565341ms",
      Minimum: "454.047µs",
      Overall: "201.12K (71.08/s)",
      Percentiles: {
        20: "2.213877ms",
        5: "985.895µs",
        50: "3.222191ms",
        80: "5.679979ms",
        95: "10.00759ms"
      }
    },
    batchWrites: {
      Avg01Min: "29 (0.49/s)",
      Avg05Min: "115.63M (385.44K/s)",
      Avg15Min: "3.66G (4.07M/s)",
      Overall: "29.06G (10.27M/s)"
    },
    dels: {
      Avg01Min: "0 (0.00/s)",
      Avg05Min: "0 (0.00/s)",
      Avg15Min: "0 (0.00/s)",
      Maximum: "0s",
	  Minimum: "0s",
      Overall: "0 (0.00/s)",
      Percentiles: {
        20: "0s",
        5: "0s",
        50: "0s",
        80: "0s",
        95: "0s"
      }
    },
    gets: {
      Avg01Min: "123.67K (2.06K/s)",
      Avg05Min: "739.38K (2.46K/s)",
      Avg15Min: "3.04M (3.38K/s)",
      Maximum: "127.309714ms",
      Minimum: "4.86µs",
      Overall: "9.00M (3.18K/s)",
      Percentiles: {
        20: "6.11µs",
        5: "5.583µs",
        50: "7.396µs",
        80: "18.321µs",
        95: "39.912µs"
      }
    },
    misses: {
      Avg01Min: "12.54K (209.05/s)",
      Avg05Min: "153.60K (511.99/s)",
      Avg15Min: "765.22K (850.24/s)",
      Overall: "3.65M (1.29K/s)"
    },
    puts: {
      Avg01Min: "0 (0.00/s)",
      Avg05Min: "7.82K (26.05/s)",
      Avg15Min: "260.17K (289.07/s)",
      Maximum: "70.281715ms",
      Minimum: "4.668µs",
      Overall: "2.13M (751.22/s)",
      Percentiles: {
        20: "1.090531ms",
        5: "1.078427ms",
        50: "1.107979ms",
        80: "1.139172ms",
        95: "4.262309ms"
      }
    },
    reads: {
      Avg01Min: "49.43M (823.79K/s)",
      Avg05Min: "237.58M (791.95K/s)",
      Avg15Min: "892.23M (991.37K/s)",
      Overall: "2.57G (907.39K/s)"
    },
    writes: {
      Avg01Min: "0 (0.00/s)",
      Avg05Min: "950.92K (3.17K/s)",
      Avg15Min: "31.65M (35.17K/s)",
      Overall: "258.72M (91.43K/s)"
    }
  }
}

**BadgerDB**

> {
  user: {
    batchPuts: {
      Avg01Min: "2.42M (40.40K/s)",
      Avg05Min: "12.61M (42.03K/s)",
      Avg15Min: "39.24M (43.61K/s)",
      Maximum: "79.679µs",
      Minimum: "170ns",
      Overall: "114.33M (45.59K/s)",
      Percentiles: {
        20: "217ns",
        5: "199ns",
        50: "337ns",
        80: "566ns",
        95: "1.59µs"
      }
    },
    batchWriteTimes: {
      Avg01Min: "7.26K (121.04/s)",
      Avg05Min: "39.05K (130.16/s)",
      Avg15Min: "118.73K (131.92/s)",
      Maximum: "62.114471ms",
      Minimum: "236.188µs",
      Overall: "324.80K (129.51/s)",
      Percentiles: {
        20: "695.077µs",
        5: "538.789µs",
        50: "993.681µs",
        80: "1.70043ms",
        95: "6.248979ms"
      }
    },
    batchWrites: {
      Avg01Min: "1.06G (17.63M/s)",
      Avg05Min: "5.48G (18.26M/s)",
      Avg15Min: "15.72G (17.47M/s)",
      Overall: "40.69G (16.22M/s)"
    },
    dels: {
      Avg01Min: "0 (0.00/s)",
      Avg05Min: "0 (0.00/s)",
      Avg15Min: "0 (0.00/s)",
      Maximum: "0s",
      Minimum: "0s",
      Overall: "0 (0.00/s)",
      Percentiles: {
        20: "0s",
        5: "0s",
        50: "0s",
        80: "0s",
        95: "0s"
      }
    },
    gets: {
      Avg01Min: "395.55K (6.59K/s)",
      Avg05Min: "1.55M (5.16K/s)",
      Avg15Min: "5.97M (6.64K/s)",
      Maximum: "12.899981ms",
      Minimum: "3.748µs",
      Overall: "26.39M (10.52K/s)",
      Percentiles: {
        20: "6.305µs",
		5: "4.746µs",
        50: "9.289µs",
        80: "17.561µs",
        95: "150.561µs"
      }
    },
    misses: {
      Avg01Min: "278.58K (4.64K/s)",
      Avg05Min: "1.03M (3.44K/s)",
      Avg15Min: "3.13M (3.48K/s)",
      Overall: "12.18M (4.85K/s)"
    },
    puts: {
      Avg01Min: "56.46K (940.99/s)",
      Avg05Min: "511.22K (1.70K/s)",
      Avg15Min: "3.93M (4.37K/s)",
      Maximum: "6.566727ms",
      Minimum: "13.199µs",
      Overall: "21.47M (8.56K/s)",
      Percentiles: {
        20: "17.822µs",
        5: "15.082µs",
        50: "25.272µs",
        80: "32.307µs",
        95: "50.532µs"
      }
    },
    reads: {
      Avg01Min: "48.80M (813.34K/s)",
      Avg05Min: "155.94M (519.79K/s)",
      Avg15Min: "995.87M (1.11M/s)",
      Overall: "5.14G (2.05M/s)"
    },
    writes: {
      Avg01Min: "6.81M (113.57K/s)",
      Avg05Min: "62.04M (206.79K/s)",
      Avg15Min: "480.16M (533.52K/s)",
      Overall: "2.63G (1.05M/s)"
    }
  }
}

**BoltDB**

> {
  user: {
    batchPuts: {
      Avg01Min: "264.76K (4.41K/s)",
      Avg05Min: "1.44M (4.78K/s)",
      Avg15Min: "4.31M (4.79K/s)",
      Maximum: "8.028µs",
      Minimum: "159ns",
      Overall: "33.42M (5.16K/s)",
      Percentiles: {
        20: "213ns",
        5: "186ns",
        50: "301ns",
        80: "651ns",
        95: "1.347µs"
      }
    },
    batchWriteTimes: {
      Avg01Min: "320 (5.34/s)",
      Avg05Min: "1.72K (5.72/s)",
      Avg15Min: "5.21K (5.79/s)",
      Maximum: "2.207547538s",
      Minimum: "5.628727ms",
      Overall: "32.48K (5.01/s)",
      Percentiles: {
        20: "114.440897ms",
        5: "54.547638ms",
        50: "206.08641ms",
        80: "376.989253ms",
        95: "694.516231ms"
      }
    },
    batchWrites: {
      Avg01Min: "36.33M (605.45K/s)",
      Avg05Min: "197.85M (659.48K/s)",
      Avg15Min: "607.09M (674.54K/s)",
      Overall: "3.76G (580.65K/s)"
    },
    dels: {
      Avg01Min: "0 (0.00/s)",
      Avg05Min: "0 (0.00/s)",
      Avg15Min: "0 (0.00/s)",
      Maximum: "0s",
      Minimum: "0s",
      Overall: "0 (0.00/s)",
      Percentiles: {
        20: "0s",
        5: "0s",
        50: "0s",
        80: "0s",
        95: "0s"
      }
    },
    gets: {
      Avg01Min: "111.84K (1.86K/s)",
      Avg05Min: "2.03M (6.76K/s)",
	  Avg15Min: "6.85M (7.61K/s)",
      Maximum: "5.775065ms",
      Minimum: "1.683µs",
      Overall: "48.82M (7.53K/s)",
      Percentiles: {
        20: "2.516µs",
        5: "2.06µs",
        50: "3.197µs",
        80: "5.647µs",
        95: "13.839µs"
      }
    },
    misses: {
      Avg01Min: "0 (0.00/s)",
      Avg05Min: "0 (0.00/s)",
      Avg15Min: "0 (0.00/s)",
      Overall: "0 (0.00/s)"
    },
    puts: {
      Avg01Min: "39.26K (654.41/s)",
      Avg05Min: "196.59K (655.31/s)",
      Avg15Min: "596.19K (662.43/s)",
      Maximum: "194.418117ms",
      Minimum: "441.926µs",
      Overall: "4.55M (701.19/s)",
      Percentiles: {
        20: "642.257µs",
        5: "564.563µs",
        50: "774.047µs",
        80: "996.149µs",
        95: "1.372207ms"
      }
    },
    reads: {
      Avg01Min: "938.51K (15.64K/s)",
      Avg05Min: "6.27M (20.90K/s)",
      Avg15Min: "65.96M (73.29K/s)",
      Overall: "629.47M (97.10K/s)"
    },
    writes: {
      Avg01Min: "4.83M (80.57K/s)",
      Avg05Min: "24.19M (80.65K/s)",
      Avg15Min: "73.36M (81.51K/s)",
      Overall: "557.17M (85.95K/s)"
    }
  }
}

**Comment by holiman** [comment]
Great work!
What would you say are the key metrics to look at above? I'm not quite sure how to read those stats.

**Comment by ArchetypicalDude** [comment]
Hey guys, late reply because I'm travelling. Thanks for your interest and putting the data in a table!

So the go-ethereum metrics module consists of meters and timers. Meters measure how much data or how many operations get executed in a certain timeframe and timers measure how long the operations take. I think looking at the timers is more interesting for the moment as they tell us how long it takes to persist data to the hard drive and how long it takes to read that data again.

Persisting data (PUT and batch write operations) is for example interesting when fast-syncing a client, as this is in part dependent on how fast you can write data to the hard disk. Reading data (GET operations) from the disk is interesting when validating transactions against your copy of the blockchain, as you have to traverse the state trie.

I think looking at the 95-percentiles of the "puts", "gets" and "batchWriteTimes" tells us the most about the different key-value-stores. BadgerDB has very good write performance, BoltDB has very good read performance and LevelDB is a good mixture of both.

I hope I don't have any misunderstandings in my explanations. I'm also hesitant to draw any final conclusions as to which key-value store might be the best fit for go-ethereum. All the metrics collected are dependent on how well the operations are batched, data is cached, hardware used and so on. Also very important is how much disk space is used by the different datastores: LevelDB is at ~70GB when fully synced, BoltDB and BadgerDB use more than 160GB. Unfortunately couldn't yet figure out where this difference comes from.

I'll have to be offline most of the time for the next two weeks but am sure to further look into this stuff when I get back home.

**Comment by siong1987** [comment]
@ArchetypicalDude great update! thank you for the work.

**Comment by manishrjain** [comment]
Hey guys, author of Badger here.

@ArchetypicalDude : This looks like really solid work. I'm giving a talk on Badger in Gophercon China in Shanghai -- while this might be too last minute; I'd like to play around with these benchmarks and generate numbers for Badger -- see if I have something solid before the talk.

One thing I noticed is that the table loading is set to memory map. That might eat away on the read performance. Ideally, the LSM tree is small enough to be kept in memory, at which point, the read performance should match up to BoltDB. So, I'd like to try that.

Can you point me regarding how to run your code and how to generate these read/write benchmark numbers?

**Comment by siong1987** [comment]
@manishrjain https://github.com/siong1987/go-ethereum/pull/1 < I created this PR based on @ArchetypicalDude's commits so that I can easily visualize what has been changed with the Github UI.

to run it, you can follow the `go-ethereum`'s installation guide here: https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Ubuntu

to get the metrics, the guide is here: https://github.com/ethereum/go-ethereum/wiki/Metrics-and-Monitoring

not sure that this is super helpful.

for the metrics, it was my bad to use the `Overall` metric. to see who is the winner, you can look more closely at the breakdown here:

BoltDB:
```javascript
gets: {
  Avg01Min: "111.84K (1.86K/s)",
  Avg05Min: "2.03M (6.76K/s)",
  Avg15Min: "6.85M (7.61K/s)",
  Maximum: "5.775065ms",
  Minimum: "1.683µs",
  Overall: "48.82M (7.53K/s)",
  Percentiles: {
    20: "2.516µs",
    5: "2.06µs",
    50: "3.197µs",
    80: "5.647µs",
    95: "13.839µs"
  }
}
```

LevelDB:
```javascript
gets: {
  Avg01Min: "123.67K (2.06K/s)",
  Avg05Min: "739.38K (2.46K/s)",
  Avg15Min: "3.04M (3.38K/s)",
  Maximum: "127.309714ms",
  Minimum: "4.86µs",
  Overall: "9.00M (3.18K/s)",
  Percentiles: {
    20: "6.11µs",
    5: "5.583µs",
    50: "7.396µs",
    80: "18.321µs",
    95: "39.912µs"
  }
}
```

Badger:
```javascript
gets: {
  Avg01Min: "395.55K (6.59K/s)",
  Avg05Min: "1.55M (5.16K/s)",
  Avg15Min: "5.97M (6.64K/s)",
  Maximum: "12.899981ms",
  Minimum: "3.748µs",
  Overall: "26.39M (10.52K/s)",
  Percentiles: {
    20: "6.305µs",
    5: "4.746µs",
    50: "9.289µs",
    80: "17.561µs",
    95: "150.561µs"
  }
}
```

as you can see from the percentiles measurements:

| Database       | BoltDB | LevelDB | Badger |
| ------------- |---:| ---:| ---: |
| 5 percentile gets | 2.06µs | 5.583µs | 4.746µs |
| 20 percentile gets | 2.516µs | 6.11µs | 6.305µs |
| 50 percentile gets | 3.197µs | 7.396µs | 9.289µs |
| 80 percentile gets | 5.647µs | 18.321µ | 17.561µs |
| 95 percentile gets | 13.839µs | 39.912µs | 150.561µs |

**Comment by siong1987** [comment]
@manishrjain also, thanks for the tips on configuring Badger to get better performance out of it. i will try those configurations that you suggested and report back here.

@ArchetypicalDude i currently have plenty of time on my hands, wanna collaborate together on this?

**Comment by manishrjain** [comment]
@siong1987 : If read performance is more important than write, you could also try setting `ValueThreshold` to a much higher value than the current 32 bytes. That way, LSM tree would store the values within it, and the value log would just act like a write-ahead log -- like any other typical LSM tree. This would also perform better on hard disks.

There're also some optimizations going into the upcoming v2.0, which would improve read performance.

**Comment by karalabe** [comment]
I don't think measuring database gets is that relevant to be honest. Try running a `geth import chain.rlp` where `chain.rlp` is the first 1.9M blocks for starters. That might give you a baseline number to start with.

Then you might want to import the first 3M blocks, which contain the spam txs and cleanups too. There your memory will run out for disk caching and actual performance will surface harder.

Lastly blocks above 4M are the really heavy ones. Those might be a lot more interesting to test with (also the database gets over 100GB there, so that's where the juicy parts start).

**Comment by siong1987** [comment]
@ArchetypicalDude 
no worries. let me know how i can help.

also, i notice that BadgerDB doesn't support compression and let the user decide whether they want to compress their data or not. i actually like this decision a lot. i wonder if we start using snappy with BadgerDB, the DB size will be smaller.

https://github.com/dgraph-io/badger/issues/411

the million dollar question: how compressable ethereum data is? cc: @karalabe

**Comment by ArchetypicalDude** [comment]
I added a CLI-Command to manually start badger's garbage collector. You can run it via 'geth badgerGarbageCollect'. Internally it just runs PurgeOlderVersions() and RunValueLogGC(0.5).

It does not result in a smaller DB size unfortunately. Maybe @manishrjain has any idea what's wrong here.
This might be related: https://github.com/dgraph-io/badger/issues/444
```
INFO [04-18|13:17:36] Starting database garbage collection; db.size lsm=25449348738 vlog=180410199890
INFO [04-18|13:19:44] RunValueLogGC error                      err="Value log GC attempt didn't result in any cleanup"
INFO [04-18|13:19:44] Database garbage collection done; db.size lsm=25449348738 vlog=180410199890
```
I also couldn't benchmark yet with `opts.TableLoadingMode = options.LoadToRAM` because the LSM-tree is already 25GB big and I'm simply running out of memory on the current testing environment.

**Comment by manishrjain** [comment]
Any way I can run this thing with Badger? Sorry, I'm a crypto n00b, so exact pointers would be helpful.

**Comment by ArchetypicalDude** [comment]
I implemented snappy compression in the latest commit and that did bring down chaindata-size from ~195GB to ~115GB :) LevelDB does this by default, so that's where the huge difference came from. So the data is very much compressible and it would be super interesting to test different compression algorithms! Absolutely a noob in that field though, have to understand a lot about how go-ethereum handles data first.

I also got the garbage collector to run. It actually works very well when database size is still small: disk space gets freed up and the vlog-files get rewritten. Once the database gets larger (~100GB but I don't have a hard number, sorry about that) it always returns "Value log GC attempt didn't result in any cleanup" and even though there were some initial cleanups, the database grows to the exact same size once all blocks are imported. Same size as if I didn't run the garbage collector at all.

@manishrjain 
I guess pretty much everybody is a noob when it comes to crypto! Here are the installation instructions for the go-ethereum client (look under "building from source"): https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Ubuntu

**Comment by siong1987** [comment]
awesome. let's me share some data that i have, this is being run on the digital ocean standard droplet with 4 vCPUs and 8GB memory. the time is measured by importing from block 1 to 2500000.

| Implementation        | Time           | Chain Size  | Source |
| ------------- |-------------:| -----:| -----|
| LevelDB      | ~ 27h 1m | 21 GB | https://github.com/siong1987/go-ethereum |
| BadgerDB | ~ 30h 34m | 39 GB | https://github.com/siong1987/go-ethereum/pull/1 |
| BadgerDB with Snappy | timeout | timeout | https://github.com/siong1987/go-ethereum/pull/2 |

like what @ArchetypicalDude saw in his data, snappy helped to make the chain size smaller but it died because it was taking a lot more memory than my BadgerDB implementation without Snappy.

@ArchetypicalDude 
I definitely do not see the time improvement that you were seeing in your earlier test. BadgerDB is actually slower than the default LevelDB implementation. btw, i am using the 1.8.6 version, it comes with the 40% block processing improvement by @holiman here #15225.

@manishrjain 
are you based in SF? i can probably drop by to show you how i do it. i might spend some time write up a blog post about my workflow on digital ocean so that others can use it too.

my next step is to get a 16GB memory droplet on digital ocean and run the same tests again.

**Comment by manishrjain** [comment]
Thanks @siong1987 for coming in and showing me how to run geth with your Badger changes.

So, based on what I'm seeing, Badger has very little load, because all the writes are done one by one, with little or no batching.

I ran an HTTP server on port 8080 (`go http.ListenAndServe("localhost:8080", nil)` in geth.main), which exposes `/debug/events` and `/debug/requests`.

Picking from `/debug/events`

```
Value Log

11:54:57.930241 | .    24 | ... Flushing 1 blocks of total size: 120
-- | -- | --
11:54:57.930247 | .     6 | ... Done
11:54:57.930458 | .   212 | ... Flushing 1 blocks of total size: 131
11:54:57.930464 | .     5 | ... Done
11:54:57.930682 | .   218 | ... Flushing 1 blocks of total size: 950
11:54:57.930687 | .     5 | ... Done
11:54:57.930736 | .    49 | ... Flushing 1 blocks of total size: 122
11:54:57.930750 | .    13 | ... Done
```

Every write to value log is tiny, barely 1KB -- given there's a system call involved, this is going to be slow. Badger integration in geth has set `SyncWrites` to false; if that was true, this would be *very slow*.

Similarly,

```
12:40:12.144301 | .     8 | ... Writing to memtable
-- | -- | --
12:40:12.144307 | .     6 | ... 2 entries written
```

There are not a lot of writes happening in one go. If batching and concurrency can be introduced, it can significantly speed up the DB operations. My understanding is that DB writes are a bottleneck, so DB ops speeding up would mean the whole import process would become faster.

**Comment by manishrjain** [comment]
Btw, I'd encourage you guys to upgrade to v1.5.0 of Badger. It has a whole bunch of improvements when it comes to space reclaims. Also, gets rid of `Purge..` functions, all that is now automatically taken care of by LSM compactions.

**Comment by ArchetypicalDude** [comment]
@siong1987 

As I said, FULL syncing the blockchain won't be any faster with Badger because you need lots of reads and read performance is not Badger's strong point. FAST syncing definitely is faster because there is way less database reads and verification of the downloaded and written data. On a powerful machine with SSDs, 256GB Ram and 100 peers my latest fast sync took exactly:

BadgerDB: Head Block 5622279, **1h 27m 11s**, source: https://github.com/ArchetypicalDude/go-ethereum/commit/790acc07a0dde0e330da82b49da36db5af134a15
LevelDB: Head Block 5623803, **6h 27m 11s**, source: https://github.com/ethereum/go-ethereum/releases/tag/v1.8.8

@karalabe @vbuterin 
I tried to create more comparable benchmarks by fast syncing in a private network but couldn't get it to work: The downloader keeps dropping perfectly fine peers. Tried to find out why this is happening for a few days but got frustrated at some point. Downloader.go is >1500 lines long and just too complicated for my level of experience. Given its poor performance and stability I'd say someone should think about rewriting it from scratch. At least I'd think more carefully about what to merge into the foundations "stable" releases. 

I also tried to collect data on block processing times on a fully synced node in both the LevelDB and BadgerDB implementations. After 24h of fairly stable processing times (50ms - 400ms) there show up spikes up to 1.5 seconds (independent of database used). After 48h the spikes get more frequent and reach up to 3 seconds. After 56 hours I get the first "Synchronisation failed, dropping peer"-Warnings and block processing times spike way up to > 10s until the node can't even stay in sync any more. This is on fairly modern machines with 32GB ram, Gigabit connection and on the latest stable release of go-ethereum. I am a bit worried this might be detrimental for overall network health and would be very thankful if someone with more experience than me could look into these issues.

**Comment by metabench** [comment]
Is there a way that the database side of Geth could be further encapsulated? I have just suggested https://github.com/ethereum/go-ethereum/issues/16919, sharding on the DB level. A way that this could be done with minimal changes to the geth code is to have geth call a database access service, and that service would then handle the database calls itself, so that work on the DB access could be done independently from the main Geth.

I already have DB code in node that over the slightly longer term I'm interested in running as a cluster (https://github.com/metabench/nextleveldb-server), but I would also be interested in writing a microservice in node that passes DB calls from Geth onto an existing database such as CockroachDB or MongoDB.

**Comment by metabench** [comment]
@ArchetypicalDude @siong1987 @manishrjain I wanted to ping you to ask if you are interested in writing go code that would send the DB calls off as a standard and presumably simple API over websockets, in order to facilitate a variety of DB approaches that are separate from the geth code and upgradable as individual components.

**Comment by shoenseiwaso** [comment]
@metabench would be interested in this as well. Our specific use case is fast seeding of large archive nodes, to spin up new nodes or permit upgrades when the underlying database structure changes.

We were thinking of something like trusted enodes that could preferentially sync and bypass full block computation, but it's just an idea and we don't know enough about the go-ethereum internals yet to know if that is realistic.

**Comment by FrankSzendzielarz** [comment]
Also this new one to look at https://artem.krylysov.com/blog/2018/03/24/pogreb-key-value-store/

**Comment by fjl** [comment]
We can try badger as soon as #17814 is merged because it expands the database interface to include iterators.

**Comment by mewwts** [comment]
Just dropping this here, as it seems like Badger could be a viable option https://github.com/dgraph-io/badger/releases/tag/v2.0.0

**Comment by ligi** [comment]
replaced by #22143
