### ISSUE TITLE
How to debug the failure transaction to a contract?

### ISSUE THREAD

**Issue by wcw84** [ethereum/go-ethereum#15721]
Hi all,
I am new to the ethereum contract, and want to learn how to debug a contract. 
I have sent a transaction to my contract, and it failed. From the https://etherscan.io/tx/0x20a79ec615ca8c4668016624e83b82ffc1a54f61b90f05e0e531fda29fc0b4d1, it just failed and without any error information. So is there any way to know why it failed?
How can I debug it?
Any help will be appreciated.

**Comment by veox** [comment]
There are no sources published for the contract in question, so it's hard to say.

The tx does fail fairly early on (only 1459 gas consumed above the minimum 21000), so likely input invalid or insufficient permissions.

-----

Also, this issue is completely unrelated to `go-ethereum` - suggest closing.

**Comment by wcw84** [comment]
@veox Thanks, Veox, in fact I have the source, and there are several "require" statements in the contract call, so I can guess one of the require failed and the call is reverted. But is there anyway to debug which line or statement of the contract failed, just like we debug in Javascript or other language?

BTW, do you know where can I ask such question about the solidity?
Thanks.

**Comment by veox** [comment]
Directly - not yet, pending https://github.com/ethereum/solidity/issues/1686.

You should be able to step it through a debugger, like the one in Remix.
