### ISSUE TITLE
Transaction is not broadcasted after set nonce in sendTransaction

### ISSUE THREAD

**Issue by wcw84** [ethereum/go-ethereum#15749]
Hi all,

I need to do several sendTransaction from one address to many other addresses, and I learned [that](https://ethereum.stackexchange.com/questions/27256/error-replacement-transaction-underpriced) I need to set nonce for every "sendTransaction", using "web3.eth.getTransactionCount(myaddress) + 1" to avoid the error "replacement transaction underpriced", and then the problem is that such transactions will never be mined:
`
> eth.getTransactionCount("0x2592a20db4c16c89b08e301792953911c4751d7f")
**80**
> eth.getTransaction("0xf4181f7c94c508be850c595521dd83919ad7bf430440aaa0d67a526cb7fc28a7");
{
  blockHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  blockNumber: null,
  from: "0x2592a20db4c16c89b08e301792953911c4751d7f",
  gas: 37274,
  gasPrice: 21000000000,
  hash: "0xf4181f7c94c508be850c595521dd83919ad7bf430440aaa0d67a526cb7fc28a7",
  input: "0xa9059cbb000000000000000000000000f4619719afd787a9cc687f5a1a07c1cf543d1ccb0000000000000000000000000000000000000000000000000de0b6b3a7640000",
  **nonce: 81,**
  r: "0xe7069eac693fac344060cd4e15824bf36f4c75ccd39e99fa4faee84dd0ff367c",
  s: "0x3d9616c312263ac62e034bb9cb40f27284f1a7ff69fed3861b8b875f25244919",
  to: "0x584b44853680ee34a0f337b712a8f66d816df151",
  transactionIndex: 0,
  v: "0x25",
  value: 0
}
`

If I don't set nonce manually, the transaction will be sent correctly.
Can anyone tell me how to set nonce in the "sendTransaction", or tell me how to send several transactions from one address in a short period of time.

#### System information

Geth version: Geth/v1.7.2-stable-1db4ecdc/linux-amd64/go1.9
OS & Version: Linux

Any help will be appreciated.

**Comment by philoctetes409bc** [comment]
yip, had one stuck in pending after it had broadcasted too, what gives with this pending thing is there way to turn off I dont care if it doesn't go through I'll know if it doesn't b/c I always check on etherscan and also it just makes me paranoid to have a broadcasted tx get stuck in pending ..

**Comment by holiman** [comment]
The easiest way to figure out the nonce is to check "which is the last successfull transaction". In the case of the account above [here](https://etherscan.io/address/0x2592a20db4c16c89b08e301792953911c4751d7f), the last one _out_ is [`0xf32d8eb2a3074e20d5f80598ed541bf4d60ee1184c51207acb2529096aab2bd0`](https://etherscan.io/tx/0xf32d8eb2a3074e20d5f80598ed541bf4d60ee1184c51207acb2529096aab2bd0), with the nonce `258`. So the next one should be `259`. 

How to set nonce: 
```javascript

> var tx = { from: "..", to : "...", nonce: 259 , ...}
> personal.sendTransaction(tx,"pass")
``` 
Several transactions in a short period of time _should_ be fine without messing with nonce manually, geth does a decent job of keeping track of it. But if you really don't want geth to do that, just set the nonce manually in a loop or whatever you use to generate the transactions. 

I'm closing this, because I don't see any real bug being reported here (?)

**Comment by SergeSysoev** [comment]
Hello. I have the same issue. When I set manually nonce, it isn't working. Something like this:
`web3.eth.getTransactionCount(this.wallet.address).then(nonce => {
        let rawTx = {
          nonce: web3.utils.numberToHex(nonce),
          to: contractAddress,
          ...
        };
web3.eth.sendSignedTransaction('0x'+serializedTx.toString('hex')).(then)...
});`
works fine, but if I set, for example, 
`nonce: web3.utils.numberToHex(nonce+1)`
transaction doesn't broadcasted.
Thanks.
