### ISSUE TITLE
includeTransactions option in PUB-SUB newHeads subscription doesn't work

### ISSUE THREAD

**Issue by leehankyeol** [ethereum/go-ethereum#15804]
#### System information

Geth version: `1.7.3-stable`
OS & Version: Windows/Linux/OSX

#### Expected behaviour

It's not documented well but what I think this option should do is to include transactions data when the node receives the new head. But I don't really know if it is deprecated or behaves different from what I expect.

#### Actual behaviour

It returns the data without transactions data. (from testnet)

```javascript
{
  parentHash: '0xc863909dfcc608c2f2d9867f5574bf35d152aa4f7e1598acd822dcf10347283a',
  sha3Uncles: '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347',
  miner: '0x00d8ae40d9a06d0e7a2877b62e32eb959afbe16d',
  stateRoot: '0xc3b294a4a07dfe04b70ece93f1313d62a66a03300d633973cfe70d7a3eeddb73',
  transactionsRoot: '0x5171e54198578155c5baf90baa6ec06728843e6cb2619b7330117a5e237850f6',
  receiptsRoot: '0x7f31c9c97da1964f50050a3ceb7f004e7aaae2a00ae73c24ab1c862d06ac269d',
  logsBloom: '0x00000010000000000000020000000000000000000000100000000010002000000000000000000000000000000000000000000000000000000000000000000000000000000000000042000000000200000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000800000000000000000000012000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000080000000000020000000008000000000000000000000000000000000000000000000000000000000000000000008000000020000000000000080000000202000000',
  difficulty: '0x7eabcbf1',
  number: '0x249496',
  gasLimit: '0x47c3f2',
  gasUsed: '0x60635',
  timestamp: '0x5a4dd23c',
  extraData: '0x414952412f7630',
  mixHash: '0xd0da9cd29fa4f9c52adeeb4fb7560966ed3c3c6d395522508e03d233473980fa',
  nonce: '0xc1126afcced36212',
  hash: '0xd5cfef2cbcc1bc2d5174d7195804a01d5fdc9dccbb0b11e4aa92b28d4b43963d'
}
```

#### Steps to reproduce the behaviour

Just subscribe with `includeTransactions: true` option.

```
const subscriptionNewHeads = {
  id: 'subscriptionNewHeads',
  method: 'eth_subscribe',
  params: ['newHeads', { includeTransactions: true }],
  subscription: null
}

const WebSocket = require('ws')
const ws = new WebSocket('ws://localhost:8546')

ws.onopen = function() {
  // Subscribe.
  ws.send(JSON.stringify(subscriptionNewHeads))
}

ws.onmessage = function(ack) {
  const data = JSON.parse(ack.data)

  switch (data.id) {
    case subscriptionNewHeads.id:
      subscriptionNewHeads.subscription = data.result
      console.log('Subscribed to newHeads!')
      break

    default:
      switch (data.params.subscription) {
        case subscriptionNewHeads.subscription:
          console.log('Head', data.params.result)
          break
      }
  }
}
```

**Comment by karalabe** [comment]
The `newHeads` endpoint only returns headers, not blocks (e.g. light clients don't have blocks available). The transactions themselves are part of the block body, which would need additional retrievals, so for a light client it could be prohibitively expensive to do implicitly.

**Comment by leehankyeol** [comment]
@karalabe I see your point. But what I pointed out is that there's an option called `includeTransactions` [in the example](https://github.com/ethereum/go-ethereum/wiki/RPC-PUB-SUB#example) and it doesn't seem to be well-documented or working.

And just out of curiosity, is there any way to get raw block or raw transaction data from geth or other Ethereum client? Can I only get new block id (hash) or pending transaction id (hash) through RPC PUB-SUB?

**Comment by sraka1** [comment]
@karalabe any news in this regard?

**Comment by sraka1** [comment]
This still seems to be the case for newHeads.

**Comment by karalabe** [comment]
I don't think this feature is worth the ambiguity vs. utility. Subscribing to a new head is "free", as in when the chain progresses, you can get a notification without any cost. Retrieving the transactions is "free" on a full node, since we're processing blocks locally, but a light client would need to retrieve them from the network. This is extra burden, might fail, might take a lot of time etc. If your code explicitly asks for a block, you know that it might fail, you know that it's extra data, etc, so you can handle failures more gracefully.

**Comment by sraka1** [comment]
@karalabe this is indeed true for light clients. I am however talking about including the option on full nodes (where, as you say, using it is in fact free) - thus removing an unneeded RPC call by having to do a getBlockByHash...but it's just 1 extra call, so negligible. 

Perhaps a better use case for this option would be on a **`pendingTransactions`** subscription, where afaik one has to currently do a **`getTransaction`** call for each pending tx (since none of them are part of a block yet). However, I might be missing another way here :)

**Comment by DiveInto** [comment]
if decided not to implement this feature, might be a good idea to remove the `includeTransactions ` option in wiki doc(https://github.com/ethereum/go-ethereum/wiki/RPC-PUB-SUB) to avoid future confusing
