### ISSUE TITLE
Duplicate nonce on transaction, transaction pending, but not moving

### ISSUE THREAD

**Issue by zombait** [ethereum/go-ethereum#15815]
Tx ID: 0x20fa456e1e8a8b30274ff3c88b7596fd5b25106dfaff5bf2d5bc8e7b05a27836

Sent some ETH, someone from the same exchange sent some at the same time, it looks like?

**Comment by zombait** [comment]
Also, I have only been able to find this tx on Etherchain, but none of the other blockchain scanners.

https://www.etherchain.org/tx/20fa456e1e8a8b30274ff3c88b7596fd5b25106dfaff5bf2d5bc8e7b05a27836

**Comment by zombait** [comment]
Now, 12 hours after it was first submitted it's disappeared from etherchain, but has not made it back to my CEX.IO exchange account.

**Comment by karalabe** [comment]
Might be an issue at the exchange. You should contact them for a refund if their transaction didn't make it to the chain.

**Comment by zombait** [comment]
The duplicate nonce issue has been reported numerous times, but over the last couple of years, each time being marked off as resolved, so thought I'd bring it up again once it appeared to me. It registered on the chain in some regards because etherchain.org was able to scan and log it (even if it is gone now).

**Comment by karalabe** [comment]
The problem is that we don't even know whether CEX.IO uses Geth, Parity or some other client, so even if it would be a bug, we don't know whether it's related to us or not.

Then, duplicate nonces might be caused also if they sign their own transactions outside of the node and just submit it, in which case the bug is in their code.
