### ISSUE TITLE
--dev mode can't mining on Windows10

### ISSUE THREAD

**Issue by EasonWang01** [ethereum/go-ethereum#15854]
#### System information

Geth version: `geth version  1.7.3-stable`
OS & Version: Windows10

#### Expected behaviour
```
geth --dev --rpc --rpcport 8104 --datadir ./Ethte1t --rpccorsdomain="*" console

miner.start(1)
```
Start mining.

#### Actual behaviour
![234234](https://user-images.githubusercontent.com/11001914/34817328-976fd37a-f6f2-11e7-90cd-1ecf8c094809.png)

 miner.getHashrate() also return 0.

Another issue is when import the default config account in dev mode to the metamask it need the password for the preconfig account,what should type in the field.

**Comment by karalabe** [comment]
Dev mode by default auto-mines when there are transactions, otherwise it just idles. You can manually force it to mine by setting the block period to something other than zero (e.g. `--dev.period=15` to mine 1 block per 15 seconds). You don't need to manually start mining, it's auto started when the node starts.

> miner.getHashrate() also return 0.

Dev mode is based on a PoA chain (so it doesn't waste CPU resources on useless hashing). There's no hashrate in PoA. Blocks can be minted whenever (either according to the above mentioned *period* configuration, or instantly if unset).

> Another issue is when import the default config account in dev mode to the metamask it need the password for the preconfig account,what should type in the field.

The developer account's password is the empty string (i.e. no password).

**Comment by EasonWang01** [comment]
Thanks,but when import account into metamask it will show the following
<img width="361" alt="2018-01-12 8 16 42" src="https://user-images.githubusercontent.com/11001914/34853849-040464d2-f771-11e7-8406-ecdb9ce12a64.png">

**Comment by karalabe** [comment]
Please open a ticket on the Metamask repo and ask them to support importing empty-passworded accounts. It's fine not to allow empty passwords when creating a new account, but they should most definitely support importing such files.

**Comment by EasonWang01** [comment]
ok,thanks!
