### ISSUE TITLE
how to handle the transaction which were in the invalid block when the blockchain change the chain?

### ISSUE THREAD

**Issue by kazaff** [ethereum/go-ethereum#15862]
Hi there.

I wonder that how can i make sure my transaction was count in the blockchain?~
For example, I will count the confirm times for my transaction. But, how can i sure about that my transaction be invalid and it never be change to valid? 

Will the miner deal with my transaction again?  Or just left it to dead?

Thanks & Waiting your answer~

**Comment by holiman** [comment]
If you mean `invalid` as in e.g. "nonce too high" or "balance too low", then the network will most likely discard your transaction. How fast depends on how many other transactions there are, when the pools are filling up, transactions get evicted. However, there's no guarantee it'll ever get evicted, it is still technically _valid_ , just not at this point in time. 


If you want to make certain the transaction `X` can never ever be broadcast by someone else, you should

* Check what `nonce` was used in `X`. 
* Make a new transaction (`Y`), from the same account, using nonce `X`. 
* In any chain where `Y` 'made it', `X` can never happen. These two are mutually exclusive. 

So, as you may understand from this, if the `invalid` is caused by `nonce too low`, then it's already permanently invalid, and no peer will keep it around, it's a total dud.

**Comment by kazaff** [comment]
@holiman thanks

can you explain the `nonce too low` or `nonce too high` means? Or just give me some articles?

I had tried to find some info from [here](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethsendtransaction): 
```
nonce: Number - (optional) Integer of a nonce. This allows to overwrite your own pending transactions that use the same nonce.
```

In other words, I create a transaction use a bigger nonce, And once it had been in the main chain. Then, My transactions which use a smaller nonce will never be accepted by all miner?

thank you  again.

**Comment by holiman** [comment]
At any time, there's only _one_ correct nonce for an account/transaction. If no transaction has ever been sent, the first nonce is `0`. The next transaction needs to have nonce `1`. 

So let's say those two have been made. The next nonce needs to be `2`. 

* If you make a tx with nonce  `1` (again), all nodes will discard it. That number is permanently burned. 
* If you make a tx with nonce `4`, some nodes may hang on to it, figuring that it's a nonce-gap, and they just haven't seen the missing one, but will keep this one around for a bit until the `3` comes along. 
* If you make a tx with nonce `3`, but too low gasprice, so it doesn't get included, and you don't see it anywhere -- then __if__ you want to perma-delete it, you need to replace it, with another `3`, with a better gasprice or whatever it was that made it not become included. 

Your original question was kind of vague, so I'm not sure if you're asking a theoretical question or if you have a specific scenario you want help with.

**Comment by kazaff** [comment]
@holiman  your answer is very helpful for me, thank you a lot!!!!!!!! I'm very interested in this theoretical point.

You said that the nodes `will keep this one around for a bit until the 3 comes along.`,  But when the time up, Or when they find the tx(nonce 3), but they do not want to handle it(for some reason like too low gasprice),
they will do the tx(nonce 4) immediately. right?

**Comment by holiman** [comment]
At any time, there's only one correct nonce for an account/transaction.

**Comment by holiman** [comment]
4 can never ever ever be executed without a number three.

**Comment by kazaff** [comment]
oh~~ I got it.😆
