### ISSUE TITLE
keys are not in increasing order

### ISSUE THREAD

**Issue by Fluchtzwerg** [ethereum/go-ethereum#15879]
Hello, I've got following Problem:

While Syncing with Geth 1.7.3 I've got a memory Management Bluecreen. 
After the restart I'm getting this Error-message:
`Fatal: Error starting protocol stack: leveldb/table: Writer: keys are not in increasing order: "LastFast\x01\xa7ݞ\x05\x00\x00\x00", "LastFast\x01\xa1۞\x05\x00\x00\x00"`

Any Idea how to fix this without restarting the Sync?

**Comment by karalabe** [comment]
Nope, your leveldb database is fried from the inside out. I've never even seen such an error message. I can open an issue upstream with leveldb so they might track this error message for a possible recovery from, but in general if the db blows out (usually due to power failure, there's not much we can do to save it).
