### ISSUE TITLE
Import fails after restart

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#16097]
#### System information

Geth version: `Geth/v1.8.1-unstable-dc7ca52b/linux-amd64/go1.9.2`
OS & Version: Linux

#### Problem

I got the hive suite running again yesterday. Now we're getting all failures
http://hivetests.ethstats.net/#displayLog=artefacts/20180215_050945-go-ethereum%3Amaster/client-775e2b79.log
First we do a successfull import of some blocks: 
```
INFO [02-15|05:27:18] Importing blockchain                     file=0001.rlp
INFO [02-15|05:27:18] Imported new chain segment               blocks=1 txs=1 mgas=0.128 elapsed=7.165ms mgasps=17.884 number=1 hash=7af679…5d3ccd cache=1.31kB
ERROR[02-15|05:27:18] Dangling trie nodes after full cleanup 
INFO [02-15|05:27:18] Blockchain manager stopped 
Import done in 7.628636ms.

Compactions
 Level |   Tables   |    Size(MB)   |    Time(sec)  |    Read(MB)   |   Write(MB)
-------+------------+---------------+---------------+---------------+---------------
   0   |          1 |       0.00123 |       0.00000 |       0.00000 |       0.00000

Trie cache misses:  7
Trie cache unloads: 0

Object memory: 194.594 MB current, 194.143 MB peak
System memory: 404.662 MB current, 404.412 MB peak
Allocations:   0.018 million
GC pause:      813.405µs

```
Then after restart, it rewinds the blockchain and removes the block we imported: 
```
INFO [02-15|05:27:18] Initialising Ethereum protocol           versions="[63 62]" network=1
WARN [02-15|05:27:18] Head state missing, repairing chain      number=1 hash=7af679…5d3ccd
INFO [02-15|05:27:18] Rewound blockchain to past state         number=0 hash=743b09…0f5488
INFO [02-15|05:27:18] Loaded most recent local header          number=1 hash=7af679…5d3ccd td=262144
INFO [02-15|05:27:18] Loaded most recent local full block      number=0 hash=743b09…0f5488 td=131072
INFO [02-15|05:27:18] Loaded most recent local fast block      number=1 hash=7af679…5d3ccd td=262144
```

**Comment by upers** [comment]
I have same problem in my private POA net.
I got error:
---------------------------------ERROR--------------------------------------
Error: invalid merkle root
########## BAD BLOCK #########
Chain config: {ChainID: 452 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: <nil> Engine: clique}

Number: 1626771
Hash: 0x53e5c4ded722ddbe00dbd8c153aa3b64741d15b5d731f5ffe745b2e1bca2d259
----------------------------------------------------------------------------------------
I fixed this by restarting all nodes and adding peers manually through the get.ipc.

But in 10 hours  all my nodes stopped synchronizing and accordingly ceased to create blocks.
Message from log: "ERROR[06-01|17:58:24] Dangling trie nodes after full cleanup."
I can not clean the block because there is valuable information there.
I tried restart nodes and added peers manually, it didn't work.

And there no error messages in log, only: "Signed recently, must wait for others."
Geth version: 1.8.3-stable.
Go version: go1.10.1
OS: ubuntu 16.04
Genesis file:
{
  "config": {
    "chainId": 452,
    "homesteadBlock": 1,
    "eip150Block": 2,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 3,
    "eip158Block": 3,
    "byzantiumBlock": 4,
    "clique": {
      "period": 3,
      "epoch": 30000
    }
  },
  "nonce": "0x0",
  "timestamp": "0x5ac632c4",
  "extraData": "0x00000000000000000000000000000000000000000000000000000000000000002368c95eb9ea3578a20d6887ccb40773499b93d5c67be939661d2559acfb059fc1737a2ceaaed4ae0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0x47b760",
  "difficulty": "0x1",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "alloc": {
    "2368c95eb9ea3578a20d6887ccb40773499b93d5": {
      "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
    },
    "c67be939661d2559acfb059fc1737a2ceaaed4ae": {
      "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
    }
  },
  "number": "0x0",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
}

**Comment by relaxbao** [comment]
hello, have you solve the problem yet?
