### ISSUE TITLE
Puppet fails to install Faucet

### ISSUE THREAD

**Issue by nileshtrivedi** [ethereum/go-ethereum#16111]
#### System information
Geth version: 1.7.3-stable
puppeth version: 0.0.0
Network type: Clique

#### Expected behaviour
Puppeth should be able to install Faucet

#### Actual behaviour
Installation fails due to build error

#### Backtrace

```
go build github.com/ethereum/go-ethereum/cmd/faucet: /usr/lib/go/pkg/tool/linux_amd64/link: signal: killed
Service 'faucet' failed to build: The command '/bin/sh -c apk add --update git go make gcc musl-dev ca-certificates linux-headers                             && mkdir -p $GOPATH/src/github.com/ethereum                                                            && 	(cd $GOPATH/src/github.com/ethereum && git clone --depth=1 https://github.com/ethereum/go-ethereum) &&   go build -v github.com/ethereum/go-ethereum/cmd/faucet                                              &&   apk del git go make gcc musl-dev linux-headers                                                      &&   rm -rf $GOPATH && rm -rf /var/cache/apk/*' returned a non-zero code: 1
ERROR[02-17|03:48:42] Failed to deploy faucet container        err="Process exited with status 1"
```

**Comment by karalabe** [comment]
Puppeth v1.7.3 still built the faucet manually when you deployed it, which requires a certain minimum amount of memory (based on your logs, the compilation failed due to the compiler running out of memory and being terminated by the OS).

I'd suggest updating to the newly released version of `puppeth`, which deploys all its components from pre-build docker images hosted on docker hub, so you don't need to build any more (and it's a lot faster to do too).
