### ISSUE TITLE
whisper: TTL protocol doesn't work without time synchronization

### ISSUE THREAD

**Issue by dshulyak** [ethereum/go-ethereum#16134]
We are running whisper protocol on mobile devices. Sometimes it is not possible to turn on time synchronization, and basically if significant time skew occurs whole applications becomes useless.
I am very curious to know if there is a plan to re-implement TTL protocol without relying on a wall clock.

One naive approach that comes to my mind is to use TTL as a counter, a number of hops every envelope is allowed to travel, and to decrement this counter when each peer receives an envelope. This will require significant changes to a technique used for sealing envelopes though. 
Have you considered such approach?

#### Expected behaviour
Envelopes are not discarded with significant (more than 10s) time desynchronization.

#### Actual behaviour
Envelopes are discarded because of https://github.com/ethereum/go-ethereum/blob/master/whisper/whisperv6/whisper.go#L753-L767

cc @gballet @gluk256

**Comment by mandrigin** [comment]
One alternative we thought about is a relative time approach.

Instead of keeping the absolute timestamp of when the envelope was created, we can make TTL counter relative to `now()` of the current node.

To do that, we create an envelope with a creation time and a TTL (e.g. 50 seconds), we enqueue it.
Just before sending it to another peer via a socket, we subtract `now() - creation_time` from TTL, and write this value there.
On the receiving node, we update `creation_time` to `now()`. Again, just before sending, we subtract `now() - creation_time` from TTL.

That makes TTL to be smaller and smaller with each hop.

We can keep the logic of discarding messages as it is now.


<img width="1187" alt="img_0001" src="https://user-images.githubusercontent.com/466427/36423723-4d40842a-1641-11e8-8ee1-0cc0db6c0d3e.PNG">

**Comment by adambabik** [comment]
One potential issue that came to my mind. This solution requires changing envelope's data (TTL). Has it been checked whether Whisper envelopes have a signature or something like that which makes sure the content has not been altered during passing from sender to recipient?

**Comment by dshulyak** [comment]
It should be, otherwise, it would be really easy to spam the network. I thought there might be a way to leave TTL field mutable but protect from such thing differently, e.g blacklisting a peer who misbehaves

**Comment by gluk256** [comment]
The message format is not going to change in v6.

**Comment by dshulyak** [comment]
I remember that we agreed that it is possible to use another source of time. I can close it upstream if it doesn't fit v6 roadmap.
