### ISSUE TITLE
Pending transactions filter in "light" mode

### ISSUE THREAD

**Issue by uaimedna** [ethereum/go-ethereum#16216]
Hello,

After numerous attempts to sync geth and parity "fast" nodes on my system with no success a whisper of hope was offered to me when a geth "light" node just magically synced within minutes. Unfortunately the hope didn't last long as it appears that "light" mode doesn't have any way to receive pending transactions. Am I wrong? If not - are there any plans to include this feature or is this technically infeasible? :)

Whats I've tried: used RPC methods: "eth_newPendingTransactionFilter" in conjunction with "eth_getFilterChanges" and there were no filter changes ever reported. "txpool_content" also seems to be empty all the time. I will provide code examples if this feature is in fact somewhat supported.

Thank you.

#### System information

Geth version: 1.8.1.  Same on nightly
OS & Version: Mac OS X

#### Expected behaviour

get some pending transctions

#### Actual behaviour

no pending transactions to be seen

**Comment by karalabe** [comment]
A light client only maintains its own transactions. It cannot maintain a pool of pending transactions, since it cannot check the validity of those transactions (without the state, which is costly to pull from the network for every single tx).

I don't think this is a use case we will ever be able to support. Accessing any "pending" data with a light client is already problematic because the result would depend on which server is answering you (since nodes in the network may see different pending states).

Sorry to say, but I don't think light client will help you here.

**Comment by simone1999** [comment]
Hello, could you please specify a bit more, what you mean by a light client would need the State of the Network?
The only real check that comes to my mind that involves chain State is checking whether an account would be able to pay for the tx fees. But since the P2P data comes from full nodes these are filtering these transactions out. Only attack vector would be a malicious node that is connected to my light client directly via P2P that would be able to spam me with transactions from addresses that can not pay fore these transactions. This should be completely negligible in my opinion.
The only other thing that comes to my mind, that is needed from the Chain state is the nonce of each address to know whether a given Transaction is able to get executed immediately or not. This also could only result in receiving valid transactions that just would not (immediately) be able to execute.
Whether a transaction reverts or not should have nothing to do with mempool and therefore balances and contracts should not be required for tx verification.

**Comment by pokrovskyy** [comment]
@karalabe I understand and agree with your explanation above, but would that be technically possible to enable this with a quick patch for a light node? Eg. consider cases when mempool tx validity is not mission-critical and user just needs to peek into the mempool - then syncing full node would be an overkill (time/resource-wise) Or is it functionally not implemented for light nodes? Thanks!

**Comment by DrewLA** [comment]
was this ever looked into? If it isn't mission critical to validate pending transactions, is there a way to sync the mempool from other full nodes broadcasting transactions without having to pull the whole state of the chain?
