### ISSUE TITLE
geth already running.

### ISSUE THREAD

**Issue by pompomJuice** [ethereum/go-ethereum#1634]
To reproduce:
* start your geth service
* attach to this service via the `attach` param
* restart your geth service: primitive process dup checking ensues.

**Comment by bas-vk** [comment]
To verify that I have understand the issue correct.

The problem is that there is some kind of check when geth is started to determine if geth is already running or not. When geth is running with the attach subcommand this check indicates that geth is running and won't start the geth service instance?

**Comment by obscuren** [comment]
Please create new issue if problem persists
