### ISSUE TITLE
A new BUG of Ethereum with send ETH without balance.

### ISSUE THREAD

**Issue by haint87** [ethereum/go-ethereum#16467]
Hi there,

https://rinkeby.etherscan.io/address/0x6Ef57BE1168628A2bD6c5788322A41265084408a
https://ropsten.etherscan.io/address/0x6Ef57BE1168628A2bD6c5788322A41265084408a

When I make a transaction (offline transaction by signTransaction and sendRawTransaction), I recognise transactions from another wallet without balance sent to this wallet  0x6Ef57BE1168628A2bD6c5788322A41265084408a. If transactions are made with high gasPrice(40.000.000.000) then ETH sending to 0x6Ef57BE1168628A2bD6c5788322A41265084408a is higher, followed by similar transactions with lower gasPrice (100.000, 10.000, 100,  0). Is it a mistake of Ethereum?

update:
1. Without balance: the source address wallet can send more ETH without balance, I tested in my testnet.
2. When you send transaction more gasPrice (eg: 1.000.000.000.000,....), more leaked ETH.
3. Hacker can create many wallets from nodes, end scan the nodes and start hijacking process.

![error](https://user-images.githubusercontent.com/25558760/38485130-48ee6cd2-3bc8-11e8-9e4e-2835fb96d96a.PNG)

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://chat.stackexchange.com/rooms/75652/discussion-between-jackson-ng-and-smarx
https://ethereum.stackexchange.com/questions/45008/eth-stolen-on-ropsten

#### System information

Geth version: 1.8.2
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by ligi** [comment]
Please provide more information - with this little information it is really hard to tell where the problem's origin is.

**Comment by haint87** [comment]
https://ropsten.etherscan.io/txs?a=0x6Ef57BE1168628A2bD6c5788322A41265084408a
https://ropsten.etherscan.io/tx/0x35d257fd25aaf4c67d5d44d15b75dfba4fd4dade1bb89e307e579047bf0634d1
Note that the wallet has transaction without balance, so the balance is from the sky falling. If the transaction before with higher "gasPrice", the hacker's wallet gets more ETH.

**Comment by holiman** [comment]
The balance is not falling from the sky, it's mining rewards: https://ropsten.etherscan.io/address/0x3f7d39bdbf1f5ce649c194571aed3d2bbb2f85cf#mine . 

I don't understand what the actual issue being reported here is. Is it something about extra transactions being made? Or about inclusion logic? Or about balance from nothing? Please clarify (or close, if it has been answered)

**Comment by dipenjoshi** [comment]
I just saw bunch of transaction going out of my account to this address as well. here's my ropsten address 0xD9e5e4bdE24Faa2B277ab2Be78C95b9ae24259A8, starting block is 3002539 and ends at 3013254

**Comment by blackwatertepes** [comment]
I'm experiencing this issue on a private Ethereum network, with no world access. So, this issue does not only exist on the public test nets, and is most likely caused from something related to the Ethereum codebase.

**Comment by laokan** [comment]
this error is confim, the bug when use web3.js transfer token, the he account all blances will give the 0x6Ef57BE1168628A2bD6c5788322A41265084408a address at rinkeby network &  0x6Ef57BE1168628A2bD6c5788322A41265084408a at main network,  what ?

**Comment by laokan** [comment]
https://rinkeby.etherscan.io/address/0x6ef57be1168628a2bd6c5788322a41265084408a
https://etherscan.io/address/0x6ef57be1168628a2bd6c5788322a41265084408a

**Comment by laokan** [comment]
https://etherscan.io/tx/0x0bffe0c95207789b5c3ad233954cd754378474b4ca5732cac474a5e3951cea4f

and  0x6ef57be1168628a2bd6c5788322a41265084408a this account has out transfer， what's wrong ？

**Comment by laokan** [comment]
i'm sure this is config error ,when the node 8545 port is open the internet (open the rpc right to the internet) ,some one has 0x6ef57be1168628a2bd6c5788322a41265084408a will attion you wallect ,wen use console unlock the account ,then the ether will be losted! please use firewall blocked the 8545 rpc's port.
please ban 0x6ef57be1168628a2bd6c5788322a41265084408a address

**Comment by holiman** [comment]
Ok, so this report relates to someone making transactions from your account(s)? Yes, do not open 8545 to the internet. That's highly dangerous. Especially if you use `unlock`.

**Comment by ligi** [comment]
I really wonder if this was the problem of the OP - hope he will answer and clarify (ping @haint87) - otherwise we should just close the issue as I see nothing actionable here

**Comment by dipenjoshi** [comment]
yes i use --unlock param when running geth. and port 8545 open from firewall. because i need to access to rpc from web3.js from another server.

**Comment by ligi** [comment]
@dipenjoshi as @holiman pointed out that is a really bad idea and you should stop doing this - there is no way to protect you when you are doing this. Can you elaborate a bit more on why you do this exactly?

**Comment by Tudmotu** [comment]
@ligi, if I need to be able to perform transactions on a private network via MetaMask, how do I do that without exposing 8545?

**Comment by ligi** [comment]
@Tudmotu exposing 8545 is not a problem generally - but this node should hold no accounts then. When using metamask the account is managed by metamask - so the node does not need the account ..

**Comment by Tudmotu** [comment]
OK, I am actually using ganache and I am using the auto-funded accounts feature, so the network starts up with 10 accounts that are pre-funded. I am using a custom mnemonic.
All the funds are transferred to 0x6Ef57BE1168628A2bD6c5788322A41265084408a after a couple of minutes.
Is there any explanation as to how is that possible?

**Comment by haint87** [comment]
I confirm this is bug of Rinkeby and Ropsten.

Note: 
1. If you send with the higher the gasPrice, 0x6Ef57BE1168628A2bD6c5788322A41265084408a will receive more ETH.
2. If you send without unlockAccount such as signTransaction, sendRawTransaction(Offline transaction), the bug is the same.

**Comment by laokan** [comment]
https://etherscan.io/txs?a=0x6ef57be1168628a2bd6c5788322a41265084408a
this address continue , & ehterum founder can blocked this address?

**Comment by haint87** [comment]
https://etherscan.io/address/0x6ef57be1168628a2bd6c5788322a41265084408a

Check this url, mainnet has an error as this bug.

**Comment by philsmd** [comment]
@haint87 yeah, this is an address and possibly a (known) address of a malicious users that is also mentioned on other forums/stackexchange etc. The attacker probably automatically finds insecure systems with not-secured/firewalled geth instances which are using unlocked accounts.... this is a well-known dangerous "feature" of geth and developers always discouraged the use of unlocked accounts on non-local systems. I think currently we have no evidence that these systems are secure and locked therefore we must assume that these "hacked" accounts are very insecure systems (not firewalled and unlocked, which is very dangerous of course!).

I still do not understand your claims about the "without balance" and the "ether received is larger if gas price is higher" claims. You need to explain in detail with transactions (not ethereum addresses!) what you think is going on (i.e. what is not okay in your eyes with these transactions, transaction != addresses).

**Comment by philsmd** [comment]
maybe I'm blind here, but if we look at the transaction https://ropsten.etherscan.io/tx/0x6d72fb71bbb03259f5de287061c96f301dcd684c379c8a0c55e03a18389c2b89  that you claim had 0 balance before the transaction, I can't confirm it with this tool:
https://ropsten.etherscan.io/balancecheck-tool

if I put address 0x71bed1e585f8cb8d840ac54715c9c5a642cb4cc1 and BlockNo 2999514 I get Balance = 0.0000000000001 Ether (the balance was not zero!) and after that block (i.e. 2999515), I get 0.000000000000001 Ether, this is as expected less than the previous balance (be aware that these online block explorers may not display all the after-comma digits and they may do some roundings, therefore it would be better to double-check the actual balance with geth/web3 or other tools that show the whole balance in wei). I still do not see why you claim that the sender's account is "without balance". There were some wei in that account before the transaction. Maybe you have a different/better example?

**Comment by haint87** [comment]
Update: 
The attacker exchanges ETH by Shapeshift...
https://etherscan.io/address/0x9d4f99555f94ae9e89a793be705f99c6f2afa2d2
https://etherscan.io/address/0x96e38a38a0a8b76331c1b6d2d52ecf0f08862e34

**Comment by karalabe** [comment]
I'll close this issue as it's not a bug in go-ethereum, rather badly configured nodes + active attackers on mainnet. Feel free to continue discussions on reddit or more appropriate forums where the community at large can participate too.

**Comment by haint87** [comment]
I think it's an error and ETH balance is from the sky falling

**Comment by holiman** [comment]
@haint87 please point to one specific transaction made with insufficient balance, and I will explain where it comes from.

**Comment by haint87** [comment]
Thanks for your answer. I don't want to post my system here, but it has the same error with more gas, the attackers have more ETH. 
I sent a test transaction with **gasPrice** 10.000.000.000.000 the attacker has 200ETH
I send a transaction the same with **gasPrice** 0 the attacker has 0.000000000000001 ETH.

I try to research and simulation as attackers do, but have not found yet.

Note: 
1. My system opens port default, clear all pending transactions -> the error working.
2. My system opens port other, clear all pending transactions -> the error working.
3. I do not use the unlockAccount function.

**Comment by philsmd** [comment]
Could you please make some screenshots (you could if you want/need only show the amount/fee/gas/gasPrice etc and hide/obscure the addresses etc) and explanation of the transaction flow etc.
What I currently do not understand is if you are claiming that whenever you are making a new/fresh transaction you see a 2nd transaction that you did not authorize ? is this the case or did I got this wrong? maybe you can explain this in more detail.

I think it would be best to have some RPC snif/logs to understand what is going on. Do you think you are able to set up a sniffer that can track what the attacker is doing ?
btw: this would be a good idea for the security guys to look into as well so maybe you can help @holiman etc to think about setting a system up like yours that acts like a honeypot. I think this shouldn't be too difficult or too expensive to run a completely open honeypot with RPC sniffer like this. A problem could be that it could take some time before shodan or other services find this new open port and connect to this (could take between some minutes to days if the IP is not already known). Another problem could be that different attackers connect to it and you can't really observe the same attack vector(s) like the one potentially used on @haint87 system.
Maybe/probably honeypots like this already exist!? @holiman ?

BTW: it could also be that your system is somehow (independently from go-ethereum etc) compromised @haint87 and some malware code is for instance attaching to the geth instance or you are running a modified/trojanized version of the geth binary etc. Did you try with a different system for which you know that there is no possibility that it is compromised/infected ? A fresh operating system installation with up-to-date anti-virus and operating system updates, for instance. The problem is that the causes for these problems could be very different. Furthermore, we really need some evidence and/or more detailed facts which you didn't provide yet... if you say that the attacker does this type of attack a lot also on non-private chains, why can't you link to a transaction ID (not a ethereum address, but a transaction, or set of transactions) where we can check the gas/fee/gasPrice/amount/input/outputs etc ?

**Comment by karalabe** [comment]
If you take a look at the transaction pool, the attacker doesn't just sign one transaction, rather submits thousands of pre-signed transactions. The effect is that it doesn't matter whether you secure your setup after the fact. Whenever your account receives funds, there's already a pending transaction pre-authorized with your account to spend those. You can't reuse an already compromised account, rather you need to switch to a new one.

**Comment by philsmd** [comment]
but let me understand this, this attack only works because the account was already unlocked in the past and the attacker had access to this unlocked account, right?
of course (and I fully agree with you @karalabe) you shouldn't continue using an address which you know was already compromised in the past.

**Comment by karalabe** [comment]
Indeed, that is my guess.

E.g. on Rinkeby, there are accounts with thousands of pre-authorized transactions going to this sink:

```
    0x300BAB56a81c096A21f2075964f095D635658834: {
      1000: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1001: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1002: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1003: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1004: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17857298877250104992 wei + 21000 gas × 75000000000 wei",
      1005: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1006: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1007: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1008: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1009: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1010: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1011: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1012: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1013: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17857298877250104992 wei + 21000 gas × 75000000000 wei",
      1014: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1015: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1016: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1017: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1018: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1019: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1020: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1021: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1022: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17857298877250104992 wei + 21000 gas × 75000000000 wei",
      1023: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1024: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1025: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1026: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1027: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1028: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1029: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1030: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17858852877250104992 wei + 21000 gas × 1000000000 wei",
      1031: "0x6Ef57BE1168628A2bD6c5788322A41265084408a: 17857298877250104992 wei + 21000 gas × 75000000000 wei",
[...]
```

**Comment by philsmd** [comment]
Is there some way that geth could (in future releases of geth) prevent pre-signing all these transactions even if the account has no funds ? As far as I know this is the main security hole that the attacker is exploiting, right?
Couldn't geth just refuse signing any transaction if the funds are not enough ? Or did I interpret this incorrectly (yeah, I'm still learning about all these details so please forgive me if I'm completely wrong here) ?

**Comment by haint87** [comment]
Thanks for yours hard working.

I'm still learn how to attacker do it. I think the problem is gas and gasPrice.

**Comment by Tudmotu** [comment]
@karalabe - To me, this happens on test nets with randomly generated accounts, that have not been compromised. Our system is docker based which means it's probably not "malware"...

How is it possible for someone to perform a transaction if they don't have the private key of the account? This feels like a real issue, where someone is able to perform transactions on behalf of arbitrary accounts.
In our case, all we do is start up the ganache node, and a couple of seconds later all the funds are transferred to the 0x6Ef57BE1168628A2bD6c5788322A41265084408a address.

**Comment by philsmd** [comment]
@Tudmotu are you sure that you do not use -u or --unlock within your ganache-cli command?
I think it would make sense to see if this only happens if you use ganache or also happens for you if you "just" use the latest geth binary alone. Could you please test this?

**Comment by Tudmotu** [comment]
Thanks @philsmd! I am not using ``--secure``. I will try that and see if it prevents this issue.
What does the ``--secure`` flag mean? Does it mean I don't need private keys to perform transactions on behalf of accounts?

**Comment by philsmd** [comment]
If we look at the description of --secure over here: https://github.com/trufflesuite/ganache-cli/ , it seems that the accounts are unlocked by default (which is very dangerous if you are running it on a world reachable/open network connection). Only with --secure the accounts are locked by default (and by using --unlock you can unlock specific accounts... which of course you should not do for these testings here because whenever you unlock the accounts the attackers can sign transactions on your behalf if they have access to your node).

I think this genache problem/discussion is mostly off-topic here, because it doesn't have anything to do with geth, as far as I can tell. Therefore, I would suggest that you just do not use unlocked accounts on wild open ports (insecure setup).

**Comment by Tudmotu** [comment]
Hi all,
This happens to me also with the ``--secure`` option. It's also transferring to ``0x7097f41f1c1847d52407c629d0e0ae0fdd24fd58`` now.
Next thing I'll try is to setup a geth node without accounts that is connected to the private ganache network. Anyone knows how to do that by any chance?

**Comment by siong1987** [comment]
@Tudmotu you might find this helpful: https://github.com/ethereum/go-ethereum/wiki/Setting-up-private-network-or-local-cluster

for using a different network with `ganache`, you can check it out here: http://truffleframework.com/docs/advanced/configuration#networks

**Comment by Tudmotu** [comment]
Thanks @siong1987  :)
Seems like I need to manually set peers via geth console, but I will look more into that and see if it can be done non-interactively.

**Comment by Jockeyvb** [comment]
ai... i am do err some nothing, same issues ,the address  0x7097f41f1c1847d52407c629d0e0ae0fdd24fd58

**Comment by haint87** [comment]
@Tudmotu this is a real issue.

**Comment by bradlucas** [comment]
I see that this issue was Closed but the original issue of the sending of ETH without a balance didn't seem to be addressed in the comments. 

I may be wrong but it seemed that having an open port of 8545 seemed to the issue and that was allowing outside actors to access an account.

I agree that having the open port and an unlocked account is a user issue but what about the ability to send ETH from an account which does not have a balance.

For example, see the following account.
 
- Account
https://ropsten.etherscan.io/address/0xd60e64afb753583941e1ab42f836ced0d23af2db

It is on Ropsten and by design is only meant to be a prototype and does have the 8545 port open and is accessed from a web page.

But, look what happened 20 days ago. 

First, the account was empty so I used a Faucet to get 2 ETH. Those transactions are here:

- Loaded the account with 2 ETH
```
0xb0a84863a0a6411fcfcc924d2b3439d3a4654cdac085aadb113bb707231f2a03	3155757	20 days 2 hrs ago	0xe17f97b518e9e8bbc9b72ab88fd3f9db10bea981	  IN  	0xd60e64afb753583941e1ab42f836ced0d23af2db	1 Ether	0.00021004
0x7dd9fceccfc230d234f54cbcad9a48f404cf472042f658a90cd028fb13a5e1b0	3155652	20 days 2 hrs ago	0x687422eea2cb73b5d3e242ba5456b782919afc85	  IN  	0xd60e64afb753583941e1ab42f836ced0d23af2db	1 Ether	0.00000105
```

Then the prototype was used a few times. You'll see the 0 ETH transactions (only TxFee). 

But, after three transactions there was this one which looks like entailed a transfer of 89 ETH out of this account.

- Somehow 89 ETH was transferred out
```
0x68442d7de4c4790dd53caaf0ea5eaee51e4c7775a85eb75f3088e87b6763ce22	3179284	16 days 14 hrs ago	0xd60e64afb753583941e1ab42f836ced0d23af2db	OUT	0x6ef57be1168628a2bd6c5788322a41265084408a	89.968911587469 Ether	0.00483
```

How could this happen? The account has a bit under 2 ETH in it but the transaction appears to be for about nearly 90 ETH.

I'm curious.

**Comment by haint87** [comment]
When you send with more gas attacker get more ETH (testnet). This is a real bug, but dev doesn't confirm it as a bug.

**Comment by karalabe** [comment]
@bradlucas According to Etherscan:

```
 Balance for 0xd60e64afb753583941e1ab42f836ced0d23af2db
At (Block#3179283) = 89.973741587469 Ether
```

https://ropsten.etherscan.io/balancecheck-tool?a=0xd60e64afb753583941e1ab42f836ced0d23af2db

**Comment by hadv** [comment]
yes, this account `0xd60e64afb753583941e1ab42f836ced0d23af2db` receive much mined reward before sending the 89ETH out. then it's not the problem.

**Comment by bradlucas** [comment]
@karalabe Thanks very much for pointing out the Balance Checker. I wasn't aware of that tool.

Also, @hadv I see now that we must have turned on mining for a bit. Your link shows that.

Thanks, both for clearing this up. Appreciate it.

**Comment by siong1987** [comment]
@haint87 i have been working on this PR that allows RPC server to set their own `username` and `password` by passing in `--rpcuser` and `--rpcpassword`. can you try it out with a `username` and a `password` to see whether the " bug" still persists? btw, once you set the `username` and the `password`, make sure that you authenticate your RPC calls with basic authentication headers - https://en.wikipedia.org/wiki/Basic_access_authentication

https://github.com/ethereum/go-ethereum/pull/16821

**Comment by marcosmartinez7** [comment]
@Tudmotu i tried to do that. I have tried to run 2 nodes, 1 of them with the rpc ports blocked and with the unlocked account, the other one has the rpc ports open but the account is locked.

The second node is just for interactions with metamas/myetherwallet/etc.

The thing is if i hit that 2nd node, since the account isnt unlocked, it can mine the blocks:

WARN [08-01|19:53:13.837] Block sealing failed
err="authentication needed: password or unlock"

Is there a way to build a "safe proxy" or something like that? a node that you can access by rpc and it will send the transactions to the other node that can mine?

**Comment by Tudmotu** [comment]
@marcosmartinez7 I personally didn't look more into this issue, so can't help unfortunately... 😕

**Comment by Micpittser84** [comment]
why does it matter if its just on the test network and has no value anyway?
