### ISSUE TITLE
Incompatibility abigen via sia(NebulousLabs)

### ISSUE THREAD

**Issue by Archie1978** [ethereum/go-ethereum#16544]
Hello,
    when I generate code go with github.com/ethereum/go-ethereum/cmd/abigen/abigen. The import is
"github.com/NebulousLabs/Sia/types". I am obliged to replace it with "github.com/ethereum/go-ethereum/core/types".

Kinds regard

**Comment by karalabe** [comment]
The issue is that we do not hard code import paths into the generated code, rather leave it empty, and then run `goimports` to find the correct imports. If you have a package with the same type signatures that also satisfies our generated code, `goimports` might use that instead.

We could investigate whether adding the go-ethereum imports and then running goimports correctly removes unused ones. That scheme though may break if we move packages around.
