### ISSUE TITLE
Ethereal (old go-ethereum) won't connect

### ISSUE THREAD

**Issue by theurbaner** [ethereum/go-ethereum#16590]
Hi everybody,

I hope someone can help me.

I have a very old version of an ethereum wallet / miner called Ethereal, developped by Obscuren.

I tried to launch it again recently but it won't connect to peers... I have some ether on it and would like to recover them...

Is there a way to make it connect to the peers again, and transfer my ether to a new wallet ?

Here is the printscreen :

![eth](https://user-images.githubusercontent.com/34656616/39373017-85ca7cea-4a46-11e8-9a79-897aaea02bfa.jpg)

Thanks in advance to anyone who could help me.

Ban

**Comment by karalabe** [comment]
I've been on this project for 3+ years and never heard about this :)) Maybe @fjl might remember something I don't? Or we can also ping @obscuren . That said, I don't think you could have any funds on such an ancient client, since even the Olympic testnet was already feature compatible with current geth with regard to account management.

Where did you get this "Ethereal" from? When did you use it? Why do you believe you have funds on it?

**Comment by obscuren** [comment]
I might have received an email about this and redirected him here. 

Ethereal is a very old client, developed back in 2014 and served as a development client. Obviously any ether mined with that client is useless as it served the poc phase.

**Comment by theurbaner** [comment]
Ok, thank you all 3 for the time you took and for your answers ! I understand that my cause is lost... :(
Bye !
