### ISSUE TITLE
WS Origin is undefined by default in web3 1.0, therefore only viable option is wsorigins set to "*"

### ISSUE THREAD

**Issue by Bunjin** [ethereum/go-ethereum#16608]
Running geth on ubuntu 16.04 with
/usr/bin/geth --ws --wsport 8540 --wsorigins 127.0.0.1

But ws is not available:

wscat -c ws://127.0.0.1:8540
error: Error: unexpected server response (403)

and the geth log:
geth[5403]: WARN [04-30|09:16:38] origin '' not allowed on WS-RPC interface

In this line:
https://github.com/Bunjin/go-ethereum/blob/master/rpc/websocket.go#L110

req.Header.Get("Origin") should be changed to req.Header.Get("origin")

PR:
https://github.com/ethereum/go-ethereum/pull/16609

Edit: This doesn't solve the issue, see below

**Comment by Bunjin** [comment]
I tried to rebuild from source with the fix in my PR, but it doesn't seem to solve the issue however.
origin or req.Header.Get("origin") is still undefined :'(

I'll investigate more and post here if I manage to solve this myself.

**Comment by Bunjin** [comment]
So actually this was a problem with web3 which doesn't set the origin.
https://github.com/ethereum/web3.js/blob/1.0/packages/web3-providers-ws/src/index.js#L78

I changed undefined to 127.0.0.1 and it worked :+1: 

https://github.com/websockets/ws

**Comment by vzts** [comment]
I've just experienced a similar issue. My situation was that I needed to use web3 1.0 websocket on my node side to connect to my local geth client.

After some investigations, my conclusion is that neither(geth or web3) needs to be changed. I'd like to share some research on this issue, with the help provided by Bunjin. Hope it can clear up some confusion that I had.

1. Most of the time in a browser dapp, web3 instance's provider is injected from outside(from MetaMask, Mist, etc.). The teams are still working to support web3 1.0(almost done, but not yet released as web3 1.0 is still in beta). So websocket provider in browser is not yet available for now. The [websocket provider that web3 1.0 itself provides](https://github.com/ethereum/web3.js/tree/1.0/packages/web3-providers-ws) is the websocket for the node(dependent on https://github.com/theturtle32/WebSocket-Node).

2. websocket's `Origin` header is set by the browser, and geth checks this header by default on websocket request([default settings is to only accept those from localhost](https://github.com/ethereum/go-ethereum/blob/master/rpc/websocket.go#L99)). This is to protect possible abuse and hijacking from other sites since WebSockets are not restrained by the same-origin policy.(see [this](https://security.stackexchange.com/questions/115716/is-the-origin-header-really-useful-for-securing-a-websocket) and [this](https://www.christian-schneider.net/CrossSiteWebSocketHijacking.html)) Also, note that `Origin` header is subject to be manipulated since it's only a header added by the browser.

3. And this `Origin` header may not have a valid meaning when used in Node side, since the request of node process is not really a user-agent scenario where the script is provided by a domain. See [the documentation from WebSocket-Node](https://github.com/theturtle32/WebSocket-Node/blob/master/docs/WebSocketClient.md#connectrequesturl-requestedprotocols-origin-headers-requestoptions):

> `origin` is an optional field that can be used in user-agent scenarios to identify the page containing any scripting content that caused the connection to be requested. (**This seems unlikely in node.. probably should leave it null most of the time.**)

I guess this is why the [web3 code](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-providers-ws/src/index.js#L78) left it `undefined`.

So all in all, one can just go with `--wsorigins *` option for geth, or specify `origin` header with some meaningful string on the web3 websocket provider's side that you will use specific origin and tell that string to geth's `--wsorigins`. One easy option might be just the thing that @Bunjin did with the web3, setting the `origin` as localhost, and does not give `--wsorigins` option since the geth defaults to accept requests from localhost.

**Comment by Bunjin** [comment]
Great write up, thanks @vzts !

**Comment by Levino** [comment]
Okay, then it is not possible to override the the "Origin" header with Javascript. This should indeed protect from cross site request forgery. But there is no link to prove that point.

**Comment by Bunjin** [comment]
https://security.stackexchange.com/questions/115716/is-the-origin-header-really-useful-for-securing-a-websocket

https://www.christian-schneider.net/CrossSiteWebSocketHijacking.html

**Comment by Levino** [comment]
Thanks!

**Comment by Bunjin** [comment]
I see, you want a strong proof that browsers indeed behave so.

maybe this global spec? 
https://www.w3.org/TR/websockets/

and then pick an open source browser and look at the code I guess :)

Let me know if you get the definite proof :)

**Comment by Levino** [comment]
Citing from there:
> Fire an event named message at the WebSocket object, using MessageEvent, with the origin attribute initialized to the serialization of the WebSocket object's url's origin, and the data attribute initialized to dataForEvent.

But then the following is true: Whenever a websocket connection to the server is opened **from within a browser** the Origin header will be set and have a value. So if the server receives a request without the Origin header, it is safe to respond, because it is a request coming from a **non browser environment** where the header can be set arbitrarily. Geth should be fixed and just respond normally when not finding a header instead of enforcing this hack to set the header by hand.

I come here because I stumbled on this while trying to get my tests running from node. It is very annoying to have to add such stuff to the production codebase just to make some tests run.

**Comment by vzts** [comment]
@Levino I think you could go with `--wsorigins *` option in that case. I agree with you that the geth should not arbitrarily assume that the client environment is a browser. Maybe the default behavior of geth should be fixed.

**Comment by Levino** [comment]
@vzts Thanks for joining the discussion. I fear your "solution" would just render the whole protection obsolete. Then any websocket from any website would be served. Whereas when just serving connections without an Origin header and serving connections with Origin headers which have a whitelisted origin would still keep the protection in place.

**Comment by vzts** [comment]
On your `serving connections without an Origin header and serving connections with Origin headers which have a whitelisted origin`, how can we check the origin without a header? I'm not sure I understood you correctly.

**Comment by vzts** [comment]
@Levino One quick thought on the nature of `WebSocket` though, WebSocket spec is nothing more than a standardization of lower level TCP socket, and it is for the **"web" specifically, where user-agents are mostly browsers**. So if you look at the history, the protocol itself is somewhat for the browser.

**Comment by vzts** [comment]
I've checked that the WebSocket protocol development has moved to IETF, and [here](https://tools.ietf.org/html/rfc6455) is the RFC. If you look at the 10.2 part "Origin Considerations":

>    The client
>    itself can contact the server and, via the mechanism of the |Origin|
>    header field, determine whether to extend those communication
>    privileges to the JavaScript application.  The intent is not to
>    prevent non-browsers from establishing connections but rather to
>    ensure that trusted browsers under the control of potentially
>    malicious JavaScript cannot fake a WebSocket handshake.

According to this, my original suggestion seems kind of valid.

**Comment by vzts** [comment]
Security consideration is always double-edged, and even if you have that origin header authentication on your server side, there's a way to manipulate that. So the origin header is only for preventing hijacking([the post](https://www.christian-schneider.net/CrossSiteWebSocketHijacking.html) I originally quoted), if you really want to whitelist the specific client you want, rather than general users that accessing your website from their browser, you will need to authenticate the users using other mechanisms such as private keys or tokens.

**Comment by Levino** [comment]
I was not challenging your original solution. It is a valid solution and I am using it:

When you run this (please note I changed the value for `Origin`)
```js
const wsProvider = new Web3.providers.WebsocketProvider("ws://localhost:8546", {
  headers: {
    Origin: "http://invalid.host"
  }
});
web3 = new Web3(wsProvider);
```
two different things happen depending on where it is run:
- If you run this code in the browser on `http://localhost:3000` the origin header will be set to `http://localhost:3000`
- If you run this code in node, the origin header will be set to `http://invalid.host`

The connection from node will only be allowed, when `http://invalid.host` is whitelisted in geth with the `--wsorigins http://localhost:3000,http://invalid.host` flag.

**BUT** when you run the code like so **in Node**:
```js
const wsProvider = new Web3.providers.WebsocketProvider("ws://localhost:8546")
web3 = new Web3(wsProvider);
```
then the origin header will be missing and geth will discard the connection to "protect against third party hijacking". The thing is: If the header is missing, it is safe to allow the connection: The "attacker" must be accessing the endpoint **non browser environment** (because otherwise the browser would have set the origin header). That means that the attacker can set any header she/he wants. So then the hacker just puts `http://localhost:3000` as the origin and gets access to the node. So instead of **enforcing the correct header** geth should **enforce a correct header, if the header is present**. If no header is present, just allow the access, there is no possible protection anyhow.

So back to the problem at hand:
- Your solution is a good workaround. For example (as in my case) to run headless tests with web3 in a node environment.
- It is not the best solution, because the best solution would require to fix the behaviour of geth, than your workaround is no longer necessary.

So I am making the point that someone did not really think things through when implementing the current behaviour of geth and this should be fixed instead of forcing everyone to use this workaround.

**Comment by vzts** [comment]
I would say that geth is behaving correctly, since it is suggested in the abstraction of the RFC:

>    The goal of this technology is to provide a mechanism for **browser-based
>    applications** that need two-way communication with servers that does
>    not rely on opening multiple HTTP connections

>    The security model used for this is the origin-based security model commonly used
>    by web browsers.

>    **Servers that are not intended to process input from any web page but
>    only for certain sites SHOULD verify the |Origin| field is an origin
>    they expect.**  If the origin indicated is unacceptable to the server,
>    then it SHOULD respond to the WebSocket handshake with a reply
>    containing HTTP 403 Forbidden status code.

If your server is intended to process input from any web page, then there is option "--wsorigins *". I think the origin header is okay to be forced by default since the main purpose of websocket technology is for the browsers, not the execution env like node.

**Comment by Bunjin** [comment]
>While I think your idea to validate origin header only when it exists is nice, but the opinions on the idea may be subjective. I really like it though. Agree with your idea.

Agreed, that would be a nice default behavior that would allow both to use node scripts without setting an origin while still having this browser protection for the users.

**Comment by holiman** [comment]
I tentatively agree that a request without `Origin` header should be excempt from origin-checks (since it's obviously not a CORS-attempt via the browser). 

I'll have to think about this for a bit, to figure out there any other cases to consider where this would have a negative effect on security.

**Comment by MicahZoltu** [comment]
@holiman Are you done thinking about this?  😉 This is causing problems with Augur and the current workaround is to tell users to do `--ws-origns '*'` which is not secure for them.

Your latest comment is correct, if no origin is present then it means the connecting client is not attempting to protect the user for cross origin attacks, most likely because it isn't a browser.  There is no situation where a client would submit no origin and expect to be protected against cross origin attacks since the mechanism for protecting against cross origin attacks is by supplying an Origin to the server and trusting the server to help you out with the protection.

**Comment by holiman** [comment]
We've decided today that to implement the suggested feature: a request without `Origin` header should be excempt from origin-checks (since it's obviously not a CORS-attempt via the browser).

**Comment by Levino** [comment]
Hooray!
