### ISSUE TITLE
Geth crashed on filter (creation?)

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#1665]
While using the wallet this just happened:

https://gist.github.com/frozeman/d5fcabe62e13da081e86

I assume the wallet wanted to create new filters, or where polling filters.

**Comment by obscuren** [comment]
Looked in to the issue. This can happen when a filter is being created and almost immediately fired before `xeth` has a chance to add it to the queue.

This can be fixed by moving the internal callback creation after the initialisation code. This will prevent any action being taken by filter **before** the filter queue has been created on `xeth`.

**Comment by frozeman** [comment]
In web3 we add them only to the polling queen after the filter id arrived, but it could have happened a race conditions somewhere.

Could you at least let the g client fail silently, e.g. returning an error that the filter doesn't exist yet
