### ISSUE TITLE
Error "Dangling trie nodes after full cleanup" and crash during shutting down

### ISSUE THREAD

**Issue by chfast** [ethereum/go-ethereum#16749]
#### System information

Version: 1.8.8-stable
Git Commit: 2688dab48c9b8ae71b8d95c7678817eaa17f2b53
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10.1
Operating System: linux

#### Steps to reproduce the behaviour
```
geth --lightserv 10
```

#### Backtrace

Full log attached.

```
^CINFO [05-17|18:16:35] Got interrupt, shutting down...
INFO [05-17|18:16:35] IPC endpoint closed                      endpoint=/home/chfast/.ethereum/geth.ipc
INFO [05-17|18:16:35] Writing cached state to disk             block=5630135 hash=e34615…023d3a root=4875bb…5f0b17
INFO [05-17|18:16:40] Persisted trie from memory database      nodes=630415 size=180.92mB time=4.617355567s gcnodes=1158624 gcsize=499.64mB gctime=4.061997519s livenodes=200750 livesize=85.29mB
INFO [05-17|18:16:40] Writing cached state to disk             block=5630134 hash=629a9b…0ed691 root=b64fb9…3605b5
INFO [05-17|18:16:40] Persisted trie from memory database      nodes=1319   size=532.87kB time=17.621581ms  gcnodes=0       gcsize=0.00B    gctime=0s           livenodes=199431 livesize=84.75mB
INFO [05-17|18:16:40] Writing cached state to disk             block=5630008 hash=20fc82…71a357 root=a9ad74…4bb9ec
INFO [05-17|18:16:41] Persisted trie from memory database      nodes=59368  size=23.33mB  time=1.029860796s gcnodes=0       gcsize=0.00B    gctime=0s           livenodes=140063 livesize=61.42mB
ERROR[05-17|18:16:42] Dangling trie nodes after full cleanup
INFO [05-17|18:16:42] Blockchain manager stopped
INFO [05-17|18:16:42] Stopping Ethereum protocol
INFO [05-17|18:16:42] Ethereum protocol stopped
INFO [05-17|18:16:42] Stopping light Ethereum protocol
fatal error: sync: unlock of unlocked mutex

goroutine 3283334 [running]:
runtime.throw(0xf2ab35, 0x1e)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/panic.go:616 +0x81 fp=0xc4e5f0c170 sp=0xc4e5f0c150 pc=0x440c81
sync.throw(0xf2ab35, 0x1e)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/panic.go:605 +0x35 fp=0xc4e5f0c190 sp=0xc4e5f0c170 pc=0x440bf5
sync.(*Mutex).Unlock(0xc42d2a4640)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/sync/mutex.go:184 +0xc2 fp=0xc4e5f0c1b8 sp=0xc4e5f0c190 pc=0x487062
runtime.call32(0x0, 0xfa0330, 0xc457a2c0f0, 0x800000008)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/asm_amd64.s:573 +0x3b fp=0xc4e5f0c1e8 sp=0xc4e5f0c1b8 pc=0x46dc1b
panic(0xdd5280, 0x108dd10)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/panic.go:502 +0x229 fp=0xc4e5f0c288 sp=0xc4e5f0c1e8 pc=0x440649
runtime.chansend(0xc431d98de0, 0xc4e5f0c378, 0xc45438d301, 0xab3f6b, 0xffffffffffffffff)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/chan.go:245 +0x583 fp=0xc4e5f0c310 sp=0xc4e5f0c288 pc=0x419783
runtime.chansend1(0xc431d98de0, 0xc4e5f0c378)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/chan.go:125 +0x35 fp=0xc4e5f0c348 sp=0xc4e5f0c310 pc=0x4191f5
github.com/ethereum/go-ethereum/les/flowcontrol.(*ClientManager).accept(0xc42d2a4640, 0xc42b2929c0, 0x22f022129e31b, 0xc4e5f0c400)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/les/flowcontrol/manager.go:195 +0x1eb fp=0xc4e5f0c390 sp=0xc4e5f0c348 pc=0xab3f6b
github.com/ethereum/go-ethereum/les/flowcontrol.(*ClientNode).AcceptRequest(0xc441a6d6b0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/les/flowcontrol/control.go:75 +0xe3 fp=0xc4e5f0c3c8 sp=0xc4e5f0c390 pc=0xab2ca3
github.com/ethereum/go-ethereum/les.(*ProtocolManager).handleMsg.func1(0x1, 0x20, 0x108fc00)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/les/handler.go:351 +0x75 fp=0xc4e5f0c440 sp=0xc4e5f0c3c8 pc=0xae0af5
github.com/ethereum/go-ethereum/les.(*ProtocolManager).handleMsg(0xc4202602d0, 0xc441f63680, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/les/handler.go:524 +0x1289 fp=0xc4e5f0dc68 sp=0xc4e5f0c440 pc=0xac0509
github.com/ethereum/go-ethereum/les.(*ProtocolManager).handle(0xc4202602d0, 0xc441f63680, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/les/handler.go:327 +0x727 fp=0xc4e5f0ddf8 sp=0xc4e5f0dc68 pc=0xabef87
github.com/ethereum/go-ethereum/les.NewProtocolManager.func1(0xc484d11b60, 0x1093e00, 0xc4225a6cb0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/les/handler.go:175 +0x23b fp=0xc4e5f0df00 sp=0xc4e5f0ddf8 pc=0xae04ab
github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc4225a6cb0, 0xc484d11b60, 0x1093e00, 0xc4225a6cb0)
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/p2p/peer.go:348 +0x66 fp=0xc4e5f0dfc0 sp=0xc4e5f0df00 pc=0x985ce6
runtime.goexit()
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc4e5f0dfc8 sp=0xc4e5f0dfc0 pc=0x4703e1
created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
	/home/travis/gopath/src/github.com/ethereum/go-ethereum/p2p/peer.go:347 +0x201
```
[geth.log](https://github.com/ethereum/go-ethereum/files/2014013/geth.log)

**Comment by upers** [comment]
I have same problem in my private POA net.
I got error:
---------------------------------ERROR--------------------------------------
Error: invalid merkle root
########## BAD BLOCK #########
Chain config: {ChainID: 452 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: <nil> Engine: clique}

Number: 1626771
Hash: 0x53e5c4ded722ddbe00dbd8c153aa3b64741d15b5d731f5ffe745b2e1bca2d259
----------------------------------------------------------------------------------------
I fixed this by restarting all nodes and adding peers manually through the get.ipc.

But in 10 hours  all my nodes stopped synchronizing and accordingly ceased to create blocks.
Message from log: "ERROR[06-01|17:58:24] Dangling trie nodes after full cleanup."
I can not clean the block because there is valuable information there.
I tried restart nodes and added peers manually, it didn't work.

And there no error messages in log, only: "Signed recently, must wait for others."
Geth version: 1.8.3-stable.
Go version: go1.10.1
OS: ubuntu 16.04
Genesis file:
{
  "config": {
    "chainId": 452,
    "homesteadBlock": 1,
    "eip150Block": 2,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 3,
    "eip158Block": 3,
    "byzantiumBlock": 4,
    "clique": {
      "period": 3,
      "epoch": 30000
    }
  },
  "nonce": "0x0",
  "timestamp": "0x5ac632c4",
  "extraData": "0x00000000000000000000000000000000000000000000000000000000000000002368c95eb9ea3578a20d6887ccb40773499b93d5c67be939661d2559acfb059fc1737a2ceaaed4ae0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0x47b760",
  "difficulty": "0x1",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "alloc": {
    "2368c95eb9ea3578a20d6887ccb40773499b93d5": {
      "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
    },
    "c67be939661d2559acfb059fc1737a2ceaaed4ae": {
      "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
    }
  },
  "number": "0x0",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
}

**Comment by adamschmideg** [comment]
This issue seems to describe three different problems. If the problem persists, please open a separate issue.
