### ISSUE TITLE
about whisper

### ISSUE THREAD

**Issue by mccoysc** [ethereum/go-ethereum#16807]
as a message system,why make it more user friend ,for example:
support interface like unix socket interface and set all options using setsockopt to control all the options.
i assume that using whisper as "net-band" ,not as a message system,transfer all data through whisper.

and another suggestion:no need to import whisper or other network layer to etherum,keeping whisper as a standalone "data-channel" like the net band.
if not ,more security issues would be imported and may no day that i can see whisper being released.

**Comment by gballet** [comment]
Thank you for your thoughts and concerns about Whisper.

indeed, whisper is not intended to be a messaging system as much as a high-latency low-throughput general-purpose communications protocol whose sole focus is to guarantee darkness.

Suggestions have been made, to use it as an encryption layer wrapping around other protocols like HTTP or even TCP/IP. It clearly doesn't scale for this kind of applications, in this respect writing a unix socket interface isn't warranted. If that's what you're looking to do, have a look at PSS, for which people have already tried to wrap other protocols into.

As for whisper belonging to Ethereum, that is because it belongs to the ecosystem and that the EF is paying for its development. People running `geth` do not have to run Whisper, so it is already separated enough. There are other, independent solutions like bitmessage, which are already independent from the ecosystem.

I'm closing this issue as I feel the questions have been addressed, feel free to re-open it if you feel they have not.
