### ISSUE TITLE
Add metrics for database compaction

### ISSUE THREAD

**Issue by AlekSi** [ethereum/go-ethereum#16922]
It would be helpful to add metrics when LevelDB runs compaction in addition to logs (#15347). Simple `1` when compaction is underway and `0` when it is off would be good. If we can extract more metrics (durations, etc.), they would be helpful too.

**Comment by rjl493456442** [comment]
We have already supported the metrics for compaction!

How to retrieve the metric data?
1. enable the metric by `--metrics`
2. attach to your geth node `geth attach geth.ipc`
3. retrieve compaction information `debug.metrics(true).eth.db.chaindata.compact`

**Comment by AlekSi** [comment]
Thanks, write delay metrics are enough for me.

**Comment by rjl493456442** [comment]
@AlekSi hey, i was thinking about adding some metrics to indicate compaction progress. The question is i have to make sure whether the long pause is due to **single long compaction** or **many continuous compaction**. 
For the former, the `eth.db.chaindata.compact` will not update anymore and geth node will print `Database compacting, degraded performance` log.  **For this situation**, a `inflight compaction progress data` will be valuable.
For the latter,  the `eth.db.chaindata.compact` will keep update, and i think this metric data is enough.

So maybe i need your feedback to decide whether we should do something.
