### ISSUE TITLE
Countless issues when doing basic GETH syncing

### ISSUE THREAD

**Issue by devedse** [ethereum/go-ethereum#16935]
Hi all,

Long time Ethereum and GETH user here, a few days ago I've started setting up a new FAST synced GETH node but as I keep running into more and more issues and the GO-Ethereum issue list seems to be stuffed with issues from 2017 regarding not getting basic sync functionality to work I would like to summarize that most of these issues are in fact still happening in version 1.8.10 of GETH.

#### System information

Geth version: 1.8.10
OS & Version: Windows
Commit hash : N/A

### GETH FAST sync issues:
`geth --datadir "F:\GethChain" --syncmode "fast" --rpc --rpcaddr 0.0.0.0 --rpccorsdomain="*" --rpcapi="db,eth,net,web3,personal,web3" --rpcvhosts=*`

#### 1. GETH Syncing is quite fast for the first 95% of the blocks and then drops to a halt.

Fast (earlier blocks):
![image](https://user-images.githubusercontent.com/2350015/41192067-f2d30fc2-6bf8-11e8-80fd-14163bc28415.png)

Incredibly slow (latest blocks):
![image](https://user-images.githubusercontent.com/2350015/41192074-18203f3e-6bf9-11e8-89a7-e805a59b5fa5.png)

Why can't it just get the last 1000 blocks in one go and import it like it does with all the older blocks?

I also read the post here: https://github.com/ethereum/mist/issues/3097#issuecomment-389521963
But this doesn't explain why we are about 200  blocks behind

#### 2. Randomly stopping with syncing

It was syncing 2 minutes ago and now it is not:

![image](https://user-images.githubusercontent.com/2350015/41192092-55dac13c-6bf9-11e8-80f4-5c0f396ef790.png)

#### 3. Synchronisation failed: Dropping peer and being silent for 30-120 minutes at a time

Sometimes when I log into my GETH machine in the morning I see that it shows some Warnings and then decided to stop syncing again. After an hour or 2 it decides to continue.

#### 4. When starting the synchronisation process it doesn't seem to start syncing sometimes untill about 5 minutes into the process

![image](https://user-images.githubusercontent.com/2350015/41192134-e4161eb0-6bf9-11e8-9cc1-389ad224f4d5.png)

#### 5. When trying to close the GETH client an error pops up:

`[06-09|15:31:10] Dangling trie nodes after full cleanup`

![image](https://user-images.githubusercontent.com/2350015/41192157-34d54c2c-6bfa-11e8-982a-fe4df2162dba.png)

#### 6. Second time running the GETH sync process it won't do a FAST sync anymore

It currently seems to be impossible to get GETH to sync in one go without having to restart it at least a dozen times. So if it only syncs the first few 100.000's of blocks with a fast sync before it's first crash, what's the use of FAST sync?

![image](https://user-images.githubusercontent.com/2350015/41192323-2df12988-6bfc-11e8-8bad-4e11e18d2aaa.png)

#### 7. The use of FAST sync

What is actually the use of FAST sync nowadays? It took until the very very end of syncing blocks and chain data before I could see my funds in metamask. Isn't this the thing that FAST sync should try to avoid?

#### 8. Synchronisation failed, dropping peers when starting the FAST sync:

![image](https://user-images.githubusercontent.com/2350015/41192446-047b3cf4-6bfe-11e8-8e44-2016bdf35259.png)

This was another start of the synchronization process on my node that was fully synced a few minutes ago.

Another one:

![image](https://user-images.githubusercontent.com/2350015/41192893-abe6da28-6c05-11e8-8e26-24ee12438013.png)

### GETH LIGHT sync issues:
`geth --datadir "F:\GethChainLight" --syncmode "light" --rpc --rpcaddr 0.0.0.0 --rpccorsdomain="*" --rpcapi="db,eth,net,web3,personal,web3" --rpcvhosts=*`

#### 1. When launching LIGHT sync on an empty folder it seemed to start but then it just stops. Eth.syncing is also false

![image](https://user-images.githubusercontent.com/2350015/41192215-f24da7f4-6bfa-11e8-84d1-0d35b2a382d1.png)

(Waited for about 15 minutes here this time)

Also connecting to the node with Metamask seems to work but my funds is displayed as 0. So it is in fact not synced up.

### Summary

I guess I'm trying to express my frustrations here around the user friendliness and buggyness of GETH more than anything else.

So if any of these errors are due to my wrongdoing, also please inform me, but if not it might be good to see how we can work on improving the experience on working with GETH.

Edit: Tried to run another sync on my local PC:
```
Processor: 3770k
Memory: 32GB
Cache set to: 10GB
Storage: Samsung 960 pro 1TB SSD
```
The sync itself seemed to run quite okay untill reaching the end where some more random stalls appeared.

![image](https://user-images.githubusercontent.com/2350015/41254357-8350b1aa-6dc3-11e8-9413-c9a97094cba4.png)

**Comment by whizzard80** [comment]
Fast sync only runs the very first time you start geth by default.  After that, you need to add the flag to the command.  I had to jump through some hoops to get geth and the regular GUI java client working together, and outlined my process in the sync issues megathread #3097.  Even with everything seemingly set up perfectly I can't get geth to sync in windows 10 without restarting it multiple times as I outlined in my comment.  I gave up on using anything but the default data dir because both Java client and command line mode only seemed to agree with defaults.  I hope these sync issues are all ironed out over time but for now, it is what it is.  Have you tried a fully default folder and settings sync?  Are you only going to use the console to run geth?

**Comment by devedse** [comment]
@whizzard80 , I'm not sure if your link is correct as it links to a pull request instead of an "Issues megathread".

I did try this on a clean machcine so I assume the geth removedb command is not needed. I did not try to sync to the default location because Azure Machines don't really have enough C Drive space to store the whole chain.

**Comment by whizzard80** [comment]
Ya link was bad.  Are you using a local machine or a server on a cloud?  What kind of disk are you storing the chain on?  Is there a way to do a I/O test on the hard disk your trying to sync to be sure the speeds are correct?  Sorry not that familiar with an Azure Machines.

**Comment by devedse** [comment]
@whizzard80 , I am using an Azure Machine. The storage that's behind is is Azure SSD storage. Haven't been able to do a performance test yet but as it does seem to obtain the first 95% of blocks in like a week I assume that the machine is more then capable enough to keep up.

**Comment by karalabe** [comment]
Here's the fix for the invalid hash chain error. Still testing it though https://github.com/ethereum/go-ethereum/pull/17839

**Comment by holiman** [comment]
Re
1. GETH Syncing is quite fast for the first 95% of the blocks and then drops to a halt.

It's because first you're fast-synching, after sync to the pivot point it actually process every block/transaction from the pivot point up to the chain head. 

4. When starting the synchronisation process it doesn't seem to start syncing sometimes untill about 5 minutes into the process

It's probably searching for suitabe peers at that time. Though I agree that 5  minutes is a bit suspisciously long. 

5. When trying to close the GETH client an error pops up:

That one I think is fixed. 

6. Second time running the GETH sync process it won't do a FAST sync anymore

Yep, once you've fast-synced, you will have to sync block by block. The alternative is to wipe the database and do a fast-sync from scratch.

**Comment by holiman** [comment]
We believe this is closed now.  Please reopen separate tickets for remaining stuff.
