### ISSUE TITLE
Release 1.1.0 locks passwordless accounts permanently

### ISSUE THREAD

**Issue by almindor** [ethereum/go-ethereum#1699]
The change in rpc/api/personal.go line #129 causes "empty" passwords to not be accepted (even if they work ok for account creation and deletion).

This causes all previously empty-password accounts to be unlockable. Fix is easy, remove the if.

**Comment by obscuren** [comment]
Thank you

**Comment by almindor** [comment]
I actually started on one but then it seemed the latest in "develop" didn't have that if. That got me confused as to what's the latest I should be making changes toward :)

**Comment by almindor** [comment]
Hups not sure if this is to be closed yet

**Comment by bas-vk** [comment]
The if statement is a basic check if the user has supplied a password. In the case of an empty password, or the user didn't supply the password in the request the user is presented with a password prompt. It is possible to unlock the account by hitting enter without typing anything. This will unlock accounts with an empty password. Note, there was/is a problem with the password prompt. This is fixed in #1710

Removing the if checkout isn't possible since it will give problems on the http channel. It can probably be removed later when we have a reliable way of asking the user for sensitive information.

**Comment by almindor** [comment]
I don't think that'd fix this issue. The check is specifically length(password) > 0 and if it fails it errors out.

But password "" is length = 0. Unless that if was change it will lock people with no passwords on their accounts in.

**Comment by karalabe** [comment]
Fixed in https://github.com/ethereum/go-ethereum/pull/1739
