### ISSUE TITLE
Reference to issue "Ethers are wiped out in account during sendTransaction or migrations #16936"

### ISSUE THREAD

**Issue by samaujs** [ethereum/go-ethereum#16992]
Unfortunately, tokens are transferred again today to the same account **"https://rinkeby.etherscan.io/address/0x7097f41f1c1847d52407c629d0e0ae0fdd24fd58"**
at block **"2464270"**
This time it is with the following information :
(1) The account is unlocked with Metamask and not geth; within only appropriately 20 minutes, ethers are being transferred;
(2) geth --rinkeby --rpc --rpccorsdomain "http://localhost:8000" --rpcapi="personal,eth,network,web3,net" --ipcpath "~/Library/Ethereum/geth.ipc"
with  **--rpcaddr "0.0.0.0"**  already removed

**Comment by karalabe** [comment]
The issue here is that an attacker can pre-sign arbitrarily many transactions ahead of time. Once they find an unlocked account accessible over the internet, they will just sign many many many transactions into the future, so whenever there are funds, they can drain it without having access any more to the original account.

The only way out is to use a new account which wasn't leaked out.

**Comment by samaujs** [comment]
Does it mean that as long as the public address of an unlocked account has been acquired once, the exposure is permanent even without the need of obtaining the private key?  Subsequently, this attack is possible whenever the port 8545 is opened in the earlier provided geth command and at the same time the account is unlocked?  Lastly, is there a way to obtain and/or cancel the many pre-signed transactions by the identified attacker?  Thanks.

**Comment by brandoncurtis** [comment]
If at _any time_ an attacker is able to sign transactions for an account (e.g. through an unlocked account on an Ethereum node), that account is vulnerable forever and must be abandoned.  Once the attacker has the signed transactions in-hand, they don't need any access to your node in order to drain the funds.  There is no way to cancel presigned transactions.

**Comment by samaujs** [comment]
Thanks, looks like the best thing to do is avoid this breached account address.  Is this the same for account in the main Ethereum network?  Literally, transferring the balance ethers from the breached account to another account address soonest possible.  Similarly, not using the breached account address anymore.  Thanks.

**Comment by brandoncurtis** [comment]
If the attacker used an unlocked node to sign transactions, they may only have signed transactions for whichever network the node was connected to or they may have signed transactions for every network.  The safest course of action is to abandon the compromised account and generate a new one.
