### ISSUE TITLE
Better logging on android

### ISSUE THREAD

**Issue by ligi** [ethereum/go-ethereum#17156]
Opening the issue after talking to @0mkara who is behind react-native-geth and asked me about:

`err "context deadline exceeded`

and the geth team. The main problem here is that this is logged as an error - should be logged as info or warning as there is nothing a developer consuming geth can do here but it can happen e.g. when a peer disapeers (pun intended) which can and will happen in a p2p network. But this needs serious work on the go-mobile logging framework and is not high priority as there are bigger fishes to fry still. Mainly opening this issue to not loose track of this and maybe give hints to developers searching for this error.

**Comment by karalabe** [comment]
I think in order to progress on this, we need to better understand how logging works in general on Android. If anyone could chip in with a tiny explanation, it would be great.

Currently within go-ethereum we use `gomobile` to create the Go->Java bindings. The binding generator takes whatever is output to `stderr` and converts it to error logs (and maybe `stdout` is converted to info logs?). As such, the way the mobile framework currently logs is that our Go logger just prints whatever to `stdout`, which gets picked up by `gomobile` and fed into `logcat`.

A better alternative would be to expand the `log` package with an `AndroidHandler`, so that when a log is being raised, we don't blindly dump it into `stderr` with the `StreamHandler`, rather we can call platform APIs directly on `logcat`.

This shoudn't be too much work really, just needs a bit of Android experience, a bit of logger framework investigation, and the ability to use and test results via `gomobile`.

**Comment by ligi** [comment]
Logging in android is done with a call to static methods the Log class: 

https://developer.android.com/reference/android/util/Log

the method used determines the log-level. 
For libraries it is also nice if they do not directly log this way but use a logging framework (slf4j is widely used but I am more a fan of [timber](https://github.com/JakeWharton/timber)) - to give consuming apps more control (e.g. interceptions like log to remote or suppressing logs)

**Comment by 0mkara** [comment]
I think same can be done for `ios` platform. Will try to find necessary information.

**Comment by monkeymitch** [comment]
I would like to take on this issue if it has not already been taken
