### ISSUE TITLE
eth.getBalance("0xef8a6d106715c7dc7f1953dbab6e95772d39ee34") retrun 0??but the account has 0.002958ether

### ISSUE THREAD

**Issue by weiweiloong** [ethereum/go-ethereum#17163]
Hi ，
Geth/v1.8.12-unstable-e916f978/linux-amd64/go1.10.3
sudo ./geth --datadir=/home/ethereum --ethash.dagdir=/home/ethereum --rpcapi eth,web3,personal --rpcport 8600 --port 8601 --rpc
-------------------------------------------------------------------------------------------------
[wut@localhost bin]$ sudo ./geth attach /geth-data/geth.ipc
Welcome to the Geth JavaScript console!

instance: Geth/v1.8.12-unstable-e916f978/linux-amd64/go1.10.3
coinbase: 0xa47884ca0829f4e7e49bf76f099c0354a9f10420
at block: 0 (Wed, 31 Dec 1969 19:00:00 EST)
 datadir: /geth-data
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0
> eth.syncing
{
  currentBlock: 5948954,
  highestBlock: 5949019,
  knownStates: 110998113,
  pulledStates: 110985873,
  startingBlock: 5948354
}
> eth.coinbase
"0xa47884ca0829f4e7e49bf76f099c0354a9f10420"
> personal.listAccounts
["0xef8a6d106715c7dc7f1953dbab6e95772d39ee34", "0x24935493d494a98a8df4ae47a1f4854b70665a1a", "0xa26cbac16ddece549ce104dfb2c596f009cc2dc1", "0xa47884ca0829f4e7e49bf76f099c0354a9f10420"]
> eth.getBalance("0xef8a6d106715c7dc7f1953dbab6e95772d39ee34")
0
> eth.getTransaction("0xc7901523b8191c899b792fed08d054c7cf2100db510b593994b029c66ad3577c")
{
  blockHash: "0xe64acb76c901f5fd646ea74ef70dbfb9a0317ee59bb18223425db599622c9c5f",
  blockNumber: 5838759,
  from: "0xef8a6d106715c7dc7f1953dbab6e95772d39ee34",
  gas: 400000,
  gasPrice: 2000000000,
  hash: "0xc7901523b8191c899b792fed08d054c7cf2100db510b593994b029c66ad3577c",
  input: "0x",
  nonce: 0,
  r: "0x2dbaf7c09f013af83018f166f2c17f57f135e664b9e1196a2de853f03594ec88",
  s: "0x2e5c46b3319109485e1988ce42d5b560bc12aba506398007a643346f4803e786",
  to: "0x55b1a238aab922118f07e38ed02cf14b388925de",
  transactionIndex: 48,
  v: "0x25",
  value: 150000000000000000
}

**Comment by karalabe** [comment]
Syncing Ethereum is a pain point for many people, so I'll try to detail what's happening behind the scenes so there might be a bit less confusion.

The current default mode of sync for Geth is called fast sync. Instead of starting from the genesis block and reprocessing all the transactions that ever occurred (which could take weeks), fast sync downloads the blocks, and only verifies the associated proof-of-works. Downloading all the blocks is a straightforward and fast procedure and will relatively quickly reassemble the entire chain.

Many people falsely assume that because they have the blocks, they are in sync. Unfortunately this is not the case, since no transaction was executed, so we do not have any account state available (ie. balances, nonces, smart contract code and data). These need to be downloaded separately and cross checked with the latest blocks. This phase is called the state trie download and it actually runs concurrently with the block downloads; alas it take a lot longer nowadays than downloading the blocks.

So, what's the state trie? In the Ethereum mainnet, there are a [ton of accounts already](https://etherscan.io/chart/address), which track the balance, nonce, etc of each user/contract. The accounts themselves are however insufficient to run a node, they need to be cryptographically linked to each block so that nodes can actually verify that the account's are not tampered with. This cryptographic linking is done by creating a tree data structure above the accounts, each level aggregating the layer below it into an ever smaller layer, until you reach the single root. This gigantic data structure containing all the accounts and the intermediate cryptographic proofs is called the state trie.

Ok, so why does this pose a problem? This trie data structure is an intricate interlink of hundreds of millions of tiny cryptographic proofs (trie nodes). To truly have a synchronized node, you need to download all the account data, as well as all the tiny cryptographic proofs to verify that noone in the network is trying to cheat you. This itself is already a crazy number of data items. The part where it gets even messier is that this data is constantly morphing: at every block (15s), about 1000 nodes are deleted from this trie and about 2000 new ones are added. This means your node needs to synchronize a dataset that is changing 200 times per second. The worst part is that while you are synchronizing, the network is moving forward, and state that you begun to download might disappear while you're downloading, so your node needs to constantly follow the network while trying to gather all the recent data. But until you actually do gather all the data, your local node is not usable since it cannot cryptographically prove anything about any accounts.

If you see that you are 64 blocks behind mainnet, you aren't yet synchronized, not even close. You are just done with the block download phase and still running the state downloads. You can see this yourself via the seemingly endless `Imported state entries [...]` stream of logs. You'll need to wait that out too before your node comes truly online.

---

**Q: The node just hangs on importing state enties?!**

A: The node doesn't hang, it just doesn't know how large the state trie is in advance so it keeps on going and going and going until it discovers and downloads the entire thing.

The reason is that a block in Ethereum only contains the state root, a single hash of the root node. When the node begins synchronizing, it knows about exactly 1 node and tries to download it. That node, can refer up to 16 new nodes, so in the next step, we'll know about 16 new nodes and try to download those. As we go along the download, most of the nodes will reference new ones that we didn't know about until then. This is why you might be tempted to think it's stuck on the same numbers. It is not, rather it's discovering and downloading the trie as it goes along.

**Q: I'm stuck at 64 blocks behind mainnet?!**

A: As explained above, you are not stuck, just finished with the block download phase, waiting for the state download phase to complete too. This latter phase nowadays take a lot longer than just getting the blocks.

**Q: Why does downloading the state take so long, I have good bandwidth?**

A: State sync is mostly limited by disk IO, not bandwidth.

The state trie in Ethereum contains hundreds of millions of nodes, most of which take the form of a single hash referencing up to 16 other hashes. This is a horrible way to store data on a disk, because there's almost no structure in it, just random numbers referencing even more random numbers. This makes any underlying database weep, as it cannot optimize storing and looking up the data in any meaningful way.

Not only is storing the data very suboptimal, but due to the 200 modification / second and pruning of past data, we cannot even download it is a properly pre-processed way to make it import faster without the underlying database shuffling it around too much. The end result is that even a fast sync nowadays incurs a huge disk IO cost, which is too much for a mechanical hard drive.

**Q: Wait, so I can't run a full node on an HDD?**

A: Unfortunately not. Doing a fast sync on an HDD will take more time than you're willing to wait with the current data schema. Even if you do wait it out, an HDD will not be able to keep up with the read/write requirements of transaction processing on mainnet.

You however should be able to run a light client on an HDD with minimal impact on system resources. If you wish to run a full node however, an SSD is your only option.
