### ISSUE TITLE
Contract tutorial out of date?

### ISSUE THREAD

**Issue by fivedogit** [ethereum/go-ethereum#1730]
Hi. I, like many folks, am new to ethereum and geth usage, so take this with a grain of salt. However, I think the contract tutorial (which has been fairly helpful) is out of date. When I tried to follow the instructions to the letter, for instance, inputting this to the console:

var greeterSource = 'contract mortal { address owner; function mortal() { owner = msg.sender; } function kill() { if (msg.sender == owner) suicide(owner); } } contract greeter is mortal { string greeting; function greeter(string _greeting) public { greeting = _greeting; } function greet() constant returns (string) { return greeting; } }'

I would always get:

"undefined"

Even "var x = 1;" would return "undefined". 

After scratching my head for a while, I removed the "var" portion of each command and it all worked. I'm not sure why this would be the case or what changed since the docs were written, but it would appear they need to be updated.

https://github.com/ethereum/go-ethereum/wiki/Contract-Tutorial

**Comment by karalabe** [comment]
`undefined` is the result of the operation `var i = 1;`. There is no result, since this is a declaration, so there's nothing to output. If you write in another line `i` after you declare it, you'll see it is indeed correctly defined and its contents will be displayed.

**Comment by linagee** [comment]
```Javascript
> var x = 1;
  undefined
```
Same in Chrome Javascript terminal. This is the expected behavior since as karalabe pointed out, it's a declaration. (I just wanted to point out to that you can test in Chrome and see that it has a consistent result there too.)

Way too much discussion on the matter: http://stackoverflow.com/questions/22844840/why-does-javascript-variable-declaration-at-console-results-in-undefined-being#answer-22844864
(tl;dr: because ECMA says so)

**Comment by fivedogit** [comment]
Ok. Thanks and sorry for the useless report.

**Comment by zunware** [comment]
This was a problem for me too. I assumed something was wrong when I got 'undefined' . This is a bit confusing
