### ISSUE TITLE
Setting ulimit appropriately (too many open files)

### ISSUE THREAD

**Issue by yackx** [ethereum/go-ethereum#17312]
`geth` failed with the dreaded "too many open files" error message:

```
CRIT [08-02|11:33:54] Failed to store hash to number mapping
err="open /home/youri/.ethereum/geth/chaindata/128935.ldb: too many open files"
```

Issue has already been [reported](https://github.com/ethereum/go-ethereum/issues/16006) and [workaround suggestion](https://github.com/ethereum/go-ethereum/issues/15582#issuecomment-391127507) can be found. I understand [a fix has already been merged](https://github.com/ethereum/go-ethereum/pull/16009) sot that `geth` honors the OS hard number of files in `ulimit`, and I assume that fix is present in `1.8.13`.

However, my default `ulimit` seems too low for `geth`:

```
$ ulimit -Sn
1024
$ ulimit -Hn
4096
```

I am not allowed to increase the hard limit on the shell even with `sudo` so instead:

```
$ grep youri /etc/security/limits.conf
youri         soft       nofile     10000
youri         hard       nofile     20000

$ reboot

$ ulimit -Sn
10000
$ ulimit -Hn
20000
```

### Question / Suggestion

I have no idea if `20000` is appropriate (too high? too low?), or if it can cause adverse effects on my aging hardware.

* Is there an official recommendation to set the `ulimit`
    * values for `soft` and `hard`
    * how to, including troubleshooting common `pam` problems if `ulimit` is not taken into account
    * possible side-effects
* Maybe more info in `ERR` when it crashes (current limit, pointer for some help)
* Does it make sense for `geth` to require such a large number of files, that one would normally expect running a large corporate DBMS for instance?

What do you think?

### Info

* geth 1.8.13
* Linux Mint 19 XFCE (kernel 4.15.0-29)
* Core2Duo, 4Gb RAM, SSD SATA3  😓

**Comment by ligi** [comment]
> Does it make sense for geth to require such a large number of files, that one would normally expect running a large corporate DBMS for instance?

basically geth is a large DBMS instance - not corporate though ,-)

A lot of projects in this space have to deal with this problem - e.g. @ipfs https://github.com/ipfs/go-ipfs/issues/3792

I think it would make sense to split this issue into actionable items - meta-issues like this are always hard to deal with and especially hard to close.

**Comment by YouriAckx** [comment]
In order to make it more practical:

1. Extending error messages to become verbose, let alone to include suggestions on how to resolve usually makes the code less readable. People will google the error message and find relevant info anyway - ideally, some documentation, or at worst, a SO topic or a GitHub issue. So maybe not the way to go (pun intended)

2. Regarding the number of file handles, I'm in no position to assess, I just wanted to point it out but I assume nobody here will reply and say : "oh yes, we totally overlooked that, why are we opening so many files again?" 😉 

3. This leaves documentation as an actionable item. So, what would be considered a good practice regarding `ulimit`? It crashed with `20000` but I had to turn off that poor machine because of the heat. I'll retry `30000`. I noticed it's `unlimited` on my MBP.

Let me know if it's ok to discuss the options here, then if you find it relevant, I can create one or several new issues at a later stage (and close this one) to have something more practicable to work on. Not sure I can be of a big help to actually solve it, but I'll try, for sure.

HTH

**Comment by nutmix** [comment]
This bug is still there in 1.8.13-stable-225171a4.

We are plagued by "accept: Too many open files" whenever we try to us the rpc apis.

We tried raising the proces and user limits to 32,000, but it always is limited to around 2000.

cat /proc/sys/fs/file-nr
2112	0	3280354
cat /proc/2160/limits | grep files
Max open files            32000                32000                files     

The only work around we have found mentioned to this bug is to have a loop continuously resetting the limits, but this is too much of a hack, and still gives the too many files open error, just less often.

**Comment by YouriAckx** [comment]
> but it always is limited to around 2000

@nutmix You mean in `geth` itself, not on your OS?

**Comment by nutmix** [comment]
@YouriAckx it seems to be geth itself setting the 20xx limit.  At least I have read several bugs which say this is its current behaviour, and what I see would agree with this diagnosis. Basically, I can raise the open file limit for all users, and for the geth process, and I see these changes using cat /proc/pid/limits for example, but geth still fails with "accept: too many open files" when the total OS open files are around 2000.  I raised every OS limit possible, but geth still fails when I hit the RPC APIs.

**Comment by YouriAckx** [comment]
You're right @nutmix, [this fix](https://github.com/ethereum/go-ethereum/pull/16009) is present in tag `v1.8.13` but it does not seem to solve the issue. Before the fix, the limit would be reduced, and after the fix, it can be raised, but not above `2048`. And it is still capped on `master`.

I don't understand the intent of:

```
if limit > 2048 { // cap database file descriptors even if more is available
    limit = 2048
}
```

Maybe some project member could shed some light on that. In the meantime I'll resync to see how it performs.

**Comment by YouriAckx** [comment]
Well, that didn't take long, "too many open files" after a few minutes. S=15000 and H=30000.

**Comment by YouriAckx** [comment]
I've tried to tweak `makeDatabaseHandles()` in `flags.go` to increase the number of file and database handles, but no luck. The program runs a bit longer but eventually fails. I've tried insanely high numbers (20000) but this makes no sense since the stable code base caps at 2048 (half of it for DB connections) and somehow it works for most people I would assume. And the machine starts to become less responsive, even with `ionice` and `renice`.

@nutmix Are you running geth on an old hardware like I am, with plain old SATA3 ? Maybe on slower hardware the I/O contentions get higher and somehow exhaust the connection (file or db) handles. But I'm just conjecturing.

I'm running out of ideas.

**Comment by nutmix** [comment]
@YouriAckx No, we are running it on fast HW, with SSD and decent IOPS.  Specifically, 8 CPU, 32GB ram, separate volume for OS and Blockchain. (Linode 32GB standard instance).  There is nothing else running on the box.

We have given up trying to use geth and the RPC api - there seems to be no workaround for the too many open files issue at the moment.   We tried upping the various file handle limits to crazy levels, still fails with a single app hitting the RPC API, with no parallelisation.

**Comment by YouriAckx** [comment]
No luck on gitter. [Some settings](https://gitter.im/ethereum/go-ethereum?at=5b74381f196bc60b6bd28f27) from somebody who has no problem running geth:

```
# lsof | grep geth | wc -l
11058
# ulimit -Sn
1024
# ulimit -Hn
1048576
```

**Comment by karalabe** [comment]
Geth was previously hard capped to 1K file descriptors for the database. We removed that limit on the latest release, will be pushed shortly.

**Comment by 1265578519** [comment]
谢谢，我也发现了S1024限制，等待新版，
