### ISSUE TITLE
using xgo to compile geth meet an err in go-duktape.v3

### ISSUE THREAD

**Issue by xiaoxuez** [ethereum/go-ethereum#17329]
i used xgo to compile geth locally and failed in macos

the info is ⤵️
```# github.com/ethereum/go-ethereum/vendor/gopkg.in/olebedev/go-duktape.v3
duk_minimal_printf.c: In function 'duk_minimal_sprintf':
duk_minimal_printf.c:286:35: error: 'SIZE_MAX' undeclared (first use in this function)
  ret = duk_minimal_vsnprintf(str, SIZE_MAX, format, ap);
                                   ^
duk_minimal_printf.c:286:35: note: each undeclared identifier is reported only once for each function it appears in
2018/08/07 12:41:41 Failed to cross compile package: exit status 2.
```

somebody knows something wrong?

**Comment by karalabe** [comment]
What OS are you compiling from and what OS to?

**Comment by xiaoxuez** [comment]
@karalabe  os is from macos to android
I read the eth wiki about xgo, then compile  cmd/geth locally, then this error happens.
then I use your go-ethereum respority and the andorid-path-fix branch to compile, it works！Thank you for your contribution！！
So.. Can't I compile directly using the official go-eth repository?

**Comment by karalabe** [comment]
Hmmm, where did you find a `android-path-fix` branch? We don't maintain any specific branches for Android (make sure you're not building some very ancient version of our code). We don't use `xgo` to build the Android library btw, rather use `gomobile` directly (`make android`). Please use that, since that prepares a correct `.aar`. You could also download a pre-built archive from our downloads page (https://geth.ethereum.org/downloads/), or you could also use Maven Central / Sonatype. 

You can read up on more at https://github.com/ethereum/go-ethereum/wiki/Mobile:-Introduction .

**Comment by xiaoxuez** [comment]
I have used `gomobile ` to get a .aar file. It is ok~

I see another way on android by the [page](https://github.com/ethereum/go-ethereum/wiki/Ethereum-on-Android) about xgo..

Then I use `xgo --deps=https://gmplib.org/download/gmp/gmp-6.0.0a.tar.bz2 --remote=https://github.com/karalabe/go-ethereum --branch=andorid-path-fix --targets=android-16/arm --pkg=cmd/geth github.com/ethereum/go-ethereum` to build..

**Comment by xiaoxuez** [comment]
```
./build/env.sh xgo --go=latest --dest=build/bin -v --targets=android-23/arm64 ./cmd/geth
```
It also works~
Thank you for your time and your answer~
