### ISSUE TITLE
Ubuntu: apt-get wants install ethereum-swarm, file-name /usr/bin/swarm collides

### ISSUE THREAD

**Issue by leberknecht** [ethereum/go-ethereum#17336]
Ubuntu package `ethereum` wants to install `ethereum-swarm` which wants to write `/usr/bin/swarm`, which is already existing on my system and belongs to package https://github.com/torognes/swarm 
Dunno how such naming-collisions are normally resolved (just guessing according to docker/moby/docker.io naming-horror that there is no common rule? like "first come, first serve")

#### System information

Package version: `ethereum-swarm_0.3.1+build14601+xenial_amd64.deb`
OS & Version: Linux
Commit hash : N/A

#### Expected behaviour
`swarm` is a very generic word, i would suggest to be more explicit here and change the binary name to `ethereum-swarm`, which would also be in-sync with the package name

#### Actual behaviour
Name of the executable collides:
```
$ sudo apt-get -f install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following package was automatically installed and is no longer required:
  swarm
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  ethereum-swarm
The following NEW packages will be installed:
  ethereum-swarm
0 upgraded, 1 newly installed, 0 to remove and 21 not upgraded.
1 not fully installed or removed.
Need to get 0 B/5.560 kB of archives.
After this operation, 22,2 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
(Reading database ... 1209236 files and directories currently installed.)
Preparing to unpack .../ethereum-swarm_0.3.1+build14601+xenial_amd64.deb ...
Unpacking ethereum-swarm (0.3.1+build14601+xenial) ...
dpkg: error processing archive /var/cache/apt/archives/ethereum-swarm_0.3.1+build14601+xenial_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/swarm', which is also in package swarm 2.1.6-1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/ethereum-swarm_0.3.1+build14601+xenial_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

#### Steps to reproduce the behaviour
```bash
docker run --rm -ti ubuntu:16.04 /bin/bash
apt-get install software-properties-common
add-apt-repository -y ppa:ethereum/ethereum
apt-get update
apt-get install swarm
apt-get install ethereum
```

**Comment by leberknecht** [comment]
Ah sorry, dups https://github.com/ethereum/go-ethereum/issues/17295

**Comment by nonsense** [comment]
The project name is Swarm, and the binary name will stay `swarm` for the time being. This has been the consensus within the team when we discussed this.

If you wish to use https://github.com/torognes/swarm (`apt-get install swarm`), then you would have to find another way to install our project, because these two project binaries conflict - for example download the binary from http://swarm.ethereum.org/ and rename it and place it anywhere on your PATH.

If you are not using https://github.com/torognes/swarm, then you can uninstall it, and `apt-get install ethereum-swarm`.

However I agree that we have to add a `conflict` within the Debian Control file in order to signal to the user that `ethereum-swarm` and `swarm` conflict with each other.
