### ISSUE TITLE
Possible memory leak with bind.NewTransactor()?

### ISSUE THREAD

**Issue by qbetti** [ethereum/go-ethereum#17411]
Hi everyone,

Just sharing this little observation about the retrieval of private key using package bind.

#### System information

OS & Version: Windows, 32 bits
Commit hash : 6d1e292eefa70b5cb76cd03ff61fc6c4550d7c36

#### Expected behaviour
The result of `bind.NewKeyedTransactor(privateKey)` and `bind.NewTransactor(wallet, "passphrase")` should be the same (right?).

#### Actual behaviour
`bind.NewTransactor(wallet, "passphrase")` seems to allocate a huge amount of **persisting (leaking?)** memory (~256MB)

#### Steps to reproduce the behaviour
I observed that the following code results in a quite huge and **persisting** memory consumption:

    import (
        "github.com/ethereum/go-ethereum/accounts/abi/bind"
    )

    const WALLET_PATH string = "my/wallet/path"
    func main() {
        data, _ := ioutil.ReadFile(WALLET_PATH)

        auth, _ := bind.NewTransactor(strings.NewReader(string(data)), "")
        _ = auth

        log.Fatal(http.ListenAndServe(":8080", nil))  
        // the program always uses 256MB of memory
    }

Whereas the following, even though it produces (I think) a pointer to an identical object, results in a few MB persisting memory consumption: 

    import (
        "github.com/ethereum/go-ethereum/accounts/abi/bind"
    )

    func main() {
        privateKey, err := crypto.HexToECDSA("cba2dc76e88397f87cfa4705917fea76c7017a7c2958582095236dd272b507fa")

        if err != nil {
            log.Fatal(err)
        }

        auth := bind.NewKeyedTransactor(privateKey)
        _ = auth

        log.Fatal(http.ListenAndServe(":8080", nil))  
        // the program uses a few MB of memory
    }

Why is that? Once the private key has been generated, the memory consumption of these programs should be roughly the same, right?

Thank you for your answers!

**Comment by karalabe** [comment]
The key files are encrypted with an algorithm called `scrypt`, which ensures that it takes a lot of effort to decrypt them, both computationally and memory consumption wise. A single decryption is targeted to take about 1 second on a modern machine and require 256MB of memory. This is the reason why accessing an encrypted private key will take a memory hit versus using the decryped key in the first place will not.

As to why the memory consumption persists, it's because Go's garbage collector holds on to allocated memory and will only return it to the system after some amount of time (2 or 5 minutes, not sure), to avoid constantly requesting/returning memory. If you wait about 5+ minutes, the memory consumption of the first program will drop down to the same level as the second one.

**Comment by qbetti** [comment]
Your answer is very clear and much appreciated!
Thank you, sir!
