### ISSUE TITLE
eth.getTransactionReceipt returns unmined transaction

### ISSUE THREAD

**Issue by ppratscher** [ethereum/go-ethereum#1746]
I encountered a very interesting issue today with geth:

According to the eth.getTxReceipt call the Tx 0x22e123f06e13791a6d405b123cd06bba9e7c33fd90da1a0cd0fe247a976b71b9 should be part of block 159157.

```
eth.getTransactionReceipt("0x22e123f06e13791a6d405b123cd06bba9e7c33fd90da1a0cd0fe247a976b71b9")
{
  blockHash: '0x9088c969d375682be12bd124f99331b10c9e536dbd39bd24b1215294e91cbbc8',
  blockNumber: 159157,
  contractAddress: Error: Cannot access member 'constructor' of null,
  cumulativeGasUsed: 1596000,
  gasUsed: 21000,
  logs: [ ],
  transactionHash: '0x22e123f06e13791a6d405b123cd06bba9e7c33fd90da1a0cd0fe247a976b71b9',
  transactionIndex: 75
}
```

But the block actually does not include the tx:

```
eth.getBlock(159157)
{
  difficulty: '6613932524610',
  extraData: '0x',
  gasLimit: 3141592,
  gasUsed: 21000,
  hash: '0xa7aab86cb87aa010ae9682cf6195240e44c68bd6ba36b0410c52805ccd0a88e8',
  logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  miner: '0x007f7f58d3eb5b7510a301ecc749fc1fcddbe14d',
  nonce: '0x417a526f892d5294',
  number: 159157,
  parentHash: '0xf6f8fde51ffce094a0e776725a99027efb6bb725e3bdc652119797103995461c',
  sha3Uncles: '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347',
  size: 632,
  stateRoot: '0xd5eb3ea83cd3ffb95a977047ddb6c59969121bffaa190a8e2aa7ef0f9d719045',
  timestamp: 1440832088,
  totalDifficulty: '466998104304796487',
  transactions: ['0xfad63c6cf7ea42ecf716fd13854d6f9db691923a8fa9cea26df5097be4a36b07' ],
  transactionsRoot: '0xe1fecdb2334ab1cae02e5e1e7bd249d461d09dfeb46e02c30096542f87848acf',
  uncles: [ ]
}
```

Is there an issue with the tx receipt call or why does it point to an invalid block hash?

I can provide a copy of my blockchain if required?

**Comment by karalabe** [comment]
Can you please run and paste this?

`eth.getBlock('0x9088c969d375682be12bd124f99331b10c9e536dbd39bd24b1215294e91cbbc8')`

**Comment by ppratscher** [comment]
```
eth.getBlock('0x9088c969d375682be12bd124f99331b10c9e536dbd39bd24b1215294e91cbbc8')

```

Returns empty

**Comment by karalabe** [comment]
Can you give us the sender or recipient address of the txn?

**Comment by ppratscher** [comment]
``` eth.getTransaction("0x22e123f06e13791a6d405b123cd06bba9e7c33fd90da1a0cd0fe247a976b71b9")
{
  blockHash: '0x9088c969d375682be12bd124f99331b10c9e536dbd39bd24b1215294e91cbbc8',
  blockNumber: 159157,
  from: '0xe6a7a1d47ff21b6321162aea7c6cb457d5476bca',
  gas: 22000,
  gasPrice: '50000000000',
  hash: '0x22e123f06e13791a6d405b123cd06bba9e7c33fd90da1a0cd0fe247a976b71b9',
  input: '0x',
  nonce: 11787,
  to: '0x18883522e2679aa9b41e0fa688f20c3802897525',
  transactionIndex: 75,
  value: '2975177071523455000'
}
```

**Comment by karalabe** [comment]
I think we have a possible hypothesis of what might have caused the issue in the first place. I think the transaction was indeed successfully mined at a certain point, but then a higher TD block (not containing the txn) appeared, the chain was reorganised and the transaction history overwritten. The issue was that all nodes marked the transaction already done, so none bothered to resend them. This issue should be addressed by https://github.com/ethereum/go-ethereum/pull/1669, though I don't have an ETA on it as Jeff's on holiday for another week or so.

A second issue that you correctly raised though is that such "disappearing" transactions should also be dropped from the database, or marked reorganized or something. I'll cross link this issue into Jeff's PR to he can add this check in there along with the resend fixes.

In the mean time, a very crude fix could be to assume that a transaction with an "uknown" containing block after a few blocks have probably disappeared due to reorganizations and should be resent, though @Gustav-Simonsson please point out any implications inseen to me :)

**Comment by Gustav-Simonsson** [comment]
@karalabe well it could also be re-orged back again :) The best advice meanwhile #1669 is yet to be merged is to wait for a reasonable number of confirmations before acting on the result of the tx.

**Comment by fjl** [comment]
@obscuren is this resolved?

**Comment by obscuren** [comment]
I don't know. I've put it on my TODO list.
