### ISSUE TITLE
add API to get transactions for accounts

### ISSUE THREAD

**Issue by almindor** [ethereum/go-ethereum#1749]
As far as I can say there's currently no API to get all the transactions for a given account(s).

There should be a way to do this. I tried using eth_NewFilter but that seems to only return contract info. Something like NewFilter should be possible for getting transactions belonging to a specific set of accounts (receiver OR sender both) and it should follow NewFilter logic so only certain history can be requested.

If this is already possible please advise on how.

**Comment by karalabe** [comment]
The JSON RPC API does not specify returning account transactions, and the reason we are reluctant to support it is because it is something already achievable through contracts, and contracts are meant to be the main driving entities in the system, not end user accounts (those should initiate things).

However, we as many people did request this feature, it is on our consideration list to the future Go API which is under design now, so with a bit of luck, we might actually also add support for this, but that's a bit more into the future (not more than 1-2 months hopefully).

Maybe @obscuren can weigh in as if I remember correctly he had some strong opinion about this.

**Comment by maran** [comment]
I think some more discussion can be found here #1703.

**Comment by wildbunny** [comment]
Any updates on this? Polling every block and looking for transactions to a specific account is starting to cost serious CPU time.

**Comment by karalabe** [comment]
I'll close this in favor of a newer duplicate issue that has some semi-active discussion on it. https://github.com/ethereum/go-ethereum/issues/1897

**Comment by MelbourneDeveloper** [comment]
When is this going to be added?

**Comment by jdneidig** [comment]
My vote is for eth_listTransactions 
We made T-shirt, it’s Free
https://simbachain.com/community/join-our-community/
