### ISSUE TITLE
getWork package only updated when new block arrives

### ISSUE THREAD

**Issue by ppratscher** [ethereum/go-ethereum#1759]
it looks like the latest geth version does only reset the getWork package if a new block arrives, that might explain why we see so many blocks with a block time of 1 second. You can check it by running the following code side by side with the geth log:
```
var web3 = require('web3');
web3.setProvider(new web3.providers.HttpProvider('http://localhost:8545'));

updateCurrentWork();
function updateCurrentWork() {
  web3.eth.getWork(function(error, data){
    console.log(data[0]);
    setTimeout(updateCurrentWork, 150);
  });  
}
```
The block hash only changes when a new block is imported. But shouldn't it change from time to time as the block timestamp is updated to the current time?

**Comment by Gustav-Simonsson** [comment]
@ppratscher The issue with T+1 was due to a bug that's been fixed and merged into the latest releases. It's correct the block-to-mine is not reset unless a new block is received. We're looking into miner strategies and possible changes to the difficulty adjustment & total difficulty algos which could impact this.

**Comment by obscuren** [comment]
ethminer actually relies on this feature to determine a new work cycle.

And Gus is right
