### ISSUE TITLE
Nonce reuse when balance too low to send transaction

### ISSUE THREAD

**Issue by FreekPaans** [ethereum/go-ethereum#17606]
Not sure if this is actually a bug/problem/undesired, but ran into it and didn't find it documented anywhere.

When you send 2 transactions that sum to an amount that you don't have the balance for, but you do have the balance for the individual transaction, geth will accept both transactions.

Example:

Balance 1 eth
Tx1: send 0.6eth
Tx2: send 0.6eth

Geth will accept both transactions, but drop the Tx2 when the first transaction is mined. Any new transaction you'll send will use the nonce for Tx2.

I've traced this down to `txPool.validateTx` using the `currentState` to check the balance. Using `pendingState` would probably solve this. But not sure if this is by design or not. Either way, the fact that this happens is logged at `TRACE` in `txPool.demoteUnexecutables`: `log.Trace("Removed unpayable pending transaction", "hash", hash)`. It might be better to log this at a higher level since it seems kind of important.

#### System information

Geth version: 1.8.3 (seen on other versions as well, checked code on 1.8.15)
OS & Version: Ubuntu 16.04

#### Expected behaviour

Not sure.

#### Actual behaviour

Both are accepted.

**Comment by karalabe** [comment]
This is working as intended. There's no way to know how much your balance will be after some number of transaction executions, so we can only take into consideration your current balance (yes, we could try to track some virtual balances, but there's an awful lot of things that could go wrong to the point where currently it's not worth the pain).

As for removing transactions that fail some preconditions, that happens all the time. Raising it to info or warning level would just flood all people's logs with superfluous messages. We perhaps could do if for local accounts though, since the user might be more interested in those.

**Comment by FreekPaans** [comment]
@karalabe fair enough. Local accounts being logged a bit higher seems like a good idea. Guess this issue can be closed.
