### ISSUE TITLE
[feature request] Add more information on self-destruct results obtained via debug_traceTransaction

### ISSUE THREAD

**Issue by pw96pw96pw96** [ethereum/go-ethereum#17660]
Small feature request:
:) 

#### System information

Geth version: 1.8.x
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"debug_traceTransaction","params":["transaction_hash", {"tracer": "callTracer"}],"id":1}' 127.0.0.1:8545
```
return
```
...{"type":"SELFDESTRUCT", "from":"0xabc...", "to":"0xefg...", "value":"0x...", "error":"..."}...
```
#### Actual behaviour
```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"debug_traceTransaction","params":["transaction_hash", {"tracer": "callTracer"}],"id":1}' 127.0.0.1:8545
```
return
```
...{"type":"SELFDESTRUCT"}...
```
#### Backtrace

````
[backtrace]
````

**Comment by pw96pw96pw96** [comment]
![selfdestruct](https://user-images.githubusercontent.com/20891594/45437327-7412a380-b669-11e8-907e-19c8f3944184.png)

**Comment by holiman** [comment]
This is really a duplicate of https://github.com/ethereum/go-ethereum/issues/16459#issuecomment-383048636 , right? 

You could try modifying https://github.com/ethereum/go-ethereum/blob/master/eth/tracers/internal/tracers/call_tracer.js#L64 , and add `balance`. Now, you can't modify the file (because it has to be souped up into a resource-bundle) and simply rebuild, but what you could do is copy it into a separate file, edit, and send the javascript with the call, to see if works.

**Comment by pw96pw96pw96** [comment]
In fact, yes, a duplicate. Our company is looking at avoiding modification of the internals of geth to obtain that information (because we are able to get that info via modification of geth source code at this moment) solely via the public API.

**Comment by holiman** [comment]
Oh, so the tracers are only semi-internal. The caller can either send in some JavaScript, or select a predefined js script. The bundled ones are to be considered examples and PoCs, and I would encourage you to build on the callTracer and add the desired functionality. 

The tracing feature is implemented to cater for this type of tracing, and the few built-in ones were never the intended end-goal. 

But sure, we might at some point add that to the callTracer.
