### ISSUE TITLE
[feature requests] From() Method in types.Transaction

### ISSUE THREAD

**Issue by lmittmann** [ethereum/go-ethereum#17717]
Hi, I'd like to propose to add a function `From()` to the type [`Transaction`](https://github.com/ethereum/go-ethereum/blob/master/core/types/transaction.go). This function would make it possible to retrieve the sender of a transaction more conveniently.

The transaction already contains the unexportet field `from` for cashing reasons. I am not really familiar with the mechanics that populate and use this field. However, I imagine the implementation of the function could look something like this:

```go
// From returns the sender address of the transaction.
func (tx *Transaction) From() *common.Address {
	if tx.from == nil {
		from, err := Sender(HomesteadSigner{}, tx)
		if err != nil {
			return nil
		}
		tx.from = from
	}
	return tx.from
}
```

**Comment by adamschmideg** [comment]
An idea would be to add a function like `expensiveGuessOfSender()`

**Comment by princesinha19** [comment]
@lmittmann As far as I understand you want to get the sender of the transaction. Right?
If yes, You can get it by using **eth_getTransaction()**.

**Comment by MariusVanDerWijden** [comment]
I don't think this needs to be a feature of the transaction. It's currently possible to retrieve the signer of a transaction like this:
```
sender, err := types.Sender(types.HomesteadSigner{}, tx)
```
This is imo an acceptable api for golang users. `Sender` also caches the result so only the first call to it will execute the expensive address recovery from the transaction. As @princesinha19 pointed out the `eth_getTransaction()` api enables json-rpc users to get the transaction sender.

There exists pretty okayish api's for both json-rpc and golang so I don't think we need this feature, especially since many users would just use it willy-nilly and not think about the implications (runtime).

**Comment by alexandru-calinoiu** [comment]
When I try to get the sender this way I get an error `invalid transaction v, r, s values`
