### ISSUE TITLE
Possible bug with tx fees inclusion

### ISSUE THREAD

**Issue by drhashes** [ethereum/go-ethereum#17729]
#### System information

Geth version: geth 1.8.15 stable
OS & Version: Ubuntu 16.04

#### Expected behaviour
Maximize included fees in block.

#### Actual behaviour
Seems that under certain conditions fees is reset to zero.

#### Steps to reproduce the behaviour
Start geth for pool mining.

#### Backtrace
An example (readable log below):
Block 6370533 is imported at 00:47:27.877. The next round of work starts on 6370534. Then 6370533 is again imported (first 6370533 probably became an uncle).
Here it comes! Watch the fees for the round 6370534: 0, 0.1600905232, 0. It would seem that as soon as 6370533 is imported in the middle of round 6370534 the fees is reset to 0! Block 6370534 was then found and no fees included..

[backtrace]
INFO [09-21|00:47:21.794] Commit new mining work                   number=6370533 uncles=0 txs=132 gas=7991403 fees=0.2046197766
INFO [09-21|00:47:27.789] Commit new mining work                   number=6370533 uncles=0 txs=132 gas=7996634 fees=0.2074531949

INFO [09-21|00:47:27.877] Imported new chain segment               blocks=1 txs=75  mgas=7.982  elapsed=167.579ms mgasps=47.633  number=6370533

INFO [09-21|00:47:27.892] Commit new mining work                   number=6370534 uncles=0 txs=0   gas=0       fees=0
INFO [09-21|00:47:28.861] Commit new mining work                   number=6370534 uncles=0 txs=141 gas=7995851 fees=0.1600905232

INFO [09-21|00:47:30.406] Imported new chain segment               blocks=1 txs=49  mgas=7.976  elapsed=190.518ms mgasps=41.864  number=6370533

INFO [09-21|00:47:30.407] Commit new mining work                   number=6370534 uncles=1 txs=0   gas=0       fees=0

INFO [09-21|00:47:30.922] Successfully sealed new block            number=6370534 
INFO [09-21|00:47:30.922] mined potential block                    number=6370534

INFO [09-21|00:47:31.132] Commit new mining work                   number=6370535 uncles=0 txs=0   gas=0       fees=0
INFO [09-21|00:47:31.873] Commit new mining work                   number=6370535 uncles=0 txs=134 gas=7992083 fees=0.2123682669

**Comment by rjl493456442** [comment]
@drhashes Thanks for the report! 

The mining mechanism in the geth is: we will maintain a batch of mining works in the single mining round and we will always try to push the new mining work to the mining pool. So actually for which block is mined in this round is totally depends on the miner itself.

So why do we need to maintain a batch of mining works?
For example, when we receive a new head block from the network, we will create an empty block and throw it to mining pool immediately since the transaction execution can last 200ms, we want to save this part of time.

And during the long mining procedure(about 15s), a lot of new transactions will arrive, some of them may have very high gas price. So we will recreate the mining block every once in a while to include more transactions or transactions with higher price.

Besides, We will also try to recreate a new mining block when we receive a uncle if the current mining block contains less than 2 uncle.

All in all, we want to create the mining block flexibly to increase the average block reward.

**Comment by drhashes** [comment]
Thanks for the reply.
So you are saying that this special situation (which will not occur very often) is not easy to avoid (or perhaps should not be avoided).
Atm I'm wondering if it could be worth to pay the price of 200 ms given the special case when importing in the middle of the round?

**Comment by rjl493456442** [comment]
@drhashes Actually we assume miner will switch from the old work to new work asap once new mining work is pushed. But yes, there is always a delay, so the miner could still working on the old one.
