### ISSUE TITLE
feature request: argument for bad blocks blacklist to prevent fast-syncing to an incorrect chain 

### ISSUE THREAD

**Issue by cdetrio** [ethereum/go-ethereum#17935]
During the recent Constantinople chain split on the Ropsten testnet, users experienced difficulty fast syncing to the correct chain. In a fast sync, geth will download all block headers, and then start fast syncing to the chain with the highest Total Difficulty. If the highest TD chain has an incorrect block prior to the fast sync block, geth will "skip" past it, leaving the client on an incorrect chain.

It would be useful if geth accepted a blacklist of block hashes that the chain _must not_ have (or alternatively, a whitelist of block hashes that the chain _must_ have), with an argument such as as `--blacklist-blockhash`. Then clients could fast sync without worrying that they will end up on the incorrect chain.

**Comment by ryanschneider** [comment]
This should help with #17905 and #17906 as well.  The issue in 905 is that even if a node isn't fast-syncing it still gets it's `highestBlock` value from the bad chain, so being able to reject any chains w/ a blacklisted hash should prevent them from polluting that value as well.

**Comment by ryanschneider** [comment]
I'm trying out this idea with this very heavy-handed approach:

https://github.com/ryanschneider/go-ethereum/commit/8b5f0944fb12132cc02e076cf200c8b003def772

And it seems to be working, my peer count is low but I haven't seen any chain jumps.

Basically on connection I'm asking the peer for the block _after_ one of the known bad ones, and then checking the `.ParentHash` and rejecting any peers that give the blacklisted block.

Lots of bad ideas in that approach, but just wanted to see if it would help and signs point to yet.

**Comment by ryanschneider** [comment]
Oh ya, I like that idea.  Makes it dynamic and could protect against other scenarios too.

BTW I've been squashing commits onto that branch while I test, here's the latest commit: https://github.com/ryanschneider/go-ethereum/commit/2585a8feed5d78d99bcd30332c460645900782b2

**Comment by holiman** [comment]
@ryanschneider I think that's a good approach. Could you either add e..g. `StringSliceFlag` which takes e.g. `--blockhashwhitelist 123123=0xabcdefabcdefabcdeaf --blockhashwhitelist 123128=0xabcdefabcdefabcdeaf`, and make a PR, or, alternatively, make a PR of what you currently have and I will add the flag stuff.

**Comment by ryanschneider** [comment]
Will do.

**Comment by ryanschneider** [comment]
Sorry, got pulled into some other stuff yesterday, looking into this more now.  But, some questions:

- Shouldn't the flag be `--blockhashblacklist`, not whitelist?  
- Right now I have a very bad hack in there to skip making this test against the boot nodes, any idea how I can more cleanly determine that a peer is a boot node?

**Comment by holiman** [comment]
Well... I was thinking that it's easier to know where (what chain) you want to land on your fastsync, rather than where you don't want to land (in case there are several bad sidechains). Is there a case why blacklist is better?

Also, what's the problem with the bootnodes? As in, why are they exempted? Should we really sync with them if they're on a bad chain? Pure bootnodes (running the bootnode binary) doesn't even have anything to provide us.

**Comment by ryanschneider** [comment]
>  Is there a case why blacklist is better?

Nope, I agree.  I think I was just thrown off when you said "that's a good approach" since my current commit uses black lists, but ya I totally agree that a whitelist is strictly better.

IIRC, the reason I had to special case the boot nodes was that if I tried to do a `p.RequestHeadersByNumber` on a boot node the connect was dropped, so I ended up never getting any peers, but I need to double check that, as I said it was just a quick hack to get things working at the time.

So, to be clear, I think the strategy should be:

- build a `whitelistedBlocks map[uint64] common.Hash` based on the `--blockhashwhitelist` arg(s), separated by `=`.
- On peer connection, do a `p.RequestHeadersByNumber` for each whitelistedBlocks key.
- In `handleMsg`, if `filter` is true, if `headers[0].Number.Uint64()` is in whitelistedBlocks, compare `headers[0].Hash` with the value in whitelistedBlocks.  If they differ, return an error to reject the client.

Outstanding questions:
- There's possibly still some logic required around boot nodes, but I need to test that.  
- Currently it looks like light clients don't do the DAO fork check, should I add this new check for light clients too?  I feel like I should, but am not 100% sure.

I'm going to make a new branch for this work, I don't think there's much other than concepts I want to take from my existing commit. ;)

I'll make a WIP PR later today so we can continue the discussion around actual code.

**Comment by ryanschneider** [comment]
After thinking about it a bit, I think the `blockhashwhitelist` arg is an "Ethereum" option and not a networking/p2p one, so I'll put it in `eth.Config` (not in `p2p.Config`); it's almost a "chain-selector" on the network ID.

My rationale is in theory this option could be used for other non-p2p reasons as well (e.g. in the `import` command to verify that a chain being imported includes a specific block, not that I'm going to implement that, at least in this PR).

**Comment by ryanschneider** [comment]
Also hitting what appears to be a bug in `StringSliceFlag`, so looking into that now too.

**Comment by ryanschneider** [comment]
Weird, `ctx.GlobalStringSlice(BlockHashWhitelistsFlag.Name)` seems to return a `[]string` like this:

 `[]string{ "[4230605=0xc358b4fb016f7cc1402619f292c92a5e58a473ef5243db00d3c59b3b9b7cb827]"}` (with the `[` and `]` in the value).

But `ctx.StringSlice` (not Global) returns the correct value:

`[]string{ "4230605=0xc358b4fb016f7cc1402619f292c92a5e58a473ef5243db00d3c59b3b9b7cb827" }`

Strange.

**Comment by holiman** [comment]
This was fixed in https://github.com/ethereum/go-ethereum/pull/18028
