### ISSUE TITLE
Geth lost minned block 

### ISSUE THREAD

**Issue by korjavin** [ethereum/go-ethereum#17957]
#### System information

Geth version: `geth version`
Version: 1.8.16-stable
Git Commit: 477eb0933b9529f7deeccc233cc815fe34a8ea56
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.11
Operating System: linux
GOPATH=
GOROOT=/usr/local/go

OS & Version: Linux

#### Expected behavior
Block would be inserted into the blockchain

#### Actual behaviour
Block lost

### Description
Our Geth Node has received three blocks with same height 6542575 at the almost same time:
Block 1: https://etherscan.io/block/0x18577fc3293c8b996bf56fbb0c7467b012527a1be536cdf09522556a1229a38a
Block 2: https://etherscan.io/uncle/0xab48fc23d15059dd47876d272eda6c03b7a11acf14d3010ac0e4c021574f7213
Block 3: https://etherscan.io/uncle/0x1a4007f43763ca82bb692323a7b6ccfb965510537f6fd1457480285fbb0b19c6

The node chose the second block as mainchain, created a mining work and send to our pool engine. Our pool has found a solution for next block with #6542576 at Oct-19-2018 06:20:12 AM +UTC. However, Geth node hasn't been able to put this block into blockchain and eventually printed the message:
October 19th 2018, 06:21:42.267
INFO [10-19|06:21:42.267] 😱 block lost number=6542576 hash=38e035…2449ea

Valid mainchain block with height 6542576 has been submitted Oct-19-2018 06:20:14 AM +UTC, so we were faster. Why our block has been lost?

**Comment by rjl493456442** [comment]
@korjavin Hi, first for the main chain block selection, basically if two blocks have the same difficulty, each one has 50 percent chance to be selected. However for big mining pool, they prefer to select the block generated locally, so I think the reason for your block can due to 2 reasons: your block doesn't have enough luck OR during the reorg, the big mining pool selects their own block and mining the following works based on that.

And regarding the block lost, if the uncle doesn't be included in the following 7 rounds, it will finally lose the chance to be rewarded. so `block lost ...` log is printed. And also, the big mining pool will prefer to select the uncles generated locally. I think it should be a reason for your block lost. And another reason might be the network connection. It means your uncle might doesn't arrive to the big mining pool nodes.

**Comment by korjavin** [comment]
Speaking of this:
> However for big mining pool, they prefer to select the block generated locally

Do you mean they use own or patched geth version to choose which block to select?

**Comment by korjavin** [comment]
Well, so I should have this optimization as well, I use geth and I mined this block.

I know exactly that this block was propogated because I saw it in my others' geth nodes logs.

`
 October 19th 2018, 06:20:13.016INFO [10-19|06:20:13] Imported new chain segment               blocks=1  txs=31   mgas=1.045   elapsed=227.776ms mgasps=4.588   number=6542576 hash=38e035…2449ea cache=103.46mB
`
another one
`
October 19th 2018, 06:20:12.938INFO [10-19|06:20:12.938] Imported new chain segment               blocks=1  txs=31   mgas=1.045   elapsed=113.139ms mgasps=9.237   number=6542576 hash=38e035…2449ea cache=535.29mB
`

I am just trying to understand what exactly is mine problem that cost me this block.

**Comment by rjl493456442** [comment]
Sure thing you could specify the local account through `--txpool.locals`. All block mined by these accounts + etherbase will be regarded as the local block.

And regarding the propagation, I check the uncle inclusion for block 6542577, 6542578 and the following blocks, there is no uncle included or only 1 uncle. So I think your block wasn't propagated to other mining pools through the p2p network fast enough

**Comment by korjavin** [comment]
Am I right that if all my nodes mine for the same wallet I don't need `--txpool.locals` it's already considered like "local" ?

**Comment by rjl493456442** [comment]
Yes.

**Comment by korjavin** [comment]
Thus the only options that you can see it's poor p2p connectivity?
Usually I check that my nodes have about 120 connected peers.
Can you suggest something that I can improve? Geo-distribuition?
