### ISSUE TITLE
Problem in `p2p/peer.go` run method

### ISSUE THREAD

**Issue by AmirSoleimani** [ethereum/go-ethereum#17950]
Hi there,

**File: `p2p/peer.go`**

in `run()` method there are add `2` WaitGroup for `readLoop` and `pingLoop` ,  but when got an error in `readLoop(...) -> msg, err := p.rw.ReadMsg() ` and pass error to `errc chan` at end of the func, call `defer p.wg.Done()` and now we have `1` WaitGroup , but `errc chan` break loop , and after call `close(p.closed)` , `p.rw.close(reason)` never returned any thing in `run()` method because `WaitGroup` waiting for done `pingLoop` and `srv.delpeer` channel in `p2p/server.go` never called.

if peer closed, `pingLoop` call `p.closed` and now `WaitGroup` is done, but it's not mean `readLoop` WaitGroup is done.

Is this the problem I explained really happening?

Tnx.

```go
func (p *Peer) run() (remoteRequested bool, err error) {
	var (
		writeStart = make(chan struct{}, 1)
		writeErr   = make(chan error, 1)
		readErr    = make(chan error, 1)
		reason     DiscReason // sent to the peer
	)
	p.wg.Add(2)
	go p.readLoop(readErr)
	go p.pingLoop()

	// Start all protocol handlers.
	writeStart <- struct{}{}
	p.startProtocols(writeStart, writeErr)

	// Wait for an error or disconnect.
loop:
	for {
		select {
		case err = <-writeErr:
			// A write finished. Allow the next write to start if
			// there was no error.
			if err != nil {
				reason = DiscNetworkError
				break loop
			}
			writeStart <- struct{}{}
		case err = <-readErr:
			if r, ok := err.(DiscReason); ok {
				remoteRequested = true
				reason = r
			} else {
				reason = DiscNetworkError
			}
			break loop
		case err = <-p.protoErr:
			reason = discReasonForError(err)
			break loop
		case err = <-p.disc:
			reason = discReasonForError(err)
			break loop
		}
	}

	close(p.closed)
	p.rw.close(reason)
	p.wg.Wait()
	return remoteRequested, err
}

func (p *Peer) pingLoop() {
	ping := time.NewTimer(pingInterval)
	defer p.wg.Done()
	defer ping.Stop()
	for {
		select {
		case <-ping.C:
			if err := SendItems(p.rw, pingMsg); err != nil {
				p.protoErr <- err
				return
			}
			ping.Reset(pingInterval)
		case <-p.closed:
			return
		}
	}
}

func (p *Peer) readLoop(errc chan<- error) {
	defer p.wg.Done()
	for {
		msg, err := p.rw.ReadMsg()
		if err != nil {
			errc <- err
			return
		}
		msg.ReceivedAt = time.Now()
		if err = p.handle(msg); err != nil {
			errc <- err
			return
		}
	}
}```

**Comment by fjl** [comment]
The problem you are talking about cannot happen. When there is an error in `readLoop` the error is sent on the `readErr` channel. This exits the loop in `run` and closes `p.closed` channel. The `pingLoop` will exit because it waits on `p.closed`.

Both `pingLoop` and `readLoop` exit if the underlying connection is closed. This is because read/write operations are unblocked by closing the connection, returning an error.

If you have seen a hanging peer, please post the stack trace.

**Comment by blakehartin** [comment]
The same problem occurred on a non-Ethereum implementation and by adding logs, we were able to  verify the problem.

in readLoop(), the execution will get stuck in line "errc <- err"  because the receiver (in run() function) is not receiving any more because the for loop above exited in a different "select". This means that there is indefinite hang. 

https://github.com/ethereum/go-ethereum/issues/29857

**Comment by blakehartin** [comment]
> The same problem occurred on a non-Ethereum implementation and by adding logs, we were able to verify the problem.

in readLoop(), the execution will get stuck in line "errc <- err" because the receiver (in run() function) is not receiving any more because the for loop above exited in a different "select". This means that there is indefinite hang.

> The problem you are talking about cannot happen. When there is an error in `readLoop` the error is sent on the `readErr` channel. This exits the loop in `run` and closes `p.closed` channel. The `pingLoop` will exit because it waits on `p.closed`.
> 
> Both `pingLoop` and `readLoop` exit if the underlying connection is closed. This is because read/write operations are unblocked by closing the connection, returning an error.
> 
> If you have seen a hanging peer, please post the stack trace.

in readLoop(), the execution will get stuck in line "errc <- err" because the receiver (in run() function) is not receiving any more because the for loop above exited in a different "select". This means that there is indefinite hang.
