### ISSUE TITLE
Contract to test every opcode

### ISSUE THREAD

**Issue by adamschmideg** [ethereum/go-ethereum#18210]
When writing unit tests, we often have a need for an 'interesting' contract that covers many areas of EVM functionality. It would be nice to have a contract that runs almost every available opcode. This issue tracks writing such a contract and making its bytecode available as a string constant.

**Comment by mohanson** [comment]
I recently rewrote go-evm with [rust](https://github.com/mohanson/cita-vm/tree/interpreter/evm/src),  I am pleased to help you @fjl

**Comment by ChainSafe** [comment]
@fjl or @karalabe , just confirming that this is something that needs contribution towards before @noot and I start working on it.

**Comment by lhendre** [comment]
I am thinking of taking a look at this, would this be the appropriate list of the opcodes?  https://solidity.readthedocs.io/en/v0.4.24/assembly.html#opcodes . Additionally, where should it be made available as a string?

**Comment by lhendre** [comment]
also would we want to include the contract code somewhere so people can check and confirm what they are running?

**Comment by lhendre** [comment]
I have a base smart contract I am working with for this.  It is a work in progress and some questions came up.  
Some opcodes are only available for Constantinople-compatible VMs.  This will cause issues for people running  Byzantium, do you want to keep or remove those.  
I am not experienced with every op code and it has been awhile since I used assembly level code in depth, but some seem to require a functional notation and not non-functional, which seems to cause a problem with things like dup1.
Do we want the smart contract to have all of it in one call or do we want to break the testing up into several calls?

**Comment by lhendre** [comment]
I also based the tests around the unit tests for solidity

**Comment by lhendre** [comment]
I have added in more opcodes with unit tests to test them and now have over 75% of them covered, including the ones commented out due to the Byzantium issue.  I am going to wrap up the opcodes soon, my plan is to hold back on the ones causing issues and come back to them if needed.  When this is done, do we just want to have the bytecode string available in the documentation or something more in depth? @adamschmideg

**Comment by lhendre** [comment]
I have finished adding in OpCodes and have generated the byte code for this.  For the OpCodes, I left off things relating to the Byzantium issue and standalone assembly for the time being.  I created a separate javascript file to store the byte codes for now.  If that is okay, @adamschmideg how do you want to make the bytecode available as a string constant?  Do you have a preference?

**Comment by lhendre** [comment]
@fjl and @adamschmideg I have notifications on, so when you have thoughts let me know here or on the review.  If you are both busy getting a review on the PR would also be super helpful

**Comment by lhendre** [comment]
Circling back to see if there has been any update on this?

**Comment by adamschmideg** [comment]
Thank you for your patience. We'll discuss at in our next weekly PR session.

**Comment by lhendre** [comment]
No Problem, let me know how it went/goes

**Comment by lhendre** [comment]
When you get an update, let me know @adamschmideg , I have the byte code ready to go so I'll wait for a while and if I don't hear anything Ill check back in after some time has passed.

**Comment by GregTheGreek** [comment]
We have a program that does this if anyone is interested
