### ISSUE TITLE
Goerli Ethstats for Puppeth PoA

### ISSUE THREAD

**Issue by zulhfreelancer** [ethereum/go-ethereum#18228]
I found this [goerli/netstats-server](https://github.com/goerli/netstats-server) project and I think it's best fit for PoA mode in Puppeth.

According to Afri [here](https://twitter.com/5chdn/status/1069171822988537856), this version of ethstats does not display stats relevant for PoW only, such as hashrate, difficulty, or uncles.

So, I'm putting this here. Hopefully we can have two different versions of ethstats; tailored to which consensus algorithm we choose.

**Comment by karalabe** [comment]
I'm a bit torn on this. The issue is that @5chdn did some awesome changes, many of which are relevant for the ethash version too. Now we have again a fragmented codebase, because if I include the Görli one into puppeth, it will behave slightly differently than the ethash one, not just the changes functionality (e.g. updated libraries). Would be nice to have a single thing being maintained and compatible with both, perhaps via some config switch.

A further complication is that https://aleth.io/ has been working on a brand new version of the stats server, so might as well be worth it to wait for that to arrive and get thm to make a generic one supporting both poa as well as pow.

**Comment by 5chdn** [comment]
>  Now we have again a fragmented codebase

Not anymore! I managed to make the same code-base support both dashboards, the PoA/Testnet version and the PoW/Mainnet version: https://github.com/goerli/ethstats-server

See readme for screenshots and details.

**Comment by 5chdn** [comment]
- PoW Demo: https://ropsten-stats.parity.io/
- PoA Demo: https://kovan-stats.parity.io/

**Comment by 5chdn** [comment]
Ok, I think I'm an "expert" on this now lol.

The goerli version of the ethstats servers come with a lot of security fixes but also with some heavy bugs introduced, unfortunately. So I would not advise to use this version unless someone has time to actually debug all the new issues.

The alethio netstats are only free in the "light" version which is not comparable to the status dashboard which is currently included in puppeth.

However, I recently discovered that POA Network has a complete rewrite available for the backend, coming with the same frontend:

- https://github.com/poanetwork/poa-netstats-warehouse
- https://github.com/poanetwork/poa-netstats-agent

I haven't tried that but might be worth investigating.

**Comment by karalabe** [comment]
Thanks for sharing these infos. @rjl493456442 was already working on integrating BlockScout into puppeth, so maybe we can tackle the stats server afterwards. That said, stats although rudimentary, seems to work well-ish, s it's not a high priority.

**Comment by adamschmideg** [comment]
Seems to be no interest in this issue in a year now
