### ISSUE TITLE
Internal transactions

### ISSUE THREAD

**Issue by MarcoGuarducci** [ethereum/go-ethereum#18236]
Because  tracetransaction is too slow and consumes too much CPU it is not suitable for a massive use as for example the development of an explorer. That's why I developed simple optional changes to geth to store internal transactions in the leveldb database when they are generated by the virtual machine and i like to contribute to geth project pushing it.
Thanks.

**Comment by mitsukomegumi** [comment]
Would you care to summarize your findings and why exactly you feel it would be viable to apply said "optimal changes" to geth? Doesn't really seem like there are many complaints regarding CPU usage at the moment, but I'd love to hear your take on it.

**Comment by AyushyaChitransh** [comment]
@dowlandaiello I can also vote for CPU issues when querying internalTransactions. 

But I never raised any issues for this, as I expected tracing internal transaction to be a CPU intensive process as all transactions of a block are replayed when a single transaction of that block is traced.

Having an option to store internal transaction inside the db will help with CPU issues.

**Comment by holiman** [comment]
Storing internal transactions to leveldb is not something we'd want to include by default, since it will blow up disk requirements. Geth is not primarily aimed at specialized targets like block explorers, who indeed have different requirements and hardware budgets. This issue is not really a bug report, so I'll close this.
