### ISSUE TITLE
Dump config to a file

### ISSUE THREAD

**Issue by adamschmideg** [ethereum/go-ethereum#18279]
If a file is specified, dump it to the file. Otherwise, dump it to stdout. See #16383

**Comment by karalabe** [comment]
Our current workflow was that we print to stdout, and the user can pipe it into a file. Windows PowerShell apparently screwes up the encoding when piping, so the idea is for `dumpconfig` to accept an optional argument - a file name - into which we can dump explicitly ourselves instead of stdout.

So we could do `geth dumpconfig` as previously, but also `geth dumpconfig somefile.conf`.

**Comment by karalabe** [comment]
Done!
