### ISSUE TITLE
ropsten chain not syncing .

### ISSUE THREAD

**Issue by alishaagupta** [ethereum/go-ethereum#18378]
I started syncing my ethereum ropsten chain using geth 3 days ago in fast mode.

eth.syncing shows false , but the difference between highest block shown by my node and the one shown at ropsten blockexplorers is around 50k .
tried adding peers 
I tried deleting the chain completely and redownloading it , still facing the same issue.

**Comment by holiman** [comment]
It's most likely a case of 

1. Difficulty in finding good peers to get the info from, 
2. Bad network? 
3. Bad network at the other peer(s) side. 

Can't really say anything since there are no logs provided. For the next time you file a ticket, please try to add as much related information as possible, otherwise it's hard for us to figure anything out.
