### ISSUE TITLE
Equivalent of `parity_removeTransaction` in geth?

### ISSUE THREAD

**Issue by miguelmota** [ethereum/go-ethereum#18389]
Is there an equivalent method to [parity_removeTransaction](https://github.com/paritytech/wiki/blob/master/JSONRPC-parity-module.md#parity_removetransaction) in geth to remove local transactions?

**Comment by karalabe** [comment]
Well, Geth does not support scheduled transactions, meaning that if you have an online node, anything you create gets immediately propagated to the network. As such, there's little point to support removals, since the network already has it. 

Perhaps there's some use case I'm missing though? Why would you like to have such a functionality?

**Comment by miguelmota** [comment]
An example use case would be to filter out certain transactions before broadcasting them. This would be for a custom privatized geth chain. Removing transactions from a local queue of scheduled transactions would be the other use case like you mentioned

Thanks for the answer. Closing issue since it is not supported
