### ISSUE TITLE
clique_getSigners doesn't return as expected

### ISSUE THREAD

**Issue by jaredwillard12** [ethereum/go-ethereum#18411]
Running a private test network.
Trying to get the signers returned.
run: 
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"clique_getSigners","params":["latest"], "id":1}' http://127.0.0.1:8502

#### System information

Geth version: 1.9.0-unstable
OS & Version: Linux

#### Expected behaviour

returns:
{'id': 1, 'result': ['0x...',...], 'jsonrpc':'2.0'}

#### Actual behaviour

{"jsonrpc":"2.0","id":1,"error":{"code":-32601,"message":"The method clique_getSigners does not exist/is not available"}}

Notes: 
-Other methods, such as eth_getTransactionReceipt, do return expected data
-In the geth console I can run 'clique.getSigners()' and the method returns as expected

Thanks!

**Comment by jmank88** [comment]
This API is not exposed over JSONRPC. I am coincidentally working on adding it to [our fork](https://github.com/gochain-io/gochain/issues/333) right now, so I would be happy to prepare a PR for geth as well, since we'd prefer to remain 100% compatible anyways. Is this something the team would be open to? What about `clique_getSnapshot`?

**Comment by jmank88** [comment]
The `clique` API is not public by default. You can add it via the `rpcapi` flag, or the `HTTPModules` config field.

**Comment by ligi** [comment]
@jaredwillard12 please reopen when you still face problems after doing what @jmank88 suggested. @jmank88 thanks fo jumping in so fast!
