### ISSUE TITLE
Transaction receipt not available even after syncing successfully mined block

### ISSUE THREAD

**Issue by AyushyaChitransh** [ethereum/go-ethereum#18448]
Fetching receipt from the RPC returns null for some transaction hashes. After encountering two instances of this issue withing 2 days, this has been reported here.

#### System information

Geth version: Geth/v1.8.20-stable/linux-amd64/go1.10.3
OS & Version: Linux

#### Expected behaviour
Receipts of all hashes contained in block should be available.

#### Actual behaviour
Fetching receipt from the RPC returns null for all transaction hashes for some blocks.

#### Steps to reproduce the behaviour
This seems to be a random behaviour which occurs for some transactions in block. This behaviour can be reproduced by continuously verifying receipts in latest blocks.

Update: Not some receipts, all receipts are missing for some blocks.

**Comment by xiaods** [comment]
@AyushyaChitransh ok. i can give you some steps to overcome the issue.
1、because the v1.8.20 is old and will outdate in Feb, 2019, could you please upgrade it node finally.
2、cloud you please can give some your use case to me, maybe a example case to query missing block. maybe a curl query rpc api use case welcome.

**Comment by AyushyaChitransh** [comment]
Closing this issue because it has been resolved by other means. I am now using multiple RPCs so if receipt is not available by one, other provides it.
