### ISSUE TITLE
CI has been broken for a long time

### ISSUE THREAD

**Issue by pkieltyka** [ethereum/go-ethereum#18499]
can someone fix the CI config and get the build flag passing? I'm surprised to see this unresolved and every PR showing failed tests for so long

I'm happy to take a pass on it as well, some feedback on https://github.com/ethereum/go-ethereum/blob/master/.travis.yml

1. can we remove the cocoapods / azure builds from travis? https://github.com/ethereum/go-ethereum/blob/master/.travis.yml#L174-L201 -- why are these here?
2. can we remove the android builds? https://github.com/ethereum/go-ethereum/blob/master/.travis.yml#L136-L172

my thought is its better to have the tests passing for common targets like linux/osx systems and have travis working, and move the ios/android/other travis stuff to another branch/PR to merge once that is ready to be maintained properly, as well, when its actually relevant. I can't imagine anyone running geth on ios/android (unless its the ethrpc stuff) as the system requirements to run an actual node are extreme at the moment

**Comment by karalabe** [comment]
CI for PPA broke because Travis added NAT traversals and broke FTP. It was fixed in the v1.8.23 release.

CI for Android is broken because Travis screwed around with some other firewall stuff, but we haven't yet found what or how to work around it. Keeping it red motivates us to find it eventually instead of ignoring it.

CI for Android broke because upstream Go syscall package pushed a commit that made it unbuildable on non-linux arm64. We signaled it last week and it was fixed. CI is green on CocoaPods again.

---

Whilst it's unfeasible to run a full ethereum node on mobile, it should be feasible to run a light client. We need that. Also shipping mobile libraries permits interacting with contracts even through infura or other remote servers, so they are still beneficial.
