### ISSUE TITLE
Trie state not periodically flushed reliably.

### ISSUE THREAD

**Issue by ksedgwic** [ethereum/go-ethereum#18521]
#### System information
Geth version: 1.8.21-stable
OS & Version: Linux, Debian GNU/Linux 9

#### Expected behaviour
After running (synchronized) for a long period of time and being abruptly terminated we expect upon restart to quickly re-synchronize.

#### Actual behaviour
Upon restart the node appears to restart synchronization from a very early point in time, when it had previously reached synchronization.

#### Steps to reproduce the behaviour
1. Run the node synchronized for a period of time.
2. Abruptly kill the node (kill -9 or system crash).
3. Restart the node, observe where it resynchronizes from.

**Comment by holiman** [comment]
It does flush the state trie periodically, IIRC it's after an hours worth of block processing time. If we estimate block processing time to `200ms`, that means the default settings will flush every 18K blocks or so. That can be modified via the `TrieTimeLimit`, which I could've sworn was configurable via either command line options or toml. 

@karalabe did we not make that configurable?

**Comment by holiman** [comment]
I think it's `trieTimeout` in the toml file, but not configurable via command line switch. It's a `time.Duration`, which I think means it can be set using a time expression, such as `1m` for one minute

**Comment by MysticRyuujin** [comment]
This is also probably related to my ask for a way to force a flush. Like if I know I'm about to reboot my node or upgrade it, it would be nice...

I just stopped my node via `supervisor stop geth` so that I could upgrade to the latest version and lost 10k blocks.

I did a little more digging, Supervisor sends `TERM` and has a default timeout of 10 seconds. I'm guessing that timeout is just too low. So I can probably fix MY issue but it would be cool for this to be more configurable / accessible.

**Comment by hackmod** [comment]
See also https://github.com/ethereum/go-ethereum/pull/18035

**Comment by holiman** [comment]
I'm closing this; works as expected. 
It deliberately does not flush more than the once every couple of hours, to increase in-memory pruning efficiency, reduce disk usage size and disk IO.


A graceful shutdown correctly flushes to disk, whereas 'abruptly' killing the node causes memory content to disappear. I don't see how geth could behave differently.
