### ISSUE TITLE
Transaction disappeared

### ISSUE THREAD

**Issue by koeppelmann** [ethereum/go-ethereum#1878]
We discovered a strange behaviour of a transaction. The transaction was created from our groupgnosis dapp and submitted via a remote geth node. Then for a moment the result was visible in our DAPP (that requires actual change on the blockchain). But then it disappeared. With further investigation fe found that the transaction is listed in this blockexplorer:  

http://frontier.ether.camp/transaction/40b66c576c879b

but this returns null:

``eth.getTransactionReceipt("40b66c576c879b7c82d9f9ec0cca2401fb1f8034fc591e40e533edd954d7276e")``

**Comment by obscuren** [comment]
The block the transaction is in was in a (natural occurring) fork. Your transaction didn't make it in to the chain. 

Updated version of `geth` actually re-add missing transactions due to forks, unfortunately it all depends on miners to update their version for this feature to take (noticeable) effect.

Best just re-submit your transaction.
