### ISSUE TITLE
Feature Request: Expose ECIES to API

### ISSUE THREAD

**Issue by MariusVanDerWijden** [ethereum/go-ethereum#19073]
Parity has it and Geth should have it to, their own exposed ECIES interface. 
https://wiki.parity.io/JSONRPC-parity-module.html#parity_encryptmessage
Geth already has the technical capabilities to implement something like this. 

This is especially useful to provide Dapp-developers with a simple way to encrypt data using public keys.

#### Expected behaviour
Ability to encrypt and decrypt messages with ECIES

#### Actual behaviour
nonexistent

**Comment by karalabe** [comment]
We're currently working on an external signer (and in general removing accounts from Geth) called Clef. I'm not sure exactly which capabilities it has, but I think someone already requested that we support RSA signatures and/or DH handshakes or something. Either way, I think it's a valid request and can probably be incorporated into that work.

@holiman ?

**Comment by holiman** [comment]
It is not a super-great fit for clef, since

a) It doesn't require a private key, so nothing to do with account management, 
b) It requires the message-to-encrypt to go over the external API, which is considered untrusted, and the message would wind up in e..g audit logs. 

However, it _could_ be part of the protected (internal) API between `clef` and the `ui`. But that makes it less usable, since a dapp wouldn't be able to invoke it -- so that would not work for this usecase. 

I'm not really sure where this belongs, tbh. If a message needs to be encrypted, it probably shouldn't be exposed to the dapp in the first place. 

@MariusVanDerWijden do you have a more concrete example of a dapp which would use this?

**Comment by MariusVanDerWijden** [comment]
I thought of End-to-End encryption of data in a DApp. And I think there should be a standardized way how to do this. I would rather not have dapps handle Encryption/Decryption themselves. 
I think there was already a proposol to standardize this

**Comment by holiman** [comment]
We've decided to close this. Implementing a backend which provides "encrypt this secret message for me" encourages Dapps in general to just hand off the secrets to whatever backend is running. Which may be infura or whatever. And that totally gives away the confidentiality. 

We _could_ add decryption into clef though, that would totally make sense.

**Comment by anjmao** [comment]
Hi @holiman @MariusVanDerWijden. Can you elaborate more on what do you mean by `encrypt this secret message for me` ? We have a case there I send encrypted data to server which cannot be trusted. The whole purpose of end to end encryption is not to trust any server and dapps should do that.

As a workaround we exported private key to json, imported it again to derive ecies keys, but this requires a lot more memory. Ideally keystore could have two more methods Encrypt, Decrypt as it already contains expanded private key. 

Would you consider reopening this?

**Comment by karalabe** [comment]
The confusion is probably due to how Geth works now vs. what the long term plans are. Currently Geth is a swiss army knife that does everything. As the ecosystem matures however, you want to separate network gateways (Geth, Parity, etc) from account management (Clef, Metamask, etc). 

From a security standpoint, it's better to have accounts not linked to nodes; and from a composability standpoint too as you could switch between using a local node, a shared node, or even Infura and have the same functionality.

From this perspective, putting such an RPC API into Geth itself reinforces the tight coupling between accounts and networking, instead of loosening it.

**Comment by anjmao** [comment]
@karalabe Thanks, you are right. I just missed a point that this proposal is for RPC api. In our case we are use go-ethereum as a library for our dApp.
