### ISSUE TITLE
eth_getTransactionCount does not include pending transactions when 'pending' qualifier  given for a deployed contract

### ISSUE THREAD

**Issue by angelosuinan** [ethereum/go-ethereum#19103]
Hi!

Similar issue with [https://github.com/ethereum/go-ethereum/issues/2880](https://github.com/ethereum/go-ethereum/issues/2880) but in this issue I want to get the transaction count of a deployed contract.

eth_getTransactionCount does not include pending transactions when 'pending' qualifier is given for a deployed contract

`web3.eth.getTransactionCount(myDeployedContract, "pending");`

For example my contract, named as `ContractCreator`, has a createContract function that when executed will deploy another contract. In order to determine what is the address that been deployed by the `ContractCreator`. I will use ethereumjs-util [generateAddress](https://github.com/ethereumjs/ethereumjs-util/blob/master/docs/README.md#const-generateaddress) function

`ethereumjs-util.generateAddress(ContractCreatorAddress, transactionCount)`

#### System information

Geth and OS version: `Geth/v1.8.22-omnibus-260f7fbd/linux-amd64/go1.11.1` using a public node ropsten.infura.io
#### Expected behaviour

Return the transactionCount including pending transaction

#### Actual behaviour
```
> let contractCreatorAddress = "0x123..."
> web3.eth.getTransactionCount(contractCreatorAddress, "pending");
215
> web3.eth.sendTransaction({to: contractCreatorAddress, data: "<a-function-that-deploys-another-contract>" })

> web3.eth.getTransactionCount(contractCreatorAddress, "pending");
215 (should be 216)
```

**Comment by karalabe** [comment]
This is an interesting corner case (ping @fjl @holiman). A while ago we changes the pending nonce API to return the nonce from the txpool, not from the pending state. The reason is that the pending state just contains a few txs (that fit in the next block) vs. the txpool contains all the txs. However, the txpool obviously cannot figure out the nonce of a contract, since it doesn't execute code.

The issue with your use case is that the only way to accurately return the pending nonce of a contract is to execute all the transactions. With thousands of txs queued up, that's not feasible. I think the practical answer is that you should try to not depend on pending contract state, as it's unreliable.

**Comment by holiman** [comment]
> I think the practical answer is that you should try to not depend on pending contract state, as it's unreliable. 

I agree.

**Comment by angelosuinan** [comment]
@karalabe Is this the pull request #15794 you are talking about, that changes the pending nonce API from the pending state to the txpool.

**Comment by karalabe** [comment]
@angelosuinan yes

**Comment by karalabe** [comment]
Unfortunately we cannot fix this issue. Retrieving pending contract state is not meaningfully possible, since it would entail executing all the transactions in the pool (20 blocks' worth).
