### ISSUE TITLE
IP address cache of lost peers should be cleared periodically

### ISSUE THREAD

**Issue by hdiedrich** [ethereum/go-ethereum#1915]
IP addresses of peers that are lost should maybe be forgotten faster than seems to be the case now.

Most people working on private networks will first connect to the public network to learn. This makes their nodes' IP addresses known and remembered by nodes in the public network, which will in turn try to re-integrate 'lost nodes' forever (?) and cause constant traffic even when those nodes have moved on to form a private network, connecting to the now-private nodes, only to disconnect as soon as a new, private network id is detected.

**Comment by Gustav-Simonsson** [comment]
![borgfirstcontact](https://cloud.githubusercontent.com/assets/293096/10582532/a309a4d2-7688-11e5-8511-40b1edb169cf.jpg)

**Comment by hdiedrich** [comment]
Actually they should be cleared from the cache when the find, upon connecting, that it's the wrong network number.

**Comment by karalabe** [comment]
The networking protocol is built up of multiple layers, a UDP discovery protocol is responsible for finding useful peers, a P2P data protocol is responsible for interconnecting peers for general data transfer, and arbitrarily many subprotocols are responsible for application specifics (e.g. ethereum, swarm, whisper, etc).

However, the notion of `network id` is present only at the Ethereum application sub-protocol level. When two nodes find each other, connect, negotiate the encryption etc, they don't even know what application protocols each of them speak, let alone figure out that those are incompatible for some reason. Furthermore, the fact that one such app protocol isn't compatible shouldn't mean that other compatible ones shouldn't be able to talk to each other. So in its current incarnation, we cannot really take the network id into consideration during connection setups.

Still, @fjl is working on spicing up the discovery protocol so that it would be a bit smarter about how it locates and advertises peers, allowing peers to hone in on others with similar capabilities, without having to randomly/blindly try all known nodes until good ones are discovered. Though I don't think this granularity would be supported, given that the `network id` would still remain the specific of a single sup-protocol. Provided that eventually more and more P2P protocols could leverage the Ethereum network, it would be a premature optimization to try and save a few connection attempts by leaking the sub-protocol details into the main overlay network.

Maybe this discussion could be picked up again after some of those capability changes reach the main codebase so we could see what direction to take this. Until then however, I don't think a quick solution to this issue will be done.

**Comment by zelig** [comment]
as for swarm this is a non-issue
