### ISSUE TITLE
Geth 1.8.23-stable taking too long to sync

### ISSUE THREAD

**Issue by redserpent7** [ethereum/go-ethereum#19167]
Geth version: 1.8.23-stable
OS & Version: Ubuntu 18.04.1 LTS

Its taking too long for Geth to sync. for over 12 hours now there is always around 100 blocks difference between the current and highest block values when I check the sync status. 

This is the current result I am getting:

```
 eth.syncing
{
  currentBlock: 7269091,
  highestBlock: 7269212,
  knownStates: 211067633,
  pulledStates: 211041909,
  startingBlock: 0
}
```

this is how I'm running Geth:
`geth --rpcapi eth,web3,personal,utils,net,miner --rpc --syncmode "fast" --port 30304 --rpcport 8545 --rpcaddr "0.0.0.0"`

The node is hosted on an AWS EC2 instance, I first started with a c5.xlarge instance which has 4 vCPUs and 8GB of RAM. Then I retired that instance and opted for c5.2xlarge with 8 vCPUs and 16GB of RAM hoping it might speed things up, even though I'm running a fast sync. Alas, its still syncing and I'm not sure what to do.

I have other ethereum nodes with  Geth 1.8.22-stable running and those have no issues running on an c5.xlarge instance.

Anyone having the same issue? Shall I just wait? it never took that long for me to sync before and its making me nervous moving forward. Note that there are no errors in the output and no reports of sync issues whatsoever.

**Comment by karalabe** [comment]
Syncing Ethereum is a pain point for many people, so I'll try to detail what's happening behind the scenes so there might be a bit less confusion.

The current default mode of sync for Geth is called fast sync. Instead of starting from the genesis block and reprocessing all the transactions that ever occurred (which could take weeks), fast sync downloads the blocks, and only verifies the associated proof-of-works. Downloading all the blocks is a straightforward and fast procedure and will relatively quickly reassemble the entire chain.

Many people falsely assume that because they have the blocks, they are in sync. Unfortunately this is not the case, since no transaction was executed, so we do not have any account state available (ie. balances, nonces, smart contract code and data). These need to be downloaded separately and cross checked with the latest blocks. This phase is called the state trie download and it actually runs concurrently with the block downloads; alas it take a lot longer nowadays than downloading the blocks.

So, what's the state trie? In the Ethereum mainnet, there are a [ton of accounts already](https://etherscan.io/chart/address), which track the balance, nonce, etc of each user/contract. The accounts themselves are however insufficient to run a node, they need to be cryptographically linked to each block so that nodes can actually verify that the account's are not tampered with. This cryptographic linking is done by creating a tree data structure above the accounts, each level aggregating the layer below it into an ever smaller layer, until you reach the single root. This gigantic data structure containing all the accounts and the intermediate cryptographic proofs is called the state trie.

Ok, so why does this pose a problem? This trie data structure is an intricate interlink of hundreds of millions of tiny cryptographic proofs (trie nodes). To truly have a synchronized node, you need to download all the account data, as well as all the tiny cryptographic proofs to verify that noone in the network is trying to cheat you. This itself is already a crazy number of data items. The part where it gets even messier is that this data is constantly morphing: at every block (15s), about 1000 nodes are deleted from this trie and about 2000 new ones are added. This means your node needs to synchronize a dataset that is changing 200 times per second. The worst part is that while you are synchronizing, the network is moving forward, and state that you begun to download might disappear while you're downloading, so your node needs to constantly follow the network while trying to gather all the recent data. But until you actually do gather all the data, your local node is not usable since it cannot cryptographically prove anything about any accounts.

If you see that you are 64 blocks behind mainnet, you aren't yet synchronized, not even close. You are just done with the block download phase and still running the state downloads. You can see this yourself via the seemingly endless `Imported state entries [...]` stream of logs. You'll need to wait that out too before your node comes truly online.

---

**Q: The node just hangs on importing state enties?!**

A: The node doesn't hang, it just doesn't know how large the state trie is in advance so it keeps on going and going and going until it discovers and downloads the entire thing.

The reason is that a block in Ethereum only contains the state root, a single hash of the root node. When the node begins synchronizing, it knows about exactly 1 node and tries to download it. That node, can refer up to 16 new nodes, so in the next step, we'll know about 16 new nodes and try to download those. As we go along the download, most of the nodes will reference new ones that we didn't know about until then. This is why you might be tempted to think it's stuck on the same numbers. It is not, rather it's discovering and downloading the trie as it goes along.

**Q: I'm stuck at 64 blocks behind mainnet?!**

A: As explained above, you are not stuck, just finished with the block download phase, waiting for the state download phase to complete too. This latter phase nowadays take a lot longer than just getting the blocks.

**Q: Why does downloading the state take so long, I have good bandwidth?**

A: State sync is mostly limited by disk IO, not bandwidth.

The state trie in Ethereum contains hundreds of millions of nodes, most of which take the form of a single hash referencing up to 16 other hashes. This is a horrible way to store data on a disk, because there's almost no structure in it, just random numbers referencing even more random numbers. This makes any underlying database weep, as it cannot optimize storing and looking up the data in any meaningful way.

Not only is storing the data very suboptimal, but due to the 200 modification / second and pruning of past data, we cannot even download it is a properly pre-processed way to make it import faster without the underlying database shuffling it around too much. The end result is that even a fast sync nowadays incurs a huge disk IO cost, which is too much for a mechanical hard drive.

**Q: Wait, so I can't run a full node on an HDD?**

A: Unfortunately not. Doing a fast sync on an HDD will take more time than you're willing to wait with the current data schema. Even if you do wait it out, an HDD will not be able to keep up with the read/write requirements of transaction processing on mainnet.

You however should be able to run a light client on an HDD with minimal impact on system resources. If you wish to run a full node however, an SSD is your only option.

**Comment by redserpent7** [comment]
Sorry but this is not what I was looking for. As stated I have been spinning new ethereum nodes hosted on AWS EC2s for as long as I remember and never did it take that much time to sync.

I started a new node  with Geth 1.8.22-stable and it took around 8 hours to sync.


1.8.23 is taking much longer, its been 18 hours now and still syncing.

**Comment by redserpent7** [comment]
@karalabe There's definitely something wrong with the new client.. Its been 36 Hours now since I started and its still playing catch-up. I started another instance yesterday and that is also still syncing for close to 20 hours.

**Comment by redserpent7** [comment]
@karalabe Well it took 4+ days to sync.... in case anyone was wondering....

**Comment by h6dworker** [comment]
Two days later
There was an error on this issue
It will not be synchronized after that
"Database compacting, degraded performance database=/var/lib/ethereum/geth/chaindata"
(1.8.23-stable-c9427004)

**Comment by DrewCoin669** [comment]
https://github.com/ethereum/go-ethereum/issues/19167#issuecomment-470821942

**Comment by protocollapse** [comment]
It has been a month for me and I am still playing catch up, I am still behind for about an average of 70 to 100 blocks. @redserpent7 What measures did you do to be able to get fully synced? Thanks in advance!

**Comment by 362228416** [comment]
me too，3 days,, It's always going to be 60-200 blocks behind

now: 

{
  currentBlock: 7391500,
  highestBlock: 7391588,
  knownStates: 156383035,
  pulledStates: 156375331,
  startingBlock: 7384104
}

**Comment by rlinxy** [comment]
same here, has been sycning for more than 3 days, still several blocks behind
