### ISSUE TITLE
eth_getblockbynumber should return null for pending blocks

### ISSUE THREAD

**Issue by gagarin55** [ethereum/go-ethereum#19332]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: Geth/v1.8.22-omnibus-260f7fbd/linux-amd64/go1.11.1

#### Expected behaviour
According to [documentation](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getblockbynumber) I expect that `eth_getBlockByNumber` returns `number == null` for pending
block

#### Actual behaviour
`eth_getBlockByNumber('pending')` returns not null in block.number field

#### Steps to reproduce the behaviour
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["pending", true],"id":1}' https://mainnet.infura.io/
```

**Comment by holiman** [comment]
My thoughts:

- Setting the block number to `null` does not make sense, since we do know the number  of the pending block. How does parity do? cc @sorpaas
- Setting `hash, miner, mixhash` to `null` does make sense (geth already does)
- Currently, in the transactions returned within the `pending` block, the `blockHash` is _not_ `null`:ed in geth. Which is quirky, and does not make sense to me.

**Comment by fjl** [comment]
Fixing this is trivial, just add `"number"` here: https://github.com/ethereum/go-ethereum/blob/2ca89ea47902adcc0f7dab40e897c23265740fd7/internal/ethapi/api.go#L628

**Comment by princesinha19** [comment]
@holiman I think we should return **null** for the pending block. Parity also returns null for the pending block. See this issue (https://github.com/paritytech/parity-ethereum/issues/8703).
