### ISSUE TITLE
Possible memory leak when "traceChain"

### ISSUE THREAD

**Issue by felberj** [ethereum/go-ethereum#19375]
#### System information

Geth version: v1.8.21)
OS & Version: OSX
Commit hash : 9dc5d1a915ac0e0bd8429d6ac41df50eec91de5f *WITH* dba336e6121578c001fde7f17c28454d1c1867bf cherry-picked

#### Expected behaviour

Memory goes down when "traceChain" finishes.

#### Actual behaviour

If I trace the chain, the memory steadily increases (and never decreases after stopping the "traceChain" RPC.

#### Steps to reproduce the behaviour

Have a blockchain synced in "full"+"archive" mode until block 2331366 or so.

`git checkout v1.8.21 `
`git cherry-pick dba336e6121578c001fde7f17c28454d1c1867bf`
`go build ./cmd/geth`
`./geth --mine=false --datadir=$YOUR_DATA_DIR --syncmode=full --gcmode=archive --maxpeers 0 console`

another terminal:

`nc -U /Volumes/ethereum/geth.ipc`

Then paste
```
{"id": 1, "method": "debug_subscribe", "params": ["traceChain", "0x1e8480", "0x22132a", {"tracer": "{\r\narguments: [],\r\nstep: function(log, db) {if (false) {\r\n this.arguments.push({x: log.stack.peek(1).toString(16), y: log.stack.peek(2).toString(16)})\r\n}\r\n},\r\nresult: function(){ return this.arguments;}, \r\nfault: function(){}\r\n}\r\n", "reexec":0}]}
```

And let it run for a while. The memory increases steadily.
You can close the "nc" socket and the memory will stay the same.

#### Backtrace

Not sure whether this helps:

[heap.txt](https://github.com/ethereum/go-ethereum/files/3034418/heap.txt)

I took a heap snapshot after running the query for a short time (2 min).

I assume it has something to do with this: https://github.com/ethereum/go-ethereum/blob/master/eth/api_tracer.go#L298-L316

Unfortunately, I do not know what this  "Reset", "Commit" is doing (and I am also not sure why we need to refrence and dereference).

Also,  does `// TODO(karalabe): Do we need the preimages? Won't they accumulate too much?` has something to do with it?

I am happy to help and to fix this if you can point me to the right places and answer the questions above. I am especially curious about @karalabe 's TODO.

**Comment by karalabe** [comment]
Go's GC releases memory only after it has't been used for quite a few minutes (5 I think). Does it go down after 5-10 minutes, or doe it stay high?

Also, starting with Go 1.12, on Linux Go uses memory **hints** to tell the OS that it **can** take some memory back, but it will only take it back if needed, otherwise the memory bloat will stay in there.

**Comment by felberj** [comment]
IIRC it stood high. I "solved" this problem by tracing 10'000 blocks at the time and then the next 10'000.

**Comment by karalabe** [comment]
Chain tracing subscription is mostly meant for full nodes where the state is not available. Internally it starts at the given starting block and keeps generating and keeping the new state in memory as it is progressing. It will not check if the disk is available on disk. This means that if you run very long traces, eventually memory use will pile up quite a bit.

Since you have an archive node, you don't need to actually keep everything in memory, that's why it actually worked with 10K chunks. For archive nodes it might make sense to trace blocks individually, not via chain tracing subscriptions.
