### ISSUE TITLE
EIP-1898: allow default block parameter to be blockHash

### ISSUE THREAD

**Issue by charles-cooper** [ethereum/go-ethereum#19394]
In the following JSON-RPC calls, allow the default block parameter to be a block hash per https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1898.md:

- `eth_getBalance`
- `eth_getStorageAt`
- `eth_getTransactionCount`
- `eth_getCode`
- `eth_call`
- `eth_getProof`

This allows clients to unambiguously specify which block they are querying. Wondering if this is feasible to implement or if any changes to the spec need to be made?

**Comment by holiman** [comment]
Although it would be kind of simple to implement this (simply interpret it as hash if it looks like a hash), there's a more subtle problem that the EIP needs to specify. 

- If the hash `h` is not a canonical block, but instead a sidechain block, then we may actually have the block, but not necessarily the state for the block. 

That is a problem we don't have for `number` or `latest`, since those are implicitly canon blocks. So, the possible ways to handle the situation above is: 

- Return the data (balance/code) if we have the state,  but return zeroes if we don't 
- Return the data if we have the state, but return error if we don't 
- Always return an error if the hash is not canon

**Comment by charles-cooper** [comment]
Good point!
> * Return the data if we have the state, but return error if we don't

I think this option is best. Do you have strong opinions either way? If not, I will go ahead and update the EIP.

**Comment by ryanschneider** [comment]
Great to see there's already an EIP going forward since I independently started building this yesterday
in https://github.com/ethereum/go-ethereum/pull/19459. :) 

In my implementation I just assumed that a block number is always less than MAX_UINT64 and a hash was greater, but I like the approach of the EIP w/ a new optional block parameter.

And if that's the case, then there's no reason why the param can't be:

```json
{
  "blockHash": "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3",
  "canonical": true 
}
```

Which is to say the user can specify whether they require canonical blocks or not, meaning the only thing left for us to decide is which one is the default. :)

**Comment by charles-cooper** [comment]
That's a neat solution (although I think the field should be named `require_canonical` :) ).

I think the default value for `require_canonical` should be false. In the use case of, do a bunch of eth_call/eth_getBalance or whatever, it is better to be able to do all the calls and then a final extra RPC call to check the block is still canonical than to potentially error out in the middle of the transaction (only to have that block get reorged back in!). It steers the client developer towards writing more robust code. Also it appears we both arrived at this conclusion independently as that's the one you chose in your PR so that is extra evidence that we should go with that :)

**Comment by ryanschneider** [comment]
Although to be fair I only chose it in my PR as the default because it’s
the default behavior inside geth’s API. :). I actually haven’t looked up
how to tell if a block is canonical or not, but assume it’s easy enough to
do so.

I think it would be `requireCanonical` as camelCase seems to be the pattern
for arguments, (e.g. in LogFilter).

Hey what if we combined your EIP with
https://github.com/ethereum/go-ethereum/pull/18346, since there’s issue
with backwards compatibility in that issue, we could make it only return an
error if the block number is specified as a JSON object `{blockNumber:
0x78654321}` but keep the old client behavior if just passed as a raw
QUANTITY?

**Comment by ryanschneider** [comment]
Actually, how about these options for the block parameter:

- `QUANTITY` block number
- `HASH` (32 byte DATA) block hash (either canonical or non-)
- `TAG` either `latest`, `earliest`, or `pending`
- `OBJECT` one of:
  - `{ "blockNumber": QUANTITY or TAG }` same as root-level QUANTITY or TAG except that block numbers greater than HEAD return an error ala #18346.
  - `{ "blockHash": HASH }` block by hash, either canonical or non-.
  - `{"canonicalHash": HASH }` block by hash, returns an error if block is non-canonical.

**Comment by holiman** [comment]
What's really the case that one would want to do operations on a non-canon block? I mean personally I might do it for exploration, but I'd expect most callers would rather fail asap if the block is not canon.

**Comment by ryanschneider** [comment]
As Charles mentioned, it's more so a multi-RPC "transaction" can complete w/o error if there's a reorg between two calls.  Likewise if you have multiple nodes in a High Availability configuration, it's ideal that both nodes can answer RPCs about a block even if on one node it's canonical and on the other it's not.

Also, it provides parity with `eth_getBlockByHash` which returns both canonical and non-canonical blocks (or at least Uncle blocks).  

I could go either way on if canonical is default or not, but definitely think it should be possible, and I defer to Charles' opinion that making it the default is optimal as my experience is less w/ building DApps or Exchanges and more with low-level Ethereum infrastructure.

**Comment by charles-cooper** [comment]
> we could make it only return an
error if the block number is specified as a JSON object `{blockNumber:
0x78654321}` but keep the old client behavior if just passed as a raw
QUANTITY?

Going to have to shoot this one down. That's going to be really difficult for client developers to predict and I would rather have backwards compatibility broken once than insert this bomb into the spec.

> HASH (32 byte DATA) block hash (either canonical or non-)

I think it's better to use a tagged approach than having the node guess what the client means?

> What's really the case that one would want to do operations on a non-canon block? I mean personally I might do it for exploration, but I'd expect most callers would rather fail asap if the block is not canon.

The case I can think of is that a block gets reorged out and then reorged back in. Generally I think if a client asks for a specific block hash and the block is available, the data should be returned. Then the onus is of course on the client to make sure it's canonical or not, but this way of doing it is more forgiving in the presence of race conditions.

Perhaps I should make a `discussions-to` for this EIP?

**Comment by charles-cooper** [comment]
> Also, it provides parity with eth_getBlockByHash which returns both canonical and non-canonical blocks (or at least Uncle blocks).

This is also a good point. I believe `eth_getLogs` also works the same way, so returning data for non-canonical blocks would make the behavior the same across all RPCs which allow blockHash.

Personally my workflow is usually to poll for new blocks, and then for all new blocks grab all the info I want associated with that block (logs, code, balances, call results etc) and put it into a cache. Since the info associated with that block is immutable, handling reorgs is just a matter of updating a pointer. This separates the concerns of grabbing data and deciding what to do about data. From the point of view of this cache, you want data for blocks you have been told about to be available whether it's canonical or not because the logic for dealing with canonical vs non-canonical data is somewhere else.

And sometimes you really do want to have that non-canonical data around; for instance, an application which takes a preliminary action (e.g., placing a funds hold) when a block is mined and takes another action when the application thinks the block has enough confirmations (e.g., releasing funds). Even if the block is non-canonical, you might not want to rollback that preliminary action until the application thinks that there are enough confirmations that it is very unlikely to be reorged back in.

**Comment by holiman** [comment]
> Generally I think if a client asks for a specific block hash and the block is available, the data should be returned. Then the onus is of course on the client to make sure it's canonical or not, but this way of doing it is more forgiving in the presence of race conditions.

Is it really more forgiving? If I need to do a sequence of `M` calls to get the data I want out, and while doing so, my block suddenly becomes a sideblock. If geth just processes the rest of the transactions as usual, my results will be consistent, but useless. 

Wouldn't it be better if call `N` instead failed, so I can start over from step one and do it from the canon block instead? 

But I see your point too, just want to make sure we're not committing to an API that has undesirable quirks.

**Comment by charles-cooper** [comment]
@holiman I think having the `requireCanonical` parameter covers both use cases. I suppose we could debate the tradeoffs of which behavior to default to all day, but for consistency I think the tiebreaker is to follow other RPCs which get block by hash. I believe the behavior is currently unspecified but in practice is to allow the block to be non-canonical (and I suppose the reasoning for that is that if the user asks for a specific block hash they really mean it!).

**Comment by holiman** [comment]
We can close this now that #19491 is merged, I believe
