### ISSUE TITLE
--genesis doesn't work with ~

### ISSUE THREAD

**Issue by ethers** [ethereum/go-ethereum#1944]
Version: 1.3.0-dev
Git Commit: 57ab1473887b4eaeac2ec6912e3d738d4839b48a

`--genesis=~/genesis.json` doesn't work (datadir does work with ~)

**Comment by obscuren** [comment]
Omit the `=` sign

**Comment by karalabe** [comment]
Just to expand a bit on this: `~` is expanded by bash into your home folder. However, for bash to do it's expansion, it must be the first character of a word, otherwise bash assumes it's a literal. So if you don't use `=`, bash will correctly expand it, but otherwise will believe it's a middle character of whatever string so it will leave it as is (bash has no notion of `--var=val` constructs, it's a single string to it, split up by the invoked command internally).

e.g.

```
$ echo ~
/home/karalabe
$ echo =~
=~
```

Will close this as it's not something we can fix (apart from manually expanding `~` ourselves, but that's crossing over to bash territory, which we don't want to do).
