### ISSUE TITLE
Exceeding txpool.globalslots means further transactions will not be processed

### ISSUE THREAD

**Issue by jmcnevin** [ethereum/go-ethereum#19458]
#### System information

Geth version: 1.8.26
OS & Version: Linux

#### Expected behaviour

Not sure what the expected behavior is here.

#### Actual behaviour

In load testing a private network, we are submitting a few thousand transactions through a node, exceeding its "txpool.globalslots" setting that we have configured at 8192.  Any transactions that are submitted to the node after exceeding that number seem to go nowhere, even after the network has worked through the other pending transactions.

<img width="968" alt="Screen Shot 2019-04-12 at 12 57 41 PM" src="https://user-images.githubusercontent.com/12859/56056743-a4671100-5d22-11e9-8c50-554cb0557f35.png">

After restarting the node, the network will work through the next 8192 transactions, and then  work stops again.

**Comment by holiman** [comment]
A node keeps track of which transactions it has already sent to it's peers, to avoid re-sending transactions all the time. However, if the remote node simply discards the transaction(s) (due to too overflowing the slots), the result will be that the origin node believes the peer already have the transactions. 

When you restart the origin node, it forgets about what txs what peers have, and resends them. 

This is expected (although non-ideal) behaviour. If you have suggestions about how to make this better (without causing total transaction churning over mainnet), please chime in.
