### ISSUE TITLE
Geth full sync so slow

### ISSUE THREAD

**Issue by MiaZmy1221** [ethereum/go-ethereum#19486]
Hi there,

When I sync the blockchain with full sync mode, it will always be very slow at some points, such as block number 440000 and 1700000. At those two points, the sync speed is so slow that only one block needs several minutes. Plus, I am sure that I do the sync on SSD, rather than HDD.

#### System information
geth version: 1.9.0-unstable
os: linux
commit hash: 0b4fe8d1929ad64ed576f7560dde4179d71ecfcb

**Comment by MiaZmy1221** [comment]
Thank you for your help!

**Comment by MiaZmy1221** [comment]
My command is "geth --syncmode full --cache 8096"

**Comment by MiaZmy1221** [comment]
Do you think will the geth version occur the slow sync?

**Comment by karalabe** [comment]
What does slow mean? Any logs? It's expected that above 4-5M range, blocks take between 100-200ms.

**Comment by MiaZmy1221** [comment]
![image](https://user-images.githubusercontent.com/44105172/56589100-98950d80-65b2-11e9-979c-8d932ba80c71.png)

**Comment by MiaZmy1221** [comment]
This is a node that I run on the AMS EC2 instance with 32 CPUs, 900 SSD, compute optimized c5d.9xlarge.

**Comment by MiaZmy1221** [comment]
![image](https://user-images.githubusercontent.com/44105172/56589389-1f49ea80-65b3-11e9-9b3d-95cbd58665ea.png)
Another node that I run on my owener server with 1.9T SSD, 12 CPUs.

**Comment by MiaZmy1221** [comment]
![image](https://user-images.githubusercontent.com/44105172/56597753-1eb85080-65c1-11e9-84bc-1e4ab5005c4b.png)

**Comment by karalabe** [comment]
Whoah, those numbers are extremely insane. Are you sure you're running on an SSD? If you do an `iotop` on the machine while Geth is running, what values do you see? We can easily saturate 300+MB/s writes on our `i3.2xlarge` instances.

**Comment by holiman** [comment]
I agree, that's orders of magnitude off what it should be. Some ideas:

- Check what geth reports as datadir in the beginning, 
- Check `df -h` to see mounts
- Check `sudo fdisk --list`  for more disk info

You can also check the raw disk speeds with 
```
dd if=/dev/zero of=/tmp/output conv=fdatasync bs=384k count=1k; rm -f /tmp/output
```
^ where you replace `/tmp/output` with a location on the same drive as the datadir

**Comment by AusIV** [comment]
I might have some insight into the high block processing times, particularly pertaining to AWS.

If you are starting from an AWS Snapshot, rather than an empty volume, then the data in your snapshot isn't actually on your local volume until it's read once. Instead, it's stored in S3 and retrieved on demand, then written to the EBS volume for future use, which leads to very high latencies on read (overall throughput is fine for big reads, but latencies are very high). I've found that when I launch a new node from a snapshot of an existing node, initially I'll see 2-3 minute block processing time, and as more of the state trie gets pulled in block processing times speed up until I'm caught up.

Something that I've found to be a huge help is to launch the volume as a provisioned IOPS volume, and once I'm in sync with the network modify the volume to be a gp2 volume. This costs maybe $0.50 in IOPS, and I'm able to catch up with the network in minutes instead of hours from a reasonably fresh snapshot.

**Comment by karalabe** [comment]
Closing as not enough information and OP disappeared.

**Comment by shargon** [comment]
It's unable to sync, extremely slow...

**Comment by holiman** [comment]
@sylr 

1. This is a very old ticket, which is also closed, 
2. The ticket is also about "full sync", in this context meaning `syncmode=full`. Which is not the same as what you're doing, 
3. You did provide logs, which is good, but we're missing the version number on you geth-node

So it's better if you open a new ticket and provide version information and exact startup command , rather than comment on a closed one with a different problem.
