### ISSUE TITLE
Make puppeth use release branches, not latest

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#19675]
Not sure it's enough, btw, just trying to work around the issue that an old puppeth tries (and will fail) to launch very new versions of Geth.

**Comment by rjl493456442** [comment]
A few things can be improved. 
Currently, we use the old version docker images for some components. For example the wallet since the code hasn't been updated for more than 1 year.
We need to somehow update the docker images automatically. Otherwise, different components can use different geth, which causes a hard-fork.

**Comment by PyrateAkananto** [comment]
I think puppeth should use all other binaries in the exact same version of itself. I manually and intentionally downloaded the stable version of "geth & tools 1.9.6" and afterwards puppeth installed an unstable version of geth 1.9.7 - which is not what I wanted.

**Comment by holiman** [comment]
`puppeth` is removed as of https://github.com/ethereum/go-ethereum/pull/26581. Closing puppeth-related tickets.
