### ISSUE TITLE
Can not apply transactions with incremented nonce when NoPrefetch=false

### ISSUE THREAD

**Issue by ramilexe** [ethereum/go-ethereum#19723]
When I was working on PR #19721 found a bug with `NoPrefetch` parameter in config:

Without `NoPrefetch: true` (line 188)

https://github.com/ethereum/go-ethereum/blob/cc479b88406ea89bf21ef3afd98e1fe8d774e197/ethclient/ethclient_test.go#L187-L192

When I try to add 2 consecutive transactions with nonce 0 and 1 (line 240 and 247):

https://github.com/ethereum/go-ethereum/blob/cc479b88406ea89bf21ef3afd98e1fe8d774e197/ethclient/ethclient_test.go#L234-L254

I get error `nonce too high` on line 172:

https://github.com/ethereum/go-ethereum/blob/cc479b88406ea89bf21ef3afd98e1fe8d774e197/core/state_transition.go#L167-L178

I think it related to #19328 

/cc @karalabe @holiman

**Comment by holiman** [comment]
I guess it doesn't make sense to have `prefetch=true` on tests that do not actually process blocks properly, but it would be good to have @karalabe check that there isn't some deeper issue here.

**Comment by karalabe** [comment]
This is an odd one. Prefetching should run the **next** block in advance, which in this case will genuinely fail... but that failure should never bubble up outside, since we're only doing it to pre-load data, we don't actually keep the execution result.

@ramilexe Do you actually hit an error, or are you just pondering about what's happening under the hood?
