### ISSUE TITLE
IO or Memory error on Raspberry Pi

### ISSUE THREAD

**Issue by SebastianBoyd** [ethereum/go-ethereum#1977]
When attempting mining on a testnet using the following command:
```
geth --rpc --networkid=39318 --datadir=~/.ethereum/DevChain/ --mine --minerthreads=4 --genesis genesis.json --etherbase='19dfb667ebf40e39f85401055523313af534c4df' console
```
I get an IO or Memory error. I don't know if this is a bug or I just don't have enough memory. I am using the pi2 with 1gb of ram.
Here is the full error text:
http://pastebin.com/L13kadEX

**Comment by karalabe** [comment]
Hey Sebastian,

  In order to mine, your node needs to generate the full DAG, which is over 1 GB in size, so unless you have significantly more than that (I think during DAG generation it can use up to 4GB RAM), you won't be able to mine. Similarly though, an RPI won't be able to do much, as the network's hashrate is equivalent to literally millions (if not billions) of RPIs :)

**Comment by SebastianBoyd** [comment]
How much ram does it take once generation is complete?  And I know the raspberry pi is not powerful enough to mine competitively, I just want an always on server for my testnet.
