### ISSUE TITLE
 A transaction cost a huge fee

### ISSUE THREAD

**Issue by qinheqing** [ethereum/go-ethereum#19782]
This is an abnormal transaction detected. I want to know if this is a bug in the program or a possible vulnerability in the go-ethereum?

[Transaction Hash:](https://etherscan.io/tx/0x988563efaf6f69bea348cb08e0a1cbd8bcc61367531470624948d689dbc8c057)
0x988563efaf6f69bea348cb08e0a1cbd8bcc61367531470624948d689dbc8c057
![image](https://user-images.githubusercontent.com/23715137/60493512-871d5f80-9cdf-11e9-8fe1-295d20415ac6.png)

[0x2fce7cee1f7b2445a31f5dc6b62cdee43aac0652](https://etherscan.io/txs?a=0x2fce7cee1f7b2445a31f5dc6b62cdee43aac0652&p=3)
This address receives a lot of similar transactions like that

Can I ask how to avoid such like this problem?

**Comment by karalabe** [comment]
Without knowing which client, service or script created that transaction, it's hard to say who's at fault. All clients can create transactions, but so do many Dapps create their own transactions, MyCrypto/MEW, etc.

As for Geth, if the user requests to send a transaction via Geth (and does not explicitly specify a gas limit), we use the median cost of the last 50 or so blocks to pick the price. This way it should be impossible to send outlier transactions via Geth.

We also have a sanity limit of [500 GWei](https://github.com/ethereum/go-ethereum/blob/master/eth/gasprice/gasprice.go#L32) as a max price we're willing to return to the user, specifically to avoid any bugs causing insane fees.

* If you are sending transactions rarely, I'd recommend setting the gas price manually based on https://ethgasstation.info/, because you always know better than Geth how fast or cheap you want it.
* If you are sending many transactions in an automated way, it could make sense to have your script/program set the gas price.

All in all, automatic gas pricing is mostly a convenience feature that you should preferably not rely on, at least not blindly. It's good for quick testnet scripts, but on mainnet I'd feel better to have stricter control over the price.
