### ISSUE TITLE
Fast syncing taking a long time on Raspberry Pi v1

### ISSUE THREAD

**Issue by paulmorriss** [ethereum/go-ethereum#1978]
Following this conversation on Reddit: https://www.reddit.com/r/ethereum/comments/3rcakv/geth_release_131/cwmtqr2 here are some of the logs from my Raspberry Pi model B when it's trying to do fast syncing. After 5 days it's only on block #150000. I've put some of the lines that show it rolling back headers in a gist. https://gist.github.com/paulmorriss/9b3f5f38aff4ad43ac14

(The â€¦ characters are an ellipsis.)

**Comment by karalabe** [comment]
Thanks for opening the issue here too.

Could you perhaps save a log with the `--vmodule=downloader=6` CLI flag set, and perhaps another one (will be huge) with `--verbosity=6`?

The issue I see from your log snippets is that the sync gets interrupted quite often, which causes frequent restarts. I am not entirely sure about the cause of the interrupts though. One possibility is if you have limited bandwidth and the downloader manages to saturate it too much. How much do you have available approximately?

Another thing that may or may not interfere is that the RPI isn't too powerful and the CPU may be saturated too much by keeping many connections active and also processing inbound connection requests. You could try lowering your `--maxpeers` to maybe 10. Another flag I introduced specifically for the RPI to limit the concurrent handshakes was removed a while ago by @fjl in favor of some fancier mechanism that however wasn't implemented until now. Any details about it or ETA (@fjl)?

**Comment by paulmorriss** [comment]
I have 50Mb, so bandwidth shouldn't be a problem. The lan light on the Pi is flashing away quite a lot, so it may be that the CPU is saturated. Anyway, I renamed the blockchain directory so it started again (as I was getting errors on the output - I can give more details if necessary).

I'm using `--vmodule=downloader=6` and maxpeers at 10, verbosity 4. I've got messages about importing headers and receipts, but also repeatedly "synchronisation already in progress". There is only one geth instance running. Shall I ignore those errors? eth.syncing.currentblock keeps on going up, so it's making progress.

**Comment by karalabe** [comment]
The sync already in progress is just a debug log that fires when the node sees something new but then figures that another thread is already pulling data so it won't start a second download procedure.

**Comment by paulmorriss** [comment]
After 24 hours it's on block 402257, with no rollbacks. There were 20 "no peers" errors. So I guess restricting the number of peers prevents it being too busy to process blocks.

**Comment by paulmorriss** [comment]
And after 50 hours its synced, and can keep up with the new blocks.

**Comment by obscuren** [comment]
Considering this closed.
