### ISSUE TITLE
Full sync (catchup) should keep pulling headers until the sync completes

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#19811]
The downloader was written in a way to download anything available, and them import it. If the chain moved ahead in between, we'd just repeat this again. While this works well for lighter blocks, with mainnet this second cycle can take 10 mins after a long range sync. The issue is that we start accepting transactions after the first cycle, which puts a whole lot of extra burden on the node before finishing catchup.

We should apply the same trick that we do during fast sync for full sync too, where we block and periodically keep pulling headers until there's nothing left to import. Only then should we complete the sync cycle. This will reduce the number of sync cycles as well as avoid this txpool issue.

**Comment by rjl493456442** [comment]
I am thinking about whether it's worthwhile to introduce this complexity. 
We have another trick: in order to protect mini reorg during the syncing, if the height of the last header we receive - current head height > 48, then we will discard some head headers.

So it means for full sync if the blockchain is not that close to head(e.g. chain is still importing 8K blocks), then headers fetching will continue(for most of the normal case).

**Comment by MariusVanDerWijden** [comment]
@karalabe Is this still relevant?
