### ISSUE TITLE
solidity : Contract creation initialization returns data with length of more than 24576 bytes. The deployment will likely fails. 

### ISSUE THREAD

**Issue by ying2025** [ethereum/go-ethereum#19912]
Contract creation initialization returns data with length of more than 24576 bytes. The deployment will likely fails. 
I I have a lot more code to write, but it alreay more than  24576 bytes.What should I do ?

**Comment by karalabe** [comment]
The Ethereum yellow paper specs contracts as having at most 24576 bytes. There's no way to deploy a contract that's larger. You'll need to split it up into smaller pieces if you must have such large code. You might want to go ti https://ethereum.stackexchange.com/ for more infos, I'd guess a lot more people can help you there with this.

**Comment by jzySaber1996** [comment]
Hello, we're investigating the issue reports in security. Since our automatic tool has observed that this issue may relate to a potential vulnerability (maybe it is not a reproducible issue, but our tool cannot check it. If so, please let us know), has it been disclosed in CVE already? Hope to receive your reply.
