### ISSUE TITLE
geth-V1.9.0 always occurs "replacement transaction underpriced" use eth_sendTransaction without a given nonce,  but not occur v1.8.0 or previous

### ISSUE THREAD

**Issue by shangmacun** [ethereum/go-ethereum#19984]
when batch send txs in  geth-V1.9.0 always occurs "replacement transaction underpriced" use eth_sendTransaction without a given nonce, but not occur v1.8.0 or previous

**Comment by holiman** [comment]
How do you 'batch send' ? There's no built-in functionality for that, so it all depends on how it's done. My guess is you rely on geth to provide nonce, and doing that erroneously leads to problems, since geth will answer with the next nonce based on what's already in the tx pool, and may thus supply the same nonce to two separate transactions, causing them to be 'same', and thus one being seen as replacement.
