### ISSUE TITLE
geth-V1.9.0 always occurs "replacement transaction underpriced"  use eth_sendTransaction

### ISSUE THREAD

**Issue by shangmacun** [ethereum/go-ethereum#19981]
WARN [08-18|11:43:07.683] Served eth_sendTransaction               conn=192.168.11.113:44272 reqid=2053901133 t=26.94454ms   err="replacement transaction underpriced"
WARN [08-18|11:43:09.335] Served eth_sendTransaction               conn=192.168.11.113:44272 reqid=301692500  t=14.545678ms  err="replacement transaction underpriced"
WARN [08-18|11:43:11.207] Served eth_sendTransaction               conn=192.168.11.113:44272 reqid=636253687  t=16.023956ms  err="replacement transaction underpriced"
WARN [08-18|11:43:13.235] Served eth_sendTransaction               conn=192.168.11.113:44272 reqid=446280682  t=12.370873ms  err="replacement transaction underpriced"
WARN [08-18|11:43:14.742] Served eth_sendTransaction               conn=192.168.11.113:44272 reqid=1965518095 t=5.369055ms   err="replacement transaction underpriced"

**Comment by karalabe** [comment]
If you've already sent a transaction with a given nonce, Geth will only accept a replacement if it's gas price is 10% more than the previous one. This is a SPAM protection measure, since all transactions need to propagate across the network. By requiring a bump in price, nodes avoid junk being shuffled in the network.

**Comment by shangmacun** [comment]
I sent a transaction without a given nonce, but V1.9.0 always occurs "replacement transaction underpriced" use eth_sendTransaction, V1.8.0 is OK
