### ISSUE TITLE
personal.newAccount should be rejected over HTTP RPC endpoints

### ISSUE THREAD

**Issue by axic** [ethereum/go-ethereum#20000]
#### System information

Geth version: `master`
OS & Version: OSX
Commit hash : 961aa0533f75027bc5bc80f994adb80d14635553

#### Expected behaviour

`personal.newAccount` is rejected when issued over an HTTP (and potentially HTTPS?) RPC connection.

#### Actual behaviour

`personal.newAccount` succeeds without any warning.

Interestingly, `personal.unlockAccount` is rejected with the message `account unlock with HTTP access is forbidden` even if issued over an IPC connect **IF** the node has HTTP RPC exposed to the public.

**Comment by holiman** [comment]
So, let me explain a bit of the background why `personal.unlock` is forbidden. 

- If an account `A` is unlocked, _anyone_ who has access to the `eth` namespace through the RPC port can send transactions from `A`. Therefore, whenever `http rpc` is enabled, we disable unlocking capabilities, regardless of whether the actual unlock happens through CLI-flags/IPC RPC/whatever. 

That same reasoning does not apply to `newAccount`, though. I would say there are two sensitive things here: 

1. An attacker might see the password traverse the network. 
2. An attacker might create new accounts, spuriously on the victim (which is not really an issue -- he would also need the actual keystore, not just the password in order to take any funds from them).

With regards to the first item, I agree that it's bad to send passwords over http, both for the reason mentioned but also because it prevents us from keeping an audit log of the RPC traffic. 

Clef does not permit such things -- but the question is if we should change how geth works at this time? I'm guessing many prod systems cannot use IPC across machines, and thus are left to HTTP which they have to secure by themselves in their local networks. If we disallow this, then I'm thinking we need geth to be able to handle https properly.
