### ISSUE TITLE
Implement JSON-RPC error codes

### ISSUE THREAD

**Issue by adamschmideg** [ethereum/go-ethereum#20117]
As per [EIPs/eip-1474.md at master · ethereum/EIPs](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1474.md). For details see [this PR discussion](https://github.com/ethereum/EIPs/pull/1474)

**Comment by hjlee9182** [comment]
Are you want to add -32005 error in docs?

**Comment by jacklightChen** [comment]
try to add -32006 ^_^

**Comment by johnson73A** [comment]
Gjjgdjnk @jacklightChen

**Comment by MariusVanDerWijden** [comment]
We're currently trying to create a new standard for the JSON-RPC api which would also include better error codes, the progress of it can be found here: https://github.com/ethereum-oasis/eth1.x-JSON-RPC-API-standard/issues
Once we have a good api, we can start to implement this, until then this issue is on hold

**Comment by duongxuantuan154** [comment]
Duplicate of #

**Comment by duongxuantuan154** [comment]
> Theo [EIPs / eip-1474.md tại master · ethereum / EIPs](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1474.md) . Để biết chi tiết, hãy xem [thảo luận PR này](https://github.com/ethereum/EIPs/pull/1474)

**Comment by lhendre** [comment]
@MariusVanDerWijden Checked the link and nothing has been updated in awhile, is this still needed?

**Comment by MariusVanDerWijden** [comment]
This issue? not really, but more json-rpc error codes should be standardized (we've added more in the engine api)
