### ISSUE TITLE
dumpconfig doesn't work

### ISSUE THREAD

**Issue by gumb0** [ethereum/go-ethereum#20127]
`dumpconfig` option doesn't work for me on the latest `master`

```
> geth dumpconfig
INFO [09-25|16:55:11.812] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [09-25|16:55:11.814] Maximum peer count                       ETH=50 LES=0 total=50
INFO [09-25|16:55:11.814] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
toml: cannot marshal nil *params.TrustedCheckpoint

```

#### System information

Geth version: `1.9.6-unstable-0568e817-20190925`
OS & Version: Linux

**Comment by ligi** [comment]
sounds LES related - pinging @rjl493456442 @zsfelfoldi

**Comment by rjl493456442** [comment]
@gumb0, In theory, this issue is already be fixed in the master. I just try the master and it works for me.  I have the hunch that the binary you used is not the lastest one.

For example the `Bumping default cache on mainnet ` log shouldn't occur in `geth dumpconfig` command. Can you double-check the binary version?

**Comment by gumb0** [comment]
@rjl493456442 You're right, that was the wrong binary, sorry for the confusion
