### ISSUE TITLE
[trie/proof.go] VerifyProof doesn't check node hash

### ISSUE THREAD

**Issue by guiguan** [ethereum/go-ethereum#20158]
It looks like the `VerifyProof` implementation doesn't re-hash the node loaded from `proofDb` and compare the hash with the wanted one. This could be a security vulnerability because the `proofDb` could be easily tampered with false Merkle paths, and the `VerifyProof` still succeeds. Is there any reason why we don't do the re-hashing?

**Comment by guiguan** [comment]
Hmm, probably you assume the proof is an array of RLP encoded nodes instead of KV store? So before calling `VerifyProof`, the process of converting the array to the KV store is already verifying that.

**Comment by karalabe** [comment]
Yes, I also made this "mistake" during a refactor. VerifyProof indeed does not check that the keys are actually the hashes, but that's because we receive only the content from the network and actually hash it and construct this prootDb out of it. So the proofDb does not com directly from the network, rather is constructed locally via hashing.

Perhaps the API is a it lame and could use some work to make this cleaner/clearer. Maybe we should not pass the proofDb as an argument, rather construct it locally. That would avoid confusion. Although I'm assuming there was a reason why it's not like that in the first place. Should check it out closer.

**Comment by guiguan** [comment]
@karalabe Thanks for the clarification. Yes, it would be better if we could mention this in the VerifyProof document. I will close this issue for now.
