### ISSUE TITLE
Freezer is failed to freeze data

### ISSUE THREAD

**Issue by rjl493456442** [ethereum/go-ethereum#20239]
Sometimes we can have such error log shown `Block receipts missing, can't freeze`.

**Comment by holiman** [comment]
```
 ERROR[11-04|12:35:13.845] Block receipts missing, can't freeze     number=1202001 hash=c4d847…799422 
```

Relevant block:

**Comment by rjl493456442** [comment]
@holiman but even the receipt is nil, the RLP encoded value is [192] which represents an empty list.

So freeze shouldn't fail on empty receipt case.

**Comment by veox** [comment]
FTR, I'm only seeing this on Goerli.

**Comment by rjl493456442** [comment]
@veox Are you using the Geth after #20287?

**Comment by veox** [comment]
I'm using `v1.9.11`, but the message has been appearing long before PR #20287 was merged.

I've cleared the DB now (except ancient), will get back here if it re-surfaces.

**Comment by rjl493456442** [comment]
@veox appreciate it!

**Comment by rjl493456442** [comment]
Seems the issue still exists in my recent running

```
ERROR[03-24|09:54:10.028] Block receipts missing, can't freeze     number=2298468 hash=2d2501…de9728
```

**Comment by crsmith75** [comment]
@rjl493456442  Was having the same error, wiped the database except for ancient, updated geth on my machine, then resynced and appears to be working now

**Comment by veox** [comment]
Can confirm @rjl493456442's findings, issue re-surfaced with v1.9.12.

**Comment by amplicity** [comment]
I'm having the same issue:

 Error in block freeze operation   err="block receipts missing, can't freeze block 17373890"

I'm running a mainnet validator, so I'm a little wary of trying the `debug.setHead` command / enabling debug on my node. I tried using `geth removedb` and removed both ancient and regular db, however, it didn't seem to actually remove the db. I assume this is because my ethereum chaindata may be in a custom directory (linux, `ethereum/execution/data/geth/chaindata`).

Am I safe to delete my `chaindata` directory, and restart geth to resolve this issue?

Also, from what I can gather, this issue is not detrimental to consensus/validator?
