### ISSUE TITLE
network is hangout at `Ancient blocks frozen already`

### ISSUE THREAD

**Issue by hadv** [ethereum/go-ethereum#20286]
chain is stop working when freezer happen

#### System information

Geth version: `1.9.6 stable`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour

chain should continue working even freezer happen 

#### Actual behaviour

chain is stop working at a specific blocknumber

#### Backtrace

````
DEBUG[11-14|03:35:15.155] Ancient blocks frozen already            number=641028 hash=9ac845…b71f22 frozen=551028
````

**Comment by rjl493456442** [comment]
Actually it's the expected behavior. You can see it's a debug level log.

So the mechanism of freezer is: whenever there are some blocks are stable enough, freezer will move these blocks from "Live database" (leveldb) into "Ancient database"(flatten file). So that freezer will have an endless loop to check the stable block every minute. If `HEAD` - `Block.number` > 90,000. Then it's migrated.

However there is a special case => Fast Sync

In the fast sync, we will write "stable" chain data into "Ancient database" directly. Basically all blocks below the checkpoint are regarded as stable. 

So it can happen that after syncing, the block with number `HEAD` - `90,000` is already migrated. So we print this debug log that we don't need to anything now.

**Comment by hadv** [comment]
Thank @rjl493456442 for your detail explanation. By the way, still don't understand why the all the validators with fast-sync stop working after freezing. I need to investigate more.

**Comment by ligi** [comment]
Can this issue be closed then?

**Comment by rjl493456442** [comment]
@hadv No idea. But I think it's not relevant to this issue. So I will just close it and you can open another one with some logs.
