### ISSUE TITLE
failed to initialize libusb: libusb: unknown error [code -99]

### ISSUE THREAD

**Issue by ankita-p17** [ethereum/go-ethereum#20416]
Hi,

#### System information

Geth version: 1.9.8 (geth-linux-amd64-1.9.8-d62e9b28)
OS & Version: Linux

#### Expected behaviour
Geth should start syncing

#### Actual behaviour
Geth started and give error : 

INFO [12-02|10:13:18.189] Initialized fast sync bloom              items=12356 errorrate=0.000 elapsed=461.460ms

ERROR[12-02|10:13:18.632] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=3 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[12-02|10:13:18.632] Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=3 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[12-02|10:13:18.632] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=3 err="failed to initialize libusb: libusb: unknown error [code -99]"

**Comment by ligi** [comment]
Please provide some more information. E.g. what linux you use. Also do you actively use the TREZOR integration?

**Comment by gballet** [comment]
@ankita-p17 This occurs because you are running this in a VM or any specific device that doesn't have a USB controller. `libusb` will therefore fail to initialize, as it needs one.

This is unrelated to your sync issue, which can take a while to start. If it doesn't, you should check your network config and if you think this is correct, then please open a new issue with your network configuration. This issue will be closed as the warning itself is a problem in `libusb` on VMs, that we have no control over.
