### ISSUE TITLE
The logic of findAncestor is not correct and effective

### ISSUE THREAD

**Issue by Nanyan** [ethereum/go-ethereum#20456]
Hi there,

I found that the logic of `findAncestor` in eth/downloader/downloader.go may be incorrect and(or) inefficient.

#### Source

Geth version: branch `master`, up to latest commit [f51cf57](https://github.com/ethereum/go-ethereum/commit/f51cf573b5c602914d22f5a31c58378c5aa17ffd)

#### Description

Think about a bundle of numbers from testcase: 
```go
func TestRemoteHeaderRequestSpan(t *testing.T) {
	testCases := []struct {
		remoteHeight uint64
		localHeight  uint64
		expected     []int
	}{
		// Remote is way higher. We should ask for the remote head and go backwards
		{1500, 1000,
			[]int{1323, 1339, 1355, 1371, 1387, 1403, 1419, 1435, 1451, 1467, 1483, 1499},
		},
......
```

Then, since the `localHeight` is `1000`, then how can the blocks `1323`,`1339`,... be exist in the local chain? 

It's impossible for the block `1323` or `1339` etc. be a common ancestor of the local chain and the remote chain.

**Comment by holiman** [comment]
It's actually neither incorrect nor inefficient, but rather incorrectly named. 
What the downloader does is not find the common ancestor, but tries to find the latest block that is also available locally. 

 This changed after a testnet screwup; in the presence of very long (but invalid) sidechains, this is what happened: 

1. Downloader peers with remote peer on bad chain. Self at `N`, other at `M`.  Common ancestor `n`.
2. Downloader detects that peer has longer chain. Downloads blocks `n+1` up to `M`. 
3. Blockchain crunches through blocks, detects that `n+k` is a bad block. Rejects it all. 
4. Go to 1

So instead of continually downloading the sidechain and try to import it, the logic was changed. The semantics became "find the most recent block that we have locally", instead of "find the most recent block that is part of the canonical chain, and that we have locally".

**Comment by Nanyan** [comment]
Thanks for your explanation. It's a very subtle mechanism.
