### ISSUE TITLE
[swarm] IPFS - Swarm integration

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#2050]
the plan is in the making, watch this space.
My current line of though is to have an ipfs module implementing `swarm/network.CloudStore` interface. This can run alonside bzz push (syncing). I see this as the quickest way to MVP
- interoperability in terms of network 
- client interoperability with different stages of bzz implementation / ipfs only 
- swap incentivisation for ipfs

**Comment by rht** [comment]
There is a much simpler integration (than to do with the components of devp2p-libp2p) that could be done right away: replace swarm's local storage (https://github.com/ethereum/go-ethereum/tree/swarm/swarm/storage) with ipfs' blockstore(flatfs)+chunker (https://github.com/ipfs/go-ipfs/tree/master/blocks/blockstore+https://github.com/ipfs/go-ipfs/tree/master/importer/chunk).

The perf boost in write throughput alone should be more than sufficient to justify this rewrite/offload.

Current dbStore (leveldb) used in bzzhash:
![ed8pddx](https://cloud.githubusercontent.com/assets/395821/15685070/437be12a-2794-11e6-88a2-34383c104691.png)

With ipfs flatfs (see https://github.com/rht/go-ethereum/commit/a709701793934d9d66185dd83c898dd65999a087, could still be further optimized):
![outdata](https://cloud.githubusercontent.com/assets/395821/15685109/734b3a0e-2794-11e6-82d8-b881b67d7d7b.png)

Here is the script to reproduce the plot: https://gist.github.com/rht/2264668885ca5f717c20af26033f77c1.

**Comment by zelig** [comment]
@rht thanks for this but i do not understand your measurements on several levels.

* bzzhash has nothing to do with the storage. It only runs the chunker to calculate the swarm hash of a document.
* the graph legend shows both `cp` and `bzzhash` with the sam green (at  least I am unable to distinguish). in the lower graph I guess the green that looks almost horizontal is the `cp` but the top graph only shows one green line.
* even with assuming the higher times the lower graph shows ipfs flatfs to take twice the time.
* Since the chunker is parallelised, measurements should be showing increasing file size on the x axis, not number of files (see [chunker benchmarks](https://github.com/ethereum/go-ethereum/blob/swarm/swarm/storage/chunker_test.go#L201). As you can see the y is linear in number of files (not toaaao surprising), therefore not that informative.
* not sure t
* since swarm chunk size is different from IPFS, so there are simply more db writes in swarm, making the comparison incorrect
* Finally, even if all the comparisons were correct, it still may not make sense since it is the end- to-end scenarios in a networked ethereum that swarm should be optimise on.

All this said, we encourage you to play, measure,  and will really appreciate any feedback sent our way.

**Comment by rht** [comment]
@zelig some bayesian update:
- I see. I was wondering of this as well. I did insert some lines to actually put the content into the bzz dir and to handle a directory as argument (https://github.com/rht/go-ethereum/commit/a709701793934d9d66185dd83c898dd65999a087 L88-105). For clarity's sake, I'd call this `bzzhashput`. Should I use the api (DPA?) instead, since it includes data storage?
- Right, `tar` and/or `cp` should be the "speed of light" in this measurement (local file transfer), except in few cases where there are lots of duplicate data. In the top graph, the green line refers to `bzzhashput`. Due to chunking (hence increased number of db write calls), I suspect it to be even slower than sqlite3.
- The statement should be "ipfs with flatfs takes ~twice the time of bzzhashput with flatfs". Indeed, I think there are still some crufts in the merkle dag construction & chunking in ipfs.
- The lines are mostly linear in themselves, but they serve to compare how each tools scale.
- ? I can't parse this statement. I assume this to be "not sure though" and is part of the previous bullet point.
- Sorry, here is more info: IPFS uses 256KB chunk size as default (in this benchmark I use 10KB chunk size). Swarm, I think, uses 32KB chunk size? Hence in this scenario there should be fewer db writes in swarm storage.
- I take this to mean "e2e network optimization should be prioritized first", which possibly concludes to "localstorage perf doesn't affect the *overall* e2e network transfer process". This may be the case in isolation, but is not so when the components are tied in together. The time it takes to chunk+store to local (used in netstore) could be much longer than network latency.

> All this said, we encourage you to play, measure, and will really appreciate any feedback sent our way.
Will do (am doing). I haven't measured the chunking perf of IPFS vs Swarm yet. So, the most I can propose from the benchmark for now is to replace the localstorage in Swarm with the one used in IPFS. Also, I have some net measurements on the pipeline.

**Comment by zelig** [comment]
not on the agenda right now
