### ISSUE TITLE
importing accounts/abi/bind triggers leveldb import

### ISSUE THREAD

**Issue by sammy007** [ethereum/go-ethereum#20535]
Usually you import it to read/write contracts, what a point having such a painful dependency with all its recent gems like "unknown field 'DisableSeeksCompaction'"?

Is it possible to relax that package dependencies?

**Comment by karalabe** [comment]
Myeah, this is a weird dependency to pull in. My hunch is that the external signer suppot references some weird internal package that pulls in a soup of others. This should definitely be fixed to not depend on leveldb.

**Comment by karalabe** [comment]
Digging around a bit, seems to be accounts/external -> internal/ethapi -> core/rawdb -> ethdb/leveldb.

This is the offending line which cascades everything in https://github.com/ethereum/go-ethereum/blob/master/accounts/external/backend.go#L184, which doesn't look like a too big of a type.

```go
// SignTransactionResult represents a RLP encoded signed transaction.
type SignTransactionResult struct {
	Raw hexutil.Bytes      `json:"raw"`
	Tx  *types.Transaction `json:"tx"`
}
```

We could easily break the dependency with duplicating this, but maybe we should rather move the types into their own package to allow referencing without pulling in runtime deps.

**Comment by karalabe** [comment]
This kind of boils down to a design decision of whether we want to expose the JSON marshalling types of our APIs for external programs or not. We kind of deliberately put all these into `internal` since they are kind of hacky and don't want people to depend on them. Bit ironic that we ended up depending on them ourselves (though to be fair, only a temporary measure to get accouts out, if that ever happens).

**Comment by sammy007** [comment]
Perhaps I misunderstood, but imo`ethclient` and whatever it returns should remain public, so much code depend on it.
