### ISSUE TITLE
How to reduce block time for existing ethereum blockchain network?

### ISSUE THREAD

**Issue by sharif2008** [ethereum/go-ethereum#20594]
I had deployed my private blockchain network back in 2018-08-12 16:12:48 +0600 (1 year, 167 days ago). Since then it is working. At that time the block time was 20-30 seconds which was acceptable for our private transaction. But now a days the average block time has increased to 1 min and sometimes it takes 8-10 minutes to mine a single block which seems crazy ;(

NB: There are 7 running nodes and all them has 8 GB ram. You can check the geth version in the picture.

Is there any way so that I can reduce the blocktime ? Or can anybody tell me that upgrading the geth version will solve problem?

Details can be found:- 
https://ethereum.stackexchange.com/questions/79340/how-to-reduce-block-time-for-existing-ethreum-blockchain-network 

#### System information
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 13
Model name:            QEMU Virtual CPU version (cpu64-rhel6)
Stepping:              3
CPU MHz:               2260.998
BogoMIPS:              4521.99
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
NUMA node0 CPU(s):     0,1

Geth details-  [check the screenshot](https://i.stack.imgur.com/3ypor.png)

**Comment by karalabe** [comment]
In PoW mode the network adjusts to 14 second blocks, independent of mining power, so this seems odd. Perhaps it's the ice age? What's your chain configs (i.e. which forks did you enable on your network)? In general is would seem odd to use a PoW private network, since the security will be 0 unless you have massive mining power. Why not use PoA (Clique)?

**Comment by sharif2008** [comment]
@karalabe  Yeah I agree that too.  That mistake happened about 2 years ago. Now what can I do if I want persist the current blocks int PoA mode? That is how can I migrate to PoA mode from PoW with current blocks. 

Geth details is:  _**Geth/v1.8.13-stable-225171a4/linux-amd64/go1.10.3**_
--




Here is my genesis.json 

```
{
    "config": {
        "chainId": 17,
        "homesteadBlock": 0,
        "eip155Block": 0,
        "eip158Block": 0
    },
    "difficulty": "0x100",
    "gasLimit": "0x2100000",
    "alloc": {
        <ignored>
    }
}
```
Also I want to know why the mining is taking so much time and how can I resolve it ?

**Comment by karalabe** [comment]
> Now what can I do if I want persist the current blocks int PoA mode? That is how can I migrate to PoA mode from PoW with current blocks.

You cannot a this point.

> Here is my genesis.json

Your network is missing 4 forks compared to mainnet currently: Byzantium, Constantinople, Petersburg and Istanbul (https://eips.ethereum.org/meta), some of those are doing difficulty adjustments, so there's a high probability that one or the other would fix your difficulty issues.

> Geth/v1.8.13-stable

That's an ancient release. We did 26 Geth releases since then. We cannot support such old code bases.
