### ISSUE TITLE
ABIGEN missing parameter 

### ISSUE THREAD

**Issue by GregTheGreek** [ethereum/go-ethereum#20640]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: Version: 1.9.10-stable
OS & Version: OSX

After running abigen, it generates the go bindings, but it lacks the `bind.ContractFilterer` parameter everywhere.

A few notes, I didn't use solcjs, instead i used a script that parses the output from `truffle compile` to generate `.bin` and `.abi` files.

```
Emitter.go:121:30: not enough arguments in call to bind.NewBoundContract
        have (common.Address, abi.ABI, bind.ContractCaller, bind.ContractTransactor)
        want (common.Address, abi.ABI, bind.ContractCaller, bind.ContractTransactor, bind.ContractFilterer)
```

**Comment by GregTheGreek** [comment]
Tested on `1.8.20-stable-24d727b6` and it seems to work

**Comment by rjl493456442** [comment]
Can you please share the contract so that we can reproduce locally?

**Comment by karalabe** [comment]
The issue here is probably that you used a newer `abigen` to wrap a contract but didn't update the underlying go-ethereum lib in your own codebase that serves it. Abigen and the bindings are constantly tested on our CI so we are certain that the same version abigen and go-ethereum lib work well in pairs. Please make sure both abigen as well as the go-ethereum library you are using in your project is updated.

**Comment by GregTheGreek** [comment]
sorry for never getting back. I can confirm that was the issue.
