### ISSUE TITLE
`eth_estimateGas` uses impossible `block.number`.

### ISSUE THREAD

**Issue by 3esmit** [ethereum/go-ethereum#20649]
#### Expected behaviour

`eth_estimateGas` should use the pending `block.number`;

#### Actual behaviour

`eth_estimateGas` uses the latest `block.number`, making estimations fail in certain conditions.

#### Steps to reproduce the behavior

1. Create a contract which check if last changed block is current block number, if no, do a very expansive operation, if yes, do a very cheap operation & deploy it.
2. Estimate at first block & submit: success transaction/estimation
3. Estimate while the latest block is still the last change block in the contract & submit: failed transaction/estimation.

I am working on a test contract and script to demonstrate and test the issue, which I will update here. 

#### Notes 

The same behavior should be applied to `eth_call`. 

Details on how the bug was found and affects users here: https://github.com/status-im/status-go/issues/1849

**Comment by 3esmit** [comment]
Looks like it should be using pending block: https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L1423-L1424

I assume that the API is being used here, so pending block don't need to be passed https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/bind/base.go#L221-L222

GraphQL seems to be correct  https://github.com/ethereum/go-ethereum/blob/master/graphql/graphql.go#L887-L888


All seems good here...

**Comment by ligi** [comment]
Thanks for the report! Just wondering: is status also using a multiplicator like MetaMask is  doing (currently 1.5 AFAIR) - because otherwise even if pending-block is used there is still a way to fail. E.g. when 2 transactions are submitted at the sameIsh time one with a lower-fee - one with a higher fee - then you basically can end up in the same situation. Also do not like these multiplicators (and the attached magic numbers) - but currently also do not see a good way out of this. That said I agree that we should use the pending-block here.

**Comment by holiman** [comment]
Odd, it does seem like it's already using the pending: https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L952

**Comment by 3esmit** [comment]
I noticed that in your sources is using pending block. 

Do you know if this is a recent change? status-go might be used an outdated version.

**Comment by 3esmit** [comment]
Ah, got it... there is a race condition there... 

Its possible that, sometimes, when pending block is retrieved a block just get mined, and this block number is then passed to gas estimate which would use the latest block, causing the wrong estimation.

Instead of using "pending block", maybe a flag should be passed to estimator, like block number = "0xFFFFFFFFFFF", where it would understand it should use the pending block for estimation.

**Comment by rjl493456442** [comment]
> Instead of using "pending block", maybe a flag should be passed to estimator, like block number = "0xFFFFFFFFFFF"

Using an arbitrary number won't fix this issue.  Also the scenario you describe is hard to be fixed in the Geth side. 
For Geth we can only return a gas estimation based on the current pending block(or whatever state specified by API). 

When you submit the transaction with the suggested gas limit, but in this time the block state is changed(include more blocks) so that the original gas limit doesn't work. I think it's more or less an issue at the application level. 

So I will close the issue now, but feel free to reopen it.

**Comment by 3esmit** [comment]
I don't see how this could be fixed at application level, as application cannot foresee the condition, as it's caused by the gas being calculated considering that multiple transactions occur in the same block. 

The only way to "fix this at application level" would be to use a hard coded gas limit for the "worst condition", therefore I consider it's a bug in the `eth_estimateGas`, not in the application level. 

This bug will cause random transaction fails out of gas due wrong calculation of gas by geth.


# Reproduction

    Create a contract which check if last changed block is current block number, if no, do a very expansive operation, if yes, do a very cheap operation & deploy it.
    Estimate at first block & submit: success transaction/estimation
    Estimate while the latest block is still the last change block in the contract & submit: failed transaction/estimation.

**Comment by rjl493456442** [comment]
@3esmit If I understand correctly, the contract has a very high execution environment dependence.

> if last changed block is current block number, do A; else do B

We can never give the correct estimation because we can't decide whether these two transactions will
be eventually put into the same block. 

To be honest, I would suggest the change in the contract level.

**Comment by 3esmit** [comment]
The contract is an ERC20 token, MiniMeToken. The function failing to gas estimate is the transfer. 

MiniMeToken saves the balance of the accounts on each block. When estimate function runs and it consider that there are two transactions to/from the same address, it will be cheaper to update then to add a new position, so it would calculate a lower gas cost. 

Transactions should be estimated as they are isolated in the block. 


This is the estimation that have lower cost https://github.com/Giveth/minime/blob/ea04d950eea153a04c51fa510b068b9dded390cb/contracts/MiniMeToken.sol#L459

And this is the normal case, a new entry to the array https://github.com/Giveth/minime/blob/ea04d950eea153a04c51fa510b068b9dded390cb/contracts/MiniMeToken.sol#L455

**Comment by 3esmit** [comment]
I don't think this should be closed.
