### ISSUE TITLE
les: A possible data race in setCapacity() due to inconsistent field protection

### ISSUE THREAD

**Issue by BurtonQin** [ethereum/go-ethereum#20651]
#### System information
Geth version: 1.9.10
OS & Version: Windows/Linux/OSX
Commit hash : 8045504abf64a865be4b1dbc780b796a9f5d11cc

#### Expected behaviour
A possible data race in func `setCapacity()` in les/clientpool.go.
`f.capLimit` is read/written 9 times; 7 out of 9 times it is protected by `f.lock.Lock()`
; 2 out of 9 times it is read without a Lock, which are in func `setCapacity()`.
https://github.com/ethereum/go-ethereum/blob/8045504abf64a865be4b1dbc780b796a9f5d11cc/les/clientpool.go#L484-L494
A data race may happen when `setCapacity()` and other func like `setLimits` are called in parallel.
I wonder if developers forgot to protect `f.capLimit` by `f.lock.Lock()` in func `setCapacity()` or there are some special calling rules on `setCapacity()` to guarantee the protection.
#### Actual behaviour
No, I found it through static analysis.

#### Steps to reproduce the behaviour
No.

#### Backtrace
No.

**Comment by BurtonQin** [comment]
Similarly, a possible data race is in func `handle()` in les/fetcher.go.
`p.headInfo` is not protected by p.lock.Lock()
https://github.com/ethereum/go-ethereum/blob/8045504abf64a865be4b1dbc780b796a9f5d11cc/les/client_handler.go#L128
But it is protected by `p.lock.Lock()` or `p.lock.Rlock()` in all other places (1 place in fetcher.go, 10 places in peer.go)
https://github.com/ethereum/go-ethereum/blob/8045504abf64a865be4b1dbc780b796a9f5d11cc/les/fetcher.go#L348-L351
A data race may happen when func `handle()` and other func like `announce()` are called in parallel.
I wonder if developers forgot to protect `p.headInfo` in func `handle()` or there are some special calling rules on `handle()` to guarantee the protection.
A possible fix is to add a boolean parameter to `f.announce()`, indicating whether it is locked or not. If locked, we won't use `p.lock.Lock()` inside it.

**Comment by zsfelfoldi** [comment]
This is actually safe, though probably not the nicest piece of code because it is hard to see why it is safe. `clientPool.setCapacity` should only be called while `clientPool.lock` is locked and this is what really happens because it is called in api.go from a callback of `clientPool.forClients` which already locks the pool lock.
Btw a major refactoring of the client pool is happening right now because new features are being added and the existing code was hacky enough already. It is WIP but close to being finished, hopefully it will make things cleaner.
https://github.com/ethereum/go-ethereum/pull/21236
