### ISSUE TITLE
geth start-up configuration file

### ISSUE THREAD

**Issue by tymat** [ethereum/go-ethereum#2067]
Would be nice to have a configuration file that has the various geth command line parameters (JSON, yaml, ini, dotfile, etc...).  Today we get around this by creating a shell script but it would be nice to have something better for automated deploys of geth nodes.

```
geth --config ~/.ethereum/geth.[json,yaml,ini,etc.]
```

**Comment by obscuren** [comment]
This will not be implemented for numerous reason and one of them is maintenance. Configuration files tend to bite people in the ass and therefor we'd rather not see it implemented.

I don't think `.sh` files are that bad tho, they are actually rather nice and feedback is given when a bad configuration parameter is being used.

**Comment by pipermerriam** [comment]
I would like to *petition* that this be reconsidered as a feature.

@obscuren you say that they tend to bite people in the ass.  I don't see why the implementation of a config file cannot be done so that it protects people from the common pitfalls.

1. If a config value is present in the file that doesn't map to one of the allowed options display a warning or throw an error.
2. At startup, if a config file was found or used, print out a message indicating as much: `"Loaded configuration options /path/to/config.something"`

As for maintenance overhead, it has been almost a year since this was first proposed.  I understand there is overhead here, but configuration via config file is *extremely* common and `geth` has matured a lot in the last 10 months.

**Comment by fjl** [comment]
Added in #13875, released in 1.6.0.
