### ISSUE TITLE
Migration from geth accounts to Clef - missing RPC calls

### ISSUE THREAD

**Issue by Crypto2** [ethereum/go-ethereum#20696]
I'm looking at Clef as a way to replace geth accounts due to this longstanding issue: https://github.com/ethereum/go-ethereum/issues/16874

As an accounts replacement everything seems to be good except for:

1. Having a way to unlock an account or set it's password over the external RPC. (ie. an equivalent of personal_unlockAccount or something like account_storePassword or even just specifying the password in the account_signTransaction call)

2. Being able to specify the password for account_new over the external RPC.

Those 2 things would make Clef a fairly complete key management and I think would be greatly beneficial to the ETH ecosystem.

I think it's a good idea when you have a decent amount of keys in your keystore because:

1. Clef as a standalone daemon is both less likely to crash than the full geth node and shouldn't need updates as often, making restarts less frequent of an issue.
2. Right now the geth node does nothing while loading keys so it is time wasted it has to catch up syncing the blockchain, keeping them separate means even if it takes hours for Clef to start up while scanning the keystore it's not blocking syncing on the geth node while it's doing it.
3. Encouraging this usage may help prioritize changes in Clef to optimize/store the keystore cache between sessions so a multi-hour startup time isn't needed.
4. When you have multiple geth nodes you end up with keystores on multiple servers requiring rsync or other solutions to keep them all in sync, have one centralized Clef daemon would make it so those solutions are no longer needed.

**Comment by holiman** [comment]
Hi, 

First of all, Clef _right now_ won't handle millions of accounts any better than geth does, however, we're hoping to fix that going forward. 


Regarding the two points, 

1.  Clef will never ever offer unlock in the same way geth does. However, `clef` has a much more secure alternative, which is a rule-engine, where you can auto-approve transcations. See https://github.com/ethereum/go-ethereum/blob/master/cmd/clef/tutorial.md#automatic-rules . 

In essence - you store the password into Clef's own database. Doing so means that whenever an "approval" is made, the user does not have to specify the password. Then you also add a rule to auto-approve (certain) transactions, and that means you don't even have to manually approve transactions either. 

2. Unfortunately, this goes against a very important underlying principle in Clef -- nothing secret/sensitive ever goes over the external API. However, we might add such a method to the internal API. 

And yes, I totally support that people should migrate to Clef -- that's been the plan from the beginning. I'll help out with integration any way I can. 

However, I'll close this ticket, since 1) is already "done" , and we're not going to do 2)

**Comment by Crypto2** [comment]
@holiman Right, I know it won't handle quantity of keys the idea is that it will be more reliable as a standalone daemon versus using geth accounts since it should be less crashy and need updates less often. It also provides a nice centralized account daemon versus syncing keystores between nodes.

The main thing is there is no way to support an existing keystore from geth. As far as I have seen the rule engine has no way to input passwords + even if it did we'd have to make a script with tons of keys in it and it wouldn't be able to support newly made keys since it can't put a password in for those. Internal or external API doesn't matter to me as long as it isn't a nightmare to implement lol.

These newer APIs would of course not be on by default, it would need a new switch like --allow-unsafe-external-api or something like that. Realistically to support migrations I don't see any way around it, even if you only had 100 keys you'd need some way to automate it versus  typing them all in one by one. Just thinking of the easiest way to support things since Clef is already nearly there and just needs 2 minor tweaks to get it to where it needs to be.

**Comment by holiman** [comment]
> The main thing is there is no way to support an existing keystore from geth.

That's exactly what clef does. It uses the existing keystore from geth (or, alternatively, creates a geth-like keystore if one doesn't exist)

> As far as I have seen the rule engine has no way to input passwords

No, it's not inherently part of the rule engine. It's a totally standalone feature: 

https://github.com/ethereum/go-ethereum/blob/master/cmd/clef/tutorial.md#advanced-rules:
```
$ clef setpw 0xd9c9cd5f6779558b6e0ed4e6acf6b1947e7fa1f3

Please enter a password to store for this address:
Password:
Repeat password:
```

That means the rule-engine and the password-storage are totally separate features. 
1. No stored pw, no ruleset: You have to manually approve and supply pw for each tx
2. With stored pw but no ruleset: you have to manually approve each tx
3. No stored pw, but ruleset: Every time a ruleset approves a tx, you have to manually supply a password
4. With stored pw, with ruleset: No manual intervention is needed (unless the ruleset responds with something other than `Approve`/`Deny` -- because in that case it goes to manual)

> Realistically to support migrations I don't see any way around it, 

Yeah, so that's not an issue. You can _already_ try clef out by simply

1. Start clef, 
2. Start geth , with `geth ... --signer /path/to/clef/ipc`. Geth will then _not_ handle accounts, but relay everything to clef. And clef will locate the geth-keystore and no migration is needed. For any call to geth which requires signing (e.g. personal.sendTransaction), it will relay it to clef.

**Comment by Crypto2** [comment]
@holiman Yep, I understand all that but that's the point I'm making. For non-interactive uses (ruleset that just approves all sends) if you had even 100 keys running 'clef setpw' wouldn't be great as a way to migrate over since it would require manual input and take forever.

I know Clef as envisioned is kind of a signing server/keystore for personal use, the changes I'm proposing won't limit it in that function but would also allow for small/medium scale use as the same but for non-interactive use like stores, smaller wallet providers, and other automatic systems that may or may not already be using geth. In the case they are new users without an existing keystore they would still need a way to set the password when creating new accounts over RPC.

The ruleset docs even has examples like limiting send amounts and such which indicate at least some thought of automatic use, this is just filling in the missing pieces of that.
