### ISSUE TITLE
Idiomatic way to use RLP encoding when a field is a union type 

### ISSUE THREAD

**Issue by fxfactorial** [ethereum/go-ethereum#20754]
Say we have a struct like so:

```go
type F struct {
  A string 
  B interface{}
}
```

Where B is a type that could be Either 

```go
type G struct {
  C *big.Int
}
```

Or
 
```go
type H struct {
  D string 
}
```
I’m not clear on the idiomatic way to represent F under the intention of RLP encoding scheme because the interface will make it awkward. What is the usual way to structure types with fields that represent a union type ?

**Comment by karalabe** [comment]
Union types are a bit messy, because RLP does not include type metadata into the encoded blobs, so there's nothing to guide decoding. We use them very rarely in Ethereum for this exact reason.

The only way to handle such cases if you write the decoder explicitly yourself, and even then you need to be able to differentiate between the cases based on the encoded data (e.g. is the "next" field an int, or a list? Is it of size x or y?). If you can differentiate using this trick, unions are kind of possible in a limited way. Generic unions are definitely not something you want to do.

In your specific case, you'll have a hard time because `G` and `H` are both structs, so they will both get marshalled as a list. You'd need to look inside further to see if the item is a number or another list. It gets messy fast.

One possible way out would be to add a type marker (e.g. an enum field before the interface) that could be used to direct the decoder (you'd still need to roll your own decoder though, there's no support for dynamic types).

**Comment by fxfactorial** [comment]
thank you so much for such a great answer. 

I tried the type marker approach but it is definitely hacky and error prone. 

I assume then that the best way to avoid this is to bite the bullet and just remove the polymorphism that a union type provides. 

Is there an example in the ethereum codebase that went this way? To avoid this awkward situation under RLP encoding.

**Comment by karalabe** [comment]
> I assume then that the best way to avoid this is to bite the bullet and just remove the polymorphism that a union type provides.

If possible, yes, I'd suggest that path.

> Is there an example in the ethereum codebase that went this way? To avoid this awkward situation under RLP encoding.

We've always tried to avoid polymorphism. AFAIK there are only 2 cases in that are live:

 * The receipts prior to Byzantium had intermediate state roots and post Byzantium a status code. The decoding is here: https://github.com/ethereum/go-ethereum/blob/master/core/types/receipt.go#L135
 * The headers in the networking protocol can be retrieved either via a number or via a hash. These are stored in the same `origin` field and decoded depending on their size: https://github.com/ethereum/go-ethereum/blob/master/eth/protocol.go#L153

In both cases above however decoding is easy, because the "polymorphism" is simply "either a hash or a number", which is very easily distinguishable based on size.
