### ISSUE TITLE
node: consider redesigning some of the API around context

### ISSUE THREAD

**Issue by mvdan** [ethereum/go-ethereum#20784]
For example, take https://godoc.org/github.com/ethereum/go-ethereum/node#Node.Start and https://godoc.org/github.com/ethereum/go-ethereum/node#Node.Stop. I think both of these could be unified into a single `Node.Start(context.Context) error`, and the semantics would be more idiomatic.

To keep backwards compatibility, perhaps we could add `FooContext` companion funcs to `Foo`, similar to `os/exec.CommandContext`. An alternative is to redesign existing APIs in a future v2.

I'm sure there would easily be many more API candidates for considering. For exampke, in the same godoc page I see `StartRPC`/`StopRPC`.

**Comment by karalabe** [comment]
Re API stability, I think we gave up a bit on the dream that we guarantee API backward compatibility. The repo root is fairly stable that we don't want to touch and maybe `ethclient` is also a bit more special snowflake since that's what most people use from Go to interface Ethereum, but for the rest, if some modification makes sense, just do it. It's better to clean up the code than to pile even more legacy junk in there. That said, I'll ask @fjl to weigh in here too because he's the saner one of the two of us wrt backwards compatibility :D 

Re this particular suggestion, do you have (a link to) some code that uses this pattern? I do see how this could work out, but truth be told it's the first time I come across it.

**Comment by mvdan** [comment]
Some examples from the standard library:

* https://golang.org/pkg/os/exec/#CommandContext
* https://golang.org/pkg/net/#ListenConfig.Listen
* https://golang.org/pkg/net/#Dialer.DialContext
* https://golang.org/pkg/net/http/#Server.Shutdown

https://blog.golang.org/context is a good introduction, and https://golang.org/pkg/context/ has up to date docs.

The TL;DR is that any API which might block for a long time, or which might run forever, should take a context to let the caller control when it stops. This includes any services/daemons one can start and stop, like the Node API above.

Your API could look like:

```
ctx, cancel := context.WithCancel(parentCtx)
defer cancel() // stop node when we finish

if err := node.Start(ctx); err != nil { ... }

// use node for some limited amount of operations
```

It's also common to use context cancellation to set timeouts (common for single operations or shutdown APIs), to handle interrupts (e.g. to stop gracefully when one hits ^C), or to make sure that cancellation is propagated "downstream" (e.g. to make cancelling a context API also cancel any other "children" context APIs it started).

The only wrinkle here is that `cancel()` is never blocking, and doesn't return any erro. You could keep the separate `Wait` method, to block until the node is fully down and return any error - that's probably the simplest option here. Other APIs use different mechanisms, like https://golang.org/pkg/net/http/#Server.Shutdown (to gracefully close clients) or https://godoc.org/github.com/chromedp/chromedp#Cancel (to wait until resources are cleaned up and return any errors).

**Comment by fjl** [comment]
I think context is not the right thing for managing long-lived services with many background goroutines, the main reason being that there is no good way to wait for the service to actually stop through the context.

The thing with contexts is that they're really mostly for unblocking the caller in case of cancellation. There are lots of ways to combine contexts to achieve control of cancellation even for chains of callers. We do use context for some of the request-based APIs, and they do work for us there. 

We also use contexts inside of some components for shutdown coordination, so that we can cancel any requests created by the component.

**Comment by fjl** [comment]
We considered this in the recently merged refactoring, but decided against it because of the reasoning given above. With the new structure in package node, we can always add a method like `Node.Context()` that returns a context which tracks the lifecycle of the node.
