### ISSUE TITLE
Is there a way to get the Websocket endpoint in geth for android

### ISSUE THREAD

**Issue by rohankeskar19** [ethereum/go-ethereum#20790]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.9.12`
OS & Version: Android
Commit hash : (if `develop`)

I'm using the geth for android version, I can start the node on android with it but is there a way to get websocket endpoint to set the whisper client for the local node similar to geth on windows, The endpoint is shown in the logs for the geth but in android I can't see any logs in the logcat which mentions the websocket endpoint, Is there a way by which I can do that?

**Comment by gballet** [comment]
There is unfortunately no way to do such thing. One thing you could do is to create a PR that allows mobile clients to call the `Send` function or, alternatively, send json payload to an RPC handler, and then create your own Websocket handler in your app.
I'm closing this issue because we will not spend time working on this workflow.

**Comment by nader1349** [comment]
Hi, I don't know the name of the pool and password due to Windows replacement, so I can't log in.


    On Thursday, April 9, 2020, 1:27:04 PM GMT+4:30, Guillaume Ballet <notifications@github.com> wrote:  
 
 


Closed #20790.
