### ISSUE TITLE
GPU hashrate down when block imported

### ISSUE THREAD

**Issue by poiuty** [ethereum/go-ethereum#2080]
After import block, some time hashrate = 0
```
> miner.hashrate
25515786
> I1216 03:09:56.021889    4995 blockchain.go:1230] imported 1 block(s) (0 queued 0 ignored) including 5 txs in 37.035837ms. #698000 [89dd5554 / 89dd5554]
I1216 03:09:56.171042    4995 worker.go:570] commit new work on block 698001 with 1 txs & 0 uncles. Took 148.419139ms
> miner.hashrate
0
> miner.hashrate
0
> miner.hashrate
0
> miner.hashrate
0
> miner.hashrate
25525228
```

**Comment by obscuren** [comment]
This is because `ethminer` reports the rate every so often. Upon finding a new block the rate goes down to 0 and it will start reporting the correct number after a submission of `eth_sumbitHashRate`.

This does not mean that your miner isn't functioning properly, just that hasn't submitted a new rate yet.
