### ISSUE TITLE
go get ... ; go install ... - can not get influxdb/client and install geth cmd

### ISSUE THREAD

**Issue by AnimusPEXUS** [ethereum/go-ethereum#20809]
following geth build+installation instruction for gnu+linux at https://geth.ethereum.org/docs/install-and-build/installing-geth#most-linux-systems-and-macos, leads to problem of go getting influxdb/client

command error messages:
`go get -v -d github.com/ethereum/go-ethereum`
no errors
`go get -v -u 'github.com/influxdata/influxdb'`
no errors
`go install -v -i github.com/ethereum/go-ethereum/cmd/geth`
`cannot find package "github.com/influxdata/influxdb/client" in any of:`
it appears, there is no `client` in `github.com/influxdata/influxdb/` at all

**Comment by karalabe** [comment]
Please make sure you have Go 1.13 or later, we rely on go modules. If you must build with 1.12 or 1.11, please specify the `GO111MODULE=on` environment var before building.

**Comment by AnimusPEXUS** [comment]
used go version is recent without docker
`go version go1.13.6 linux/amd64`

**Comment by AnimusPEXUS** [comment]
just tried `make geth` (which is with GO111MODULE=on) - this works ok

**Comment by karalabe** [comment]
Yeah, so this is an issue in Go, I've opened a new one https://github.com/golang/go/issues/38196, there was an old one too that nobody cared to fix https://github.com/golang/go/issues/24250.

Long story short, you'll need to download our repo explicitly without building and then build from within the root. Otherwise Go just ignores the module file. Closing this as there's not much we can do, Go needs to get their act together wrt modules.
