### ISSUE TITLE
Downloads page not loading

### ISSUE THREAD

**Issue by achalpatel** [ethereum/go-ethereum#20855]
Hello,
I want to notify that the downloads page - https://geth.ethereum.org/downloads/
is failing to load by displaying  "Retrieving packages from release server..."

**Comment by ligi** [comment]
It is loading for me but it took a bit of time (don't remember it taking so long before) - but it finished. How long did you wait?

**Comment by achalpatel** [comment]
I am waiting for 1-2 minutes and there is google chrome alert saying "Failed to load releases". I am still waiting but no response.

**Comment by karalabe** [comment]
The xml dump that lists all the binaries we have is about 10MB in size, so it takes a while to download. Afterward for me the page crunches quite a bit, which is strange.

**Comment by ucwong** [comment]
Yes, I also failed several times when loading this page before ... ><

**Comment by achalpatel** [comment]
The page loaded and I was able to download it when using a VPN. Might be server issue in North America.

**Comment by holiman** [comment]
Actually, it splits the downloading up into parts. For me it does 5 fetches, four of them 2.5 MB:

https://gethstore.blob.core.windows.net/builds?restype=container&comp=list&maxresults=5000&prefix=geth-&marker=2!136!MDAwMDU3IWdldGgtYWxsdG9vbHMtbGludXgtYXJtNjQtMS45LjExLXVuc3RhYmxlLTcxMWVkNzRlLnRhci5neiEwMDAwMjghOTk5OS0xMi0zMVQyMzo1OTo1OS45OTk5OTk5WiE-
https://gethstore.blob.core.windows.net/builds?restype=container&comp=list&maxresults=5000&prefix=geth-&marker=2!136!MDAwMDU4IWdldGgtYWxsdG9vbHMtbGludXgtbWlwc2xlLTEuOS4xNS11bnN0YWJsZS1mM2YxZTU5ZS50YXIuZ3ohMDAwMDI4ITk5OTktMTItMzFUMjM6NTk6NTkuOTk5OTk5OVoh
https://gethstore.blob.core.windows.net/builds?restype=container&comp=list&maxresults=5000&prefix=geth-&marker=2!112!MDAwMDM5IWdldGgtbGludXgtYW1kNjQtMS44LjE4LTU4NjMyZDQ0LnRhci5neiEwMDAwMjghOTk5OS0xMi0zMVQyMzo1OTo1OS45OTk5OTk5WiE-
https://gethstore.blob.core.windows.net/builds?restype=container&comp=list&maxresults=5000&prefix=geth-&marker=2!128!MDAwMDUxIWdldGgtbGludXgtbWlwcy0xLjkuMTItdW5zdGFibGUtOTcyNDNmM2EudGFyLmd6LmFzYyEwMDAwMjghOTk5OS0xMi0zMVQyMzo1OTo1OS45OTk5OTk5WiE-
https://gethstore.blob.core.windows.net/builds?restype=container&comp=list&maxresults=5000&prefix=geth-&marker=2!120!MDAwMDQ0IWdldGgtd2luZG93cy0zODYtMS45LjgtdW5zdGFibGUtYzVjNWUwZGIuemlwITAwMDAyOCE5OTk5LTEyLTMxVDIzOjU5OjU5Ljk5OTk5OTlaIQ--

So it seems we're requesting them in batches of 5000. Perhaps we could request only the latest 500 items or so, and update the page. And if someone explicitly wants to get older stuff, we could load the remaining items on demand.

**Comment by holiman** [comment]
Unfortunately, there doesn't seem to exist any API-params to tell it to "give me 500 items, reverse order (only the latest)" https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs . When I ask it for 2 items, I get stuff from 2016

```
curl 'https://gethstore.blob.core.windows.net/builds?restype=container&comp=list&maxresults=2&prefix=geth-' -H 'User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0' -H 'Accept: application/xml, text/xml, */*; q=0.01' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Origin: https://geth.ethereum.org' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: https://geth.ethereum.org/downloads/' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache'
```
```xml
<?xml version="1.0" encoding="utf-8"?><EnumerationResults ServiceEndpoint="https://gethstore.blob.core.windows.net/" ContainerName="builds"><Prefix>geth-</Prefix><MaxResults>2</MaxResults><Blobs><Blob><Name>geth-alltools-darwin-amd64-1.5.0-c3c58eb6.tar.gz</Name><Properties><Last-Modified>Tue, 15 Nov 2016 14:55:58 GMT</Last-Modified><Etag>0x8D40D67822E1541</Etag><Content-Length>20360983</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-MD5>mwPxjrViwk6vHvOrVKhqyA==</Content-MD5><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState></Properties></Blob><Blob><Name>geth-alltools-darwin-amd64-1.5.0-c3c58eb6.tar.gz.asc</Name><Properties><Last-Modified>Tue, 15 Nov 2016 14:55:58 GMT</Last-Modified><Etag>0x8D40D678273BA9D</Etag><Content-Length>800</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-MD5>4GJ8HiAyYd/Km4TLRPeieA==</Content-MD5><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState></Properties></Blob></Blobs><NextMarker>2!124!MDAwMDQ4IWdldGgtYWxsdG9vbHMtZGFyd2luLWFtZDY0LTEuNS4xLTgxMDM4OWMwLnRhci5neiEwMDAwMjghOTk5OS0xMi0zMVQyMzo1OTo1OS45OTk5OTk5WiE-</NextMarker></EnumerationResults>
```

**Comment by holiman** [comment]
Oh. It seemed a bit odd to me that meta-info about our _releases_ went over 10Mb. But the reason is that the blobs are not only the releases, it's also the develop-versions. So for every single commit to master, we publish 10 versions of geth and 10 versions of alltools. We should do two things, IMO

- Remove/unlist all `-unstable` binaries which are more than a month old, Preferrably we should clean `unstable` once in a while.
- Change the naming, so `unstable` is part of a prefix. IF we do that, then we can change the download page to use a prefix and fetch stable/unstable in two separate steps.

**Comment by holiman** [comment]
There was an exising 'purge' travis cron-job. However, the cron-job wasn't enabled, and it had an error which prevented it from successfully deleting all things it should have deleted. This has now been fixed, and the cron-job is enabled weekly. The download size went down to ~2.5 Mb, and should grow much slower from this point.

**Comment by firesh** [comment]
Content-Type shows gzip is not enabled. Can enable gzip on azure or use any gzip enabled CDN URL?
![image](https://user-images.githubusercontent.com/7334304/88122772-038d2400-cbfc-11ea-8413-311c79d56a04.png)

**Comment by joeytwiddle** [comment]
I'm getting this problem because I'm on a 4G network. So using the browser's debugger, I edited this variable:

```
var url = 'https://gethstore.blob.core.windows.net/builds?restype=container&comp=list&maxresults=5000&prefix=geth-';
```

In my case, fetching maxresults=500 instead of 5000 worked. (I also set `marker=""` to drop out after the first fetch.)

It's difficult to tune that batch size appropriately for every client's network. But perhaps it's good to configure it a bit lower, for poorer networks.

Possible solutions:

1. As firesh suggested, **enabling gzip** might help a lot.
2. Find where the timeout is, and increase it. (My fetch was failing after 34 seconds.)
3. Reduce the maxresults from 5000 to something lower (maybe 500).

----

Is there any other place to see the list of downloads? If so, the failure popup could direct the user to there.

----

If you are a user just trying to download the latest version, you can wait until the failure message, then run the following in the browser's console, to make the page usable:

```
$('#loader, .modal-backdrop').remove();
$('body').removeClass('modal-open');
```

**Comment by joeytwiddle** [comment]
Happening again today. Timeout after 30 seconds. Not sure if it's the server or my network which is under strain.

![Screenshot_20220218_151154](https://user-images.githubusercontent.com/911799/154636999-4edc7fac-ed37-4d72-a8aa-9e268ea9c658.png)

![Screenshot_20220218_150935](https://user-images.githubusercontent.com/911799/154636984-440525d7-2aa5-4263-b06e-83655260730d.png)

Reducing the maxresults to 500 was still failing, but 250 worked ok.

![Screenshot_20220218_152504](https://user-images.githubusercontent.com/911799/154637024-6e3baef1-20ab-4e30-a7f1-c6fb7004e9da.png)

This issue could be reduced by:

1. Provide another way to download the releases. (Currently the GitHub releases page just points us to this page!)

2. Make the website clean up the modal after a failure, so that users could at least access the links on the top of the page.

3. Change the (server?) timeout from 30 seconds to 180 seconds.

The current situation is network-ist!

**Comment by fjl** [comment]
The code for the downloads page is in this repo, in the `gh-pages` branch. At this time, we are using JavaScript to load the releases because the page itself is static.

We are aware this page absolutely sucks and needs a rewrite. We just don't have time to do it unfortunately.
