### ISSUE TITLE
eth.blockNumber is 0 but should not equal zero

### ISSUE THREAD

**Issue by schnitzlein** [ethereum/go-ethereum#20906]
Hi there,

#### System information

Geth version: `geth version`
Geth
Version: 1.9.12-stable
Git Commit: b6f1c8dcc058a936955eb8e5766e2962218924bc
Git Commit Date: 20200316
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.13.8
Operating System: linux

#### Expected behaviour
eth.blockNumber should be: 7683731
according to the go-lang Source code from: https://github.com/ethereum/go-ethereum/blob/c8e9a91672ce27d3c82a579a14d840bd6a04049f/internal/ethapi/api.go#L79

**the eth.sync is:**
syncing: {
    currentBlock: 7683642,
    highestBlock: 7683731,
    knownStates: 55169567,
    pulledStates: 55158665,
    startingBlock: 0
  },

#### Actual behaviour
**the whole eth is:**

> eth
{
  accounts: [],
  blockNumber: 0,
  coinbase: undefined,
  compile: {
    lll: function(),
    serpent: function(),
    solidity: function()
  },
  defaultAccount: undefined,
  defaultBlock: "latest",
  gasPrice: 1000000000,
  hashrate: 0,
  mining: false,
  pendingTransactions: [],
  protocolVersion: "0x41",
  syncing: {
    currentBlock: 7683642,
    highestBlock: 7683731,
    knownStates: 55169567,
    pulledStates: 55158665,
    startingBlock: 0
  },

#### Steps to reproduce the behaviour
Geth is running with:
```
PID   USER     TIME  COMMAND
    1 geth      3h43 geth --nousb --datadir /home/geth/.ethereum --testnet --ws --wsaddr 0.0.0.0 --wsport 8546 --wsorigins * --ipcdisable --syncmode fast
```

and the geth java-script console is succesfully launched.

I have a successfully running client where the eth.chainId() becomes 0x3 and it is syncing: false.
But this kind of configuration in different system shows me strange errors. I double/tripple checked all ports and connection vectors. 

#### Backtrace
The geth client is connected succesfully and imported states also new blocks, but still this blockNumber is 0 and the eth.chainId() is 0x0 which is bad, because I need connection from ws from outside and its rely on this chainId...

Someone please? Do you an advice? or Idea=

````
...
INFO [04-09|12:45:33.412] Imported new state entries               count=768  elapsed=5.660ms   processed=55300361 pending=5039   retry=0    duplicate=6655 unexpected=38361
INFO [04-09|12:45:35.265] Imported new state entries               count=768  elapsed=4.559ms   processed=55301129 pending=6064   retry=0    duplicate=6655 unexpected=38361
INFO [04-09|12:45:36.668] Imported new state entries               count=1920 elapsed=11.625ms  processed=55303049 pending=4751   retry=0    duplicate=6655 unexpected=38361
INFO [04-09|12:45:37.368] Imported new block headers               count=1    elapsed=5.416ms   number=7683754 hash=b488ac…5c894b
INFO [04-09|12:45:38.283] Imported new state entries               count=768  elapsed=4.831ms   processed=55303817 pending=4627   retry=0    duplicate=6655 unexpected=38361
INFO [04-09|12:45:39.857] Imported new state entries               count=768  elapsed=5.343ms   processed=55304585 pending=4430   retry=0    duplicate=6655 unexpected=38361
INFO [04-09|12:45:42.786] Imported new state entries               count=1152 elapsed=9.015ms   processed=55305737 pending=3805   retry=0    duplicate=6655 unexpected=38361
INFO [04-09|12:45:44.678] Imported new state entries               count=768  elapsed=4.503ms   processed=55306505 pending=3631   retry=0    duplicate=6655 unexpected=38361
INFO [04-09|12:45:46.321] Imported new state entries               count=384  elapsed=2.469ms   processed=55306889 pending=3741   retry=0    duplicate=6655 unexpected=38361
INFO [04-09|12:45:51.464] Imported new state entries               count=768  elapsed=4.762ms   processed=55307657 pending=3990   retry=0    duplicate=6655 unexpected=38361
INFO [04-09|12:45:52.449] Imported new block headers               count=1    elapsed=6.735ms   number=7683755 hash=326df2…4be6ed
INFO [04-09|12:45:58.487] Imported new block headers               count=1    elapsed=5.572ms   number=7683756 hash=018fc4…cb0230

````

**Comment by schnitzlein** [comment]
Let me guess, it takes more time?
As mentioned in: https://github.com/ethereum/go-ethereum/issues/14338#issuecomment-490054375

**Comment by karalabe** [comment]
#
Syncing Ethereum is a pain point for many people, so I'll try to detail what's happening behind the scenes so there might be a bit less confusion.

The current default mode of sync for Geth is called fast sync. Instead of starting from the genesis block and reprocessing all the transactions that ever occurred (which could take weeks), fast sync downloads the blocks, and only verifies the associated proof-of-works. Downloading all the blocks is a straightforward and fast procedure and will relatively quickly reassemble the entire chain.

Many people falsely assume that because they have the blocks, they are in sync. Unfortunately this is not the case, since no transaction was executed, so we do not have any account state available (ie. balances, nonces, smart contract code and data). These need to be downloaded separately and cross checked with the latest blocks. This phase is called the state trie download and it actually runs concurrently with the block downloads; alas it take a lot longer nowadays than downloading the blocks.

So, what's the state trie? In the Ethereum mainnet, there are a [ton of accounts already](https://etherscan.io/chart/address), which track the balance, nonce, etc of each user/contract. The accounts themselves are however insufficient to run a node, they need to be cryptographically linked to each block so that nodes can actually verify that the account's are not tampered with. This cryptographic linking is done by creating a tree data structure above the accounts, each level aggregating the layer below it into an ever smaller layer, until you reach the single root. This gigantic data structure containing all the accounts and the intermediate cryptographic proofs is called the state trie.

Ok, so why does this pose a problem? This trie data structure is an intricate interlink of hundreds of millions of tiny cryptographic proofs (trie nodes). To truly have a synchronized node, you need to download all the account data, as well as all the tiny cryptographic proofs to verify that noone in the network is trying to cheat you. This itself is already a crazy number of data items. The part where it gets even messier is that this data is constantly morphing: at every block (15s), about 1000 nodes are deleted from this trie and about 2000 new ones are added. This means your node needs to synchronize a dataset that is changing 200 times per second. The worst part is that while you are synchronizing, the network is moving forward, and state that you begun to download might disappear while you're downloading, so your node needs to constantly follow the network while trying to gather all the recent data. But until you actually do gather all the data, your local node is not usable since it cannot cryptographically prove anything about any accounts.

If you see that you are 64 blocks behind mainnet, you aren't yet synchronized, not even close. You are just done with the block download phase and still running the state downloads. You can see this yourself via the seemingly endless `Imported state entries [...]` stream of logs. You'll need to wait that out too before your node comes truly online.

---

**Q: The node just hangs on importing state enties?!**

A: The node doesn't hang, it just doesn't know how large the state trie is in advance so it keeps on going and going and going until it discovers and downloads the entire thing.

The reason is that a block in Ethereum only contains the state root, a single hash of the root node. When the node begins synchronizing, it knows about exactly 1 node and tries to download it. That node, can refer up to 16 new nodes, so in the next step, we'll know about 16 new nodes and try to download those. As we go along the download, most of the nodes will reference new ones that we didn't know about until then. This is why you might be tempted to think it's stuck on the same numbers. It is not, rather it's discovering and downloading the trie as it goes along.

**Q: I'm stuck at 64 blocks behind mainnet?!**

A: As explained above, you are not stuck, just finished with the block download phase, waiting for the state download phase to complete too. This latter phase nowadays take a lot longer than just getting the blocks.

**Q: Why does downloading the state take so long, I have good bandwidth?**

A: State sync is mostly limited by disk IO, not bandwidth.

The state trie in Ethereum contains hundreds of millions of nodes, most of which take the form of a single hash referencing up to 16 other hashes. This is a horrible way to store data on a disk, because there's almost no structure in it, just random numbers referencing even more random numbers. This makes any underlying database weep, as it cannot optimize storing and looking up the data in any meaningful way.

Not only is storing the data very suboptimal, but due to the 200 modification / second and pruning of past data, we cannot even download it is a properly pre-processed way to make it import faster without the underlying database shuffling it around too much. The end result is that even a fast sync nowadays incurs a huge disk IO cost, which is too much for a mechanical hard drive.

**Q: Wait, so I can't run a full node on an HDD?**

A: Unfortunately not. Doing a fast sync on an HDD will take more time than you're willing to wait with the current data schema. Even if you do wait it out, an HDD will not be able to keep up with the read/write requirements of transaction processing on mainnet.

You however should be able to run a light client on an HDD with minimal impact on system resources. If you wish to run a full node however, an SSD is your only option.

**Comment by schnitzlein** [comment]
Thanks for the quick response Péter. :)
