### ISSUE TITLE
My main adress from my Ledger Nano S is not showing up in MEW or mycrypto

### ISSUE THREAD

**Issue by Falsetto286** [ethereum/go-ethereum#20945]
Need your help guys.
I have been using my ledger with MEW for the past 3years but since I updated firmware my main address does not show up in MEW/Mycrypto/LL anymore.
I tried looking for the address on findeth but noting to be found, its like my adress never existed.

I checked the wallet on etherscan and my funds are still there but I have no way to access.

I also tried different derivation paths but it still doesn't show up.

Hope you guys can help me out or all my eth will be lost in nirvana......

**Comment by ligi** [comment]
This does not sound like a geth issue - wondering why you open this issue here ..

**Comment by karalabe** [comment]
So, a few things. As Ligi mentioned, the Geth team cannot really help as we maintain the client, but we don't maintain the Ledger hardware wallets, not track its firmwares, so not much we can do.

That said, you might want to double check which firmware you updated from and to which to. Ledger changed their default derivation path a couple years back, but the old should still work if you explicitly request it.

Now, the other thing is that updating a hardware wallet is always a bit risky, because things can go wrong. That is why they always say to expect a failure and ensure you have you seed words written down. If you do however, then you can always regenerate the same address you had before, so you should be safe even if the device got bricked.

**Comment by Falsetto286** [comment]
I tried contacting but no response, could you please open a ticket and assist?

Thank you

________________________________
Von: Péter Szilágyi <notifications@github.com>
Gesendet: Montag, 20. April 2020 10:40
An: ethereum/go-ethereum <go-ethereum@noreply.github.com>
Cc: Falsetto286 <ryan_stalder@hotmail.com>; Author <author@noreply.github.com>
Betreff: Re: [ethereum/go-ethereum] My main adress from my Ledger Nano S is not showing up in MEW or mycrypto (#20945)


Closed #20945<https://github.com/ethereum/go-ethereum/issues/20945>.

**Comment by ligi** [comment]
you are really wrong here - please contact the ledger support
