### ISSUE TITLE
admin.getContractInfo seems to search for white space hash when given contract address.

### ISSUE THREAD

**Issue by colm** [ethereum/go-ethereum#2096]
admin.getContractInfo seems to search for white space hash when given contract address.

var address = "0x4db56c006f6d9e2edf742438c7a7dc032a5c3025"
admin.getContractInfo(address)

gives err: HashToHash: content hash not found for '0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470'

var address = "0x1194e966965418c7d73a42cceeb254d875860356"
admin.getContractInfo(address)

gives: err: HashToHash: content hash not found for '0x32e7a6a214206e5822d71def806a2f764c50fb8b612e1caafc11674040ff45d5'

is the hash of the string "" and is returned for many contract addresses. So i don't know what is causing this but it seems like a bug.

**Comment by karalabe** [comment]
Hmmm, those methods seem to be using natspec, which is AFAIK experimental stuff. Dunno why natspec got merged into the admin namespace though, should probably have gone into its own. Anyway, that aside, maybe @zelig has an idea?

**Comment by colm** [comment]
Thanks Karalabe, Just to note I used "geth --natspec console 2>> out.txt" enable netspec. As I found online. Not sure about experimental state.

**Comment by zelig** [comment]
@colm 
In the first case, the hash is indeed that of the empty string. 
This is because that contract does not exist, so its contract code is empty. 
Obviously, this is not very friendly, with the new RPC and modules, there will be a lot of improvement of errors like this.

In the second case however, the hash looked up is correct:

```js
address = "0x4db56c006f6d9e2edf742438c7a7dc032a5c3025"
web3.sha3(eth.getCode(address), {encoding:"hex"})
// "32e7a6a214206e5822d71def806a2f764c50fb8b612e1caafc11674040ff45d5"
```
which means you have not correctly registered your contract hash (or your transaction didn't make it) you can do it on the console with: 

```js
admin.register(eth.account[0], address, content_hash)
```

@karalabe I didn't know natspec was experimental. The whole roundtrip of creating, storing and retrieving contract Info is certainly not set in stone, but the standard seems solid to me.
