### ISSUE TITLE
Warn if `--networkid` refers to an existing network

### ISSUE THREAD

**Issue by adamschmideg** [ethereum/go-ethereum#20968]
If I run `geth --goerli`, it will set the networkid to 5 and it will configure a few other things. When, however, I run `geth --networkid 5`, it will run with an inconsistent configuration. It should either work the same as if specified goerli directly, or it should give a warning, something like `networkid 5 is reservered, use --goerli instead`.

**Comment by holiman** [comment]
Works as expected. Why would anyone set a networkid unless they know what they're doing?

**Comment by holiman** [comment]
I mean, there are unlimited number of crazy things you can do, since we allow a lot of configurability. Like, you can set your tcp port to 443, maybe to try to allow traffic through a firewall. Should we warn users that "there may be http traffic on that port" and "no, just because the port is 443, that doesn't mean it will serve https content".I'm thinking that users who use advanced options have a reason for doing so.

**Comment by karalabe** [comment]
I tend to agree with @holiman here.

It should most definitely not do the same thing as `--goerli`. If you want Görli, specify that. If you specified something different, it's to be expected that it will do something different.

The issue with printing a warning is what Martin mentioned, that it will be a never ending task of figuring out all the possible bad combinations people can dream up and try to be smart about them. Don't get me wrong, there are definitely flags where we can and already do more: e.g. we forbid setting insane cache limits that would OOM, we try to detect bad NTP configs, we reject invalid flags and RPC namespaces. However, these are things that many many people had trouble with, so they were worth the effort. The `--networkid` flag is nost something people use, or if they do use it, they run their private network and need it for that. Nobody seems to be complaining about it really to warrant special casing.
