### ISSUE TITLE
Feature request: Get internal transaction

### ISSUE THREAD

**Issue by tyrone98** [ethereum/go-ethereum#20978]
We want to migrate the node from parity to Geth. I tried to get the internal transaction with debug_traceTransaction。Unfortunately, debug_traceTransaction is unbearably slow. trace all transactions of one block may be spent 17-20s.  
Hope Geth can provide this function directly.

**Comment by karalabe** [comment]
Geth does have a call tracer if you specify `{tracer: 'callTracer'}` as a second option to the various trace methods. Tracing a single transaction is fine if you know what you're looking for, but if you by any chance want to trace the entire block, then doing it one tx at a time results in N^2 executions, because each trace needs to recompute its prestate from the start. In that case it's more optimal to trace the entire block in one go.

Geth does not auto-trace txs currently however, so there's no way to simply retrieve traces.
