### ISSUE TITLE
Geth dev mode: networkId should also set chainId

### ISSUE THREAD

**Issue by monokh** [ethereum/go-ethereum#21120]
The chainId and networkId for a local test network should match. Since dev mode is a quick and easy way to setup the dev network, it shouldn't need creating a custom genesis config.

#### System information

Geth version: 1.9.11-stable
OS & Version: OSX

#### Expected behaviour

Specifying `--networkId` should set the genesis `chainId`

#### Actual behaviour

The same chainId `1337` is used regardless of the networkId. A custom genesis config needs to be constructed.

#### Steps to reproduce the behaviour

1. geth --dev --networkId 33
2. See `ChainId` in the console `Initialised chain configuration` will be set to 1337

**Comment by karalabe** [comment]
Chain ID and network ID are different concepts. Whilst it might make sense to maybe have the network id default to the chain ID, but definitely not the other way around. We don't want the consensus rules to change due to some network flag.

Dev more also is just a quick way to run (unit) tests locally. If you are entering networking territory, just spin up a proper private network. Dev mode isn't meant for that and we should not make it smarter than it's supposed to be.

**Comment by monokh** [comment]
@karalabe Running tests is precisely the reason I'm running geth in dev mode actually. Only that I am unable to use the default chainId `1337`. I don't have any need for the networking, it's just that `networkId` is the only parameter in the command line that looked relevant. As I understand it, setting a custom genesis would be undoing a bunch of parameters that `dev` mode provides. 

Put simply, I'm just looking for a way to use a different chainId with dev mode.
