### ISSUE TITLE
rpc: support websocket keepalive in Client

### ISSUE THREAD

**Issue by natsukagami** [ethereum/go-ethereum#21126]
As of now, `go-ethereum`'s `rpc.Client` does not in any way expose the underlying `websocket.Conn`. This makes creating methods for connection keep-alive difficult (as sending `ping` is not possible).

I am wondering if there can be any support for either:
- Automatic pings (or even manual `Ping` functions).
- Exposing the underlying `websocket.Conn`.

I acknowledge that the Client does have built-in support for automatic retry, however this is still very cumbersome in the case of using `eth-subscribe`. We've had experience with Infura's websocket server which often closes connections even with active subscriptions (sometimes as often as 1.5 minute!) 
Right now our workaround is to proxy the websocket connection and inject pings in the middle, which is far from optimal.

#### System information

Geth version: v1.9.14

**Comment by fjl** [comment]
Out of all the option, I think I prefer 'automatic ping'. Exposing the connection is messy because of the automatic reconnect. Exposing a `Ping` method is weird because it would only work on WebSocket.

I'm not 100% what the best way to implement this would be. We can probably fit the ping into client by starting an additional background goroutine when opening the websocket connection.

**Comment by fjl** [comment]
I implemented this as a PoC in #21142

**Comment by fjl** [comment]
The fix is now merged.
