### ISSUE TITLE
Connecting a HTTPS WebAPP to Ethereum

### ISSUE THREAD

**Issue by lfamorim** [ethereum/go-ethereum#2121]
I'm really really excited on how web3.js and Ethereum JSON RPC can change the web forever and I will start using to spread it to the world.

I will be glad to know how I could make the communication with Ethereum client. It's because my application are served in SSL (https://www.harlan.com.br/) and the Ethereum runs locally without SSL. Did you guys pretend spread Ethereum only at Mist? Good luck with that! Will be a way more simple if the web application ask for permission on SSL SOCKET like https://local.ethereum.org:8489/ witch resolves at 127.0.0.1. It is on ROADMAP? How could I help? Where I can find the things I need to change in the source?

![screenshot from 2016-01-13 14 56 22](https://cloud.githubusercontent.com/assets/195014/12301182/dab33432-ba05-11e5-8120-cb9741dc5ec5.png)

http://code.google.com/p/google-web-toolkit-doc-1-5/wiki/FAQ_SOP
https://en.wikipedia.org/wiki/Cross-origin_resource_sharing

Someone against that?

https://github.com/aaw/maybe_tls
https://github.com/ethereum/go-ethereum/blob/465e810c66ccee49410ea34d08102a82ce7b48a5/rpc/comms/http.go#L176

Best regards,
Lucas Fernando Amorim.

**Comment by tgerring** [comment]
For this to work, it requires the user to be running a local node configured to serve RPC requests locally, which is targeted at developers and unlikely to be a common case in the future. Instead, solutions like browser plugins or [MetaMask](https://metamask.io) will likely be adopted, in addition to Mist and invariants running on multiple OSs.

What use-case do you see for Geth supporting TLS over HTTP?

**Comment by karalabe** [comment]
I think the reason is simply to work around browser security policies. Chrome for example refuses to execute HTTP AJAX calls if the page itself was loaded over HTTPS. Still though I don't think interfacing a webpage directly with a locally running node is a good thing, neither can I imagine users allowing it, so I don't think this is really something we should be investing time in.

**Comment by ButterinUpTheButtHole** [comment]
@karalabe is smart. Ethereum clearly needs to use something more secure like TLS for communication. The best current option is to set up a dumby server that just takes HTTPS requests and relays them to a localhost Ethereum server.

**Comment by louisabraham** [comment]
Yes, for my app, I need to communicate with a geth client installed on a server (I sign the transactions locally in the browser before sending, but I can't connect because of the browser policy…
Now it doesn't work, but https://etherchain.org/api/web3/ used to serve a web3 API over https.
I think I will run a dumb proxy https server for the moment.

**Comment by SeaMonkey82** [comment]
I would also like to be able to connect to the HTTP RPC using HTTPS.
