### ISSUE TITLE
[code] freezer repair

### ISSUE THREAD

**Issue by zhangsoledad** [ethereum/go-ethereum#21211]
I have questions about
https://github.com/ethereum/go-ethereum/blob/v1.9.15/core/rawdb/freezer_table.go#L235-L236
```go
t.tailId = firstIndex.offset
t.itemOffset = firstIndex.filenum
```

should it be like this? 
```go
t.tailId = firstIndex.filenum
t.itemOffset = firstIndex.offset
```
I think the reason it goes fine for now, cause they all are 0 in general.

**Comment by rjl493456442** [comment]
Indeed, are you willing to open a PR to fix it?

**Comment by fadhlan1986** [comment]
what mean pr? can explain why I cant transfer my CRYPTO? any solution?

Regards

**Comment by holiman** [comment]
These will always be zero, until we start supporting deletion. The way deletion is meant to happen is

- N files can be deleted (no half-deletion of fies). 
  - When `N` files are deleted, `M` (where `M >N`) items are deleted. `M` is `itemOffset`. 
- The first index-entry is special, it contains `N` and `M`, today always zero.

However, looking into it now, I see that `M` is read from `fileNum`, which is limited to `65K`, being stored as a `uint16`. And `N` (file number) is read from `offset` (4 bytes). 

This means that we won't handle deletion of more than `65K` items. As far as I can see, this is an error. Since we haven't yet implemented tail-deletion, it should be pretty easy to fix. I need to look into it some more though, to be totally sure that there isn't some other nifty trick going on.
