### ISSUE TITLE
Is there any way to get the real block time?

### ISSUE THREAD

**Issue by SopmmmodII** [ethereum/go-ethereum#21223]
I have established a POA private chain, and now I want to get the real block time while the peroid is setted as 10 in genesis file. 
Could you please tell me what does "elapsed" mean in
**Successfully sealed new block            number=11770 sealhash=0b8088…bc8fc5 hash=e90338…430e39 elapsed=9.976s** ?
And, if there are some transactions being submitted into the blockchain, the "elapsed" changes to about 6 or 3.

**Comment by MariusVanDerWijden** [comment]
Elapsed denotes the time between the time the task was created (the block was assembled) and now. It denotes how much time the miner needed to mine the block.

The workflow is as follows, we create a block which means we assemble all transactions, run the transactions to get the state modifications, add some post finalization (for block rewards) and then we create a new task for the miner. This is the start time for elapsed. Since the miner is programmed to mine a block every 10 seconds, elapsed time should be around 10 - time to assemble the block.

If you now send transactions to the blockchain, assembling the time of the block takes longer. We have to execute all transactions which takes more time. This means the miner has less time to mine the block, which means elapsed will be lower.

If you want to get the real block time, you would have to write a small script to always retrieve two consecutive blocks and get the difference of their timestamp. There is afaik no place in geth where we assemble this information that can be queried from the outside.
