### ISSUE TITLE
Storage locality

### ISSUE THREAD

**Issue by iliastsa** [ethereum/go-ethereum#21233]
Hi everyone, lately I've been looking into geth sync performance together with @yanniss. I am reposting a message that @yanniss posted on Discord regarding some potential improvements on storage trie locallity:

> Hi all. I'm trying to understand geth archive-sync performance and have been browsing the code for the past couple of days. Am I correct in that there's no locality in how trie data are stored in LevelDB? That is, different nodes of the storage trie of a single account are in no way stored close-by, just at random locations, due to hashed keys? (I see there is locality for account snapshots, but I think these are not used during initial syncing?) 
> 
> I'm guessing improving locality has been tried and there are space savings in the DB (i.e., single representation of distinct tries) that are more valuable than encoding parts of the same trie with prefix-related keys? Have the savings of tries sharing representations been quantified? (I may want to work on improving locality, if people can tell me what has been tried already.)

**Comment by hmijail** [comment]
I have also been thinking about experimenting with a trie using locality-preserving hashes and some smartish encoding to try to keep related nodes nearby - though surely then hash collisions would be an issue. So, I'd also love to know what has already been tried.

**Comment by AusIV** [comment]
The way leveldb is structured there's really no feasible way to ensure node locality.

Leveldb is not a great database for storing trie structures. Each node has to be stored by its hash, and looking up a node from its hash takes 4-7 disk reads depending on available RAM.

I've outlined a data storage engine optimized for storing state tries [here](https://github.com/openrelayxyz/triedb/blob/master/docs/source/topic/design.rst), but I have no idea if I'll ever get around to actually building it. Even then I don't really worry about locality, so much as each trie node telling you exactly where in the file to go for the next node, rather than having to go back to an index to look up each node.

**Comment by holiman** [comment]
There's not much we can do to improve locality right now, we're pretty vested in the current storage-by-hash. The constraints might be lifted a bit when we start to use the snap protocol, giving us more freedom to experiment.

**Comment by yanniss** [comment]
Just wanted to say that this is still in our work queue and we are likely to re-open the issue in the next couple of months. We plan to implement a storage model that preserves locality, alongside a secondary index that offers the current access-by-node-hash required by `GetNodeData` and other current uses.
