### ISSUE TITLE
Rinkeby faucet transactions not going through

### ISSUE THREAD

**Issue by gaieges** [ethereum/go-ethereum#21280]
Seems as though I  had a lot of trouble getting my transactions to go through, but once I did, I was able to see it in the list of transactions that should have been taken place.  However, they 1) all appear red for the past 24 hours or so, and 2) don't actually correlate to a transaction on the rinkeby network as far as I can tell)

<img width="943" alt="Screen Shot 2020-06-30 at 4 09 52 PM" src="https://user-images.githubusercontent.com/6024347/86177448-4a4f9880-baec-11ea-8cc2-113aab20e677.png">

Would have expected two of those transactions in the screenshot to credit, but it seems there have been none: https://rinkeby.etherscan.io/address/0x3965f3d69eb0db34e710ed863f4bf83fbaa7e75a

**Comment by gaieges** [comment]
@karalabe seems like you may have worked with this in the past, any chance you have a second to take a look please?

**Comment by bgcdanang123** [comment]
NewIteratorWithPrefix(prefix []byte)
NewIteratorWithStart(start []byte)

**Comment by karalabe** [comment]
Thanks for the heads up!

Myeah. The discovery of the light client protocol was nuked, currently it can only do DNS discovery, which puppeth/faucet is not capable of. Because of this, the faucet can only ever talk to the bootnode. Hopefully a replacement will be shipped for the discovery or maybe I'll take a look at somehow hacking some more options into puppeth.

Either way, I've restarted the faucet and it's in sync now, so please try again. If it borked again, please notify me.

**Comment by gaieges** [comment]
Works beautifully, thanks!
