### ISSUE TITLE
Question about log output: stderr vs stdout

### ISSUE THREAD

**Issue by MysticRyuujin** [ethereum/go-ethereum#21405]
I'm trying to figure out why geth does not log to `stdout` but instead logs everything to `stderr` when using `supervisor` on Linux.

Basically I have a `supervisor` config that looks something like this:
```
[program:geth]
command=bash -c '<path_to_geth> <cli_flags>'
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/geth.err.log
stdout_logfile=/var/log/supervisor/geth.out.log
stopwaitsecs=300
```

Almost everything that geth normally outputs to the console when running interactively gets put into the `geth.error.log` file. I would think that normal console output would go into the `geth.out.log` file and errors would go into the `geth.error.log` file.

It's been like this for as long as I've been running geth and I always just kind of ignored it...so I'm just wondering why it might do that?

**Comment by meowsbits** [comment]
> At program start-up, three streams shall be predefined and need not be opened explicitly: standard input (for reading conventional input), standard output (for writing conventional output), and standard error (for writing diagnostic output). When opened, the standard error stream is not fully buffered; the standard input and standard output streams are fully buffered if and only if the stream can be determined not to refer to an interactive device.
> https://unix.stackexchange.com/a/331808/273201

- https://www.jstorimer.com/blogs/workingwithcode/7766119-when-to-use-stderr-instead-of-stdout

Geth logs to `stderr` because the log lines are diagnostic and error messages, not "conventional program output." 

Geth's normal job is not to generate conventional output, but to sync a blockchain, which is more-or-less limited doing network and database stuff, not printing any specific values to the `stdout` for storage or piping. You'll note that in the cases of some subcommands, however, stdout is used; eg. `geth dumpgenesis` prints to stdout because that (sub)program's job is to give you (well, stdout) that specific data.
