### ISSUE TITLE
Different size of database 

### ISSUE THREAD

**Issue by garysdevil** [ethereum/go-ethereum#21413]
Geth version: 1.9.9-stable
OS & Version: Linux
They have the same version and block height, but why they have different sizes of chaindata, why?
node01 552G 
node02 555G
node03 556G
node04 568G
Can we remove redundant data by command for saving storage if there are redundant data

**Comment by karalabe** [comment]
Resync them with fast sync and you'll get the slimmest possible database. You can keep the `ancients` folder within `chaindata` and that way you'll only download the state, not the chain all over. There's no other way currently to clear accumulated junk from the database.

**Comment by karalabe** [comment]
The size difference is due to different load. Geth pushes state to disk stuff after every hour of processing, if your node is more loaded, it can process less blocks in 1h, so it pushes to disk more frequently. We're working on some way to prune in the future, but there are some database migration steps involved first.
