### ISSUE TITLE
Geth doesnt respect --maxpeers 250

### ISSUE THREAD

**Issue by Gdocal** [ethereum/go-ethereum#21452]
Hi.
Here is my command line to start geth
"c:\Program Files\Geth\geth" --ws --wsport "8080" --wsorigins  "*" --wsapi  "db,eth,net,web3,admin" --syncmode fast --rpc --cache 8192 --txpool.globalslots 50000 --datadir.ancient "D:\gethdata\ancient" -http --http.port 8081 --maxpeers 250

I want to connect to as many nodes as possible. But my node never had more than 82 peers. 
What else I should check to force the node to respect my maxpeers settings.

I have static IP, but my node behind a router (Mikrotik), no port forwarding configured. 
Geth process now uses 11789 MB of RAM.
I have 100 Mbps internet connection speed, Windows 10 task manager says that I Send: 10 Mbps and Receive 15Mbps

**Comment by karalabe** [comment]
If you are blocking inbound connections (no port forward), then your node can only ever connect to other node that accept themselves inbound connects and also have free slots. Since more people are like you (we have 1500 publicly routed nodes vs. 9000 total nodes), there's a slot burden on the public nodes. 

As for network bandwidth, depends on what you are doing currently. Fast sync is heavy on the local disk too and heavy on latency, but light on bandwidth. We'll have a better version out later this year that is light on the disk and latency so it can use bandwidth better.

So, your node seems to work ok-ish, if you want more peers, you'll need to sort out port forwarding.

**Comment by Gdocal** [comment]
> If you are blocking inbound connections (no port forward), then your node can only ever connect to other node that accept themselves inbound connects and also have free slots. Since more people are like you (we have 1500 publicly routed nodes vs. 9000 total nodes), there's a slot burden on the public nodes.
> 
> As for network bandwidth, depends on what you are doing currently. Fast sync is heavy on the local disk too and heavy on latency, but light on bandwidth. We'll have a better version out later this year that is light on the disk and latency so it can use bandwidth better.
> 
> So, your node seems to work ok-ish, if you want more peers, you'll need to sort out port forwarding.

thank you for your answer. After I setup port forwarding I see that more peers get connected to my node.
