### ISSUE TITLE
Help. After Mist wallet deprecation , unable to see account content

### ISSUE THREAD

**Issue by arenaitmx** [ethereum/go-ethereum#21518]
Hi there,

   After mist  wallet deprecation I'm not able to see the content of the my wallet, I still have all the data inside, I raised a ticket on their repo but they redirect me here so I'm kindly asking for some help to sync the data of the my account and move the ethers to a another accounts. The content is part of my savings and not sure what to do I'm kind of desperate here, I'd really appreciate some help. Thanks in advance.

Regards,
Julio

**Comment by hadv** [comment]
I think it'd better to export your private key and then import to metamask

**Comment by holiman** [comment]
>  I'm not able to see the content of the my wallet

What does that mean? If you run `geth`, attach to it with `geth attach <path-to-ipc>` and, in the latter console, do `eth.accounts`, does it list you account?

Alternatively, do `geth console` and check `eth.accounts`. 

If you do see the account, it will list as `0` balance, but that's just because it takes quite some time to sync. However, if you can see the accounts, then that is step one.

**Comment by arenaitmx** [comment]
Hi there,
`I'm not able to see the content of the my wallet` , I see 0 balance. I can now login to the wallet but as it is not syncing I see no balance.
I've tried to import to metamask using the key but it requests a passphrase which I think I lost. 
I will try the `get attach ipc`

Thanks a lot guys!

**Comment by arenaitmx** [comment]
Hi. So I ran a docker container of the eth-go client using the same `.ethereum` data dir and I can see the accounts.

![image](https://user-images.githubusercontent.com/44147477/92397812-ad5d3d00-f0e4-11ea-8bad-79d39ead5076.png)

Additionally I see this:
`INFO [09-07|14:32:45.838] Initializing fast sync bloom             items=6853252 errorrate=0.000 elapsed=3m4.892s
WARN [09-07|14:32:47.929] Dropping unsynced node during fast sync  id=19f7695546b411b0 conn=dyndial addr=155.138.161.235:30303 type=Geth/v1.9.13-stable-cbc4ac26/linux-amd64/go1.13
WARN [09-07|14:32:50.500] Checkpoint challenge timed out, dropping id=166089c0e6ad14cf conn=dyndial addr=47.94.236.241:30303   type=Geth/v1.9.20-stable-979fc968/linux-amd64/go1.15
INFO [09-07|14:32:52.284] Looking for peers                        peercount=2 tried=72 static=0
INFO [09-07|14:32:53.350] Migrating ancient blocks                 count=100023 elapsed=2m38.598s
INFO [09-07|14:32:54.021] Initializing fast sync bloom             items=7101031 errorrate=0.000 elapsed=3m13.075s
INFO [09-07|14:33:02.041] Initializing fast sync bloom             items=7264023 errorrate=0.000 elapsed=3m21.095s`

**Comment by arenaitmx** [comment]
Hi all. I've been syncing but I found the below warn. It hangs there and it was almost a day doing that and no progress in syncing when this warning comes out.  Is there any way to avoid this?

eth.syncing
```.bash
{
  currentBlock: 4862947,
  highestBlock: 10821590,
  knownStates: 11862273,
  pulledStates: 11861792,
  startingBlock: 4853849
}

Log
WARN [09-08|14:44:30.734] Database compacting, degraded performance 
database=/root/.ethereum/chaindata
```

**Comment by holiman** [comment]
So, syncing takes quite a while, depending on your machine, any time from 6 hours (fast machine, lots of ram) to several days (consumer laptop). 

Note, though, that it's technically _not_ required to sync, in order to make transactions. For example, if you want to send ether off to some other address, the following would work: 

- Look up your account `nonce` on e.g. etherscan. As an example, let's use this account: https://etherscan.io/address/0x81409e4c1a55c034ec86f64a75d18d911a8b0071 . Last outgoing transaction is here: https://etherscan.io/tx/0xe0523c6ace3b265de8b8b5fec3b087b17425767397b1a62be2b9361cc68cd16c . Press "Click to see more", and you see the nonce for that transaction

![Screenshot_2020-09-08 Ethereum Transaction Hash (Txhash) Details Etherscan](https://user-images.githubusercontent.com/142290/92493765-2ea3f500-f1f5-11ea-9cae-cd6166d28cc0.png)

Ok, so now we know that the next nonce is `1196`. 

We also need to decide on a gasPrice. Check https://etherscan.io/gastracker , it currently reports `95gwei`. 

With that info, we'll create a transaction. For readability, I'll create a javascript file, and then load it into the console. 

`tx.js`:
```javascript
// Your account
var from="0x81409e4c1a55c034ec86f64a75d18d911a8b0071"
// Set destination account here
var recipient="0x81409e4c1a55c034ec86f64a75d18d911a8b0071"
// Set next nonce here
var nextNonce=1196
function makeTx(nonce, price,val){
	tx = {
		from: from,
		to: recipient,
		value: val,
		nonce: nonce,
		gasPrice:  web3.toWei(price, "gwei"),
		gas: 21000,
	}
	return tx
}
```

With that in place, we can start geth in non-syncing mode:

```
geth --nodiscover --maxpeers 0 console
...
...
> loadScript("tx.js")
```

And now you can invoke:

```
> var tx = makeTx(nextNonce, 95, 1)

 personal.signTransaction(tx,"your_password_here")
{
  raw: "0xf8668204........................................................................................................................................................................................................",
  tx: {
    gas: "0x5208",
    gasPrice: "0x161e70f600",
    hash: "0x5c0221299c25d7f2d762ed6a5fb4f281ed98922bf0503a1e615b39b96c45a6a1",
    input: "0x",
    nonce: "0x4ac",
    r: "...............",
    s: "............",
    to: "...........",
    v: "0x26",
    value: "0x1"
  }
}
```

The `raw` part is can be copied to e.g. mycrypto (https://mycrypto.com/pushTx) , to broadcast it onto the network. 

Now, some caveats

- All operations you perform are at your own risk. 
- Make sure to verify in particular `to`, and `gasPrice`,
- If the recipient is a contract wallet, you should specify maybe `34K` gas instead of `21k` gas.

**Comment by arenaitmx** [comment]
Hi. Thanks a lot for the detailed instructions! . I thought I need to sync in order to see balance. I've checked in etherscan and can't see any transaction from the accounts listed in my wallet (which is not true as I deposited some ether to those accounts), does that means accounts are empty ?. Thanks a lot for  your time and patience!

**Comment by holiman** [comment]
>  I thought I need to sync in order to see balance. I've checked in etherscan and can't see any transaction from the accounts listed in my wallet (which is not true as I deposited some ether to those accounts), 

Well, if you can't see any transactions _from_ the accounts, it just means you haven't sent anything _out_.

> does that means accounts are empty 

Not necessarily, if you have incoming transfers. It means your next `nonce` is `0`.
