### ISSUE TITLE
--networkid doesn't work

### ISSUE THREAD

**Issue by vietthang207** [ethereum/go-ethereum#21550]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.9.19`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
The docs at https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options list --networkid as a valid option. When running with --networkid 3, the node should sync with ropsten network. It works fine with --testnet and --ropsten

#### Actual behaviour
Node can't handshake with peers

#### Backtrace

````
[backtrace]
````

**Comment by vietthang207** [comment]
When running with --testnet and --ropsten there is a log line ```Starting Geth on Ropsten testnet...```. This line didn't show up when I run with --networkid 3

**Comment by MariusVanDerWijden** [comment]
Hey @vietthang207 we had several discussions about this already. See for example here: https://github.com/ethereum/go-ethereum/issues/20968
We came to the conclusion that the `--networkid` should only be used if you know what you're doing. It does not have any impact on the configuration you use to sync the chain. You choose the configuration by `--ropsten` or `--goerli`. The `--networkid` only sets the network id, it uses the default config for mainnet. That's why you can't sync properly.

@adamschmideg Maybe we should add an explanation to `--networkid` that it does not choose the chainconfig

**Comment by vietthang207** [comment]
Thanks for the clarification! I just think that the documentation need an update.
