### ISSUE TITLE
Ancient directory is too small

### ISSUE THREAD

**Issue by carlosfrancia** [ethereum/go-ethereum#21574]
In our company we run a full archive sync network. In total we are using around 4.9Tb of SSD storage and we are looking into some cost saving using the freezer feature. Looking into the potential saving we have noticed that our `chaindata/ancient` directory is only 150.7Gb and this is obviously a very small proportion of the entire network data.

According to the documentation freezer directory should contain data older than 3 epochs so we assumed that the ancient data would be much larger.

Shouldn’t ancient data directory be much larger and contains all the old data including archive?

#### System information

Geth version: `geth v1.9.15`
Args: `--cache=4096 --syncmode=full --gcmode=archive`
OS & Version:Linux

**Comment by karalabe** [comment]
The ancient folder only stores the chain (headers, blocks, uncles, receipts). State can't really be stored on an HDD. For an archive node, the freezer is not that useful since the crux of the data is the state. Unfortunately there's no way - currently at least - to meaningfully cut down on SSD usage.
