### ISSUE TITLE
There are 2 private keys leading to the same address key

### ISSUE THREAD

**Issue by quyenneo** [ethereum/go-ethereum#21628]
Hi Ethereum Development Team,

I found out 2 private keys that lead to the same address key.
This is a serious problem in the ethereum system.
I need to talk to the development team.
Please contact me.
ndqcoin@gmail.com

**Comment by Neurone** [comment]
Someone else better than me with the math can also say the probability of that, but yes, it can happen, different private keys can lead to the same address.

Public key comes from applying ECDSA to private key. Long address comes by applying Keccak-256 to public key. Ethereum address comes from the last 20 bytes of the long address. Quoting the [yellow paper](https://ethereum.github.io/yellowpaper/paper.pdf):

_For a given private key, **pr**, the Ethereum address **A(pr)** (a 160-bit value) to which it corresponds is defined as the
rightmost 160-bits of the Keccak hash of the corresponding ECDSA public key: **A(pr) = B96..255 KEC(ECDSAPUBKEY(pr))**_

**Comment by jiangshangqifeng** [comment]
> Hi Ethereum Development Team,
> 
> I found out 2 private keys that lead to the same address key.
> This is a serious problem in the ethereum system.
> I need to talk to the development team.
> Please contact me.
> [ndqcoin@gmail.com](mailto:ndqcoin@gmail.com)

Show your keys, or else, you are lying

**Comment by holiman** [comment]
I think there's an underlying misunderstanding here. The address in question matches the one used in this demo: https://lorenzograssia.com/business-online/2018/04/cosa-e-myetherwallet-e-come-settarlo/attachment/schermata-2018-04-05-alle-14-16-20/, and I seem to recall someone else also reported "finding" this same address. 

What appears to have happened, is that when running some particular demo/tutorial, this key is inserted into the keystore, and users mistakenly believe that they have found a collision, since it apparently actually was used on mainnet at some point in time.
