### ISSUE TITLE
Error while accessing ETH wallet

### ISSUE THREAD

**Issue by Kruason** [ethereum/go-ethereum#21756]
Hi all. How I can fix this error?

https://prnt.sc/v6ob7o

https://prnt.sc/v6yt6t

**Comment by ligi** [comment]
How was the key generated you try to use there? Please provide more details!

**Comment by karalabe** [comment]
Geth assumes that a correctly encoded key file contains a proper elliptic private key. Otherwise it crashes (not the best idea, but that's not relevant here). Your keyfile seems to contain a key that's not valid on an Ethereum network, hence why both Geth and that other program rejects it. As @ligi said above, please check how you generated/obtained the key in the first place, because it's not a valid key.
