### ISSUE TITLE
admin.addPeer not symmetric to admin.addTrustedPeer

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#21774]
These two methods should allow configuring persistent connections that have higher priority and guarantees than all the others. `addTrustedPeer` should ensure that a remote dial is always permitted (independent of limits) and `addPeer` should ensure that a dial is always attempted, if not connected yet.

Unfortunately, `addPeer` is limited by the node's maximum configured peer count, independent if the remote node is considered trusted or not. This is a problem, because if 2 nodes are fully saturated with peers, it makes it impossible to connect them as neither will dial from their own initiative.

The fix could be:

- Make `addPeer` (static peers) ignore the maximum allowance. This seems simpler, but it might break people's setup who've been adding peers via shared lists (especially on Ropsten), since all of a sudden they'd try to dial hundreds of nodes.
- Make `addTrustedPeer` (trusted peers) also have an effect on outboud dials, so that if a remote peer is trusted and we're attempting to dial it, it should not take into consideration the peer count limit.

Either solution would work, but one of them is needed, otherwise manual peering is not reliably possible.

Edit: An example is running a publicly routed node with only-manual connections. Ideally we'd run with `--nodiscover --maxpeers=0` and manually add peers, but the maxpeer limit prevents us from dialing out. Removing the maxpeer limit also permits inbound dials, so if the node was already in the DHT it will get insta-flooded (and then have no more room to manually dial). Connecting remotely to our node has the same fault that long running existing nodes will be already saturated networking wise so they'll not dial.

**Comment by fjl** [comment]
I changed the design of `addPeer` because it is a user-facing API. The addPeer function previously behaved as you request here, but had the unfortunate downside that listing, say, 500 nodes in the static-nodes.json file would create a lot of dial load.

> Removing the maxpeer limit also permits inbound dials, so if the node was already in the DHT it will get insta-flooded (and then have no more room to manually dial).

We discussed this in the issue triage call today, and the solution for such issues is regenerating the node key.

**Comment by holisticode** [comment]
Sorry to peruse this old thread again but I am stuck at an issue related to this.

I am optimizing some connections. I want validators to connect to specific other nodes only. So the maximum added peercount on top of MaxPeers would only be around 10. No overkill I suppose.

But when I try to `AddTrustedPeer` for my peers, and MaxPeers is reached (testing with a deliberate low MaxPeers), then the p2p server only adds the peer to `trusted[]` but not to the connection, because the peer is not added yet (not in `peers[]`). But if I add the peer first with `AddPeer`, then obviously this will be rejected because MaxPeers is reached.

Catch22. In other words I can't run dynamically `AddTrustedPeer`. Any suggestion about how to circumvent this?
