### ISSUE TITLE
../github.com/ethereum/go-ethereum/common/types.go:212:9: undefined: sha3.NewLegacyKeccak256

### ISSUE THREAD

**Issue by Jackie-Zhong** [ethereum/go-ethereum#21823]
go version is 
go version go1.14.4 linux/amd64

the go-ethereum source version i use is 
1.9.23
 or
 master

but all faile like this 
../github.com/ethereum/go-ethereum/common/types.go:212:9: undefined: sha3.NewLegacyKeccak256

how should i do

**Comment by Jackie-Zhong** [comment]
at last,i use 1.9.4 version that solve my problem。

**Comment by fjl** [comment]
Are you building go-ethereum using go modules? Please enable go modules to use an up-to-date version of golang.org/x/crypto/sha3 which contains the NewLegacyKeccak256 function.

To enable Go modules, set `GO111MODULE=on` in your environment.

**Comment by Jackie-Zhong** [comment]
> Are you building go-ethereum using go modules? Please enable go modules to use an up-to-date version of golang.org/x/crypto/sha3 which contains the NewLegacyKeccak256 function.
> 
> To enable Go modules, set `GO111MODULE=on` in your environment.

sure,i have my own golang.org/x/crypto/sha3,but the newest version like 1.9.23 of go-ethereum don't work for me.so i use the 1.9.4 version that solve my problem.

**Comment by fjl** [comment]
@Jackie-Zhong I'm trying to understand if your issue is solved. I cannot reproduce your issue, go-ethereum v1.9.23 builds successfully on my machine. 

If your issue is fixed, please close.

If your issue is not fixed, please provide more details like the Go version you are using (`go version` output) and your build environment (`go env` output).

**Comment by Jackie-Zhong** [comment]
had fixed problem.
