### ISSUE TITLE
estimateGas but Error:insufficient funds for transfer

### ISSUE THREAD

**Issue by boy-good** [ethereum/go-ethereum#21851]
Hi there,

#### System information

Geth version: `geth 1.9.23`
OS & Version: Linux

![image](https://user-images.githubusercontent.com/39320533/99224484-5df06700-2821-11eb-9c9f-edc1f3bc2c08.png)

What‘s wrong？How to deal this problem. I estimateGas other address successful.

**Comment by karalabe** [comment]
Recent (last half a year) versions of Geth take into consideration your total balance when estimating the gas so that you don't end up attempting to spend more funds than you have. In your example, you've specified your entire balance to send (`value` field), which leaves you with 0 funds to cover the transaction fees.

**Comment by boy-good** [comment]
> Recent (last half a year) versions of Geth take into consideration your total balance when estimating the gas so that you don't end up attempting to spend more funds than you have. In your example, you've specified your entire balance to send (`value` field), which leaves you with 0 funds to cover the transaction fees.

Thanks. I got!!!
I used version 1.9.9 but last week i update to 1.9.23 and get this error.
