### ISSUE TITLE
Transaction ordering within a block should be non-deterministic.

### ISSUE THREAD

**Issue by Thrasymachus01** [ethereum/go-ethereum#21965]
# Rationale

76% of eth nodes are currently running Geth where the default transaction ordering is deterministic - [SortByPriceAndNonce()](https://github.com/ethereum/go-ethereum/blob/290e851f57f5d27a1d5f0f7ad784c836e017c337/core/types/transaction.go#L372) 

`SortByPriceAndNonce()` orders transactions by gas fees (while still preserving nonce ordering).

It means an attacker can view transactions that have a high chance of being included in the next block and frontrun that transaction by simply broadcasting a transaction with a higher gas fee. Since 76% of nodes run geth the probability that he will run a successful attack is:
`76% chance - chance of his tx being included in the next block - the chance of victim's tx being included in the next block`

This attack can easily be avoided by adding some sort of randomness to the way tx's are sorted in a block. Frontrunning and deterministic ordering of tx's holds more security vulns than just at uniswap (for obvious reasons, i won't disclose here).

# Implementation

Add a randomizer function (instead of sorting by gas fees) to sort transactions that still preserves nonce ordering.

**Comment by DbIsFantastic** [comment]
First of all, it is very hard to guarantee security in a distributed system. Shuffle doesn't solve the problem, because the attacker could send tons of transactions. Actually, front-run attack is actually the business of DApp, I don't know whether geth should take care of it. These AMA swap protocols actually encourage arbitrage to keep the price fair. 
Let's think about why front-run transactions could make a profit. 
The front-runner first catches a user's normal swap transaction, for example, swap 100 ETH to 60,000 XXX(any coin exists in the uniswap), with gasprice 100GWei. Then the front-runner first sends a tx with a little higher gasprice, 101GWei, so that this tx could be placed before the normal transaction to make the user trade with a much bigger slippage. And then the front-runner sends another tx to swap XXX back ETH, so that he could make a profit. But the risk of the front-runner is that the slippage created by his first transaction will be flattened easily by arbitragers, since the front-runner must send two txs with different gasprice, which are not atomic, then the front-runner won't get any profits, and even lost some money. In this way the normal user will not be affected at all. But front-run txs still happen, why? The real reason is that there is usually only 1 pool for this pair so that arbitragers couldn't work as expected by AMA protocol. Why not suggesting adding more pool for the coins and keep AMA protocol works as expected?

**Comment by holiman** [comment]
There are a couple of things at play here. 
First of all, geth cannot dictate a policy that would not benefit miners. If we order transaction to _not_ maximise miner profit, rational miners will just modify geth, or use some fork, to ensure that profit is maximised. So highest gas fee wins. 

With the release of [Red Janey](https://github.com/ethereum/go-ethereum/releases/tag/v1.9.19), we did make one big change, in that we removed the randomization, and made the ordering first as price, then as fifo. This removes the incentive for back-runner to flood the network with transactions in order to back-run a transaction. 

But, as for front-running, not much we can do at the infrastructure layer.

**Comment by rjl493456442** [comment]
Personally, I agree with @holiman's point. We introduce deterministic sorting which can remove most of the useless transactions. Even with the non-deterministic sorting the front-running actually won't be fixed(e.g. with some nonce checking in the arbitrage contract?) but It will make back-running worse.

**Comment by Thrasymachus01** [comment]
@holiman It's possible to still get the top ~100 most profitable transactions, select them for inclusion in the block, randomize them and then sort them by nonce.

The miner's won't lose any profit like this but the order of the transactions within the block are randomized.

**Comment by rjl493456442** [comment]
@Thrasymachus01 Yes, but it's still hurt for the back-running. They will send A LOT of transactions with the same price to flood the network.
