### ISSUE TITLE
Ask for help. When geth runs to 1.1 million blocks, it is difficult to change and cannot be started

### ISSUE THREAD

**Issue by bitbeb** [ethereum/go-ethereum#22013]
Ask for help. When geth runs to 1.1 million blocks, it is difficult to change and cannot be started
When geth runs to 1.1 million blocks, it changes the fixed value of difficulty 18888, and it has been running for 2 months, reaching 6.5 million blocks. After restarting the node, it cannot start geth normally, and it rolls back to 1.1 million blocks, resulting in data loss.
Reward 3eth to solve this problem:
requirement:
1. Use the backup image (6.5 million full block data) to resume normal startup and mining
2. Other nodes can synchronize blocks
thank you!

**Comment by bitbeb** [comment]
info@betbeb.com
Reward 5eth to solve this problem:
requirement:

Use the backup image (6.5 million full block data) to resume normal startup and mining
Other nodes can synchronize blocks
thank you!

**Comment by rjl493456442** [comment]
Are you running the Geth in the private network?  You may need to check your chain config. In the mainnet there are some difficulty bomb enabled.

**Comment by bitbeb** [comment]
Because the geth difficulty value was changed to 18888, it was unable to start

**Comment by holiman** [comment]
The difficulty formula, according to the YP, has a minimum difficulty of `131072` (`0x20000`). If you modify geth to go below that, the outcome of the difficulty formula is undefined. 

> Reward 3eth to solve this problem

This is an issue tracker, not a bounty-page. If you want to commission some work, look into e.g. gitcoin.  

I'm closing this, since you're not actually reporting a bug in go-ethereum, but a bug in a modified version (where the bug clearly stems from the modifications made). Feel free to reopen if I misunderstood something here.
