### ISSUE TITLE
Update go modules

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#22050]
`gomodctl check`

We should probably update some of these
```
                  MODULE                 |                CURRENT                |        LATEST          
-----------------------------------------+---------------------------------------+------------------------
  github.com/aws/aws-sdk-go              | v1.25.48                              | v1.36.12               
  github.com/golang/protobuf             | v1.4.2                                | v1.4.3                 
  github.com/olekukonko/tablewriter      | v0.0.2-0.20190409134802-7e037d187b0c  | v0.0.4                 
  github.com/rs/cors                     | v0.0.0-20160617231935-a62a804a8a00    | v1.7.0                 
  github.com/go-stack/stack              | v1.8.0                                | v1.8.0                 
  github.com/karalabe/usb                | v0.0.0-20190919080040-51dc0efba356    | no version available   
  github.com/steakknife/bloomfilter      | v0.0.0-20180922174646-6819c0d2a570    | no version available   
  github.com/deckarep/golang-set         | v0.0.0-20180603214616-504e848d77ea    | v1.7.1                 
  github.com/gballet/go-libpcsclite      | v0.0.0-20190607065134-2772fd86a8ff    | no version available   
  github.com/wsddn/go-ecdh               | v0.0.0-20161211032359-48726bab9208    | no version available   
  golang.org/x/time                      | v0.0.0-20190308202827-9d24e82272b4    | no version available   
  github.com/dop251/goja                 | v0.0.0-20200721192441-a695b0cdd498    | no version available   
  github.com/mattn/go-isatty             | v0.0.5-0.20180830101745-3fb116b82035  | v0.0.12                
  github.com/cloudflare/cloudflare-go    | v0.10.2-0.20190916151808-a80f83b9add9 | v0.13.6                
  github.com/holiman/uint256             | v1.1.1                                | v1.1.1                 
  golang.org/x/text                      | v0.3.3                                | v0.3.4                 
  github.com/mattn/go-colorable          | v0.1.0                                | v0.1.8                 
  gopkg.in/olebedev/go-duktape.v3        | v3.0.0-20200619000410-60c24ae608a6    | no version available   
  github.com/edsrzf/mmap-go              | v0.0.0-20160512033002-935e0e8a636c    | v1.0.0                 
  github.com/fjl/memsize                 | v0.0.0-20180418122429-ca190fb6ffbc    | no version available   
  github.com/rjeczalik/notify            | v0.9.1                                | v0.9.2                 
  gopkg.in/urfave/cli.v1                 | v1.20.0                               | v1.20.0                
  github.com/huin/goupnp                 | v1.0.0                                | v1.0.0                 
  github.com/status-im/keycard-go        | v0.0.0-20190316090335-8537d3370df4    | no version available   
  github.com/cespare/cp                  | v0.1.0                                | v1.1.1                 
  github.com/davecgh/go-spew             | v1.1.1                                | v1.1.1                 
  github.com/fatih/color                 | v1.3.0                                | v1.10.0                
  github.com/golang/snappy               | v0.0.3-0.20201103224600-674baa8c7fc3  | v0.0.2                 
  github.com/hashicorp/golang-lru        | v0.5.4                                | v0.5.4                 
  github.com/jedisct1/go-minisign        | v0.0.0-20190909160543-45766022959e    | no version available   
  github.com/shirou/gopsutil             | v2.20.5+incompatible                  | v3.20.11+incompatible  
  github.com/tyler-smith/go-bip39        | v1.0.1-0.20181017060643-dbb3b84ba2ef  | v1.1.0                 
  github.com/VictoriaMetrics/fastcache   | v1.5.7                                | v1.5.7                 
  github.com/aristanetworks/goarista     | v0.0.0-20170210015632-ea17b1a17847    | no version available   
  github.com/google/gofuzz               | v1.1.1-0.20200604201612-c04b05f3adfa  | v1.2.0                 
  github.com/julienschmidt/httprouter    | v1.1.1-0.20170430222011-975b5c4c7c21  | v1.3.0                 
  github.com/prometheus/tsdb             | v0.6.2-0.20190402121629-4f204dcbc150  | v0.10.0                
  github.com/graph-gophers/graphql-go    | v0.0.0-20191115155744-f33e81362277    | no version available   
  github.com/syndtr/goleveldb            | v1.0.1-0.20200815110645-5c35d600f0ca  | v1.0.0                 
  gotest.tools                           | v2.2.0+incompatible                   | v2.2.0+incompatible    
  github.com/Azure/azure-storage-blob-go | v0.7.0                                | v0.12.0                
  github.com/btcsuite/btcd               | v0.0.0-20171128150713-2e60448ffcc6    | v0.21.0-beta           
  github.com/naoina/toml                 | v0.1.2-0.20170918210437-9fafd6967416  | v0.1.1                 
  github.com/peterh/liner                | v1.1.1-0.20190123174540-a2c9a5303de7  | v1.2.1                 
  github.com/influxdata/influxdb         | v1.2.3-0.20180221223340-01288bdb0883  | v1.8.3                 
  github.com/jackpal/go-nat-pmp          | v1.0.2-0.20160603034137-1fa385a6f458  | v1.0.2                 
  github.com/stretchr/testify            | v1.4.0                                | v1.6.1                 
  gopkg.in/natefinch/npipe.v2            | v2.0.0-20160621034901-c1b8fa8bdcce    | no version available   
  github.com/docker/docker               | v1.4.2-0.20180625184442-8e610b2b55bf  | v20.10.1+incompatible  
  golang.org/x/crypto                    | v0.0.0-20200622213623-75b288015ac9    | no version available   
  github.com/gorilla/websocket           | v1.4.1-0.20190629185528-ae1634f6a989  | v1.4.2                 
  github.com/pborman/uuid                | v0.0.0-20170112150404-1b00554d8222    | v1.2.1                 
  golang.org/x/sys                       | v0.0.0-20200824131525-c12d262b63d8    | no version available   
-----------------------------------------+---------------------------------------+------------------------
                                                     NUMBER OF MODULES           |          53            
                                         ----------------------------------------+------------------------
```

**Comment by MariusVanDerWijden** [comment]
Update | package | version | comment
---------| -------- | -------- | ---------
no | github.com/cespare/cp | v1.1.1 | introduces overwrite functions to the copy functions
maybe | github.com/fatih/color | v1.10.0 | introduces new colors, vendors in dependencies, updates a dependency which had a index out of bounds in windows, other windows issues (https://github.com/fatih/color/pull/115)
yes  | github.com/golang/protobuf  | v1.4.3  | fixed an error with marshalling of time.Duration
yes  | github.com/stretchr/testify  | v1.7.0  | crazy amount of miner and major fixes (https://github.com/stretchr/testify/milestones?state=closed)
no  | github.com/cloudflare/cloudflare-go |  v0.13.7 |  many major and minor fixes (https://github.com/cloudflare/cloudflare-go/compare/v0.10.2...v0.13.7) afaict none that relate to our use case
no  | github.com/prometheus/tsdb |  v0.10.0 |  many changes, none related to the filelock afaict, repo was archived, might be good to move to a small dependency because we use it just for locking the datadirectory in `node/node.go` and `core/rawdb/freezer.go`.
no  | github.com/rjeczalik/notify  | v0.9.2  | added a go mod file
idk |  github.com/shirou/gopsutil  | v3.20.12+incompatible |  Nope not going there...
no  | github.com/Azure/azure-storage-blob-go  | v0.12.0  | minor fixes, increased file size
no  | github.com/deckarep/golang-set  | v1.7.1  | tiny fixes in code not used by us 
yes  | github.com/gorilla/websocket  | v1.4.2  | potential dos fix (https://github.com/gorilla/websocket/commit/5b740c29263eb386f33f265561c8262522f19d37)
yes |  github.com/fjl/memsize  | -  | no version avail accounting fix, speed increase
maybe |  github.com/dop251/goja  | no version avail |  multiple panic fixes, seem to merging a lot lately maybe not good to update right now
yes  | github.com/graph-gophers/graphql-go |  no version avail  | multiple panic and sigsegv fixes
yes  | github.com/influxdata/influxdb  | v1.8.3  | we can either switch 1.8.3 or 2.0.3 both contain many improvements and bug fixes, I would suggest to update to 1.8.3 
no  | github.com/jackpal/go-nat-pmp |  v1.0.2  | only doc typo fixes
yes  | github.com/pborman/uuid  | -  | this package became only a wrapper around https://github.com/google/uuid, we should either update this or directly switch to the google maintained uuid
no  | github.com/status-im/keycard-go  | -  | no major fixes only small stuff
inline  | github.com/aristanetworks/goarista  | -  | we only use the monotonic package, which is really tiny
maybe  | github.com/aws/aws-sdk-go |  v1.36.29 |  we use it only in the devp2p dns package so it doesn't matter that much, but there have been > 1000 commits since our version with more than 1mm loc added.
no  | github.com/docker/docker | -  |  we only use the `reexec` package from docker which wasn't updated since 2018
yes  | github.com/edsrzf/mmap-go  | v1.0.0  | fixes an issue we had in geth(https://github.com/edsrzf/mmap-go/pull/14)
maybe |  github.com/mattn/go-isatty  | v0.0.12  | has some fixes to support more linux based os's, I think we should only update if someone complains
no  | github.com/olekukonko/tablewriter  | -  | nothing critical, only updates to powerpc archs
no |  golang.org/x/text | - |  no fixes to `norm` package which we use
yes  | github.com/rs/cors |  v1.7.0  | fixes to adhere to cors standard (release is 1 1/2 y.o)
no  | golang.org/x/crypto  | -  | only speed improvements in ssh, doc fixes, small fixes in packages not used by us
yes |  github.com/btcsuite/btcd  | v0.20.0  | small fix to signing, dos bug in recovery, speed improvements
no  | github.com/julienschmidt/httprouter  | - |  only small fixes to path parsing (we use it only in simulations)
maybe |  github.com/mattn/go-colorable  | v0.1.8 |  avoids an index out of bounds on windows
no  | github.com/peterh/liner  | -  | only small fixes
maybe  | github.com/tyler-smith/go-bip39  | - | fixes an evaluation problem when creating a new mnemonic + add czech

**Comment by holiman** [comment]
Re `github.com/aws/aws-sdk-go` , if aws upstream changes their APIs, and we fail to do the corresponding updating of the client, we'll notice only when our discovery crawler starts failing to update the route53 dns entries for ethdisco. Might be worth staying on top of -- what do you say, @fjl ?

**Comment by holiman** [comment]
Re github.com/prometheus/tsdb , the repo was archived, and merged into https://github.com/prometheus/prometheus/tree/master/tsdb/. We're only using this pretty small package: https://github.com/prometheus/prometheus/tree/master/tsdb/fileutil , and yeah, really _only_ `fileutil.Flock`. Seems non-trivial to inline though, because it's several platform-dependent files. 

I'd be in favour of updateing that to use the new repo.
