### ISSUE TITLE
How to make geth keep states for the last 10000 blocks instead of 128?

### ISSUE THREAD

**Issue by forencen** [ethereum/go-ethereum#22091]
# geth version
```
Geth
Version: 1.9.23-stable
Git Commit: 8c2f271528f9cccf541c6ea1c022e98407f26872
Git Commit Date: 20201015
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.3
Operating System: linux
GOPATH=
GOROOT=go
```
# ubuntu version
`Ubuntu 18.04.5 LTS`

# node info
run : `geth --rpc --rpcapi web3,eth,net,txpool,admin,personal,debug --rpcaddr 0.0.0.0 --rpcport 8545 --datadir "/disk/eth/data" --syncmode "full"`

node model: `full-sync with pruning`

```
> eth.blockNumber
11554317
```

# my question

## reqeust parmas

```
{
    "jsonrpc": "2.0",
    "method": "debug_traceBlockByNumber",
    "params": [
        "0xb04d45",
        {"tracer": "callTracer"}
    ],
    "id": 1
}
```

## response

```
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32000,
        "message": "required historical state unavailable (reexec=128)"
    }
}
```

I checked the [documentation](https://geth.ethereum.org/docs/dapp/tracing), but it’s still not clear.

I try to use like this：

```
{
    "jsonrpc": "2.0",
    "method": "debug_traceBlockByNumber",
    "params": [
        "0xb04d45",
        {"tracer": "callTracer", "reexec": 500}
    ],
    "id": 1
}
```

still have problems:
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32000,
        "message": "required historical state unavailable (reexec=500)"
    }
}
```

I don't know if it is used correctly.

and

How to make geth keep states for the last 10000 blocks instead of 128?

Thank you in advance

**Comment by MariusVanDerWijden** [comment]
You can just set reexec to 10.000
```
{
    "jsonrpc": "2.0",
    "method": "debug_traceBlockByNumber",
    "params": [
        "0xb04d45",
        {"tracer": "callTracer", "reexec": 10000}
    ],
    "id": 1
}
```

**Comment by forencen** [comment]
thank you for your help

when I sent this request: 
```
curl -X POST --data '{"jsonrpc": "2.0", "method": "debug_traceBlockByNumber", "params": [ "0xb04d45", {"tracer": "callTracer", "reexec": 10000}], "id": 1}' -H 'content-type:application/json;'  http://127.0.0.1:8545

curl: (52) Empty reply from server
```
Every time I request, the server takes a long time to process.

But I need a lot of blocks trace information


everytime I use this request, I have to wait a long time. Isn't there a global configuration to replace 128?

**Comment by holiman** [comment]
Unfortunately not. This is not a trivial problem to solve -- in order to keep 10K untouched, it requires us to keep 10K states in memory -- because the pruner is in-memory, and thus in order to do _any_ pruning, we'd have to keep 10K+ states in memory. 
So, that probably won't work. And as long as we only have in-memory pruning and no disk-based pruning, the methods to achieve what you want is either reexec or to simply disable pruning, by using `gcmode=archive`. 

You can do a fast-sync + `gcmode=archive`, and if it eventually grows too big (because it _will_ grow fast without pruning), you can just wipe it all, do a fresh sync and start over. 

There's really nothing actionable for us here, so I'll close this ticket.

**Comment by nuliknol** [comment]
> thank you for your help
> 
> when I sent this request:
> 
> ```
> curl -X POST --data '{"jsonrpc": "2.0", "method": "debug_traceBlockByNumber", "params": [ "0xb04d45", {"tracer": "callTracer", "reexec": 10000}], "id": 1}' -H 'content-type:application/json;'  http://127.0.0.1:8545
> 
> curl: (52) Empty reply from server
> ```
> 
> Every time I request, the server takes a long time to process.
> 
> But I need a lot of blocks trace information
> 
> everytime I use this request, I have to wait a long time. Isn't there a global configuration to replace 128?

yeah, there is a global configuration, the file name is `core/blockchain.go` and the constant is:

`  TriesInMemory       = 128`

but who knows how much states it is going to hold in RAM. Geth has lots of memory management issues. Probably the devs should write a custom allocator for Golang. I have been running `import` command and every 3 hours I need to restart `geth` because it blows out the RAM. There is memory leak somewhere in the code and it eats up all ram in a few hours. Probably some funciton needs a resource-cleaning `defer{}` to be added, but who knows , I am not here to do other's job. 

Traces are going to consume all resources of your server because every instruction is added to the trace object (which probably you don't need), you need to hack into the EVM to extract what you need , it is easy, you just need to modify two files, the `core/vm/evm.go` and `core/vm/instructions.go` . Then you can modify `core/state_transition.go` and dump all the collected data to a file. Do the data collection into the `EVM` object.

For archival node you need about 6 terabytes right now, but in March it is going to be needed 8 terabytes. So, you are going to run out of space if you set it up. Also run out of money. But there is a trick. You can set up Linux's kernel module called `bcache` and for an SSD of 1TB it will LRU-cache all the important data and accelerate the processing a lot. It is still slow, but it works and it syncs. And with small amount of resources you can get your archival node for development. 

@forencen
