### ISSUE TITLE
Just launched geth develop - send tx does not prompt to enter pass for locked accounts

### ISSUE THREAD

**Issue by jambtt** [ethereum/go-ethereum#2224]
Instead I just got this:
{
code: -32000,
message: "account is locked"
}

win7 64bit

**Comment by bas-vk** [comment]
This is intentional. The reason is that the console can be attached to an external node. This introduces a couple of security issues.
1. If you are asked for your password it would be send plain text to the remote node. This is not desirable and an unexpected side effect for most users.
2. An unlocked account in the node is current node wide unlocked. That means once an account is unlocked anyone who can submit a transaction to the node can use the unlocked account to sign possible malicious transactions/data.

Therefore we are moving to a new model where the console can be seen as an ordinary DApp which has it own local account management. This would allow you to keep your keys on the local machine and submit signed transaction to an external node, not necessary a node that you manage. It would also allow you to use the console in combination with any ethereum node that supports the necessary RPC interface. This requires a bit of refactoring but when done you will be prompted for the password again without any of the security issues.

**Comment by obscuren** [comment]
We're targeting the new console suite for 1.6
