### ISSUE TITLE
How to estimate size of blockchain download

### ISSUE THREAD

**Issue by Mithrandir2k18** [ethereum/go-ethereum#22303]
I just installed the package from pacman, created a new wallet and started the download(with --fast and a large cache). Now the question is, how big is the download going to be? Does it check if I have enough diskspace?

If that information is online somewhere, the tool could check if there's enough disk space before starting that download. Is that the case? And if not, how can I estimate if I have enough available space?

And is there a way to download the blockchain to a different location/partition/NAS?

**Comment by MariusVanDerWijden** [comment]
We can not estimate in the software how much disk is going to be needed as it varies a lot depending on your sync speed. Generally around 350 GB are needed for the initial sync, but I would suggest an ssd with at least 1 tb since the node grows quickly once it was synced. The node can not check if there is enough space before starting the download. But it will stop if the space wasn't enough. In the future such questions are better suited to the ethereum stackexchange https://ethereum.stackexchange.com/
