### ISSUE TITLE
Open Files reported by LSOF very high on Ubuntu 20.04

### ISSUE THREAD

**Issue by stephenhodgkiss** [ethereum/go-ethereum#22356]
#### System information

AMD EPYC 32 Cores
256GB RAM
1TB Samsung 970 Evo Plus
 
Geth version: 1.9.25-stable
OS & Version: Ubuntu 20.04.2 LTS
Commit hash : (if `develop`)

#### Expected behaviour

open files should be released or at least be a lower number

#### Actual behaviour

Start GETH inside a screen with: -

geth --syncmode "fast" --nousb --ws --ws.api eth,net,web3 --ws.addr 127.0.0.1 --datadir chaindata/geth/ --datadir.ancient /root/ancient --cache 235520 --maxpeers 100 --ws.port 8646 --http.port 8645 --cache.trie 60

lsof | awk '{ print $2; }' | uniq -c | sort -rn | head

result after just a few minutes:

3272620 1305177 (GETH process running under a SCREEN)
    413 860065
    413 859743
    413 859410
    322 860278
    322 860265
    322 860253
    322 860235
    322 860202
    322 860181

#### Steps to reproduce the behaviour

closed GETH tidily and then restarted .... Number of open files reported by LSOF increases very quickly

**UPDATE February 22, 2021**

Installed the latest unstable release
Version: 1.9.26-unstable

Repeated the same test and after 5 minutes of starting GETH as before, LSOF command reports nearly 5 million open files.

**Comment by MariusVanDerWijden** [comment]
I don't think you count the open files correctly.
Your command (`lsof | awk '{ print $2; }' | uniq -c | sort -rn | head`) produces ~1.6 million for my geth process while `lsof -p <pid> | wc -l` produces ~67.000. 
Given that the `.ethereum` folder on my machine has ~70.000 files I think the latter is more accurate. 
I also tried `lsof -P -n -p <pid> | wc -l` which produces a similar number of ~67.000.

This is still a lot of open file descriptors, but this is due to the way data is handled by go-leveldb.

**Comment by stephenhodgkiss** [comment]
Thanks @MariusVanDerWijden 

Both your commands return the same number of 68600.

**Comment by stephenhodgkiss** [comment]
On a different note, the CPU of mine is capable of running 64 threads. 

Running just 30 threads and accessing random addresses (getBalance) to try to simulate a real-world test, the maximum it can handle seems to be around 6 milliion per minute. Increasing or decreasing the number of threads seems to indicate that it has reached its peak, even though I have tried to configure the Trie to be all in memory.

I chose the getBalance function because I understood that this call would use the Trie cache.

Does anyone have any input on this and how to further improve the performance?

**Comment by karalabe** [comment]
I'm going to close this issue since the original post was solved.

For performance improvements you can play with cache sized, RAM, thread counts, but at the end of the day we don't have a guide on how to max out your node. If you can pinpoint a bottleneck for us, we might attempt to work around it, but there's no clear-cut way on how to simple "improve things".
