### ISSUE TITLE
How to send zero gas prices transaction?

### ISSUE THREAD

**Issue by wenjiping** [ethereum/go-ethereum#22408]
At present, the Gas price on the ETH network is very expensive. Even so, I found that some transactions still achieve 0 Gas Price. I want to know, how should I do it and realize it?

Example: https://etherscan.io/tx/0x2d10ea087d1f8a70f31e504356d45face7f086af5fabab0ef1bc24400f532c5f

I built the Geth node myself and used it for an ETH miner. I can send the transaction to my Geth node and mine at the same time. But it seems that my transaction will not be packaged.

**Comment by karalabe** [comment]
Geth doesn't accept 0 gas priced txs. That's a security feature, otherwise you could spam the network indefinitely from accounts with no balance.

The only way to get around the gas price limits is to set certain accounts as `local`. That makes Geth ignore the price. Geth's miner will also prioritize local transactions over all else.

Thus, if you see a 0 price tx, that was explicitly made by the miner, or explicitly pre-approved by the miner. You can't do such a thing without miner collaboration (or mining your own block).
