### ISSUE TITLE
Work submitted but none pending

### ISSUE THREAD

**Issue by andrewmayer1997** [ethereum/go-ethereum#22445]
#### System information

Geth version: `latest`
OS & Version: Linux

#### Expected behaviour
Work submitted

#### Actual behaviour
Work submitted but none pending error

It's the correct behaviour? How to fix it or why this bug is coming?

**Comment by MariusVanDerWijden** [comment]
This happens if your miner submits a solution to your node for a work package that is not available in the node anymore.
So basically when you're mining, your node will create "work packages". They are send to the miner. Once the miner finds a solution to the work package (a valid nonce for the pow) it will submit the solution back to the node.
If you changed the work package or your node dropped the work package, your solution will not be accepted and the `Work submitted but none pending` error will be thrown.

So things you can do:
- Don't modify the work packages coming from geth
- Work packages will be deleted after the block is older than 7 blocks

If you're not mining, you can safely ignore the error
