### ISSUE TITLE
Transactions continuously stuck in the local mempool

### ISSUE THREAD

**Issue by Norfolks** [ethereum/go-ethereum#22490]
#### System information

Geth version: `geth 1.10.0`
OS & Version: Linux
Mode: Full
CPU/RAM/SSD: More than needed.

#### Expected behaviour
Geth node receives transactions and broadcasts them through the network.

#### Actual behaviour
At some point, transactions are stucked in mempool. The gas price of our transactions is high, however, we do not see transactions on other nodes/etherscan.

#### Steps to reproduce the behaviour
Too hard to reproduce. We have a lot of transactions to different wallets, we haven't met such a problem while sending less amounts of transactions.
For now, we have found two workarounds: 
1. resend a transaction with a slight gas increase(Doesn't help sometimes). 
2. delete some peers from a node list, when the node connects to new peers transactions start to broadcast successfully.
There is possibly some bug in the p2p connection because reconnection to node helps.

#### Backtrace
Backtrace looks fine, no errors, the node has 25 peers available.

**Comment by tharunprabhakaran** [comment]
Faced this issue few days back, in our case the cause of the issue was the low IOPS of the disk. Please mention the IOPS of the SSD.

**Comment by Norfolks** [comment]
Thanks @tharunprabhakaran
But it doesn't look like we have IOPS problem.
We have found a temporary solution - delete one node from the peer list, and as soon as another node is added, our transactions are broadcasted.
It is definitely a network problem.

**Comment by MariusVanDerWijden** [comment]
Actually this is currently expected behaviour (we're working on it).
Basically we don't want nodes to be able to resend their transactions to peers that have already seen the transactions. 
Otherwise this would increase the network load of ethereum significantly and also allow for ddos-ing peers. 
So the transactions are only send to each peer once. If you kick a peer and connect to a new one, then the transactions are resend to that peer, which will distribute them again in the network.

So yeah, kicking a peer and adding a new one is the way to go right now.
As I said, we're working on a better solution than this

**Comment by Norfolks** [comment]
@MariusVanDerWijden
Thanks for the answer.
We hope for your success in resolving the issue.

**Comment by gitteri** [comment]
@MariusVanDerWijden @karalabe I understand it's quite the problem when considering rebroadcasting, but is there any appetite for enforcing an unstable peer list? By that I mean, can we simply enforce a new peer every x minutes to fix this issue, decrease the likelihood of an eclipse attack, and keep a better decentralized web of node connections? If this is acceptable then I can get working on it.
