### ISSUE TITLE
Logs displaying

### ISSUE THREAD

**Issue by sdmg15** [ethereum/go-ethereum#22505]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

I found it a bit misleading that you start your custom node but in the log it's display `Starting Geth on Ethereum mainnet... `

![image](https://user-images.githubusercontent.com/13077039/111309067-c3335800-865b-11eb-831e-daf1d30069d9.png)

Just because of that log I spent some times wondering if my custom chain was really taken into consideration

**Comment by MariusVanDerWijden** [comment]
Yes, you need to set the networkid flag, otherwise your node will try to connect to all other nodes that don't have the networkid set (which basically means your custom chain will try to connect to mainnet but fail since you have a different chainid/genesis).
Please specify `--networkid`, this will make your nodes connect to each other faster and prevent your nodes from spamming requests to mainnet nodes
