### ISSUE TITLE
web3 version radically out of date

### ISSUE THREAD

**Issue by cyrusadkisson** [ethereum/go-ethereum#22521]
#### System information

Geth version: 1.10.1 from ubuntu repos
OS & Version: Ubuntu linux 20.04.1

#### Expected behaviour

web3 that works and is inline with current documentation

#### Actual behaviour

web3 that does not work and is not in line with current documentation

#### Steps to reproduce the behaviour

web3.version = 0.20.1

current = 1.3.4

It would be one thing to just completely drop web3 and say geth doesn't support it (which would be insane) but it's another to claim support "we support all functionality of web3. Click here to view modern web3 docs that look nothing like what we actually support." and then not offer it. It took me hours to figure out why I couldn't get anything to work.

(Side issue: can't connect to ws or http or ipc and spent all day trying. Internally, from another computer, ports, firewalls, tried to sideload web3, etc. I finally gave up, loaded web3 into node console, started using an Infura endpoint and gave up on geth entirely.)

**Comment by ligi** [comment]
where does geth claim:  "we support all functionality of web3. Click here to view modern web3 docs that look nothing like what we actually support." ?

**Comment by holiman** [comment]
Our JS interpreter is pretty old, and it doesn't support certain things in the newer ECMAScript standards, for example, it cannot handle `async`, which makes anything promise-based not possible. It also differs in the regexp implementation (IIRC it uses the golang regexps, which are different). 
Therefore, we can't update to a modern version of web3.js, and even making a small update to web3 is quirky, since we have to modify the javascript to change a few regexp uses (again, IIRC). 

Our console is mainly for some quick manual debugging. We've considered many times to drop it, but OTOH it's highly useful for us as developers, whenever one has to do a quick check on some basic thing, and don't want to spin up a full node environment. 

For any more advanced contract interaction, you should use a better environment, such as node-based or python-based, with all the bells and whistles. 

I'd like to close this ticket, but maybe we should highlight this somehwere in the docs -- could you point us to any specific places where you think this info should be more visible? 

> (Side issue: can't connect to ws or http or ipc and spent all day trying. Internally, from another computer, ports, firewalls, tried to sideload web3, etc. I finally gave up, loaded web3 into node console, started using an Infura endpoint and gave up on geth entirely.)

Now _this_ is a lot more concerning to me. Please provide more info, because connecting to ws or http always works like a charm for me, and it's very important that this works well.

**Comment by cyrusadkisson** [comment]
![Screenshot from 2021-03-18 10-55-53](https://user-images.githubusercontent.com/2284720/111647257-b720d500-87d8-11eb-9822-9233f92ee009.png)

This wasn't the only place this support was claimed. And in one place (can't find it with a cursory search now) this claim included a link to web3js documentation which landed on web3js v1.20.
