### ISSUE TITLE
p2p: API for protocol-driven connectivity

### ISSUE THREAD

**Issue by fjl** [ethereum/go-ethereum#2254]
This is a proposal for a fundamental API change in package p2p. 

The API for protocol ("eth", "shh", ...) implementations is vaguely similar to the net/http server API. Protocols are registered to the server and provide a callback function for new sessions. The server drives connectivity without any input from protocols and launches protocol sessions in fresh goroutines after the connection has made it through the handshake.

This approach works well enough for protocols that don't care about their peer set, but can be a show stopper in other cases. The connectivity required by "bzz", "les" cannot be implemented in this model,
they need:
- Node discovery handled by subprotocols e.g.
  - "bzz" wants to connect to nodes in its Kademlia table
  - "les" wants to connect light clients to full nodes, which are registered under a topic hash in discovery.
- Listen-only, Dial-only protocols
- Access to RLPx discovery tables, which are currently hidden within package p2p internals.
  - required for topic lookups
- Separate optimal peer counts
  - "bzz" wants a specific number of peers
## Proposed API

Instead of registering protocols with `Server`, it is rechristened `Network` and functions like a socket.

``` go
package p2p

type Network struct {
    *discover.Table
    ...
}

type Protocol struct {
    Name   string
    Version uint
    Length int // maximum message code, to be removed after RLPx v5
}


type Listener interface {
    Accept() (Session, error)
    Close() error
}

type Session interface {
    MsgReadWriter
    Close() error

    Node() discover.Node
    RemoteAddr() net.Addr
    LocalAddr() net.Addr
}

func (*p2p.Network) Listen(p Protocol) (Listener, error) { ... }
func (*p2p.Network) Dial(p Protocol, n *discover.Node) (Session, error) { ... }
```

Protocols no longer need to be registered before the server is started.
Instead, each procotol can receive connections by invoking `Listen` once, then
waiting for connections by calling `Accept` on the listener in a loop.
When the listener is closed, the protocol will no longer be offered to other nodes
but existing sessions stay established.

If a protocol wants to dial a particular node, it can do so through `Dial`.
The connection will be attempted and the session for that particular node returned
if the attempt is successful. If the dialed node speaks other protocols for which `Listen`
was invoked previously, the corresponding listeners will also output this connection (except
for the dialing protocols own listener of course).

The new API requires that protocols keep track of the `p2p.Network` instance, otherwise they
cannot dial. In order to keep protocol implementations testable, a mock implementation 
of `Network`, `Listener` and `Session` will be provided in package p2ptest. There will also be a few
new helper functions in package p2p implementing the random connectivity used by "eth" and "shh".

**Comment by zelig** [comment]
This is incredibly exciting @fjl 
first sight it looks pretty much what we always planned just more. 
i very much welcome your decision to open up devp2p for protocols and give them this freedom. 
Very very much supported. 
Technicalities follow in separate comments
maybe we should create branch with a `README.dip0` so that we can put in line comments and have threaded discussion on the details.

**Comment by fjl** [comment]
We can discuss here. Good to hear that you like it. I bit the bullet and ditched my other approach because an API based on configuration will always be insufficient for some uses.

**Comment by zelig** [comment]
what immediately comes to mind is what happens when I close the session exactly. 
The protocols often make assumptions that this means  'disconnect' please confirm it means exactly that. 

However, as discussed previously protocol-speficic session management is better be supported on the protocol level. In other words we should have a way to close a protocol session without either closing the listener for the entire protocol.  I think clarifying this would be very important. 
I dont remember  what happens now if we receive msgs with protocol offsets not allowed as per the intersection of the two peers' protocol caps. If we just ignore them, then we should have a per-peer dymanic caps setting. Also then protocols should implement their specific disconnect messages to let their peers know that there is no business. 
But here I think it is better to delegate this managing this to devp2p. My proposal is that Close() takes a disconnect reason, standard devp2p-level disconnect reasons will cause peer disconnect, while if the reason implements ProtocolLevelDisconnectReason (an error interface protocols implement) than it just causes the protocol connection to shut down. 

This would actually be an explicit change in devp2p, namely allowing a field with subprotocol error that encode which protocol closes its session. Technically it is backwards compatible with peers who would just sadly disconnect the network session if they receive a subprotocol error. 
This relates to the other issue. That subprotocol errors are not properly detailed, they are under the same code, so protocol level communication about the disconnect reason is either not done or need to be reimplemented at the protocol level. Therefore it would be great to allow types of subprotocol errors. One way to do this is to allow yet another field, but it is not necessary if higher not used codes are interpreted by the protocol (which is not encoded)

Another way to do this is to allow repeated devp2p handshakes. This means if i close a protocol session only, devp2p would resend a handshake message with the new proto caps. this has the advantage that it is only a semantic change in devp2p and backward compatible with the old versions who would simply close the network session upon this event (correct old behaviour). 

I dont mind if this will only be in version 2, 
my 2 wei, let me know what you think

**Comment by fjl** [comment]
Dynamic protocol sessions and per-protocol disconnect reason is definitely planned.

**Comment by zelig** [comment]
already in 1.5 nice!
we must rewrite swarm API though probably quite a bit.
The other question is whether i used anything else on the peer object which the current protocol makes available. Gotta check before we finalise API.

**Comment by gluk256** [comment]
Thank you @fjl, very good proposal.
