### ISSUE TITLE
No peers after update to 1.10.1 / can't fully sync

### ISSUE THREAD

**Issue by l4zygreed** [ethereum/go-ethereum#22555]
#### System information

Geth version: `1.10.1`
OS & Version: Linux

#### Problem
After update to verison 1.10.1 geth can't find peers. 
for 10-40 minutes it outputs this messages to logs
```
INFO [03-23|11:29:43.776] Initializing state bloom                 items=20158277 errorrate=0.000 elapsed=11m23.879s
INFO [03-23|11:29:44.273] Looking for peers                        peercount=0 tried=12  static=0
INFO [03-23|11:29:51.879] Initializing state bloom                 items=20395732 errorrate=0.000 elapsed=11m31.983s
INFO [03-23|11:29:54.287] Looking for peers                        peercount=0 tried=7  static=0
```
then it can find 1-2 peers but continue spam this messages.
With 1-2 peers it sync only to ~100 blocks before `highestBlock` and freeze syncing until it become more than ~150-200 and repeat.

startup flags
```
--ropsten --syncmode 'snap' or 'fast' --nousb --cache 4048 
--http --http.addr '0.0.0.0' --ws --ws.addr '0.0.0.0' --ws.origins 'nginx' 
--http.vhosts '*' --http.api "eth,web3,personal,txpool,net" --allow-insecure-unlock
```

**Comment by begetan** [comment]
I can confirm the problem with finding peers in Rinkeby network for version `Geth/v1.10.1-stable-c2d2f4ed/linux-amd64/go1.16`

I've made a clean-up of geth/data dir after upgrade from 1.9.25 and found that synchronization got frozen having a single peer. I expect that this peer also not synced properly.

This behaviour was repeated twice ( first time I did resync from ancient directory) and the second time I did clean synchronization

The workaround is to restart the service.

This issue may danger the upcoming hardfork implementation because most people have skipped 1.10.0 release 

![image](https://user-images.githubusercontent.com/17225934/112155758-e921a500-8be5-11eb-914b-fef07066cf03.png)

**Comment by l4zygreed** [comment]
`The workaround is to restart the service.`
Didn't help me. Updated 19 Mar and still can't sync.
Restarted geth few times with different increased cache, snap syncmode, nothing help

just 0 peers for a long period and then 1-2 with freezing sync

**Comment by karalabe** [comment]
This seems odd. All the Rinkeby signers are updated and nobody ever reported / neither did we see peering issues. Do you have your 30303 ports properly forwarded, both TCP and UDP?

**Comment by karalabe** [comment]
I've tried starting a fresh Ropsten node, it found a good peer and started syncing in about 1 minute, without any port forward at all.

**Comment by begetan** [comment]
We run the Rinkeby node on AWS at the us-east region with a public IP.  It was 30303 open for TCP. During the sync, I saw a maximum of two peers:  `peercount=2 tried=4  static=0` 

The node stop syncing twice during the day. So I had to restart Geth to continue syncing. The sync process is slow because of a lack of peers at the stage of importing states.

I've opened UPD for the 30303 port and restarted the Geth service, but see no difference. Let me know if you need more details or extra debug.

**Comment by l4zygreed** [comment]
After working for 4 days it finally found 5 peers and synced. But syncing speed was pretty slow than before update, mostly 1-4 blocks per minute
Server located in Ukraine. 🤔

Yeah, pretty odd behaviour... before this update finding peers and syncing was way faster.

Idk.. maybe close this? I need node for developing and totally don't wanna restart it and wait for syncing again... 😅

**Comment by holiman** [comment]
We're investigating some issues with the DNS crawler / enr parser now, which have caused some issues for discovery. Should be resolved soon

**Comment by SweeXordious** [comment]
Any update on this ? I have been facing the same issue for some time and I can't get the latest blocks... Only one peer active from time to time

**Comment by tinodj** [comment]
hmmm - same here, any suggestions?

**Comment by SweeXordious** [comment]
@tinodj for me. I updated to the latest version then made sure all the ports are open (no firewall or anything blocking them) and it worked... In case this helps

**Comment by tinodj** [comment]
@SweeXordious Thanks. Can you recall what was last version? I am at 1.10.8. behind NAT but everything forwarded/open.

**Comment by SweeXordious** [comment]
@tinodj try adding the `--v5disc` param then try again, maybe

**Comment by SweeXordious** [comment]
@tinodj btw, are you running geth inside docker?

**Comment by tinodj** [comment]
I tried with v5disc and actually I just double checked it is 1.10.13 (newest geth). It is a virtual machine, I am not sure which virtualisation technique was used, but I don't think it is docker.

**Comment by SweeXordious** [comment]
Using a virtual machine, you might have that problem if you're not configuring the ports correctly.
You need to map 30303 to 30303 on the host and allow it to listen for incoming traffic... 
Try opening a socket using telnet `telnet <address> <port>` and see if it's listening or not

**Comment by tinodj** [comment]
Hi, I've resolved this. I think it was because I had a config file where I had BootstrapNodes for Ethereum mainnet (1) but I was trying to sync the ropsten (3). After changing the BootstrapNodes it started working like a charm :) Thanks for your answers!
