### ISSUE TITLE
web3j.getGasPrice

### ISSUE THREAD

**Issue by msak222** [ethereum/go-ethereum#22705]
The gasPrice of the main network is more than 300 Gwei, but web3j.getGasPrice is obtained from our latest version of the full node and occasionally returns 6 or 2. What is the problem?

**Comment by karalabe** [comment]
Just tried it on one of our nodes, returned 209 Gwei. Re you sure the node you're querying is in sync?

**Comment by karalabe** [comment]
Ran it against all of our bootnodes, 6 returned 206 gwei, and one which is not synced returned 1 gwei.

**Comment by msak222** [comment]
We found that occasionally a very low gasPrice will be returned at a very small stage. Our node is the latest version and synchronized to the latest block. We are also very confused, so we ask for your help.

**Comment by msak222** [comment]
If you have the conditions, please monitor for a longer time, such as whether there is this problem in two days, we will continue to observe the problem

**Comment by bulgakovk** [comment]
Faced the same issue a few times. I have also found a correlation between extremely low fees and mined blocks with 0 transactions:
<img width="907" alt="image" src="https://user-images.githubusercontent.com/8983736/115389970-6856c880-a1e6-11eb-9bfb-a90fc8a22526.png">

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/8983736/115390063-815f7980-a1e6-11eb-803e-1baf4070d37c.png">

I do see this comment:
https://github.com/ethereum/go-ethereum/blob/cc33398cef4d9faeaec1e68e13029e1a0e1d6e41/eth/gasprice/gasprice.go#L182-L185

but not sure where exactly the case with 0 length TXs blocks is handled in the function. Might it be the root reason for these random drops?

**Comment by msak222** [comment]
> Ran it against all of our bootnodes, 6 returned 206 gwei, and one which is not synced returned 1 gwei.



> Faced the same issue a few times. I have also found a correlation between extremely low fees and mined blocks with 0 transactions:
> <img alt="image" width="907" src="https://user-images.githubusercontent.com/8983736/115389970-6856c880-a1e6-11eb-9bfb-a90fc8a22526.png">
> 
> <img alt="image" width="1290" src="https://user-images.githubusercontent.com/8983736/115390063-815f7980-a1e6-11eb-803e-1baf4070d37c.png">
> 
> I do see this comment:
> https://github.com/ethereum/go-ethereum/blob/cc33398cef4d9faeaec1e68e13029e1a0e1d6e41/eth/gasprice/gasprice.go#L182-L185
> 
> but not sure where exactly the case with 0 length TXs blocks is handled in the function. Might it be the root reason for these random drops?

Hi guys. A friend encountered a similar problem above, please verify the situation, please @karalabe

**Comment by junderw** [comment]
Verification of this bug requires polling a geth node once every minute for a couple days until congestion occurs.

I think it has to do with blocks, so maybe even polling / gathering data once every 15 seconds would be better to find any issues sooner.

**Comment by junderw** [comment]
@bulgakovk

Can you share some recent "dips"... I think this is a constant issue among all instances. So it definitely has to do with the blocks.

Our most recent dips that were consitent across all of our instances were

2021/04/22 08:47:00 UTC (dip to 6 gwei from 112 gwei)
2021/04/22 08:53:00 UTC (dip to 6 gwei from 112 gwei)

**Comment by junderw** [comment]
I think you probably have similar dips.

Our polling job polls all of the instances in sequence, but in general the requests should only be a few ms off for us... maybe if your jobs are off by 30 seconds etc. then maybe it won't be exactly the same but I am interested to see if you have dips at similar time.

**Comment by holiman** [comment]
> Verification of this bug requires polling a geth node once every minute for a couple days until congestion occurs.

No, that should not be posslbe. Any given segment of blocks should lead to a totally deterministic gas oracle. If I'm wrong about this, it's a bug which needs to be fixed. I'm 99% certain that if I replay the GPO on the segment used in the charts above, looking only at the actual transactions that were included in the blocks, I would get an identical chart.

**Comment by bulgakovk** [comment]
> @bulgakovk
> 
> Can you share some recent "dips"... I think this is a constant issue among all instances. So it definitely has to do with the blocks.


Confirming one of our nodes had the same dip exactly at that time (UTC timezone):
<img width="667" alt="image" src="https://user-images.githubusercontent.com/8983736/115852424-bced8400-a430-11eb-98b5-870144d9e4b9.png">

However, it's not a case for the second node:
<img width="670" alt="image" src="https://user-images.githubusercontent.com/8983736/115852607-eefee600-a430-11eb-81e0-a7bc4698e4e1.png">

It seems to depend on which exactly chain segment the node has used to predict the price (since the method returns some percentile of TX gas prices included in the recent blocks IIRC).

**Comment by Melraidin** [comment]
For instances of this occurring I walked the chain to get the gas price at each block. Here's a block where I saw an unusually low gas price:
```
Block number: 12287282
Gas price: 1,000,000,000
Prices used in gas calculation: [+0 +0 +0 +0 +0 +0 +0 +0 +0 +0 +0 +0 +0 +0 +0 +0 +0 +0 +0 +0 +0 +0 +0 +0 +0 +1 +1 +1 +1 +1 +1 +1000000000
 +1000000000 +1000000000 +1000000000 +1000000000 +1000000000 +1000000000 +120000000000 +132000000000 +132000000000 +132000000000 +132000000000 +135000001561 +135300000000 +135300000000 +141015000000 +141075000262 +148000001459 +14900000
0000 +149000000000 +150000000000 +150000000000 +150000000000 +150000000000 +150000000000 +150000000000 +161700000000 +162000000000 +164000000000]
```

That's a lot of zero or one wei gas prices. It makes sense though, given we grab the cheapest transactions from the blocks instead of sampling a random set of transactions from the blocks we're using in the estimate: https://github.com/ethereum/go-ethereum/blob/34f3c9539b49396b17524ee72ea20498f96600b9/eth/gasprice/gasprice.go#L198

Here's links to a few of these transactions to confirm I'm not misreading them and perhaps see how they ended up in a block to begin with:
https://etherscan.io/tx/0xc370d0a480b477fe2465f4259e6cf21603d9cc4906aa1d86704292e6fa369e0a
https://etherscan.io/tx/0xb11fb82fbbc8499bfc2d6c0e20ae5b358b5b3dd7ee91ff56afa773543a19da93
https://etherscan.io/tx/0x939ef48c3bb73fc4b389496c573d77305d8ff1f8f4ed3221ef6d61add378fc80
