### ISSUE TITLE
Increase resiliency to better handle Ropsten's deep reorgs

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/go-ethereum#22713]
# Rationale

Hi all,

this weekend we had two deep reorgs on the Ropsten network, causing problems to some nodes trying to fetch local state data older than 128 blocks.

Below, the amount of reorgs deeper than 12 blocks that we had in the last 10 days:

<img width="966" alt="image" src="https://user-images.githubusercontent.com/47108/115593457-8681fe80-a2a2-11eb-8b45-984b881690d6.png">

_Source: https://ropsten.etherscan.io/blocks_forked_

What are good strategies to mitigate/solve this problem?
On a node level, we wonder if it would be beneficial to increase the state retention for Ropsten to an arbitrary number, let's say, 512 — or as a user-defined flag. On an network level, maybe deploying more mining power might help as well?

Additionally, is there a forkmon for Ropsten that could be used for network monitoring?

TYSM!

# Implementation

Are you willing to implement this feature?

✅

**Comment by holiman** [comment]
Triage discussion, there are two things that need to be changed. 

- Pruning: right now, we explicitly do not memory-prune the most recent `128` blocks. We would need to make this limit configurable, so the "pruning avoidance" can be set larger. 
- Snapshot diff layers. Right now, we maintain "difflayers" for the most recent 128 blocks, to support reorgs. We would either need to make this limit configurable (which increases the memory consumption), _or_ make it so that once you reorg over the threshold, things at least keep working (I hope they already do -- we simply don't find the snapshot root and will execute trie-only).

**Comment by holiman** [comment]
> Additionally, is there a forkmon for Ropsten that could be used for network monitoring?

We had https://testnet.forkmon.ethdevops.io/ up temporarily, and reused it for the testnets. It's not active any longer, however.

**Comment by holiman** [comment]
Stale, closing
