### ISSUE TITLE
confusing about mining

### ISSUE THREAD

**Issue by master-davidlee** [ethereum/go-ethereum#22743]
If a miner is mining and receives a transaction with the same nonce and a higher fee, will the miner stop and replace the transaction, then restart mining ?

**Comment by ccsalway** [comment]
Surely this would mean restarting the verification of the transaction and computation of the block hash as the payload has changed, and as such a wasted expense. 

Work flow:
Transaction fee offered is 100
You compute to verify transaction 
You start to calculate the block hash
Transaction fee offered is now 120
You start the verify process again
You restart to calculate the block hash

You have potentially done most of the work to calulcate the block hash, which will be wasted.  So unless the new transaction fee is a lot higher to have to start everything again, why would you...  just compute it and move on.

**Comment by master-davidlee** [comment]
Thanks for the answer, I was wondering from the real code point view, would miners give up and waste the effort already made and replace it with this new tx ? Sorry I don't know go language.🤕

**Comment by holiman** [comment]
> You have potentially done most of the work to calculate the block hash, which will be wasted.

That's not quite true. Mining is not about "carefully building a tower" , it's more about randomly picking grains of sands on a large beach, and eventually finding a grain that matches what you're looking for. 

So switching out the work-package is no real loss. The only loss comes from the sliver of time that the GPU is not mining, which _should_ be short. If the node updates the work package, and the miner simultaneously finds a solution, then the node _should_ accept that solution, even though the old work package is a bit stale. Otherwise there's a risk there aswell. 

So, 
> If a miner is mining and receives a transaction with the same nonce and a higher fee, will the miner stop and replace the transaction, then restart mining ?

Yes, but not immediately. We don't insta-rebuild the work package whenever a better transaction comes in, afaik. But yes, we do incrementally improve the work package while the miner is working on it.
