### ISSUE TITLE
Mismatch coordinates order between EncodePoint() and ToBytes()

### ISSUE THREAD

**Issue by wangyifan** [ethereum/go-ethereum#22815]
https://github.com/ethereum/go-ethereum/blob/effaf185234533b787926a67a6f73eb8d636e7af/crypto/bls12381/g2.go#L154-L180

The order for point coordinates in EncodePoint() is [x1, x0, y1, y0] while it's [x0, x1, y0, y1] in ToBytes(). 
Is this intentional?

**Comment by MariusVanDerWijden** [comment]
Yes I think that's intentional. `EncodePoint` encodes the coordinates while `ToBytes` encodes the point after affine transformation.
`EncodePoint` encodes [x1, x0, y1, y0].
`ToBytes()` encodes [p0[1], p0[0], p1[1], p0[0]] with p being in the affine representation, p0, p1 of type `Fe2`.
From the documentation for type `Fe2`:
```
// fe2 is element representation of 'fp2' which is quadratic extension of base field 'fp'
// Representation follows c[0] + c[1] * u encoding order.
```
So c[1] represents the upper bytes of the `fe2` element and c[0] the lower bytes
