### ISSUE TITLE
Wrong gas estimation

### ISSUE THREAD

**Issue by mdeliadi** [ethereum/go-ethereum#22850]
#### System information

Geth version: 1.10.2-stable
OS & Version: Debian GNU/Linux 9.6 (stretch)

#### Actual behaviour

I've encountered, especially recently, a lot of transactions with a wrong estimated gas, resulting in an "Out of gas" error.
I've tried the same estimation with Infura and their results are higher than my node, I don't get why.
Is there any setting I can try to tweak to fix that?

**Comment by karalabe** [comment]
Geth's gas estimation is "perfect" as in it gives you the exact number the current state requires. If the state changes in between, you might end up needing more. I think Infura adds a multiplier on top of what we return to cover these fluctuations. Can't really say more without some more details to look into.

**Comment by khidesha** [comment]
My transactions get the same error. plz suggest something

https://etherscan.io/tx/0xbb636cb91d9ecd7bc06c9369f5b72be3a9971b586a6672f71ac7430dc88d99a8

**Comment by karalabe** [comment]
@khidesha I can only answer the same thing as above. The gas estimator will work, but if the contract changes state, and your tx is included a few blocks later, the estimated gas might be off. It's generally useful to add a bit of slack to the estimated gas (say 10%) so that small variations don't result in reverts.
