### ISSUE TITLE
Reply to censored thread

### ISSUE THREAD

**Issue by jon-chuang** [ethereum/go-ethereum#22945]
I don't want my name associated with shitty codebases.

Correction: world's shittiest codebase.

**Comment by karalabe** [comment]
We're trying our best. If that's not enough for you, feel free to fork Geth (or start from scratch) and make something better. That's the spirit of OSS.

**Comment by jon-chuang** [comment]
Yeah, that I will. I spent 3 weeks of my life reading this spaghetti codebase, worked hard to create a potentially meaningful contribution tackling one of Ethereum's biggest pain points - state access - and got 0 feedback and review, help or encouragement, even after I proved my case. It's pretty clear to me there's something wrong in this community, and contributions are indeed unwelcome. So goodbye.

**Comment by jon-chuang** [comment]
I would have been ok with all this, if you'd just said that you're busy and you'd follow up in the future about it. 

But I felt through our interactions that you'd already dismissed my ideas out of hand. You didn't even give guidance on how I myself could have helped to move things forward via a more realistic benchmark. 

I think if you were more serious in nurturing potential contributors, you'd have taken some time to at least reply. But its obvious the team is too caught up in whatever its doing.

This codebase is by far not the best in the world. Even then, I was willing to ignore it if it meant that Ethereum community can have less issues with state access bottleneck in the future. 

But obviously, this was not welcome at all.

**Comment by karalabe** [comment]
> But I felt through our interactions that you'd already dismissed my ideas out of hand. 

Yes, we've discarded it as probably a dead end. We can always be wrong, but that's why we need real benchmarks, not a synthetic one.

> You didn't even give guidance on how I myself could have helped to move things forward via a more realistic benchmark.

Mainnet full sync, master vs. proposal. Anything else is meaningless.

> But its obvious the team is too caught up in whatever its doing.

London hard fork, ETA in a month. Ethereum 2 merge, ETA end of year.

> This codebase is by far not the best in the world. 

Your point beyond insulting people?

> But obviously, this was not welcome at all.

You are wrong, but obviously don't care.

> If you want to know - yeah, I am insulted.

You should try and reevaluate the gravity of things, the world doesn't revolve around you.

> I've got many better things to do with my time than waiting around on no response and not being taken seriously.

You were taken seriously, until today that is.

> All your followers - they know nothing about how rotten geth is on the inside.

Again, your point beyond trying to insult people?

> I do, and with this kind of community spirit, I'm honestly done.

You were done 5 times already today. But sure, go on.

**Comment by Dylan-Kerler** [comment]
So is this now stale?

In the original PR @jon-chuang claimed a 3x improvement:

> If this allows block construction time to be reduced by 3x, I would say this is a big win. It would also be robust and thus able to increase block gas limit by, hypothetically, 3x.

Surely this is at least worth doing a proper benchmark on. Even a 10% increase would be significant.

**Comment by karalabe** [comment]
> So is this now stale?
> 
> In the original PR @jon-chuang claimed a 3x improvement:
> 
> > If this allows block construction time to be reduced by 3x, I would say this is a big win. It would also be robust and thus able to increase block gas limit by, hypothetically, 3x.
> 
> Surely this is at least worth doing a proper benchmark on. Even a 10% increase would be significant.

Please see https://github.com/ethereum/go-ethereum/pull/22881#issuecomment-848862890. The PR OOMs, but before doing so, it is 12% slower than master. This was our problem all along, it's a blind optimization that the author didn't even bother to test on a live node. Can it be made faster? Maybe, I don't know. It is not my task to prove the PR is faster than one we have, that lies at the author.

PS: Next time you want to contribute to the "worlds shittiest codebase", at least don't submit an OOM. Doesn't make you look good.

**Comment by jon-chuang** [comment]
@karalabe lol. you're really a petty one, aren't you. I'm not going to respond. If you had been this quick in trying to help me work things out as you have been trying to prove yourself right, we wouldn't have ended up here in the first place.

**Comment by taylordwright44** [comment]
> @karalabe lol. you're really a petty one, aren't you. I'm not going to respond. If you had been this quick in trying to help me work things out as you have been trying to prove yourself right, we wouldn't have ended up here in the first place.

CHING CHONG WHY YOU NOT TEST MY SHITTY CODE THAT DOESN'T WORK AND IS 12 PERCENT SLOWER FOR ME IMMEDIATELY THIS IS ALL YOUR FAULT NOT MINE SHAMEFUR DISPRAY GETH TEAM

**Comment by karalabe** [comment]
> If you had been this quick in trying to help me work things out as you have been trying to prove yourself right, we wouldn't have ended up here in the first place.

We don't owe you anything. Neither our time, nor any priority handling. I ran your code as a courtesy to @Dylan-Kerler, who asked nicely if the improvement was relevant or not.

For the record, benchmarks usually take a week to finish, unless the code is buggy or is an obvious deterioration in performance. When code reaches our benchmarkers, we don't expect them to blow up.

I don't get why you're angry that we didn't put more time in it. Your code OOMs, and does so *fast*. This means you didn't even bother to try and run even a short sync cycle with it. If you couldn't even be bothered to sanity test your own code, turns out that the team was always right not to try and benchmark it. It just wasn't ready. It is not the Geth team's job to fix obvious issues. Yes, we can help iron out kinks or maybe discuss integration points, but first you need to prove it's worthwhile, which you didn't do.

My friendly suggestion for the future is to accept the working style of a team you're trying to contribute to, whether you like it or not. The world around you is not dumb and there are reasons processes work as they do. If you find them insufficient, try to understand why they are like that, and maybe afterwards suggest improvements. Trying to insult people and calling them things won't get your point across and will neither make you look good.

Let's agree to part was semi-amicably and stop escalating the situation. Wish you all the best in life.
