### ISSUE TITLE
The synchronization mainnet has been stuck and cannot be synchronized to the latest block

### ISSUE THREAD

**Issue by swapnft** [ethereum/go-ethereum#22953]
Version used

Geth
Version: 1.10.4-unstable
Git Commit: 93407b14a66287d1a0ad0140b9c5f754c11ad437
Git Commit Date: 20210524
Architecture: amd64
Go Version: go1.15.3
Operating System: linux

The synchronization mainnet has been stuck and cannot be synchronized to the latest block

When I entered the console, I found that the time in the console did not match the time on the server. Is this the reason why I could not synchronize
instance: Geth/v1.10.4-unstable-93407b14-20210524/linux-amd64/go1.15.3
at block: 0 (Thu Jan 01 1970 08:00:00 GMT+0800 (CST))

**Comment by swapnft** [comment]
{
  currentBlock: 12514732,
  highestBlock: 12514822,
  knownStates: 622086129,
  pulledStates: 621937010,
  startingBlock: 12507100
}


INFO [05-27|14:31:53.857] Imported new state entries               count=1152 elapsed=6.287ms     processed=621,975,440 pending=189,805 trieretry=0    coderetry=0 duplicate=0 unexpected=61241
INFO [05-27|14:31:54.023] Imported new state entries               count=768  elapsed=4.156ms     processed=621,976,208 pending=189,341 trieretry=0    coderetry=0 duplicate=0 unexpected=61241
INFO [05-27|14:31:58.308] Imported new state entries               count=768  elapsed=2.401ms     processed=621,976,976 pending=190,834 trieretry=0    coderetry=0 duplicate=0 unexpected=61241
INFO [05-27|14:31:58.783] Imported new state entries               count=694  elapsed=4.055ms     processed=621,977,670 pending=190,753 trieretry=0    coderetry=0 duplicate=0 unexpected=61241
INFO [05-27|14:32:01.939] Imported new state entries               count=384  elapsed="58.488µs"  processed=621,978,054 pending=192,229 trieretry=0    coderetry=0 duplicate=0 unexpected=61241
INFO [05-27|14:32:02.782] Imported new block headers               count=1    elapsed=5.678ms     number=12,514,826 hash=828a4d..a8e410 age=1m3s
INFO [05-27|14:32:05.781] Imported new state entries               count=384  elapsed="56.497µs"  processed=621,978,438 pending=193,292 trieretry=0    coderetry=0 duplicate=0 unexpected=61241
INFO [05-27|14:32:10.653] Imported new state entries               count=384  elapsed="71.707µs"  processed=621,978,822 pending=194,277 trieretry=0    coderetry=0 duplicate=0 unexpected=61241
INFO [05-27|14:32:13.186] Imported new state entries               count=384  elapsed="980.024µs" processed=621,979,206 pending=195,532 trieretry=0    coderetry=0 duplicate=0 unexpected=61241
INFO [05-27|14:32:16.266] Imported new state entries               count=768  elapsed=2.429ms     processed=621,979,974 pending=196,382 trieretry=0    coderetry=0 duplicate=0 unexpected=61241
INFO [05-27|14:32:19.102] Imported new block headers               count=1    elapsed=5.598ms     number=12,514,827 hash=1d69f2..cb5a06 age=1m4s
INFO [05-27|14:32:20.514] Imported new state entries               count=994  elapsed=2.509ms     processed=621,980,968 pending=198,474 trieretry=0    coderetry=0 duplicate=0 unexpected=61241
INFO [05-27|14:32:23.918] Imported new state entries               count=384  elapsed="98.918µs"  processed=621,981,352 pending=199,653 trieretry=0    coderetry=0 duplicate=0 unexpected=61241
INFO [05-27|14:32:27.060] Imported new state entries               count=384  elapsed="201.99µs"  processed=621,981,736 pending=201,169 trieretry=0    coderetry=0 duplicate=0 unexpected=61241
INFO [05-27|14:32:29.678] Imported new state entries               count=384  elapsed="239.019µs" processed=621,982,120 pending=203,034 trieretry=0    coderetry=0 duplicate=0 unexpected=61241
INFO [05-27|14:32:32.266] Imported new state entries               count=384  elapsed="49.251µs"  processed=621,982,504 pending=205,139 trieretry=0    coderetry=0 duplicate=0 unexpected=61241
INFO [05-27|14:32:35.430] Imported new block headers               count=1    elapsed=4.836ms     number=12,514,828 hash=f6b3e2..528bad
INFO [05-27|14:32:35.919] Imported new state entries               count=384  elapsed="142.065µs" processed=621,982,888 pending=206,385 trieretry=0    coderetry=0 duplicate=0 unexpected=61241
INFO [05-27|14:32:39.579] Imported new state entries               count=384  elapsed="50.57µs"   processed=621,983,272 pending=207,679 trieretry=1    coderetry=0 duplicate=0 unexpected=61241
INFO [05-27|14:32:41.912] Imported new state entries               count=384  elapsed="63.168µs"  processed=621,983,656 pending=209,650 trieretry=0    coderetry=0 duplicate=0 unexpected=61241
INFO [05-27|14:32:45.476] Imported new state entries               count=384  elapsed="9.689µs"   processed=621,984,040 pending=210,728 trieretry=0    coderetry=0 duplicate=0 unexpected=61241
INFO [05-27|14:32:48.699] Imported new state entries               count=384  elapsed="55.453µs"  processed=621,984,424 pending=212,039 trieretry=0    coderetry=0 duplicate=0 unexpected=61241
INFO [05-27|14:32:48.806] Imported new state entries               count=0    elapsed=106.087ms   processed=621,984,424 pending=212,053 trieretry=3    coderetry=0 duplicate=0 unexpected=61242
INFO [05-27|14:32:52.051] Imported new state entries               count=395  elapsed="78.127µs"  processed=621,984,819 pending=213,395 trieretry=0    coderetry=0 duplicate=0 unexpected=61242
INFO [05-27|14:32:54.997] Imported new state entries               count=384  elapsed="2.722µs"   processed=621,985,203 pending=214,732 trieretry=0    coderetry=0 duplicate=0 unexpected=61242
INFO [05-27|14:32:58.268] Imported new state entries               count=384  elapsed="127.027µs" processed=621,985,587 pending=215,625 trieretry=0    coderetry=0 duplicate=0 unexpected=61242
INFO [05-27|14:33:05.261] Downloader queue stats                   receiptTasks=0   blockTasks=0   itemSize=232.64KiB throttle=282

**Comment by swapnft** [comment]
This is how I start it

geth \
--datadir "/mnt/hdd01/node" \
--http \
--http.addr "0.0.0.0" \
--http.port "8545" \
--http.corsdomain "*" \
--http.vhosts "*" \
--ws \
--ws.addr "0.0.0.0" \
--ws.port "8546" \
--ws.origins "*" \

**Comment by holiman** [comment]
>  I found that the time in the console did not match the time on the server. Is this the reason why I could not synchronize
instance: Geth/v1.10.4-unstable-93407b14-20210524/linux-amd64/go1.15.3
at block: 0 (Thu Jan 01 1970 08:00:00 GMT+0800 (CST))

No, that's not the current time, it's the timestamp of the latest block, which is genesis, with a timestamp of `0`.

**Comment by holiman** [comment]
Your sync is progressing, as far as I can tell. What you're experiencing is common enough that we have a 'bottled response' for it: 


--- 

Syncing Ethereum is a pain point for many people, so I'll try to detail what's happening behind the scenes so there might be a bit less confusion.

The current default mode of sync for Geth is called fast sync. Instead of starting from the genesis block and reprocessing all the transactions that ever occurred (which could take weeks), fast sync downloads the blocks, and only verifies the associated proof-of-works. Downloading all the blocks is a straightforward and fast procedure and will relatively quickly reassemble the entire chain.

Many people falsely assume that because they have the blocks, they are in sync. Unfortunately this is not the case, since no transaction was executed, so we do not have any account state available (ie. balances, nonces, smart contract code and data). These need to be downloaded separately and cross checked with the latest blocks. This phase is called the state trie download and it actually runs concurrently with the block downloads; alas it take a lot longer nowadays than downloading the blocks.

So, what's the state trie? In the Ethereum mainnet, there are a [ton of accounts already](https://etherscan.io/chart/address), which track the balance, nonce, etc of each user/contract. The accounts themselves are however insufficient to run a node, they need to be cryptographically linked to each block so that nodes can actually verify that the account's are not tampered with. This cryptographic linking is done by creating a tree data structure above the accounts, each level aggregating the layer below it into an ever smaller layer, until you reach the single root. This gigantic data structure containing all the accounts and the intermediate cryptographic proofs is called the state trie.

Ok, so why does this pose a problem? This trie data structure is an intricate interlink of hundreds of millions of tiny cryptographic proofs (trie nodes). To truly have a synchronized node, you need to download all the account data, as well as all the tiny cryptographic proofs to verify that noone in the network is trying to cheat you. This itself is already a crazy number of data items. The part where it gets even messier is that this data is constantly morphing: at every block (15s), about 1000 nodes are deleted from this trie and about 2000 new ones are added. This means your node needs to synchronize a dataset that is changing 200 times per second. The worst part is that while you are synchronizing, the network is moving forward, and state that you begun to download might disappear while you're downloading, so your node needs to constantly follow the network while trying to gather all the recent data. But until you actually do gather all the data, your local node is not usable since it cannot cryptographically prove anything about any accounts.

If you see that you are 64 blocks behind mainnet, you aren't yet synchronized, not even close. You are just done with the block download phase and still running the state downloads. You can see this yourself via the seemingly endless `Imported state entries [...]` stream of logs. You'll need to wait that out too before your node comes truly online.

---

**Q: The node just hangs on importing state enties?!**

A: The node doesn't hang, it just doesn't know how large the state trie is in advance so it keeps on going and going and going until it discovers and downloads the entire thing.

The reason is that a block in Ethereum only contains the state root, a single hash of the root node. When the node begins synchronizing, it knows about exactly 1 node and tries to download it. That node, can refer up to 16 new nodes, so in the next step, we'll know about 16 new nodes and try to download those. As we go along the download, most of the nodes will reference new ones that we didn't know about until then. This is why you might be tempted to think it's stuck on the same numbers. It is not, rather it's discovering and downloading the trie as it goes along.

**Q: I'm stuck at 64 blocks behind mainnet?!**

A: As explained above, you are not stuck, just finished with the block download phase, waiting for the state download phase to complete too. This latter phase nowadays take a lot longer than just getting the blocks.

**Q: Why does downloading the state take so long, I have good bandwidth?**

A: State sync is mostly limited by disk IO, not bandwidth.

The state trie in Ethereum contains hundreds of millions of nodes, most of which take the form of a single hash referencing up to 16 other hashes. This is a horrible way to store data on a disk, because there's almost no structure in it, just random numbers referencing even more random numbers. This makes any underlying database weep, as it cannot optimize storing and looking up the data in any meaningful way.

Not only is storing the data very suboptimal, but due to the 200 modification / second and pruning of past data, we cannot even download it is a properly pre-processed way to make it import faster without the underlying database shuffling it around too much. The end result is that even a fast sync nowadays incurs a huge disk IO cost, which is too much for a mechanical hard drive.

**Q: Wait, so I can't run a full node on an HDD?**

A: Unfortunately not. Doing a fast sync on an HDD will take more time than you're willing to wait with the current data schema. Even if you do wait it out, an HDD will not be able to keep up with the read/write requirements of transaction processing on mainnet.

You however should be able to run a light client on an HDD with minimal impact on system resources. If you wish to run a full node however, an SSD is your only option.
