### ISSUE TITLE
gasPrice returning 0

### ISSUE THREAD

**Issue by erickcrus** [ethereum/go-ethereum#23000]
My node is running for weeks, didn't have any problem until now, from 2 days to now sometimes the eth.gasPrice returns 0, the node is full synced and while the eth.gasPrice returns 0 the eth.syncing returns false, eth.blockNumber show the latest block, anyone experiencing this problem?

**Comment by ulope** [comment]
Same here. We have been seeing this for the last ~2 days.
This caused a bunch of tx with gasPrice set to `0x0` to be stuck in the txpool. 

A lot of head scratching ensued...

**Comment by erickcrus** [comment]
Someone said it is fixed on 1.10.4, but i'm not sure on how to update my current node to this UNSTABLE version.

**Comment by MariusVanDerWijden** [comment]
The problem is that having a lot of MEV transactions with 0 gas price will confuse the gas price oracle. In 1.10.4 we fixed the gas price oracle to ignore 0 gas price transactions.
You can download and build the master branch as shown here: https://geth.ethereum.org/docs/install-and-build/installing-geth#build-go-ethereum-from-source-code
