### ISSUE TITLE
Transactions that doesn't exist

### ISSUE THREAD

**Issue by zeleniy** [ethereum/go-ethereum#23023]
Issue based on [that](/ethereum/go-ethereum/issues/14669#issuecomment-854757512) and [that](/ethereum/go-ethereum/issues/14669#issuecomment-855805539) comments.

Ethereum returns correct data set as if tx was registered but some of them never appear on etherscan.io. For instance i have this one - https://etherscan.io/tx/0xbc41a7acc77f4bb07595fd2fda92ed088b07b696019afbaa14b19bbb8f7c351c.

eth_getTransactionByHash and eth_getTransactionReceipt returns null for that hash.

**Comment by ligi** [comment]
Please provide more information. This way this issue is not really actionable. It is e.g. a normal behavior when your transaction is underpriced.

**Comment by zeleniy** [comment]
You can find more information about the problem from links of [this comment](https://github.com/ethereum/go-ethereum/issues/14669#issuecomment-854757512).

Normal behavior in such case would be returning `The transaction is underpriced` or `Insufficient funds for gas * price + value` error. But no error occurs. So client application think that everything goes well but later you find that tx was never created. Does it seems normal? I don't think so.

**Comment by fjl** [comment]
It is not possible for us to guarantee that a transaction submitted to geth via RPC will be accepted by other peers and/or miners. Even if the transaction is valid in every way, other nodes may still reject it because they have a different view of the tx fee market.

Your own node will accept the transaction, and will continue to submit it to other peers as long as it is in the local pool. In fact, the pool has special handling for locally submitted transactions to ensure they are not evicted even if their fee amount is significantly below others.

etherscan.io will show the transaction before it is included *only if the tx makes it to their pool*, which is not guaranteed.
In order to ensure that your transactions will eventually be included, you can track every tx you send in your application, and send with higher fees if you find the inclusion does not happen fast enough.

**Comment by zeleniy** [comment]
> In order to ensure that your transactions will eventually be included, you can track every tx you send in your application

Are you kidding? And how long should i track them? How can i do this with API?

**Comment by zeleniy** [comment]
So anybody knows how long i should track transactions and what the tracking is?

**Comment by manoj398** [comment]
#23009

**Comment by zeleniy** [comment]
So what? One more issue closed with reference to next one. But nether of them solved. First mention of [the problem](https://github.com/ethereum/go-ethereum/issues/14672) is 2017.

**Comment by i-norden** [comment]
This isn't a problem with go-ethereum, hence the closed issues. What you're asking is how to guarantee a transaction will be mined by a remote miner or enter a specific mempool (i.e. etherscan's). You can't, it's probabilistic. Every miner is free to configure their own gas price minimums. Miners will prioritize higher priced remote txs and have finite space in their tx pools and will discard the lowest priced ones when it fills up.

> So anybody knows how long i should track transactions and what the tracking is?

You will probably want to track the transactions until 1) you see they are included in a block or 2) you see they were not included in a block within the amount of time that you wanted them to be, in which case you resubmit the tx with a higher gas price (but, importantly, the same nonce).

From your [previous comment](https://github.com/ethereum/go-ethereum/issues/14669#issuecomment-854757512) "What sence to return tx data of transaction never created. " The transaction is created when you submit it, you are the one creating it, whether or not the transaction is included in a block is another thing. And one reason it makes sense to return the tx data at this stage is that it aids you in tracking it. You can use the tx hash returned to see if it is included in a block or not. You can [subscribe](https://geth.ethereum.org/docs/rpc/pubsub) to `newHeads` and check new blocks for your tx hash.

**Comment by zeleniy** [comment]
> wait for ~12 confirmations

I can't believe. ~12 confirmations... 12!

> You can't, it's probabilistic.

Are you sure you developed something stable and reliable? Imagine you should check every INSERTion into MySQL/PostgreSQL/Oracle ~12 times.

**Comment by karalabe** [comment]
N confirmations in blockchain world means that there are N blocks mined on top of the one containing your tx. Since there's a global set of miners, in PoW chains it can happen that some miners miner on top of one reality while other on another. Probabilistically they converge fast. The reason exchanges wait for 12 blocks is because they can go bankrupt if someone sends them tokens, sells them and 15 secs later the tx gets reorged out. 

You don't need to "check 12 times". Depending on your threat model you might want to wait 1-2-12 blocks on top of the one you've first seen your tx in.
