### ISSUE TITLE
difference in etherscan and geth debug_traceTransaction

### ISSUE THREAD

**Issue by alysak6075** [ethereum/go-ethereum#23059]
if anyone can help me please:
https://etherscan.io/tx/0x89a1ed3d7e57c752a3b195ed4b584f7ac2c68e6ad532907596d7f108a90847ad/advanced
internal transactions tab lists all the transactions with the gas Limit
call_6 has a limit of 30,046
but geth debug_traceTransaction doesnt return a gas or gas used fields
how is this number calculated
geth output
{"type":"CALL","from":"0x7a250d5630b4cf539739df2c5dacb4c659f2488d","to":"0xf43c68d57f92adfaf2173422d487259a789d9b2f","value":"0x148e25f9594227c","input":"0x","output":"0x"}]}

**Comment by karalabe** [comment]
There are certain limitations of our tracing infrastructure that prevents us from reporting gas usage values for plain calls (i.e. if there's no execution inside a call, we need to guess the gas, which is not always possible).

There are a few ideas on how this could be solved, but there's nothing that I can give you now that will fix it. Unfortunately I'll close this issue since we already have a tracking open for it. Hopefully we can get it fixed in the not-too-far future.
