### ISSUE TITLE
Geth monitoring question (pidof)

### ISSUE THREAD

**Issue by jbriaux** [ethereum/go-ethereum#23174]
Hello,

I have been monitoring geth with a simple shell script for a while.
Sometimes, "pidof geth" returns nothing when geth is up and running (PID did not change, nothing weird happens in geth logs or dmesg at same timestamp).
I am wondering if this is expected or not and if there are some cases (not only for geth) of running process not reported by pidof.

Regards,

**Comment by gballet** [comment]
if the PID of geth doesn't change, then your problem is definitely with `pidof` or your Linux system. Geth doesn't have control over its pid.

Sorry we can't help you there. I advise that you check  the error code returned by `pidof` in your shell script, maybe something of significance will show up.
