### ISSUE TITLE
BAD BLOCK error: invalid merkle root

### ISSUE THREAD

**Issue by diglos** [ethereum/go-ethereum#23222]
#### System information

Geth version: `1.10.5`
OS & Version: Ubuntu 20.04/Linux ARM 64

#### Expected behaviour

Keep in sync with the rest of the network

#### Actual behaviour

We are getting a BAD BLOCK error after upgrading to 1.10.5. It may be a DB corruption but it happened right after the update. We are doing a fresh sync in another device to check if we get this error again.

Did the Go version change for this release? I asked because it may be related to ARM arch as well, see: #19754

#### Steps to reproduce the behaviour

Update from 1.10.4 to 1.10.5

#### Backtrace

[geth-bad-block-invalid-merkletree-20210716.txt](https://github.com/ethereum/go-ethereum/files/6829063/geth-bad-block-invalid-merkletree-20210716.txt)

**Comment by AusIV** [comment]
I might suggest setting `--syncmode=full --snapshot=false` and see if that fixes it. I run a bunch of nodes, and lately I've been getting BAD BLOCK errors, but disabling snapshots solves the problem. (I've not reported this myself because I'm running a fork of Geth that I believe to be introducing the mismatch between the snapshot and the chain, but it looks similar enough that those flags might solve your problem).

**Comment by karalabe** [comment]
Have snapshots finished generating?

Can you try `geth snapshot verify-state`?
