### ISSUE TITLE
Recommit interval purpose

### ISSUE THREAD

**Issue by marcelTUB** [ethereum/go-ethereum#23258]
i stumbled upon this closed issue #21359 but i don't understand why a new block is created at the start of a blockperiod rather than just before it is committed. Then it would be unnecessary to recreate the block. I probably just don't understand one of the ethereum basics. Thanks in advance!

**Comment by rjl493456442** [comment]
The new mining block is created first(with executable transactions included), but the PoW fields are still unassigned. It's the unsealed block. Then it will be sent to the miners for finding the PoW solution in order to become a complete block.

The procedure of finding the correct PoW solution may take very long time(~13s)

**Comment by marcelTUB** [comment]
But why is it used for private blockchains with clique or ibft (quorum)? Is it because Geth was developed primarily for the mainnet?

**Comment by rjl493456442** [comment]
For the other testnets(goerli, rinkeby and ropsten), there is no downside for this recommit thing. You can set this recommit interval as a large number if you want to disable it. (--miner.recommit)
