### ISSUE TITLE
Slow debug_traceCall, anyway to speed up?

### ISSUE THREAD

**Issue by t-anyu** [ethereum/go-ethereum#23271]
Hey,

My debug_traceCall via IPC / HTTP takes ~1-2s in average. Anyway to speed up this process? My CPU is Zen3, 32 threads, 64GB RAM, no userspace restrictions are applied to the geth process.

The debug_traceCall purpose is to extract LOG ops of pending transactions. Or are there any other ways to extract logs of a unconfirmed pending transaction?

Thanks!

**Comment by rjl493456442** [comment]
What's your PRC parameters?

**Comment by t-anyu** [comment]
Params are [tx_object, 'latest']

tx_object contains from, gas, gasPrice, data, to, value. Data is some arbitrary smart contract call, or empty. Smart contract call could be for example Uniswap swap.

Thanks

**Comment by rjl493456442** [comment]
You can pass an optional parameter for tracing. for example `[tx_object, 'latest', {disableStack: true, disableMemory: true, disableStorage: true}]`, so that you can disable capturing huge stack, memory and storage information. 

You can find some tracing relevant information here https://geth.ethereum.org/docs/dapp/tracing.

**Comment by t-anyu** [comment]
Wooow, thanks!!
