### ISSUE TITLE
Almost empty blocks while the mempool is congested

### ISSUE THREAD

**Issue by drlorente97** [ethereum/go-ethereum#23339]
Hello to the community of developers. I am worried about something: There are almost empty blocks (less than 30 tx) being mined on the blockchain since the London hardfork block. All of them have in common that the included trasactions have a high gas limit but, with a very low gas consumption. It is posible that setting a high gas limit to normal trasactions, could be used to intentionally attack the network by generating almost empty blocks to produce congestion?

Example:
https://etherscan.io/block/12966835
In this block the total gas limit was 28,601,046 gwei but the gas consumption was 1,920,428

**Comment by rjl493456442** [comment]
Most of the empty blocks are not intentional. In the mining procedure the Geth needs to prepare a mining block first, then do the PoW computation base on that. But the mining block preparation(packing transactions from the mempool) is not trivial which can 100-300ms. So in this time window Geth will push an empty block out first for PoW computation and then switch the target.

In the miner's perspective, the empty block is kind of the bonus otherwise the mining machines are idle.

**Comment by rjl493456442** [comment]
> All of them have in common that the included transactions have a high gas limit but, with a very low gas consumption

In this case, the remaining gas can be used for the next transaction.
For the small block, either the basefee is high enough so that users can afford the cost, or the mining pools refuse to pack more transactions. It's the choice of mining pool since they lose some transaction fee.
