### ISSUE TITLE
For bindings use interface for BoundContract instead of a struct 

### ISSUE THREAD

**Issue by krasi-georgiev** [ethereum/go-ethereum#23526]
# Rationale

Why should this feature exist?
To allow implementing custom bound contract calls
What are the use-cases?
I want to implement `BoundContractWithRetry` that keeps retrying on errors and also switches the node URL when the current node returns too many errors.
The problem is that at the moment all generated bindings use `*bind.BoundContract` and switching it to an interface will allow using custom `BoundContract` call logic

# Implementation

Do you have ideas regarding the implementation of this feature?
yes
Are you willing to implement this feature?
yes

**Comment by krasi-georgiev** [comment]
ping

**Comment by MariusVanDerWijden** [comment]
This is a *very* specific feature and I am not sure if we should really put more abstraction into the bindings in order to support it. The BoundContract already contains almost only interfaces. I'm pretty sure you can just implement your logic as a `ContractTransactor` and set that in the `BoundContract` for all bindings. You could also patch all your generated bindings to use your `ContractTransactor` in their `bindContractName` method.

**Comment by krasi-georgiev** [comment]
Aah yeah that might work, will give it a try in the next few days and will let you know. Thanks for the suggestion

**Comment by krasi-georgiev** [comment]
yes your suggestion worked very well. thanks!
