### ISSUE TITLE
Untraceable transaction using debug_traceTransaction

### ISSUE THREAD

**Issue by maxogden** [ethereum/go-ethereum#23552]
#### System information

Geth version: `1.10.8`
OS & Version: linux

#### Expected behaviour

The transaction `0x430874b252f837eecef4eefd51f94019d31b0cb2fa8cba78ebc98f33c660ade2`  can't be traced by our archive node. I also tried on etherscan and their trace times out after 60s with a 'Raw traces operation timeout' error.

I see on Etherscan that the tx cost over $6800 in gas fees, maybe that is related:

https://etherscan.io/tx/0x430874b252f837eecef4eefd51f94019d31b0cb2fa8cba78ebc98f33c660ade2

#### Steps to reproduce the behaviour

```
$ time curl -X POST -H "Content-Type: application/json" --data '{"method":"debug_traceTransaction","params":["0x430874b252f837eecef4eefd51f94019d31b0cb2fa8cba78ebc98f33c660ade2",{"tracer":"callTracer","timeout":"60s"}],"id":15295,"jsonrpc":"2.0"}' http://localhost:8545

real    0m59.282s
user    0m0.015s
sys     0m0.007s
```

**Comment by yuga-cb** [comment]
I am seeing this exact problem as well.

Hey @MariusVanDerWijden - this is very similar to https://github.com/ethereum/go-ethereum/issues/23128. Currently using debug.standardTraceBlockToFile isn't an option because our processing of these transactions is synchronous / has to keep up with the blockchain.

**Comment by maxogden** [comment]
Another tx that we can't get to trace on our archive node is `0xa76cdf87291f4f38b9ff4100b24c9070aa4c3548fa358d468a7fe495e9754d75`. It also times out on the etherscan trace (https://etherscan.io/vmtrace?txhash=0xa76cdf87291f4f38b9ff4100b24c9070aa4c3548fa358d468a7fe495e9754d75) and has $8950 worth of tx fees

**Comment by jadechip** [comment]
This seems to have occurred again for tx: `0x66bf740ad2a56c9d1d57e1bc5b0a019414bb25aa73a25e9223f92dff76eab56d`
with a whopping 2.998256343 Ether ($10,452.34)worth of fees.

**Comment by holiman** [comment]
Some transactions are too large to do over rpc: 
1. The tx is executed, each line of the trace is collected in memory, 
2. The list of trace logs is marshalled to json, 
3. The full json response is shipped over HTTP to the caller. 

In order to make this data smaller, one thing that can be done is to disable memory `{ disableMemory: true}`, aswell as `disableStorage` and `disableStack`. Of these theree, `disableMemory` is usually the biggest offender, because it shows the full memory at _every_ step of the trace. 

If the trace is hundreds of MB or even Gb, then this is bound to fail. For this specific reason, we implemented `debug.standardTraceBlockToFile( <blockhash> , <options>)`. 

This method avoids the overhead, by sending traces immediately to a `jsonl` (jsonlines) output file:
 
1. The tx is executed. For each operation, a `json` object is piped to the destination file. 

This method is capable of tracing arbitrarily large transactions. 

Example to trace a specific transaction without memory: 
```
> debug.standardTraceBlockToFile("0x0bbe9f1484668a2bf159c63f0cf556ed8c8282f99e3ffdb03ad2175a863bca63", {txHash:"0x4049f61ffbb0747bb88dc1c85dd6686ebf225a3c10c282c45a8e0c644739f7e9", disableMemory:true})
```
This will write the trace-file to the `/tmp/` folder (or whatever your OS temp folder is).

**Comment by MariusVanDerWijden** [comment]
Tracing the transaction with `standardTraceBlockToFile` takes ~3 minutes and produces a 23 GB file
`[09-09|10:17:39.902] - [09-09|10:20:13.734] `
` 23G Sep  9 10:20  block_0x0d11c419-23-0x430874b2-604245093`

**Comment by MariusVanDerWijden** [comment]
Disabling Memory and ReturnData in the RPC call lands me at 20 seconds
```
time curl -X POST -H "Content-Type: application/json" --data '{"method":"debug_traceTransaction","params":["0x430874b252f837eecef4eefd51f94019d31b0cb2fa8cba78ebc98f33c660ade2",{"tracer":"callTracer","timeout":"60s","disableMemory":true,"disableReturnData":true}],"id":15295,"jsonrpc":"2.0"}' http://localhost:8545

Executed in   20.21 secs      fish           external
   usr time    0.36 millis  363.00 micros    0.00 millis
   sys time    5.74 millis   94.00 micros    5.65 millis
```

**Comment by maxogden** [comment]
our company has been able to trace every tx in ethereum history until this new batch which are around 23M gas in a single tx. it seems the new eip-1559 gas limit is allowing these mega transactions to bog down the tracer. we rely on tracing to show our customers their accurate transaction history and balance in real time

**Comment by s1na** [comment]
Something else you can try is compressing the response, e.g. via `-H "Accept-Encoding: gzip,deflate"`. This should cut the network transfer overhead but then there's compression and decompression. I tried with a 4m gas tx:

```
ubuntu@ubuntu:~/go-ethereum$ time curl -X POST -H "Content-Type: application/json" --data '{"method":"debug_traceTransaction","params":["0xb30f9f96026d4c7dab60486e
9c5e3b19fec6094c9c524a95df90fde9a48b114b",{}],"id":15295,"jsonrpc":"2.0"}' http://localhost:8545 > trace.normal
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  206M    0  206M  100   145  23.6M     16  0:00:09  0:00:08  0:00:01 58.3M

real    0m9.040s
user    0m0.035s
sys     0m0.278s
ubuntu@geth-sync-test:~/go-ethereum$ time curl -X POST -H "Content-Type: application/json" -H "Accept-Encoding: gzip,deflate" --data '{"method":"debug_traceTransaction","p
arams":["0xb30f9f96026d4c7dab60486e9c5e3b19fec6094c9c524a95df90fde9a48b114b",{}],"id":15295,"jsonrpc":"2.0"}' http://localhost:8545 > trace.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5494k    0 5494k  100   145   917k     24  0:00:06  0:00:05  0:00:01 1450k

real    0m6.007s
user    0m0.023s
sys     0m0.023s
```

**Comment by afmsavage** [comment]
Similar issue I am experiencing on the ETH Classic core-geth client.  https://github.com/etclabscore/core-geth/issues/412

**Comment by rjl493456442** [comment]
https://github.com/ethereum/go-ethereum/pull/23558 This PR(disable the memory and returnData) should fix it. Close it now.
