### ISSUE TITLE
Node use the Intranet IP addresses linked together

### ISSUE THREAD

**Issue by kaolula** [ethereum/go-ethereum#23583]
I have five servers synchronizing the mainnet network nodes on AWS,want these five servers to broadcast transactions through the intranet p2p.I see two arguments, but I don't know how to use them
```
  --netrestrict value                 Restricts network communication to the given IP networks (CIDR masks)
  --nat value                         NAT port mapping mechanism (any|none|upnp|pmp|extip:<IP>) (default: "any")
```

**Comment by verheesj** [comment]
First, determine the IP address of the machine your bootstrap node will run on. If you are using a cloud service such as Amazon EC2, you’ll find the IP of the virtual machine in the management console. Please also ensure that your firewall configuration allows both UDP and TCP traffic on port 30303.

The bootstrap node needs to know about its own IP address in order to be able to relay it others. The IP is set using the `--nat` flag (insert your own IP instead of the example address below).

`geth --datadir data --networkid 15 --nat extip:172.16.254.4
`

Now extract the ‘node record’ of the bootnode using the JS console.

`geth attach data/geth.ipc --exec admin.nodeInfo.enr
`
This command should print a base64 string such as the following example. Other nodes will use the information contained in the bootstrap node record to connect to your peer-to-peer network.

`"enr:-Je4QEiMeOxy_h0aweL2DtZmxnUMy-XPQcZllrMt_2V1lzynOwSx7GnjCf1k8BAsZD5dvHOBLuldzLYxpoD5UcqISiwDg2V0aMfGhGlQhqmAgmlkgnY0gmlwhKwQ_gSJc2VjcDI1NmsxoQKX_WLWgDKONsGvxtp9OeSIv2fRoGwu5vMtxfNGdut4cIN0Y3CCdl-DdWRwgnZf"
`

Setting up peer-to-peer networking depends on your requirements. If you connect nodes across the Internet, please ensure that your bootnode and all other nodes have public IP addresses assigned, and both TCP and UDP traffic can pass the firewall.

If Internet connectivity is not required or all member nodes connect using well-known IPs, **we strongly recommend setting up Geth to restrict peer-to-peer connectivity to an IP subnet**. Doing so will further isolate your network and prevents cross-connecting with other blockchain networks in case your nodes are reachable from the Internet. Use the **--netrestrict flag to configure a whitelist of IP networks:**

`geth <other-flags> --netrestrict 172.16.254.0/24
`
With the above setting, Geth will only allow connections from the `172.16.254.0/24 `subnet, and will not attempt to connect to other nodes outside of the set IP range.

### Running Member Nodes

Before running a member node, you have to initialize it with the same genesis file as used for the bootstrap node.

With the bootnode operational and externally reachable (you can try `telnet <ip> <port>` to ensure it’s indeed reachable), you can start more Geth nodes and connect them via the bootstrap node using the `--bootnodes` flag.

To create a member node running on the same machine as the bootstrap node, choose a separate data directory (example: data-2) and listening port (example: 30305):

`geth --datadir data-2 --networkid 15 --port 30305 --bootnodes <bootstrap-node-record>`

With the member node running, you can check whether it is connected to the bootstrap node or any other node in your network by attaching a console and running admin.peers. It may take up to a few seconds for the nodes to get connected.

`geth attach data-2/geth.ipc --exec admin.peers`

**Comment by wemem** [comment]
I have three Amazon EC2,they are all synchronized with Ethereum node data.
The machine information
|  Machine Name   | External network ip  | Internal network ip  |
|  ----  | ----  |----  |
| EC2-A  | 70.122.90.94 |192.168.1.1 |
| EC2-B  | 70.122.91.95 |192.168.1.2 |
| EC2-C  | 70.122.92.96|192.168.1.3|
> The i.P. information on the extranet is fake,Just for better description
EC2-A machine start script
```
./geth --config ./config.toml --nat=extip:192.168.1.1 --maxpeers 10000 
```
EC2-B machine start script
```
./geth --config ./config.toml --nat=extip:192.168.1.2--maxpeers 10000 
```
EC2-C machine start script
```
./geth --config ./config.toml --nat=extip:192.168.1.3--maxpeers 10000 
```

**Information for each node** 
EC2-A nodeino
```
  enode: "enode://f2b359dc15a673145c491474c2e7830fb5a3a5d652c770ab5d8d8ab96c58f483acc8b17e31f33926c77894ee1fc7560d5f6f65c99a75687fd3eb24716f51c2ee@192.168.1.1:30311",
  enr: "enr:-J24QLPie002uZ8ootd9oDOkaCGJoEd0eJwNV231Bm3idtM5FFqkTvuJxPxMbeWkv5Je16uV-ZpspB5K1I1-XstE7lUDg2V0aMfGhPw8preAgmlkgnY0gmlwhMCoARqJc2VjcDI1NmsxoQLys1ncFaZzFFxJFHTC54MPtaOl1lLHcKtdjYq5bFj0g4RzbmFwwIN0Y3CCdmeDdWRwgnZn",
  id: "b6fe3c28cc6a3eabd9ad5eab9047611faaea3a9650e9a2237b4f654bd89f6d7e",
  ip: "192.168.1.1",
  listenAddr: "[::]:30311",
```

EC2-B nodeino
```
  enode: "enode://4da3f4aa20ff15276c1faef532cf796f93f10d85164bf4ce16a73c8eaaab96e3d6f6af6581d9cf01410d717b9fd5b22ae4bc81706b53f252006bd9ba19a20567@192.168.1.2:30311",
  enr: "enr:-J24QOoMf8CjLdpcBNBbTAqVfNySlXdbXN8An2LikjJPKwDMfiSnVP1flxDc3jLnhI8DRb_TG_CUNn2ucr0IFdeZn3sDg2V0aMfGhPw8preAgmlkgnY0gmlwhMCoAR6Jc2VjcDI1NmsxoQNNo_SqIP8VJ2wfrvUyz3lvk_ENhRZL9M4WpzyOqquW44RzbmFwwIN0Y3CCdmeDdWRwgnZn",
  id: "8b87239184918b94013e32cb43b86a0458a4b7f3df8516af56629112fa48797e",
  ip: "192.168.1.2",
  listenAddr: "[::]:30311",
```


EC2-C nodeino
```
  enode: "enode://c86df17a43d969edd5c72d6709cbbd8af04899fc7da5ecd97dc7f9863be2edc6c3d32a0c14d1451114b3d328b3d11c9836ec136e9a32e08e00f4f38d09b6e03f@192.168.1.3:30311",
  enr: "enr:-J24QGn4cFBGMiTFjZlls83jCGz0woy1XU9DCgX9uZ292SqSU59gjd-W8ZUlYRTkIGxMiqqm8WNrpuxI_z64Od1BNhMDg2V0aMfGhPw8preAgmlkgnY0gmlwhMCoAQiJc2VjcDI1NmsxoQPIbfF6Q9lp7dXHLWcJy72K8EiZ_H2l7Nl9x_mGO-LtxoRzbmFwwIN0Y3CCdmeDdWRwgnZn",
  id: "073e9fe8072d90178f347a95bb65176ec017a9a6d6bc9af113afde480d118560",
  ip: "192.168.1.3",
  listenAddr: "[::]:30311",
```
![image](https://user-images.githubusercontent.com/11549225/133870947-1c6fcd8d-ff77-420c-bb5f-950a79f602d9.png)
These three machines can broadcast transactions on the intranet machine p2p.But I found that the node identity is the intranet ip, will this prevent other machines from connecting to our machine?

**Comment by verheesj** [comment]
> I have three Amazon EC2,they are all synchronized with Ethereum node data.
> The machine information
> Machine Name 	External network ip 	Internal network ip
> EC2-A 	70.122.90.94 	192.168.1.1
> EC2-B 	70.122.91.95 	192.168.1.2
> EC2-C 	70.122.92.96 	192.168.1.3
> 
> > The i.P. information on the extranet is fake,Just for better description
> > EC2-A machine start script
> 
> ```
> ./geth --config ./config.toml --nat=extip:192.168.1.1 --maxpeers 10000 
> ```
> 
> EC2-B machine start script
> 
> ```
> ./geth --config ./config.toml --nat=extip:192.168.1.2--maxpeers 10000 
> ```
> 
> EC2-C machine start script
> 
> ```
> ./geth --config ./config.toml --nat=extip:192.168.1.3--maxpeers 10000 
> ```
> 
> **Information for each node**
> EC2-A nodeino
> 
> ```
>   enode: "enode://f2b359dc15a673145c491474c2e7830fb5a3a5d652c770ab5d8d8ab96c58f483acc8b17e31f33926c77894ee1fc7560d5f6f65c99a75687fd3eb24716f51c2ee@192.168.1.1:30311",
>   enr: "enr:-J24QLPie002uZ8ootd9oDOkaCGJoEd0eJwNV231Bm3idtM5FFqkTvuJxPxMbeWkv5Je16uV-ZpspB5K1I1-XstE7lUDg2V0aMfGhPw8preAgmlkgnY0gmlwhMCoARqJc2VjcDI1NmsxoQLys1ncFaZzFFxJFHTC54MPtaOl1lLHcKtdjYq5bFj0g4RzbmFwwIN0Y3CCdmeDdWRwgnZn",
>   id: "b6fe3c28cc6a3eabd9ad5eab9047611faaea3a9650e9a2237b4f654bd89f6d7e",
>   ip: "192.168.1.1",
>   listenAddr: "[::]:30311",
> ```
> 
> EC2-B nodeino
> 
> ```
>   enode: "enode://4da3f4aa20ff15276c1faef532cf796f93f10d85164bf4ce16a73c8eaaab96e3d6f6af6581d9cf01410d717b9fd5b22ae4bc81706b53f252006bd9ba19a20567@192.168.1.2:30311",
>   enr: "enr:-J24QOoMf8CjLdpcBNBbTAqVfNySlXdbXN8An2LikjJPKwDMfiSnVP1flxDc3jLnhI8DRb_TG_CUNn2ucr0IFdeZn3sDg2V0aMfGhPw8preAgmlkgnY0gmlwhMCoAR6Jc2VjcDI1NmsxoQNNo_SqIP8VJ2wfrvUyz3lvk_ENhRZL9M4WpzyOqquW44RzbmFwwIN0Y3CCdmeDdWRwgnZn",
>   id: "8b87239184918b94013e32cb43b86a0458a4b7f3df8516af56629112fa48797e",
>   ip: "192.168.1.2",
>   listenAddr: "[::]:30311",
> ```
> 
> EC2-C nodeino
> 
> ```
>   enode: "enode://c86df17a43d969edd5c72d6709cbbd8af04899fc7da5ecd97dc7f9863be2edc6c3d32a0c14d1451114b3d328b3d11c9836ec136e9a32e08e00f4f38d09b6e03f@192.168.1.3:30311",
>   enr: "enr:-J24QGn4cFBGMiTFjZlls83jCGz0woy1XU9DCgX9uZ292SqSU59gjd-W8ZUlYRTkIGxMiqqm8WNrpuxI_z64Od1BNhMDg2V0aMfGhPw8preAgmlkgnY0gmlwhMCoAQiJc2VjcDI1NmsxoQPIbfF6Q9lp7dXHLWcJy72K8EiZ_H2l7Nl9x_mGO-LtxoRzbmFwwIN0Y3CCdmeDdWRwgnZn",
>   id: "073e9fe8072d90178f347a95bb65176ec017a9a6d6bc9af113afde480d118560",
>   ip: "192.168.1.3",
>   listenAddr: "[::]:30311",
> ```
> 
> ![image](https://user-images.githubusercontent.com/11549225/133870947-1c6fcd8d-ff77-420c-bb5f-950a79f602d9.png)
> These three machines can broadcast transactions on the intranet machine p2p.But I found that the node identity is the intranet ip, will this prevent other machines from connecting to our machine?

Setting up peer-to-peer networking depends on your requirements. If you connect nodes across the Internet, please ensure that your bootnode and all other nodes have public IP addresses assigned, and both TCP and UDP traffic can pass the firewall.

**Comment by holiman** [comment]
> ./geth --config ./config.toml --nat=extip:192.168.1.3--maxpeers 10000 

This is wrong -- you're telling geth to use the internal IP as the external IP. You should insted use `--nat=extip:70.122.92.96`. 

And to answer this question: 

> But I found that the node identity is the intranet ip, will this prevent other machines from connecting to our machine?

Yes (but no). So yes, it will prevent incoming connections, which accounts for up to half the peer slots. However, the other half is outgoing connections, which will still work. So your nodes will still be able to connect to external peers (but only those that have a public ip address.)

**Comment by wemem** [comment]
> > ./geth --config ./config.toml --nat=extip:192.168.1.3--maxpeers 10000
> 
> This is wrong -- you're telling geth to use the internal IP as the external IP. You should insted use `--nat=extip:70.122.92.96`.
> 
> And to answer this question:
> 
> > But I found that the node identity is the intranet ip, will this prevent other machines from connecting to our machine?
> 
> Yes (but no). So yes, it will prevent incoming connections, which accounts for up to half the peer slots. However, the other half is outgoing connections, which will still work. So your nodes will still be able to connect to external peers (but only those that have a public ip address.)

If i set --nat use external Ip,
for example:
EC2-A machine start script
```
./geth --config ./config.toml --nat=extip:70.122.90.94 --maxpeers 10000 
```
EC2-B machine start script
```
./geth --config ./config.toml --nat=extip:70.122.90.95 --maxpeers 10000 
```
EC2-C machine start script
```
./geth --config ./config.toml --nat=extip:70.122.90.96 --maxpeers 10000 
```
Then these three machines all use the public network for p2p broadcast transactions, right?

**Comment by holiman** [comment]
> Then these three machines all use the public network for p2p broadcast transactions, right?

They will alwys do that, regardless fo what you set extip to. Whether or not to connect to mainnet peers or not can be influenced by netrestrict (prevent peering outside your bubble) or `--networkid` (connect only to peers on your specific ethereum network id)

**Comment by wemem** [comment]
> > Then these three machines all use the public network for p2p broadcast transactions, right?
> 
> They will alwys do that, regardless fo what you set extip to. Whether or not to connect to mainnet peers or not can be influenced by netrestrict (prevent peering outside your bubble) or `--networkid` (connect only to peers on your specific ethereum network id)

Ok,Thank you very much for your answer

**Comment by holiman** [comment]
Seems resolved, closing this
