### ISSUE TITLE
Blockpool API

### ISSUE THREAD

**Issue by obscuren** [ethereum/go-ethereum#236]
For the client (mist) I need to give the user an indication it's doing *something*. A great way to show progress is by giving the user progression of catching up on the network.

The previous version of the block chain had a couple of methods which would allow me to get certain information such as:

- [ ] Amount of hashes fetched
- [ ] Amount of blocks downloaded
- [ ] Flag "downloading"

**Comment by obscuren** [comment]
@zelig status?

**Comment by zelig** [comment]
clarification needed: 
- amount of hashes fetch : since the start of this uptime? or we need to persist something acrosss sessions? 
- amount of blocks: since when, see above. Should this include superseeded forks?
Im asking cos these numbers are pretty meaningless, apart from maybe their rate of change is informative of processing burden and/or network health.
- flag for downloading: the problem is, in the model i have there is no such thing as downloading as something different from keeping in sync which is normal operation. I could indicate if there are no active fetching processes, this may be useful to indicate network issues but if online with 12 sec blocktime idleness aint gonna happen.

Apart from this info, the blockpool could provide a lot more (useful?) data, see below a few ideas. This leads me back to @fjl 's idea that each protocol has its own peer pool/peer selector. The blockpool could also keep (or give info to) a permanent record of peer usefulness (activity rate, best peer rate, etc) which in the future could feed into a reputation scheme driving peer selection (beyond kademlia principles). 

API:
blah:
```go
func (self *BlockPool) NumberOfBlockHashes() int
func (self *BlockPool) NumberOfBlockHashes() int
func (self *BlockPool) Syncing() bool
```
or better:

type Status struct {
BlockHashes int // number of hashes fetched this session 
Blocks int // number of blocks fetched this session
NewBlocks int // number of new blocks (received with new blocks msg) 
InsertedBlocks int // number of blocks inserted/connected to the blockchain 
ValidBlocks int // number of blocks inserted and actually valid
LongestChain int // the longest chain inserted since the start of session (aka session blockchain height)

Peers int // cumulative number (or full list) of all different registered peers since the start of this session
ActivePeers int // cumulative number (or full list) of all different peers that contributed a hash or block since the start of this session
LivePeers int // live peers registered with the block pool (supposed to be redundant but good sanity check 
BestPeer []byte //Pubkey
BestPeers [][]byte // the cumulative list of all peers that at some point were promoted as best peer (peer with highest TD status) this session
BadPeers [][]byte // number or list of all peers that violated the protocol (invalid block or pow, unrequested hash or block) 
// etc etc
}

// and the API is the extendibe:
func (self *BlockPool) Status() *Status

**Comment by obscuren** [comment]
I like the idea of having a status per protocol. Information required is

* total hashes downloaded
* total blocks downloaded
* flag actively downloading blocks

Information can be "since startup". 

Actively downloading blocks is mainly used during catching up. People like to see progress.

**Comment by zelig** [comment]
API:
``` go
func (b *BlockPool) Status() *Status 
```

Status is reporting about the BlockPool. Cumulative counts report over the period of this session (since start of the blockpool = launch of client)

Status Public Fields:

``` go
Syncing           bool   // true if requesting, updating etc, false if idle

BlockHashes       int    // number of hashes fetched 
BlockHashesInPool int    // number of hashes currently in the pool
Blocks            int    // number of blocks fetched 
BlocksInPool      int    // number of blocks currently in the pool
BlocksInChain     int    // number of blocks inserted/connected to the blockchain ()
NewBlocks         int    // number of new blocks (received with new blocks msg) 
Forks             int    // number of chain forks in the blockpool 
LongestChain      int    // the longest chain inserted (aka session blockchain height)

Peers             int    // cumulative number of all different registered peers
ActivePeers       int    // cumulative number of all different peers that contributed a hash or block 
LivePeers         int    // number of live peers registered with the block pool (supposed to be redundant but good sanity check
BestPeers         int    // cumulative number of all peers that at some point were promoted as best peer (peer with highest TD status) 
BadPeers          int    // cumulative number of all peers that violated the protocol (invalid block or pow, unrequested hash or block, etc)
```
