### ISSUE TITLE
Binary search for common ancestor should not use remote height as max value

### ISSUE THREAD

**Issue by ferranbt** [ethereum/go-ethereum#23604]
#### System information

This behaviour was found on Polygon PoS (upstream v1.10.8) but I think it also affects Go-ethereum.

#### Expected behaviour

At startup, local Geth node is at block A (local header=local full block=local full block=A) and target sync node is at block B. To find an ancestor, local Geth uses binary search in the span (A-max reorgs, B). Does it make sense to search in (A, B) knowing that local Geth should not have any of those blocks? In normal conditions, if local Geth is synced with the correct chain, the ancestor will be A.

#### Actual behaviour

We are experiencing that during the binary search, the common ancestor block is between A and B. I am not sure why is this happening but it might be due to the fact that Geth syncs headers in advance. Finding the wrong common ancestor is leading to huge memory allocations and immediate shutdowns.

I think a simple fix would be to limit the ancestor binary search span to (A-max reorgs, A). Would you accept a PR with this fix?

**Comment by holiman** [comment]
> We are experiencing that during the binary search, the common ancestor block is between A and B.

That is because it's erroneously named. There are two things at play here. 

- For the blockchain, the common ancestor is the first block where the two chains have the same block. 
- However, the downloader is not really concerned about which is canon and which is side. It just wants to deliver blocks to the blockchain. Therefore, what the downloader tries to do, is not "identify the common ancestor", but instead "for the chain that the remote part is on, what is the earliest block that we already have locally?". 

This behaviour was changed, in https://github.com/ethereum/go-ethereum/pull/18085 for example. The reason for this change was that there was consensus-issues on ropsten, which caused very long non-canon sidechains. 

Say you have a fork at block N. Now, there are two chains, N->M1 (canon) and N->M2 (side). Both of them are 10K blocks long. 

If we look for the "blockchain common ancestor", then every time we connect to a peer on M2, the downloader will find N to be the "common ancestor". It will thus download the 10K blocks in N->M2, and deliver to the blockchain. The blockchain will start executing them, and find that "Hey, N+1 is bad", and promptly ignore them. Then that scenario happens again and again and again. 

So we changed it. Now, instead, the we only download N->M2 once. The blockchain rejects them (but stores them), and the next time with hit a sidechain-peer, we will not download the entire N->M2 chain all over again. 
 

> Finding the wrong common ancestor is leading to huge memory allocations and immediate shutdowns.

That doesn't sound great. Any more info about that?

**Comment by ferranbt** [comment]
Okay, so there must be something else. This are the logs from the machine:
```
```

**Comment by ferranbt** [comment]
I have another trace for the problem from another of our nodes (remember that this is Polygon). I have added a couple of logs more (I mixed real outputs from some Println traces I manually added):
```
INFO [09-20|13:05:08.487] Loaded most recent local header          number=19,184,708 hash=9ff64a..d718a2 td=219,472,701 age=3d14h11m
INFO [09-20|13:05:08.487] Loaded most recent local full block      number=19,104,548 hash=e0d86a..d0d6aa td=218,150,856 age=5d20h17m
INFO [09-20|13:05:08.487] Loaded most recent local fast block      number=19,113,098 hash=db56a2..4e5347 td=218,284,470 age=5d14h57m
...
DEBUG [09-20|13:05:22.855] Found common ancestor                    peer=d70f89eb number=19,224,281 hash=a69420..4824c2
```
insertChain() from 19224282 to 19224490.
```
DEBUG [09-20|13:05:25.028] Pruned ancestor, inserting as sidechain  number=19,224,282 hash=8c0adb..0a170f
DEBUG [09-20|13:05:25.029] Injected sidechain block                 number=19,224,282 hash=8c0adb..0a170f diff=18 elapsed="727.779µs" txs=103 gas=20,519,744 uncles=0 root=5fafd4..3c8d71
DEBUG [09-20|13:05:25.041] Injected sidechain block                 number=19,224,283 hash=685fce..efb93a diff=18 elapsed="352.606µs" txs=110 gas=20,544,523 uncles=0 root=af47b7..c76c1a
DEBUG [09-20|13:05:25.071] Injected sidechain block                 number=19,224,284 hash=8d67d0..68adba diff=18 elapsed="62.104µs"  txs=0   gas=0          uncles=0 root=af47b7..c76c1a
DEBUG [09-20|13:05:25.073] Injected sidechain block                 number=19,224,285 hash=cba627..aa36a3 diff=18 elapsed="395.99µs"  txs=87  gas=20,591,855 uncles=0 root=93fbac..eb522d
DEBUG [09-20|13:05:25.119] Injected sidechain block                 number=19,224,286 hash=57cef5..8fbd8a diff=18 elapsed="346.104µs" txs=51  gas=20,610,133 uncles=0 root=9ab22a..a7fd18
DEBUG [09-20|13:05:25.137] Injected sidechain block                 number=19,224,287 hash=f7840a..0ba7ce diff=18 elapsed="803.914µs" txs=156 gas=20,634,449 uncles=0 root=017cd2..71547f
...
DEBUG [09-20|13:05:27.388] Injected sidechain block                 number=19,224,489 hash=56468e..036174 diff=18 elapsed="523.477µs" txs=303 gas=20,430,562 uncles=0 root=a40a7c..41a252
DEBUG [09-20|13:05:27.398] Injected sidechain block                 number=19,224,490 hash=2f000b..2f2e09 diff=18 elapsed="469.807µs" txs=239 gas=20,403,319 uncles=0 root=8b6888..112a8e
INFO [09-20|13:08:04.507] Importing heavy sidechain segment        blocks=956 start=19,183,783 end=19,184,738
```
insertChain() from 19183783 to 19184738.
writeBlockWithState() block 19183783
reorg() (oldblock=19104548, newBlock=19183783)

---

Note that it tries to reorg from the current full block to the sync target. At that point it crashes because it cannot allocate 79235 blocks on memory. I would assume that even with enough memory it would show ```Impossible reorg, please file an issue``` with oldnum=newnum.

**Comment by holiman** [comment]
This is not relevant any longer
