### ISSUE TITLE
Disallow creation of empty contracts

### ISSUE THREAD

**Issue by MrChico** [ethereum/go-ethereum#2367]
Is there any reason why anyone would want to create a contract without any code?

It seems that it mostly happens by accident when users fail to specify the recipient of an ether transfer in one way or another, causing them to lose their money.

**Comment by obscuren** [comment]
We cannot not allow it because it poses a restriction on the actual usability and functionality on the client. One way to see Geth and its libraries is as a backend that is hackable, tuneable and offers you little to no actual restrictions other than those defined in the protocol. 

If such a restriction is to be added it would be any of the frontends (e.g. Mist). I suggest that you open up a feature request on the mist repo if you wish for this type of restriction to be added. 

Closing this because it's not an actual issue.
