### ISSUE TITLE
rpc: JSON integers are accepted for numeric arguments

### ISSUE THREAD

**Issue by gavofyork** [ethereum/go-ethereum#2384]
#### System information

Geth version: all versions
OS & Version: Windows/Linux/OSX
Commit hash : all versions
#### Expected behaviour

Note spec at https://github.com/ethereum/wiki/wiki/JSON-RPC:

> When encoding QUANTITIES (integers, numbers): encode as hex, prefix with "0x", the most compact representation (slight exception: zero should be represented as "0x0").

Make JSONRPC call and give a JSON integer as an argument; expected result is "Invalid Arguments" error.
#### Actual behaviour

geth interprets the JSON integer as the according `QUANTITY` argument.
#### Steps to reproduce the behaviour

Given above.

**Comment by obscuren** [comment]
As long as the return values are proper I don't care all that much. Parity is broken in that regard, see https://github.com/ethereum/go-ethereum/issues/2370#issuecomment-199750867

**Comment by tinybike** [comment]
RPC is basically for dapps / used by dapp developers.  Every dapp developer I'm aware of currently uses geth.  If you change geth to make it conform to a different spec, this will almost certainly break currently functioning dapps.  My suggestion: **snapshot geth's current implementation and define that as the spec**, since it is already the de facto spec for everyone using the RPC system.

**Comment by fjl** [comment]
Fixed by #3475
