### ISSUE TITLE
I have been using this nginx config for ssl geth rpc url. But it's not working.

### ISSUE THREAD

**Issue by AJONCODE** [ethereum/go-ethereum#23911]
```
server {
        listen 8544 ssl http2;
        #server_name _;
        server_name my_domain;

        listen 443 ssl; # managed by Certbot
        ssl_certificate /etc/letsencrypt/live/my_domain/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/my_domain/privkey.pem; # managed by Certbot        
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

        location / {
                proxy_set_header   Host $host:$server_port;
                proxy_set_header   X-Real-IP $remote_addr:8544;
                proxy_set_header   X-Forwarded-Proto "https";
                proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Port 8544;
                proxy_pass         http://127.0.0.1:8545;
        }

}
```

**Comment by holiman** [comment]
Sorry, but this is really not a ticket demonstrating a bug in geth. For one, it's a configuration problem with setting up an nginx reverse proxy. 
Secondly, saying "it's not working" doesn't really help. Instead of saying "it's not working", you need to dive in a bit into _how_ it is not working. 

Are the requests not forwarded to geth? Or are they not served? Or are they served but with errors?
In order to figure this out, some ideas come to mind, 

- Check the nginx logs
- Check the geth logs
- Do a packet capture on the geth-host / port (`8545`) to see if the requests are coming in, 
- Open a 'random' web-server on `8545` and see if the forwarding works, 

If you are able to narrow down the problem, and indeed it appears to be something which is broken/changed in geth, feel free to reopen this ticket.
