### ISSUE TITLE
personal_unlockAccount takes much time, expected?

### ISSUE THREAD

**Issue by hievan2016** [ethereum/go-ethereum#2393]
#### System information

Geth
Version: 1.3.5
Git Commit: 34b622a24853e1cf550238e8c8be6dfa4178cd35
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.6
OS: linux

#### Actual behaviour

We use personal_unlockAccount RPC API to unlock an account, seems the time used to finish this
operations is somehow related to the number of miner threads started, that is, more time is used
when more miner threads are started, is this expected?

Below is the time used (second) vs miners, 

1-2s          1  miner
~20s         2  miners
~50s         4 miners

The questions are:

1. is it expected? 
2. And is any solution to reduced the time used to unlock an account (except using less miners)?

#### Steps to reproduce the behaviour

1. start geth using this cmd with --minerthreads  1/2/4/... separately

./geth --rpc --rpcaddr="0.0.0.0" --rpccorsdomain="*" --rpcapi="db,eth,net,web3,personal,web3"  --verbosity=3 --maxpeers=0  --networkid 482771 --genesis ~/test/genesis.json --nodiscover --datadir ~/.hdether --minerthreads="1" --mine

2. run this cmd to see the time used for each case

date; curl http://localhost:8545 -X post --data '{"jsonrpc":"2.0","method":"personal_unlockAccount","params":["0x2ba878e691f4fb6c934a7a4b8abc7022186a7a5a", "123456", 30000000],"id":1}'; date

Ie. the outout for 4 miners is (51s)

ubuntu@VM-44-75-ubuntu:~$ date; curl http://localhost:8545 -X post --data '{"jsonrpc":"2.0","method":"personal_unlockAccount","params":["0x2ba878e691f4fb6c934a7a4b8abc7022186a7a5a", "123456", 30000000],"id":1}'; date
Thu Mar 31 13:26:24 CST 2016
curl: (52) Empty reply from server
Thu Mar 31 13:27:15 CST 2016

#### Backtrace

````
[backtrace]
````

**Comment by bas-vk** [comment]
It is hard to determine if this is expected in your situation. It depends on free available cpu's. Unlocking an account takes significant cpu resources and if miners (or other processes) are using these cpu's then they will be shared. That will cause the unlock to take more time. Since you described a relation between the number of miners and the time it takes to unlock this is probably the scenario.

You have several options:
1. don't use account management in geth but use external signing and submit transactions with [eth_sendRawTransaction](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sendrawtransaction). You can unlock/sign messages on a different computer which is not mining, or use a different algorithm to protect your keys which is lighter and secure enough for your situation. If you are using web3 Consensys made something that you might want to take a [look at](https://github.com/ConsenSys/hooked-web3-provider).
2. Use the `lightkdf` parameter. This uses the same algorithm but with reduced security margin. It is up to you to determine if this is secure enough for your situation. Note, this is **not** recommended and only works with new keys.

**Comment by hievan2016** [comment]
Thanks for the reply, your are right, after increasing the # of CPU cores, the performance is improved.

Will find some time to test the lightkdf option.
