### ISSUE TITLE
Wrong gas estimate by eth_estimateGas

### ISSUE THREAD

**Issue by trapp** [ethereum/go-ethereum#2395]
#### System information

Geth version: 1.4.0-unstable
OS & Version: OSX 
Commit hash : f93758bf64ea6d8720ceccca4c6b183d25cda30d

#### Expected behaviour

`eth_estimateGas` should return exactly the amount of gas that the execution would take.

#### Actual behaviour

`eth_estimateGas` returns the value of the parameter gas when the execution would fail.

#### Steps to reproduce the behaviour

One example is estimating gas of the now closed digix crowd sale contract: 
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"to":"0xf0160428a8552ac9bb7e050d90eeade4ddd52843","value":"0xff22","gasPrice":"0x051da038cc","gas":"0xffffff"}],"id":1}' http://localhost:8545
-> {"jsonrpc":"2.0","id":1,"result":"0xffffff"}
```

Geth says a transaction would use several millions of gas for its execution.

However, an actual transaction only uses 121,000 gas because the execution fails: http://etherscan.io/tx/0xf0512cb94a5c04643cbc846f70e7308f6e81c44097da61a42a4b9b86f3565fda

Gas estimates should be correct, whether the execution succeeds or fails.

**Comment by obscuren** [comment]
Cheers. Yes I've I can confirm this issue. I've also figured what the problem is. 

The value returned to estimate the gas is the same value returned that figures out the exact amount of gas used, however, the gas used may not always be the amount of gas required. The gas used amount is the normalised value which includes suicides and storage clearings.

In order to fix this issue we need to patch up the `core.ApplyMessage` the return not only the gas used but also the actual amount it needed to run the entire transition **without** the reductions.

**Comment by obscuren** [comment]
Linked commit fixes the issue

**Comment by trapp** [comment]
I tried it with 1f3596c25af077a3303c554ee6b49404b20f7117 but it still returns whatever I put in as gas:

```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"to":"0xf0160428a8552ac9bb7e050d90eeade4ddd52843","value":"0xff22","gasPrice":"0x051da038cc","gas":"0xfffffffff"}],"id":1}' http://localhost:8545
{"jsonrpc":"2.0","id":1,"result":"0xfffffffff"}
```

0xfffffffff = 68 billion gas.

It would be good to indicate that the execution would fail but that's probably out of scope for this method.
