### ISSUE TITLE
eth_sign: JSON RPC spec and Go API are not conform

### ISSUE THREAD

**Issue by Georgi87** [ethereum/go-ethereum#2397]
The JSON-RPC interface describes that the data returned from the eth_sign call is the signed data while the go implementation signs a hash of the data:

https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sign

Go:
https://github.com/ethereum/go-ethereum/blob/develop/eth/api.go#L1108
```
func (s *PublicTransactionPoolAPI) Sign(address common.Address, data string) (string, error) {
	signature, error := s.am.Sign(accounts.Account{Address: address}, common.HexToHash(data).Bytes())
	return common.ToHex(signature), error
}
```

**Comment by obscuren** [comment]
Thank you for reporting this. There are at the moment two issues:

* The specification is wrong (you should always sign hashes, not data)
* The implementation's function definition is wrong; `data string` should be `common.Hash`

**Comment by obscuren** [comment]
Implementation fixed. See linked PR. Will address the spec soon.

**Comment by Georgi87** [comment]
Thank you!

**Comment by kumavis** [comment]
https://github.com/ethereum/go-ethereum/pull/2402#issuecomment-239565949
its important that the `eth_sign` request passes in the message and not the hash, so that the id mgmt (browser/wallet) can show the message to the user for approval before signing. internally the id mgmt should hash the message then sign it, but that should not affect the parameters in `eth_sign` method

the danger of passing in just a hash is that it could be the hash of a tx that the user is not aware the are signing for

**Comment by fjl** [comment]
Feeding the message into the signing function without hashing allows extraction of the private key.
This issue is **not fixed**. I don't know why we changed it like this, but the go-ethereum eth_sign endpoint **does not** hash the message, but forces the message to be 32 bytes long, assuming that it is a hash of some kind.

**Comment by fjl** [comment]
A better fix would be to deprecate eth_sign and create a new method, perhaps `personal_sign`, that hashes the passed message prior to signing it.

**Comment by Georgi87** [comment]
I would argue that not sending hashes but clear text to a (remote) rpc-node would also raise privacy concerns. Maybe eth_sign could sign a sent hash together with a random salt and return signature and salt?

**Comment by fjl** [comment]
personal_sign is being added in #2940.

**Comment by kumavis** [comment]
> I would argue that not sending hashes but clear text to a (remote) rpc-node would also raise privacy concerns.

im not sure in what case you would be doing this

**Comment by Georgi87** [comment]
Agreed @kumavis
