### ISSUE TITLE
Is there a way to get a partial archived node?

### ISSUE THREAD

**Issue by TonyHzr** [ethereum/go-ethereum#24063]
Hello, I want to analyze the data on Ethereum, which may require a archived node. But in fact, I only care about the blocks after 8,000,000  blocks height. 

So is there any way to directly request the world state at that height and get a partial archived node?

**Comment by holiman** [comment]
The closest way to do that is to sync `syncmode=full` from genesis. Once you reach `8M`, you need to stop the node, and then use `gcmode=archive`. That will make it so that you will prune most of the data up to 8M, but from 8M onwards you will have every state. 

It is theoretically possible to do a snap-sync to block 8M, but it would require that you modify geth to target a particular block (and not move the pivot along the way), and it would also require that you find an archive node which has that state available, which is very _very_ unlikely.

**Comment by holiman** [comment]
Follow-up: you only need an archive node if you are really interested in the 'state' data, e.g. balances and storage at certain heights. If you're only interested in the block data (transactions / receipts / headers etc) , a regular node would suffice.

**Comment by martinboehm** [comment]
@holiman Hi, we have an archive node, which we use to fetch internal transactions. After the internal transactions are processed, the archive data are not interesting for us. To save the disk space (and also time), we would like to do the following:

1. fully sync archive node and process the internal transactions up to the last block
2. delete the geth database, keep only the ancient folder
3. let the DB sync from the ancient, still using archive mode (or possibly only full mode, I am not sure)
4. after the sync is finished, switch to archive mode (if not already in it) and keep processing new internal transactions

After the DB grows again to too large size, repeat.

Is this scenario feasible? Are there some issues with it?

**Comment by holiman** [comment]
@martinboehm that doesn't make sense to me. 



> 1.  fully sync archive node and process the internal transactions up to the last block

Ok, so while doing this, you can process internal transactions. You don't actually need the state for block `5` while you process block `13M`, so you don't actually _need_ archive, if you instead process while you import each block. 

> 2.     delete the geth database, keep only the ancient folder

Ok, save the block data, nuke the state. 

> 3.  let the DB sync from the ancient, still using archive mode (or possibly only full mode, I am not sure)

This means doing a new (archive-) sync from genesis. I see no point in doing this. After doing this, you're back at point one. You're probably better off doing a snap-sync at this point, if you don't want old state-data to be present. 

> 4.   after the sync is finished, switch to archive mode (if not already in it) and keep processing new internal transactions

Again, you can just process these in lock-step with the import.

**Comment by holiman** [comment]
> The question is if something would be missing from the DB if we restore it in snap-sync or full mode using ancient data? We need transaction data, transaction logs but not the debug info.

Ancient data is only block data. If you "sync from ancient data", the only possible sync is block by block import.

However, if you do a `snap` sync, you can still "make use of" your ancient data, simply by making it available to geth. Then geth will avoid downloading ~500GB of data from the network (but the the state is still downloaded from the network). 


If you want to partition your nodes have different "epochs" of responsibility, then snap-sync is not very useful for you: a snap-sync can only sync to "now" -- since only recent state is available on the network. So it's not possible to snap-sync to e.g. block 10M. So that kind of forces you to use block-by-block sync...

... although, technically that's not really true. It would be possible (but not trivial) to make it so that you snap-sync off your own archive node, which _can_ serve the historic state you are interested in. So theoretically, your node 2 could sync to "state at 10M" off the archive node, and then it could import `1M` blocks in archive mode, and you'd have a node which is "archive from 10M to 11M". But that requires a bit of programming to pull off

**Comment by martinboehm** [comment]
It would be OK for us to do `snap sync` to "now", if we could afterwards switch to `archive` mode. Is it possible?

**Comment by holiman** [comment]
Yes it is perfectly possible.

**Comment by Sharath11** [comment]
@holiman how to do` snap sync` to "now", and switch to `archive` mode?
First do I need to start using flag `--syncmode snap` and let it sync to current time then restart the node by adding `--gcmode archive` or do I need to start the node with `--syncmode snap --gcmode archive` ?

**Comment by duyhuynhdev** [comment]
> Follow-up: you only need an archive node if you are really interested in the 'state' data, e.g. balances and storage at certain heights. If you're only interested in the block data (transactions / receipts / headers etc) , a regular node would suffice.

Does that mean we can get all transactions from the Genesis block using a full node?
