### ISSUE TITLE
Archival node - "required historical state unavailable"

### ISSUE THREAD

**Issue by playmint-jbr** [ethereum/go-ethereum#24070]
#### System information

Geth version: `geth version`
Geth
Version: 1.10.13-stable
Git Commit: 7a0c19f813e285516f4b525305fd73b625d2dec8
Git Commit Date: 20211124
Architecture: amd64
Go Version: go1.17.2
Operating System: windows
GOPATH=
GOROOT=go

OS & Version: Windows/Linux/OSX
Window 10 x64
Commit hash : (if `develop`)

#### Expected behaviour
debug_traceTransaction RPC calls should return traces

#### Actual behaviour
"required historical state unavailable"

#### Steps to reproduce the behaviour
geth --rinkeby --gcmode=archive --http --http.api=eth,net,web3,debug
Wait until synced, then attempt to trace a transaction/call

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by holiman** [comment]
Please provide an exact details about the call you try to trace, and the startup logs from the node. 
`

**Comment by spectre1989** [comment]
> Please provide an exact details about the call you try to trace, and the startup logs from the node. `

Sorry between posting the issue and you replying I tried clearing the db and syncing again with --syncmode=full so it's going to take a while before it's done. Should it work without `--syncmode=full`?

The details for the call I'm trying to trace, I'm using truffle debug:
`truffle debug --network rinkeby 0xe41ed22ef238c3b5150d7f96c86e5f593aa7e66dd0b4b8ccf7b8f0e0c714f056`

Here's the Geth output to cmd from startup:

> PS C:\Users\joebe\Desktop> geth --rinkeby --gcmode=archive --http --http.api=eth,net,web3,debug
INFO [12-06|13:08:16.889] Starting Geth on Rinkeby testnet...
INFO [12-06|13:08:16.891] Maximum peer count                       ETH=50 LES=0 total=50
WARN [12-06|13:08:16.899] Disable transaction unindexing for archive node
INFO [12-06|13:08:16.899] Enabling recording of key preimages since archive mode is used
INFO [12-06|13:08:16.899] Set global gas cap                       cap=50,000,000
INFO [12-06|13:08:16.899] Allocated trie memory caches             clean=307.00MiB dirty=0.00B
INFO [12-06|13:08:16.900] Allocated cache and file handles         database=C:\Users\joebe\AppData\Local\Ethereum\rinkeby\geth\chaindata cache=512.00MiB handles=8192
INFO [12-06|13:08:18.465] Opened ancient database                  database=C:\Users\joebe\AppData\Local\Ethereum\rinkeby\geth\chaindata\ancient readonly=false
INFO [12-06|13:08:18.473] Persisted trie from memory database      nodes=355 size=50.43KiB time="573.8µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [12-06|13:08:18.476] Initialised chain configuration          config="{ChainID: 4 Homestead: 1 DAO: <nil> DAOSupport: true EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 1035301 Constantinople: 3660663 Petersburg: 4321234 Istanbul: 5435345, Muir Glacier: <nil>, Berlin: 8290928, London: 8897988, Arrow Glacier: <nil>, Engine: clique}"
INFO [12-06|13:08:18.477] Deep froze chain segment                 blocks=2 elapsed=9.883ms number=9,677,496 hash=2825b7..5b5b46
INFO [12-06|13:08:19.334] Initialising Ethereum protocol           network=4 dbversion=8
INFO [12-06|13:08:19.430] Loaded most recent local header          number=9,767,496 hash=46111b..431b53 td=16,381,904 age=17s
INFO [12-06|13:08:19.430] Loaded most recent local full block      number=9,767,496 hash=46111b..431b53 td=16,381,904 age=17s
INFO [12-06|13:08:19.430] Loaded most recent local fast block      number=9,767,496 hash=46111b..431b53 td=16,381,904 age=17s
INFO [12-06|13:08:19.430] Loaded last fast-sync pivot marker       number=9,767,201
INFO [12-06|13:08:19.498] Loaded local transaction journal         transactions=0 dropped=0
INFO [12-06|13:08:19.499] Regenerated local transaction journal    transactions=0 accounts=0
WARN [12-06|13:08:19.500] Switch sync mode from fast sync to full sync
INFO [12-06|13:08:19.503] Gasprice oracle is ignoring threshold set threshold=2
INFO [12-06|13:08:19.504] Starting peer-to-peer node               instance=Geth/v1.10.13-stable-7a0c19f8/windows-amd64/go1.17.2
INFO [12-06|13:08:19.540] New local node record                    seq=1,638,782,055,852 id=3a3308672527a57a ip=127.0.0.1 udp=30303 tcp=30303
INFO [12-06|13:08:19.541] Started P2P networking                   self=enode://c07f9bc1be708bf71bb8e50a979edbdf1d5a46b9fb08de368af48c7c038ad296fe10cd43837805952987c9f68ee8b2263cdc7ee44cf242a80d58395d689e1fa8@127.0.0.1:30303
INFO [12-06|13:08:19.546] IPC endpoint opened                      url=\\.\pipe\geth.ipc
INFO [12-06|13:08:19.547] HTTP server started                      endpoint=127.0.0.1:8545 prefix= cors= vhosts=localhost
INFO [12-06|13:08:19.556] Mapped network port                      proto=tcp extport=30303 intport=30303 interface=NAT-PMP(192.168.50.1)
INFO [12-06|13:08:19.558] Mapped network port                      proto=udp extport=30303 intport=30303 interface=NAT-PMP(192.168.50.1)
INFO [12-06|13:08:19.565] New local node record                    seq=1,638,782,055,853 id=3a3308672527a57a ip=185.86.10.29 udp=30303 tcp=30303
INFO [12-06|13:08:29.543] Looking for peers                        peercount=0 tried=35 static=0
INFO [12-06|13:08:39.550] Looking for peers                        peercount=0 tried=30 static=0
INFO [12-06|13:08:50.209] Looking for peers                        peercount=0 tried=42 static=0
INFO [12-06|13:09:00.242] Looking for peers                        peercount=0 tried=41 static=0
INFO [12-06|13:09:10.264] Looking for peers                        peercount=1 tried=40 static=0
INFO [12-06|13:09:11.132] Block synchronisation started
INFO [12-06|13:09:11.746] Downloader queue stats                   receiptTasks=0 blockTasks=0 itemSize=1.65KiB throttle=8192
INFO [12-06|13:09:11.863] Chain reorg detected                     number=9,767,495 hash=1ef8e6..302846 drop=1 dropfrom=46111b..431b53 add=1 addfrom=3e7d82..df4b9a
INFO [12-06|13:09:11.863] Imported new chain segment               blocks=1 txs=40 mgas=7.851 elapsed=113.574ms mgasps=69.123 number=9,767,496 hash=3e7d82..df4b9a age=1m9s dirty=0.00B
INFO [12-06|13:09:12.199] Imported new chain segment               blocks=4 txs=155 mgas=26.130 elapsed=335.159ms mgasps=77.963 number=9,767,500 hash=b93e5e..9d0236 dirty=0.00B
INFO [12-06|13:09:18.497] Deep froze chain segment                 blocks=4 elapsed=13.562ms  number=9,677,500 hash=5bd58a..545d55
INFO [12-06|13:09:19.393] Imported new chain segment               blocks=1 txs=48  mgas=7.376  elapsed=44.035ms  mgasps=167.495 number=9,767,501 hash=c98b6c..d9b1e4 dirty=0.00B
INFO [12-06|13:09:19.479] Chain reorg detected                     number=9,767,500 hash=b93e5e..9d0236 drop=1 dropfrom=c98b6c..d9b1e4 add=1 addfrom=c9e18b..edbf01
INFO [12-06|13:09:19.479] Imported new chain segment               blocks=1 txs=48  mgas=7.376  elapsed=14.414ms  mgasps=511.700 number=9,767,501 hash=c9e18b..edbf01 dirty=0.00B

**Comment by rjl493456442** [comment]
`geth --rinkeby --gcmode=archive --http --http.api=eth,net,web3,debug` I think you are using the **snap sync** to do the initial sync and after the syncing, node starts to do sync block in archive node. But unfortunately the state before the pivot point are non-existent.

Please also add the `--syncmode full` for the initial sync.

Btw, can you please check the database size? It's might much easier to quick verify my guess.

**Comment by playmint-jbr** [comment]
Yes I would've been using snap sync, I the database was about 60GB I think, I've restarted it with a full sync now

**Comment by playmint-jbr** [comment]
Should I turn snapshot database mode off by the way? I heard you don't need it on if you're running an archive node

**Comment by rjl493456442** [comment]
> Should I turn snapshot database mode off by the way? I heard you don't need it on if you're running an archive node

Snapshot is recommended, even for archive node.

**Comment by rjl493456442** [comment]
Close it right now. Feel free to reopen if you still meet problems.
