### ISSUE TITLE
eth_getLogs allows to query events from unmined block

### ISSUE THREAD

**Issue by bogdan** [ethereum/go-ethereum#24078]
#### System information

Geth version: v1.10.13
OS & Version: OSX

#### Steps to reproduce the behaviour

Given there are multiple geth nodes behind an HTTP load balancer and suppose that one of them gets behind other by 20 blocks for whatever reason - network connection issue, human error, slow hardware etc.

1. Client calls `eth_blockNumber`. 
2. The request is routed an up to date ethereum node 
3. Node returns XX2100 block number
4. Client calls `eth_getLogs` with  block range XX2050-XX2090 (assuming 10 confirmation blocks),
5. The request gets routed to a node that is 20 blocks behind up to date one
 
#### Expected behaviour

`eth_getLogs` return an error that head block is behind a specified block range.

#### Actual behaviour

The outdated node doesn't return event from blocks XX2080-XX2090. Client has no way to know about the issue as such a block range can really have no events.

**Comment by s1na** [comment]
Something you could try (at cost of performance) is to query the logs block by block, i.e. `getLogs({"blockHash": "0xabab..."})` which returns an error if it encounters a block it doesn't recognize.

Because the head might be somewhere between the queried block range it feels weird either to return an error for the whole range or an error and only the logs up till the head block.

**Comment by bogdan** [comment]
> Something you could try (at cost of performance) is to query the logs block by block, i.e. getLogs({"blockHash": "0xabab..."}) which returns an error if it encounters a block it doesn't recognize.

The cost is quite significant here when you work with fast PoS block generating network.

> Because the head might be somewhere between the queried block range it feels weird either to return an error for the whole range or an error and only the logs up till the head block.

The alternative may be is to return a head block number as part of the response. That might be also more backward compatible.

**Comment by ligi** [comment]
What kind of balancer are you using? Would a web3-aware balancer like [dshackle](https://github.com/emeraldpay/dshackle) also solve your problem?

**Comment by bogdan** [comment]
I am using Infura at the moment and I am not sure what kind of load balancer do they use.
I'd better want to eliminate such problems as a class because if I am writing an open source library I am not sure which service provider will be used by a client.

**Comment by MariusVanDerWijden** [comment]
This should be fixed by multicall, you can do a `eth_blockNumber` and `eth_getLogs` in the same call and be sure that they originated from the same node. There is not really anything we could do without changing the rpc spec. I am going to close this issue for now. If you feel really strongly that `eth_getLogs` should return an error/the head block number, please open an issue here: https://github.com/ethereum/execution-apis

**Comment by bogdan** [comment]
> This should be fixed by multicall

Unforturnatelly, multicall can not work here because the result of the first call should used in a second one.

> If you feel really strongly that eth_getLogs should return an error/the head block number, please open an issue here: https://github.com/ethereum/execution-apis

I think it is a good idea. We can introduce an option for this to be backward compatible: `returnErrorIfBlockrangeIncludesUnminedBlock: true`.

Thanks for suggestion!
