### ISSUE TITLE
A crazy idea about MPT storage

### ISSUE THREAD

**Issue by qianbin** [ethereum/go-ethereum#24097]
If globally maintain a sequence number for each MPT commit, and assign the SN to each newly produced nodes, then a node can be uniquely identified by its path with SN.

That's to say, the hash pointer which causes state explosion can be dropped. Instead, using a 64-bit SN is enough. A scratch (branch)node storage scheme is like:

```
path || SN => Self-Hash || Child-SNs || Leaf-Value
```

For a full branch node without leaf-value, the RLP encoded length is about 1/5 of current scheme. It will bring great benefits to disk IO/usage, and cache efficiency.

Disadvantage: it's required to read all child-nodes to get their hashes, before recompute the parent node hash.

**Comment by holiman** [comment]
I don't fully understand how your scheme would work. 
However, @rjl493456442 has been working on a path-based schema, in https://github.com/ethereum/go-ethereum/pull/24087 . With that schema, we would only ever have one single trie on disk. And in order to support reorgs, we would have a memory-backed difflayer structure to represent the latest N blocks. 

Any change in this areas is a _huge_ amount of work. I'm going to close this ticket, since it's not really an actionable item from our perspective. 
If you want to flesh out your proposal a bit more, we'd be happy to take a look at it. You can also study the PR linked above, and give comments/feedback on that one.
