### ISSUE TITLE
light node: Transaction returning null until second try.

### ISSUE THREAD

**Issue by JoeGruffins** [ethereum/go-ethereum#24101]
We are testing with a private network. Two snap sync nodes and two light nodes using the proof of authority "clique" to mine blocks. Light nodes sometimes do not find transactions until the second time you ask for them.

```
[harness-ctl]$ ./gamma attach --exec 'eth.getTransaction("0xb2846bb0c1b97c22ff2f886ed0e5ca383e054b5830abdacb7066c1daa14ec7a9")'
null
[harness-ctl]$ ./gamma attach --exec 'eth.getTransaction("0xb2846bb0c1b97c22ff2f886ed0e5ca383e054b5830abdacb7066c1daa14ec7a9")'
{
  accessList: [],
  blockHash: "0x045666f2a4c7c5e077065b182f97538c93ba935c95ab13476b25c87fbaf3238b",
  blockNumber: 221,
  chainId: "0x2a",
  from: "0xdd93b447f7ebca361805ebe056259853f3912e04",
  gas: 21000,
  gasPrice: 2000000000,
  hash: "0xb2846bb0c1b97c22ff2f886ed0e5ca383e054b5830abdacb7066c1daa14ec7a9",
  input: "0x",
  maxFeePerGas: 2000000000,
  maxPriorityFeePerGas: 2000000000,
  nonce: 45,
  r: "0x640cc950e3a71cc1cb5a487a62edd9b778d178ea24da2fb22de4f6dad23076ea",
  s: "0x4507a46a4f4a1f2d40d2de89039f81fd09ac254b313d67b50c927995614c6ac5",
  to: "0x8d83b207674bfd53b418a6e47da148f5bfecc652",
  transactionIndex: 0,
  type: "0x2",
  v: "0x0",
  value: 1000000000
}
```
This only seems to happen very rarely. I do not know how to reproduce. We're using "clique" with a one second period if that would matter.

edit: Originally it seemed to be connected to fetching the block separately but that does not seem so. Title also edited to reflect the revelation that asking for it twice finds it.

**Comment by holiman** [comment]
With a light node, you won't always get up-to-date results. It needs to have a server to query about things, and that can't always be guaranteed. Since you're also running with very fast blocks, 1 second between them, the chance that a les client is cannot obtain the requested information in time increases. 
I don't think this is an issue in geth, rather "the way things are" due to the nature of light clients.

**Comment by chappjc** [comment]
> them, the chance that a les client is cannot obtain the requested information in time increases

Thanks for responding.  Could you clarify what is meant here by "in time" w.r.t a `getTransaction` request?  Assuming the light client does have a connection to a full node, what circumstances and timing issues might cause it to fail to retrieve the transaction if the server it is connected to has it?  Lagging block processing on said server?

My understanding from the original ORD getTransaction PR (https://github.com/ethereum/go-ethereum/pull/19069#issuecomment-489608576), and the code, which follows through light/odr_util.go like `GetTransaction` > ... > `rawdb.ReadBodyRLP` otherwise `odr.Retrieve`, is that if the upstream full node has the data, it will be retrieved.

Thanks for helping us understand and set our expectations for these requests.
