### ISSUE TITLE
More efficient storage of headers/blocks

### ISSUE THREAD

**Issue by zsfelfoldi** [ethereum/go-ethereum#2413]
Currently, headers are stored in chainDb with the key formatted as "block-HASH-header". This way they are scattered randomly within the "block-" key prefix range, which slows down database access of continous block number ranges significantly, which is a major limiting factor for the speed of header downloads, both on the request serving and the downloading side.
Instead, we should use something like "block-NUMBER-HASH-header" where number is encoded as a big endian uint64. Canonical hashes could be stored on "block-NUMBER-hash" (so that they are interleaved with the actual data). Although we usually know the number of the block/header we're accessing, there are some exceptions when we only know the hash so the canonical assignments should be stored in both directions, block numbers being stored at "blocknum-HASH".
The same approach can be used for TDs, bodies and receipts too, although storing the bodies/receipts on separate key ranges (like "body-NUMBER-HASH" and "receipt-NUMBER-HASH") might be a good idea because we're downloading headers and bodies/receipts separately.

**Comment by karalabe** [comment]
We can most definitely consider this, but I'm not sure it's that simple as you think it is.

Internally our code mostly uses hashes for almost everything. Adding the block number into the keys would mean that we either have to resolve the numbers all the time, or pass the block number along with the hash when we do a lookup. The latter is imho the only workable solution but does increase code complexity a bit.

As you already mentioned, sometimes we do need hash->number lookups if we only have the hash, so storing individual mappings is also a must. Storing another set of keys at a completely different location may have a bigger impact than the gain.

However, our current database bottleneck is compaction: when lower levels of the database gets filled p with semi random data and they need to be merged into higher levels. From this perspective, your suggestion is actually very good one: since our chain data is mostly ordered by block number, storing thme like that on disk would limit the scope of compaction in the database. We do need to update a different location (that is random still because of the hashes), but since the bulk of the data is in the sorted part and the random hash part are tiny (only a number mapping), perhaps the negative effects of the extra data/compaction is less than the positive effects on the content compaction.

Regarding splitting the individual components to header- body- receipt-, I'm not sure about that since during normal operation we need the header, body and receipts at the same time for a block, it it might be worth to keep them close (in the same database block, so when one is retrieved all others are).

All in all I think we need a ton of benchmarks and whatnot to figure this one out, but it's an idea definitely worth investigating.

**Comment by zsfelfoldi** [comment]
@karalabe I didn't think that this is trivial either :) But I also don't think it's extremely hard since everything would remain accessible by hash. We could even keep the access functions with old semantics and add new ones which are more efficient for accessing a large number of consecutive block data. Those will mainly be used by the protocol handler serving download messages.
The only problem I see is the format of GetBlockBodies and GetReceipts messages because they only contain hashes. Maybe we could solve this without changing the message formats by caching hash->number associations because downloaders usually get bodies and receipts not long after headers. Maybe we don't even need new semantics for the db access, we could just automatically cache hash->number associations in GetHeaderByNumber.

**Comment by fjl** [comment]
Fix released in 1.5.0.
