### ISSUE TITLE
[Suggestion] Adding API fetching Gas Ceiling of configured in node.

### ISSUE THREAD

**Issue by aeharvlee** [ethereum/go-ethereum#24138]
# Rationale

Why should this feature 
* If this feature exists, we can fetch the current actual `Gas Ceiling` of a block.
* If this feature dose not exists, we never know what `Gas Ceiling` value exactly.

What are the use-cases?
* There is an official documentation about [gas limit of block](https://ethereum.org/en/developers/docs/blocks/#block-size), but user or devs cannot knows what value exactly is set up in nodes. 
* I also saw [this tweet](https://twitter.com/etherchain_org/status/1273912037274537984?s=20), but cannot find the actual "Gas Limit of block" value in source codes or any place. And found that `GasCeiling` field. It is the actual `gas limit of block` value set on node. Please let me know if I'm missing something.
* So if this API exists, user or devs can knows the actual `Gas Limit` of a Block by using API. 

# Implementation

Do you have ideas regarding the implementation of this feature?
* Returning `worker.config.GasCeil` (in `miner/miner.go`) would be ok just now. 

Are you willing to implement this feature?
* Of course.

**Comment by holiman** [comment]
I don't really get it. 

> worker.config.GasCeil 

If you're a node operator, then it's fairly trivial to figure out what CLI params/toml config you used to configure the node. If you're not a node operator -- how is this information useful at all?

**Comment by aeharvlee** [comment]
@holiman 
Hi. 
I'm not a node operator but, want to figure out the real [block gas limit](https://ethereum.org/en/developers/docs/blocks/#block-size) of Ethereum.

I believe block gas limit matter because this is the indicator related with performance(or limitation?) of Ethereum.

High block gas limit means it can include more txs than low block gas limit.

IMHO, Researchers or developers who want to know the actual specifications of Ethereum are likely to be able to use this indicator.

**Comment by MariusVanDerWijden** [comment]
In order to determine the gas limit a block producer used, you would need to access their node. Block producers are not exposing any rpc though since that can be an attack vector. The gas ceiling of non block producing nodes does not matter. You can reasonably infer the set block gas limit from observing the gas used in a block. There is no need for this API endpoint in my opinion. I am going to close this issue for now. If you disagree and would like to have this endpoint, please open an issue with the execution apis here: https://github.com/ethereum/execution-apis
