### ISSUE TITLE
Add method to the client to send TX using `eth_sendTransaction`

### ISSUE THREAD

**Issue by krasi-georgiev** [ethereum/go-ethereum#24218]
# Rationale

Why should this feature exist?
when using hardhat to impersonate an account TX are send using `eth_sendTransaction`
What are the use-cases?
running tests against a mainnet  fork
# Implementation

Do you have ideas regarding the implementation of this feature?
yes with some guidance
Are you willing to implement this feature?
yes

**Comment by ligi** [comment]
Please elaborate a bit more what exactly the problem is and what you are trying to do

**Comment by krasi-georgiev** [comment]
the issue is that the eth client doesn't have a method for `eth_sendTransaction`

it has for `eth_sendRawTransaction` but not for `eth_sendTransaction`

https://github.com/ethereum/go-ethereum/blob/0169d579d0eed4f6366697985a7b0f0b99402783/ethclient/ethclient.go#L507

**Comment by MariusVanDerWijden** [comment]
We don't really like `eth_sendTransaction` since it requires the node to have key management. Some other node implementations don't even implement it. We would like to get rid of it in the future, so it wouldn't be the right step to add this to the ethclient. You can use the rpc client directly to access this method directly if you really need this method

**Comment by krasi-georgiev** [comment]
Who are "we"? Is this your personal opinion or all maintainers think the same way?

**Comment by karalabe** [comment]
The long term direction is to remove account management from Geth, simply because it's not appropriate. We haven't yet done so because it helps debugging issues for us, but we most definitely don't want people to use Geth as the account manager. Keeping the keys in your own process is both safer as well as allows you to switch different providers.

**Comment by holiman** [comment]
If one of the maintainers uses the term "we", it's most likely something that has been discussed internally. Although we may  appear high and mighty, we usually avoid the use royal personal pronouns :)

**Comment by krasi-georgiev** [comment]
> If one of the maintainers uses the term "we", it's most likely something that has been discussed internally. Although we may appear high and mighty, we usually avoid the use royal personal pronouns :)
got it thanks, 

> The long term direction is to remove account management from Geth, simply because it's not appropriate.

why is "eth_sendTransaction" considered for account management?
Isn't this just one of the official JSON Rpc API endpoints and as such shouldn't the client allow calling it?

**Comment by samlaf** [comment]
Hey guys, late to the party here. I'm also a bit confused after reading this doc: https://geth.ethereum.org/docs/tools/clef/introduction

This picture seems to indicate that even with wallet not managed by the node, eth_sendTransaction is needed, and the geth node will simply proxy the request to the connected wallet.
![image](https://github.com/user-attachments/assets/f68d4d4e-727a-4e2a-b5e7-e5b8472ebbcc)

Is this picture no longer relevant? Is the recommended way now to get the signature directly from clef instead and then broadcast the tx myself?
