### ISSUE TITLE
Any way to repair state data when `missing trie node` happend

### ISSUE THREAD

**Issue by louisliu2048** [ethereum/go-ethereum#24215]
Our team uses a modified go-ethereum to build a private chain, run our own application. Everything was ok until last week, one node's disk(archive node) was full and that node crashed. When we clean up the data of other applications and restart the node again, we occurs a `missing trie node` error . After querying on the Internet, we know that the database of trie may be broken. Therefore, we intend to re-execute some blocks to repair the trie database.
We select a state that is more than 10,000 blocks earlier than the node collapse (we modified the code of go-ethereum, and think that the data at that height is no problem) as the starting state, and re-execute the subsequent blocks from that point. 
However, we found a problem. When we finished executing the height N, we were able to obtain the damaged trie node data through the function `db.OpenStorageTrie`, and successfully completed the `so.trie.Commit` commit operation in the Commit stage, also updated the relevant root hash. However, when the height is N+1, when we try to get tire node data through `db.OpenStorageTrie` with the latest updated root hash, there is still a `missing trie node` error, which confuses us.
We would like to know if there is an official way to fix the state data by re-executing the block. Is our repair method correct and what needs to be improved.

**Comment by karalabe** [comment]
It's a bit hard to see what you're doing or how correct it is. Geth by default has a memory caching/pruning layer above the disk database. (trie.Database). During block processing, the references are added and removed to the roots explicitly that trigger various GC operations. Archive nodes are special cased to do flushes intertwined with these operations. (core/blockchain.go).

You'll need to make sure that your recovery mechanism also takes the trie GC into account. Comitting the trie will only have it end up in this memory layer, you'll need to flush this to disk (in case of an archive node) to persist it across blocks. Also make sure you respect the referencing/dereferencing of the roots to avoid a mismatch and a later failure due to that.

**Comment by louisliu2048** [comment]
> It's a bit hard to see what you're doing or how correct it is. Geth by default has a memory caching/pruning layer above the disk database. (trie.Database). During block processing, the references are added and removed to the roots explicitly that trigger various GC operations. Archive nodes are special cased to do flushes intertwined with these operations. (core/blockchain.go).
> 
> You'll need to make sure that your recovery mechanism also takes the trie GC into account. Comitting the trie will only have it end up in this memory layer, you'll need to flush this to disk (in case of an archive node) to persist it across blocks. Also make sure you respect the referencing/dereferencing of the roots to avoid a mismatch and a later failure due to that.

Thx, we have found the root cause: miss use of `ethcmn.TrimLeftZeroes` function at `trie.TryUpdate`, which will lead to probabilistic data inconsistency
