### ISSUE TITLE
SimulatedBackend?

### ISSUE THREAD

**Issue by kawahwookiee** [ethereum/go-ethereum#24226]
I recently stumbled upon `SimulatedBackend` struct while browsing the code. I noticed that it has a constructor (i.e. `NewSimulatedBackendWithDatabase`) which apparently accepts the path to the node's LevelDB, which is `geth/chaindata` (right?).

Now, since `SimulatedBackend` provides several functions like `CallContract`, `SendTransaction` etc., my guess is that its purpose is to simulate the outcomes of mock transactions, or even contract calls. However, when specifying the path to a runnning node's chaindata, the client failed to start with `resource temporarily unavailable` error. Stopping the node just for this purpose doesn't seem to be a grand idea.

Does anyone have experience with this `SimulatedBackend`? If so, what's the best approach to get it up and running?

Thanks

**Comment by s1na** [comment]
You can check this article for some walkthrough: https://medium.com/@m.vanderwijden1/intro-to-web3-go-part-4-5a21bc71fddc. The error `resource temporarily unavailable` is because you have a node running which uses the same datadir. But you don't have to stop the node. You can just use `NewSimulatedBackend` which creates an in-memory database.

**Comment by kawahwookiee** [comment]
> You can check this article for some walkthrough: https://medium.com/@m.vanderwijden1/intro-to-web3-go-part-4-5a21bc71fddc. The error `resource temporarily unavailable` is because you have a node running which uses the same datadir. But you don't have to stop the node. You can just use `NewSimulatedBackend` which creates an in-memory database.

Thanks, I've read that one.
`NewSimulatedBackend` does create an in-memory database, but where would it get info about a contract I use with `client.CallContract(..)`? Doesn't it require actual chanidata?

**Comment by fjl** [comment]
The simulated backed provides functionality similar to 'ganache'. It creates a separate blockchain where you can deploy your own contracts and interact with them, all from within Go code and without having to install/launch additional software.

You don't need to use it with your mainnet node's chaindata (and in fact I would not recommend it because it may alter the database).

**Comment by kawahwookiee** [comment]
Very useful, thanks
