### ISSUE TITLE
Enforce a unit gas price

### ISSUE THREAD

**Issue by kamikazechaser** [ethereum/go-ethereum#24248]
I would like to run a network where the gas price is always 1. The validating node should accept a transaction with _any_ gas price into the mempool, but use an effective price of 1 when rewarding the validator.

Is it currently possible to set an _upper bound_ for the gas price?

If not, how much of a change would be involved?

cc/ @nolash

**Comment by karalabe** [comment]
There's no such functionality in the Ethereum protocol to allow rewarding less than the fees specified by the user. Making that change would seem a non-trivial work since you'd need to handle that at various locations (tx execution, mempool, etc). Maybe you could hack it in by modifying the EVM setup when starting to execute a transaction + the end when the rewards are allocated to the miner, but it's gonna get messy. It's not something we would add to the protocol or go-ethereum implementation.
