### ISSUE TITLE
How is contract data persisted to levelDB

### ISSUE THREAD

**Issue by hsyodyssey** [ethereum/go-ethereum#24243]
Hi Guys, I now have a question about how contract data is persisted to levelDB.

I now know that in EVM, Contract data is managed in terms of Slots. Usually, the key of a Slot is calculated based on the location of the Slot. 

My questions are as follows:

1. When persisting contract data, what is the key of each k-v pair in leveldb?

2. If the key is a hash based on the location of the Slot, won't their data collide for different contracts that use the same slot location?

3. For the data of contracts of different contracts, will they be stored in the same levelDB instance. In other words, is it possible for the data of different contracts to be stored in the same levelDB sstable?

Thanks so much！

**Comment by rjl493456442** [comment]
1. All the ethereum state(accounts, storage slots) are managed by a 2-layers Merkle-Patricia-Tree. For example, all the accounts are inserted into a MPT as "leaves" and a batch of internal nodes will be generated according to the rules of MPT.
So from the perspective of database, it only sees a batch of trie nodes(leaves, internal nodes).

And currently these MPT nodes are stored by hash. Specifically, it uses the node hash as the database key.

2. Yes, it will. Different contracts can refer to a same storage slot. Currently there is no disk pruning in Geth, so the shared storage slot won't be deleted. 

But what if a contract modify this slot? Then a new storage slot will be created in the database since the content is changed, new hash will be derived.

3. It's impossible for ethereum state be persisted in a single leveldb sstable. Ethereum state is quite large(let's say 100GB) so it's impossible to store all of them in a single sstable. 

And unfortunately, currently the state is stored by hash, it means the state data will cross the entire key space and be stored everywhere.

**Comment by hsyodyssey** [comment]
> 1. All the ethereum state(accounts, storage slots) are managed by a 2-layers Merkle-Patricia-Tree. For example, all the accounts are inserted into a MPT as "leaves" and a batch of internal nodes will be generated according to the rules of MPT. So from the perspective of database, it only sees a batch of trie nodes(leaves, internal nodes). And currently these MPT nodes are stored by hash. Specifically, it uses the node hash as the database key.
> 2. Yes, it will. Different contracts can refer to a same storage slot. Currently there is no disk pruning in Geth, so the shared storage slot won't be deleted.  But what if a contract modify this slot? Then a new storage slot will be created in the database since the content is changed, new hash will be derived.
> 3. It's impossible for ethereum state be persisted in a single leveldb sstable. Ethereum state is quite large(let's say 100GB) so it's impossible to store all of them in a single sstable.  And unfortunately, currently the state is stored by hash, it means the state data will cross the entire key space and be stored everywhere.

Thank you for your reply. My third question may not have been very clear in its description. According to your reply, can I understand that a part of the data from different contracts may be mixed in a certain sstable? For example, some [address/balance] pair data from two different ERC-20 contracts may be stored in the same sstable at a certain level in the same leveldb instance?

**Comment by rjl493456442** [comment]
Yes, it's totally possible.

**Comment by hsyodyssey** [comment]
> Yes, it's totally possible.

I understand now. Thank you very much for your answer！
