### ISSUE TITLE
turn MPT tree into a sharding model

### ISSUE THREAD

**Issue by QianSun-github** [ethereum/go-ethereum#24295]
In MPT, there are 3 kinds of nodes, Leaf Node, Branch Node and Extension Node and the branch node has 16 children

With massive amounts of data being stored and keys being hashed, the root layer should be the branch node

so can we make The MPT tree  splited into 16 sub MPT  shards  and each shard in parallel?  

The advantage of doing this is that  we can parallelize the related operations of mpt include insert/delete/hash calculation . In this way, we can greatly improve the performance of commit and hash calculations

**Comment by fjl** [comment]
Hi,

thanks for your improvement suggestion. I'm unsure about the exact meaning of your comment.

I think you mean that the Ethereum protocol should be changed to compute changes in parallel. Unfortunately, it is not possible to do this because contracts in different parts of the trie can interact with each other during a single transaction.

If you mean that go-ethereum could compute the trie root hash in parallel, then the answer is: yes, it's possible. But we have tried it before and it did not provide a big performance improvement. The overhead of communicating between different hashing threads was larger than the benefit provided by parallel computation.
