### ISSUE TITLE
Replace EVM with eWASM virtual machine.

### ISSUE THREAD

**Issue by Kenun99** [ethereum/go-ethereum#24350]
# Rationale

**Q: Why should this feature exist?**
A: In the next step of [Ethereum](etherscan.io/address/0x46403e94529fc04d04c9c393beab1d050ef06409#code), smart contracts should run in eWASM bytecode rather than EVM bytecode, for scalability and security.  I have implemented an EVM-to-eWASM bytecode translator that can generate eWASM smart contracts from EVM bytecode directly with correctness. Developers can use the most of EVM infrastructures to develop and interact the eWASM contracts, e.g., Web3. 
Check [https://github.com/Kenun99/ethsema](https://github.com/Kenun99/ethsema) for more details. 
Currently, the eWASM fork of go-ethereum is out-of-date. It is important for Ethereum2.0 to develop a new eWASM client.  

**Q: What are the use-cases?**
Run eWASM smart contracts.
We can integrate EthSema (https://github.com/Kenun99/ethsema) to convert EVM smart contract to eWASM just-in-time and execute eWASM bytecode.

# Implementation

**Q:Do you have ideas regarding the implementation of this feature?**
A:We need to make go-ethereum to provide a new virtual machine to execute smart contracts. 

**Q:Are you willing to implement this feature?**
A:Probably.

**Comment by s1na** [comment]
> It is important for Ethereum2.0 to develop a new eWASM client.

Ewasm is not part of the official roadmap for Eth2. The last discussions on that topic revolved around the idea of using ewasm for the other shards. But since then the roadmap has changed and those other shards which are going to be introduced in phase1 are kept data-only, no execution. Closing the issue for now. It can be re-opened if at some point execution shards were back on the table for eth2.
