### ISSUE TITLE
What did the chain data size drop drastically on January 26, 2022?

### ISSUE THREAD

**Issue by MoGuGuai-hzr** [ethereum/go-ethereum#24388]
Today, I was surprised to find that the chain data scale of Geth(Full Node) has dropped on a large scale. That is
> January 26, 2022 524.50  Gb
> January 25, 2022 1185.93  Gb

This is a delightful good news, but can anyone tell me what's going on?

**Comment by a2468834** [comment]
Did you see this information at [Etherscan,.io](https://etherscan.io/chartsync/chaindefault)?
 I have also been wondering the same question since last week.
But I still cannot figure out what happened.

According to the discussion with my friends, we guessed it might be caused by a new feature [node pruning](https://gist.github.com/yorickdowne/3323759b4cbf2022e191ab058a4276b2).

On 1/25, the client version is 1.10.12, and then on 1/26, it changes to 1.10.15.
So we estimate that maintenance operators might upgrade the client version and do offline pruning at the same time.

Because I have not used pruning before, I do not know the root cause of dropping is (or might be) related to this new feature.

Maybe you could follow the article above to test how big would disk usage be cut off.
Many thanks.

**Comment by MoGuGuai-hzr** [comment]
@a2468834 
Thanks for your reply, I'm going to read this article.

I'm investigating Ethereum's usage of disk, and got this information from [ycharts](https://ycharts.com/indicators/ethereum_chain_full_sync_data_size).

**Comment by holiman** [comment]
They must have done a pruning operation. It's not caused by something we've done in geth

**Comment by a2468834** [comment]
Thanks for your reply, holiman 🙏😭
This really helps me to figure out what happened to the disk usage.

**Comment by a2468834** [comment]
@MoGuGuai-hzr
Recommend you for using Etherscan.io.
It seems like that ycharts also uses Etherscan as the data source.

BTW, I'm recently researching on hosting Ethereum node by OpenEthereum which has smoother growth curve of disk usage (at full node). Maybe you could also try this.
