### ISSUE TITLE
Why EIP-2930 access list tx use unprotected Homestead signature scheme

### ISSUE THREAD

**Issue by dustinxie** [ethereum/go-ethereum#24421]
sorry to post a question here, but I've looked on Ethereum stackexchange to no avail, here's my question: https://ethereum.stackexchange.com/questions/121813/why-eip-2930-access-list-tx-use-unprotected-homestead-signature-scheme
thanks for answer or any pointer

**Comment by dustinxie** [comment]
in one sentence, the question is why EIP-2930 access list tx does NOT use the EIP-155 way of signature (for replay-attack mitigation) just as legacy tx does, the comment in the code https://github.com/ethereum/go-ethereum/commit/bbfb1e4008a359a8b57ec654330c0e674623e52f#diff-58204a02692cd9ef1cf0767b18dbc4df99eb678126c8982350e5b727af075b5eR194-R197 only states the fact but gives no reasoning/explanation

**Comment by fjl** [comment]
Hi,

legacy and non-legacy transactions store the chain ID for replay protection in a different way.

For legacy transactions, the chain ID is encoded into the tx V value. This scheme, which is defined by EIP-155, was implemented because the protocol authors did not want to change the structure of transactions at the time. It is possible to derive the chain ID from any transaction from V.

For non-legacy transactions, [the chain ID is simply part of the transaction data](https://github.com/ethereum/go-ethereum/blob/d6f49bf764c48e9415b168e701b6dc26566a675c/core/types/access_list_tx.go#L47). This makes it unnecessary to add it into V.

I hope it answers your question.
