### ISSUE TITLE
[Question] Why does snap sync sometimes switch to full sync?

### ISSUE THREAD

**Issue by dzou** [ethereum/go-ethereum#24457]
Hey, I have a question about what happens if a fully synced up node is shutdown for some time, and then wants to be synced up again? Is it possible to "catch up" the node using snap sync?

I see in my case, I see that [snap sync switches back to full sync from this line](https://github.com/ethereum/go-ethereum/blob/adc0a6adca90c4a784b7eb9ba88c1af15fd2b681/eth/handler.go#L163).

```
INFO [02-09|20:42:17.378] Initialising Ethereum protocol           network=1 dbversion=8
INFO [02-09|20:42:18.604] Loaded most recent local header          number=786,629 hash=54da69..b98d10 td=5,014,519,227,691,977,823 age=6y2mo1w
INFO [02-09|20:42:18.604] Loaded most recent local full block      number=786,629 hash=54da69..b98d10 td=5,014,519,227,691,977,823 age=6y2mo1w
INFO [02-09|20:42:18.604] Loaded most recent local fast block      number=786,629 hash=54da69..b98d10 td=5,014,519,227,691,977,823 age=6y2mo1w
INFO [02-09|20:42:18.614] Loaded local transaction journal         transactions=0 dropped=0
INFO [02-09|20:42:18.614] Regenerated local transaction journal    transactions=0 accounts=0
WARN [02-09|20:42:18.614] Switch sync mode from snap sync to full sync
```

Could someone explain why the sync-mode gets switched?

Also, I see in my logs that I already have some blocks. I'm working with a base image that already has some blocks downloaded; we thought that this would help speed things up. But now I think this may not be the case if we have understood `snap` sync incorrectly.

**Comment by holiman** [comment]
There are two types of sync, which both leads to a "full node". 
- statesync: `syncmode=snap` (or the old `syncmode=fast`)
  - In this mode, the "current" state is downloaded from peers. With "current", I mean that it aims for the state at block `N`, where `N` is close to head when the sync starts, also called the pivot point. Since we cannot sync up quickly enough, we move the pivot point forward from time to time. Eventually, geth has the complete state for a certain block, but has still maybe ~100 blocks remaining to be fully in sync with head.  
  - Once this mode reaches the point where it has the full state for a certain block, it switches over to "block-by-block" sync.
- block-by-block-sync: `syncmode=full`. 
  - In this mode, geth imports and executes the contents of each block, from genesis to head. 

If geth has performed a state-sync at any point, it will never redo that, but always progress block by block. It _is_ possible to bypass this, by deleting a certain metadata field (which one I don't recall right now), and do a new statesync, but it's not something we have implemented as part of the "normal ux". 

In your logs, you seem ot have started a full-sync and gone up to block 786K. After a block-by-block sync is started, regardless of what you tell it to do, it will continue with the block-by-block sync.

**Comment by 2thecoin** [comment]
Your post helped me too, thanks.

**Comment by shiziwen** [comment]
@holiman Hi, if I run geth with snap sync and it has synced to the latest block. Then, I stopped the node and make the node as image which I can load to other machines to accelerate the sync speed. I may cost almost one day.

When I restart the node, can it still use snap sync mode?

**Comment by shiziwen** [comment]
@holiman I have met an issue.
I run geth node as full syncmode, and stopped the node, make it as image and load to other machine, start it.
The geth node sync very very slow. It differs from the latest block by 10,000. I'm afraid it can't sync to the latest block.
