### ISSUE TITLE
Abigen fails with complex type as argument

### ISSUE THREAD

**Issue by infiloop2** [ethereum/go-ethereum#24572]
#### System information

Geth version: `v1.10.16`
OS & Version: OSX
Commit hash: -

#### Expected behaviour

abigen produces a go wrapper

#### Actual behaviour

abigen errors out

#### Steps to reproduce the behaviour

Save this as Example.sol

```
// SPDX-License-Identifier: MIT

pragma solidity 0.8.6;

library Example {
  enum Field {
    F1
  }

  function example(Field x) public view {}
}
```

Run:
```
solc-select use 0.8.6
./abigen --pkg example --sol Example.sol
```

#### Backtrace

````
Fatal: Failed to generate ABI binding: unsupported arg type: Example.Field
````

**Comment by infiloop2** [comment]
Interestingly this works if I change 'library' to 'contract'

**Comment by rjl493456442** [comment]
I have opened an issue in solidity repo. Looks like Solidity compiler doesn't generate the expected abi for library. Let's see how it's responded there. https://github.com/ethereum/solidity/issues/12867

**Comment by Haleymiranda79** [comment]
> Interestingly this works if I change 'library' to 'contract'

Why must we substitute words? I have to carry a thesaurus 24/7 because everyone talks in riddles, double-speak and metaphor just to name a few "devices". I'm going to play in traffic. We're too old for this. Let's say what we mean. On the bright side, my vocabulary has tripled during covid. I have to know synonyms these days. The word "bike" is a synonym for a flock of some type of bird if I remember correctly.

**Comment by h5law** [comment]
I am receiving the following error from abigen:

```console
$ abigen --abi abi.json --pkg versioning --type Versioning --out versioning.go
Fatal: Failed to generate ABI binding: unsupported arg type: State
```

For simplicity I have produced a minimal reproducible copy of what is causing the error, from my actual code, with an example code shown below.

```solidity
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.5;

enum State {
    UNINITIALISED,
    INIT,
    OPEN
}

library Versioning {
    function versionState(
        State state,
        string calldata version
    ) external pure returns (string memory versionedState) {
        if (state == State.OPEN) {
            return string(abi.encodePacked(version, "OPEN"));
        }
        if (state == State.INIT) {
            return string(abi.encodePacked(version, "INIT"));
        }
        if (state == State.UNINITIALISED) {
            return string(abi.encodePacked(version, "UNINITIALISED"));
        }
        return "UNKNOWN STATE";
    }
}
```

I am able to reproduce the code generation error, when running the following set of commands:

```console
$ forge build mrc.sol
$ jq .abi ./out/mrc.sol/Versioning.json > abi.json
$ abigen --abi abi.json --pkg versioning --type Versioning --out versioning.go
Fatal: Failed to generate ABI binding: unsupported arg type: State
```

`typechain` is able to correctly interpret the ABI and create bindings for the interface methods. For this example using `typechain`, from `./out/mrc.sol/Versioning.json` generates a `Versioning.ts` file that correctly identifies this enum and converts it to a `BigNumberish`, using the following command:

```console
$ typechain --target ethers-v6 --out-dir . ./out/mrc.sol/Versioning.json
```

```typescript
...
  versionState: TypedContractMethod<
    [state: BigNumberish, version: string],
    [string],
    "view"
  >;
...
```

I would expect the enum in question to be converted to some integer type in Go, `math/big`'s `big.Int` or an `int{,8,32,64}/uint{,8,32,64}` but due to the `abigen` failure not a single piece of Go code is generated for this one file. I have another enum, defined outside of the library right next to the one called `State` here that is converted to `uint8` in the Go code generated by a separate contract that imports the type from the library as defined above. For example:

```solidity
// mrc.sol

// SPDX-License-Identifier: MIT

pragma solidity ^0.8.5;

enum Example {
    THIS,
    IS,
    AN,
    EXAMPLE,
    ENUM
}

enum State {
    UNINITIALISED,
    INIT,
    OPEN
}

library Versioning {
    function versionState(
        State state,
        string calldata version
    ) external pure returns (string memory versionedState) {
        if (state == State.OPEN) {
            return string(abi.encodePacked(version, "OPEN"));
        }
        if (state == State.INIT) {
            return string(abi.encodePacked(version, "INIT"));
        }
        if (state == State.UNINITIALISED) {
            return string(abi.encodePacked(version, "UNINITIALISED"));
        }
        return "UNKNOWN STATE";
    }
}

// import.sol

// SPDX-License-Identifier: MIT

pragma solidity ^0.8.5;

import { Example } from "./mrc.sol";

contract ExampleContract {
    constructor() {}

    function exampleType(
        Example exm
    ) external pure returns (string memory example) {
        return string(abi.encodePacked("example", exm));
    }
}
```

Using the commands below generates the following Go code:

```console
$ forge buid mrc.sol import.sol
$ jq .abi ./out/import.sol/ExampleContract.json > abi.json
$ abigen --abi abi.json --pkg example --type Example --out example.go
# No errors
```

```go
...
// ExampleType is a free data retrieval call binding the contract method 0xd19b25d7.
//
// Solidity: function exampleType(uint8 exm) pure returns(string example)
func (_Example *ExampleCaller) ExampleType(opts *bind.CallOpts, exm uint8) (string, error) {
	var out []interface{}
	err := _Example.contract.Call(opts, &out, "exampleType", exm)

	if err != nil {
		return *new(string), err
	}

	out0 := *abi.ConvertType(out[0], new(string)).(*string)

	return out0, err

}
...
```

**Comment by holiman** [comment]
This is stale, `abigen` no longer supports `sol`, instead it expects the solc-artefacts as input, and leaves it to the user to invoke `solc`.
