### ISSUE TITLE
OpenCL not enabled in Windows builds

### ISSUE THREAD

**Issue by RikuKawai** [ethereum/go-ethereum#2464]
#### System information

Geth version: `1.4.0-unstable`
OS & Version: Windows 10
Commit hash : bf324bd

#### Expected behaviour
OpenCL functions correctly for GPU mining

#### Actual behaviour
Displays 'OpenCL disabled. Set GO_OPENCL and re-build to enable.'

#### Steps to reproduce the behaviour
run 'geth gpuinfo' or 'geth gpubench'

#### Backtrace

````
[backtrace]
````

**Comment by karalabe** [comment]
OpenCL is not enabled in any of the builds by default. Having it enabled would mean that if you don't have/need OpenCL, the binary would fail to run due to missing libraries/dependencies. To play with OpenCL currently the only option is to build Geth yourself with OpenCL enabled:

`GO_OPENCL=1 make geth`
