### ISSUE TITLE
blockchain sync stalls/ extremely slow

### ISSUE THREAD

**Issue by dhruv-9** [ethereum/go-ethereum#2467]
#### System information

Geth version: `1.3.6`
OS & Version: Windows7 64bit
Commit hash : 

#### Expected behaviour

blockchain should download in a few hours.

#### Actual behaviour

Iv been trying to sync blockchain on Geth for the past four days now and have only managed to get to block 900 k. Though initially i enjoyed download speeds of a few second per 256 blocks, speeds have dropped to more than two min per 256 blocks over the last two days. Also download keeps breaking off every 20 min or so and i need to restart to resume sync. This continues for a couple of hours a day and then download stops altogether for the remaining hours of day with error - no peers to resume download activity. Im left to wait another 24 hrs before i see some txn activity again.

i have tried everything from syncing system clock with time.nist.gov, enabled port forwarding to 30303, turned antivirus and firewall off etc.. but all in vain.

experiencing this issue on --rpc, --fast & console commands.

Please help!

#### Backtrace

````
[backtrace]
````

**Comment by pinecrest515** [comment]
Same issue, after an initial quick download for the first 200,000 blocks, the syncing really slows to about 256 blocks for every 2 minutes.  I've verified that it is not issue with unstable Internet connection, timer, port connection, firewall, etc.  

Also, when running the --fast, I am getting a synchronization failed, no peers error after a while.  It's not efficient to erase db every time this happens, so I am forced to go with the regular download, which after the first 200,000 or so blocks slows down to about 256 blocks every 2 minutes.

**Comment by obscuren** [comment]
Could you try 1.4 rc1 https://github.com/ethereum/go-ethereum/releases/tag/v1.4.0 and report back if your issues persist (or not)

**Comment by dhruv-9** [comment]
Good news is that im synced to last block now. I did this via regular download on geth 1.3.6 using --rpc and it took forever(16 days to be precise). I tried everything including trying to add active fully synced enodes manually and nothing helped push the pace. The only significant observation I made was that majority of the syncing took place between 3.30 AM - 8.30 am everyday western standard time. Download speeds ranged between 17 sec - 1min per 256 blocks. 

Fast sync helps too though you need to make sure you have a stable internet connection and a fast cpu. Any breaks while downloading the state side transactions and you'll have to start over again. Make sure not to interfere in the process until you see the message - 'fast sync complete. auto disabling'. Ppl i know have synced successfully using --fast sync and it took them no longer than a day.

Hope this info helps. 

Good luck!

**Comment by pinecrest515** [comment]
Thanks, the slow sync issue described persists while running the geth 1.4 console.  I have been opening and re-starting the geth 1.4 console for 2 days now, finally at 1,350,000 blocks...getting there.  Averaging about 256 blocks for every 2 minutes.   As described earlier --fast does not work efficiently in this situation as I run into "synchronization failed...no peers" error after running --fast for a while, and hesitate to wipe db and start over again, only to encounter the same sync issue.

**Comment by gsj5** [comment]
Hi,

I am trying to download Ethereum blockchain for the past week, and every attempt has failed for one reason or another.   Last two attempts appear to have corrupted chains perhaps due to "empty head header set" error(see logs below.)   After getting this error, block count has gone down back to 1, and subsequently "geth --fast"  gets automatically disabled.  Downloading subsequent blocks gets progressively slower, taking anywhere from 2 minutes to 30 minutes to process next block.

Would someone from the geth team please have a closer look at following logs.  If you require any additional information, please let me know.

**Environment**

Geth Version: 1.5.0-unstable
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.5.1
Linux  3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 

[*Logs of Third attempt...*]
I0505 08:52:43.117607 core/blockchain.go:751] imported 57 receipt(s) (0 ignored) in 35.84024ms. #904612 [721a7b17… / 83098843…]
I0505 08:52:44.479115 core/blockchain.go:751] imported 43 receipt(s) (0 ignored) in 22.063965ms. #904655 [97d396eb… / 4566be98…]
I0505 08:52:50.051243 core/headerchain.go:294] imported 192 header(s) (0 ignored) in 153.927648ms. #904847 [46e2fa35… / 53d830cb…]
I0505 08:52:51.196290 core/blockchain.go:751] imported 176 receipt(s) (0 ignored) in 142.817809ms. #904831 [46e2fa35… / 4d2678d9…]
I0505 08:52:59.369162 core/blockchain.go:751] imported 16 receipt(s) (0 ignored) in 2.450058ms. #904847 [d39f2998… / 53d830cb…]
I0505 08:53:00.680303 core/headerchain.go:294] imported 192 header(s) (0 ignored) in 221.741163ms. #905039 [4d57dacd… / 5fde38ed…]
I0505 08:53:04.549654 eth/downloader/downloader.go:1130] Rolled back 2048 headers (LH: 905039->902991, FB: 904847->902991, LB: 0->0)
I0505 08:53:06.229897 core/blockchain.go:751] imported 192 receipt(s) (0 ignored) in 340.412845ms. #905039 [4d57dacd… / 5fde38ed…]

**I0505 08:54:51.992812 eth/downloader/downloader.go:998] Peer 0b052862d7d52938 [blocks 0.00/s, receipts 0.00/s, states 0.00/s, lacking    0]: empty head header set**

I0505 08:55:44.690737 core/headerchain.go:294] imported 191 header(s) (1 ignored) in 408.797824ms. #905230 [5fde38ed… / 57cb1179…]
I0505 08:55:44.694533 core/blockchain.go:751] imported 1 receipt(s) (1 ignored) in 241.128µs. #905040 [5fde38ed… / 76aee05a…]
I0505 08:55:47.721676 eth/downloader/downloader.go:1130] Rolled back 191 headers (LH: 905230->905039, FB: 905040->905039, LB: 0->0)
I0505 08:55:49.488844 core/blockchain.go:751] imported 4 receipt(s) (0 ignored) in 789.393µs. #905044 [48e40f60… / 082074a5…]
I0505 08:55:49.766112 core/blockchain.go:751] imported 34 receipt(s) (0 ignored) in 14.433435ms. #905078 [f409fea7… / 25a188a2…]
I0505 08:55:49.789895 core/blockchain.go:751] imported 12 receipt(s) (0 ignored) in 2.138365ms. #905090 [605f5518… / 1d74c83e…]
I0505 08:55:51.015882 core/blockchain.go:751] imported 140 receipt(s) (0 ignored) in 298.996387ms. #905230 [ee4098e0… / 57cb1179…]
I0505 08:56:19.477816 core/headerchain.go:294] imported 0 header(s) (192 ignored) in 2.532442ms. #712570 [bbd2fd55… / 9a58c5e0…]
I0505 08:56:19.519859 eth/downloader/downloader.go:1372] imported 0 state entries in 1.283007ms: processed 0 in total
I0505 08:56:19.673618 eth/downloader/downloader.go:1372] imported 0 state entries in 107.356µs: processed 0 in total
I0505 08:56:19.779851 eth/downloader/downloader.go:1372] imported 0 state entries in 127.039µs: processed 0 in total
I0505 08:56:20.565955 eth/downloader/downloader.go:1372] imported 1 state entries in 559.807µs: processed 1 in total
I0505 08:56:20.616795 eth/downloader/downloader.go:1372] imported 0 state entries in 11.941005ms: processed 1 in total
I0505 08:56:20.648009 eth/downloader/downloader.go:1372] imported 0 state entries in 7.865926ms: processed 1 in total
I0505 08:56:20.675806 eth/downloader/downloader.go:1372] imported 0 state entries in 205.36µs: processed 1 in total
I0505 08:56:20.697938 eth/downloader/downloader.go:1372] imported 0 state entries in 581.381µs: processed 1 in total
I0505 08:56:20.778004 eth/downloader/downloader.go:1372] imported 1 state entries in 79.931905ms: processed 2 in total
I0505 08:56:20.778066 eth/downloader/downloader.go:1372] imported 0 state entries in 68.583675ms: processed 2 in total

**[*Logs of Fourth attempt...*]**

I0506 16:22:56.366388 core/headerchain.go:294] imported 192 header(s) (0 ignored) in 1.878031918s. #450086 [1fd0243f… / 6808ed53…]
I0506 16:22:57.450432 core/blockchain.go:751] imported 209 receipt(s) (0 ignored) in 1.971181683s. #449894 [c61b1827… / 46ee809b…]
I0506 16:22:57.712905 core/blockchain.go:751] imported 2 receipt(s) (0 ignored) in 354.311µs. #449896 [1fd0243f… / 1795b3d2…]
I0506 16:23:06.880466 eth/downloader/downloader.go:1130] Rolled back 1920 headers (LH: 450086->448166, FB: 449896->448166, LB: 0->0)
I0506 16:23:06.946466 core/blockchain.go:751] imported 190 receipt(s) (0 ignored) in 8.677346324s. #450086 [e85d349e… / 6808ed53…]
**I0506 16:24:54.289713 eth/downloader/downloader.go:998] Peer 17946d9af146f4ef [blocks 0.00/s, receipts 0.00/s, states 0.00/s, lacking    0]: empty head header set**
I0506 16:25:41.820794 core/headerchain.go:294] imported 192 header(s) (0 ignored) in 18.316232564s. #192 [fd337a68… / fafce6c5…]
I0506 16:25:56.875365 core/blockchain.go:959] imported 192 block(s) (0 queued 0 ignored) including 0 txs in 14.957557775s. #192 [fd337a68 / fafce6c5]
I0506 16:25:56.952506 core/headerchain.go:294] imported 0 header(s) (192 ignored) in 75.591242ms. #384 [967642fd… / d3d5d5c1…]

**I0506 16:25:57.136551 eth/downloader/queue.go:336] Header #193 [967642fd] broke chain ancestry
**I0506 16:25:57.239096 eth/downloader/downloader.go:1130] Rolled back 192 headers (LH: 192->0, FB: 192->0, LB: 192->0)
**I0506 16:27:40.439154 core/blockchain.go:959] imported 2 block(s) (0 queued 0 ignored) including 0 txs in 107.120649ms. #2 [88e96d45 / b495a1d7]**

I0506 16:27:40.481778 core/blockchain.go:959] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 7.250885ms. #3 [3d612266 / 3d612266]
I0506 16:27:43.287454 core/blockchain.go:959] imported 33 block(s) (0 queued 0 ignored) including 0 txs in 1.936560518s. #36 [23adf5a3 / 5f81bfa6]
I0506 16:27:56.739009 core/blockchain.go:959] imported 256 block(s) (0 queued 0 ignored) including 0 txs in 13.372601067s. #292 [0ee49bf8 / feeb6c4b]
I0506 16:28:08.936740 core/blockchain.go:959] imported 256 block(s) (0 queued 0 ignored) including 0 txs in 12.196890549s. #548 [75a4bcc3 / ab425bfb]
I0506 16:28:09.981647 core/blockchain.go:959] imported 29 block(s) (0 queued 0 ignored) including 0 txs in 1.044750096s. #577 [5684b6f0 / c4cee3bf]
I0506 16:28:30.360963 core/blockchain.go:959] imported 256 block(s) (0 queued 0 ignored) including 0 txs in 20.313028219s. #833 [a84b1363 / 5fe8ca24]
I0506 16:28:49.912905 core/blockchain.go:959] imported 256 block(s) (0 queued 0 ignored) including 0 txs in 19.551235112s. #1089 [ec0302fa / 35dc9154]
I0506 16:29:10.671437 core/blockchain.go:959] imported 256 block(s) (0 queued 0 ignored) including 0 txs in 20.75772801s. #1345 [9bfa758e / 87926eeb]
I0506 16:29:32.557689 core/blockchain.go:959] imported 256 block(s) (0 queued 0 ignored) including 0 txs in 21.885512238s. #1601 [01a66c7c / cf9daff8]
I0506 16:29:50.981428 core/blockchain.go:959] imported 256 block(s) (0 queued 0 ignored) including 0 txs in 18.423027978s. #1857 [37660ec4 / 52a883bf]
I0506 16:29:53.399158 core/blockchain.go:959] imported 63 block(s) (0 queued 0 ignored) including 0 txs in 2.417489693s. #1920 [ac4c2878 / 80013e0e]

**I0506 16:29:53.399206 eth/sync.go:180] fast sync complete, auto disabling**

I0506 16:30:07.016177 eth/downloader/downloader.go:274] Synchronisation failed: peer is unknown or unhealthy
I0506 16:31:04.889545 core/blockchain.go:959] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 33.266852ms. #1921 [4997d3f7 / 4997d3f7]
I0506 16:31:07.552914 core/blockchain.go:959] imported 2 block(s) (0 queued 0 ignored) including 0 txs in 194.732338ms. #1923 [1145f5d3 / 37ba3482]
I0506 16:31:12.043977 core/blockchain.go:959] imported 63 block(s) (0 queued 0 ignored) including 0 txs in 2.131238057s. #1986 [995c0339 / 82ccfce1]
I0506 16:31:21.615741 core/blockchain.go:959] imported 256 block(s) (0 queued 0 ignored) including 0 txs in 9.474523016s. #2242 [50b12562 / 703147f8]

**Comment by 18dew** [comment]
understand your bandwidth to solve this problem I faced it in here. If you
are in india you would face this problem as bandwith of ISP is in mega bits
per sec at times which limits download of full chain and you would be left
in constant sync state. -  Ref -
https://www.linkedin.com/pulse/blockchain-out-sync-harsh-patel?trk=mp-author-card

**Comment by gsj5** [comment]
@18dew, just for the record, I am running in AWS us-east1, so bandwidth should not be the issue.   My problem arises after 80% of the chain is downloaded as expected, and then some corruption occurs around ~700K to ~900K range.

Following is the outcome from last nights run.  There were three "empty head header set" log entries previous to the fourth entry at 09:13:15.631645 which seems to have renumbered the blockchain from 923850 to 505355.  Later on, at 09:49:19.206404, fast sync was disabled, but no log entry as to why?

I've attached the log file, in case information presented here does not give a full picture.
[nohup.out.zip](https://github.com/ethereum/go-ethereum/files/253499/nohup.out.zip)



I0507 09:12:40.483073 core/blockchain.go:751] imported 219 receipt(s) (0 ignored) in 5.715053187s. #923467 [4dca1459… / 88892f23…]
I0507 09:12:43.524825 core/blockchain.go:751] imported 256 receipt(s) (0 ignored) in 2.880065952s. #923723 [e8f9ada7… / 85796a70…]
I0507 09:12:44.645948 core/blockchain.go:751] imported 127 receipt(s) (0 ignored) in 1.120600664s. #**923850** [5a0080a7… / 29aeea19…]
**I0507 09:13:15.631645 eth/downloader/downloader.go:998] Peer 6d278166ecc937bc [blocks 0.00/s, receipts 0.00/s, states 0.00/s, lacking    0]:empty head header set**
I0507 09:13:51.371210 core/headerchain.go:294] imported 0 header(s) (192 ignored) in 2.604942ms. #**505355** [f4fc2829… / 118504b8…]
I0507 09:13:54.381531 core/headerchain.go:294] imported 0 header(s) (192 ignored) in 2.627593ms. #505547 [4a828873… / 72074903…]
I0507 09:13:55.831888 eth/downloader/downloader.go:1372] imported 0 state entries in 911.208µs: processed 0 in total
I0507 09:13:56.341073 core/headerchain.go:294] imported 0 header(s) (192 ignored) in 2.660891ms. #505739 [a11a26c3… / f7ff243d…]
I0507 09:13:57.740833 eth/downloader/downloader.go:1372] imported 1 state entries in 18.281617ms: processed 1 in total
I0507 09:13:58.129731 core/headerchain.go:294] imported 0 header(s) (192 ignored) in 429.677059ms. #505931 [cc058e8b… / ef5d67ab…]
I0507 09:13:58.209957 eth/downloader/downloader.go:1372] imported 0 state entries in 41.821724ms: processed 1 in total
I0507 09:13:58.235395 eth/downloader/downloader.go:1372] imported 1 state entries in 62.259334ms: processed 2 in total
[...]
**I0507 09:18:39.806797 core/blockchain.go:272] committed block #505164 [f4fc2829…] as new head**
I0507 09:19:24.990221 core/blockchain.go:959] imported 256 block(s) (0 queued 0 ignored) including 376 txs in 43.859894983s. #505420 [d0c1acce / 56a8999d]
I0507 09:20:46.765281 core/blockchain.go:959] imported 256 block(s) (0 queued 0 ignored) including 1187 txs in 1m21.772965005s. #505676 [5282ad6c / 92af02fb]
I0507 09:24:04.762961 core/blockchain.go:959] imported 256 block(s) (0 queued 0 ignored) including 1708 txs in 3m17.805470597s. #505932 [a036dcd3 / ac588b1c]
I0507 09:27:50.756329 core/blockchain.go:959] imported 256 block(s) (0 queued 0 ignored) including 1946 txs in 3m45.991845687s. #506188 [034c42f8 / aa41d412]
[...]
I0507 09:49:13.617461 core/blockchain.go:959] imported 256 block(s) (0 queued 0 ignored) including 200 txs in 18.79589628s. #514891 [9bde4e20 / 93b846a4]
I0507 09:49:19.008059 core/blockchain.go:959] imported 64 block(s) (0 queued 0 ignored) including 58 txs in 5.39033397s. #514955 [f9fab512 / 2270f1bb]
**I0507 09:49:19.206404 eth/sync.go:180] fast sync complete, auto disabling**
I0507 10:03:49.196068 eth/downloader/downloader.go:274] Synchronisation failed: no peers to keep download active
I0507 15:20:21.474309 core/blockchain.go:959] imported 1 block(s) (0 queued 0 ignored) including 2 txs in 68.779553ms. #514956 [c6e078be / c6e078be]
I0507 15:20:53.075403 core/blockchain.go:959] imported 256 block(s) (0 queued 0 ignored) including 266 txs in 26.057332775s. #515212 [3d52fa73 / f534cd4e]

**Comment by 18dew** [comment]
Agreed this is a different issue all together ...

**Comment by hynese** [comment]
go-ethereum is effectively unusable.

I'm in an Amazon data centre in EU/Ireland.

I cannot get it to sync. I am now trying with --fast option.

I completely deleted the database and ran:

`geth --fast --maxpeers "100" console 2>> ~/geth.log`

Amazon security group is wide open.

I am now getting this error:

I0515 20:03:19.525672 eth/downloader/downloader.go:1130] Rolled back 2048 headers (LH: 110830->108782, FB: 110830->108782, LB: 0->0)

Ubuntu 16.04, geth 1.4.3-stable

**Comment by fjl** [comment]
The issue has been identified. You can watch‎ #2569 for progress.

**Comment by obscuren** [comment]
Also setting maxpeers is generally a bad idea. Change this only if you know what you are doing. 100 peers requires you to relay and handle 4 times more data!

**Comment by karalabe** [comment]
Sync issues should be solves by the latest 1.4.6 release. Please check with that and reopen a new issue with details if sync failures still occur for you.
