### ISSUE TITLE
Stance on refactoring

### ISSUE THREAD

**Issue by piersy** [ethereum/go-ethereum#24712]
I recently saw @karalabe's [tweet](https://twitter.com/peter_szilagyi/status/1504887154761244673?s=20&t=h-iaR1mL9yIednBx_gJ-jQ) about the increasing complexity in ethereum, having worked on forks of ethereum for a few years now I have definitely felt the burden of that ever increasing complexity.

I have also been thinking that even without changing the protocol there are some areas of the code that could be simplified through some refactoring. I have some more specific ideas in mind and I'm wondering if there is any interest in discussing them / seeing PRs for them?

Asking first here rather than just diving straight in with PRs since there's probably quite a lot of work involved and the changes are likely to touch a lot of places in the code.

**Comment by karalabe** [comment]
It's a bit more complicated. Whilst refactors are welcome, much of the code contains insane cross optimizations - which are the root cause of the complexity. Other parts of the code are very very sensitive and we often prefer not to touch it vs breaking it.

So, feel free to make suggestions, but definitely please discuss first before diving it, otherwise it's gonna get problematic.

**Comment by s1na** [comment]
If you're interested in pursuing this further please open a ticket per refactoring suggestion for discussion and we'll take it from there.
