### ISSUE TITLE
block timestamp is older than transaction creation time

### ISSUE THREAD

**Issue by mlesterdampios** [ethereum/go-ethereum#24788]
I am trying to do some time-sensitive application.
I just noticed that when I created a transaction at let say `12:00:01`,
it's block timestamp is showing at `11:59:XX`

Correct me if i'm wrong.
I understand that blocks that started mining can contain new transactions that's why my tx falls to the last block.

My main question is, how can I assure that my transaction will fall into the earliest valid block, especially when the condition is `block.timestamp >= someDeadline` ?

I made some readings here: https://github.com/ethereum/go-ethereum/issues/24152
But I still got no idea on how to precisely do timers with this.

Thank you so much!

**Comment by rjl493456442** [comment]
The timestamp of block is assigned when the mining block is constructed. In the next ten seconds (because the average block time is around 12 seconds), miner will try to **re-generate** the mining block with latest pending transaction list  every three seconds, with the **origin timestamp**, to increase the revenue. So it can explain why your transaction is included in a block with smaller timestamp.

> My main question is, how can I assure that my transaction will fall into the earliest valid block, especially when the condition is block.timestamp >= someDeadline ?

I will recommend you to set the limit in your contract. Solidity does support to retrieve the timestamp of the current block, so you can compare and control the flow? https://docs.soliditylang.org/en/v0.8.13/units-and-global-variables.html
