### ISSUE TITLE
WARN err="context canceled" in Ubuntu 22.04

### ISSUE THREAD

**Issue by deivid1** [ethereum/go-ethereum#24790]
#### System information

Geth version: 1.10.17 and 1.10.16
OS & Version: Linux Ubuntu 22.04

#### Actual behaviour
I am receiving this error once in a while. I use 'light' syncmode.
In Ubuntu 21.10 I don't have this issue. Any idea? can it be a problem or can I just ignore it? 
I deleted the db a few times to start over but problem persists.
Thanks in advance.

WARN [04-30|00:27:11.612] Served eth_getLogs                       conn=127.0.0.1:39360 reqid=128 duration=1m0.000013544s err="context canceled"

**Comment by Kantitad** [comment]
รับ Outlook สำหรับ Andro<https://aka.ms/AAb9ysg>
________________________________
From: deivid1 ***@***.***>
Sent: Saturday, April 30, 2022 5:39:35 AM
To: ethereum/go-ethereum ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ethereum/go-ethereum] WARN err="context canceled" in Ubuntu 22.04 (Issue #24790)


System information

Geth version: 1.10.17 and 1.10.16
OS & Version: Linux Ubuntu 22.04

Expected behaviour
Actual behaviour

I am receiving this error once in a while. In Ubuntu 21.10 I don't have this issue. Any idea? thanks
WARN [04-30|00:27:11.612] Served eth_getLogs conn=127.0.0.1:39360 reqid=128 duration=1m0.000013544s err="context canceled"

**Comment by fjl** [comment]
This error just means that an internal timeout of one minute was reached while serving a `getLogs` request via RPC.
