### ISSUE TITLE
ethclient returns incorrect gas price for Transaction

### ISSUE THREAD

**Issue by npbool** [ethereum/go-ethereum#24841]
#### System information

Geth version: `1.0.17`
OS & Version: Arch Linux

#### Expected behaviour
GasPrice for mainnet transaction `0x6d4903754379195eaf6957878f3c47facf22c185e761c20b2b3d241fa43307d8` should return 
`57036244480`

#### Actual behaviour
go-ethereum/ethclient returns `76000000000`.

json response for the transaction is as below. GasPrice `0xd47a00600` is 57036244480 in decimal. It seems the hex is unmarshaled incorrectly.

Actually the embedded web3.js console or other libraries like web.py will return the correct value.

```
{
    "jsonrpc": "2.0",
    "id": 0,
    "result": {
        "hash": "0x6d4903754379195eaf6957878f3c47facf22c185e761c20b2b3d241fa43307d8",
        "accessList": [],
        "blockHash": "0x7e4c07756a69dd25f9b17b608bd8e86fa6730dd5bb8145a9952d39d41601eab3",
        "blockNumber": "0xe10361",
        "chainId": "0x1",
        "from": "0x8fd37c5da43d2f85137016533fa39c49d773e3de",
        "gas": "0x29b99",
        "gasPrice": "0xd47a00600",
        "input": "0xb3ab66b00000000000000000000000000000000000000000000000000000000000000001",
        "maxFeePerGas": "0x11b1f3f800",
        "maxPriorityFeePerGas": "0x77359400",
        "nonce": "0x2a",
        "r": "0xa2725482fd22bf051916dda3ef0c8b1268afd7fe071ff3957223623d3d12dde2",
        "s": "0x350fd8495941d74e6313f00f12ef78b9fed3b32e3b101390027aae230e4fb94",
        "to": "0xbe401896658fb7339762e8146db072bde126a55f",
        "transactionIndex": "0xc",
        "type": "0x2",
        "v": "0x1",
        "value": "0x2a303fe4b530000"
    }
}
```

#### Steps to reproduce the behaviour
```
ec, _ := ethclient.Dial(...)
tx, _, _ = ec.TransactionByHash(context.TODO(), common.Hex("0x6d4903754379195eaf6957878f3c47facf22c185e761c20b2b3d241fa43307d8"))
tx.GasPrice() // incorrect
```

#### Backtrace
None

When submitting logs: please submit them as text and not screenshots.

**Comment by karalabe** [comment]
The `76000000000` value matches with the `"maxFeePerGas": "0x11b1f3f800"`. Seems on the tx unmarshalling side, we will not parse the `GasPrice` field for 1559 txs. Bit of a werid situation because the actually consumed gas price is not part of the transaction, rather a computed field. Have to think how to approach this. CC @fjl

**Comment by karalabe** [comment]
Seems it's not that simple either, because internally 1559 tx do not have a `gasPrice` field in go-ethereum.

**Comment by holiman** [comment]
The ethclient is not just a thin json request-response wrapper. It gets the return, then converts the responses into `types.Transaction` (or `types.Header` etc). This means that any contextual info present in the json response is _lost_, which bites people from time to time. 

This happened earlier when we decided to return the clique miner in the `header.Miner` field -- when it was converted into `types.Header`, this change made the `Hash()` return incorrect value (since the actual header.miner field is all zeroes). 

So ethclient is prone to lose contextual info in json responses. This is unfortunately a side-effect of the conversion to `types`. 

In the case of transactions, the context we lose it the basefee of the block it was exceuted in, and so we cannot determine the `gasPrice`. 

I don't think we fix this -- you can either use a "more stupid" library, or use the transaction receipt to figure out what the `gasPrice` ended up with.

**Comment by fjl** [comment]
I agree with @holiman, it is better to request the receipt with the [TransactionReceipt](https://pkg.go.dev/github.com/ethereum/go-ethereum/ethclient#Client.TransactionReceipt) method.

**Comment by JanRuettinger** [comment]
> The ethclient is not just a thin json request-response wrapper. It gets the return, then converts the responses into `types.Transaction` (or `types.Header` etc). This means that any contextual info present in the json response is _lost_, which bites people from time to time.

I think all computed fields are lost. E.g. totalDifficulty is also lost. 

What do you think is the best way forward here?
Create new types which are only used in ethclient to consume json responses?

**Comment by fjl** [comment]
@JanRuettinger We will not change the ethclient API.

**Comment by JanRuettinger** [comment]
What way forward would you suggest for those who want to access exactly the data that is send in the json response?

I see the following options:
- Use light wrapper types around official Geth/types 
- Extract ethclient from repo adapt types (quite a bit of work; similar to https://github.com/jowenshaw/gethclient)

What would you recommend?

**Comment by fjl** [comment]
If you want to get the JSON-RPC result exactly, you can just call the API using package rpc instead.

```
type rpcBlock struct{
    Number hexutil.Uint64
    TotalDifficulty hexutil.Big
}

client, _ := rpc.Dial(...)

var result rpcBlock
err := client.Call(&result, "eth_getBlockByNumber", "latest", false)
```

Note that the `rpcBlock` type above is just an example. You can also get the result as a map or even use `json.RawMessage` to get the undecoded response.

**Comment by JanRuettinger** [comment]
Yes I do something similar right now. But it becomes messy quite quickly since you have to redefine all types (tx, logs, blocks, traces) including marshaling/unmarshaling functions. Then you end up with types which are not compatible with the rest of the very helpful functions in Geth.

**Comment by holiman** [comment]
> But it becomes messy quite quickly since you have to redefine all types (tx, logs, blocks, traces) including marshaling/unmarshaling functions

It shouldn't, really. Because if you use a more generic approach, basically "a thin json wrapper" as I mentioned above, then you don't have to actually define the types, you can just use the json-structure, and dig out the specific things you need when you need them. 

But yeah, it may become messy. We don't have any great fixes for that.
