### ISSUE TITLE
Clique Network Can transfer gasToken with 0 gasfee

### ISSUE THREAD

**Issue by fenQY** [ethereum/go-ethereum#24862]
I was deploy a Clique Netwrok by geth,   and was set miner.gasprice = 50000000000 to start it .   But I can still send transactions for free(it's only transfer gastoken). how to disable  it ?

![image](https://user-images.githubusercontent.com/42881904/168034543-7bd557eb-a3cb-4ea4-a20b-984b862c0727.png)

![image](https://user-images.githubusercontent.com/42881904/168035747-33147158-2dcf-43ce-a743-73ce573e8661.png)

**Comment by hsyodyssey** [comment]
Here's an same issue you can use for reference: https://github.com/ethereum/go-ethereum/issues/22292.

I think this is because the transaction you sent is a "local transaction." Thus, it is still acceptable for such transactions with a zero transaction fee.

Related Geth Code here: https://github.com/ethereum/go-ethereum/blob/master/core/tx_pool.go#L624-L627

**Comment by karalabe** [comment]
If you submit the transaction via your miner node, it will track it as "local" and allow mining without fees. This is mostly meant to allow mining pools to do their own payouts without gas. If you were to have a 2 node network and send the transaction from the non-miner, it wouldn't mine it any more.

**Comment by Theadri1900** [comment]
Hello,
i'm facing the same problem but as @karalabe mentionned it i use two different docker which runs a different geth instance :
![image](https://user-images.githubusercontent.com/22106021/223449479-1f68e6b0-755a-4877-a36d-82ccf919847f.png)

As you can see i set the minimum gasprice at 50 Gwei and metamask broadcast it to the "public" node which don't mine. But the miner despite the miner.gasprice mined it ...

I'm running POA too
