### ISSUE TITLE
about feed event

### ISSUE THREAD

**Issue by smallfish-root** [ethereum/go-ethereum#24872]
HI, I have a question about feed event as follow:
Delete removeSub from sendCase when send, so another removeSub how to handle in send.
THX
![image](https://user-images.githubusercontent.com/75240003/168248140-9c8bbaab-2dd8-462c-a933-109200d089d2.png)

**Comment by holiman** [comment]
Could you please try to expand the question a bit? As it is, it's a bit unclear what you mean

**Comment by smallfish-root** [comment]
> Could you please try to expand the question a bit? As it is, it's a bit unclear what you mean

I mean when the event is published, this field(removeSub) is removed from the sendCase list, and then the rest of the cancelled subscribers are processed here?  In other words, this field(removeSub) is unnecessary?

**Comment by fjl** [comment]
I also don't understand your question completely. 

In Feed.Send, the `cases` list keeps the cases of the select operation. The first select case (index 0) is a read operation on the `removeSub` channel. The remaining select cases are send operations on subscription channels. `removeSub`  is used to cancel subscriptions. When a subscription is canceled/unsubscribe while `Send` is active, the subscription channel must be removed from the select cases because it is not allowed to send on a subscription channel after `Unsubscribe` has returned.

If you think this can be implemented better or more efficiently, please make a pull request or propose a diff. The tests will also show if your idea works or not.
