### ISSUE TITLE
How to set etherbase with contract address  on Clique Network?

### ISSUE THREAD

**Issue by fenQY** [ethereum/go-ethereum#24894]
Hello brothers, I was deployed a Clique network, and  want collect gasfee from all verify-nodes in one contract for uniform redistribution.    But I noticed that it seemed to only be set to a local address.   How do I do that?

**Comment by fenQY** [comment]
I tried to modify the source code but could not find the function for miners to reward gas in POA mode。

**Comment by hsyodyssey** [comment]
You want to set your coinbase address to a centain contract address?

**Comment by rjl493456442** [comment]
In clique network, the signer notion is basically equivalent to a miner in PoW. And in Geth the first account in your local keystore will be used as the signer unless you specify it explicitly via `--miner.etherbase`.

And as you said, you want to modify the source code a bit for other purposes, you can check the block generation logic here https://github.com/ethereum/go-ethereum/blob/4b309c70065e68321f6ba518f35b0454a5c929a9/miner/worker.go#L977 If you modify the coinbase field then all transaction fee will be gathered to this address.

**Note, there is no block reward in clique network, only transaction fee**

And I will close this ticket since it's not that relevant with go-ethereum itself.

**Comment by Sunmimy** [comment]
yes， but it only support local accounts .
________________________________
发件人: Siyuan Han ***@***.***>
发送时间: 2022年5月17日 23:37
收件人: ethereum/go-ethereum ***@***.***>
抄送: agold ***@***.***>; Author ***@***.***>
主题: Re: [ethereum/go-ethereum] How to set etherbase with contract address on Clique Network? (Issue #24894)


You want to set your coinbase address to a centain contract address?

―
