### ISSUE TITLE
Client ends up with empty peer list after several hours

### ISSUE THREAD

**Issue by pnomarev** [ethereum/go-ethereum#2507]
#### System information

Geth version: 1.3.6
OS & Version: Windows

#### Expected behaviour

Maintain peers list

#### Actual behaviour

At some point stops peer discovery(most likely to happen during full sync, less likely when the node is fully synchronized)
In the main server cycle, when `newTasks` decided to perform discoveryTask, this task may not make it to the scheduled tasks(if active tasks count >= maxActiveDialTasks). As a result, `newTasks` still thinks that discoveryTask was initiated, and the whole discovery process stops until client's restart.

p2p/server.go:

        scheduleTasks := func(new []task) {
		pt := append(pendingTasks, new...)
		start := maxActiveDialTasks - len(tasks)
		if len(pt) < start {
			start = len(pt)
		}
		if start > 0 {
			...
		} 
                //// This part is missing
                else {
			pendingTasks = append(pendingTasks, new...)
		}
                //////////////////////////////////////
	}

**Comment by fjl** [comment]
looking

**Comment by fjl** [comment]
I looked and don't see the bug, at least not in the place that you highlighted.
[This commit](https://github.com/ethereum/go-ethereum/pull/2510/commits/da1ba583db2bf36122b845178199cf469459f62b) improves the code a bit
so the slice handling is less weird.

But you probably submitted this issue because it didn't work for you. Can you please describe what is
happening and maybe give log output? The other issue fixed by #2510 can be a cause for the 
problem that you mentioned (discovery not finding any more nodes).

**Comment by pnomarev** [comment]
Looks like your mentioned commit solves the problem I described, although I haven't tested it yet.
The problem can be reproduced by simply running the client behind the firewall and thus preventing incoming connections on port 30303. This would prevent other peers to connect to you.
Now, once your client have "discoverTask" appearing in the scheduled tasks, your client will continuously discover new peers and connect to them.
But, once this discoverTask is dropped due to mentioned bug(didn't make it to the queue), your client stops getting new peers and looses all of them after some time.

Overall, to reproduce the issue - simply start fresh geth client without any local database with your 30303 port closed for incoming connections ( probably the majority of peers ).
