### ISSUE TITLE
Terminal block is unknown parent

### ISSUE THREAD

**Issue by paulhauner** [ethereum/go-ethereum#25427]
#### System information

Geth version: `v1.10.21`
OS & Version: Linux
Commit hash : NA

#### Description

In Lighthouse CI we have a series of "execution integration tests" where we test some scenarios between Geth and LH.

Since these tests started running on v1.1.0.21, we've noticed a change in behaviour. The previous behaviour was:

1. LH uses `getPayload` to request a payload from Geth.
    1. Geth response with a `payload`.
2. LH sends a `forkchoiceUpdated` for the `payload` that was returned 
    1. Geth response with `SYNCING`
3. LH sends a `newPayload` with the `payload`
    1. Geth responses with `VALID`
    
Now, with v1.10.21 Geth responds in 3.i with `ACCEPTED`. I believe this response violates the *"the payload doesn't extend the canonical chain"* point of the [newPayload API](https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md#engine_newpayloadv1).

I'm aware that an fcU before newPayload is weird behaviour, so I don't see this as an immediate issue. However I thought it's worth raising to your attention :relaxed:

**Comment by karalabe** [comment]
This seems very odd, I can't see anything in the code that could explain missing the genesis block.

**Comment by karalabe** [comment]
Could you provide some dump of the payload json you're transmitting? Something seems off here

**Comment by karalabe** [comment]
Quoting my comment from the Lighthouse repo:

> Hey all, the new behavior is correct (though it should have returned SYNCING), just changed from the previous incorrect one.

Geth by default starts in snap sync mode. In snap sync, the node *must* finish a sync cycle first before it accepts blocks. The reason is that snap sync goes around all block validation pathways and writes stuff directly to the database, so it cannot allow some process to inject something conflicting out of band. I.e. if Geth is asked to snap sync, it will deny importing a payload on the engine API until snap sync finishes.

You should start geth with `--syncmode=full` if you want to test feeding Geth blocks from #1 onward via the engine API.

**Comment by karalabe** [comment]
We should however fix the warning log and the return code to make this funny behavior obvious.
