### ISSUE TITLE
--exitwhensynced doesn't work after the goerli merge

### ISSUE THREAD

**Issue by hdiass** [ethereum/go-ethereum#25517]
#### System information

Geth version: `v1.10.21`
OS & Version: Linux

#### Expected behaviour
Expected to see geth cleanly stopping when it gets synced.

#### Actual behaviour
Nothing, continues to work as it was ran without that flag

#### Steps to reproduce the behaviour
Run geth with --exitwhensynced flag

**Comment by rjl493456442** [comment]
Do you have a beacon node setup? Just for more information before I dive in.

**Comment by hdiass** [comment]
Hello yes i do, is it possible to run goerli without it ?

Thanks,

**Comment by rjl493456442** [comment]
@hdiass I can exit the sync without no issue. Perhaps you don't have the correct setup for either beacon node or geth?

my setup

[[ beacon node ]]

```
./lighthouse beacon_node --network goerli --execution-endpoint http://127.0.0.1:8551 --execution-jwt ...  --checkpoint-sync-url ... --datadir .
```

[[ Geth ]]
geth --goerli --datadir . --port xxx  --exitwhensynced

**Comment by hdiass** [comment]
I'm using IPC , and using prysm as CL , but other than that nothing seems broken

**Comment by rjl493456442** [comment]
Can you try http for `--execution-endpoint`? I don't think Geth will expose `engine` API over IPC.

**Comment by hdiass** [comment]
Is it possible that Geth doesn't expose engine api over IPC and the goerli node can continue ?

**Comment by hdiass** [comment]
Anyway tested your approach and same happened..
```
INFO [08-22|13:52:04.515] Imported new potential chain segment     blocks=1  txs=20  mgas=10.483  elapsed=123.611ms    mgasps=84.806  number=7,451,886 hash=6c299f..333cf9 dirty=50.95MiB
INFO [08-22|13:52:04.582] Chain head was updated                   number=7,451,886 hash=6c299f..333cf9 root=a77b3c..bb3555 elapsed=1.563204ms
INFO [08-22|13:52:04.582] Unindexed transactions                   blocks=1  txs=1   tail=5,101,887 elapsed="299.555µs"
INFO [08-22|13:52:27.292] Imported new potential chain segment     blocks=1  txs=91  mgas=25.606  elapsed=237.867ms    mgasps=107.650 number=7,451,887 hash=b11919..59c5be dirty=51.56MiB
INFO [08-22|13:52:27.449] Chain head was updated                   number=7,451,887 hash=b11919..59c5be root=1a03b0..668c33 elapsed=10.74897ms
INFO [08-22|13:52:27.450] Unindexed transactions                   blocks=1  txs=1   tail=5,101,888 elapsed="136.657µs"
```

` --jwt-secret=/path/geth/jwtsecret --http-web3provider=http://localhost:8551`

**Comment by hdiass** [comment]
It should've stopped at this point of the log

**Comment by fjl** [comment]
It seems that the engine API does not expose enough information to make `--exitwhensynced` work in all cases. In scenarios where the CL itself is also syncing, we will not trigger an internal 'sync' event, and thus the 'sync' will never be considered finished.

**Comment by AusIV** [comment]
I've been working around this with lighthouse by running:

```
geth --options &
GETHPID=$!
lighthouse bn --options --shutdown-after-sync
kill $GETHPID
wait $GETHPID
```

So Geth runs in the background and my script shuts it down after lighthouse is synced.

**Comment by hdiass** [comment]
problem is that geth doesn't stop :)

**Comment by MariusVanDerWijden** [comment]
The problem with `--exitwhensynced` is that there are two ways for us to sync post-merge. 
The first way, where `--exitwhensynced` still works is if the beacon node provides us a head and we start snap syncing (or full syncing) to that head. 
The other way is if the beacon node provides us blocks one by one. In this scenario we don't know when we arrived at the head and finished our sync. 

In most cases the beacon node will use the first way, only if you shut down a synced beacon node and restarted will it use the second way. What you can do is to specify a pretty recent synctarget via `--synctarget` which will instruct your node to try to sync to this target and stop or you use the script that @AusIV provided.

I'm closing this for now since there is not much that we can do about it, since only the beacon node knows whether we are truly synced or not post-merge.
