### ISSUE TITLE
Why method  'eth_blockNumber' doesn't have a parameter for commitment level (last, safe, finalized)?

### ISSUE THREAD

**Issue by biganashvili** [ethereum/go-ethereum#25773]
geth version: Sentry Omega (v1.10.23)
network: goerli

request: 
`{"jsonrpc":"2.0","method":"eth_blockNumber","params":["safe"],"id":1}`
response:
`{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32602,
        "message": "too many arguments, want at most 0"
    }
}`

**Comment by karalabe** [comment]
That is the way the method always worked. It's a bit of a less useful endpoint mind you, because it just gives you a number, but not the hash, so you can go wild reorging and the number will stay the same.

You should use eth_getBlockByNumber to retrieve the a specific block and have the necessary guarantees.
