### ISSUE TITLE
Does Geth light node still available for RPC call after the merge?

### ISSUE THREAD

**Issue by Nevknight** [ethereum/go-ethereum#25781]
When using light node, it stopped syncing and log showed
```
the method engine_exchangeTransitionConfigurationV1 does not exist
```
Geth version is 1.10.24

**Comment by rjl493456442** [comment]
The sync mechanism for light client is not delivered yet. So theoretically light client won't work after the merge. However, technically it can still sync *without* beacon client, but it's not safe at all without consensus security guarantee.

So if you only want to retrieve some data without high security requirement, maybe you can try it, otherwise I will recommend you to switch fullnode until we deliver the PoS-complete light client.

**Comment by Nevknight** [comment]
> The sync mechanism for light client is not delivered yet. So theoretically light client won't work after the merge. However, technically it can still sync _without_ beacon client, but it's not safe at all without consensus security guarantee. In another word, it blindly trusts the ethereum full node.
> 
> So if you only want to retrieve some data without high security requirement, maybe you can try it, otherwise I will recommend you to switch fullnode until we deliver the PoS-complete light client.

Thanks.
