### ISSUE TITLE
Race Condition on fetcher.insert

### ISSUE THREAD

**Issue by mvanotti** [ethereum/go-ethereum#2583]
On the insert function, when a new block is added, it is propagated AND announced.

First, [broadcastBlock is called in a goroutine](https://github.com/ethereum/go-ethereum/blob/master/eth/fetcher/fetcher.go#L754-L758), which propagates the block and announces it if it is already in the blockchain.

Then the [block is inserted in the blockchain](https://github.com/ethereum/go-ethereum/blob/master/eth/fetcher/fetcher.go#L769-L776) and announced again (in a goroutine)

So, if the first goroutine executes after the block is inserted in the blockchain, the block hash could be announced twice.

**Comment by karalabe** [comment]
That shouldn't really be a problem since the propagation code checks to only send blocks/announcements to peers that have not been notified yet: https://github.com/ethereum/go-ethereum/blob/master/eth/handler.go#L712 . Indeed there is a small window where the peers's list of known hashes isn't updated yet and a second announce could take place, but does this actually happen often in practice?

**Comment by mvanotti** [comment]
I see, thanks for pointing that out. I thought the notify didn't add the block to the peer. The block is marked as known in sendBlockHashes.

So, the race condition still exists, it is just that it has a small window.

**Comment by fjl** [comment]
I will close this now because we won't change it any time soon. @mvanotti if you're interested, this would make a good first contribution ;)
