### ISSUE TITLE
Not visible my node on ethernodes.org. What I'm doing wrong?

### ISSUE THREAD

**Issue by theaidem** [ethereum/go-ethereum#2588]
#### System information

Geth version: `geth version`
```
Geth
Version: 1.4.4-stable-94ad694a
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.6.2
OS: linux
GOPATH=
GOROOT=/opt/google/go
```

#### Expected behaviour

check my node on ethernodes.org

#### Actual behaviour

doesnt appear in node list

#### Steps to reproduce the behaviour

run Geth with fast mode

```
geth --fast --cache=1024 --jitvm --identity "OmskLines"
```

Node Info: `>admin.nodeInfo`:

```
{
  enode: "enode://8a6661dd8a6004fd57f9e7aee3d5c9c70c63475154d4ee4101edd9d1285a50c46b2815b3eaa0fdf0d20cf2733f6e8d9492825e3786d73a28bae628adee92fdf5@172.16.0.49:30303",
  id: "8a6661dd8a6004fd57f9e7aee3d5c9c70c63475154d4ee4101edd9d1285a50c46b2815b3eaa0fdf0d20cf2733f6e8d9492825e3786d73a28bae628adee92fdf5",
  ip: "172.16.0.49",
  listenAddr: "[::]:30303",
  name: "Geth/v1.4.4-stable-94ad694a/linux/go1.6.2/OmskLines/JIT",
  ports: {
    discovery: 30303,
    listener: 30303
  },
  protocols: {
    eth: {
      difficulty: 20780355635374740000,
      genesis: "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3",
      head: "0x02bf9dff7891ffb9a196eb8a0e9a48ab9a059007f6970c1b63e4a40af8db55bd",
      network: 1
    }
  }
}
```

**Comment by karalabe** [comment]
There is no service built into geth that will get your node on any listing, ethernodes or otherwise.

Ethernodes itself works by running a few nodes and seeing who connects to it, and also by randomly connecting to nodes advertised by the discovery service. Though it's a closed private system, so I have no idea of exactly how they collect their statistics. Either way, it takes time for new nodes to be discovered since it's like shooting in the dark and seeing who responds. Give it time, it will eventually find it it the node runs for longer periods of time.
