### ISSUE TITLE
Inconsistency with stack depth check in js-tracer

### ISSUE THREAD

**Issue by cattingcat** [ethereum/go-ethereum#25910]
I found inconsistency with error messages about stack underflow. For example:

Some commands returns error with log.getError()

code:
```
var err = log.getError();
    if (err) {
      this.callContractEnter = false;
      this.debug.push([log.getPC(), log.op.toString(), log.getDepth(), this.callstack.length, 'err step', err]);
      ...
```

```
Array(6) [0, LOG4, 3, 3, err step, stack underflow (0 <=> 6)]
Array(6) [0, AND, 3, 3, err step, stack underflow (0 <=> 2)]
Array(6) [0, DUP9, 3, 3, err step, stack underflow (0 <=> 9)]
```

And REVERT called in both places in step function with empty stack (in my case) so I can't get stack params because it breaks my traces
and after that it is processed inside fault function

Transaction with lots of stack issues: 0x93985273e6b0a0744a09261cd75fa5abd7ebacb9406ccff25a89463a303f4cda (mainnet)

Is it correct behaviour?

**Comment by live-suppo** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue
https://direct.lc.chat/14571264/

**Comment by karalabe** [comment]
Could you please write up a tiny self contained js tracer thta reproduces the issue you're seeing? It would help us a lot to have something we can run and see vs having to guess the missing parts.

**Comment by cattingcat** [comment]
Yep, no problem @karalabe 

Here is tracer:
```
{
  tst: [],

  fault: function (log, db, err) {
  },

  step: function (log, db) {
    var opcode = log.op.toNumber();
    var symbol = log.op.toString();
    var err = log.getError();
    if (err === 'out of gas') {
      return;
    }
    if (err) {
      this.tst.push(['if err', symbol, err]);
      return;
    }

    // REVERT
    if (opcode === 0xFD) {
      if (log.stack.length() === 0) {
        this.tst.push(['opcode process', symbol, 'not enough args during opcode process']);
      }
    }

  },

  result: function (ctx, db) {
    var counter = 0;

    return {
      tst: this.tst,
    };
  }
}

```

The problem is here
```
this.tst.push(['opcode process', symbol, 'not enough args during opcode process']);
 ```
 
 It is expected to not be called at all, because of `return` in `if err` condition, but actually it is called with not enough stack args

<img width="719" alt="image" src="https://user-images.githubusercontent.com/5341725/198581793-adeac771-c9b1-4e6f-9b1d-fd9b898e4924.png">

All opcodes process stack underflow in `if err`, but REVERT doesn't

**Comment by holiman** [comment]
That transaction, https://etherscan.io/tx/0x93985273e6b0a0744a09261cd75fa5abd7ebacb9406ccff25a89463a303f4cda , was in [2.4M](https://etherscan.io/block/2419253). At that point in time, REVERT did not exist as an opcode (it was added in Byzantium at block 4.37M), so it should instead get an error due to being an invalid opcode. 

Now, we do this little trick internally
```golang
	// Fill all unassigned slots with opUndefined.
	for i, entry := range tbl {
		if entry == nil {
			tbl[i] = &operation{execute: opUndefined, maxStack: maxStack(0, 0)}
		}
	}
```
We define them as actual opcodes, with an exec-function like this: 
```golang
func opUndefined(pc *uint64, interpreter *EVMInterpreter, scope *ScopeContext) ([]byte, error) {
	return nil, &ErrInvalidOpCode{opcode: OpCode(scope.Contract.Code[*pc])}
}
```
So it will _not_ hit a stack depth error (`maxStack: maxStack(0, 0)}`), but executing it _should_ return this error

```
func (e *ErrInvalidOpCode) Error() string { return fmt.Sprintf("invalid opcode: %s", e.opcode) }
```
However, this is one of those times where we will callback  twice. One just before the exec: 
```
			in.cfg.Tracer.CaptureState(pc, op, gasCopy, cost, callContext, in.returnData, in.evm.depth, err)
			logged = true
		}
		// execute the operation
		res, err = operation.execute(&pc, in, callContext)
```
And the `err` will be non-nil, and we will execute the deferred one for the fault during exec: 
```
					in.cfg.Tracer.CaptureFault(pcCopy, op, gasCopy, cost, callContext, in.evm.depth, err)
```

So the TLDR is that different errors happen at different times. For stack depth errors, they happen early, and we can call-back about them early. 

For other errors, such as errors during exec of the opcode, they happen late. We have already emitted a calback prior to the exec, and thus we emit a second via captureFault for this error. The only surefire way to disambiguate is: if two callbacks happen sequentially and they both concern the same PC, then they are one and the same (and can be merged.)

Yeah, it's not ideal, or remotely user-friendly, but it's the way it is. Closing this since I don't see us changing this anytime soon.
