### ISSUE TITLE
latest 1.10.25 won't do initial sync until CL is sync

### ISSUE THREAD

**Issue by garyng2000** [ethereum/go-ethereum#25936]
The 1.10.25 add the condition that it would only start to sync when the CL layer is fully sync. This make setting up a new node more time consuming(may need 1-2 days to first sync in prysm) then geth.

and in prysm, I am seeing this because EL is not synced, so it becomes a chicken and egg issue.

"ERROR powchain: Unable to process past deposit contract logs, perhaps your execution client is not fully synced error=no contract code at given address"

I assume that even though it is shown as error, it probably is fine but just odd.

Can there be a flag to disable this behaviour ? As pre-merge data can be synced without CL.

**Comment by holiman** [comment]
>  I am seeing this because EL is not synced, so it becomes a chicken and egg issue.

The solution to the chicken and egg problem is that CL does an "optimistic sync". Using checkpoints usually help. 

> Can there be a flag to disable this behaviour ? As pre-merge data can be synced without CL.

Yes and no. The pre-merge data only helps so far. So, in theory, it could 

- Do a block by block import from genesis until merge, This is still possible, via `syncmode=full`. 
- Do a header by header verification up until merge. Geth could download headers and block bodies until this point, but would not be able to download state data, since it's stale and forgotten by the network at this point in time. Geth would still have to wait for CL to direct where to 'go next', and then download the remaining headers (and hope they link up) and bodies, and then sync the state. Since the state-sync is often the most intense part, this way of syncing doesn't help a lot. 

So not really a lot of good choices here. We're doing what we can
