### ISSUE TITLE
NVIDIA GPU Mining - Urgent fix needed regarding drivers

### ISSUE THREAD

**Issue by Crasha** [ethereum/go-ethereum#2594]
#### System information

Geth version: `1.4.4 stable`
OS & Version: Windows 10 64bit
Graphics Card: Geforce GTX 980 TI SC
Commit hash : N/A

#### Expected behaviour
According to ethminer.exe -G -M - I'm supposed to get about 18MH/s. This is meant to be the same when actually mining too.

#### Actual behaviour
When actually mining, I get 4-5MH/s. Rolling back the drivers is NOT an option since they don't support the 980 TI thus a better fix must be found.

#### Steps to reproduce the behaviour
Windows 10 64bit with up to date drivers for NVIDIA.

#### Backtrace

````
[backtrace]
````

**Comment by obscuren** [comment]
Ping @chriseth 

`etherminer` is developed under the C++ repository and is included in the C++ suite. @chriseth can tell you where to open the issue :-)

**Comment by Crasha** [comment]
Thanks!

**Comment by chriseth** [comment]
@Crasha did you try the genoil miner? It usually works much better across the range of devices. If you want, you can open an issue in webthree-umbrella

**Comment by Crasha** [comment]
Yeah I tried every type of miner. Still the same issue. I'll open an issue
over there. Thanks.

**Comment by Genoil** [comment]
This is not a bug, rather a hardware limitation imposed by the new WDDM driver model. The limited page size causes the GPU TLB to fill up quickly on a kernel like ethash, causing a lot of global memory replays.

This is fixed with WDDM 2.1 (win10 annicersary), but it also requires Pascal hardware to work. Your bedt workaround now is to use Win7 or Linux.
