### ISSUE TITLE
geth cache width CPU

### ISSUE THREAD

**Issue by Black-Memory** [ethereum/go-ethereum#25970]
Configuration: 32 cores, 1.8T SSD disk, memory 257G, geth 1.10.25
Enable configuration for the first time

```
geth --cache 30720 --datadir /data/eth/geth --http --http.port 8545 --http.vhosts '*' --http.corsdomain '*' --http.api eth,web3,net - -ws --ws.addr 0.0.0.0 --ws.port 8545 --ws.api eth,net,web3 --ws.origins '*' --graphql --graphql.corsdomain '*' --graphql.vhosts '*' --authrpc.jwtsecret=/data/eth/jwtsecret --allow-insecure-unlock
```

Second enable configuration

```
geth --cache 4096 --datadir /data/eth/geth --http --http.port 8545 --http.vhosts '*' --http.corsdomain '*' --http.api eth,web3,net - -ws --ws.addr 0.0.0.0 --ws.port 8545 --ws.api eth,net,web3 --ws.origins '*' --graphql --graphql.corsdomain '*' --graphql.vhosts '*' --authrpc.jwtsecret=/data/eth/jwtsecret --allow-insecure-unlock
```

The CPU would be fully loaded before. In order to find the problem, I modified the cache configuration. After restarting, the CPU obviously increased, and 100% will not appear. Is there any problem here?
![image](https://user-images.githubusercontent.com/18435334/195216188-1f1fe84a-d121-4a2e-a4d9-d8f17dcc2add.png)

**Comment by rjl493456442** [comment]
Thanks for the report. It might be relevant with the cache library we are using and should be worthwhile for investigation.

**Comment by jsvisa** [comment]
@Black-Memory could you please give more metrics about the before && after's geth's status, eg: 

- syncing status;
- rpc requests;
- ...

If you have enabled Prometheus + Grafana, maybe you can use [dashboards/13877-single-geth-dashboard/)](https://grafana.com/grafana/dashboards/13877-single-geth-dashboard/) to view more metrics.

**Comment by holiman** [comment]
Having `30G` cache instead of `4` means we juggle a lot more data in-app. We do more work on pruning, and leveldb has a lot more memory caches to search. Less memory means we wait more for IO. 

You also seem to have exposed ws on the public `0.0.0.0` interface. Is it possible that someone was performing resource-intensive queries until you shut it off? 

Also, the logs from when it was doing 100% would be relevant. Not much we can say at this point. When geth is in sync and just processing blocks every now and then, it should look more like it does on the latter end, than the former end. 

I don't see any actionable item from us here. I'm closing, but feel free to reopen if you think there's some bug here that I'm missing, and that you can provide information about.
