### ISSUE TITLE
Request: admin.setTime()

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/go-ethereum#2615]
I'm working on a time dependent contract. Unfortunately, there doesn't seem to be a good way to test it. Would it be possible to add an api for updating the evm's time?

**Comment by paultiplady** [comment]
It seems that without this, it's impossible to test (and therefore safely deploy) any contract which has a time-dependent aspect, i.e. any usage of the `now` function in Solidity. Is there another option for testing these cases?

It looks like this issue will be the case with the default tooling, but it may be possible to swap in another EVM, e.g. `pyethereum` into the test framework to cover these time-dependent test cases. However it's not clear that there's a good way to manipulate time in pyethereum either (though Python is fundamentally more malleable since it can be monkey-patched).

**Comment by DaveAppleton** [comment]
If you are using simulatedBackend to test your contract, adjustTime exists.

**Comment by lelikalf** [comment]
type
