### ISSUE TITLE
Spin up ethereum node from snapshot

### ISSUE THREAD

**Issue by Malak-youness** [ethereum/go-ethereum#26325]
I have a synced full Ethereum node to mainnet on AWS. When I try to take a snapshot of the disk, where Ethereum data is saved, and immediately give it to a new node [ the new node is approximately 73 blocks away ]. It takes about an hour to resync with the network [ the  difference between local latest block number and network latest block number keeps increasing until after 50 mins it starts to drop at a higher rate until it is synced with the network] . 

Why does it take that long to resync, knowing that all the data is already found in the snapshot? Or is this way of snapshotting not valid and there is another way?

**Comment by rjl493456442** [comment]
Perhaps you can post some logs here from the new node, it's not enough for us to know what might be the issue, or if it's Geth's issue.

**Comment by Malak-youness** [comment]
Here are some of the logs. Nothing out of the ordinary! 
![image](https://user-images.githubusercontent.com/112073758/206374685-ee5b72e9-1043-44a8-9ebc-f0a05f7eaa2a.png)
![image](https://user-images.githubusercontent.com/112073758/206374781-e6187c06-c48d-4a83-9a3e-af898a6ac92f.png)
![image](https://user-images.githubusercontent.com/112073758/206374892-fa8baf36-04ad-49dd-ac28-8e651f129b56.png)


> Perhaps you can post some logs here from the new node, it's not enough for us to know what might be the issue, or if it's Geth's issue.

**Comment by rjl493456442** [comment]
It feels like leveldb is compacting somehow. I am not sure how does AWS manage the data. But it turns out some block executions take up to 1 minute, which is definitely impacted/blocked by database.

**Comment by Malak-youness** [comment]
I will look into  it. 

I have another question though. Is the checkpoint URL passed to the lighthouse consensus client related to the idea of starting a node from a recent block ((i.e. snapshot) instead of from genesis block? And should geth syncing mode in that case be snap ? 

> It feels like leveldb is compacting somehow. I am not sure how does AWS manage the data. But it turns out some block executions take up to 1 minute, which is definitely impacted/blocked by database.

**Comment by rjl493456442** [comment]
Checkpoint URL is only relevant with consensus layer client. It will fast bootstrap consensus layer client and let it sends signal to Geth.

It doesn't matter geth is launched with snap or full sync mode.

**Comment by rjl493456442** [comment]
Checkpoint is just a hint for consensus layer, so that consensus layer can fast bootstrap and be aware of what's the current head of the network. Then Geth will backfill the missing data between local chain and this "network chain head" by syncing mechanism.

If Geth uses full sync, then all the missing chain segments will be pulled from the network with verification and replay all transactions inside locally.

If Geth uses snap sync, then all the missing chain segments and the corresponding states will be pulled from the network with verification, the pulled state will be used as the base to handle blocks on top.

I will just close the issue. But feel free to reopen if necessary.
