### ISSUE TITLE
Slow sync

### ISSUE THREAD

**Issue by kingteddy** [ethereum/go-ethereum#2633]
#### System information

Geth version: 1.4
OS & Version: Windows 8.1 pro
Commit hash : (if `develop`)

#### I have tried to re sync multiple times and now it is very slow. Please advise on how to fix this problem.
<img width="425" alt="screenshots1" src="https://cloud.githubusercontent.com/assets/19600329/15628390/cb0797e8-24b4-11e6-8b32-16b0df978843.PNG">

**Comment by anton44eg** [comment]
I also have sync troubles with both geth 1.4.X and 1.3.X. Running it in Ubuntu server, 30303 port is open

**Comment by karalabe** [comment]
@jdevoo Good to hear it. I'm guessing you're on an HDD. The database is quite huge and our data layout wasn't optimized for HDD access patterns. We're working on reorganizing the data to make it faster on HDDs and also on state pruning, but that will be slated to our next major release. The current 1.4.6 meant to sort out any networking issues so that we can have a stable data stream for everyone.

You might also try backing up your `chaindata` folder and redoing a fast sync. It should make it a ton smaller (4GB) and hence make processing way way faster for subsequent blocks.

@kingteddy @anton44eg Please try with Geth 1.4.6. It's the latest release specifically addressing sync stability. I'll close this issue. Feel free to open ones against our latest release if some issues still persist.
