### ISSUE TITLE
Outdated / inconsistent build instructions

### ISSUE THREAD

**Issue by hmijail** [ethereum/go-ethereum#26344]
#### System information

OS & Version: OSX 13.0.1

#### Expected behaviour
Follow instructions in README.md to build geth. End up with a runnable binary.

#### Actual behaviour
The README.md sends me to https://geth.ethereum.org/docs/install-and-build/installing-geth, which tells me to use `go get`, which was deprecated and retired some time ago. Simply substituting for `go install` doesn't work.

In my case, running `make geth` worked OK - no idea of what were the prerequisites nor how they were satisfied.

**Comment by MariusVanDerWijden** [comment]
@jmcook1186 Could you take a look at this? 
https://go.dev/doc/go-get-install-deprecation

**Comment by jmcook1186** [comment]
thanks for raising this - you are right - `go get` is no longer used to download and build packages, only update them. 

New instructions provided in PR #26443.

I think the reason `make` worked for you but `go install` didn't is probably that you passed the path `github/ethereum/go-ethereum` to `go install` which downloaded the project to your `GOPATH` but failed to build anything because `go-ethereum` is not a main package. The makefile is there though, so you can build yourself using `make`, but `go install` needs pointing to the main packages: `cmd/geth`, `cmd/clef` etc.

cc @MariusVanDerWijden

**Comment by jmcook1186** [comment]
Closing now https://github.com/ethereum/go-ethereum/pull/26443 is merged
