### ISSUE TITLE
Feature request: --authrpc.api flag

### ISSUE THREAD

**Issue by chappjc** [ethereum/go-ethereum#26406]
On the authenticated endpoint (`authrpc`) are there certain modules that will always be provided (beyond the `engine` api), and can an `--authrpc.api=...` config option be added that allows enabling certain modules the user requires?

From https://github.com/ethereum/execution-apis/blob/main/src/engine/authentication.md, it appears that only the `engine` module/namespace is required on the authenticated interface.  `geth` defines `DefaultAuthModules = []string{"eth", "engine"}`, and uses that only.  Presently the modules listed by `--http.api=...` or `--ws.api=...` apply only to those interfaces.

A related question: is it ill-advised to use the `authrpc` interface with applications other than a consensus client?  I understand from the markdown spec linked above that the _motivation_ for the authenticated API was the `engine` API, but is it alright to be using it for other purposes where we'd like authentication.

**Comment by karalabe** [comment]
I would probably say it's ill advised to use the authrpc for anything else since it's a shared secret (one key for all). If you wanted to use some form of authentication, it might make more sense to have app specific keys that you can revoke / change without impacting other users of the API. That however goes towards a more complex auth infra and I'd say to look for a reverse proxy supporting it vs. hoping Geth will ship enough features for it.

**Comment by chappjc** [comment]
Thanks for the perspective.  I guess I mean not for a shared RPC application, but just one user and their own geth.  I suppose in that case it would be "what's the point of authentication then?" and admittedly the use case isn't strong, but the JWT does prevent the browser based abuse described in the second bullet of [api spec doc](https://github.com/ethereum/execution-apis/blob/main/src/engine/authentication.md).

I suspect for the application I'm working on, we'll have it use the tried and true http/ws interfaces and not the authrpc one because of the module availability ambiguity.  If geth needs to be on a separate machine from the app, both transport encryption and authentication are solvable with external tools like vpns and ssh tunnels.

Depending on the intended use cases for `authrpc` beyond consensus clients (if any), it would still potentially be nice to have a `--authrpc.api=...` switch instead of just the two default api modules that limit the interface's usefulness.

**Comment by holiman** [comment]
I think authrpc is not the right tool for the job. And whatever we implement will fall short, once the modules have been configured, other things on a wishlist would be 

- Ability to have per-user tokens, 
- Ability to have SSL encryption, 
- Ability to configure cors, vhosts, 
- Abilty to use sesisons (cookies) instead of jwt
