### ISSUE TITLE
Etherscan contract interface does not check for authentication, Large number of admin functions callable by public, XSS vulnerability in etherscan.

### ISSUE THREAD

**Issue by amritabithi** [ethereum/go-ethereum#26434]
#### Expected behaviour
- Many functions across all contracts are publicly callable that are clearly only intended for admins of the contract to use, it is as though there is no authentication happening in most contracts for some contract function calls whatsoever.
- The 'Write Contract' interface should prompt for authentication to make clicking the writable functions more difficult.
- The form processing done on input from text boxes on the smart contract interface screens of "Read Contract" / "Write Contract" should filter special characters when receiving input, at least for double quotes and their various representations in hex, decimal, unicode, html entities, escaped JavaScript, etc.  Code can currently be injected into function calls by escaping the double quotes character and at a minimum cause exceptions as a method of burning gas on purpose ( not all gas is reverted upon certain exceptions).

#### Actual behaviour
The public can manipulate some of the top contracts, potential for data corruption via XSS on etherscan, writeable panel of contract interface issues network requests on button clicks even if user is not logged in.  ( No error message or success message is displayed, but the request is sent and received and processed by the server when the button is pressed. )
Some contracts that I was able to look at on goerli had nearly every writable function callable anonymously by the public without doing a proper transaction or requiring coins to issue.

#### Steps to reproduce the behaviour
View a contract on testnet like this one, go to "Write Contract" and enter zeros into each field, hit submit, and you have written to the contract without spending coins. - https://goerli.etherscan.io/address/0x8ae7063d03213d4d90103c16f048b3f64de2d4d0#code

I have been trying to submit and get attention to these problems for some time now, to both an almost comical and embarassing degree, and after being completely ignored and seeing as this is being obviously abused I decided it better to post here so that people are made aware of the situation sooner than later.  I had reported this to solidity but have not heard back anything from them and in my opinion it is too late to siliently roll out a fix.

**Comment by karalabe** [comment]
Hey there,

  The are a number of issues with your report:

- First up, this is not Etherscan's repos, so it's a bit misplace. But I understand you're trying to raise awareness. Still.
- Contracts on the Ethereum network are all public and anything Etherscan can call, so can anyone directly via a transaction. Etherscan adding any authentication is irrelevant, because that's just one UI out of many to access contracts.
- I wouldn't agree with your evaluation that many top contracts are publicly writable. All of them are restricted within the contracts deployed on Ethereum, that's where the authorization happens, not on the UI level. If you were to find any case where a top contract can be abused, the bounties paid by most teams are in the millions (so def go for it).
- Writing a contract via etherscan is not free. You need an Ethereum account that can "sign" the transaction, meaning that whatever signs it will bear the costs. Etherscan won't bear the cost for you.
- Side note, on testnets, I'd assume there are many many many contracts where people just play around with things, so that's not really the best baseline to say how many contracts are problematic. Those contracts are mostly test / play things that are works in progress with possibly many problems. The interesting ones are the mainnet ones.
- Data sanitization is again not really the taks of Etherscan. They should submit whatever data they get to the contracts, that's the user's intent. Of course, if they display any data *out of* a contract they should ensure there's no XSS and similar vector, but that's on the read/display side, not when submitting.

All in all everything seems to work as intended. Perhaps you're missing a few insights on how exactly the smart contracts work, one thing that could help you understand the ecosystem a bit better is if you did just a couple started tutorials on solidity and contract dev. That would allow you to see how contracts do authorization, what is callable/not, etc.
