### ISSUE TITLE
[website] Investigate why Dev builds are not loading on /downloads besides Windows

### ISSUE THREAD

**Issue by nhsz** [ethereum/go-ethereum#26476]
Investigate why dev builds (except for Windows) are not being loaded on `/downloads`

**Comment by holiman** [comment]
The problem here is that the download, with the URL
```
export const ALL_LINUX_GETH_RELEASES_URL =
  'https://gethstore.blob.core.windows.net/builds?restype=container&comp=list&prefix=geth-linux';
```
Downloads about 1M of data, 

https://learn.microsoft.com/en-us/rest/api/storageservices/list-blobs?tabs=azure-ad

> Optional. Specifies the maximum number of blobs to return, including all BlobPrefix elements. If the request doesn't specify maxresults, or specifies a value greater than 5,000, the server will return up to 5,000 items. If there are additional results to return, the service returns a continuation token in the NextMarker response element. In certain cases, the service might return fewer results than specified by maxresults, and also return a continuation token.

I think the response fills up those 5K items. The first item has modifed-date `Wed, 03 Mar 2021 17:17:32 GMT`, and the last item has modified date `Fri, 06 Dec 2019 10:58:19 GMT`.  

I still don't know why they are not shown, though -- I suspected that there was some filter somewhere, which filtered out these releases due to being too old, but I don't see any such filter. 
Anyway, I suspect the fetch needs to be done in several steps, to fetch _all_ releases, using the `marker` to get the next page.

**Comment by holiman** [comment]
See https://github.com/ethereum/go-ethereum/blob/gh-pages/downloads.html#L268 -- how we previously iterated through the full result-set

**Comment by soulpilot** [comment]
any one found a way to download latest unstable geth updates !

**Comment by holiman** [comment]
Well, dev builds are now showing for Linux + Windows, for some reason, but not MacOS. (Not for android/iphone either, but that may legitimately be that we fail to build them)

**Comment by minimalsm** [comment]
Blocked, not something web dev team can solve. Waiting on this being investigated.

**Comment by nhsz** [comment]
Seems dev builds for WIndows, Linux & MacOS are being displayed correctly now, was blob data on Azure fixed maybe? (we didn't make any change on the fetching data)

**Comment by holiman** [comment]
Yup, it vörks
