### ISSUE TITLE
Unclean shutdown throws geth 4-5 days behind

### ISSUE THREAD

**Issue by pokrovskyy** [ethereum/go-ethereum#26493]
#### System information

Geth
Version: 1.10.19-stable
Architecture: amd64
Go Version: go1.18.4
Operating System: linux (CentOS 9)

#### Actual behaviour
First off, I am using a custom modified geth, however I tend to think the issue is more global. So anytime my geth gets killed for whatever reason (eg. by OOM killer etc.), it complains on head state missing (understandably) and starts 4 to 5 days back (given it's been running for at least this amount of time)

#### Expected behaviour
geth should better maintain state so that unclean shutdown does not throw it back so far (it takes considerable amount of time to re-sync and get it back to speed)

#### Steps to reproduce the behaviour
Have geth running for >4 days. Then SIGKILL it eg. `kill -9 <pid>` and try starting

Note `age=4d4h41m` in the log excerpt:
```
INFO [01-14|10:40:00.197] Forkchoice requested sync to new head    number=16,404,503 hash=b3ae17..6057e9
INFO [01-14|10:40:05.654] Imported new chain segment               blocks=12    txs=1472      mgas=186.814 elapsed=8.827s    mgasps=21.162 number=16,374,464 hash=00d3ea..1e6ddc age=4d4h41m  dirty=1022.00MiB
INFO [01-14|10:40:12.003] Forkchoice requested sync to new head    number=16,404,504 hash=862adc..e78b9d
INFO [01-14|10:40:16.250] Imported new chain segment               blocks=16    txs=2272      mgas=247.983 elapsed=10.596s   mgasps=23.402 number=16,374,480 hash=553fb6..0ec4c6 age=4d4h38m  dirty=1022.56MiB
INFO [01-14|10:40:24.492] Imported new chain segment               blocks=13    txs=1563      mgas=192.997 elapsed=8.241s    mgasps=23.418 number=16,374,493 hash=a54a08..37d5b4 age=4d4h36m  dirty=1022.70MiB
```

**Comment by rjl493456442** [comment]
It's expected behavior. 

Geth will maintain dirty states in memory in order to perform in-memory garbage collection algorithm. 
This GC mechanism is vital to reduce the data written into disk.

By default, Geth will save the state that needs to be executed for one hour in memory, so state gets
rewound the past in case of unclean shutdown happens.

**Comment by holiman** [comment]
It's unfortunate, but expected. Try to alway shut down geth gracefully (giving it up to 2 minutes)

**Comment by XiaoHuiHui233** [comment]
> It's expected behavior.
> 
> Geth will maintain dirty states in memory in order to perform in-memory garbage collection algorithm. This GC mechanism is vital to reduce the data written into disk.
> 
> By default, Geth will save the state that needs to be executed for one hour in memory, so state gets rewound the past in case of unclean shutdown happens.

@rjl493456442 Sorry to bother you with this question. I ran into the same problem as this issue. My Geth shut down unexpectedly for 15 minutes due to OOM. After I reboot, it starts healing from the state that was at least two days ago.

I can understand that Geth handles dirty data in memory for the speed. But it caches so much data that the time from unexpected shutdown to restart of geth is much less than the time from data loss. You mentioned one hour, can I comprehend the meaning in this way? Because of this caching mechanism, as long as there is an unexpected shutdown, it will take at least one hour(actually it took me 4 hours to heal to a synced state) to restart.

If so, is there any way to reduce the time of caching in memory to make this recovery time can be reduced, or reduce the probability of OOM occurrence? Thank you very much.

**Comment by srounce** [comment]
> It's unfortunate, but expected. Try to alway shut down geth gracefully (giving it up to 2 minutes)

Currently giving geth up to 10min to shutdown after initial SIGTERM and it does indeed close before the timeout, however I'm still seeing it jump approximately 2 days behind. So is there an issue with the shutdown logic of geth itself?
