### ISSUE TITLE
How can I get the internaltransaction(trace) besides using debug_tracetransaction?

### ISSUE THREAD

**Issue by shiziwen** [ethereum/go-ethereum#26567]
Hi, how can I get the internaltransaction besides using debug_tracetransaction?

Till now, I use ```debug_traceTransaction  params=[tx_id, {'tracer': 'callTracer', 'timeout': '20s'}] ``` to get the internaltransactions. But using this way will cost a lot of resources and time. 

Is there any better to get the internaltransaction?

**Comment by rjl493456442** [comment]
@s1na I am wondering if it makes sense to have a specific tracer to capture the "ether transfer"(we don't have it now)?

**Comment by holiman** [comment]
> besides using debug_tracetransaction?

You can't, afaik. 

> But using this way will cost a lot of resources and time.

Yeah, the thing is, there is _no way_ to obtain internal transactions cheaply. It is an intrinsically non-trivial problem, since geth does not store any such metadata about transactions - so each transaction must be (re-)executed in order to see what internal transactions are made. 


> a specific tracer to capture the "ether transfer"(we don't have it now)?

I think that would be more or less very similar to the existing callTracer? Anyway, I think such a tracer would only solve ~60% of the usecases, since most people are also interested in token/nft transfers, not only ether.
