### ISSUE TITLE
rebuilding stateDb without a database 

### ISSUE THREAD

**Issue by maurodelazeri** [ethereum/go-ethereum#26666]
Is there any way to rebuild the state of the EVM with`debug_getBlockRlp` and `debug_dumpBlock` ? I would like to run traces against a state of the EVM at a given block without running any sort of archive node

**Comment by s1na** [comment]
Short answer is no. In exceptional cases in which the block you want to trace is close to the head of the chain, or was mined after your node was synced you might be able to trace it by giving an appropriate `reexec` parameter. See the [docs](https://geth.ethereum.org/docs/developers/evm-tracing) for more info.

I'm not sure that answers your question. The title of your issue is a bit confusing. Anyhow feel free to re-open the issue if you have further questions.
