### ISSUE TITLE
Are you working on online (as opposed to 'offline') pruning?

### ISSUE THREAD

**Issue by lurais** [ethereum/go-ethereum#26673]
hello, Are you working on online (as opposed to 'offline') pruning? is that completed now ? where is the discussion about the way you take?

**Comment by holiman** [comment]
We already have online in-memory-pruning, which obviously is imperfect since it does not have access to all state, and never prunes stuff written to disk. 
We also have offline disk-pruning, 
We are not working on online pruning per se, BUT, when we switch trie schema to be path-based instead of hash-based, then our disk data will only represent one single trie. So essentially it will be pruned (x)

Main PR: https://github.com/ethereum/go-ethereum/pull/25963 

x: Caveat: we will actually not always clear storage elements from self-destructed accounts, so we will not achieve perfect pruning even with this approach.

**Comment by joaocenoura** [comment]
Hi @holiman just to understand better, PBSS will then be more space efficient but node operators still need to run offline pruning? (i.e.: eventually/less often). If so, do you foresee any changes on how to perform offline pruning (this [doc](https://geth.ethereum.org/docs/fundamentals/pruning))?

For context, we're evaluating if it's worth automate the pruning process. But if PBSS changes that, we might wait or choose not to do it.
