### ISSUE TITLE
Failed to load the private key: invalid character '"' at end of key file

### ISSUE THREAD

**Issue by zydjohnHotmail** [ethereum/go-ethereum#26766]
#### System information

Geth version: 1.11.2-stable
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: Windows
Commit hash : (if `develop`)

#### Expected behaviour
I should be able to import account from geth account new

#### Actual behaviour
Fatal: Failed to load the private key: invalid character '"' at end of key file

#### Steps to reproduce the behaviour
1) Download latest version of geth for Windows 10, and installed it
2) Run the command: 
D:\Geth>geth account new --datadir D:\Geth
INFO [02-23|20:41:03.772] Maximum peer count   ETH=50 LES=0 total=50
Your new account is locked with a password. Please give a password. Do not forget this password.
Password:
Repeat password:

Your new key was generated

Public address of the key:   0x6BD0dE2A9569e4DE77087bCF1dA39D24929552cF
Path of the secret key file: D:\Geth\keystore\UTC--2023-02-23T19-41-24.381481300Z--6bd0de2a9569e4de77087bcf1da39d24929552cf

- You can share your public address with anyone. Others need it to interact with you.
- You must NEVER share the secret key with anyone! The key controls access to your funds!
- You must BACKUP your key file! Without the key, it's impossible to access account funds!
- You must REMEMBER your password! Without the password, it's impossible to decrypt the key!

D:\Geth>geth account import D:\Geth\keystore\UTC--2023-02-23T19-41-24.381481300Z--6bd0de2a9569e4de77087bcf1da39d24929552cf
Fatal: Failed to load the private key: invalid character '"' at end of key file

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

I found similar issue on Github about 6, 7 years ago. I think  this should be fixed by now.
But for version 1.11.2-stable, the same issue appeared again.
I tried to learn how to use clef, but the documents are not easy to follow.  By the way, it seems not easy to find even I can use clef to create some accounts in Goerli network, but not easy to find how to import the accounts via geth command.
Any ideas how to fix this?

**Comment by holiman** [comment]
```
[user@work ~]$ geth account import -h
NAME:
   geth account import - Import a private key into a new account

USAGE:
   geth account import [command options] <keyFile>

DESCRIPTION:
   
       geth account import <keyfile>

   Imports an unencrypted private key from <keyfile> and creates a new account.
   Prints the address.

   The keyfile is assumed to contain an unencrypted private key in hexadecimal format.

```
IN particular: `   The keyfile is assumed to contain an unencrypted private key in hexadecimal format.`, whereas your keystore is encrypted json container. It can just be copied over to the new installation.

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply.  But I still don't quite understand what you have said.
Please give me an example on how to use geth account import to use the generated keystore file?
Thanks,

**Comment by dansinghinthedark** [comment]
Thanks for the response

 


 My problem solved already please close the case thanks 
 
 
  
   
   
    Dan Singh
    
   
  
  
   
   
  
 
  
   
  
    On Sat, Feb 25, 2023, 06:27 am zydjohnHotmail ***@***.***> wrote: 
    
   
   
    
   Hello: Thanks for your reply. But I still don't quite understand what you have said. Please give me an example on how to use geth account import to use the generated keystore file? Thanks, 
   —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***> 
   [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/ethereum/go-ethereum/issues/26766#issuecomment-1444596832",
"url": "https://github.com/ethereum/go-ethereum/issues/26766#issuecomment-1444596832",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by yuercl** [comment]
keyfile is base64string, cannot start with 0x.
`
ok: 3e4b81252ab80bacfe9ca12ae499c626b85abacec3fbf8064d7dbafb2256445a
error: 0x3e4b81252ab80bacfe9ca12ae499c626b85abacec3fbf8064d7dbafb2256445a
`
