### ISSUE TITLE
On private PoA network, stopping miner breaks transaction propagation/mining

### ISSUE THREAD

**Issue by tsirkin** [ethereum/go-ethereum#26927]
#### System information

Geth running in docker ethereum/client-go:v1.11.4
Docker container

#### Expected behaviour
Running a single miner in PoA clique private network, if a miner is stopped and a transaction created in other nodes, the transactions is not propagated or mined once it is started again.

#### Actual behaviour
The transaction should be included in blocks.

#### Steps to reproduce the behaviour
Create a simple PoA (Clique) private network consisting of a miner and a regular (not mining) node.
Both running in containers.
Initially, creating transaction on regular node is nicely mined.
Now: 
1. Stop the miner node.
2. Create a transaction on a regular node.
3. Start the miner again.
The transactions are stuck in the node indefinitely and creating new one is stuck too.
(You can see the using eth.getBlock('pending')

Interesting enough, if you leave the miner running but 
1. Disconnect the regular node from network
2. Run transaction on regular node
3. Connect the regular node back
The transaction is propagated

I pushed my config files here https://github.com/tsirkin/miner_restart_reproduce 
Can post them here if required.

In our real world scenario, we are trying to build a private network with single miner + boot node + regular nodes, all using PoA .
Stopping the miner or the boot node actually breaks any node trying to create a transaction.

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by s1na** [comment]
Clique has been deprecated in Geth. There is no plans as of now to support a PoA network. You can try setting up a local PoS network. Kurtosis allows easily spinning up such a network (specially for testing purposes) but doesn't offer the full flexibility. https://geth.ethereum.org/docs/fundamentals/kurtosis.
Otherwise you can look at https://github.com/ethpandaops/ethereum-genesis-generator to set up genesis files for your network and spinning up everything manually.
