### ISSUE TITLE
feature: add jsonrpc eth_getBlockReceipt

### ISSUE THREAD

**Issue by jsvisa** [ethereum/go-ethereum#26948]
# Rationale

We extract all transaction data for each block from Ethereum using JSON-RPC, then we iterate through all receipts and assemble the data before saving it to the database. However, I found that when retrieving transaction receipts, they are also obtained one block at a time, cached, and then metadata is added. If we have an interface that returns both the block's receipt and metadata together, it would be much more efficient for the client.

# Implementation

Do you have ideas regarding the implementation of this feature? // yes
Are you willing to implement this feature? // yes

Similar issues:

- https://github.com/ethereum/go-ethereum/issues/17044

**Comment by s1na** [comment]
It is pretty simple to do this via GraphQL if that's an option for you. You can get multiple blocks, their txes and receipt fields (logs) all in one request. I can help you write a query if you describe the data fields you need. Also see https://geth.ethereum.org/docs/interacting-with-geth/rpc/graphql.

Otherwise there's a PR for this: https://github.com/ethereum/go-ethereum/pull/25316 but the requirement is this method needs to be specc'ed and agreen on by other clients before we add it.

**Comment by jsvisa** [comment]
thanks, @s1na. And hat do other clients think about this spec?

**Comment by s1na** [comment]
@jsvisa I'm not aware if other clients have discussed this. AFAIK It needs a champion to write the spec and take it to the ACD call.

Something else you can check is `debug_getRawReceipts` which returns a list of encoded receipts.

**Comment by jsvisa** [comment]
Thanks, @s1na Yeah, I see, but the raw receipts are hex encoded. I also need the metadata. How about we add this rpc under the `debug` namespace?

**Comment by lightclient** [comment]
If you want to add a method to retrieve all the receipts in a block, I recommend opening an issue in `ethereum/execution-apis`.

**Comment by jsvisa** [comment]
> If you want to add a method to retrieve all the receipts in a block, I recommend opening an issue in `ethereum/execution-apis`.

Thanks @lightclient proposed in https://github.com/ethereum/execution-apis/issues/393

**Comment by s7v7nislands** [comment]
should close this issue? https://github.com/ethereum/go-ethereum/pull/27702 this is merged.
