### ISSUE TITLE
May the header height fall back after crash?

### ISSUE THREAD

**Issue by jongrun** [ethereum/go-ethereum#26954]
Does it mean that the header height may fall back when geth crashes and restarts? If so, a user of node service can not have the assumption that the height is ascending unless reorg. Is my understanding correct?
https://github.com/ethereum/go-ethereum/blob/e5eb32acee19cc9fca6a03b10283b7484246b15a/core/blockchain.go#L291-L317

**Comment by karalabe** [comment]
Geth stores a lot of freshly generates dirty state in RAM. We do that because a lot of it will get update or deleted in a few blocks, so it's a lot of saved disk writes. However, if we crash, then all that unwritten data will be lost. To regenerate it, we need to go back to a past point in history where we had the full state and rerun the blocks from there.

We're slowly merging a new trie data structure that will not have this aspect, that will be resilient to crashes from a head revertal perspective. Currently however, the head will go back in case of a crash for full nodes, yes.

**Comment by jongrun** [comment]
> 

Is it possible that we don't start the rpc service util all blocks between the past point and last height (before crash) finishes to rerun? If so, the head does not go back when viewed from the outside. We don't do like this because the start-up time is too long?

**Comment by jongrun** [comment]
> Geth stores a lot of freshly generates dirty state in RAM. We do that because a lot of it will get update or deleted in a few blocks, so it's a lot of saved disk writes. However, if we crash, then all that unwritten data will be lost. To regenerate it, we need to go back to a past point in history where we had the full state and rerun the blocks from there.
> 
> We're slowly merging a new trie data structure that will not have this aspect, that will be resilient to crashes from a head revertal perspective. Currently however, the head will go back in case of a crash for full nodes, yes.

@karalabe Is it possible that we don't start the rpc service util all blocks between the past point and last height (before crash) finishes to rerun? If so, the head does not go back when viewed from the outside. We don't do like this because the start-up time is too long?
