### ISSUE TITLE
graphql: can't get account's block based tranaction

### ISSUE THREAD

**Issue by jsvisa** [ethereum/go-ethereum#26984]
#### System information

Geth version: `latest`

#### Expected behaviour

I'm extracting data with GraphQL RPC:

```graphql
query TxInfo {
  blocks(from: 16857053, to: 16857053) {
    number
    hash
    timestamp
    transactions {
      hash
      from {
        address
        code
        balance
      } 
      to {
        address
        balance
      }
      value
    }
  }
}
```

What I expect to get is the `pre` or `post` transaction balance of `from/to` addresses at the time of the transaction (which requires go-ethereum to run in archive mode), but currently only gets the current balance of these addresses. This could be misleading for users who use GraphQL RPC, so we may need to explain in the documentation or not expose these state properties.

Seems we read the block info from GraphQL's context, not from the transaction's context, eg:

https://github.com/ethereum/go-ethereum/blob/0137bd69c55ca1edd42c533e543297493d3182ff/graphql/graphql.go#L374

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by s1na** [comment]
I agree the result might be surprising. You can provide an argument to `from` and `to`, e.g. `from (block: 16857053)` in which case you will get the balance at that block if your node has the state in db.

I think it will be more user-friendly if by default we provide the state at that TX. But note this will be an expensive operation because in addition to database lookups we will need to do tx processing too.

**Comment by jsvisa** [comment]
Yes, I totally agree with you, tx-related statedb not only required an archive node but also more computer resources were used, maybe we should add more documents in the [graphql's website](https://geth.ethereum.org/docs/interacting-with-geth/rpc/graphql)

**Comment by fjl** [comment]
This feature cannot be supported by go-ethereum because we don't maintain transaction-level balances after processing a block. State is kept at block granularity.

The query you posted has well-defined semantics: when you access the `balance` of an address, the result is the balance at the current block. The query does not track the 'context' of the balance query in any way.

**Comment by s1na** [comment]
I documented this behavior in #27211. Not sure we can do anything more at this moment. Closing this issue.
