### ISSUE TITLE
The question about ‘EIP150Hash’ in ‘params.ChainConfig’     

### ISSUE THREAD

**Issue by joohhnnn** [ethereum/go-ethereum#26994]
Why is the EIP150Hash (the block header hash for the EIP-150 protocol upgrade) separately marked in the ChainConfig struct? After reviewing EIP-150, it seems that there were no changes made to the hash algorithm. Instead, only gas cost adjustments were made. If the EIP150Hash field is not highlighted separately, it may cause confusion or misinterpretation for those who are only interested in the changes related to hash algorithm.

**Comment by karalabe** [comment]
I think the `ForkXYZHash` was a legacy idea where before the fork we specify the block number and after the fork we hard code the forked hash too as an extra defensive mechanism. It wasn't really used ever since forks weren't contentious and for all the various testnets and private network it was just a PITA to keep setting. Should really just drop that field altogether.
