### ISSUE TITLE
Shanghai update problem? ### BAD BLOCK ### Block: 17034870 (0x57f77052f67cdbdb14987b46d3a2d6f001dee0e974cb21da7f59c6dea4ad39c7)

### ISSUE THREAD

**Issue by webhype** [ethereum/go-ethereum#27091]
#### System information

Geth version: 1.11.5-stable-a38f4108
CL client & version: Lighthouse v3.1.0-aa022f4
OS & Version: Ubuntu 22.04

#### Expected behaviour

That the node continue syncing past block 17034869

#### Actual behaviour

Stuck at 17034869, calls 17034870 a "bad block":
```
ERROR[04-13|00:38:18.849] 
########## BAD BLOCK #########
Block: 17034870 (0x57f77052f67cdbdb14987b46d3a2d6f001dee0e974cb21da7f59c6dea4ad39c7)
Error: missing withdrawalsHash
Platform: geth (devel) go1.20.2 amd64 linux
VCS: a38f4108-20230321
Chain config: &params.ChainConfig{ChainID:1, HomesteadBlock:1150000, DAOForkBlock:1920000, DAOForkSupport:true, EIP150Block:2463000, EIP150Hash:0x2086799aeebeae135c246c65021c82b4e15a2c451340993aacfd2751886514f0, EIP155Block:2675000, EIP158Block:2675000, ByzantiumBlock:4370000, ConstantinopleBlock:7280000, PetersburgBlock:7280000, IstanbulBlock:9069000, MuirGlacierBlock:9200000, BerlinBlock:12244000, LondonBlock:12965000, ArrowGlacierBlock:13773000, GrayGlacierBlock:15050000, MergeNetsplitBlock:<nil>, ShanghaiTime:(*uint64)(0xc0000421f8), CancunTime:(*uint64)(nil), PragueTime:(*uint64)(nil), TerminalTotalDifficulty:58750000000000000000000, TerminalTotalDifficultyPassed:true, Ethash:(*params.EthashConfig)(0x2b77940), Clique:(*params.CliqueConfig)(nil)}
Receipts: 
##############################      
 
WARN [04-13|00:38:18.849] NewPayloadV1: inserting block failed     error="missing withdrawalsHash"
```

#### Steps to reproduce the behaviour

geth has been running fine / didn't touch anything

**Comment by portlandiator** [comment]
Getting the same bad block problem running Geth 1.11.5 on Ubuntu with the latest version of Lighthouse (4.0.1).

**Comment by louiswilbrink** [comment]
Got this as well.  Upgraded both Geth (1.11.5-stable-a38f4108) and Lighthouse (v4.0.1-a53830f) this afternoon ahead of Shapella.

**Comment by dankao** [comment]
Same error. Built from source.

```
Geth
Version: 1.11.5-stable
Architecture: amd64
Go Version: go1.19.1
Operating System: linux
```

**Comment by webhype** [comment]
I noticed my Lighthouse was outdated (3.11 or so). Upgraded the binary to 4.0.1 (see why at https://github.com/sigp/lighthouse/releases/ ), restarted both geth and lighthouse and it became unstuck for me. I will leave this issue open though because others seem to see "my" error even with Lighthouse 4.0.1.

**Comment by rjl493456442** [comment]
It's because consensus client(perhaps lighthouse specific) sends the `NewPayloadV1` event incorrectly. It should use `NewPayloadV2` instead. Please report this issue to lighthouse repo.

**Comment by louiswilbrink** [comment]
I have no idea why, but after my 13th restart, attestations went green again.

I didn't upgrade or prune or anything.  12 restarts would always get `BAD BLOCK`, but then somehow it started working on the last restart.  So that would indicate that `geth` was working, but that the data was indeed bad...

**Comment by portlandiator** [comment]
My issue resolved - turns out that in fact I was running an older version of Lighthouse.

**Comment by Progy46** [comment]
I can see it's written in Geth and it seems to be having issues with syncing past block 17034869. 

From the error message you provided, it looks like the node is stuck at block 17034869 and is unable to proceed further due to a missing withdrawalsHash error. This could be due to a number of reasons, such as network connectivity issues or issues with the blockchain itself.

To fix this issue, you can try resetting your Geth node by deleting the chaindata folder and resyncing from scratch. Alternatively, you can try using a different client such as OpenEthereum or Parity to see if that resolves the issue. 

If resetting your Geth node and using a different client does not resolve the issue, you can try the following alternative solutions:

1. Check your network connectivity: Ensure that your internet connection is stable and that your firewall is not blocking any incoming or outgoing connections.

2. Increase the Geth cache size: You can try increasing the cache size of your Geth node by adding the --cache flag when starting the node. This will help improve the node's performance and may help it sync past the problematic block.

3. Use a different sync mode: You can try using a different sync mode such as fast or light sync, which may help the node sync past the problematic block.

4. Wait for the blockchain to resolve the issue: Sometimes, blockchain issues can resolve themselves over time. You can try waiting for a few hours or days to see if the issue resolves itself.
You can try:

- Update your Geth version: Make sure you are using the latest version of Geth, as newer versions may have bug fixes or improvements that can help with syncing issues.

-Use a different network: If the issue persists, you can try connecting to a different Ethereum network, such as a testnet, to see if the issue is specific to the network you are currently using.

-Use a different machine: If none of the above solutions work, you can try running the Geth node on a different machine to see if the issue is specific to your current machine.

- Contact Ethereum support: If none of the above solutions work, you can contact Ethereum support for further assistance. They may be able to provide additional insights or solutions to help you resolve the issue.


As a responsible coder, I would advise you to proceed with caution and ensure that any modifications you make are safe and ethical.

**Comment by ko0f** [comment]
What is this, ChatGPT answer?! 

Resyncing the node from scratch isn't a viable option, it'll take a week.

Other suggestions seem generic and unrelated.

**Comment by holiman** [comment]
@Progy46 please stop "helping". This chatgpt-nonsense spamming our tickets is not helpful at all.

**Comment by ko0f** [comment]
Not sure if that's the issue, I was running an old version of Prysm.

**Comment by holiman** [comment]
Apparently this is fixed for op, and at least some of the other people who've chimed in. I'll close this, assuming it's all related to older versions of lighthouse or geth. 
Please open a new ticket if it remains
