### ISSUE TITLE
Some thoughts on opSload and dynamic type array slot calculation.

### ISSUE THREAD

**Issue by joohhnnn** [ethereum/go-ethereum#27115]
### Background: 
I have been pondering why Ethereum has an OPCODE like SELFDESTRUCT to clear the entire storage, but no OPCODE to copy the complete storage from a specified address to a new contract during deployment. After discussing with @jsvisa , we concluded that since slots are calculated based on the contract address, even if the storage is copied, it cannot be used due to the slot calculation rules. This has led me to think more deeply about the issue.
### question：
1. Why doesn't SLOAD have a specified account (contract) input? Currently, it is impossible to use any OPCODE to access data on a specific slot of another account during EVM runtime. Perhaps we can add an input parameter to SLOAD to achieve this, or introduce a brand new opcode.
2. Ethereum may adopt Verkle trees in the future. When calculating the storage location for dynamic data types, the contract address is involved. My understanding is that this design was initially intended to prevent hash collisions and enhance security (this is just my personal speculation; there may be deeper reasons). However, considering the development timeline for Verkle trees, it is unlikely that hash collisions could be caused by computational power. Using a fixed value instead of the contract address to participate in slot calculations could not only optimize performance but also facilitate future expansion (e.g., replicating the entire storage for data migration or adding new SLOAD functionality mentioned above). Keeping forked code slots consistent would be beneficial for the development of fork-based derivatives, aggregators, etc., such as those seen with Uniswap.

**Comment by s1na** [comment]
What you raise here is not directly related to go-ethereum. They are questions about the protocol and would be best discussed on Eth R&D channels or ethresear.ch.

And while I'm not the best person to answer these questions I'll take a stab at writing a short comment:

- As for SCOPYALL: There are plans to drop SELFDESTRUCT, in fact as of Shanghai it is already ["deprecated"](https://eips.ethereum.org/EIPS/eip-6049). The main reason why it will be dropped is because SELFDESTRUCT is the only opcode which has a variable resource requirement. Imagine having to remove a contract with many slots. The opcode you propose (say SCOPYALL) has the same issue.
- I don't understand the point of allowing a contract to directly read storage of other accounts. It can call functions of the target contract and get the data it needs. And if a storage slot is not exposed in the interface of the target contract, well maybe there's a reason for it.
- The biggest reason for a switch to verkle is in fact not avoiding hash collisions, rather allowing for stateless ethereum. I.e. being able to prove parts of state cheaply. MPT proofs are heavyweight.
- Storage slots belong to contracts. It is required to hash together the contract address with the slot to be able to distinguish between slot 0x00...1 of contract A and B.

**Comment by joohhnnn** [comment]
First of all, I apologize for not asking the question in the right place, and I appreciate your response.

1. Indeed, earlier today, I saw gballet's post about several Verkle tree migration methods. It seems that Verkle trees are coming sooner than expected, and operations based on MPT trees might not be suitable anymore.
2. During development, directly reading specific slots can save some gas compared to calling functions (by avoiding gas consumption from processes like function selector traversal). Moreover, some fields might be needed for secondary development but not exposed by the original contract through functions.
3. I agree with that.
4. I am a bit confused. When reading slots, isn't the specific contract located first? In which scenarios do we need to distinguish between different slots like 0x00...1?

**Comment by s1na** [comment]
I'll ask a clarifying question. What are you referring to by slot calculation, e.g. in this sentence: "When calculating the storage location for dynamic data types, the contract address is involved"?

**Comment by joohhnnn** [comment]
> I'll ask a clarifying question. What are you referring to by slot calculation, e.g. in this sentence: "When calculating the storage location for dynamic data types, the contract address is involved"?

ohhhhhh, No worries at all! I just get momentarily confused between the slot's position in the EVM and its position in LevelDB (contract address + MPT node hash).
Now let's focus on question two, concerning directly reading the value of a specific slot in a specific contract. Currently, many frameworks, such as Foundry, have a `getStorageAt() `function. However, sometimes during dApp development, it is necessary to access values that are not exposed through functions in runtime.

**Comment by axic** [comment]
> Why doesn't SLOAD have a specified account (contract) input? Currently, it is impossible to use any OPCODE to access data on a specific slot of another account during EVM runtime.

There's a proposal for [`EXTSLOAD`](https://eips.ethereum.org/EIPS/eip-2330), perhaps the discussion URL there is a good place for diving deeper.

**Comment by s1na** [comment]
Thanks @axic.

Closing the issue now.
