### ISSUE TITLE
bloombits: protect field access with lock to avoid possible data race

### ISSUE THREAD

**Issue by yanke-xu** [ethereum/go-ethereum#27170]
#### System information

Geth version: `V1.11.6`
OS & Version: `Ubuntu 20.04`

#### Expected behaviour
No data race

#### Actual behaviour
Data race

#### Steps to reproduce the behaviour
Manually check the related code

#### Backtrace
A data race is found by code analysis, and backtrace is described in detatil.  
`res.cached` is read/write in bloombits/scheduler.go; it is write and protected by s.lock.Lock() in func deliver(); it is read without a Lock, which is in func scheduleDeliveries() on L164.
A data race may happen when scheduleDeliveries() and other func like deliver() are called in parallel.
The fix is to protect the access to `res.cached` and save the result to a local variable.

**write on res.cached:** 
https://github.com/ethereum/go-ethereum/blob/f8aa62353666a6368fb3f1a378bd0a82d1542052/core/bloombits/scheduler.go#L177
````
    testScheduler()
->  deliver()
->  res.cached = data[i]  
````

**read on res.cached:**
https://github.com/ethereum/go-ethereum/blob/f8aa62353666a6368fb3f1a378bd0a82d1542052/core/bloombits/scheduler.go#L164
```
    testScheduler()
->  run()
->  scheduleDeliveries()
->  done <- res.cached
```

**Comment by holiman** [comment]
Before the **read on res.cached** happens, there's this select: 
```golang
			select {
			case <-quit:
				return
			case <-res.done:
			}
```
Which means that the read won't happen unless `res.done` has been closed.
The **write on res.cached** happens here: 
```golang
	for i, section := range sections {
		if res := s.responses[section]; res != nil && res.cached == nil { // Avoid non-requests and double deliveries
			res.cached = data[i]
			close(res.done)
		}
	}
```
Meaning, it sets the `res.cached`, and after that's done, it closes `res.done`, thus releasing the potential waiting reader.
So it seems to me that it's handled already. Since things like this is difficult to reason about with confidence, it would be even better if you can trigger a race via testing, and `go test -run <thetest> -race`.

**Comment by holiman** [comment]
Stale, closing

**Comment by yanke-xu** [comment]
您好，邮件我已收到，我会及时给您回复，祝好！
