### ISSUE TITLE
What do the labels on the issues mean?

### ISSUE THREAD

**Issue by adust09** [ethereum/go-ethereum#27180]
I personally cannot intuitively understand what the labels mean. For example, what does "area:, type:" mean?

If you have a page that explains these things, please let me know.

Of the current 88 labels, only todo-pr-into-docs has a description.Perhaps a description should be provided for all labels.

<img width="1143" alt="スクリーンショット 2023-04-28 1 28 22" src="https://user-images.githubusercontent.com/47593288/234928900-bff37afb-63e4-4e11-898f-87c2fc3576b1.png">

**Comment by karalabe** [comment]
Myeah, just ignore them. We had a number of people try to bring some new order to the PRs issues with their own style labels, which we used for a while and then just abandoned because it's just too annoying to keep tagging and for the 5 people who bugfix it's obvious what the code touches by just looking at it.

 Currently we rarely use tags, usually to mark something that's interesting at a specific moment for some reason (e.g. `triage` to know what to talk about on meetings, or `fork xyz` to know which PRs belong collectively to some hardfork, etc).

**Comment by adust09** [comment]
I see. Thank you very much.

I wondered if there was an unspoken rule for me, as I have recently started committing to geth.
