### ISSUE TITLE
rpc: replacement for gorilla/websocket

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#27261]
From time to time, we hit this on appveyor (primarily windows-tests)

```
panic: The handle is invalid.
goroutine 10137 [running]:
internal/poll.execIO(0xc00007b198, 0x1023ac0)
	C:/Users/appveyor/AppData/Local/geth-go-1.20.3-windows-amd64/go/src/internal/poll/fd_windows.go:201 +0x385
internal/poll.(*FD).Read(0xc00007b180, {0xc000224000, 0x400, 0x400})
	C:/Users/appveyor/AppData/Local/geth-go-1.20.3-windows-amd64/go/src/internal/poll/fd_windows.go:436 +0x2b8
net.(*netFD).Read(0xc00007b180, {0xc000224000?, 0xc0002917d6?, 0xc0002917d5?})
	C:/Users/appveyor/AppData/Local/geth-go-1.20.3-windows-amd64/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc00000a668, {0xc000224000?, 0x187d985a1e8?, 0x187b1760108?})
	C:/Users/appveyor/AppData/Local/geth-go-1.20.3-windows-amd64/go/src/net/net.go:183 +0x45
bufio.(*Reader).fill(0xc0001b6780)
	C:/Users/appveyor/AppData/Local/geth-go-1.20.3-windows-amd64/go/src/bufio/bufio.go:106 +0xff
bufio.(*Reader).Peek(0xc0001b6780, 0x2)
	C:/Users/appveyor/AppData/Local/geth-go-1.20.3-windows-amd64/go/src/bufio/bufio.go:144 +0x5d
github.com/gorilla/websocket.(*Conn).read(0xc000238000, 0xc00687a898?)
	C:/Users/appveyor/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:370 +0x2c
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc000238000)
	C:/Users/appveyor/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:798 +0x7b
github.com/gorilla/websocket.(*Conn).NextReader(0xc000238000)
	C:/Users/appveyor/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:980 +0xcc
github.com/gorilla/websocket.(*Conn).ReadJSON(0x18?, {0xf717e0, 0xc00297a5e8})
	C:/Users/appveyor/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/json.go:50 +0x27
github.com/ethereum/go-ethereum/rpc.(*jsonCodec).readBatch(0xc000067c70)
	C:/projects/go-ethereum/rpc/json.go:225 +0x4d
github.com/ethereum/go-ethereum/rpc.(*Client).read(0xc000261680, {0x10a42b0, 0xc00015a630})
	C:/projects/go-ethereum/rpc/client.go:664 +0xa2
created by github.com/ethereum/go-ethereum/rpc.(*Client).dispatch
	C:/projects/go-ethereum/rpc/client.go:588 +0x155
FAIL	github.com/ethereum/go-ethereum/rpc	12.572s
ok  	github.com/ethereum/go-ethereum/signer/core	4.988s

```
The `gorilla/websocket` package is archived, https://github.com/gorilla/ , see [here](https://github.com/gorilla#gorilla-toolkit) for more details. 

We should look into either replacing gorilla with another library, or see if we can simply swap it out for the standard library components.

**Comment by jshufro** [comment]
https://github.com/gobwas/ws seems to be quite popular- have we looked into it?

**Comment by fjl** [comment]
It's an interesting option. I think we will stick with the existing library for now, it works and there are no known bugs.

**Comment by fjl** [comment]
I closed this because the issue this applies to is very likely not an issue with the websocket library.

**Comment by tspearconquest** [comment]
While the OP's logs may not apply to the websocket library, the title of the issue is to replace gorilla. With the project being archived, you're leaving go-ethereum open to potential unknown CVEs. I vote to reopen. Ask OP to remove the logs and just make the issue relevant to replacing gorilla. Alternatively, I can open a separate issue for the same and highlight some reasons why it should be replaced simply to alleviate security risk concerns.

**Comment by fjl** [comment]
If a vulnerability is discovered in gorilla/websocket, there will be a way to fix it. The library being archived doesn't mean it will become vulnerable all of a sudden. And conversely, a library being actively maintained does not inherently make it safer. If anything, it could be argued that a codebase under active development is more likely to introduce new vulnerabilities.

**Comment by tspearconquest** [comment]
Hi,

The concern is not around the ability to fix it. It's around the ability to report it.

No issues can be opened under the gorilla project anymore. GitHub Security Advisories interacts with project issues to provide vulnerable/fixed version details, and open source vulnerability scanners like Trivy use the data from GHSA to report on CVEs.

GHSA cannot add a new security advisory to the gorilla project since the project is archived and read-only, so those vulnerability scanners won't report a CVE.

See also: https://github.com/gorilla/websocket/security/advisories/GHSA-jf24-p9p9-4rjh

And related search https://github.com/advisories?query=gorilla
