### ISSUE TITLE
rpc call eth_getBalance does not accept address 

### ISSUE THREAD

**Issue by AnsgarSchmidt** [ethereum/go-ethereum#2728]
#### System information

Geth
Version: 1.5.0-unstable
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.6.1
OS: linux
GOPATH=
GOROOT=/usr/lib/go-1.6
#### Expected behaviour

myaddress = server.eth_accounts()[0]
print server.eth_getBalance([myaddress, "latest"])
#### Actual behaviour

**jsonrpclib.jsonrpc.ProtocolError: (-32602, u'Invalid address length, expected 40 got 56 bytes')**
#### Steps to reproduce the behaviour

I try to call the eth_getBalance method from python.

import jsonrpclib
server = jsonrpclib.Server('http://<ip>:8545')
print "clientVersion: %s" % server.web3_clientVersion()
**myaddress = server.eth_accounts()[0]**
print "My address: %s" % myaddress
print "Unlock account: %s" % server.personal_unlockAccount(myaddress,"GEHEIM", 60)
print "Lock account: %s" % server.personal_lockAccount(myaddress)

results in:
clientVersion: Geth/v1.5.0-unstable/linux/go1.6.1
My address: 0x693b53714fffefdccb0ac6af2a20660892fadfca
Unlock account: True
Lock account: True

Getting the address and using this address for unlocking and locking works, but when I try to use getBalance I get this error:

**print server.eth_getBalance([myaddress, "latest"])**

**jsonrpclib.jsonrpc.ProtocolError: (-32602, u'Invalid address length, expected 40 got 56 bytes')**

Not sure if I made an error here. I tried to find examples but is seem that is the right way to call the RPC function.

**Comment by bas-vk** [comment]
According to the error message the supplied account is too long. Ethereum addresses are 160 bits long. The RPC interface uses hex encoding which makes it expect 40 bytes. According to the error message you supplied 56 byte for the address.

The same parsing logic is used for lock/unlocking accounts as for retrieving the balance. So I don't expect there to be an issue.

In the examples you give is a difference that might explain this:
```
print "Unlock account: %s" % server.personal_unlockAccount(myaddress,"GEHEIM", 60)
print server.eth_getBalance([myaddress, "latest"])
```
In the case of getBalance you pass an array, in the case of the unlock 3 parameters. Is this intentional? I expect the getBalance call to look like: `server.eth_getBalance(myaddress, "latest")`.

**Comment by fjl** [comment]
Closing because this is old and likely to be a client side issue.
