### ISSUE TITLE
evm state test runner does not produce any output

### ISSUE THREAD

**Issue by d-xo** [ethereum/go-ethereum#27326]
#### System information

Geth version: 1.11.6
OS & Version: linux

#### Expected behaviour

Running `evm statetest` on a general state test produces some output

#### Actual behaviour

No output is produced (tried with 3 different json files)

#### Steps to reproduce the behaviour

Any of the following:

```
evm --json statetest $TESTS_REPO/BlockchainTests/GeneralStateTests/Shanghai/stEIP3860-limitmeterinitcode/creationTxInitCodeSizeLimit.json
evm --json statetest $TESTS_REPO/BlockchainTests/GeneralStateTests/stArgsZeroOneBalance/smodNonConst.json
evm --json statetest $TESTS_REPO/BlockchainTests/GeneralStateTests/stBadOpcode/opc1EDiffPlaces.json
```

**Comment by holiman** [comment]
Instead of `BlockchainTests/GeneralStateTests/stArgsZeroOneBalance/smodNonConst.json`, try `GeneralStateTests/stArgsZeroOneBalance/smodNonConst.json`. The former are blockain tests which have been generated based off general state tests. The evm runner cannot do blockchain tests, but it can do general state tests (the latter)

**Comment by d-xo** [comment]
Ah got it, thanks a lot!
