### ISSUE TITLE
Spike in goroutines when CL blocked on setting new head

### ISSUE THREAD

**Issue by s1na** [ethereum/go-ethereum#27386]
When CL requests setting new head which involves processing many blocks, during this time CL will keep sending other requests which pile up as goroutines until the stuck routine is released. This shows in the charts here:

<img width="325" alt="Screenshot 2023-05-30 at 16 30 12" src="https://github.com/ethereum/go-ethereum/assets/1591639/0a0745df-a0b9-42ed-b617-5e066892bed3">
<img width="385" alt="Screenshot 2023-05-30 at 16 30 34" src="https://github.com/ethereum/go-ethereum/assets/1591639/2790a4a4-2d52-40bc-9fa3-2c2bdfd7a433">

This is where the first request gets stuck:

```
goroutine 60 [semacquire, 20 minutes]:
sync.runtime_Semacquire(0xde9fc0?)
        runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0xc015094680?)
        sync/waitgroup.go:139 +0x52
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Cancel(0xc015094680)
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:700 +0x30
github.com/ethereum/go-ethereum/eth/downloader.(*beaconBackfiller).suspend(0xc01f27e580)
        github.com/ethereum/go-ethereum/eth/downloader/beaconsync.go:74 +0xb9
github.com/ethereum/go-ethereum/eth/downloader.(*skeleton).sync.func3()
        github.com/ethereum/go-ethereum/eth/downloader/skeleton.go:370 +0x2f
github.com/ethereum/go-ethereum/eth/downloader.(*skeleton).sync(0xc00daacb60, 0xc0add9a240?)
        github.com/ethereum/go-ethereum/eth/downloader/skeleton.go:448 +0xed3
github.com/ethereum/go-ethereum/eth/downloader.(*skeleton).startup(0xc00daacb60)
        github.com/ethereum/go-ethereum/eth/downloader/skeleton.go:271 +0x211
created by github.com/ethereum/go-ethereum/eth/downloader.newSkeleton
        github.com/ethereum/go-ethereum/eth/downloader/skeleton.go:233 +0x1da
 ```
 
This is where the rest of them are locked out:

```
goroutine 155145 [semacquire, 3 minutes]:
sync.runtime_SemacquireMutex(0x0?, 0xe0?, 0x20?)
        runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc001946138)
        sync/mutex.go:171 +0x165
sync.(*Mutex).Lock(...)
        sync/mutex.go:90
github.com/ethereum/go-ethereum/eth/catalyst.(*ConsensusAPI).newPayload(_, {{0xf6, 0xc8, 0xc4, 0x45, 0x37, 0xbd, 0xc4, 0x50, 0x47, ...}, ...})
        github.com/ethereum/go-ethereum/eth/catalyst/api.go:450 +0x91
github.com/ethereum/go-ethereum/eth/catalyst.(*ConsensusAPI).NewPayloadV2(_, {{0xf6, 0xc8, 0xc4, 0x45, 0x37, 0xbd, 0xc4, 0x50, 0x47, ...}, ...})
        github.com/ethereum/go-ethereum/eth/catalyst/api.go:433 +0x178
```

**Comment by holiman** [comment]
Here are two benchmarker machines that are doing a full-sync

![Screenshot 2023-05-31 at 08-17-08 Dual Geth - Grafana](https://github.com/ethereum/go-ethereum/assets/142290/c9ffe53c-dd0b-4b09-9cad-68c497aec41d)

**Comment by holiman** [comment]
Sorry, my bad, only the yellow one is doing a full-sync, the green one is already synced (via snap). No idea what the green goroutine-spikes are all about

**Comment by karalabe** [comment]
Huh, interestingly, I thought the issue is in the downloader, but in reality it's unrelated.

If the blockchain is busy importing blocks (or compacting or whatever), then all newPayload calls will block. It's even written in the method doc :D 

```
	// 1. NewPayload( execdata-N ) is invoked from the CL. It goes all the way down to
	//      api.eth.BlockChain().InsertBlockWithoutSetHead, where it is blocked on
	//      e.g database compaction.
```

So it's not an unforseen issue, just a non-cared-about issue because I guess we didn't expect a previous chain insertion to keep the (blockchain) lock for 15 mins.

**Comment by karalabe** [comment]
Hmm, if the chain is still way behind and we're getting blocks with missing parents, we should detect that directly though the database and should not hit the chain importer at all. In that case we might get stuck on BeaconExtend. Would need a bit more stack dump to confirm.

**Comment by karalabe** [comment]
Seems the issue is quite convoluted and surfaced by a faulty beacon updater (factor round robining a batch of good and one bad beacon client).

The triggering behavior is that the beacon client feeding the head updates periodically sent an old update, causing very frequent reorgs to be triggered by the benchmarkers.

When a reorg is triggered, a previous sync cycle is cancelled. To prevent discarding a potentially 256MB of cached block data, the downloader will keep importing those blocks (and delaying the cancellation). This delay however will hang the beacon syncer that maintains the skeleton/beacon header chain from shutting down.

While that goroutine is stuck on shutdown (and before it gets a chance to restart with a new head), newPayload beaconExtend requests are not consumed. The suck beaconExtend will hold the newPayload lock, causing subsequent newPayloads to keep piling up.

---

Introducing a force interrupt in the downloader would fix things, but I'm not sure it's healthy to discard downloaded data - since a buggy consensus update (like in this case) would trigger tons of restarts and discarded data.

One potential "dirty" fix would be to detect the case when the skeleton syncer is unavailable to consume the head update due to trying to restart, and have a hard coded timeout of say 1-3s after which the call just assumes that the we're stuck on catch-up import and return SYNCING blindly.

It is a bit wonky to introduce a timeout, maybe we could do without one and just consider the skeleton syncer being offline as this specific scenario. Need to think through what the implications would be in the general runtime case.

**Comment by holiman** [comment]
Logs from bench06 (green one), first pretty soon after a drop, the second one after ~5 minutes of ramping up routines. 

[bench06.stacks.2.txt](https://github.com/ethereum/go-ethereum/files/11611796/bench06.stacks.2.txt)
[bench06.stacks.txt](https://github.com/ethereum/go-ethereum/files/11611797/bench06.stacks.txt)
