### ISSUE TITLE
I want a fix block time. and change the difficulty of a block to a fix number ,will it do that ?

### ISSUE THREAD

**Issue by yangmiok** [ethereum/go-ethereum#27454]
```
// WriteTd stores the total difficulty of a block into the database.
func WriteTd(db ethdb.KeyValueWriter, hash common.Hash, number uint64, td *big.Int) {
	data, err := rlp.EncodeToBytes(td)
	if err != nil {
		log.Crit("Failed to RLP encode block total difficulty", "err", err)
	}
	if err := db.Put(headerTDKey(100, hash), data); err != nil {
		log.Crit("Failed to store block total difficulty", "err", err)
	}
}
```

**Comment by lightclient** [comment]
You need to use `period` field in the clique config struct to have a fixed block time: https://github.com/ethereum/go-ethereum/blob/281e8cd5abaac86ed3f37f98250ff147b3c9fe62/params/config.go#L292

**Comment by yangmiok** [comment]
But I do not want the POA consensus，I want the POW to have a fixed block time

**Comment by lightclient** [comment]
Block time can't be fixed in proof-of-work, instead the follow a [poisson distribution](https://ethresear.ch/t/deep-dive-into-current-pow-difficulty-adjustment-algorithm-and-a-possible-alternative/5267). To target a different time, you would need to modify the difficulty adjustment algorithm.

Please note however, that as of geth `v1.12.0` we no longer support private proof-of-work chains.
