### ISSUE TITLE
Failure to catch-up sync after downtime

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#27482]
I am not sure if this is an issue in geth, or lighthouse, but this is a good place to start discussing, I guess. Recently, on a machine running lighthouse +geth, the geth node went down. It was down for several days, and after starting up again, it just printed out `Forkchoice requested unknown head hash=7cadd7..d467d1`. 

This message happens only via `FCU`. IT does not trigger geth to actually _do_ anything further: 
```golang
	// Check whether we have the block yet in our database or not. If not, we'll
	// need to either trigger a sync, or to reject this forkchoice update for a
	// reason.
	block := api.eth.BlockChain().GetBlockByHash(update.HeadBlockHash)
	if block == nil {
		// If this block was previously invalidated, keep rejecting it here too
		if res := api.checkInvalidAncestor(update.HeadBlockHash, update.HeadBlockHash); res != nil {
			return engine.ForkChoiceResponse{PayloadStatus: *res, PayloadID: nil}, nil
		}
		// If the head hash is unknown (was not given to us in a newPayload request),
		// we cannot resolve the header, so not much to do. This could be extended in
		// the future to resolve from the `eth` network, but it's an unexpected case
		// that should be fixed, not papered over.
		header := api.remoteBlocks.get(update.HeadBlockHash)
		if header == nil {
			log.Warn("Forkchoice requested unknown head", "hash", update.HeadBlockHash)
			return engine.STATUS_SYNCING, nil
		}
```

So, 
1. Geth & Lighthouse are in sync
2. Geth goes down
3. Geth starts up (days later)
4. Lighthouse _only_ does `FCU` calls. 

I tried getting out of this rut by wiping geth and restarting, however, it got stuck in the same place again. Only when I wiped lighthouse did it finally trigger geth to sync properly again. 

Not sure if this is expected behaviour or not, and also which client is doing something wrong here.  

cc @paulhauner

**Comment by michaelsproul** [comment]
Hey @holiman. You don't happen to still have logs from the Lighthouse node do you? Default level INFO logs would be fine, but debug logs would be even better. Lighthouse stores size-limited debug logs by default in `$datadir/beacon/logs`.

This could be related to Lighthouse's behaviour during finalized sync. We will avoid sending `newPayload` calls in this case, which allows us to get back in sync. Once we get close to the head (~2 epochs) we'll resume sending newPayload, while remaining in "optimistic sync". Lighthouse _should_ follow the chain in this state, and feed a regular stream of `newPayload` _and_ `fcU` to the EL. If we aren't doing that, then it's a bug.

**Comment by michaelsproul** [comment]
@holiman Ah, that makes sense then. It looks like Lighthouse was still doing finalized sync, in which case it won't send newPayload.

If you would like Lighthouse to send newPayload before it finishes syncing you can use the `--disable-optimistic-finalized-sync` flag. We get reports about this from other EL devs occasionally, and would be open to disabling the behaviour by default if you think that would be better.

**Comment by holiman** [comment]
> Ah, that makes sense then. It looks like Lighthouse was still doing finalized sync, in which case it won't send newPayload.

Could you please elaborate on that? Both the part "still doing" -- as in, did it not finish the initial sync before the downtime? And "finalized sync" -- as opposed to what?

**Comment by michaelsproul** [comment]
Sure.

Lighthouse has two different sync phases which use slightly different algorithms. The first is finalized sync, which kicks in when syncing long distances. Its goal is to get Lighthouse from wherever it is currently up to the finalized checkpoint reported by peers. Putting aside the issue of malicious peers which might misrepresent their finalized checkpoint, this sync phase will run until Lighthouse is about 2 epochs behind the canonical head. The 2nd sync phase occurs once Lighthouse has caught up to the finalized checkpoint, and is called "head sync". It tolerates peers which report diverging chains and will follow the ones that seem most promising until it reaches the head.

By default, Lighthouse will only send `newPayload` to the EL when it is in the head sync phase. During finalized sync, it will send `fcU` occasionally, but no `newPayload`. When it changes from one sync phase to the other it will log `INFO Sync state updated` with the old and new phases.

What I think happened in your case was:

1. Geth goes down, and is completely offline. It doesn't respond to any calls on the engine port.
2. Lighthouse stops being able to make progress because Geth isn't responding, and sits waiting for Geth to come back. That's what the `INFO Syncing est_time: --, distance: 9878 slots (1 day 8 hrs), peers: 88, service: slot_notifier` logs show. Lighthouse does not currently attempt to sync (even optimistically) if the execution node is completely offline (or returning errors). Optimistic sync can only happen when the EL is online and responding with SYNCING/ACCEPTED to `fcU`. Arguably this is a bit strange, because we aren't expecting the EL to actually _do_ much during finalized sync, i.e. we are checking the block roots in Lighthouse rather than sending them to the EL for the block root check & SYNCING response.
3. Once Geth comes back online, Lighthouse resumes trying to sync. It's a long way behind by now, so it uses the finalized sync algorithm which doesn't send `newPayload` to Geth. Based on the logs, it was _still_ attempting finalized sync when it logged: `INFO Syncing est_time: 40 mins, speed: 9.33 slots/sec, distance: 22591 slots (3 days 3 hrs), peers: 88`. It's 3 days behind the head and estimating that it needs another 40 minutes to catch up.

If you waited for Lighthouse to finish finalized sync (distance ~= 2 epochs), then it would transition to head sync, at which point it would start sending `newPayload` to Geth.

In terms of tweaking the behaviour here there are two things we could try to optimise:

1. First is the long wait for Lighthouse to finish finalized sync and send `newPayload`. This can be mitigated by using `--disable-optimistic-finalized-sync`, which was previously the default. With that flag, Lighthouse would send `newPayload` as soon as Geth came back (start of step 3).
2. The other thing that would be nice to avoid is the long downtime in step (2). To do this would require "going the other way" in terms of allowing Lighthouse to do more without Geth. Lighthouse _could_ continue verifying EL block hashes and syncing optimistically while Geth is offline, meaning that it would be synced to the head (and sending `newPayload`) by the time Geth came back online. The reason we don't do this currently is that it's somewhat dangerous for Lighthouse to go into optimistic mode when the execution node is erroring or not responding. If an attacker could publish a block that caused a large portion of ELs to error, and CLs went into optimistic sync, then a _large portion of validators would stop attesting and producing blocks_. We refer to this kind of block as a "bomb block" (@paulhauner's term). There might be room however for Lighthouse t sync optimistically on its own during _finalized chain sync_. This would avoid the issues of bomb blocks causing liveness faults, while also allowing a Lighthouse node with an offline/erroring EL to at least keep up with the finalized checkpoint (so it is at most 2 epochs behind by the time the EL comes back).

Sorry for the long response! Curious to hear what you think of this design space and what you think the right trade-offs might be.

**Comment by holiman** [comment]
Thanks for the info!

Some notes

>     It's 3 days behind the head and estimating that it needs another 40 minutes to catch up.

> If you waited for Lighthouse to finish finalized sync (distance ~= 2 epochs), then it would transition to head sync, at which point it would start sending newPayload to Geth.

So, by the sound of it, had I waited out those 40 minutes, thing might have gotten ok again. However, here's a snippet roughly `23 minutes` later -- the estimation goes `21 min` -> `1h 23 min` -> `2h 47 min`: 

```
Jun 15 21:00:05 crush beacon Jun 15 18:59:53.000 INFO Syncing est_time: 24 mins, speed: 9.34 slots/sec, distance: 13745 slots (1 day 21 hrs), peers: 88, service: slot_notifier
Jun 15 21:00:05 crush beacon Jun 15 18:59:53.000 WARN Syncing deposit contract block cache est_blocks_remaining: 141792, service: slot_notifier
Jun 15 21:00:05 crush beacon Jun 15 18:59:59.081 WARN Error processing HTTP API request method: POST, path: /eth/v1/validator/prepare_beacon_proposer, status: 503 Service Unavailable, elapsed: 101.851µs
Jun 15 21:00:05 crush beacon Jun 15 19:00:05.000 INFO Syncing est_time: 24 mins, speed: 9.33 slots/sec, distance: 13682 slots (1 day 21 hrs), peers: 88, service: slot_notifier
Jun 15 21:00:05 crush beacon Jun 15 19:00:05.000 WARN Syncing deposit contract block cache est_blocks_remaining: 141792, service: slot_notifier
Jun 15 21:02:05 crush beacon Jun 15 19:01:05.000 INFO Syncing est_time: 1 hr 23 mins, speed: 2.67 slots/sec, distance: 13431 slots (1 day 20 hrs), peers: 88, service: slot_notifier
Jun 15 21:02:05 crush beacon Jun 15 19:01:05.000 WARN Syncing deposit contract block cache est_blocks_remaining: 141792, service: slot_notifier
Jun 15 21:02:05 crush beacon Jun 15 19:01:11.081 WARN Error processing HTTP API request method: POST, path: /eth/v1/validator/prepare_beacon_proposer, status: 503 Service Unavailable, elapsed: 97.363µs
Jun 15 21:02:05 crush beacon Jun 15 19:01:17.000 INFO Syncing est_time: 2 hrs 47 mins, speed: 1.33 slots/sec, distance: 13368 slots (1 day 20 hrs), peers: 88, service: slot_notifier
Jun 15 21:02:05 crush beacon Jun 15 19:01:17.000 WARN Syncing deposit contract block cache est_blocks_remaining: 141792, service: slot_notifier
```
But I assume that's just the inherent fluctuations of time-estimation; and that means that I could have waited it out, and it would have sorted itself out, eventually. And in that case, I don't see this as a bug anymore, but just "it works as expected (I just didn't give it enough time)". 


---- 

Also, interesting thoughts about the bomb block. 

> If an attacker could publish a block that caused a large portion of ELs to error, and CLs went into optimistic sync, then a large portion of validators would stop attesting and producing blocks. 

So what is the alternative? What is the current macro-network-behaviour on "a large portion of EL drop-offs"?

**Comment by aa21** [comment]
Thanks for this report @holiman  and the detailed explanation @michaelsproul.

**Comment by holiman** [comment]
Thanks for all the info! Closing this (but bookmarking it for future refs)
