### ISSUE TITLE
core/rawdb/freezer: table size is inaccurate if elements were removed from the tail

### ISSUE THREAD

**Issue by rjl493456442** [ethereum/go-ethereum#27483]
Freezer table can support both tail and head deletion. Tail deletion is a bit special, it
will hide the removed items and keep them in the file. The file will only be dropped if
all elements in this file are hidden. (we call it as lazy-deletion).

However, the reported size doesn't respect the tail deletion. The hidden items are
still counted for overall table size. Although these elements are indeed live in the 
file system, but we might need another API to report the size of live elements to
avoid some confusions.

**Comment by joaovwfreire** [comment]
Can I try it? =)

**Comment by shyam-patel-kira** [comment]
Is there any update on this? I'd like to try

**Comment by abhinav700** [comment]
@rjl493456442 Can you assign this issue to me. I would love to work on it.

**Comment by theblueskies** [comment]
@MariusVanDerWijden  Is this still up for grabs? can I get it?

**Comment by Sh0g0-1758** [comment]
I am also highly interested in contributing to geth. Can I take this one :)

**Comment by bnovil** [comment]
Does anyone still work on this?

**Comment by makinje16** [comment]
👋🏿 Just looking to present a different view and to get some clarification since I've started to read through the `rawdb` code.

From the database perspective, the table size is accurate. The contract when using the freezer is that data is lazily deleted when `freezerTables` are [defined](https://github.com/ethereum/go-ethereum/blob/f265cc24b4b17b55b468b315303a3a599fc01d81/core/rawdb/freezer_table.go#L94) which is also seen on the client side when looking at the `AncientWriter` [interface](https://github.com/ethereum/go-ethereum/blob/f265cc24b4b17b55b468b315303a3a599fc01d81/ethdb/database.go#L119C12-L119C12).

I don't think its a good idea to change this contract because by "deleting" data in the ancient we aren't guaranteeing the data is gone. We guarantee we won't visit it again. All for the use case if we need but I agree it may want to live somewhere else or under a different method/API/etc.

**Comment by wangyifan** [comment]
@rjl493456442 @holiman Hi, I just create a PR for this issue. This is my first PR for geth. Let me know if I'm missing something. Thanks!

**Comment by rjl493456442** [comment]
Completed.
