### ISSUE TITLE
You cannot set the miner.gasPrice to 0 or the txpool.pricelimit to 0 in private chains

### ISSUE THREAD

**Issue by bradbrown-gtmn** [ethereum/go-ethereum#27517]
You cannot set the miner.gasPrice to 0, if you try, you'll see a warning in the logs: 

```
WARN [12-01|11:51:18.506] Sanitizing invalid miner gas price       provided=0    updated=1,000,000,000
```

Geth explicitly does not allow this because accepting 0 priced transactions would mean that you also accept/pool them from the network and propagate them, which is essentially a very potent DoS vector (I can send arbitrary junk tx from arbitrary non-existing account since there's no cost).

_Originally posted by @karalabe in https://github.com/ethereum/go-ethereum/issues/26285#issuecomment-1333501611_
            
It makes no sense to limit the functionality of geth for developers using private chains because of a potential "attack vector" possibly experienced by geth nodes attached to real networks. You cannot send arbitrary junk tx to my private chain, since it is private and my ports aren't open. Please allow developers to continue to choose to use zero gas transactions in their private chains.

**Comment by karalabe** [comment]
You can't really have true zero gas price post 1559 though. The basefee must always be burnt.

> It makes no sense to limit the functionality of geth for developers using private chains

Do note, that Geth is an implementation of Ethereum. There never was nor ever will be a promise to support anything else. Our private network support is meant to run testnets for local testing, it is not meant to run alternative production L1s with different rule sets.

You are welcome to use our code - it's open source after all - but wherever you diverge from Ethereum mainnet behavior, it's up to you to support your fork.

**Comment by GTMN-bradbrown** [comment]
"Our private network support is meant to run testnets for local testing, it is not meant to run alternative production L1s with different rule sets."

I'm trying to run a testnet for local testing, using transactions with 0 gas costs so that I don't have to fiddle with and set up automation scripts for allocating gas money. Five months ago, I was able to do this just fine. That convenience let me just get right into testing the functionality of Ethereum smart contracts, to be deployed on the Ethereum mainnet. I am not "running alternative production L1s with different rulesets", I am trying to test smart contracts to be deployed on the mainnet.

It's one thing that such a feature should be wanted simply as a quality of life feature for developers, it's another thing that it already existed and it was removed, and there seems to be no adequate reasoning for removing it from the perspective of a developer testing their smart contracts prior to mainnet deployment.

**Comment by karalabe** [comment]
But how did you run 0 gas prices with London enabled (basefee)?

**Comment by GTMN-bradbrown** [comment]
I was able to do it without London enabled, genesis looks like

      ..., "homesteadBlock": 0,
      "eip150Block": 0,
      "eip155Block": 0,
      "eip158Block": 0,
      "byzantiumBlock": 0,
      "constantinopleBlock": 0,
      "petersburgBlock": 0,
      "istanbulBlock": 0,
      "berlinBlock": 0, ...
      
This setup no longer works. There are more comments about it in https://github.com/ethereum/go-ethereum/issues/26285#issuecomment-1333501611, but they are all unanswered.

**Comment by karalabe** [comment]
Hmm, ok. So some hard forks only change the EVM internals, but others also introduce behavioural changes to other parts of the code too (e.g. tx pooling). Whilst we do take care during a transition period to be able to operate in both "old" and "new" feature sets, eventually we need to start removing old modes of operation (that are not EVM related) as it's a significant burden to tiptoe around code that is not exercised any more.

We removed Ethash in a similar vein and will remove Clique too because those require the network to do forward sync whereas Ethereum mainnet nowadays operates on sync directed via the beacon chain (backwards). It is a huge piece of code everywhere to keep both modes of operation and track all the attack vectors and mitigations for both.

Similarly, transaction pooling is constantly evolving, we are introducing blob transactions now which requires a complete overhaul of the tx pooling and there's no reason to re-introduce old mechanisms into the new transaction pools that serve no purpose any more.

My only suggestion is that you need to keep up with the Ethereum hard forks on private networks too as our code base is constantly evolving to track the current network behaviour and we don't have the capacity to be indefinitely backwards compatible to all past versions of network that someone uses.

**Comment by GTMN-bradbrown** [comment]
Do you not agree that this feature would still be very convenient and useful for Ethereum mainnet smart contract developers right now, and would remain convenient and useful for as long as Ethereum transactions require some form of gas? That enabling 0-gas transactions in developer private chains would allow developers to test the functionality of their smart contracts without needing to manage the gas of every address involved in testing? The beacon chain still uses gas, doesn't it, so this would apply to that, too?

**Comment by chenjia404** [comment]
You can easily get gas for private chains

**Comment by GTMN-bradbrown** [comment]
Was taking a look at the documentation again, noticed that it explicitly says that enabling dev mode "Sets the gas price to 0".
https://geth.ethereum.org/docs/developers/dapp-developer/dev-mode
![image](https://github.com/ethereum/go-ethereum/assets/136281932/b2c6f6ae-75fa-4132-aa98-b51407810169)
@karalabe Geth's sanitizing of a gas price of 0 and allowing a gas price of 0 for dev mode is contradictory, and it is clear that one or the other is an issue that needs to be fixed.
As for why I'm not using dev mode, I am developing a multi-chain app and have many private Geth instances running and I need them to have different chain IDs. Whoever created the dev mode built-in to Geth must have thought it would be funny for the chain ID to be hardcoded as 1337.

**Comment by jsvisa** [comment]
@GTMN-bradbrown as you can see the document is outdated, and should be updated

<img width="878" alt="image" src="https://github.com/ethereum/go-ethereum/assets/3627395/58af33a8-0b7c-4f4e-9445-fc5661dfd537">

**Comment by GTMN-bradbrown** [comment]
I cannot understand why the documentation should be updated to reflect that developers can no longer set their gas costs to zero on private test chains for the purpose of development intended to support the Ethereum Mainnet.
There are no security risks.
It is more convenient for developers.
Obviously, at some point, this feature was available, or else the documentation (and the geth binary help reflects this, too) wouldn't state this.

This is very clearly a nice feature that has been removed and nobody can provide an adequate or relevant reason. I am baffled.

**Comment by rmlearney-digicatapult** [comment]
@GTMN-bradbrown we solved this by setting:

`baseFeePerGas: 0x1` in genesis.json

and adding the following switch at startup time:

`--gpo.ignoreprice 0`

This sets a gas price of 2. While not zero, it's a decent workaround.

**Comment by holiman** [comment]
> nobody can provide an adequate or relevant reason. I am baffled.

As @karalabe has explained:

> You can't really have true zero gas price post 1559 though. The basefee must always be burnt.

> Geth is an implementation of Ethereum. There never was nor ever will be a promise to support anything else. Our private network support is meant to run testnets for local testing, it is not meant to run alternative production L1s with different rule sets.
