### ISSUE TITLE
Unable to sync to testnet

### ISSUE THREAD

**Issue by zweicoder** [ethereum/go-ethereum#2756]
#### System information

Geth version: 1.5.0-unstable
OS & Version: Linux

I can sync with the main network but I can't sync with testnet when running with the --testnet flag. This is how I'm running it: `geth --datadir .ethereum/ --ipcpath ~/.ethereum/geth.ipc --testnet`. The `Block Synchronization Started` message is never printed.

Any pointers on possible causes?

**Comment by zweicoder** [comment]
Update: I'm not very sure what is happening but I opened Ethereum wallet (which was supposed to use `~/.ethereum` as the datadir) and it started syncing now. Feel free to close this issue!

**Comment by karalabe** [comment]
Our node discovery service cannot currently differentiate between nodes belonging to different networks (i.e. mainnet vs. testnet), so most of the nodes you find ate mainnet ones, and only rarely find one for the testnet. Because of this joining the testnet takes significantly more time.

@fjl and @zsfelfoldi are working on a new discovery protocol to allow including metadata too to filter/query based on capabilities. It's a long run though as it's a non-trivial change and needs to be speced and synced between other implementations too.

Sorry for the annoyance, hopefully we can solve it in the not too distant future properly.
