### ISSUE TITLE
Block sealing failed with "signed recently, must wait for others" error in a private Ethereum network with just one signer node.

### ISSUE THREAD

**Issue by AlirezaEthDev** [ethereum/go-ethereum#27659]
I encountered an error message in the Geth client stating "Block sealing failed err="signed recently, must wait for others"". I would like to understand the cause of this error and find a solution to resolve it. I would like to emphasize that this error is occurring in a private Ethereum network with just one signer node.

#### System information

Geth version: 1.12.0
OS & Version: Windows Server 2019

#### Expected behaviour
The signer node signs transactions and seals blocks.

#### Actual behaviour
The signer node waits for others and doesn't its job.

**Comment by jwasinger** [comment]
Can you verify that executing `clique.getSigners("latest")` in the console returns only one result?

**Comment by AlirezaEthDev** [comment]
> clique.getSigners("latest")

I tried it, its result is this error: `ReferenceError: clique is not defined at <eval>:1:1(0)`

**Comment by jwasinger** [comment]
> ReferenceError: clique is not defined at <eval>:1:1(0)

> Block sealing failed err="signed recently, must wait for others"

These errors can not both simultaneously happen (the first can only occur if clique is not enabled and the second one will only occur when it is).

Ensure that you are attaching to the console by supplying the path to the `geth.ipc` file that corresponds to the node that is failing to seal:
`geth attach /path/to/geth.ipc`

**Comment by 0x0OZ** [comment]
The same issue happens with me when I use two validators and `clique.getSigners("latest")`  returns the two.

I connect them manually to each other with `admin.addPeer()` because for some reason they don't automatically connect even when the bootnode is set correctly

in both cases, I modified the `extradata` in the Genesis manually because I couldn't find a tool for this(`Istanbul-tools` fails with me)

**Comment by neodiz** [comment]
Its POA or POS ?

**Comment by neodiz** [comment]
I have same error on POS

**Comment by petrkr** [comment]
PoA

**Comment by 0x0OZ** [comment]
The issue when creating a PoA in geth has different causes, for example, I was running 3 nodes connected to bootnode with discover v5. This resulted in nodes being unable to communicate or connect automatically because you use discover v4.
![image](https://github.com/ethereum/go-ethereum/assets/52073989/aee9d084-9dba-4ad6-a076-cf4bf5ed3253)

When I started the bootnode without `-v5` argument I was able to have a working network with 3 nodes(kinda working)
![image](https://github.com/ethereum/go-ethereum/assets/52073989/f8f966d0-b5d6-4460-9f8e-5e8985eba2ae)
 

This is the repo that I used to create the network
https://github.com/0x0OZ/peth

**Comment by holiman** [comment]
Original reporter seems to have abandoned the issue, so I'm closing. 

@0x0OZ I think your manual edit of the extradata is incorrect. You're welcome to open a separate ticket, and if you do, please provide the output of  `clique.GetSigners(0)` and `clique.Status()`
