### ISSUE TITLE
Miner & Personal Deprecated 

### ISSUE THREAD

**Issue by faarid-emad** [ethereum/go-ethereum#27748]
In geth.ethereum.org, under JSON-RPC Namespaces, miner and personal have been deprecated. Where can I find the updated one? Also I'am not able to run any console commands as well

**Comment by s1na** [comment]
There are not going to be a successor to personal and miner namespaces. Miner has been deprecated and will be removed due to Ethereum switching to PoS. Which means consensus will be handled by a beacon client. If you're using clique that will probably be deprecated too soon.

As for personal, the alternative that go-ethereum is offering is [clef](https://geth.ethereum.org/docs/tools/clef/introduction). But you can of course use any other wallet (e.g. Metamask) to maintain accounts and sign transactions for you and have it submit the transaction to geth.
