### ISSUE TITLE
Transaction List

### ISSUE THREAD

**Issue by faarid-emad** [ethereum/go-ethereum#27750]
How can I get the transaction list for my address?

**Comment by jwasinger** [comment]
This information wouldn't be possible to compute if you have a snap-synced node (because Geth doesn't download/import all blocks from the chain history in snap sync).

I don't think there's an easy way to compute it with a full-synced mode unless you manually iterate the history of the chain and note the transactions from your account.

**Comment by karalabe** [comment]
You cannot.

There are different levels of what one might consider "transaction list for my address" and it's pretty much impossible to index all for a generic node (i..e I don't want to index everyone else's txs):

- Transactions that you send, these can be collected from the blocks
- Transactions that you directly receive, these can be collected from the blocks
- Transactions that you receive indirectly via CALL opcodes, these need rerunning EVM execution and saving the data
- Token and NFT transfers, these need understanding of each contract and logs.

**Comment by holiman** [comment]
This is something we could add to the feature "live chain tracing", where we could spit out info every time a certain account is somehow touched. 

For now, though, it's not something that can simply be done via geth.
