### ISSUE TITLE
CVE-2022-37450 Mitigation

### ISSUE THREAD

**Issue by 0xtimosarkar** [ethereum/go-ethereum#27765]
Hi Guys.

Do you know how to mitigate the CVE-2022-37450 at version <=1.10.21 of geth. (Severity rated 5.9/10).
Here is the official description:

```
Go Ethereum (aka geth) through 1.10.21 allows attackers to increase rewards by mining blocks in certain 
situations, and using a manipulation of time-difference values to achieve replacement of main-chain blocks, 
aka Riskless Uncle Making (RUM), as exploited in the wild in 2020 through 2022.
```

#### System information

Geth version: 1.10.21
CL client & version: e.g. geth@<=1.10.21
OS & Version: Ubuntu 20:04

**Comment by MariusVanDerWijden** [comment]
I don't think we can help you maintain a fork of go-ethereum. There are some issues with PoW and the only real solution is to move to PoS. IIRC the issue here was that mining pools would manipulate timestamps to increase the difficulty of their block in order to win over other miners. The solution was to prioritize the existing block in a reorg afair.
