### ISSUE TITLE
Mist - No web3.providers.QTProvider

### ISSUE THREAD

**Issue by scottzer0** [ethereum/go-ethereum#278]
the debugger shows a TypeError and seems to be missing providers in the web3 js object.

**Comment by kumavis** [comment]
![image](https://cloud.githubusercontent.com/assets/1474978/5949944/8434023c-a708-11e4-84a5-806cb4d4a788.png)

My guess is that something is trying to use `web3.providers.QtProvider` before it is defined, and the whole thing blows up, so the providers are never defined. Due to the limited features of the debugger its hard to actually inspect further.

**Comment by kumavis** [comment]
the 404 is for the favicon. not a concern.

**Comment by kumavis** [comment]
Scott and I were both running latest dev builds. Debug info:
```
###### Mist 0.8.1 (go1.4.1) #######

eth 52 (p2p = 2)

CPU:        # 68061120
Goroutines: # 97
CGoCalls:   # 18955

Alloc:      12025880
Heap Alloc: 12025880

CGNext:     1241040
NumGC:      16
```

**Comment by kumavis** [comment]
Its hard to tell what git commit sha is associated with the build. is there any way to tell?

**Comment by obscuren** [comment]
Ethereum.js dropped async (QtProvider). Working towards synchronous API (workable state in Qt5.4 branch)

**Comment by obscuren** [comment]
Synchronous API now on develop. Enjoy
