### ISSUE TITLE
Pruning error

### ISSUE THREAD

**Issue by ktjooho** [ethereum/go-ethereum#27865]
I am running geth 1.11.5 in linux with gcmode  = archive. 
I got an unknown snapshot error when snapshot prune-state with state-root for specific block(which node has state tree).
I think this input state-root hash was not a snapshot checkpoint.

Does pruning support to prune only state HEAD ~ (HEAD - 128) range?  
If this is right, I was wrong guessing. 

However if my guess is right, How should I find a checkpoint block or state-root for pruning..? 
Is there any tool to find it..? I havent seen it.
Thanks.

**Comment by rjl493456442** [comment]
The mechanism of offline pruning is:

- A target state is chosen(HEAD-128 as default)
- iterate the target state, prune all other state data which don't belong to it

In order to simplify the situation a bit, we can only do offline pruning is snapshot
is available and has all HEAD-128 -> HEAD layers present.

In order to run the pruning correctly, you just need to relaunch Geth, run it for a
while(so that snapshot should have 128 layers), and then run the pruning command.
