### ISSUE TITLE
Some possible optimizations for geth

### ISSUE THREAD

**Issue by hzysvilla** [ethereum/go-ethereum#28203]
Dear Geth Team,
I am currently researching some optimisations to Geth related to cache, state and underlying storage as part of my work on the downstream **chainlancet**.
With **chainlancet**，I have observed some optimizations that may improve geth's efficiency, as follows:

1.Duplicate contract bytecode writing. 
The bytecode of the contract newly created by the user will always be written to the underlying database. However, the underlying data uses bytecode hashes as keys and according to research [1] more than 90% of bytecodes are duplicates. This means that a considerable amount of bytecode is being written repeatedly.
Geth can prevent repeated bytecode from being written to reduce write load. In addition, it is thought that corresponding EIP can be proposed for the _Create_ opcode to optimize the gas amount and improve the user experience. For example, deploying duplicate bytecode consumes less gas (similar to _Sstore_ [2]).

2.Duplicate keccak256 calculation
The current implementation of the _keccak256_ instruction does not have any cache, which causes calculations for the same preimage even within a transaction to be executed repeatedly, wasting CPU resources. According to our observation, this kind of repeated calculation of _keccak256_ instructions is very common. For example, in the ERC20 token transfer, the _msg.sender_ and _to_ parameters will be calculated twice by _keccak256_ instruction.
We believe that cache can be added to the implementation of _keccak256_ instructions in geth's implementation, so that repeated hash calculations can be avoided. In addition, we can also propose EIP to reduce gas consumption when the contract repeats _keccak256_ calculations.

We hope that our findings can further optimize geth operation and improve user experience.

Cheers,
The team of  **chainlancet**

**Comment by holiman** [comment]
> 1.Duplicate contract bytecode writing.

The ethereum state trie allows for deduplicating code, since it's referenced by hash. Originally, go-ethereum had a hash-based trie implementation, making it so that we _by necessity_ had each contract only once, keyed by hash. 
While this does save space, it also costs space, since it means an implementation can never delete code, unless there's also an active reference counting going on. 

> 2.Duplicate keccak256 calculation

The actual `keccak256` operation might or might not be optimizable via a cache. Personally I don't quite believe it would make noticeable change, but it would increase execution complexity somewhat. 


Neat ideas, but we don't really need to keep an open ticket for them. We welcome contributions if anyone wants to try out an idea for an optimization, please file a PR.
