### ISSUE TITLE
Valid transaction gas limit

### ISSUE THREAD

**Issue by hyunchel** [ethereum/go-ethereum#28259]
https://github.com/ethereum/go-ethereum/blob/052355f5e2b1726552fdb38a94cf6ea1506caf95/core/txpool/validation.go#L79

I find this line of validation a bit confusing.
I'm sure there is a historical reason for this validation, but can someone explain to me why such upper bound was chosen?
If a large amount of gas is problematic,  50% or 10% upper bound seems to be more proper than 100% of the block's gas limit.

**Comment by jwasinger** [comment]
A transaction that consumes more gas than the current gas limit of the head block of chain is ineligible for inclusion and unlikely to be eligible in the near future.  So it should be discarded and not added to the pool (as this code does).

> If a large amount of gas is problematic, 50% or 10% upper bound seems to be more proper than 100% of the block's gas limit.

Why would that be the case?

A transaction with a large upper-bound could potentially be included and should be considered (especially if it will be included by a block the client is proposing, yielding the tx fees as part of the reward)

**Comment by hyunchel** [comment]
> A transaction with a large upper-bound could potentially be included ...

Right, so a transaction that consumes 90% of the header's gas limit imposes the same level of danger.
If the limit was `100`, and the transaction's gas estimate returns `99`, the above code let the transaction slide.
If such transaction is included, wouldn't that bump the block's total gas to near 200% of its expected value?

Maybe I'm not understanding what `head.GasLimit` is exactly.
I thought this value depends on the block's gas target, which aims to deal with network congestion.

I feel like I'm missing and/or misunderstanding something big here.

**Comment by karalabe** [comment]
> If such transaction is included, wouldn't that bump the block's total gas to near 200% of its expected value?

Yes, it would, that's fine though. If it fits, it fits.

> I thought this value depends on the block's gas target, which aims to deal with network congestion.

No, not really. The base fee (calculated from the gas limits and gas targets) are meant to stabilize the gas prices. They cannot "solve" congestion: if the pool is full, the pool if full no matter how you charge for it. But with the base fee, you can quickly hike up prices and then equally quickly go down, independent of what users send their txs with. I.e. instead of users sending needlessly large prices, the protocol can figure out what's the bare minimum needed and charges only that.

Either way, pricing and fitting is two different concepts :)
