### ISSUE TITLE
Allowing state reexecution with eth_call method

### ISSUE THREAD

**Issue by kaliubuntu0206** [ethereum/go-ethereum#28447]
Like the option `reexec` is supported by `debug_traceTransaction` it would be great if we could have an additional params to reexecute states from `eth_call` method to call contract states beyond 128 blocks.

**Comment by bnovil** [comment]
Seems `eth_call` already support `reexec`, since `TraceCallConfig` embed `TraceConfig `
https://github.com/ethereum/go-ethereum/blob/f4ac548619e12e5be31543a72e995ab2b3904214/eth/tracers/api.go#L151-L167

**Comment by kaliubuntu0206** [comment]
@bnovil Meaning that params is already supported or we should add support for an additional params?

**Comment by bnovil** [comment]
Param is already supported

**Comment by kaliubuntu0206** [comment]
@bnovil I have checked the types for the function and looks like it is likely removed or doesn't exists

https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L1061

https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/transaction_args.go#L37
https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L945

TraceCallConfig only applies to `debug_traceCall` method I think https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#debugtracecall

https://github.com/ethereum/go-ethereum/blob/master/eth/tracers/api.go#L866

**Comment by bnovil** [comment]
@kaliubuntu0206  Sorry I was wrong 😂. I checked again, you are right

**Comment by karalabe** [comment]
Sorry, but this won't be possible / safe. Reexecuting blocks is extremely heavy. On a node that had debug namespace exposed and tracing enabled, we expect the user to not use it in production so hitting it hard with the reexecution is kind of acceptable, but doing it on eth_call would be dangerous for all node operators.

So the short term answer, it's not possible. The mid term answer is that we're working on a new archive node move, where instead of specifying whether you want to be archive or not, you can specify a window of states to keep (e.g. last 1M blocks). That would make it possible to do eth_calls on older state without reexecing anything.

That however still needs some work.

**Comment by kaliubuntu0206** [comment]
@karalabe Is there any ETA for the feature to be available? Sounds super useful
