### ISSUE TITLE
RPC SUB has heavy delay

### ISSUE THREAD

**Issue by rjl493456442** [ethereum/go-ethereum#2850]
#### System information

Geth version: 

api: "0.15.3"
ethereum: "0x3f",
network: "1",
node: "Geth/v1.5.0-unstable/linux/go1.5.1",

OS & Version: Linux
Commit hash : (if `develop`)

#### Actual behaviour

I use `eth_subscribe` rpc to subscribe a specific event like `newBlock`.
However, when i recv subscription message i will block a long time until message return.
And there is a delay between the subscription result with the recently block information in my ethereum node.

Besides, i use `eth_newBlockFilter` and call `eth_getFilterChanges` later to fetch the result back,
i found there is the same problem that return an empty list contain no block information even my ethereum has accept a new block
#### Steps to reproduce the behaviour

````
[backtrace]


{
  "jsonrpc": "2.0",
  "params": [
    "0x3102ba65a139cff3cf9a86c7aaa0c85d"
  ],
  "method": "eth_getFilterChanges",
  "id": 142
}

````

**Comment by bas-vk** [comment]
This might be related to https://github.com/ethereum/go-ethereum/issues/2837. Would be nice to get a response on that. If you overstress the system these things can happen.

**Comment by rjl493456442** [comment]
Thanks, may i ask you another question?
I read the ethereum source code which implemented in python. 
If a normal account send a tx to a contract account, and this tx emit an another transaction sent by this contract account, this kind of transaction is named as internal contract.
I'm confused whether this type of transaction will be written on the blockchain.
Cause i read the EVM code and found "internal transaction" just be processed immediately and didn't new a transaction instance.
So, this type of transaction won't be stored in blockchain. Is my comprehension right?

**Comment by bas-vk** [comment]
If you send a transaction to a contract and that contract does something like `address.send(...)` it won't make a new transaction that is stored on the blockchain as you already figured out. Blockchain explorers use a modified EVM to record these type of transactions.

**Comment by rjl493456442** [comment]
There is an event in solidity. When you send a tx in contract, is an event necessary? If i send a transaction in contract without an event, will this transaction effective?

**Comment by bas-vk** [comment]
An event in solidity is a way to create a log and is not mandatory for a transaction. It's up to the contract creator to add an event of not. You can read more about events and how to use them in the [solidity tutorial](http://solidity.readthedocs.io/en/latest/structure-of-a-contract.html#events). Receipts are by itself not part of the blockchain but stored in their own tree. The root of this receipt tree is part of a block and thus the blockchain.

I'm closing this issue since the origin issue doesn't seem to be relevant anymore. If you need support with these kind of questions please use the gitter channels ([soldity](https://gitter.im/ethereum/solidity), [go-ethereum](https://gitter.im/ethereum/go-ethereum)) or the [ethereum stackoverflow page](http://ethereum.stackexchange.com/). Issues are meant to report problems with geth.
