### ISSUE TITLE
geth --mine --miner.etherbase 0x5495530c79f10A6a894b7E3EB27a39B41424dE40 not working anymore

### ISSUE THREAD

**Issue by heat9070** [ethereum/go-ethereum#28671]
on cmd I have written this command
geth --mine --miner.etherbase 0x5495530c79f10A6a894b7E3EB27a39B41424dE40       

now I get back this error, previously was working fine

panic: ethash (pow) sealing not supported any more

goroutine 4270 [running]:
github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).Seal(0xc0003b0280?, {0x7ff755bf9965?, 0xc0001de840?}, 0xc0001de948?, 0xc0001de840?, 0x8f44b4a2ddbae9db?)
        C:/DEV/go-ethereum/consensus/ethash/ethash.go:84 +0x25
github.com/ethereum/go-ethereum/consensus/beacon.(*Beacon).Seal(0xc0003bf1a0, {0x7ff757834c48, 0xc000201400}, 0xc00011f040, 0x0?, 0x1?)
        C:/DEV/go-ethereum/consensus/beacon/consensus.go:399 +0x8d
github.com/ethereum/go-ethereum/miner.(*worker).taskLoop(0xc0000c4b40)
        C:/DEV/go-ethereum/miner/worker.go:623 +0x2fd
created by github.com/ethereum/go-ethereum/miner.newWorker in goroutine 1
        C:/DEV/go-ethereum/miner/worker.go:294 +0x918

I have cloned the repo and tried to switch to other branch (release/1.11) and installed geth locally, yet I got the same error

What should be done here ?

**Comment by karalabe** [comment]
Geth only supports post-merge (PoS) networks. Bock production on those networks require an operational beacon chain and beacon client too. The beacon client will use Geth's engine API to produce blocks.

> I switched to branch 1.11.6, run same command, same issue, any ideas?

You cannot have the same issue because that error message did not exist in 1.11.6. Perhaps you did not rebuild Geth or you have the previous version still referenced when you try to run it.

**Comment by heat9070** [comment]
> Geth only supports post-merge (PoS) networks. Bock production on those networks require an operational beacon chain and beacon client too. The beacon client will use Geth's engine API to produce blocks.
> 
> >

Would you share more details, I need to mine using geth but without POW

**Comment by karalabe** [comment]
You'll need to provide a lot more details as to what you're trying to do. "Mine without PoW" doesn't make much sense for us unfortunately.

**Comment by heat9070** [comment]
I think it is straight forward, now when I try to start mining on geth I get back panic: ethash (pow) sealing not supported any more, so what I am simply asking about is the alternative to proof of work to start mining, I hope it is clear !

**Comment by karalabe** [comment]
Mining as a concept doesn't exist at Ethereum any more since last year. As such, Geth does not support mining any more.

If you want to make blocks on Ethereum mainnet (or any of our testnets), you need to look into how PoS works, how the beacon chain works, and how validators work. Geth is a small component of the larger validator infrastructure nowadays.

If you want to run your own private networks, you can run old versions of Geth, but we do not support those any more. Or you can set up your own PoS network, for which there are devops tools out there. Hosting your beacon network it outside the scope of Geth however.

**Comment by heat9070** [comment]
Do you have any reference to look at for working with PoS on Ethereum ?

**Comment by karalabe** [comment]
Lighthouse (a beacon client) has a fairly good doc on setting up a node and later in the docs on setting up and running validators: https://lighthouse-book.sigmaprime.io/intro.html .
