### ISSUE TITLE
auto transfer to out account geth

### ISSUE THREAD

**Issue by bhaagiKenpachi** [ethereum/go-ethereum#28854]
I use go-ethereum deploy private network test net point, My account always send all balance to out address.

I use the followed command to start geth:

build/bin/geth --testnet --syncmode "fast" --rpc --cache=1024 --rpcaddr 0.0.0.0 --rpcport 8545 --rpcapi "eth,net,web3" --datadir "./data" console 2>>eth.log

Out address is:
0x6e4cc3e76765bdc711cc7b5cbfc5bbfe473b192e0x6

**Comment by holiman** [comment]
What version of geth are you using? The `fast` syncmode, and `--testnet` is, as far as I know pretty outdated. Also, what does the `eth.log` show? Probably useful information there. 

Normally, I'd guess that `0x6e4cc3e76765bdc711cc7b5cbfc5bbfe473b192e0x6` is an attacker who've found your node (public rpc, `0.0.0.0`), but according to the command above, you do not have `--insecure-unlock` enabled, which otherwise typically would be the easiest way to drain the wallet. 

The address has zero funds on mainnet (an internet-crawler/drainer would probably have non-zero balance). 

I think you'll have to provide more info for us to be able to say anything meaningful.

**Comment by bhaagiKenpachi** [comment]
Please check this tx
https://explorer.dojima.network/tx/0x3c64f5f298360716b0dd3f1f7b3a38d28188e90ad6d24a100621e8bcc133e26c

**Comment by bhaagiKenpachi** [comment]
We found few hints. Thanks for your help. Closing the issue,
