### ISSUE TITLE
Can we add SQRT opcode to EVM?

### ISSUE THREAD

**Issue by t-anyu** [ethereum/go-ethereum#28924]
# Rationale

As square root is needed in many smart contracts and current solidity sqrt implementations consume significant amount of gas when numbers are in orders of > 1E18. Could we add EVM opcode of SQRT? As go-ethereum uses holiman's uint256, can we just add SQRT opcode and specify x gas cost to it?

# Implementation

Add sqrt to core/vm/instructions.go
use uint256 library's Sqrt function

Should be pretty straigthforward or am I missing something?

**Comment by karalabe** [comment]
This repository is not appropriate to suggest protocol change. Protocol proposals need to be created in https://github.com/ethereum/EIPs, possibly with a very strong rationalisation of why they are needed.

Wrt to adding opcodes in general, the consensus is that opcodes are added to enable new types of functionality. Making some operation a bit more optimal whilst noble, would lead to an infinite request of different opcodes that could be added to make one or another thing faster. And adding a new opcode is non trivial, because pricing needs to cover both normal and worst cases, as well as you need to spec out all undefined scenarios. Overall it's a huge chunk of work making sure everything is correct, so people won't willingly do it unless there's a very strong case. Sqrt will not have a strong enough case I'm afraid.

**Comment by t-anyu** [comment]
Yup, totally understandable. Next time I'll be requesting for AVX512
