### ISSUE TITLE
Basic question about data access on full node

### ISSUE THREAD

**Issue by JourneyToSilius** [ethereum/go-ethereum#28936]
Are transactions, transaction receipts, and logs generated by contracts on that transaction available on a full node since genesis ? I am not clear about what exactly can be queried on full node vs archive node. What I currently need is just tx, tx receipts and logs generated on these tx. I am now curently using Erigon but facing problems with memory leaks and I need to know if I can use  Geth full node, since Erigon has been my first experience with Eth nodes 

Thanks

**Comment by adelowo** [comment]
You need an archive node. Full nodes can prune older data

**Comment by rjl493456442** [comment]
[[ FULL NODE ]]

Geth will keep all the historical chain segments by default (block headers, transactions, receipts, logs) on full node. However, only the transaction index of the most recent year will be retained, namely old transactions/receipts/logs are not accessible.
You can change the configuration by setting flag`--history.transactions=0`, which will keep all the transaction indexes.

[[ ARCHIVE NODE ]]

Archive node will keep all the data which full node has, and additionally all the states since genesis. Therefore, the geth archive node is huge(which needs 20TB+ storage space).

For your case, you just need to run geth full node with flag `--history.transactions=0`.
