### ISSUE TITLE
Lost Ether, help

### ISSUE THREAD

**Issue by 362228416** [ethereum/go-ethereum#2895]
#### System information

Geth version: `1.4.10`
OS & Version: Windows
#### Expected behaviour

I've lost my purse money, when I'm going to transfer money to another is not commonly used address saved, unlock the change of address, currency or in right now, but when I turn out the failed, I once again to check, money has disappeared, that have not been to another address 0 x957cd4ff9b3894fc78b5134a8dc72b032ffbc464, totally lost twice, this time it was 208ether and the last time is more than 40ether, are sent in my unlock before and after a few minutes, money can back?
#### Backtrace

```
[backtrace]
```

**Comment by fjl** [comment]
Did you use Mist or geth? Did you use --rpc or other command line options?

**Comment by 362228416** [comment]
@fjl Yes, I use web3 api sendTransaction.

**Comment by fjl** [comment]
Did you run the sendTransaction command in the geth JavaScript 
console?

**Comment by 362228416** [comment]
@fjl No, I use nodejs run it  through the web3 module。

**Comment by 362228416** [comment]
I want to know what money can back？Don't know how money is lost, don't know how to guard against, happened twice already, the loss is very serious。

**Comment by fjl** [comment]
If your account balance on the blockchain indicates that the money is gone, it is gone forever and cannot be recovered.

Sorry for my stupid questions. I was trying to get some details in order to know how a theft could have happened. 

Do not leave accounts unlocked while using the --rpc or --rpcaddr 0.0.0.0 command line options.
--rpc is not enabled by default. If you do leave accounts unlocked while using those command line options to geth, attackers will be able to access your accounts while they are unlocked.
