### ISSUE TITLE
Get rid of snap sync heal phase 

### ISSUE THREAD

**Issue by ababyprogrammer** [ethereum/go-ethereum#29070]
Although snap is great, there are a few classes of users that I don't think it serves the best:

1. Ethereum users with poor internet, but good hardware -- for these users it will take a while for the healing phase to complete.
2. Ethereum power-users who need to sync new nodes and have powerful hardware capable of quickly recomputing state -- yes healing will be relatively fast, but likely not as fast as fully executing the blocks from a recent state checkpoint.
3. Ethereum clones with high gas limits -- some of these churn state so much that most hardware / networks are insufficient to ever complete healing.

For these reasons, it might be interesting to allow users to opt-in to some type of warp-sync-like-scheme using snap.

The general idea would be to have a way to tell geth to stop at certain intervals to "preserve" the snap layers for that block and to also allow clients to pass a specific node id to snap sync from and avoid pivoting to a later block (so long as the target continues responding).

**Comment by karalabe** [comment]
I don't think that's going to ever happen.

If an operator wants to have custom snapshot states and setup a custom sync infra that's on them, but making these snapshots available on the public network is not feasible IMO.

Such a frozen snapshot is non negligible size wise; and it would entail at some point stopping the world until the snapshot is cloned (original issue why Parity's warp sync was having issues).

We will try to maybe have some alternative format based on witnesses to somehow aggregate writes instead of doing so many round trips, but I don't think the general design can be changed much.
