### ISSUE TITLE
Passwordless Clef

### ISSUE THREAD

**Issue by willianpaixao** [ethereum/go-ethereum#29129]
# Rationale

We're moving towards a passwordless world, where we rely on other protocols rather than user created passwords.
I initially propose the integration of [FIDO2](https://en.wikipedia.org/wiki/FIDO_Alliance#FIDO2) into Clef. It will allow, for example, to use security keys to unlock a keystore, an account, maybe sign a transaction.

# Implementation

In Go the library to implement is [go-libfido2](https://github.com/keys-pub/go-libfido2). I could help out with initial implementation, whoever would need assistance from someone with deeper knowledge in Clef.

**Comment by karalabe** [comment]
That doesn't really make sense. The only way to keep your private key secure on disk is to have a key / password / passphrase to encrypt it with. FIDO doesn't provide you with a decryption key, it simply says you are who you are based on a previous handshake / setup. With FIDO Clef would know that you are who you are, but that would not give it the decryption passphrase to access your private key. And if Clef already has the decryption passphrase stored somewhere to do it itself, then your security is down the drain because anyone getting hold of the disk has all the data, irrelevant what FIDO says.
