### ISSUE TITLE
Upgrading GETH from 1.5.9 (no sync data)

### ISSUE THREAD

**Issue by stephenstroud** [ethereum/go-ethereum#29130]
Upgrading from GETH 1.5.9 original - when running geth --fast the server starts but I'm getting no transactions through.

 I've installed the last GETH for Windows, however, it's still pointing to the version 1.5.9, any ideas how I can do to get the latest chain, will 1.5.9 sync not work anymore?

The GETH version is from 2017

**Comment by weiihann** [comment]
I'm pretty sure v1.5.9 is no longer supported...

**Comment by rjl493456442** [comment]
--fast `fastSync` was deprecated a few years ago. There is no supported protocol for it.

> I've installed the last GETH for Windows, however, it's still pointing to the version 1.5.9

What do you mean it's still pointing to old version. Do you have any logs?

I guess you are running a private network? Recommend to use the latest geth version, otherwise it's really hard to know what's the issue and we don't really want to spend time debugging a legacy version.

**Comment by karalabe** [comment]
We're not really sure what you're doing. Geth 1.5.9 is non functional on Ethereum for probably 6-7 years now. If you're running some private network, you might as well start from scratch.

If you want to use mainnet, it feels weird that you go from 7 years to the present, but hey. For that I'm unsure how you installed the old Geth how you installed the new one. We've always shipped the same installers, so if you used that, it should work. If it doesn't, it kind of means you installed Geth via some custom way that we can't really help with.

**Comment by stephenstroud** [comment]
So more context, I've blown off the cobwebs from an old mining machine from at least 6/7 years ago when I had the entire chain synced. (I will start a fresh) thanks!
