### ISSUE TITLE
 Drop Selfish Peers in Transaction Sharing

### ISSUE THREAD

**Issue by learnerLj** [ethereum/go-ethereum#29327]
I am reviewing the source code of geth for my research and noticed that the `TxFetcher` module in `eth/fetcher/tx_fetcher.go` does not trace whether a transaction request is successful or not. Currently, it sends the request and attempts to fetch the transactions, but if a request fails (e.g., due to a peer disconnecting), it reschedules the hashes without further action.
```go
func (f *TxFetcher) scheduleFetches(timer *mclock.Timer, timeout chan struct{}, whitelist map[string]struct{}) {
...
	go func(peer string, hashes []common.Hash) {
		// Try to fetch the transactions, but in case of a request
		// failure (e.g. peer disconnected), reschedule the hashes.
		if err := f.fetchTxs(peer, hashes); err != nil {
			txRequestFailMeter.Mark(int64(len(hashes)))
			f.Drop(peer)
		}
	}(peer, hashes)
....
}
```
I suggest adding a requirement that if a synced peer fails to respond to transaction requests more than 5 times in an hour, we should disconnect from this peer. This could improve the reliability of transaction fetching.

**Comment by rjl493456442** [comment]
Introducing peer scoring could bring risks due to the unexpected behavior from remote nodes, stemming from programming errors or other special cases(e.g. high workload). Dropping peers could potentially result in network splits or unforeseen network issues, which we really want to avoid. Instead, having a few network request failures is totally acceptable.

**Comment by holiman** [comment]
Yeah, we have decided not to implement peer-scoring. Any time we have a peer scoring mechanism, it will be subject to gaming, and it will be at risk to produce false positives, leading to network splits.

If a peers is blatantly misbehaving, we yeet it, otherwise we just accept it and move on. 

At some point, we might decide do implement peer scoring, but currently we do not
