### ISSUE TITLE
[BUG] transaction type not supported error on BaseChain

### ISSUE THREAD

**Issue by TangMonk** [ethereum/go-ethereum#29407]
```
block, err := consts.Web3ClientHTTP.BlockByNumber(context.Background(), big.NewInt(oldBlockNum))
if err != nil {
  fmt.Println("Error fetching block", oldBlockNum, err)
}
```

error:

```
Error fetching block transaction type not supported
```

**Comment by 0xmetaofo** [comment]
use evm json rpc package: github.com/onrik/ethrpc . it's may work for your

**Comment by TangMonk** [comment]
> use evm json rpc package: github.com/onrik/ethrpc . it's may work for your

But I have too many code are building on **go-ethereum** before, I have to migration the old code now.

**Comment by rjl493456442** [comment]
Please upgrade your go-ethereum dependency, otherwise the new type transaction can't be resolved by your node. (I guess you are using ethclient to interact with node).

**Comment by TangMonk** [comment]
Using [op-eth](https://github.com/ethereum-optimism/optimism) will support BaseChain now

**Comment by mwrrlvkixj** [comment]
> Using [op-eth](https://github.com/ethereum-optimism/optimism) will support BaseChain now

@TangMonk Hi, Did you solve it? I tried to use [op-eth](https://github.com/ethereum-optimism/optimism) instead but it also throws transaction type not supported error.

**Comment by nolanjannotta** [comment]
Hey guys, anyone found a solution?  Its weird that `BlockByNumber`  throws a `transaction type not supported` error as it has nothing to do with transactions, you're just fetching a block from the blockchain, right?  Seems weird for go-ethereum to not support L2s.

**Comment by nolanjannotta** [comment]
This is my solution if anyone is running into the same issue:
instead of 
`block, err := wssclient.BlockByNumber(context.Background(), header.Number)`
which throws `transaction type not supported`

im doing 


`var raw json.RawMessage`
`
	err := c.Client().Call(&raw, "eth_getBlockByNumber", hexutil.EncodeBig(blockNumber), true)
`
`
if err != nil {
		log.Fatal(err)
	}`

`c` is a `*ethclient.Client`

the response are bytes in `raw`
I havent tested with an http client, only websockets

Youre basically doing the same thing as what `wssclient.BlockByNumber` does, but for some reason it works fine!

works on Base, Apechain, Mainnet, Arbitrum, Optimism, Polygon

**Comment by arrayofone** [comment]
@nolanjannotta just adding my 2 cents: afaik `BlockByNumber` will implicitly load the transactions for a given block. The comment on `BlockByNumber` states `Use HeaderByNumber if you don't need all transactions or uncle headers.`

Perhaps `HeaderByNumber` is a better fit for your use-case?
