### ISSUE TITLE
Broadcast transaction keeps reporting errors "code\":-32000,\"message\":\"address already reserved\

### ISSUE THREAD

**Issue by hanzhenlong1314** [ethereum/go-ethereum#29400]
Broadcast transaction keeps reporting errors "code\":-32000,\"message\":\"address already reserved\，how should I solve this？How to modify the configuration of the node?

**Comment by karalabe** [comment]
Sending both 4844 and non-4844 transactions form the same account simultaneously will be rejected by Geth. If you've alrteady queued on one or the other, you need to flush it out (e.g. by bumping it's price to ensure it's included) before you can send the other type of transaction. This is done because we keep blob tx and non-blob txs in separate pools and there's no meaningful scenario where both need to be supported, so we decided to keep is simpler by forbidding the mixed case.

**Comment by hanzhenlong1314** [comment]
> Sending both 4844 and non-4844 transactions form the same account simultaneously will be rejected by Geth. If you've alrteady queued on one or the other, you need to flush it out (e.g. by bumping it's price to ensure it's included) before you can send the other type of transaction. This is done because we keep blob tx and non-blob txs in separate pools and there's no meaningful scenario where both need to be supported, so we decided to keep is simpler by forbidding the mixed case.

got it,thanks
