### ISSUE TITLE
Make `operation` struct public

### ISSUE THREAD

**Issue by fedekunze** [ethereum/go-ethereum#29521]
# Rationale

The current geth design prevents upstream users from integrating custom EVM opcodes or modifying their fields (eg. `constantGas`) without having to hard-fork the repository.

# Implementation

Do you have ideas regarding the implementation of this feature?

a) Make [`operation`](https://github.com/ethereum/go-ethereum/blob/master/core/vm/jump_table.go#L32-L45) a public struct with public fields
b) Create a public function (i.e setter) to set a new opcode to the `JumpTable`

Are you willing to implement this feature?

Yes

cc @s1na

**Comment by holiman** [comment]
So, making `operation` public, would ostensibly make it possible to modify opcodes, set new gas schedules etc. 

However, if the purpose is to make downstream users build their own custom blockchains without having to hard-fork the repository, then it falls pretty short. 

- You can modify the gascost, or implementation, but that's kind of it. 

I don't think any single downstream "alternative chain" can be implemented in this limited way. They need to modify the state processing logic, the consensus logic, header format, block format etc etc. 

I'm open to being convinced otherwise, if you can show me that this is actually useful for some project, and not just theoretically useful.

**Comment by karalabe** [comment]
I don't think this would be a good idea. The opcodes are insanely intricate in their interplay and making them modifiable will just open the door for infinite bugreports about people changing them and shooting themselves in the foot. I'd say that changing such a core part of Geth kind of warrants its author maintaining their own fork at that point.

**Comment by fedekunze** [comment]
> I don't think any single downstream "alternative chain" can be implemented in this limited way. They need to modify the state processing logic, the consensus logic, header format, block format, set of precompiles, give precompiles access to state, etc etc.

Correct, we do have an EVM that enables custom stateful precompiles. The Header and Consensus can be customized using [ABCI++](https://informal.systems/blog/intro-to-abci-v2). 

I understand the security considerations to modify the opcodes and the limitation of liability in this regard of why you wouldn't like to maintain this software.

> I'd say that changing such a core part of Geth kind of warrants its author maintaining their own fork at that point.

Yeah that's what we've been doing as well. I was wondering if you were open for us to upstream this code to Geth
