### ISSUE TITLE
geth compilation issues

### ISSUE THREAD

**Issue by zhouhanker** [ethereum/go-ethereum#29560]
Hi
    I use make geth encountered the following issue when recompiling geth1.13.14 version
    
![image](https://github.com/ethereum/go-ethereum/assets/93653642/7c10c68c-135a-44e5-8940-098a90a7d5d5)
    I am trying to set GOEXPRESSION='loopvar 'for go_env but it's still such a mistake I don't know much about go, can anyone tell me a solution 
    dev_env:
            go version -> go1.21.9 linux/amd64
            make version -> 4.3
            gcc version -> gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

**Comment by holiman** [comment]
Yes, that's a bit odd. It's not a "go"-problem, rather, the go-files contains some code written in c, and the go-compilation process triggers a c-compilation step. That's where this error happens, since a variable declaration is inlined into a for-loop, which is not valid "classic" c, only c99 and onwards. 

I don't know why you see this error, but others do not. For what it's worth, my gcc version is `gcc version 13.2.1 20240316 (Red Hat 13.2.1-7) (GCC) `. Is your version heavily outdated perhaps?

**Comment by zhouhanker** [comment]
okay, I'll upgrade my GCC version first and then try compiling again 
Thanks

**Comment by holiman** [comment]
According to https://gcc.gnu.org/ , supported releases are

- 13.2
- 12.3
- 11.4

The [`4.8`](https://gcc.gnu.org/gcc-4.8/) version is no longer supported, `4.8.5` is from June 23, 2015.

**Comment by zhouhanker** [comment]
This issue has been resolved, thank you
