### ISSUE TITLE
Can bad blocks stop synchronization from working?

### ISSUE THREAD

**Issue by AsadullahSoomro** [ethereum/go-ethereum#29685]
I encountered these errors during synchronization:

- Warning: "Downloader queue stats"
- Warning: "Sync Failed, Dropping Peer"
- Error: "Retrieved hash chain is invalid: no peers available or all tried for download"
- Error: "Peer is unknown or unhealthy"
- Error: "Timeout"
- Error: "Pending request exists for joining peer"
- Error: "Expired request does not exist"

However, after some time(approximately 20 hours), the new node started working fine,

**Comment by AsadullahSoomro** [comment]
I am using Clique PoA(Proof-of-Athuority) Consensus algorithm.

**Comment by rjl493456442** [comment]
Which network you are trying to sync. Keep in mind that Rinkeby and Goerli has been deprecated.

**Comment by AsadullahSoomro** [comment]
@rjl493456442  I am using Clique PoA(Proof-of-Athuority) Consensus algorithm.

**Comment by holiman** [comment]
As @rjl493456442 already answered the main question ("Can bad blocks stop synchronization", "No"), nothing more to do here. I'm closing this. 

If you are still having issues, please open a new ticket. But please consider: instead of asking a specific question like "can bad blocks stop sync from working", perhaps it's better to present the problem. "I have the following setup of nodes :..., and the following network: ... , and after a certain time, sync is unable to continue, and this is what I see in the logs: ..." . 

That is, provide is with as much information as possible, so that we might be able to help you diagnose and solve your problems. 
Cheers
