### ISSUE TITLE
eth_estimateGas uses global gas cap as the high watermwark

### ISSUE THREAD

**Issue by karalabe** [ethereum/go-ethereum#29695]
Tracker for https://github.com/ethereum/go-ethereum/pull/29509.

Gas estimation should cap itself to the block gas limit if none is given, currently it caps itself to the configured call gas cap. This is bad because it wastes estimation cycles.

Interestingly, the gas estimator itself works correctly, but is called bad (the gas is set *before* estimation to the global gas cap, so the poor estimator works with what it's given). The cause is a long stream of refactors and abstractions which gradually bubbles setting the gas value of a transaction in ToMessage, which sounds counterintuitive.

Fixing it is not *super* obvious, because changing ToMessage to not set the gas might have other implications. We should look through the call sites and see how to best fix without adding workarounds.

**Comment by quminghaonanya** [comment]
can we get the block gas cap in the `DoEstimateGas` function and pass it to the gas estimator,(https://github.com/ethereum/go-ethereum/pull/28600/files#diff-c426ecd2f7d247753b9ea8c1cc003f21fa412661c1f967d203d4edf8163da344L1208-L1216 just move these logic back and pass the block gas cap to `gasestimator.Estimate`.
so that we can make the higher boundary capped at block gas cap rather than the call gas cap.

**Comment by quminghaonanya** [comment]
Here's the MR to demonstrate my idea: https://github.com/ethereum/go-ethereum/pull/29732

**Comment by SangIlMo** [comment]
I think we can just recap gas.args with header gasLimit when gas.args is greater than block gasLimit.
This enable us to check if gas.args == nil in CallDefaults(). And also, we can prevent gas.args from being greater than block gasLimit.

Here's the suggested PR: #29738 

I think it could be a simple change which meets the purpose of this issue.

**Comment by arajasek** [comment]
@karalabe Can this be closed since 29695 landed?
