### ISSUE TITLE
Wrong Use of Fallback IP(127.0.0.1) as fromIP in Ping message of Node Discovery Protocol

### ISSUE THREAD

**Issue by learnerLj** [ethereum/go-ethereum#29713]
Our tool finds that a client `Geth/v1.14.0-stable-87246f3c/linux-amd64/go1.22.2` sends node discovery `Ping` message whose `fromIP`  is `127.0.0.1`. But the second `Ping` of it shows the correct public IP. I guess the it is the NAT or the setupPortMapping that trigger the problem.
![image](https://github.com/ethereum/go-ethereum/assets/72367122/1a871883-8a93-4f6e-8f06-2e7cd0afd844)

**Comment by fjl** [comment]
The `fromIp` field in discv4 Ping is not widely used. go-ethereum sets it to the current best guess of the local node endpoint. If the node is unaware of its own endpoint, it puts 127.0.0.1 into this field. Local knowledge of the endpoint can change, for example when endpoint prediction behind NAT is in use. So that's why it will sometimes set to 127.0.0.1 and to another IP later.
