### ISSUE TITLE
`eth.coinbase` returns error in developer mode after v1.14.0

### ISSUE THREAD

**Issue by ardislu** [ethereum/go-ethereum#29747]
#### System information

```
$ geth --version
geth.exe version 1.14.3-stable-ab48ba42
```

#### Steps to reproduce the behaviour

1. Run geth in developer mode:

```
geth --dev
```

2. In a separate window, attach a JavaScript console:

```
geth attach
```

3. In the JavaScript console, run `eth.coinbase`:

```
> eth.coinbase
```

#### Expected behaviour

The coinbase address is returned.

#### Actual behaviour

```
> eth.coinbase
Error: the method eth_coinbase does not exist/is not available
        at web3.js:6387:9(39)
        at get (web3.js:6287:66(14))
        at <eval>:1:5(1)
```

The window running geth shows the following `WARN` log:

```
WARN [05-10|00:39:09.291] Served eth_coinbase                      reqid=8 duration=0s err="the method eth_coinbase does not exist/is not available"
```

---

#### Workarounds:

1. Use `eth.accounts[0]`, which returns the address as expected:

```
> eth.accounts[0]
"0xfbf85da4676078f99da1d47409da18f87b9a8752"
```

2. Use a prior version of geth. `eth.coinbase` is working as expected in v1.13.15:

```
$ ./geth --version
geth.exe version 1.13.15-stable-c5ba367e

$ ./geth --dev
```

In the JavaScript console:

```
> eth.coinbase
"0x50db607615fff21e52c9f9f989d9d9b938d4ec5e"
> eth.accounts[0]
"0x50db607615fff21e52c9f9f989d9d9b938d4ec5e"
```

**Comment by karalabe** [comment]
There's no notion of "coinbase" any more. Mining is not directed by Geth any more, rather by the beacon client.

In case of dev mode, this is a bit "peculiar"., because the beacon client is a simulated stub part of Geth, but still, Geth itself is "unaware" of who the block author will be, so it doesn't provide an API any more to retrieve it.

This unfortunately will be an idiosyncrasy in dev mode to avoid creating dedicated APIs for it.

**Comment by karalabe** [comment]
E.g. On a live PoS node, you can set etherbase/coinbase to anything, it will be completely ignored and the one provided by the beacon client will be used. We kept etherbase only for backwards compatibility with non merged networks, but was getting wonky. Since we dropped non-merge support, cleaning this makes everything less ambiguous. Everything except dev mode as it turns out :)
