### ISSUE TITLE
When downloading geth-windows-amd64-1.14.3-ab48ba42.exe NordVPN says "Malware detected and deleted"

### ISSUE THREAD

**Issue by ihenriksen** [ethereum/go-ethereum#29759]
#### System information

Geth version: geth-windows-amd64-1.14.3-ab48ba42.exe
CL client & version: N/A
OS & Version: Windows 11 23H2 Build 22631.3447
Commit hash : N/A

#### Expected behaviour
Download without any problems

#### Actual behaviour
NordVPN says "Malware detected and deleted" and deletes the file. 

I turned off NordVPN's File Protection and confirmed that the geth-windows-amd64-1.14.3-ab48ba42.exe file's signature matches the 29eadff60633f4cada4000f21e5870e1 signature on your website.

Detailed NordVPN warning is:
File name: geth-windows-amd64-1.14.3-ab48ba42.exe
File origin: https://gethstore.blob.core.windows.net/builds/geth-windows-amd64-1.14.3-ab48ba42.exe
Status: "Threat detected: HEUR/APC"

#### Steps to reproduce the behaviour
1. Start NordVPN
2. Make sure that "File Protection" is turned on.
3. Try to download geth-windows-amd64-1.14.3-ab48ba42.exe installer from https://geth.ethereum.org/downloads
4. NordVPN says "Malware detected and deleted" and deletes the file before I can run it.

#### Backtrace
N/A

**Comment by karalabe** [comment]
Seems a false positive on their end: https://www.virustotal.com/gui/url/35b45d697424b34f236dcc9c7bde3f120d2550c88749064539121220e3cf3bcf

It's a bit annoying, but due to Geth having P2P code, mining code, crypto code, etc; it quite often gets flagged by one system or another. I'm not really sure what we can do about it, apart from ask people using those systems to try and report as false positive (as long as everyone else reports it as clean).

**Comment by ihenriksen** [comment]
Figured as much but thought I would report this anyway, thanks for looking into it. Have a nice day.
