### ISSUE TITLE
How to obtain the returned value of payable call? 

### ISSUE THREAD

**Issue by Sammers21** [ethereum/go-ethereum#29848]
I want to call `ExactInputSingle` on that smart contract and obtain the returned value:
<img width="1049" alt="image" src="https://github.com/ethereum/go-ethereum/assets/16746106/2da1b217-596b-42ea-a9a5-1720db0da113">
[Contract](https://sepolia.etherscan.io/address/0x3bFA4769FB09eefC5a80d6E87c3B9C650f7Ae48E)

```go
res, err := uniswap.ExactInputSingle(&bind.TransactOpts{
		From:     ...,
		Context:  ...,
		GasPrice: ..,
		Nonce:    ...,
		Signer: ...
	}, singleParams)
```

But the `res` here is the `Transaction` type, how do i get the amountOut value thats being returned?

**Comment by karalabe** [comment]
abigen currently returns data only for read-only methods (eth_call), but not for transacting methods (since there's no result before the transaction is mined). For that you'd need to retrieve the receipt of the mined transaction and parse the result. I'm not aware of abigen supporting that. It's an interesting feature request tho, will have to think about it.

**Comment by Sammers21** [comment]
@karalabe how do i extract result from receipt of the mined transaction and parse it?
