### ISSUE TITLE
Does the single boot node stated by "bootnode" command have the maximum connection node limit ?

### ISSUE THREAD

**Issue by ObscureLin** [ethereum/go-ethereum#29884]
I am using docker to run 100+ geth nodes and 1 bootnode, it seems only around 30 nodes can connect to bootnode. So can a bootnode only guide 30 geth nodes ?

**Comment by karalabe** [comment]
Are you running an actual node for your bootnode, or are you running `cmd/bootnode` (discovery only)?

If the former, then it's a default node config that maxpeers are 50, out of which 1/3 is outbound (I guess 0 peers in you case because the geth nodes aren't accessible) and 2/3 inbound (which would be 33 nodes accepted to connect to the bootnode).

You could raise the peer count on your central node via `--maxpeers`. For 100 inbound peers, you'd need to set maxpeers to 150+

**Comment by ObscureLin** [comment]
Very appreciate for your help. What if i am using the latter（cmd bootnode）？
---- Replied Message ----
From Péter ***@***.***> Date 05/30/2024 16:58 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [ethereum/go-ethereum] Does the single boot node stated by "bootnode" command have the maximum connection node limit ? (Issue #29884) 
Are you running an actual node for your bootnode, or are you running cmd/bootnode (discovery only)?
If the former, then it's a default node config that maxpeers are 50, out of which 1/3 is outbound (I guess 0 peers in you case because the geth nodes aren't accessible) and 2/3 inbound (which would be 33 nodes accepted to connect to the bootnode).
You could raise the peer count on your central node via --maxpeers. For 100 inbound peers, you'd need to set maxpeers to 150+
