### ISSUE TITLE
Sync time over NTP

### ISSUE THREAD

**Issue by General-Beck** [ethereum/go-ethereum#2990]
https://github.com/ethcore/parity/issues/2062
this question is very relevant! Many users complain about the sync.

**Comment by Arachnid** [comment]
I also think that this is the responsibility of the OS, not any tasks running on it.

**Comment by karalabe** [comment]
We've debated this a few times. The reason go-ethereum issues a warning but does not sync anything to an NTP server is because it's an attack vector. NTP can be spoofed easily enough, so if the node were to sync automatically your clock and someone spoofs NTP they can get you connected to some weird subnetworks "in another time" controlled by the attacker. Then they can do all kinds of replay attacks since you cut yourself off of the main peers.

Lastly I think it's very bad practice for running programs to change your OS settings. If anything, we should try to come up with a discovery protocol that doesn't rely on timestamps.
