### ISSUE TITLE
Ancient blocks frozen already

### ISSUE THREAD

**Issue by alex-bratu** [ethereum/go-ethereum#30165]
#### System information

Geth version: `geth 1.13.12`
OS & Version: Debian 11

I have a private net running on PoA using clique. In the last week it seems like it has trouble keeping up the mining process. The error that I get is "Ancient blocks frozen already". I found a workaround to set the chainHead a bit lower than the current blocknNumber and starts again, but I want to find a more stable solution and go to the root of the problem.

#### Expected behaviour
Mine blocks

#### Actual behaviour
Freezes the blocks and and goes out of sync

**Comment by fjl** [comment]
The log message "Ancient blocks frozen already" is not an error. It's a DEBUG level message. So your issue is not related.

It's pretty likely that your issue is related with clique consensus. There is a known issue where the protocol can sometimes lock up. You can configure an **odd** number of signers to make it less likely to occur. 

Please note that support for clique consensus is no longer provided by Geth v1.14, and thus issues with clique will not be fixed.
