### ISSUE TITLE
Ensure nodes can be added early to the node discovery table

### ISSUE THREAD

**Issue by dknopik** [ethereum/go-ethereum#30243]
# Rationale

Currently, while the node table is being initialized (i.e. while the first `doRefresh` is being run), nodes can not be added to the node table: https://github.com/ethereum/go-ethereum/blob/6e33dbf96a06cb3ad3bdbd5d0539e54de254ce6b/p2p/discover/table.go#L512-L516

This causes nodes that very quickly connect (for example in devnets and simulations) to be "bonded" (as per `UDPv4.checkBond`), but not present in the table, and thus are not included in `NEIGHBOUR` responses.

# Implementation

There are several ways to potentially fix this.

1. My current naive workaround is to add the nodes after initialization:
```go
// For nodes from inbound contact, there is an additional safety measure: if the table
// is still initializing the node is not added.
if req.isInbound && !tab.isInitDone() {
    go func() {
        <-tab.initDone
        tab.addInboundNode(req.node)
    }()
    return false
}
```
I'm pretty sure though that this is not really the way to go.  

2. Only listen to our discovery port as soon as we have initialized the table and are thus ready to properly handle requests.
3. Fix the underlying problem with adding inbound nodes while the first refresh is in progress. I am not sure why this is not possible.

I am willing to implement your preferred approach.

**Comment by lightclient** [comment]
Thanks for this issue. This is a very interesting part of the table implementation. The reason we do not add nodes before the table is initialized is because while bootstrapping, the node is vulnerable. Without this restriction, it would be possible to quickly ping the node with many identities and eclipse them. By allowing the bootstrap to run to completion, we have a high confidence that there are honest peers in the table.

Given that - I think there is not a possibility to do 1 or 3. Do you issues if you setup the enodes for the peers on the network as bootnodes?

> This causes nodes that very quickly connect (for example in devnets and simulations) to be "bonded" (as per UDPv4.checkBond), but not present in the table, and thus are not included in NEIGHBOUR responses.

Could you elaborate on this issue? Is the problem that it takes a long time for peers to bond in a small network? It makes sense the node isn't included in `NEIGHBOR` responses if it isn't added to the table. This could also happen if certain IP limits are reached in the table.

**Comment by dknopik** [comment]
>Do you issues if you setup the enodes for the peers on the network as bootnodes?

Sorry, what do you mean by this?

>Could you elaborate on this issue? Is the problem that it takes a long time for peers to bond in a small network? It makes sense the node isn't included in NEIGHBOR responses if it isn't added to the table.

In my case, I have one Geth `bootnode` process and four Reth nodes. The Reth nodes quickly send a `PING` packet each to the Bootnode, which is immediately responded to by a `PONG` and a `PING` each. As soon as the response `PONG`s have arrived, the Bootnode starts accepting other discovery packets from them (i.e. `FINDNODE` and `ENRREQUEST`), and _would_ add them to the table, but doesn't, as the table is still being initialized. The Reth nodes then try to poll the table via `FINDNODE`, but the table is empty, as all nodes have pinged the Bootnode too quickly. The table is not filled afterwards, as the discovery code only does so in these cases:  
a) a `PING` has been received, and we remember receiving successful `PONG` from that peer recently
b) a `PING` has been received, and we try to `PING` in return. The corresponding `PONG` will add the peer

The Reth nodes will not `PING` for a while, because from their perspective they don't need to. Thus, the table stays empty and the Reth nodes will never discover each other.

I realize that my case is pretty specific, and as you mentioned, as soon as another node pings after the bootstrap period, the nodes would slowly discover each other via that node. And in my case, I could simply start the Reth nodes 5 seconds after `bootnode`. So I guess Option 4 is wontfix, but I would advocate for at least a log message so that future users with unconventional setups won't have to spend much time trying to figure out what's going on. :)

**Comment by fjl** [comment]
I appreciate the debugging. However, due to safety concerns as @lightclient mentioned, we cannot accept inbound nodes during the init phase. The discovery system is designed with a larger network in mind and will sometimes have these kinds of odd faults in small private networks. I've tried to make it work somewhat even for those cases (for example, IP address limits are not applied in LAN).

**Comment by dknopik** [comment]
Alright, thanks for the explanation :)
