### ISSUE TITLE
Highest block returned by `eth.syncing` fluctuates moving up and down.

### ISSUE THREAD

**Issue by colm** [ethereum/go-ethereum#3033]
#### System information

Geth version: `geth version` 1.4.11-stable
OS & Version: Linux Ubuntu Xenial
Commit hash : (if `develop`)

#### Expected behaviour
Highest block returned by `eth.syncing` should only increase. 

#### Actual behaviour
Highest block returned by `eth.syncing` changes
```
> eth.syncing
{
  currentBlock: 2272408,
  highestBlock: 2326482,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 2265791
}
> eth.syncing
{
  currentBlock: 2272408,
  highestBlock: 2282630,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 2265791
}
> eth.syncing
{
  currentBlock: 2272408,
  highestBlock: 2326493,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 2265791
}
```

#### Steps to reproduce the behaviour
I start geth with the following `geth --cache 1024 --targetgaslimit 1500000 --     gasprice 20000000000 --support-dao-fork --fast --forcejit --rpc console 2>> out.txt`

#### Backtrace
````
````

**Comment by karalabe** [comment]
Highest block is defined by your peer that reports the most difficulty chain. Since it may happen that that particular peers disappears, there's no guarantee that the highest block it reported is still true or not. So when you try to sync with someone else, the highest block number is taken from the new node. There's is no way to know the true highest number in the network.
