### ISSUE TITLE
Strange discrepancy in ETH egress

### ISSUE THREAD

**Issue by holiman** [ethereum/go-ethereum#30517]
This is a bit odd. I've been trying to do a comparison between `bench07` (my experiment) and `bench08` (master). However, looking at the
last 24h here, I can see that the `master` has more memory usage, but also more egress traffic:

![Screenshot 2024-09-27 at 07-50-29 Dual Geth - Grafana](https://github.com/user-attachments/assets/eb3b0c35-7f43-435e-a850-f4c5301c3ebc)

So, has someone been syncing from `08` for the whole time? Seems a bit strange. So let's look at the traffic charts: 

Here's the `08` egress rate on `ETH`: 

![Screenshot 2024-09-27 at 07-57-46 Single Geth - Grafana](https://github.com/user-attachments/assets/04636047-8192-4b10-9513-76ab7b0e2b87)

To compare with `07` egress rate on ETH: 

![Screenshot 2024-09-27 at 07-58-28 Single Geth - Grafana](https://github.com/user-attachments/assets/bc1de846-6b4e-4ba7-bc34-6e0f950bc2aa)

Summary, the `08` has been serving transactions (`eth/68 transaction response`) at a rate of `250 kB/s` for the last (at least) 24 hours - corresponding figure for `07` is `~5 kB/s`. A factor of `50x` difference. I find it curious, opening this ticket to see if anyone has any interesting ideas on the why. 

For example, could it be fake/thin peers which only continuously leech transactions, in some MEV pursuit? And once you're unlucky enough to peer with one, you'll be serving data continuously ?

**Comment by karalabe** [comment]
This is indeed interesting. Wondering if we could try and track more detailed metrics per peer (would venture to say per node type, but that's so easy to fake that it's a meaningless metric in case someone is abusing tihngs).

**Comment by kaber2** [comment]
While I obviously can not say what happened in your specific case, your assumption is correct. There are many MEV people running their own fake node implementations in order to receive transactions faster, my handwaving estimation on a different network has been that at least 95% of nodes (by enode) are fake.

The normal mode of operation is to simply request any announced Tx immediately, some do optimistic fetching, meaning they will spam nodes with fetch requests of Txs announced by other nodes (presumably with a larger RTT) and some are simply sending garbage fetch requests or requesting the same Tx over and over again, presumably because their implementation is broken.
