### ISSUE TITLE
Invalid whoareyou when whoareyou message using a nonce derived from a resp packet

### ISSUE THREAD

**Issue by GrapeBaBa** [ethereum/go-ethereum#30592]
Currently, go-ethereum only track the activecall which sent request discv5 packet, however not track the active response which sent resp discv5 packet. When receiving a whoareyou message which use the nonce from a resp discv5 packet, go-ethereum will throw the invalid whoareyou error when in `matchWithCall` function. This seems a bug according to the discv5 [spec](https://github.com/ethereum/devp2p/blob/master/discv5/discv5-wire.md#whoareyou-packet-flag--1)

**Comment by karalabe** [comment]
CC @fjl

**Comment by fjl** [comment]
This is by design. The handshake only works if there is an answer to the challenge.

So the idea is this:

The protocol, at a high level, has requests and responses. It also has the need to negotiate a session, which is a low-level process. In order to make the session negotiation work we need to receive a response packet.

```
A -> B    Request
A <- B    WHOAREYOU (nonce)
A -> B    Request (nonce, challenge)
A <- B    Response (challenge-response)
```

What you are proposing is like this:

```
A -> B    Response
A <- B    WHOAREYOU (nonce)
A -> B    Response (nonce, challenge)
A <- B    ???
```

But it doesn't work because party `B` has nothing to send in response to a response.

**Comment by GrapeBaBa** [comment]
@fjl @karalabe Thank you for the explanation, it seems that this should be an issue with another portal client.
