### ISSUE TITLE
geth 1.4.14 prerelease issue

### ISSUE THREAD

**Issue by DariusPrzydzial** [ethereum/go-ethereum#3065]
#### System information

Geth version: `geth version`               1.4.14  prerelease/go1.7
OS & Version: Windows/Linux/OSX  Win 10
Commit hash : (if `develop`)

#### Expected behaviour
geth syncing blockchain is normal

#### Actual behaviour
ehtminer running 10% slower and not submitting results to dwarfpool after updating geth
also, Windows 10 had an update earlier in the morning

#### Steps to reproduce the behaviour
just fyi

**Comment by fjl** [comment]
Thank you for the report. Can you go into more detail? So you are running ethminer against dwarfpool and it runs slower because you updated geth?

**Comment by DariusPrzydzial** [comment]
Correct, once I updated geth to prerelease, the ethminer stopped submitting results or maybe stopped finding solutions. I reverted geth to 1.4.13 and could not correct this behavior. I restarted the ethminer several times and also deleted all DAGs in suspicion they were corrupted.

**Comment by fjl** [comment]
Can you paste the command lines that you use to start ethminer and geth here? I doubt that the 1.4.14 release is the problem, but would be nice to be sure.

**Comment by DariusPrzydzial** [comment]
geth --rpc console
----
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer -G -F http://eth-us.dwarfpool.com/0xXXXX7848da43XX4a605XXa6f2250516adff06XXX/rig1

**Comment by DariusPrzydzial** [comment]
ethminer version 1.2.7

**Comment by fjl** [comment]
ethminer does not use geth at all with these settings. So if all you want to do is mining you can probably just uninstall geth.

**Comment by DariusPrzydzial** [comment]
sure but this does not resolve my issue with ethminer not submitting results. I am not sure what else I could do ...

**Comment by fjl** [comment]
You probably want to open an issue here: https://github.com/Genoil/cpp-ethereum/issues
You can also contact dwarfpool support.

**Comment by d57heinz** [comment]
Not meaning to interrupt but as a suggestion  lookup genoil 1.1.7 on github if your running windows  click the drop down that lets you change the branch Goto 110 branch. Then scroll down the page and look for the release folder.   Not the one up top. Then click view raw and it will download the exe.  Or lookup claymore dual Ethereum miner but it has a 1% fee attached to it and is closed source.  I don't use that version ethminer1.2.7 so I don't know if it has stratum support or not.  But nowadays you def need that and that could be why it's not working correctly with dwarf.  Also what speed are you mining at. It could take some time just to submit one share if you have only one card.  Dwarfpool diff is high if I recall correctly.  I mine solo now and have for some time so I can't attest as to what the pools have going on nowadays.   Btw geth 1.1.14 working great. Steady mem usage and I've already submitted one block since the changeover. Thanks for the relentless effort guys/gals!

BR 
d57heinz

**Comment by DariusPrzydzial** [comment]
I resolved my issue with just downloading the new ethminer software (link below) and it run on the first try. https://github.com/Genoil/cpp-ethereum/blob/master/releases/ethminer-0.9.41-genoil-1.1.7.zip
Thank you for your great work.
Darius
