### ISSUE TITLE
geth quits unexpectedly and regularly while sync'ing

### ISSUE THREAD

**Issue by attila-lendvai** [ethereum/go-ethereum#3131]
#### System information

```
Geth
Version: 1.4.17-stable-5a6008e0
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.5.1
OS: linux
GOPATH=
GOROOT=/usr/lib/go
```

i have attached below a zip with several log files where geth sometimes just quits silently, or reports a backtrace, sometimes complaining about memory.

it first happened while i was doing a --fast sync, and now regularly that i'm continuing the sync.

my machine has 4GB, 2GB is used for geth cache, and geth is alone on the linux.

this is how i start geth:

```
#!/bin/bash

SCRIPT_DIR=`dirname "$0"`
SCRIPT_DIR=`readlink -f ${SCRIPT_DIR}`

pushd "${SCRIPT_DIR}"

while true; do
  now="`date +%Y-%m-%d-%H:%M:%S`"
  ./go-ethereum/build/bin/geth --oppose-dao-fork --jspath "${SCRIPT_DIR}" --preload "geth-autoload.js" --nat any --cache 2048 --rpc --rpccorsdomain localhost 2>&1 | tee /var/log/geth/geth-${now}.log

  echo "looping to restart geth..."
  sleep 1
done

popd
```

#### Backtrace
[geth-crash-logs.zip](https://github.com/ethereum/go-ethereum/files/527571/geth-crash-logs.zip)

**Comment by fjl** [comment]
ETC is also affected by DoS attacks. We are preparing a fix for the latest attack seen on ETH network. ETH will most likely hard fork in the next couple of days to fix gas costs of the EVM exploited operations.

Thank you for reporting the crashes. I will close this issue because we already have several OOM reports open and the cause is known.
