### ISSUE TITLE
Latest geth has severe memory leak!  Over 7.8GB memory and still climbing!

### ISSUE THREAD

**Issue by molitar** [ethereum/go-ethereum#3134]
#### System information

Geth version: 1.4.17
OS & Version: Windows 7 64 bit

#### Expected behaviour
way way less memory usage.

#### Actual behaviour
7.846GB of memory usage. climbing by the minute.

#### Steps to reproduce the behaviour
run ether wallet and monitor geth.exe while it's syncing!

#### Backtrace

````
[backtrace]
````

**Comment by fjl** [comment]
This is the result of an ongoing DoS attack. We are working on implementation improvements and 
a hard fork has been proposed to mitigate it at the protocol level. See https://blog.ethereum.org/2016/10/13/announcement-imminent-hard-fork-eip150-gas-cost-changes/ for more information.

I'm closing this because https://github.com/ethereum/go-ethereum/issues/3129 also tracks the memory issue.

**Comment by fjl** [comment]
Geth 1.4.18 has been released and fixes the memory usage issue.
