### ISSUE TITLE
Geth install intructions

### ISSUE THREAD

**Issue by jdetychey** [ethereum/go-ethereum#3159]
Hi,
It looks like the the install instructions need an update.
The link https://install-geth.ethereum.org/ is broken so the instruction:
`bash <(curl -L https://install-geth.ethereum.org)`
won t work.

Using:

`apt-get install geth`

doesn't seem to install the last version but 1.5.0-unstable.

Best regards, <3 golang

**Comment by karalabe** [comment]
Where are these install instructions? The first one was only for frontier, it was dropped later. The apt-get version installs develop because you've added the `ethereum-dev` PPA repository too. But yes, we'll need to clean up. Our new build infrastructure will push both stable and develop into a single PPA and then you can install either `apt-get install geth` or `apt-get install geth-develop`, which should make things a lot clearer.

**Comment by jdetychey** [comment]
I followed:

https://github.com/ethereum/go-ethereum => Readme.md

"For prerequisites and detailed build instructions please read the Installation Instructions on the wiki."

that leads me here 

https://github.com/ethereum/go-ethereum/wiki/Building-Ethereum

and there

https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Ubuntu

those instructions suggests: "You can alternatively install only the geth CLI with apt-get install geth if you don't want to install the other utilities (bootnode, evm, disasm, rlpdump, ethtest)."


I haven t tested the Automated development builds line in the Readme.md

FYI my node is fine I am running the last version of Mist with fork update.

**Comment by fjl** [comment]
Instructions are updated now.
