### ISSUE TITLE
Transaction disappeared.

### ISSUE THREAD

**Issue by BorilloB** [ethereum/go-ethereum#3167]
#### System information

Geth version: `1.4.17`
OS & Version: Linux
Commit hash : (if `develop`)
#### Expected behaviour

Transaction send 16.10.16, befor harfork.
#### Backtrace

```
[backtrace]
```

Hello. Our clients makes several transactions, for example(from log):
I1016 08:46:01.687279 eth/api.go:1185] Tx(0x09eebacdfe8155064b590e2636d1115fb0b229003a1e58cbc927f1e81cd1f56c) to: 0x67f0f1b1c753062b6093359d4184a36882e389df
I1016 08:42:02.043335 eth/api.go:1185] Tx(0x3b0dd7d4a68fc6b2e53611f4204ca2d9a5b84b39f9032de16bded91274009c95) to: 0x5c70eb0e8923cc0c416e8fa002ad165c9cfcfb24

Eth don't received to destination address and not return back. What we need to do for resolve this issue ?
Now we use 1.4.18 version, but this not help for resolve our problem with disappeared transactions. 
Thank you.

**Comment by bas-vk** [comment]
There can be several reasons for this:
1. Your node doesn't have a good peer set, check from the geth console with `admin.peers.length`. If you restart your node all transactions that have not been send onto the network will be lost. This can be a bit tricky since geth nodes that are not synced will ignore incoming transactions.
2. You set a too low gas price, miners won't accept these. Use the default gas price the node calculates.

**Comment by BorilloB** [comment]
What you mean "all transactions that have not been send onto the network will be # lost" Lost= return to client ?

**Comment by karalabe** [comment]
None of those transactions that you listed were executed by the network, so no funds ever moved.
