### ISSUE TITLE
how long does the tx  stay in the queue in txpool?

### ISSUE THREAD

**Issue by zhumingu** [ethereum/go-ethereum#3228]
such as the title, and may there be multiple transactions associated with the same account and nonce in queue and pending? It seems to not update the document.

**Comment by karalabe** [comment]
The transaction pool contains two queues:

* The `pending` queue contains transactions that seem to be executable, though there may be a lot of them so it may take time until miners start including them.
* The `future` queue contains transactions that seem to not be executable, usually because there's a nonce gap for the particular account. The role of this queue is mostly to cover out of order transactions arriving from the network.

Now, the caveats:

 * If a new transaction is issues for the same account and the same nonce, the higher priced version will be retained.
 * The local transaction pool will always accept your local transactions irrelevant of the price, but remote pools will filter out anything that's below their configured gas price.
 * If pool limits are reached, `pending` transactions are evicted in such a way that accounts have a fair share to get transactions included and `future` transactions are evicted according to when the account last had a successful transaction (to avoid caching junk for inactive spammers).

**Comment by zhumingu** [comment]
Thanks to reply timely. As you said, may pending transactions be  evicted？Each future transaction can stay in the future queue all the time and no limit?

**Comment by obscuren** [comment]
Pending transaction will be evicted if a "better" transaction from the same sender with the same nonce is found. Future transactions may stay in the pool in a limited matter.
