### ISSUE TITLE
RPC vulnerable?

### ISSUE THREAD

**Issue by Levino** [ethereum/go-ethereum#3298]
This is rather a general question: Can people trigger harmful code execution when they use the RPC interface of a node? Is it dangerous to open the RPC port to the outside world?

I am not talking about "stealing funds from unlocked accounts". But executing arbitrary code and stuff / DOS of the node / crashing the node. Are there tests for this?

**Comment by ethernomad** [comment]
Probably. The light client is coming! ;-)

**Comment by karalabe** [comment]
Don't expose RPC to the world. It was not designed to be a public facing endpoint, there are many ways to exhaust resources (e.g. just send tons of `estimateGas` calls with large contracts).

If you need outside access you should do that in a controlled way by placing your own API proxy as a front end, doing all the necessary checks there and if everything checks out, then execute a call against a backend node.

**Comment by Levino** [comment]
I think this should be improved. Would be a very easy solution for light wallets with client sided signatures. The goal should be that the rpc is robust.

In our case I think that somewhat was able to execute arbitrary code (we got a port scanning abort message) in the ethereum-go docker container. But this is just an educated guess, as I have no proof for this. I just saw that the thread in the container logged weird errors.

**Comment by bas-vk** [comment]
What you are asking for is really hard to implement. As @karalabe mentiond, if you expose the RPC interface anyone can simply overload the node with RPC requests. The RPC is robust within its design parameters, that is not publicly accessible.

There are 2 alternative solution:
1. Use a firewall/proxy and use ACL and/or throttle the number of requests.
2. Use a local light client (experimental support since 1.5) with your DApp.

> In our case I think that someone was able to execute arbitrary code (we got a port scanning abuse message) in the ethereum-go docker container. But this is just an educated guess, as I have no proof for this. I just saw that the thread in the container logged weird errors.

Geth doesn't allow execution of arbitrary code, it will allow execution of smart contract code. The EVM has limited support for interacting with the OS (e.g. write storage) but this happens in a controlled way. If you have strong suspicions and preferable clear indications that its possible to exploit the RPC interface and execute arbitrary code please send a bug bounty report.

**Comment by Levino** [comment]
What about writing memory of other processes and stuff? I do not think that it allows this by intend, but maybe there are bugs that can be exploited. I will come back to this if I have a clear lead on what happened but I put the node behind a basic auth proxy now, so I actually do not expect any successful attacks any more.

**Comment by obscuren** [comment]
Closing this down as it's a general question that can't be directly answered or observed. Please re-open if you've a detailed report when there is an issue with the RPC.
