### ISSUE TITLE
Please release versioned docker images.

### ISSUE THREAD

**Issue by Levino** [ethereum/go-ethereum#3349]
Someone released an image tagged v1.5.2 but v1.5.3 or v1.5.4 were not released.

See here https://hub.docker.com/r/ethereum/client-go/tags/

Please automatically publish new docker images with tags. "Latest" was not really stable in my experience so I was happy to be able to use versioned images with 1.5.2 but of course now I need to update.

While we are at it: Please publish as 1.5.3 and NOT v1.5.3 Notobody else is prepending the v. See also https://hub.docker.com/_/mongo/ or https://hub.docker.com/_/node/

**Comment by karalabe** [comment]
I personally would not like to maintain docker version tags. If @Arachnid accepts this burden then great. Alternatively we might extend `ci.go` to automatically do docker tags. But that's yet again something I personally don't want to undertake.

**Comment by Arachnid** [comment]
Versioned docker images are automatically built, but the last two builds failed due to a breaking change in `ci.go`, which has since been fixed.

Version numbers are tagged to match the branch they're in. We could drop the 'v', but given we've already started releasing versions with it, I'd need a compelling reason to dump it now.
