### ISSUE TITLE
Go binding any update ?

### ISSUE THREAD

**Issue by thejdavid** [ethereum/go-ethereum#3392]
is there any progress on the implementation of events in go ?

**Comment by karalabe** [comment]
There is, but it needs the push notification based subscription APIs to be properly implemented in the Go API first, otherwise it would just be polling and would be thrown out later anyway. There was an attempt previously but got a bit postponed due to the attacks and whatnot. @fjl is working on finalizing the non-event Go API stuff, and we'll focus on getting the events out right afterwards.

**Comment by alanchchen** [comment]
Hi @karalabe 
I'm also interested in go binding
What work should be done to complete this?
Could you explain it in more detail?  
Thanks :)

**Comment by murrekatt** [comment]
@karalabe @fjl can you give some kind of rough estimate when we could expect to have subscriptions as well as events?

**Comment by karalabe** [comment]
The new event/subscription system was merged in a few weeks ago. The work was mostly blocked until now because we didn't want to hack something in that gets dumped afterwards. I'll have to finish some log porting for the Geth 1.6 release, but will look into picking this up after Geth 1.6.0 is released.

**Comment by paultiplady** [comment]
This is now in master -- PR with docs here: https://github.com/ethereum/go-ethereum/pull/15832

**Comment by karalabe** [comment]
I hope I'll find the time to properly update the docs (or get a technical writer onboard actually :D).
