### ISSUE TITLE
JSON-RPC problem. Failed to connect to http://127.0.0.1:8545

### ISSUE THREAD

**Issue by FlyDazed** [ethereum/go-ethereum#3571]
Cannot start mining. 
Gives out a mistake:

```
JSON-RPC problem. Probably couldn't connect. Retrying in 1...
miner  04:52:33.939|main  Getting work package...
  X  04:52:35.144|main  Failed to submit hashrate.
  X  04:52:35.145|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error: 7 -> Could not connect to http://127.0.0.1:8545
```

Info:
Geth version: ethminer version 1.2.9
Build: Windows/msvc/Interpreter/RelWithDebInfo

Windows 10 Build 14393

**Comment by karalabe** [comment]
Geth does not open it's HTTP interface by default since it is potentially dangerous. If ethminer does not support communicating via IPC channels, you may open Geth's HTTP RPC interface by specifying `--rpc` on the command line. Please make sure that you do **not** expose your HTTP interface publicly to external machines, by default Geth only opens it for `localhost`.

**Comment by ramusbucket** [comment]
@karalabe, I'm note sure how to run - `ethminer -F ethereumpool.co/?miner=10@0x<address> --farm-recheck 200` with `geth --rpc`. Any advice?
