### ISSUE TITLE
Minimize mining times for private blockchain

### ISSUE THREAD

**Issue by forik** [ethereum/go-ethereum#3586]
I need to set up miners on a private blockchain to mine blocks as fast as possible.

I have compiled a geth client with a constant value of difficulty (func CalcDifficulty(...) to always return big.NewInt(1)) but seems that mining complexity still grows. What directions should I look into to achieve the goal? Thanks

**Comment by karalabe** [comment]
It generally doesn't make much sense to mine as fast as possible, since if there aren't transactions, it will just create a huge empty blockchain. A better approach would be to mine only when there are transactions, and stop otherwise. There's a proposal from me that supports this, while also always striving towards lowering the difficulty (i.e. making blocks easy to mine when needed).

https://github.com/ethereum/go-ethereum/pull/3478

**Comment by forik** [comment]
Yeah, seems like I had misunderstanding of a mining concept - I thought it normally happen only when there are pending transactions.  I'll follow your PR. 
Btw, @karalabe based on your reply, does that mean that setting difficulty to a static value makes more harm rather than benefits?

**Comment by konradkonrad** [comment]
> It generally doesn't make much sense to mine as fast as possible, since if there aren't transactions, it will just create a huge empty blockchain.

It depends :) In raiden (or similar projects) you may have block number dependent timeouts. In our (raiden) CI we make use of `geth`. While we can start the chain with a very low difficulty, we would like to be able to manipulate the block time (adjustment) for our tests in order to speed up CI.

**Comment by karalabe** [comment]
Hmmm, for internal contract tests we use a [chain simulator](https://godoc.org/github.com/ethereum/go-ethereum/accounts/abi/bind/backends). It's pretty crude, but it works for simple and short Go tests. Perhaps it would be nice to surface it (or something similar) into an RPC API to allow unit testing via a full blown Geth instance.

**Comment by sharif2008** [comment]
Hopefully there is a solution. any ideas?
