### ISSUE TITLE
contracts/release/release.go:134] Failed to retrieve current release

### ISSUE THREAD

**Issue by awesomehimanshu** [ethereum/go-ethereum#3597]
#### System information

Geth version: `geth version` 1.5.4
OS & Version: ubuntu 14.04

I am working on private ethereum with 2 node peer each other .
I have run a script which created contract 2 contract per second and it workes fine . But it crush in middle says error . Can you tell me for what this error come ?

contracts/release/release.go:134] Failed to retrieve current release

**Comment by karalabe** [comment]
That line is the release oracle Geth uses to periodically check whether there's a new version available or not. The releases are pushed into a smart contract on the blockchain, and it tried to retrieve the data from there. The warning simply means that the contract cannot be found (since you're running a private chain). 

Odd that it's enabled at all for non mainnet. Should't be. Though there's no harm in it.

**Comment by fzzr-** [comment]
I have same error on the latest stable geth in the mainnet. O_o
