### ISSUE TITLE
crash while generating DAG: `unexpected signal during runtime execution`

### ISSUE THREAD

**Issue by SCBuergel** [ethereum/go-ethereum#3628]
#### System information

Geth version: Version: 1.5.5-unstable
OS & Version: Ubuntu 16.04x64

#### Expected behaviour
Geth should just run fine.

#### Actual behaviour
Geth crashed at some point randomly while generating DAG while running for a few days in a private testnet.

#### Steps to reproduce the behaviour
I ran the following script for some days before it seems to randomly crash:
```
geth --nodiscover --maxpeers 0 --datadir "./chainData" --targetgaslimit "123123123" --mine --minerthreads=1 --rpc --rpcapi "eth,net,web3,personal" --rpccorsdomain "*" --rpcaddr "0.0.0.0" --unlock 0xddba7cdc7601cf0b5f11de7cb8aaee66320e2972 --password /dev/null
```

**Comment by dbblackdiamond** [comment]
@SCBuergel : we used to have the same issue on our private chain and it turned out to be a memory issue. Geth was running out of memory during the DAG generation process at random time and would just crash. I increased the virtual memory on my nodes by increasing the swap space and it has been fine since. Try it out and see how it works for you.

**Comment by SCBuergel** [comment]
Thanks @dbblackdiamond, how big a swap file did you give it? ATM, I have 3.5GB memory in total but no swap file at all (default cloud machine).

**Comment by dbblackdiamond** [comment]
@SCBuergel : I have 16GB of RAM on my nodes and I created a 32GB swap partition. My nodes are starting with a `--cache=4096` value. From what I can see though, my nodes are barely using any swap, so I would think that for your installation, using 4GB of swap should probably be sufficient. Give that a try and see if you still have the issue.

**Comment by karalabe** [comment]
@SCBuergel 3.5GB memory in total is a bit pushing it for mining. The first DAG is about 1GB in size. Couple that with Go's garbage collector strategy to only run when at least as much memory is allocated that the previous sweep left, and you're at 2GB memory requirement already, and we haven't even talked about how much Geth uses for it's normal operation. I'm not sure exactly what happens during epoch transitions when a new DAG is generated but the old is still available, but I can imagine that being a problematic transition, since it possibly doubles the memory needed for the DAG for a short time span.

@dbblackdiamond 4GB memory for the database cache may be a bit much, since the more live memory, the higher the burden on the garbage collector (should be a lot better with Go 1.8 though). Not saying that you should use less, just that it might worth a check to see how it would perform :)

**Comment by SCBuergel** [comment]
@karalabe thanks for the explanation. It would be advantageous to have a more meaningful crash report than [this lengthy crash output](https://gist.github.com/SCBuergel/8018cc902efb76bd1edf4e287d62109f) that geth currently produces though. It takes people a while to figure that this is a memory issue.

@dbblackdiamond so far running ok with 4GB swap file.

**Comment by karalabe** [comment]
Unfortunately this isn't generated by Go. We are using the C++ ethash implementation and if that code crashes, it is beyond the capacity of Go to recover from it to even print a decent error message. Go would have output a nice error message explicitly stating it it out of memory if it were to happen within Go code, but in this case C++ code crashes and takes the entire process down with it.

**Comment by karalabe** [comment]
Would have been nice to reimplement ethash in Go, alas there's little benefit, especially with plans being to transition to PoS.

**Comment by SCBuergel** [comment]
Interesting insight @karalabe. Ok I will open if this is re-appearing for other reasons.
