### ISSUE TITLE
About find private network peers

### ISSUE THREAD

**Issue by EasonWang01** [ethereum/go-ethereum#3676]
#### System information

Geth version: `1.5.8-stable`
OS & Version: OSX

#### Expected behaviour

I start my two peers like this
```
geth  --ipcdisable --rpc --rpcport 8104 --datadir "./privatechain/01" --networkid 123 --rpcapi="db,eth,net,web3,personal" --port=30310 console

and


geth  --ipcdisable --rpc --rpcport 8105 --datadir "./privatechain/02" --networkid 123 --rpcapi="db,eth,net,web3,personal" --port=30311 console
```

If I don't manual `admin.addPeer()` they can't find each other but I'm not setting the ` --nodiscover`,why they can't automatically find each other?
But rather than finding each other surprisingly they can find someone stranger.why?

my genesis.json is the same when init.

#### Backtrace

````
[backtrace]
````

**Comment by bas-vk** [comment]
In that case geth uses the predefined bootnodes that are not really useful for your private network. If you want the nodes in your multi node cluster to find each other I would recommend setting up your own bootnode and instruct your geth nodes to use that instead of the predefined ones.

Instructions can be found [here](https://github.com/ethereum/go-ethereum/wiki/Setting-up-private-network-or-local-cluster#private-network).

**Comment by EasonWang01** [comment]
thank,but if the Dapp running on the same server as IPC or RPC should we prefer to using IPC for security concern?
