### ISSUE TITLE
Download page has a breakdown?

### ISSUE THREAD

**Issue by ShawnyXiao** [ethereum/go-ethereum#3712]
Download page can't get bnaries and mobile libraries. Snapshot is as follow.

![image](https://cloud.githubusercontent.com/assets/9656978/23339146/ba52518e-fc56-11e6-87a4-b9c1aa0fa1f7.png)

**Comment by karalabe** [comment]
Works for me now. Could you check again? How long before this error appears?

**Comment by ShawnyXiao** [comment]
Still can't work for me now. It is always loading and then pop a prompt "Failed to load latest release!", even if I switch my browser from Chrome to Edge. The whole page is like this: 

![image](https://cloud.githubusercontent.com/assets/9656978/23393508/3ae23a0e-fdbe-11e6-88de-589b7fcf9f89.png)

**Comment by karalabe** [comment]
That is odd. Are you by any chance blocking GitHub? As I see it from the image above, you managed to correctly retrieve the packages from our Azure storage, just the "latest release" is missing, which is pulled from the GitHub APIs.

Please check whether you can access https://api.github.com/repos/ethereum/go-ethereum/releases/latest

**Comment by ShawnyXiao** [comment]
When I access [https://api.github.com/repos/ethereum/go-ethereum/releases/latest](https://api.github.com/repos/ethereum/go-ethereum/releases/latest), I can get a JSON like:

```json
{
  "url": "https://api.github.com/repos/ethereum/go-ethereum/releases/5433399",
  "assets_url": "https://api.github.com/repos/ethereum/go-ethereum/releases/5433399/assets",
  "upload_url": "https://uploads.github.com/repos/ethereum/go-ethereum/releases/5433399/assets{?name,label}",
  "html_url": "https://github.com/ethereum/go-ethereum/releases/tag/v1.5.9",
  "id": 5433399,
  "tag_name": "v1.5.9",
  "target_commitish": "release/1.5",
  "name": "Davy Jones' Locker (v1.5.9)",
  "draft": false,
  "author": {
    "login": "karalabe",
    "id": 129561,
    "avatar_url": "https://avatars.githubusercontent.com/u/129561?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/karalabe",
    "html_url": "https://github.com/karalabe",
    "followers_url": "https://api.github.com/users/karalabe/followers",
    "following_url": "https://api.github.com/users/karalabe/following{/other_user}",
    "gists_url": "https://api.github.com/users/karalabe/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/karalabe/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/karalabe/subscriptions",
    "organizations_url": "https://api.github.com/users/karalabe/orgs",
    "repos_url": "https://api.github.com/users/karalabe/repos",
    "events_url": "https://api.github.com/users/karalabe/events{/privacy}",
    "received_events_url": "https://api.github.com/users/karalabe/received_events",
    "type": "User",
    "site_admin": false
  },
  "prerelease": false,
  "created_at": "2017-02-13T16:54:59Z",
  "published_at": "2017-02-13T17:30:50Z",
  "assets": [

  ],
  "tarball_url": "https://api.github.com/repos/ethereum/go-ethereum/tarball/v1.5.9",
  "zipball_url": "https://api.github.com/repos/ethereum/go-ethereum/zipball/v1.5.9",
  "body": "*\"Roses are red, Violets are blue, Geth now supports Hardware wallets too!\"*\r\n\r\nGeth v1.5.9 is a feature release working towards hardware and HD (hierarchical deterministic) wallets. The first step consists of support for the *Ledger Nano S* and *Ledger Blue (USB only)* HD hardware wallets (https://github.com/ethereum/go-ethereum/pull/3592), also laying the groundwork for supporting subsequent hardware and software HD wallets.\r\n\r\nOther notable changes:\r\n\r\n * Genesis JSON additions and polishes for black box testing https://github.com/ethereum/go-ethereum/pull/3635, https://github.com/ethereum/go-ethereum/pull/3656\r\n * Split off Android builds into Linux build jobs https://github.com/ethereum/go-ethereum/pull/3662\r\n * Swarm manifest manipulation commands https://github.com/ethereum/go-ethereum/pull/3645\r\n * Slim down versioned Alpine Docker images https://github.com/ethereum/go-ethereum/pull/3670\r\n\r\nBugfixes:\r\n\r\n * Fix data race in transaction pool nonce retrieval https://github.com/ethereum/go-ethereum/pull/3625\r\n * Support swarm in-process restarts https://github.com/ethereum/go-ethereum/pull/3651\r\n * Fix `abigen` contract parsing for `solc` v1.4.8+ https://github.com/ethereum/go-ethereum/pull/3648\r\n * Fix shutdown issue for swarm running in a docker container https://github.com/ethereum/go-ethereum/pull/3649\r\n\r\nFor a full rundown, please see the [v1.5.9 milestone](https://github.com/ethereum/go-ethereum/milestone/46?closed=1).\r\n\r\n**Binaries and mobile libraries are available on our [download page](https://geth.ethereum.org/downloads/)**.\r\n\r\n### Ledger ProTips\r\n\r\n * Signing EIP155 transactions requires at least v1.0.3 of the Ethereum app on the Ledger.\r\n   * You may sign non-EIP155 transactions using the `go-ethereum` library directly.\r\n * Contract interactions or deploys need to enable `Contract data` from the Ethereum app `Settings`.\r\n * `Browser support` needs to be turned off from the Ethereum app `Settings` (different protocol).\r\n * Windows support requires a USB driver (official Red Hat): https://github.com/daynix/UsbDk/releases\r\n    * May be bundled into our installer later, we're curious how well it holds up in the wild first.\r\n * Linux support might require [granting the user write access](http://support.ledgerwallet.com/knowledge_base/topics/ledger-wallet-is-not-recognized-on-linux) to the Ledger \r\n * Accounts are automatically derived, searching for non zero balance or non zero nonce.\r\n    * First empty account is always listed (sending it funds will derive the next empty account).\r\n * Mist doesn't know about Ledger, if asked for a password, enter empty and confirm tx on device.\r\n * If in doubt, unplug and replug :P \r\n\r\n### Go API changes\r\n\r\n*Just to emphasize, the section below is about the Go API (i.e. `go-ethereum` library) changes. The RPC did not incur any backwards incompatible changes. If you do find something, it's a bug, please report it.*\r\n\r\nUntil now the `go-ethereum` codebase assumed that accounts are equivalent to individual private keys stored on disk inside a keystore. To support hardware and HD wallets however, this invariant breaks, requiring a new API with different constructs and mechanisms. We've tried our best to introduce this new API in such a way that it's trivial to transition to it for anyone already using `go-ethereum` as a library from Go or Java/ObjC/Swift.\r\n\r\nThe first breaking change is that while previously the `accounts.Manager` (or `AccountManager` on mobile) was a glorified keystore, now it changed its scope to handle `Wallet` objects, which may contain multiple accounts, as well as may be backed by different backends (keystore or hardware). The previous keystore is kept intact, just renamed to `Keystore` within the `keystore` package (arguably a better name and location). If you used the account manager in your own code, a simple swap to the keystore should more or less just work™.\r\n\r\nThe other breaking change you need to be aware of is that while previously transaction signing in the keystore only required a hash of the transaction, the new code requires the entire transaction object. This is needed to support hardware wallets which require the transaction details for user confirmation UI elements."
}
```

**Comment by karalabe** [comment]
Could you check your browser's JavaScript console for any error messages?

**Comment by ShawnyXiao** [comment]
So strange! I can access the download page now. Maybe it's a random event...

And there is no error messages on browser console.

Thank u~

**Comment by karalabe** [comment]
Great :)

**Comment by srharry** [comment]
i have the same error, cannot retrieve package, even on chrome and fierfox.
![geth_error](https://user-images.githubusercontent.com/7199702/33352482-06949c5a-d4a1-11e7-8cb1-c7cc2710a8af.jpg)

when i access  https://api.github.com/repos/ethereum/go-ethereum/releases/latest i got something like this : 

{
  "url": "https://api.github.com/repos/ethereum/go-ethereum/releases/8600241",
  "assets_url": "https://api.github.com/repos/ethereum/go-ethereum/releases/8600241/assets",
  "upload_url": "https://uploads.github.com/repos/ethereum/go-ethereum/releases/8600241/assets{?name,label}",
  "html_url": "https://github.com/ethereum/go-ethereum/releases/tag/v1.7.3",
  "id": 8600241,
  "tag_name": "v1.7.3",
  "target_commitish": "release/1.7",
  "name": "Weir (v1.7.3)",
  "draft": false,
  "author": {
    "login": "karalabe",
    "id": 129561,
    "avatar_url": "https://avatars2.githubusercontent.com/u/129561?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/karalabe",
    "html_url": "https://github.com/karalabe",
    "followers_url": "https://api.github.com/users/karalabe/followers",
    "following_url": "https://api.github.com/users/karalabe/following{/other_user}",
    "gists_url": "https://api.github.com/users/karalabe/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/karalabe/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/karalabe/subscriptions",
    "organizations_url": "https://api.github.com/users/karalabe/orgs",
    "repos_url": "https://api.github.com/users/karalabe/repos",
    "events_url": "https://api.github.com/users/karalabe/events{/privacy}",
    "received_events_url": "https://api.github.com/users/karalabe/received_events",
    "type": "User",
    "site_admin": false
  },
  "prerelease": false,
  "created_at": "2017-11-21T09:54:19Z",
  "published_at": "2017-11-21T10:41:22Z",
  "assets": [

  ],
  "tarball_url": "https://api.github.com/repos/ethereum/go-ethereum/tarball/v1.7.3",
  "zipball_url": "https://api.github.com/repos/ethereum/go-ethereum/zipball/v1.7.3",
  "body": "Geth v1.7.3 ([Weir](https://en.wikipedia.org/wiki/Weir)) is a maintenance release to address various issues in our previous releases, most importantly along log filtering and replacement transaction propagation. The release also contains a few developer niceties. **Please see compatibility section below!**\r\n\r\n**New features:**\r\n\r\n * Roll out v2 of the `les` light client protocol (https://github.com/ethereum/go-ethereum/pull/14970, https://github.com/ethereum/go-ethereum/pull/15367, https://github.com/ethereum/go-ethereum/pull/15391).\r\n * Insta-mining, zero CPU, clique based PoA developer mode `--dev` (https://github.com/ethereum/go-ethereum/pull/15323).\r\n * Add API endpoint to list modified accounts between two blocks (https://github.com/ethereum/go-ethereum/pull/15512).\r\n * Gas estimation returns error instead of maxgas if transaction cannot be executed (https://github.com/ethereum/go-ethereum/pull/15477).\r\n * Improve EVM jump destination analysis for worst case scenarios (https://github.com/ethereum/go-ethereum/pull/14582).\r\n * Enforce `application/json` for HTTP RPC requests (https://github.com/ethereum/go-ethereum/pull/15220, https://github.com/ethereum/go-ethereum/pull/15496).\r\n * Private network faucet support Facebook, Twitter and Google+ authentication (https://github.com/ethereum/go-ethereum/pull/15313).\r\n * Support encrypted SSH keys in the Puppeth network manager (https://github.com/ethereum/go-ethereum/pull/15443).\r\n * Introduce docker images containing all Ethereum tools (https://github.com/ethereum/go-ethereum/pull/15467).\r\n * Start shipping Ubuntu Artful Aardvark launchpad packages (https://github.com/ethereum/go-ethereum/pull/15344).\r\n\r\n**Squashed bugs:**\r\n\r\n * Fix log filtering when specifying non-8-multiple starting block number (https://github.com/ethereum/go-ethereum/pull/15489).\r\n * Fix replacement transaction propagation (https://github.com/ethereum/go-ethereum/pull/15343).\r\n * Reduce disk overhead on keystore startup (https://github.com/ethereum/go-ethereum/pull/15526, https://github.com/ethereum/go-ethereum/pull/15527, https://github.com/ethereum/go-ethereum/pull/15529).\r\n * Fix occasional Rinkeby chain split by additional fork selection logic (https://github.com/ethereum/go-ethereum/pull/15470).\r\n * Fix JavaScript tracing to permit working with `Address` types (https://github.com/ethereum/go-ethereum/pull/15297).\r\n * Fix missing commit hash in docker image versions (https://github.com/ethereum/go-ethereum/pull/15458, https://github.com/ethereum/go-ethereum/pull/15464).\r\n\r\n**Compatibility caveats:**\r\n\r\n * All HTTP RPC requests from now on need to have the `Content-Type: application/json` header set on them. Geth v1.7.3 will **refuse** to service requests with no content type headers set (or headers with different content types). This is a security measure to counter a browser CORS circumvention technique.\r\n * Geth v1.7.3 ships with `les/2` light client support, which might have harder time finding light servers initially until the server providers upgrade to v1.7.3 too.\r\n\r\nFor a full rundown of changes, please see the [v1.7.3](https://github.com/ethereum/go-ethereum/milestone/59?closed=1) milestone.\r\n\r\n**As always, binaries and mobile libraries are available on our [download page](https://geth.ethereum.org/downloads/)**."
}

**Comment by karalabe** [comment]
Could you please reload the page with your browser's developer tool open on the network tab? We're making one request to github and one to azure. Based on your screenshot, it seems to me that azure is blocked or doesn't load for some reason for you.

**Comment by srharry** [comment]
these are the screen capture network and console tab
![geth_error_networktab](https://user-images.githubusercontent.com/7199702/33374556-97f6b23e-d4fe-11e7-919b-63036e3afeea.jpg)
![geth_error2](https://user-images.githubusercontent.com/7199702/33374557-985c0bca-d4fe-11e7-88c1-79d2733b1cd2.jpg)

**Comment by srharry** [comment]
these are the screencapture network and console tab
![geth_error_networktab](https://user-images.githubusercontent.com/7199702/33376098-3b8acf5c-d504-11e7-9de2-b03058edbe43.jpg)

![geth_error_console](https://user-images.githubusercontent.com/7199702/33376085-32611cc4-d504-11e7-919a-d678d032392a.jpg)

**Comment by Tsunami02** [comment]
Even I am seeing the same error

`VM127:1 GET https://gethstore.blob.core.windows.net/builds?restype=container&comp=list net::ERR_CONNECTION_RESET
(anonymous) @ VM127:1
send @ jquery.min.js:4
ajax @ jquery.min.js:4
(anonymous) @ (index):308`

Anything particular you guys did to download these files? @ShawnyXiao @srharry 
I remember downloading the files without any issue just a week back but on a different PC.

**Comment by Tsunami02** [comment]
[https://gethstore.blob.core.windows.net/builds?restype=container&comp=list](url)
Does this return any error to you guys now? I see following:
![image](https://user-images.githubusercontent.com/8060569/34969366-8383991e-fa94-11e7-976b-5e35ec3a5c1a.png)

**Comment by WalterBoles** [comment]
So can see everything all in one spot

**Comment by humayuntanwar** [comment]
![getherror](https://user-images.githubusercontent.com/26435693/36658114-f9c1604e-1af0-11e8-9cd1-02904e74be09.png)
i m getting this error in chrome, in edge it works fine

**Comment by wdx7266** [comment]
I also met this problem, and found a available download address: https://github.com/EthFans/wiki/wiki/Ethereum-Geth-Mirror
It might be helpful, but I'm not sure the security of this dowload addresss.

**Comment by Pupin3** [comment]
Is this issue closed? How?
Because I do have the same error message with both Chrome and Mozilla although I have javascript enabled and I also disabled any add blockers....

Alternatively, can someone confirm that the mirror address wdx7266 suggested above contains the latest up to date version?

**Comment by Pupin3** [comment]
Ok after waiting a while it seems that the link is actually working....

However, I am surprised to see that latest geth version number is 1.8.13 whereas in the mirror site mentioned above version is already 1.8.3 
what am I missing here?

**Comment by dillonharlessNHRMC** [comment]
Anyone able to figure this out? 6 months later and users are still experiencing this issue...

**Comment by Retia-Adolf** [comment]
> Though probably not recommended, I used the dev console and selector tool to delete the notification and the page overlay.

Me too, but can't get md5 on the page in this way..

**Comment by Ashokrayal** [comment]
> Anyone able to figure this out? 6 months later and users are still experiencing this issue...
> 
> Though probably not recommended, I used the dev console and selector tool to delete the notification and the page overlay. Then I just downloaded the only version showing at the top. Here's to hoping it works for someone.

I have done the same :)

**Comment by sarbogast** [comment]
This issue is still present. How can something so critical be not fixed yet. I had to use Firefox to be able to download the Windows installer. Both Chrome and Edge gave me a "Failed to load releases" error message.

**Comment by tabsusanoo** [comment]
maybe the private mode of your browser can be helpful

**Comment by zjg555543** [comment]
> This issue is still present. How can something so critical be not fixed yet? I had to use **Firefox** to be able to download the Windows installer. Both Chrome and Edge gave me a "Failed to load releases" error message.

Thanks for @sarbogast

**Comment by AliWisam** [comment]
https://github.com/EthFans/wiki/wiki/Ethereum-Geth-Mirror

**Comment by beaver9953** [comment]
This issue is still there. I am failing to download using chrome or firefox. The mirror link suggested is returning the same error. Guys is there a solution to this, it's so frustrating!

**Comment by mohitrakhade20** [comment]
![image](https://user-images.githubusercontent.com/48031017/85190568-324f6c00-b2d7-11ea-896f-e33b4a082cdb.png)
somebody please help....

**Comment by freespiriter** [comment]
This issue is still present. can someone fix this problem

**Comment by mohitrakhade20** [comment]
Yes anybody knows about this issue ? plesase help

**Comment by monteiro74** [comment]
> Yes anybody knows about this issue ? plesase help

Retrieving packages from release server...
Thursday March 11, 2021
the site continues to have the same problem! It seems that they dont want to or dont know how to fix it!

**Comment by karalabe** [comment]
Check your borwsers network traffic. High chance you're firewalled off. The
files are hosted by Azure, so i dpubt they are offline.

**Comment by prashanta0234** [comment]
If you using a chrome browser,  hard reload your page with Hold down Ctrl (Control) + Shift and click R. it's working in my case.
