### ISSUE TITLE
When i create 50 new account in geth concurrently , the system get hang ? 

### ISSUE THREAD

**Issue by himanshuoodles** [ethereum/go-ethereum#3764]
#### System information

Geth version: `geth version` 1.5.7
OS & Version: Linux
Commit hash : (if `develop`)

Is there is any solution so that geth doesn't take to many of memory ?

#### Backtrace

````
[backtrace]
````

**Comment by holiman** [comment]
I'm curious, how do you go about creating 50 new accounts 'concurrently'? Using 50 paralell rpc-requests, or something else?

**Comment by himanshuoodles** [comment]
Yes I run Jmeter script 50 rpc call at a second.

**Comment by obscuren** [comment]
This is because of *Scrypt* to store the private key to disk, which takes `256MB` per call. This will, given enough coroutines, an OOM.

**Comment by himanshuoodles** [comment]
Why it is done 256 Mb . I have change it to 2 power 3 , Now also it is working fine . So what is benefit of it , to reduce DDoS attack  .

**Comment by obscuren** [comment]
Please use our light Scrypt option instead of modifying it yourself if you really **need** it (`--lightkdf`). For more information about `N` see [this](http://crypto.stackexchange.com/questions/35423/appropriate-scrypt-parameters-when-generating-an-scrypt-hash) explanation.

Closing this issue as it's a non-issue.

**Comment by obscuren** [comment]
Please note that `--lightkdf` is meant for memory constraint devices such as routers, RPi, etc. It's not meant as a fix for your "issue".

**Comment by himanshuoodles** [comment]
Thanks .
