### ISSUE TITLE
geth crashes on launch on OS X 10.12.x "Killed: 9"

### ISSUE THREAD

**Issue by davidvartan** [ethereum/go-ethereum#3792]
#### System information

Geth version: 

```
brew install ethereum
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
llvm@3.9

Warning: ethereum/ethereum/ethereum-1.5.9 already installed
```

OS & Version: OS X 10.12.3

Commit hash : N/A

#### Expected behaviour

Does not crash

#### Actual behaviour

Crashes (Killed: 9) regardless of the argument

#### Steps to reproduce the behaviour

```
brew tap ethereum/ethereum
brew install ethereum
geth
```
#### Backtrace

N/A

**Comment by nazilover** [comment]
Skip to content
This repository

    Pull requests
    Issues
    Gist

    @nazilover

471
3,327

    1,170

ethereum/go-ethereum
Code
Issues 278
Pull requests 42
Projects 4
Wiki
Pulse
Graphs
geth crashes on launch "Killed: 9" #3792
Open
davidvartan opened this Issue 8 days ago · 0 comments
Assignees
No one assigned
Labels
None yet
Projects
None yet
Milestone
No milestone
Notifications

You’re not receiving notifications from this thread.
1 participant
@davidvartan
@davidvartan
davidvartan commented 8 days ago • edited
System information

Geth version:

brew install ethereum
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
llvm@3.9

Warning: ethereum/ethereum/ethereum-1.5.9 already installed

OS & Version: OS X 10.12.3

Commit hash : N/A
Expected behaviour

Does not crash
Actual behaviour

Crashes (Killed: 9) regardless of the argument
Steps to reproduce the behaviour

brew tap ethereum/ethereum
brew install ethereum
geth

Backtrace

N/A
@nazilover

Attach files by dragging & dropping,

, or pasting from the clipboard.
Styling with Markdown is supported

    Contact GitHub API Training Shop Blog About 

    © 2017 GitHub, Inc. Terms Privacy Security Status Help

**Comment by georgekrasenov** [comment]
+1

**Comment by chihoko** [comment]
+1

**Comment by Asiron** [comment]
+1

**Comment by RenSilvaAU** [comment]
+ 1 

I tried building geth from Source too, and got the same error.

**Comment by mariolfi** [comment]
+1 same error here.

**Comment by obscuren** [comment]
Could you please update a crash log containing the back trace?

**Comment by skateryang** [comment]
+1

**Comment by fjl** [comment]
I get this too. There is no stack trace.

**Comment by fjl** [comment]
Please use --devel as a workaround. The underlying issue is a Go compiler incompatibility with the Xcode 8.3 linker that affects almost all Go programs  We will prepare a new stable release soon.

**Comment by mariolfi** [comment]
@fjl thanks for the help, I'm still getting the same error when I try geth --devel. Thoughts on how to solve it? Thanks!

**Comment by morriswong** [comment]
I am getting the same error here too, don't really know how to get around. Would appreciate someone pointing somewhere to start with.

**Comment by RenSilvaAU** [comment]
geth --devel 

... still gets the same result (Killed: 9)

tried uninstalling ethereum and installing again to no avail

**Comment by fjl** [comment]
> Please use --devel as a workaround. 

I meant: Please run `brew reinstall go-ethereum --devel` to get the unstable 1.6 release.

**Comment by nginnever** [comment]
thanks @fjl can confirm reinstalling with the developer branch with homebrew worked for here.

`brew reinstall ethereum --devel`

**Comment by RayTeon** [comment]
Had the same issue. Confirming unlinking stable version` brew unlink ethereum` and installing --devel via `brew install ethereum --devel `worked.

**Comment by ZWHe2016** [comment]
the order   # brew reinstall ethereum --devel is ok !thanks @fjl

**Comment by jjacquet** [comment]
`brew reinstall ethereum --devel` is not working OS X 10.12. The installation prints out a message stating no support. Could I install and mine if I use an older operating system? `geth: command not found`
