### ISSUE TITLE
Unlock account from other Node

### ISSUE THREAD

**Issue by EasonWang01** [ethereum/go-ethereum#3821]
If using `web3.setProvider(new web3.providers.HttpProvider('http://localhost:8104'));`

but the account was in another running node and want to unlock how to do it?

For example,A want to tranfer token to B using Dapp listening in PRC port 8104 but A need to unlock account first,but A account is belong to another node.

**Comment by joeb000** [comment]
Its a bad idea to have web3 provider nodes expose the `personal` rpc api. I think the solution you are looking for could be [metamask](https://metamask.io/) - it basically proxies a web3 provider to let users sign transactions in the browser (client side).

Alternatively and more manually, you could use the [ethereumtx-js](https://github.com/ethereumjs/ethereumjs-tx) package to sign transactions from your Dapp and post them raw to your web3 provider.

**Comment by nazilover** [comment]
Skip to content
This repository

    Pull requests
    Issues
    Gist

    @nazilover

471
3,327

    1,170

ethereum/go-ethereum
Code
Issues 278
Pull requests 42
Projects 4
Wiki
Pulse
Graphs
Unlock account from other Node #3821
Open
EasonWang01 opened this Issue 8 hours ago · 1 comment
Assignees
No one assigned
Labels
None yet
Projects
None yet
Milestone
No milestone
Notifications

You’re not receiving notifications from this thread.
2 participants
@EasonWang01
@joeb000
@EasonWang01
EasonWang01 commented 8 hours ago • edited

If using web3.setProvider(new web3.providers.HttpProvider('http://localhost:8104'));

but the account was in another running node and want to unlock how to do it?

For example,A want to tranfer token to B using Dapp listening in PRC port 8104 but A need to unlock account first,but A account is belong to another node.
@joeb000
joeb000 commented 2 hours ago

Its a bad idea to have web3 provider nodes expose the personal rpc api. I think the solution you are looking for could be metamask - it basically proxies a web3 provider to let users sign transactions in the browser (client side).

Alternatively and more manually, you could use the ethereumtx-js package to sign transactions from your Dapp and post them raw to your web3 provider.
@nazilover

Attach files by dragging & dropping,

, or pasting from the clipboard.
Styling with Markdown is supported

    Contact GitHub API Training Shop Blog About 

    © 2017 GitHub, Inc. Terms Privacy Security Status Help

**Comment by EasonWang01** [comment]
If the account private key is from different Nodes,how they using the same Dapp provide by one Node then sign the transaction?thanks for reply.

**Comment by joeb000** [comment]
Its hard to explain without knowing what your use case is, but all transactions in ethereum need to be sent from an account (key). The transaction will have many fields such as value, gas, data ect... All this data must be signed using the private key. Once it is signed, the transaction can be posted to the ethereum network where it will be propagated by peers, verified and executed (mined) by the miners, and included in the next block.

You might be getting hung up on the fact that when using the geth console, your transactions are signed by the unlocked account that is already known to the console. For many Dapps (like the ones that use metamask), you can't expect users to be running a full node with their accounts unlocked. In these cases, the Dapps must create the transaction object on the client side and also sign it with keys on the client side. Now that we have a raw transaction that has been signed on the users client side, all you need to do is post that raw transaction to any RPC enabled node where it will be propagated through the network. Metamask abstracts much of the pain of doing this - check out some of the example projects.

In the future, you may want to consider posting questions and issues like this to the [ethereum stack exchange](http://ethereum.stackexchange.com/) page since this isn't a bug in the client.

**Comment by EasonWang01** [comment]
The use case is eatablish a private network and using Dapp to control four geth Nodes,but `web3.setProvider(new web3.providers.HttpProvider('http://localhost:8104'))` only connect one Node,is it possible to connect mutiple node?That Dapp can show all account on the same network and unlock it.

the official tutorial can talk more about it,people don't need to ask basic question on stack exchange.

**Comment by joeb000** [comment]
So technically, its entirely possible to communicate with multiple nodes in a single app (not sure id call it a Dapp). If you are using nodejs and web3 you could code the 4 RPC urls into a config file and switch between them, setting the `web3.setProvider` function. You can't connect to more than one provider at a time but you could use some kind of Promise.then() daisy chain to make requests to each of them from a single function.

That said, I'm not sure why you would want to do that. You only really need one blockchain connected node to interact with the network. And again, this is not a bug/issue with geth so im not sure go-ethereum github is the appropriate forum for Dapp level support.

**Comment by EasonWang01** [comment]
thanks for reply.

**Comment by EasonWang01** [comment]
thanks for reply.
