### ISSUE TITLE
p2p hangs on ^C when network is down

### ISSUE THREAD

**Issue by zelig** [ethereum/go-ethereum#428]
it seems when network is down, the cli hangs on ^C 
here is the output of loglevel 5 and produced by kill -QUIT 
https://gist.github.com/zelig/d9d32fdb3feb87defbd9

it gets stuck on ethereum.Start -> discover.ListenUDP

wonder if it'd be worth putting an interrupt handler somewhere here
https://github.com/ethereum/go-ethereum/blob/poc-9/p2p/discover/udp.go#L149
or here:
https://github.com/ethereum/go-ethereum/blob/poc-9/p2p/nat/nat.go#L228

**Comment by fjl** [comment]
It should not hang for very long. The timeout for NAT autodiscovery is about 2 seconds.

**Comment by fjl** [comment]
Anyway, I see the bug now. What seems to happen is that the first `wait` reads from the `done` channel and stores the discovered `nat.Interface` in `n.found`. The second (concurrent) `wait` checks before it is stored and waits as well. We can probably just put the lock around the whole thing instead of taking it twice.

**Comment by zelig** [comment]
@fjl  is this fixed?

**Comment by fjl** [comment]
Can you try again? I was never really able to reproduce this, but didn't do anything about it either.

**Comment by fjl** [comment]
I will try adding a test for it.

**Comment by fjl** [comment]
Fixed in #960.
