### ISSUE TITLE
Installing geth

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/go-ethereum#583]
I've followed the [building instruction for Mac OS X](https://github.com/ethereum/go-ethereum/wiki/Building-Instructions-for-Mac), and got `ethereum` going.

I now want to try the [JavaScript console](https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console). Sadly, `geth console` outputs

```
-bash: geth: command not found
```

and `ethereum console` outputs

```
[CLI] resource temporarily unavailable
```

What gives?

**Comment by bas-vk** [comment]
Ethereum is renamed to geth very recently. Since your are able to run ethereum I believe you are on the wrong branch, not up to date or running a previous build version of ethereum which is somewhere in your path. Pull the latest sources, checkout the develop branch and build cmd/geth. If you already have the geth binary its probably not in your PATH. A `go install` may help with that depending on your configuration.

The second output might be caused by running the ethereum application multiple times. Stop all running ethereum/geth processes and then start one console instance. You can pass additional arguments and use the javascript console to have a limited administration console.

**Comment by JustinDrake** [comment]
So we have different names across the repository. This seems pretty poor.

Anyway, I've stopped all `ethereum` processes, and `ethereum console` now outputs:

```
[CLI] open console: no such file or directory
```

What's up with this new error?

I didn't realise how far from production Ethereum actually is.

**Comment by zelig** [comment]
well, already one step closer with your kind help.
so what you are saying is:
- [ ] improve documentation stressing that the wiki pages are about the development branch.
- [ ] start a trouble shooting page with funny errors like this
- [ ] improve error message for `[CLI] resource temporarily unavailable
`

**Comment by JustinDrake** [comment]
@zelig: Good summary. Also add "improve error message for `[CLI] open console: no such file or directory`". I have no idea what this mean in the context of `ethereum console`.

**Comment by obscuren** [comment]
Thanks @JustinDrake. `geth` will soon be on the master branch as well.

@zelig Don't bother about mentioning develop in documentation. This will soon be obsolete

**Comment by zelig** [comment]
if you devtype living on the edge follow https://github.com/ethereum/go-ethereum/wiki/Developers%27-Guide
otherwise on MacOS you got brew: `brew install ethereum --devel --build-from-source`

**Comment by kristianmandrup** [comment]
Is this still the case? I installed Ethereum Wallet and Mist from MacOSX `.dmg` files.
When I went to the [Readme](https://github.com/ethereum/go-ethereum) I'm told there are distributions, but when I click it downloads `Mist.dmg` which I already installed... Very confusing!
Please make it more clear in the docs. Too many name changes and inconsistent recipes...
