### ISSUE TITLE
Geth build error on OSX

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/go-ethereum#659]
Ok, so I installed `go`, then

```
mkdir $HOME/go
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
go get github.com/tools/godep
go get github.com/ethereum/go-ethereum/cmd/geth
```

This last command resulted in the following error message:

```
package github.com/ethereum/go-ethereum/cmd/geth
	imports github.com/ethereum/go-ethereum/cmd/geth
	imports github.com/ethereum/go-ethereum/cmd/geth: cannot find package "github.com/ethereum/go-ethereum/cmd/geth" in any of:
	/usr/local/go/src/github.com/ethereum/go-ethereum/cmd/geth (from $GOROOT)
	/Users/justin/go/src/github.com/ethereum/go-ethereum/cmd/geth (from $GOPATH)
```

What's up?

**Comment by maran** [comment]
Geth is not merged into the master branch yet. I recommend you checkout the develop branch and use godep go install to install it.

**Comment by obscuren** [comment]
As discussed [here](https://github.com/ethereum/go-ethereum/issues/583) `geth` isn't part of master yet. If you'd like to build from source (I'll put up a wiki page for this as well) you need to `git checkout develop && cd cmd/geth`. Now the tricky part is building because since you're building from `develop` you need to install all deps manually (it isn't so hard, just requires manual labour). The following step will fail but you need to do this first in order to get the list of deps: `godep go install`. You'll now see a bunch of error about a dependency not being installed. What you'll have to do is `go get <dependency>` for each that is missing. Once you've installed the deps do a `godep go install` again and it will install `geth`.

If that doesn't work, let me know.

**Comment by JustinDrake** [comment]
@obscuren: Ok, so I'm at the point where I need to install the dependencies (note: I'm not familiar with `go`). So, the first dependency `godep go install` complains about is:

```
../../Godeps/_workspace/src/github.com/ethereum/ethash/ethash.go:34:2: cannot find package "github.com/ethereum/go-ethereum/common" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/github.com/ethereum/go-ethereum/common (from $GOROOT)
	/Users/justin/Desktop/go-ethereum/Godeps/_workspace/src/github.com/ethereum/go-ethereum/common (from $GOPATH)
	/Users/justin/go/src/github.com/ethereum/go-ethereum/common
```

which seems to be a dependency called `common`. So I've tried `go get common`, and `go get github.com/ethereum/go-ethereum/common`; both didn't work. Could you provide more details about installing the dependencies?

**Comment by obscuren** [comment]
What's the working directory you're attempting this from?

**Comment by JustinDrake** [comment]
`cmd/geth`, as you recommended.

**Comment by fjl** [comment]
You get this error because you have no `GOPATH` set. 
Assuming you have cloned go-ethereum to `/a/b/c/d/src/github.com/ethereum/go-ethereum` you need to set `GOPATH` to `/a/b/c/d` before running `godep go install`.

**Comment by fjl** [comment]
I am considering adding a build script so non-gophers don't need to care about `GOPATH`. The Go workspace concept is very useful, but most people just want to build the software and don't care about setting up a Go development environment.

**Comment by caktux** [comment]
`brew install ethereum --devel --build-from-source`

**Comment by JustinDrake** [comment]
@caktux: That seemed to work. Thanks!
