### ISSUE TITLE
ERROR: Incorrect Total Difficulty

### ISSUE THREAD

**Issue by simenfd** [ethereum/go-ethereum#706]
I get a lot of "ERROR: Incorrect Total Difficulty" after recompiling the latest version on linux
(commit: 1fa844aa). Every block received creates this message... I believe this might disappear if I delete .ethereum/

I submit this FYI.

I0413 19:29:59.693187   13361 backend.go:183] Protocol Version: 60, Network Id: 0
I0413 19:29:59.693248   13361 backend.go:193] Blockchain DB Version: 1
I0413 19:29:59.694546   13361 chain_manager.go:186] Last block (#90176) 9a346f8ccb15f83de4f297c1709f8e15e98154a696bfd994047d3a892ea44a99 TD=239597588340
I0413 19:30:00.573348   13361 ethash.go:94] Making cache
I0413 19:30:01.841700   13361 ethash.go:99] Took: 1.268275564s
I0413 19:30:01.849193   13361 cmd.go:116] Starting  Geth/v0.9.9/linux/go1.4.2
I0413 19:30:01.849303   13361 server.go:170] Starting Server
I0413 19:30:01.852512   13361 udp.go:157] Listening, enode://0422c0381b41f85b84ecbfaacb832c7c00f2c80a07b8b444867b64b1ae8b720f14584ae688b7a475528d0f5e0758718bedc0ed24e0897893103c050ee5f39e77@84.209.71.211:30303
I0413 19:30:01.852603   13361 blockpool.go:276] Blockpool started
I0413 19:30:01.852618   13361 whisper.go:75] Whisper started
I0413 19:30:01.852638   13361 backend.go:396] Server started
I0413 19:30:01.852687   13361 server.go:286] Listening on [::]:30303
I0413 19:30:10.614995   13361 errors.go:82] [ETH] ERROR: NetworkId mismatch: 99107 (!= 0)
I0413 19:30:13.409319   13361 chain_manager.go:548] imported 4 block(s) 0 queued in 25.649576ms. #90180 [e9138445 / 3f39480a]
I0413 19:30:13.409456   13361 errors.go:82] [Blockpool] ERROR: Incorrect Total Difficulty: on block 3f39480a75a07af4e3169b0ed396e72eae7fddf5e770119b61e7cecadc79c311 peer td 249199161275 =?= block td 239624647985

**Comment by obscuren** [comment]
It's fine. You may safely ignore it :-)

**Comment by zelig** [comment]
People were asking so here you go.a few nodes on the test net advertise incorrect high total difficulty for their head block. We never follow them as best peers otherwise we risk lagging behind if they are slow or even get stuck on a bad fork if they decide to start mining on their high td block. 

If the offending node is malicious this can be called a chain hijacking attack which has a lucrative potential if 51 percent runs the naive client. 

So it is quite important to detect incorrectly advertised td and deal with offending peers. 

For now we don't kick them out cos we know its some well meaning client with a problem and also given our small network we opportunistically harness them to provide their valid blocks. 
These pre frontier days of lenience are soon over though.

That said they should be suspended (prevent them from gaining best peer status for a set period of suspension or the duration of the connection (whichever is longer).

See also #604


















-------- Original message --------
