### ISSUE TITLE
Add new error codes according to new spec

### ISSUE THREAD

**Issue by frozeman** [ethereum/go-ethereum#768]
Not sure if we want to have this in before frontier release, though.
I will increase that list if i come across cases where we need more explicit errors.

Please implement according to: https://github.com/ethereum/wiki/wiki/JSON-RPC-Error-Codes-Improvement-Proposal
- [ ] SendTransaction when account is locked -> code: 1 Unauthorized
- [ ] SendTransaction when confirmation window is waiting user input -> code: 2 Action not allowed
- [ ] SendTransaction gas to low -> code: 3 Execution error, Reason -> 102 `GAS` to low
- [ ] SendTransaction gas limit exceeded -> code: 3 Execution error, Reason -> 103 `GAS` limit exceeded
- ...

**Comment by zelig** [comment]
sorry for maybe polluting this issue, but could you look at these 2 pending (?) RPC issues:

- [ ] gav: additional RPC: eth_latestConfirmedHash() -> returns string of hash. (not sure what this is, investigate)
- [ ] RPC sendTransaction: Known transaction #662  - manage nonce automatically (maybe fixed by https://github.com/ethereum/go-ethereum/pull/760)

**Comment by zelig** [comment]
sry accidentally closed with comment

**Comment by frozeman** [comment]
- `eth_latestConfirmedHash` is not part of the RPC specs, i never heard of it.
-  sendTransaction: Known transaction. would be definitely an interesting error we should probably add. Could somebody explain if thats intended behaviour preventing twice the same transaction?
