### ISSUE TITLE
Mining freezes docker container

### ISSUE THREAD

**Issue by anthony-cros** [ethereum/go-ethereum#860]
Maybe related or a duplicate of https://github.com/ethereum/go-ethereum/issues/844

I create a docker container based on ubuntu, then run avsa's instructions from https://docs.google.com/document/d/1fupguDpg-pB-EfBE7yqPEAtYQzXOo8iTd8rzIVggCs0/edit#heading=h.wksardrvnyc0 and eventually the geth command exits. From that point on the terminal is messed up (does not display commands properly), and the container usually freezes shortly after. For instance, trying to look into the log, the session freezes inside the "less" command. Here's the most of the log I was able to recover (at the very bottom of the log file):

EDIT: I was able to recover the log file eventually: https://gist.github.com/anthony-cros/01ed1d155ed302183795

**Comment by tgerring** [comment]
The error was `fatal error: runtime: out of memory` at the end of DAG generation.

Since this was for a relatively old version (0.9.15 vs 0.9.22 today), can you re-run this with an updated docker container, ensuring it has at least 2GB memory? DAG should be about 1GB right now in addition to whatever geth consumes.

**Comment by fjl** [comment]
Ethash has been rewritten to use mmap. This particular issue won't happen again.
