### ISSUE TITLE
Fatal: Could not create the account: encoding/hex: invalid byte: U+007B '{'

### ISSUE THREAD

**Issue by avdoshyn** [ethereum/go-ethereum#901]
Fatal: Could not create the account: encoding/hex: invalid byte: U+007B '{'

**Comment by avdoshyn** [comment]
http://prntscr.com/73m6w3

**Comment by tgerring** [comment]
From the screenshot, it looks like you're trying to use `geth account import` to import the presale wallet JSON. I don't believe this is the correct way to import the JSON file, since on https://github.com/ethereum/go-ethereum/wiki/Managing-your-accounts#creating-an-account-by-importing-a-private-key it mentions "The keyfile is assumed to contain an unencrypted private key as canonical EC raw bytes encoded into hex."

**Comment by tgerring** [comment]
According to https://github.com/ethereum/go-ethereum/wiki/Backup-&-restore the proper syntax for importing the presale wallet is `geth wallet import /path/to/my/etherwallet.json`.

The screenshot shows that `account` was used instead of `wallet`. Can you try with `wallet` and see if the error persists?

**Comment by obscuren** [comment]
@avdoshyn have you tried @tgerring suggestion? Please re-open this issue if you keep having issues.

**Comment by avdoshyn** [comment]
it works thnx

**Comment by nitinsurana** [comment]
Using `geth wallet import keystorejsonfile`, then it asks for passphrase. After entering the passphrase it throws the following error -
```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/ethereum/go-ethereum/accounts/keystore.decryptPreSaleKey(0xc420460c00, 0x1e9, 0x3e9, 0xc4200134b0, 0x9, 0x47dbc72, 0xc420240320, 0x0)
	/private/tmp/ethereum-20170611-53055-1bjmq4j/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/keystore/presale.go:61 +0x62a
github.com/ethereum/go-ethereum/accounts/keystore.importPreSaleKey(0x508d580, 0xc4204400c0, 0xc420460c00, 0x1e9, 0x3e9, 0xc4200134b0, 0x9, 0x0, 0x0, 0x0, ...)
	/private/tmp/ethereum-20170611-53055-1bjmq4j/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/keystore/presale.go:36 +0xa2
github.com/ethereum/go-ethereum/accounts/keystore.(*KeyStore).ImportPreSaleKey(0xc4200b0000, 0xc420460c00, 0x1e9, 0x3e9, 0xc4200134b0, 0x9, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/ethereum-20170611-53055-1bjmq4j/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore.go:478 +0xbb
main.importWallet(0xc420399180, 0x4a99a3c, 0x8)
```
Looks like a regression issue.
